---
title: 'New journal paper: <em>A Formal Concept Analysis Approach to Cooperative Conversational
  Recommendation</em>'
author:
- Pablo Cordero
- Manuel Enciso
- Ángel Mora
- Manuel Ojeda-Aciego
- Carlos Rossi
date: '2020-08-19T00:00:00Z'
categories:
- Formal concept analysis
- Recommendation system
- Simplification logic
---

The work <u>A Formal Concept Analysis Approach to Cooperative Conversational Recommendation</u> has been published in <em><em>International Journal of Computational Intelligence Systems</em>, 13 (1), pp. 1243 - 1252</em>.

<u>Abstract</u>:


We focus on the development of a method to guide the choice of a set of users in an environment where the number of features describing the items is high and user interaction becomes laborious. Using the framework of formal concept analysis, particularly the notion of implication between attributes, we propose a method strongly based on logic which allows to manage the users' preferences by following a conversational paradigm. Concerning complexity, to build the conversation and provide updated information based on the users' previous actions (choices) the method has polynomial delay.



For more details on this work, visit <a href='/publications/journals/2020-ijcis'>its own page</a>.
