---
author:
- Ezequiel López-Rubio
- Juan Miguel Ortiz-de-Lazcano-Lobato
- Domingo López-Rodríguez
Status: Published
date: '2009-08-19'
slug: 2009-ieee
title: Probabilistic PCA self-organizing maps
categories:
- Neural networks
- Principal component analysis
header_image: ~
details: <em>IEEE Transactions on Neural Networks</em> vol 20 (9), 1474-1489
doi: 10.1109/TNN.2009.2025888
link: 2009-ieee/paper.pdf
project: ~
keywords: ''
---


# Abstract


In this paper, we present a probabilistic neural model, which extends Kohonen's self-organizing map (SOM) by performing a probabilistic principal component analysis (PPCA) at each neuron. Several SOMs have been proposed in the literature to capture the local principal subspaces, but our approach offers a probabilistic model while it has a low complexity on the dimensionality of the input space. This allows to process very high-dimensional data to obtain reliable estimations of the probability densities which are based on the PPCA framework. Experimental results are presented, which show the map formation capabilities of the proposal with high-dimensional data, and its potential in image and video compression applications.





# Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```


# Citation
Please, cite this work as:


<a name=bib-Lopez-RubioOL09></a>[[LOL09]](#cite-Lopez-RubioOL09) E. López-Rubio, J. M. Ortiz-de-Lazcano-Lobato, and D. López-Rodríguez. “Probabilistic PCA Self-Organizing Maps”. In: _IEEE Trans. Neural Networks_ 20.9 (2009), pp. 1474-1489. DOI: [10.1109/TNN.2009.2025888](https://doi.org/10.1109%2FTNN.2009.2025888). URL: [https://doi.org/10.1109/TNN.2009.2025888](https://doi.org/10.1109/TNN.2009.2025888).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@article{Lopez-RubioOL09,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author    = {Ezequiel López{-}Rubio and<br>&nbsp;&nbsp;&nbsp;&nbsp;               Juan Miguel Ortiz{-}de{-}Lazcano{-}Lobato and<br>&nbsp;&nbsp;&nbsp;&nbsp;               Domingo López{-}Rodríguez},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title     = {Probabilistic {PCA} Self-Organizing Maps},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal   = {{IEEE} Trans. Neural Networks},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume    = {20},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number    = {9},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages     = {1474--1489},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year      = {2009},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url       = {https://doi.org/10.1109/TNN.2009.2025888},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi       = {10.1109/TNN.2009.2025888},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Wed, 14 Nov 2018 10:32:52 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl    = {https://dblp.org/rec/journals/tnn/Lopez-RubioOL09.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org}<br>}

:::


