---
author:
- Ezequiel López-Rubio
- Juan Miguel Ortiz-de-Lazcano-Lobato
- <a href='/people/staff/dominlopez/' style='color:rgb(100,0,50);'>Domingo López Rodríguez</a>
Status: Published
date: '2009-08-19'
slug: 2009/PrPcMa
title: Probabilistic PCA self-organizing maps
categories:
- Neural networks
- Principal component analysis
header_image: ~
details: <em>IEEE Transactions on Neural Networks</em> vol 20 (9), 1474-1489
doi: 10.1109/TNN.2009.2025888
link: 2009-ieee/paper.pdf
project: ~
keywords: ''
---


# Abstract


In this paper, we present a probabilistic neural model, which extends Kohonen's self-organizing map (SOM) by performing a probabilistic principal component analysis (PPCA) at each neuron. Several SOMs have been proposed in the literature to capture the local principal subspaces, but our approach offers a probabilistic model while it has a low complexity on the dimensionality of the input space. This allows to process very high-dimensional data to obtain reliable estimations of the probability densities which are based on the PPCA framework. Experimental results are presented, which show the map formation capabilities of the proposal with high-dimensional data, and its potential in image and video compression applications.












# Citation
Please, cite this work as:


<a name=bib-Lopez-RubioOL09></a>[[LOL09]](#cite-Lopez-RubioOL09) E. López-Rubio, J. M. Ortiz-de-Lazcano-Lobato, and D. López-Rodríguez. “Probabilistic PCA Self-Organizing Maps”. In: _IEEE Trans. Neural Networks_ 20.9 (2009), pp. 1474-1489. DOI: [10.1109/TNN.2009.2025888](https://doi.org/10.1109%2FTNN.2009.2025888). URL: [https://doi.org/10.1109/TNN.2009.2025888](https://doi.org/10.1109/TNN.2009.2025888).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@article{Lopez-RubioOL09,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author    = {Ezequiel López{-}Rubio and<br>&nbsp;&nbsp;&nbsp;&nbsp;               Juan Miguel Ortiz{-}de{-}Lazcano{-}Lobato and<br>&nbsp;&nbsp;&nbsp;&nbsp;               Domingo López{-}Rodríguez},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title     = {Probabilistic {PCA} Self-Organizing Maps},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal   = {{IEEE} Trans. Neural Networks},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume    = {20},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number    = {9},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages     = {1474--1489},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year      = {2009},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url       = {https://doi.org/10.1109/TNN.2009.2025888},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi       = {10.1109/TNN.2009.2025888},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Wed, 14 Nov 2018 10:32:52 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl    = {https://dblp.org/rec/journals/tnn/Lopez-RubioOL09.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org}<br>}

:::



# Bibliometric data

## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Yuan_Cao_2012></a>[[1]](#cite-Yuan_Cao_2012) Y. Cao, H. He, and H. Man. “SOMKE: Kernel Density Estimation Over Data Streams by Sequences of Self-Organizing Maps”. In: _IEEE Transactions on Neural Networks and Learning Systems_ 23.8 (Aug. 2012), p. 1254–1268. ISSN: 2162-2388. DOI: [10.1109/tnnls.2012.2201167](https://doi.org/10.1109%2Ftnnls.2012.2201167). URL: [http://dx.doi.org/10.1109/tnnls.2012.2201167](http://dx.doi.org/10.1109/tnnls.2012.2201167).

<a name=bib-Chen_2013></a>[[2]](#cite-Chen_2013) L. Chen, Y. Liu, Z. Huang, et al. “An improved SOM algorithm and its application to color feature extraction”. In: _Neural Computing and Applications_ 24.7–8 (Apr. 2013), p. 1759–1770. ISSN: 1433-3058. DOI: [10.1007/s00521-013-1416-9](https://doi.org/10.1007%2Fs00521-013-1416-9). URL: [http://dx.doi.org/10.1007/s00521-013-1416-9](http://dx.doi.org/10.1007/s00521-013-1416-9).

<a name=bib-Du_2013></a>[[3]](#cite-Du_2013) K. Du and M. N. S. Swamy. “Probabilistic and Bayesian Networks”. In: _Neural Networks and Statistical Learning_. Springer London, Dec. 2013, p. 563–619. ISBN: 9781447155713. DOI: [10.1007/978-1-4471-5571-3_19](https://doi.org/10.1007%2F978-1-4471-5571-3_19). URL: [http://dx.doi.org/10.1007/978-1-4471-5571-3_19](http://dx.doi.org/10.1007/978-1-4471-5571-3_19).

<a name=bib-Florent_n_N_ez_2013></a>[[4]](#cite-Florent_n_N_ez_2013) M. N. Florentín-Núñez, E. López-Rubio, and F. J. López-Rubio. “Adaptive kernel regression and probabilistic self-organizing maps for JPEG image deblocking”. In: _Neurocomputing_ 121 (Dec. 2013), p. 32–39. ISSN: 0925-2312. DOI: [10.1016/j.neucom.2012.10.029](https://doi.org/10.1016%2Fj.neucom.2012.10.029). URL: [http://dx.doi.org/10.1016/j.neucom.2012.10.029](http://dx.doi.org/10.1016/j.neucom.2012.10.029).

<a name=bib-Gruszczynski_2018></a>[[5]](#cite-Gruszczynski_2018) M. Gruszczynski, A. Klos, and J. Bogusz. “A Filtering of Incomplete GNSS Position Time Series with Probabilistic Principal Component Analysis”. In: _Pure and Applied Geophysics_ 175.5 (Apr. 2018), p. 1841–1867. ISSN: 1420-9136. DOI: [10.1007/s00024-018-1856-3](https://doi.org/10.1007%2Fs00024-018-1856-3). URL: [http://dx.doi.org/10.1007/s00024-018-1856-3](http://dx.doi.org/10.1007/s00024-018-1856-3).

<a name=bib-Gruszczynski_20181></a>[[6]](#cite-Gruszczynski_20181) M. Gruszczynski, A. Klos, and J. Bogusz. “A Filtering of Incomplete GNSS Position Time Series with Probabilistic Principal Component Analysis”. In: _Geodynamics and Earth Tides Observations from Global to Micro Scale_. Springer International Publishing, Aug. 2018, p. 247–273. ISBN: 9783319962771. DOI: [10.1007/978-3-319-96277-1_19](https://doi.org/10.1007%2F978-3-319-96277-1_19). URL: [http://dx.doi.org/10.1007/978-3-319-96277-1_19](http://dx.doi.org/10.1007/978-3-319-96277-1_19).

<a name=bib-Kaya_2017></a>[[7]](#cite-Kaya_2017) I. E. Kaya, A. Ç. Pehlivanlı, E. G. Sekizkardeş, et al. “PCA based clustering for brain tumor segmentation of T1w MRI images”. In: _Computer Methods and Programs in Biomedicine_ 140 (Mar. 2017), p. 19–28. ISSN: 0169-2607. DOI: [10.1016/j.cmpb.2016.11.011](https://doi.org/10.1016%2Fj.cmpb.2016.11.011). URL: [http://dx.doi.org/10.1016/j.cmpb.2016.11.011](http://dx.doi.org/10.1016/j.cmpb.2016.11.011).

<a name=bib-Lopez_Rubio_2013></a>[[8]](#cite-Lopez_Rubio_2013) E. Lopez-Rubio. “Improving the Quality of Self-Organizing Maps by Self-Intersection Avoidance”. In: _IEEE Transactions on Neural Networks and Learning Systems_ 24.8 (Aug. 2013), p. 1253–1265. ISSN: 2162-2388. DOI: [10.1109/tnnls.2013.2254127](https://doi.org/10.1109%2Ftnnls.2013.2254127). URL: [http://dx.doi.org/10.1109/tnnls.2013.2254127](http://dx.doi.org/10.1109/tnnls.2013.2254127).

<a name=bib-L_pez_Rubio_20101></a>[[9]](#cite-L_pez_Rubio_20101) E. López-Rubio. “Probabilistic Self-Organizing Maps for Continuous Data”. In: _IEEE Transactions on Neural Networks_ 21.10 (Oct. 2010), p. 1543–1554. ISSN: 1941-0093. DOI: [10.1109/tnn.2010.2060208](https://doi.org/10.1109%2Ftnn.2010.2060208). URL: [http://dx.doi.org/10.1109/tnn.2010.2060208](http://dx.doi.org/10.1109/tnn.2010.2060208).

<a name=bib-L_pez_Rubio_2010></a>[[10]](#cite-L_pez_Rubio_2010) E. López-Rubio. “Probabilistic self-organizing maps for qualitative data”. In: _Neural Networks_ 23.10 (Dec. 2010), p. 1208–1225. ISSN: 0893-6080. DOI: [10.1016/j.neunet.2010.07.002](https://doi.org/10.1016%2Fj.neunet.2010.07.002). URL: [http://dx.doi.org/10.1016/j.neunet.2010.07.002](http://dx.doi.org/10.1016/j.neunet.2010.07.002).

<a name=bib-L_pez_Rubio_20102></a>[[11]](#cite-L_pez_Rubio_20102) E. López-Rubio. “Restoration of images corrupted by Gaussian and uniform impulsive noise”. In: _Pattern Recognition_ 43.5 (May. 2010), p. 1835–1846. ISSN: 0031-3203. DOI: [10.1016/j.patcog.2009.11.017](https://doi.org/10.1016%2Fj.patcog.2009.11.017). URL: [http://dx.doi.org/10.1016/j.patcog.2009.11.017](http://dx.doi.org/10.1016/j.patcog.2009.11.017).

<a name=bib-L_pez_Rubio_20111></a>[[12]](#cite-L_pez_Rubio_20111) E. López-Rubio, E. José Palomo-Ferrer, J. Miguel Ortiz-de-Lazcano-Lobato, et al. “Dynamic topology learning with the probabilistic self-organizing graph”. In: _Neurocomputing_ 74.16 (Sep. 2011), p. 2633–2648. ISSN: 0925-2312. DOI: [10.1016/j.neucom.2011.03.020](https://doi.org/10.1016%2Fj.neucom.2011.03.020). URL: [http://dx.doi.org/10.1016/j.neucom.2011.03.020](http://dx.doi.org/10.1016/j.neucom.2011.03.020).

<a name=bib-L_pez_Rubio_2014></a>[[13]](#cite-L_pez_Rubio_2014) E. López-Rubio and R. M. Luque-Baena. “An adaptive system for compressed video deblocking”. In: _Signal Processing_ 103 (Oct. 2014), p. 415–425. ISSN: 0165-1684. DOI: [10.1016/j.sigpro.2013.12.033](https://doi.org/10.1016%2Fj.sigpro.2013.12.033). URL: [http://dx.doi.org/10.1016/j.sigpro.2013.12.033](http://dx.doi.org/10.1016/j.sigpro.2013.12.033).

<a name=bib-L_pez_Rubio_2011></a>[[14]](#cite-L_pez_Rubio_2011) E. López-Rubio and R. M. Luque-Baena. “Stochastic approximation for background modelling”. In: _Computer Vision and Image Understanding_ 115.6 (Jun. 2011), p. 735–749. ISSN: 1077-3142. DOI: [10.1016/j.cviu.2011.01.007](https://doi.org/10.1016%2Fj.cviu.2011.01.007). URL: [http://dx.doi.org/10.1016/j.cviu.2011.01.007](http://dx.doi.org/10.1016/j.cviu.2011.01.007).

<a name=bib-L_PEZ_RUBIO_2011></a>[[15]](#cite-L_PEZ_RUBIO_2011) E. LÓPEZ-RUBIO, R. M. LUQUE-BAENA, and E. DOMÍNGUEZ. “FOREGROUND DETECTION IN VIDEO SEQUENCES WITH PROBABILISTIC SELF-ORGANIZING MAPS”. In: _International Journal of Neural Systems_ 21.03 (Jun. 2011), p. 225–246. ISSN: 1793-6462. DOI: [10.1142/s012906571100281x](https://doi.org/10.1142%2Fs012906571100281x). URL: [http://dx.doi.org/10.1142/s012906571100281x](http://dx.doi.org/10.1142/s012906571100281x).

<a name=bib-Lopez_Rubio_2011></a>[[16]](#cite-Lopez_Rubio_2011) E. Lopez-Rubio and E. J. Palomo. “Growing Hierarchical Probabilistic Self-Organizing Graphs”. In: _IEEE Transactions on Neural Networks_ 22.7 (Jul. 2011), p. 997–1008. ISSN: 1941-0093. DOI: [10.1109/tnn.2011.2138159](https://doi.org/10.1109%2Ftnn.2011.2138159). URL: [http://dx.doi.org/10.1109/tnn.2011.2138159](http://dx.doi.org/10.1109/tnn.2011.2138159).

<a name=bib-L_PEZ_RUBIO_2014></a>[[17]](#cite-L_PEZ_RUBIO_2014) E. LÓPEZ-RUBIO, E. J. PALOMO, and E. DOMÍNGUEZ. “BREGMAN DIVERGENCES FOR GROWING HIERARCHICAL SELF-ORGANIZING NETWORKS”. In: _International Journal of Neural Systems_ 24.04 (Apr. 2014), p. 1450016. ISSN: 1793-6462. DOI: [10.1142/s0129065714500166](https://doi.org/10.1142%2Fs0129065714500166). URL: [http://dx.doi.org/10.1142/s0129065714500166](http://dx.doi.org/10.1142/s0129065714500166).

<a name=bib-L_pez_Rubio_2015></a>[[18]](#cite-L_pez_Rubio_2015) F. J. López-Rubio, E. Domínguez, E. J. Palomo, et al. “Selecting the Color Space for Self-Organizing Map Based Foreground Detection in Video”. In: _Neural Processing Letters_ 43.2 (May. 2015), p. 345–361. ISSN: 1573-773X. DOI: [10.1007/s11063-015-9431-8](https://doi.org/10.1007%2Fs11063-015-9431-8). URL: [http://dx.doi.org/10.1007/s11063-015-9431-8](http://dx.doi.org/10.1007/s11063-015-9431-8).

<a name=bib-Lopez_Rubio_2014></a>[[19]](#cite-Lopez_Rubio_2014) F. J. Lopez-Rubio, E. Lopez-Rubio, R. M. Luque-Baena, et al. “Color space selection for self-organizing map based foreground detection in video sequences”. In: _2014 International Joint Conference on Neural Networks (IJCNN)_. IEEE, Jul. 2014, p. 3347–3354. DOI: [10.1109/ijcnn.2014.6889404](https://doi.org/10.1109%2Fijcnn.2014.6889404). URL: [http://dx.doi.org/10.1109/ijcnn.2014.6889404](http://dx.doi.org/10.1109/ijcnn.2014.6889404).

<a name=bib-Palomo_2018></a>[[20]](#cite-Palomo_2018) E. J. Palomo, M. A. Molina-Cabello, E. Lopez-Rubio, et al. “A New Self-Organizing Neural Gas Model based on Bregman Divergences”. In: _2018 International Joint Conference on Neural Networks (IJCNN)_. IEEE, Jul. 2018, p. 1–8. DOI: [10.1109/ijcnn.2018.8489545](https://doi.org/10.1109%2Fijcnn.2018.8489545). URL: [http://dx.doi.org/10.1109/ijcnn.2018.8489545](http://dx.doi.org/10.1109/ijcnn.2018.8489545).

<a name=bib-Silva_20121></a>[[21]](#cite-Silva_20121) T. C. Silva and L. Zhao. “Network-Based Stochastic Semisupervised Learning”. In: _IEEE Transactions on Neural Networks and Learning Systems_ 23.3 (Mar. 2012), p. 451–466. ISSN: 2162-2388. DOI: [10.1109/tnnls.2011.2181413](https://doi.org/10.1109%2Ftnnls.2011.2181413). URL: [http://dx.doi.org/10.1109/tnnls.2011.2181413](http://dx.doi.org/10.1109/tnnls.2011.2181413).

<a name=bib-Silva_2012></a>[[22]](#cite-Silva_2012) T. C. Silva and L. Zhao. “Stochastic Competitive Learning in Complex Networks”. In: _IEEE Transactions on Neural Networks and Learning Systems_ 23.3 (Mar. 2012), p. 385–398. ISSN: 2162-2388. DOI: [10.1109/tnnls.2011.2181866](https://doi.org/10.1109%2Ftnnls.2011.2181866). URL: [http://dx.doi.org/10.1109/tnnls.2011.2181866](http://dx.doi.org/10.1109/tnnls.2011.2181866).

<a name=bib-Soltani_2014></a>[[23]](#cite-Soltani_2014) A. Soltani and M. Akbarzadeh-T. “Confabulation-Inspired Association Rule Mining for Rare and Frequent Itemsets”. In: _IEEE Transactions on Neural Networks and Learning Systems_ 25.11 (Nov. 2014), p. 2053–2064. ISSN: 2162-2388. DOI: [10.1109/tnnls.2014.2303137](https://doi.org/10.1109%2Ftnnls.2014.2303137). URL: [http://dx.doi.org/10.1109/tnnls.2014.2303137](http://dx.doi.org/10.1109/tnnls.2014.2303137).

<a name=bib-Sovilj_2010></a>[[24]](#cite-Sovilj_2010) D. Sovilj, T. Raiko, and E. Oja. “Extending Self-Organizing Maps with uncertainty information of probabilistic PCA”. In: _The 2010 International Joint Conference on Neural Networks (IJCNN)_. IEEE, Jul. 2010, p. 1–7. DOI: [10.1109/ijcnn.2010.5596578](https://doi.org/10.1109%2Fijcnn.2010.5596578). URL: [http://dx.doi.org/10.1109/ijcnn.2010.5596578](http://dx.doi.org/10.1109/ijcnn.2010.5596578).

<a name=bib-Yin_2014></a>[[25]](#cite-Yin_2014) H. Yin, C. Zhang, and Y. Ji. “Distributed clustering using distributed mixture of probabilistic PCA”. In: _2014 11th International Conference on Fuzzy Systems and Knowledge Discovery (FSKD)_. IEEE, Aug. 2014, p. 352–357. DOI: [10.1109/fskd.2014.6980859](https://doi.org/10.1109%2Ffskd.2014.6980859). URL: [http://dx.doi.org/10.1109/fskd.2014.6980859](http://dx.doi.org/10.1109/fskd.2014.6980859).


