---
title: Relational dual tableau decision procedures and their applications to modal
  and intuitionistic logics
author:
- Joanna Golinska-Pilarek
- Taneli Huuskonen
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
date: '2014'
categories: uncategorised
slug: 2014/ReDuTaDePrApMoInLo
details: Ann. Pure Appl. Log. vol. 165 (2), pages 409--427.
doi: 10.1016/J.APAL.2013.06.003
---



# Abstract


We study a class DL of certain decidable relational logics of binary relations with a single relational constant and restricted composition. The logics in DL are defined in terms of semantic restrictions on the models. The main contribution of the present article is the construction of relational dual tableau decision procedures for the logics in DL. The systems are constructed in the framework of the original methodology of relational proof systems, determined only by axioms and inference rules, without any external techniques. All necessary bookkeeping is contained in the proof tree itself and used according to the explicit rules. All the systems are deterministic, producing exactly one proof tree for every formula. Furthermore, we show how the systems for logics in DL can be used as deterministic decision procedures for some modal and intuitionistic logics.








# Citation
Please, cite this work as:


<a name=bib-GolinskaPilarek2014></a>[[GHM14]](#cite-GolinskaPilarek2014) J. Golinska-Pilarek, T. Huuskonen, and E. Mu~noz-Velasco. “Relational dual tableau decision procedures and their applications to modal and intuitionistic logics”. In: _Ann. Pure Appl. Log._ 165.2 (2014), pp. 409-427. DOI: [10.1016/J.APAL.2013.06.003](https://doi.org/10.1016%2FJ.APAL.2013.06.003). URL: [https://doi.org/10.1016/j.apal.2013.06.003](https://doi.org/10.1016/j.apal.2013.06.003).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{GolinskaPilarek2014,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Joanna Golinska-Pilarek and Taneli Huuskonen and Emilio Mu~noz-Velasco},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Ann. Pure Appl. Log.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Relational dual tableau decision procedures and their applications to modal and intuitionistic logics},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2014},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number = {2},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {409--427},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {165},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/apal/Golinska-PilarekHM14.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1016/J.APAL.2013.06.003},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 21 Feb 2020 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1016/j.apal.2013.06.003},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1016/J.APAL.2013.06.003" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1016/J.APAL.2013.06.003" class="plumx-details" data-site="plum" data-hide-when-empty="true">Relational dual tableau decision procedures and their applications to modal and intuitionistic logics</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1016/J.APAL.2013.06.003"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Burrieza_2018></a>[[1]](#cite-Burrieza_2018) A. Burrieza, E. Muñoz-Velasco, and M. Ojeda-Aciego. “Logics for Order-of-Magnitude Qualitative Reasoning: Formalizing Negligibility”. In: _Ewa Orłowska on Relational Methods in Logic and Computer Science_. Springer International Publishing, 2018, p. 203–231. ISBN: 9783319978796. DOI: [10.1007/978-3-319-97879-6_8](https://doi.org/10.1007%2F978-3-319-97879-6_8). URL: [http://dx.doi.org/10.1007/978-3-319-97879-6_8](http://dx.doi.org/10.1007/978-3-319-97879-6_8).

<a name=bib-Cantone_2014></a>[[2]](#cite-Cantone_2014) D. Cantone, J. Golińska-Pilarek, and M. Nicolosi-Asmundo. “A Relational Dual Tableau Decision Procedure for Multimodal and Description Logics”. In: _Hybrid Artificial Intelligence Systems_. Springer International Publishing, 2014, p. 466–477. ISBN: 9783319076171. DOI: [10.1007/978-3-319-07617-1_41](https://doi.org/10.1007%2F978-3-319-07617-1_41). URL: [http://dx.doi.org/10.1007/978-3-319-07617-1_41](http://dx.doi.org/10.1007/978-3-319-07617-1_41).

<a name=bib-Cantone_2018></a>[[3]](#cite-Cantone_2018) D. Cantone and M. Nicolosi-Asmundo. “Dual Tableau-Based Decision Procedures for Fragments of the Logic of Binary Relations”. In: _Ewa Orłowska on Relational Methods in Logic and Computer Science_. Springer International Publishing, 2018, p. 169–202. ISBN: 9783319978796. DOI: [10.1007/978-3-319-97879-6_7](https://doi.org/10.1007%2F978-3-319-97879-6_7). URL: [http://dx.doi.org/10.1007/978-3-319-97879-6_7](http://dx.doi.org/10.1007/978-3-319-97879-6_7).

<a name=bib-httpsdoiorg1048550arxiv180207508></a>[[4]](#cite-httpsdoiorg1048550arxiv180207508) D. Cantone, M. Nicolosi-Asmundo, and E. Orłowska. _A Dual Tableau-based Decision Procedure for a Relational Logic with the Universal Relation (Extended Version)_. 2018. DOI: [10.48550/ARXIV.1802.07508](https://doi.org/10.48550%2FARXIV.1802.07508). URL: [https://arxiv.org/abs/1802.07508](https://arxiv.org/abs/1802.07508).

<a name=bib-Goli_ska_Pilarek_2016></a>[[5]](#cite-Goli_ska_Pilarek_2016) J. Golińska-Pilarek, E. Muñoz-Velasco, and A. Mora. “Tableau reductions: Towards an optimal decision procedure for the modal necessity”. In: _Journal of Applied Logic_ 17 (Sep. 2016), p. 14–24. ISSN: 1570-8683. DOI: [10.1016/j.jal.2015.09.005](https://doi.org/10.1016%2Fj.jal.2015.09.005). URL: [http://dx.doi.org/10.1016/j.jal.2015.09.005](http://dx.doi.org/10.1016/j.jal.2015.09.005).

<a name=bib-Grzelak_2017></a>[[6]](#cite-Grzelak_2017) A. Grzelak and D. Leszczyńska-Jasion. “Automatic proof generation in an axiomatic system for $\mathsfCPL$ by means of the method of Socratic proofs”. In: _Logic Journal of the IGPL_ 26.1 (Nov. 2017), p. 109–148. ISSN: 1368-9894. DOI: [10.1093/jigpal/jzx057](https://doi.org/10.1093%2Fjigpal%2Fjzx057). URL: [http://dx.doi.org/10.1093/jigpal/jzx057](http://dx.doi.org/10.1093/jigpal/jzx057).

<a name=bib-Leszczy_ska_Jasion_2018></a>[[7]](#cite-Leszczy_ska_Jasion_2018) D. Leszczyńska-Jasion, M. Ignaszak, and S. Chlebowski. “Rasiowa–Sikorski Deduction Systems with the Rule of Cut: A Case Study”. In: _Studia Logica_ 107.2 (Apr. 2018), p. 313–349. ISSN: 1572-8730. DOI: [10.1007/s11225-018-9795-7](https://doi.org/10.1007%2Fs11225-018-9795-7). URL: [http://dx.doi.org/10.1007/s11225-018-9795-7](http://dx.doi.org/10.1007/s11225-018-9795-7).

