---
author: Francisco Pérez-Gámez, Pablo Cordero, Manuel Enciso, Domingo López-Rodríguez,
  Angel Mora
Status: Published
date: '2022-07-13T00:00:00Z'
slug: 2022/CoMiCoLa
title: Computing the Mixed Concept Lattice
categories: Formal concept analysis
header_image: ~
details: <em>International Conference on Information Processing and Management of
  Uncertainty in Knowledge-Based Systems</em>
doi: 10.1007/978-3-031-08971-8_8
link: 2022-ipmu/PAPER.pdf
project: 2019-flair
keywords: Formal concept analysis, Mixed attributes, Concept lattice
listing:
- id: funding
  contents: funding.yml
  type: default
  sort: date desc
---


# Abstract





# Funding
::: {.callout-note appearance='minimal' collapse=false}
## Projects funding this work

:::{#funding}
:::
:::









# Citation
Please, cite this work as:


<a name=bib-Mixed-IPMU></a>[[Pér+22]](#cite-Mixed-IPMU) F. Pérez-Gámez, P. Cordero, M. Enciso, et al. “Computing the Mixed Concept Lattice”. In: _Information Processing and Management of Uncertainty in Knowledge-Based Systems - 19th International Conference, IPMU 2022, Milan, Italy, July 11-15, 2022, Proceedings, Part I_. Ed. by D. Ciucci, I. Couso, J. Medina, D. Slezak, D. Petturiti, B. Bouchon-Meunier and R. R. Yager. Vol. 1601. Communications in Computer and Information Science. Springer, 2022, pp. 87-99. DOI: [10.1007/978-3-031-08971-8\_8](https://doi.org/10.1007%2F978-3-031-08971-8%5C_8). URL: [https://doi.org/10.1007/978-3-031-08971-8\_8](https://doi.org/10.1007/978-3-031-08971-8\_8).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@inproceedings{Mixed-IPMU,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author    = {Francisco Pérez{-}Gámez and<br>&nbsp;&nbsp;&nbsp;&nbsp;               Pablo Cordero and<br>&nbsp;&nbsp;&nbsp;&nbsp;               Manuel Enciso and<br>&nbsp;&nbsp;&nbsp;&nbsp;               Domingo López{-}Rodríguez and<br>&nbsp;&nbsp;&nbsp;&nbsp;               Angel Mora},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor    = {Davide Ciucci and<br>&nbsp;&nbsp;&nbsp;&nbsp;               Inés Couso and<br>&nbsp;&nbsp;&nbsp;&nbsp;               Jesús Medina and<br>&nbsp;&nbsp;&nbsp;&nbsp;               Dominik Slezak and<br>&nbsp;&nbsp;&nbsp;&nbsp;               Davide Petturiti and<br>&nbsp;&nbsp;&nbsp;&nbsp;               Bernadette Bouchon{-}Meunier and<br>&nbsp;&nbsp;&nbsp;&nbsp;               Ronald R. Yager},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title     = {Computing the Mixed Concept Lattice},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Information Processing and Management of Uncertainty in Knowledge-Based<br>&nbsp;&nbsp;&nbsp;&nbsp;               Systems - 19th International Conference, {IPMU} 2022, Milan, Italy,<br>&nbsp;&nbsp;&nbsp;&nbsp;               July 11-15, 2022, Proceedings, Part {I}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series    = {Communications in Computer and Information Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume    = {1601},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages     = {87--99},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year      = {2022},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url       = {https://doi.org/10.1007/978-3-031-08971-8\_8},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi       = {10.1007/978-3-031-08971-8\_8},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Mon, 25 Jul 2022 08:39:18 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl    = {https://dblp.org/rec/conf/ipmu/Perez-GamezCEL022.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org}<br>}

:::



# Bibliometric data

## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Braud_2023></a>[[1]](#cite-Braud_2023) A. Braud, X. Dolques, M. Huchard, et al. “Relational Concept Analysis in Practice: Capitalizing on Data Modeling Using Design Patterns”. In: _Formal Concept Analysis_. Springer Nature Switzerland, 2023, p. 166–182. ISBN: 9783031359491. DOI: [10.1007/978-3-031-35949-1_12](https://doi.org/10.1007%2F978-3-031-35949-1_12). URL: [http://dx.doi.org/10.1007/978-3-031-35949-1_12](http://dx.doi.org/10.1007/978-3-031-35949-1_12).


