---
title: CRL-Chu Correspondences
author:
- Ondrej Kridlo
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '2013'
categories: uncategorised
slug: 2013/Co
details: Proceedings of the Tenth International Conference on Concept Lattices and
  Their Applications, La Rochelle, France, October 15-18, 2013 , {CEUR} Workshop Proceedings
  vol. 1062, pages 105--116.
---



# Abstract


We continue our study of the general notion of L-Chu correspondence by introducing the category CRL-ChuCors incorporating
residuation to the underlying complete lattice L, specifically, on the basis of a residuation-preserving isotone Galois connection λ. Then, the L-bonds are generalized within this same framework, and its structure is related to that of the extent of a suitably defined λ-direct product.








# Citation
Please, cite this work as:


<a name=bib-Kridlo2013></a>[[KO13]](#cite-Kridlo2013) O. Kridlo and M. Ojeda-Aciego. “CRL-Chu Correspondences”. In: _Proceedings of the Tenth International Conference on Concept Lattices and Their Applications, La Rochelle, France, October 15-18, 2013_. Ed. by M. Ojeda-Aciego and J. Outrata. Vol. 1062. CEUR Workshop Proceedings. CEUR-WS.org, 2013, pp. 105-116. URL: [https://ceur-ws.org/Vol-1062/paper9.pdf](https://ceur-ws.org/Vol-1062/paper9.pdf).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Kridlo2013,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Ondrej Kridlo and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Proceedings of the Tenth International Conference on Concept Lattices and Their Applications, La Rochelle, France, October 15-18, 2013},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {CRL-Chu Correspondences},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2013},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Manuel Ojeda-Aciego and Jan Outrata},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {105--116},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {CEUR-WS.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {{CEUR} Workshop Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {1062},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {We continue our study of the general notion of L-Chu correspondence by introducing the category CRL-ChuCors incorporating<br>&nbsp;&nbsp;&nbsp;&nbsp;residuation to the underlying complete lattice L, specifically, on the basis of a residuation-preserving isotone Galois connection λ. Then, the L-bonds are generalized within this same framework, and its structure is related to that of the extent of a suitably defined λ-direct product.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/cla/KridloO13.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 10 Mar 2023 16:22:10 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://ceur-ws.org/Vol-1062/paper9.pdf},<br>}

:::








