---
author:
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/enciso/' style='color:rgb(100,0,50);'>Manuel Enciso</a>
- <a href='/people/staff/amora/' style='color:rgb(100,0,50);'>Ángel Mora</a>
- Vilem Vychodil
Status: Published
date: '2020-08-06'
slug: 2020/PaSiLoReImClClOp
title: 'Parameterized simplification logic I: reasoning with implications and classes
  of closure operators'
categories: Simplification logic
header_image: ~
details: <em>International Journal of General Systems</em> vol 49 (7), pp. 724 --
  746
doi: 10.1080/03081079.2020.1831484
project: ~
keywords: Closure operator; lattice theory; completeness; if-then rules; isotone Galois
  connection
---


# Abstract


In this paper, we present a general inference system for reasoning with if-then rules. They are defined using general lattice-theoretic notions and their semantics is defined using particular closure operators parameterized by systems of isotone Galois connections. In this general setting, we introduce a simplification logic, show its sound and complete axiomatization, and deal with related issues. The presented results can be seen as forming parameterized framework for dealing with if-then rules that allows to focus on particular dependencies obtained by choices of parameterizations.












# Citation
Please, cite this work as:


<a name=bib-doi1010800308107920201831484></a>[[PV20]](#cite-doi1010800308107920201831484) A. M. Pablo Cordero Manuel Enciso and V. Vychodil. “Parameterized simplification logic I: reasoning with implications and classes of closure operators”. In: _International Journal of General Systems_ 49.7 (2020), pp. 724-746. DOI: [10.1080/03081079.2020.1831484](https://doi.org/10.1080%2F03081079.2020.1831484). eprint:

https://doi.org/10.1080/03081079.2020.1831484

. URL: [

https://doi.org/10.1080/03081079.2020.1831484

](

https://doi.org/10.1080/03081079.2020.1831484

).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@article{doi:10.1080/03081079.2020.1831484,<br>&nbsp;&nbsp;&nbsp;&nbsp;author = {Pablo Cordero, Manuel Enciso, Angel Mora and Vilem Vychodil},<br>&nbsp;&nbsp;&nbsp;&nbsp;title = {Parameterized simplification logic I: reasoning with implications and classes of closure operators},<br>&nbsp;&nbsp;&nbsp;&nbsp;journal = {International Journal of General Systems},<br>&nbsp;&nbsp;&nbsp;&nbsp;volume = {49},<br>&nbsp;&nbsp;&nbsp;&nbsp;number = {7},<br>&nbsp;&nbsp;&nbsp;&nbsp;pages = {724-746},<br>&nbsp;&nbsp;&nbsp;&nbsp;year = {2020},<br>&nbsp;&nbsp;&nbsp;&nbsp;publisher = {Taylor & Francis},<br>&nbsp;&nbsp;&nbsp;&nbsp;doi = {10.1080/03081079.2020.1831484},<br>&nbsp;&nbsp;&nbsp;&nbsp;<br>&nbsp;&nbsp;&nbsp;&nbsp;<br>&nbsp;&nbsp;&nbsp;&nbsp;URL = { <br>&nbsp;&nbsp;&nbsp;&nbsp;    <br>&nbsp;&nbsp;&nbsp;&nbsp;        https://doi.org/10.1080/03081079.2020.1831484<br>&nbsp;&nbsp;&nbsp;&nbsp;    <br>&nbsp;&nbsp;&nbsp;&nbsp;    <br>&nbsp;&nbsp;&nbsp;&nbsp;<br>&nbsp;&nbsp;&nbsp;&nbsp;},<br>&nbsp;&nbsp;&nbsp;&nbsp;eprint = { <br>&nbsp;&nbsp;&nbsp;&nbsp;    <br>&nbsp;&nbsp;&nbsp;&nbsp;        https://doi.org/10.1080/03081079.2020.1831484<br>&nbsp;&nbsp;&nbsp;&nbsp;    <br>&nbsp;&nbsp;&nbsp;&nbsp;    <br>&nbsp;&nbsp;&nbsp;&nbsp;<br>&nbsp;&nbsp;&nbsp;&nbsp;}<br>&nbsp;&nbsp;&nbsp;&nbsp;<br>}

:::



# Bibliometric data

## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Arag_n_2022></a>[[1]](#cite-Arag_n_2022) R. G. Aragón, M. Eugenia Cornejo, J. Medina, et al. “A Formal Method for Driver Identification”. In: _Computational Intelligence and Mathematics for Tackling Complex Problems 4_. Springer International Publishing, Sep. 2022, p. 153–159. ISBN: 9783031077074. DOI: [10.1007/978-3-031-07707-4_19](https://doi.org/10.1007%2F978-3-031-07707-4_19). URL: [http://dx.doi.org/10.1007/978-3-031-07707-4_19](http://dx.doi.org/10.1007/978-3-031-07707-4_19).

<a name=bib-Arag_n_2021></a>[[2]](#cite-Arag_n_2021) R. G. Aragón, J. Medina, and E. Ramírez-Poussa. “Identifying Non-Sublattice Equivalence Classes Induced by an Attribute Reduction in FCA”. In: _Mathematics_ 9.5 (Mar. 2021), p. 565. ISSN: 2227-7390. DOI: [10.3390/math9050565](https://doi.org/10.3390%2Fmath9050565). URL: [http://dx.doi.org/10.3390/math9050565](http://dx.doi.org/10.3390/math9050565).

<a name=bib-Cordero_2022></a>[[3]](#cite-Cordero_2022) P. Cordero, M. Enciso, A. Mora, et al. “Parameterized Simplification Logic: Reasoning With Implications in an Automated Way”. In: _IEEE Transactions on Fuzzy Systems_ 30.12 (Dec. 2022), p. 5534–5543. ISSN: 1941-0034. DOI: [10.1109/tfuzz.2022.3179847](https://doi.org/10.1109%2Ftfuzz.2022.3179847). URL: [http://dx.doi.org/10.1109/tfuzz.2022.3179847](http://dx.doi.org/10.1109/tfuzz.2022.3179847).

<a name=bib-Cornejo_2022></a>[[4]](#cite-Cornejo_2022) M. E. Cornejo, J. C. Díaz-Moreno, and J. Medina. “Generalized quantifiers in formal concept analysis”. In: _Journal of Computational and Applied Mathematics_ 404 (Apr. 2022), p. 113772. ISSN: 0377-0427. DOI: [10.1016/j.cam.2021.113772](https://doi.org/10.1016%2Fj.cam.2021.113772). URL: [http://dx.doi.org/10.1016/j.cam.2021.113772](http://dx.doi.org/10.1016/j.cam.2021.113772).

<a name=bib-Cornejo_2024></a>[[5]](#cite-Cornejo_2024) M. E. Cornejo, J. Medina, and F. J. Ocaña. “Attribute implications in multi-adjoint concept lattices with hedges”. In: _Fuzzy Sets and Systems_ 479 (Mar. 2024), p. 108854. ISSN: 0165-0114. DOI: [10.1016/j.fss.2023.108854](https://doi.org/10.1016%2Fj.fss.2023.108854). URL: [http://dx.doi.org/10.1016/j.fss.2023.108854](http://dx.doi.org/10.1016/j.fss.2023.108854).

<a name=bib-Nesibe_Kesicio_lu_2024></a>[[6]](#cite-Nesibe_Kesicio_lu_2024) M. Nesibe Kesicioğlu and E. Kürkçü Çakar. “Closure operators constructed by logical operations on bounded lattices”. In: _Fuzzy Sets and Systems_ 484 (May. 2024), p. 108945. ISSN: 0165-0114. DOI: [10.1016/j.fss.2024.108945](https://doi.org/10.1016%2Fj.fss.2024.108945). URL: [http://dx.doi.org/10.1016/j.fss.2024.108945](http://dx.doi.org/10.1016/j.fss.2024.108945).

<a name=bib-Ojeda_Hern_ndez_20223></a>[[7]](#cite-Ojeda_Hern_ndez_20223) M. Ojeda-Hernández, I. P. Cabrera, and P. Cordero. “Quasi-closed elements in fuzzy posets”. In: _Journal of Computational and Applied Mathematics_ 404 (Apr. 2022), p. 113390. ISSN: 0377-0427. DOI: [10.1016/j.cam.2021.113390](https://doi.org/10.1016%2Fj.cam.2021.113390). URL: [http://dx.doi.org/10.1016/j.cam.2021.113390](http://dx.doi.org/10.1016/j.cam.2021.113390).

<a name=bib-Ojeda_Hernandez_2021></a>[[8]](#cite-Ojeda_Hernandez_2021) M. Ojeda-Hernandez, I. P. Cabrera, P. Cordero, et al. “On (fuzzy) closure systems in complete fuzzy lattices”. In: _2021 IEEE International Conference on Fuzzy Systems (FUZZ-IEEE)_. IEEE, Jul. 2021, p. 1–6. DOI: [10.1109/fuzz45933.2021.9494404](https://doi.org/10.1109%2Ffuzz45933.2021.9494404). URL: [http://dx.doi.org/10.1109/fuzz45933.2021.9494404](http://dx.doi.org/10.1109/fuzz45933.2021.9494404).

<a name=bib-Ojeda_Hern_ndez_2021></a>[[9]](#cite-Ojeda_Hern_ndez_2021) M. Ojeda-Hernández, I. P. Cabrera, P. Cordero, et al. “Closure Systems as a Fuzzy Extension of Meet-subsemilattices”. In: _Joint Proceedings of the 19th World Congress of the International Fuzzy Systems Association (IFSA), the 12th Conference of the European Society for Fuzzy Logic and Technology (EUSFLAT), and the 11th International Summer School on Aggregation Operators (AGOP)_. ifsa-eusflat-agop-21. Atlantis Press, 2021. DOI: [10.2991/asum.k.210827.006](https://doi.org/10.2991%2Fasum.k.210827.006). URL: [http://dx.doi.org/10.2991/asum.k.210827.006](http://dx.doi.org/10.2991/asum.k.210827.006).

<a name=bib-Ojeda_Hern_ndez_20221></a>[[10]](#cite-Ojeda_Hern_ndez_20221) M. Ojeda-Hernández, I. P. Cabrera, P. Cordero, et al. “Fuzzy closure relations”. In: _Fuzzy Sets and Systems_ 450 (Dec. 2022), p. 118–132. ISSN: 0165-0114. DOI: [10.1016/j.fss.2022.05.016](https://doi.org/10.1016%2Fj.fss.2022.05.016). URL: [http://dx.doi.org/10.1016/j.fss.2022.05.016](http://dx.doi.org/10.1016/j.fss.2022.05.016).

<a name=bib-Ojeda_Hern_ndez_2022></a>[[11]](#cite-Ojeda_Hern_ndez_2022) M. Ojeda-Hernández, I. P. Cabrera, P. Cordero, et al. “Fuzzy closure systems: Motivation, definition and properties”. In: _International Journal of Approximate Reasoning_ 148 (Sep. 2022), p. 151–161. ISSN: 0888-613X. DOI: [10.1016/j.ijar.2022.06.004](https://doi.org/10.1016%2Fj.ijar.2022.06.004). URL: [http://dx.doi.org/10.1016/j.ijar.2022.06.004](http://dx.doi.org/10.1016/j.ijar.2022.06.004).

<a name=bib-Ojeda_Hern_ndez_20222></a>[[12]](#cite-Ojeda_Hern_ndez_20222) M. Ojeda-Hernández, I. P. Cabrera, P. Cordero, et al. “Relational Extension of Closure Structures”. In: _Information Processing and Management of Uncertainty in Knowledge-Based Systems_. Springer International Publishing, 2022, p. 77–86. ISBN: 9783031089718. DOI: [10.1007/978-3-031-08971-8_7](https://doi.org/10.1007%2F978-3-031-08971-8_7). URL: [http://dx.doi.org/10.1007/978-3-031-08971-8_7](http://dx.doi.org/10.1007/978-3-031-08971-8_7).

<a name=bib-P_rez_G_mez_2023></a>[[13]](#cite-P_rez_G_mez_2023) F. Pérez-Gámez, P. Cordero, M. Enciso, et al. “Simplification logic for the management of unknown information”. In: _Information Sciences_ 634 (Jul. 2023), p. 505–519. ISSN: 0020-0255. DOI: [10.1016/j.ins.2023.03.015](https://doi.org/10.1016%2Fj.ins.2023.03.015). URL: [http://dx.doi.org/10.1016/j.ins.2023.03.015](http://dx.doi.org/10.1016/j.ins.2023.03.015).


