---
title: Fuzzy closure structures as formal concepts
type: journals
author:
- <a href='/people/staff/manuojeda/' style='color:rgb(100,0,50);'>Manuel Ojeda Hernández</a>
- <a href='/people/staff/ipcabrera/' style='color:rgb(100,0,50);'>Inmaculada de las
  Peñas Cabrera</a>
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero Ortega</a>
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
date: '2023-01-01'
categories:
- Formal concept analysis
- Fuzzy logic
- Fuzzy sets
- Uncertainty
doi: 10.1016/j.fss.2022.12.014
slug: 2023-MOH-IPC-PC-EMV-Fuzzy
keywords: ''
project: 2019-flair
details: 'Fuzzy Sets Syst. 463: 108458'
listing:
- id: funding
  contents: funding.yml
  type: default
  sort: date desc
---




# Abstract

Galois connections seem to be ubiquitous in mathematics. They have been used to model solutions for both pure and application-oriented problems. Throughout the paper, the general framework is a complete fuzzy lattice over a complete residuated lattice. The existence of three fuzzy Galois connections (two antitone and one isotone) between three specific ordered sets is proved in this paper. The most interesting part is that fuzzy closure systems, fuzzy closure operators and strong fuzzy closure relations are formal concepts of these fuzzy Galois connections.


# Funding
::: {.callout-note appearance='minimal' collapse=false}
## Projects funding this work

:::{#funding}
:::
:::




# Citation
Please, cite this work as:


<a name=bib-Ojeda-Hernndez2023></a>[[Oje+23]](#cite-Ojeda-Hernndez2023) M. Ojeda-Hernández, I. P. Cabrera, P. Cordero, et al. “Fuzzy closure structures as formal concepts”. In: _Fuzzy Sets and Systems_ 463 (2023). Cited by: 6; All Open Access, Green Open Access, Hybrid Gold Open Access. DOI: [10.1016/j.fss.2022.12.014](https://doi.org/10.1016%2Fj.fss.2022.12.014). URL: [https://www.scopus.com/inward/record.uri?eid=2-s2.0-85145982725&doi=10.1016

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@ARTICLE{Ojeda-Hernández2023,<br>&nbsp;&nbsp;&nbsp;&nbsp;	author = {Ojeda-Hernández, Manuel and Cabrera, Inma P. and Cordero, Pablo and Muñoz-Velasco, Emilio},<br>&nbsp;&nbsp;&nbsp;&nbsp;	title = {Fuzzy closure structures as formal concepts},<br>&nbsp;&nbsp;&nbsp;&nbsp;	year = {2023},<br>&nbsp;&nbsp;&nbsp;&nbsp;	journal = {Fuzzy Sets and Systems},<br>&nbsp;&nbsp;&nbsp;&nbsp;	volume = {463},<br>&nbsp;&nbsp;&nbsp;&nbsp;	doi = {10.1016/j.fss.2022.12.014},<br>&nbsp;&nbsp;&nbsp;&nbsp;	url = {https://www.scopus.com/inward/record.uri?eid=2-s2.0-85145982725&doi=10.1016%2fj.fss.2022.12.014&partnerID=40&md5=4b37584d1536d8a88466d1dbb3d70b10},<br>&nbsp;&nbsp;&nbsp;&nbsp;	type = {Article},<br>&nbsp;&nbsp;&nbsp;&nbsp;	publication_stage = {Final},<br>&nbsp;&nbsp;&nbsp;&nbsp;	source = {Scopus},<br>&nbsp;&nbsp;&nbsp;&nbsp;	note = {Cited by: 6; All Open Access, Green Open Access, Hybrid Gold Open Access}<br>}

:::

