---
title: Information Processing and Management of Uncertainty in Knowledge-Based Systems.
  Applications - 17th International Conference, {IPMU} 2018, C{\'{a}}diz, Spain, June
  11-15, 2018, Proceedings, Part {III}
author: ''
date: '2018'
categories: uncategorised
slug: 2018/InPrMaUnApInJuPa
details: []
doi: 10.1007/978-3-319-91479-4
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Medina2018b></a>[[Med+18]](#cite-Medina2018b) J. Medina, M. Ojeda-Aciego, J. L. V. Galdeano, et al., ed. _Information Processing and Management of Uncertainty in Knowledge-Based Systems. Applications - 17th International Conference, IPMU 2018, Cádiz, Spain, June 11-15, 2018, Proceedings, Part III_. Vol. 855. Communications in Computer and Information Science. Springer, 2018. ISBN: 978-3-319-91478-7. DOI: [10.1007/978-3-319-91479-4](https://doi.org/10.1007%2F978-3-319-91479-4). URL: [https://doi.org/10.1007/978-3-319-91479-4](https://doi.org/10.1007/978-3-319-91479-4).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Proceedings{Medina2018b,<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Information Processing and Management of Uncertainty in Knowledge-Based Systems. Applications - 17th International Conference, {IPMU} 2018, C{\'{a}}diz, Spain, June 11-15, 2018, Proceedings, Part {III}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2018},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Jes{\a'u}s Medina and Manuel Ojeda-Aciego and Jos{\a'e} Luis Verdegay Galdeano and Irina Perfilieva and Bernadette Bouchon-Meunier and Ronald R. Yager},<br>&nbsp;&nbsp;&nbsp;&nbsp;  isbn = {978-3-319-91478-7},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Communications in Computer and Information Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {855},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/ipmu/2018-3.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/978-3-319-91479-4},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Thu, 07 Jan 2021 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/978-3-319-91479-4},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/978-3-319-91479-4" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/978-3-319-91479-4" class="plumx-details" data-site="plum" data-hide-when-empty="true">Information Processing and Management of Uncertainty in Knowledge-Based Systems. Applications - 17th International Conference, {IPMU} 2018, C{\'{a}}diz, Spain, June 11-15, 2018, Proceedings, Part {III}</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1007/978-3-319-91479-4"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Alzate_Mej_a_2021></a>[[1]](#cite-Alzate_Mej_a_2021) N. Alzate-Mejía, G. Santos-Boada, and J. R. de Almeida-Amazonas. “Decision-Making under Uncertainty for the Deployment of Future Hyperconnected Networks: A Survey”. In: _Sensors_ 21.11 (May. 2021), p. 3791. ISSN: 1424-8220. DOI: [10.3390/s21113791](https://doi.org/10.3390%2Fs21113791). URL: [http://dx.doi.org/10.3390/s21113791](http://dx.doi.org/10.3390/s21113791).

<a name=bib-Aravanis_2024></a>[[2]](#cite-Aravanis_2024) T. Aravanis, I. Hatzilygeroudis, and G. Spiliopoulos. “Ensemble Modelling for Predicting Fish Mortality”. In: _Applied Sciences_ 14.15 (Jul. 2024), p. 6540. ISSN: 2076-3417. DOI: [10.3390/app14156540](https://doi.org/10.3390%2Fapp14156540). URL: [http://dx.doi.org/10.3390/app14156540](http://dx.doi.org/10.3390/app14156540).

<a name=bib-Buitrago_2019></a>[[3]](#cite-Buitrago_2019) S. Buitrago, P. L. Duque, and S. Robledo. “Branding Corporativo: una revisión bibliográfica”. In: _ECONÓMICAS CUC_ 41.1 (Nov. 2019). ISSN: 0120-3932. DOI: [10.17981/econcuc.41.1.2020.org.1](https://doi.org/10.17981%2Feconcuc.41.1.2020.org.1). URL: [http://dx.doi.org/10.17981/econcuc.41.1.2020.org.1](http://dx.doi.org/10.17981/econcuc.41.1.2020.org.1).

<a name=bib-Cano_2019></a>[[4]](#cite-Cano_2019) A. Cano, M. Gómez-Olmedo, and S. Moral. “A Bayesian approach to abrupt concept drift”. In: _Knowledge-Based Systems_ 185 (Dec. 2019), p. 104909. ISSN: 0950-7051. DOI: [10.1016/j.knosys.2019.104909](https://doi.org/10.1016%2Fj.knosys.2019.104909). URL: [http://dx.doi.org/10.1016/j.knosys.2019.104909](http://dx.doi.org/10.1016/j.knosys.2019.104909).

<a name=bib-Chaparro_Martinez_2023></a>[[5]](#cite-Chaparro_Martinez_2023) E. Chaparro-Martinez, C. Hernández-Domínguez, and E. Carrasquero-Rodríguez. “Producción científica y gestión editorial de la revista Ciencia Unemi”. In: _CIENCIA UNEMI_ 16.43 (Sep. 2023), p. 35–47. ISSN: 1390-4272. DOI: [10.29076/issn.2528-7737vol16iss43.2023pp35-47p](https://doi.org/10.29076%2Fissn.2528-7737vol16iss43.2023pp35-47p). URL: [http://dx.doi.org/10.29076/issn.2528-7737vol16iss43.2023pp35-47p](http://dx.doi.org/10.29076/issn.2528-7737vol16iss43.2023pp35-47p).

<a name=bib-Chukhrova_2021></a>[[6]](#cite-Chukhrova_2021) N. Chukhrova and A. Johannssen. “Fuzzy hypothesis testing: Systematic review and bibliography”. In: _Applied Soft Computing_ 106 (Jul. 2021), p. 107331. ISSN: 1568-4946. DOI: [10.1016/j.asoc.2021.107331](https://doi.org/10.1016%2Fj.asoc.2021.107331). URL: [http://dx.doi.org/10.1016/j.asoc.2021.107331](http://dx.doi.org/10.1016/j.asoc.2021.107331).

<a name=bib-Cornejo_2020></a>[[7]](#cite-Cornejo_2020) M. E. Cornejo, D. Lobo, and J. Medina. “Extended multi-adjoint logic programming”. In: _Fuzzy Sets and Systems_ 388 (Jun. 2020), p. 124–145. ISSN: 0165-0114. DOI: [10.1016/j.fss.2019.03.016](https://doi.org/10.1016%2Fj.fss.2019.03.016). URL: [http://dx.doi.org/10.1016/j.fss.2019.03.016](http://dx.doi.org/10.1016/j.fss.2019.03.016).

<a name=bib-Cornejo_2024></a>[[8]](#cite-Cornejo_2024) M. E. Cornejo, D. Lobo, and J. Medina. “Stratified extended multi-adjoint logic programming”. In: _Fuzzy Sets and Systems_ 492 (Sep. 2024), p. 109064. ISSN: 0165-0114. DOI: [10.1016/j.fss.2024.109064](https://doi.org/10.1016%2Fj.fss.2024.109064). URL: [http://dx.doi.org/10.1016/j.fss.2024.109064](http://dx.doi.org/10.1016/j.fss.2024.109064).

<a name=bib-Cornejo_2021></a>[[9]](#cite-Cornejo_2021) M. E. Cornejo, J. Medina, and E. Ramírez-Poussa. “Algebraic structure and characterization of adjoint triples”. In: _Fuzzy Sets and Systems_ 425 (Nov. 2021), p. 117–139. ISSN: 0165-0114. DOI: [10.1016/j.fss.2021.02.002](https://doi.org/10.1016%2Fj.fss.2021.02.002). URL: [http://dx.doi.org/10.1016/j.fss.2021.02.002](http://dx.doi.org/10.1016/j.fss.2021.02.002).

<a name=bib-Cricelli_2021></a>[[10]](#cite-Cricelli_2021) L. Cricelli, M. Grimaldi, and S. Vermicelli. “Crowdsourcing and open innovation: a systematic literature review, an integrated framework and a research agenda”. In: _Review of Managerial Science_ 16.5 (Jul. 2021), p. 1269–1310. ISSN: 1863-6691. DOI: [10.1007/s11846-021-00482-9](https://doi.org/10.1007%2Fs11846-021-00482-9). URL: [http://dx.doi.org/10.1007/s11846-021-00482-9](http://dx.doi.org/10.1007/s11846-021-00482-9).

<a name=bib-D_az_Moreno_2022></a>[[11]](#cite-D_az_Moreno_2022) J. C. Díaz-Moreno, J. Medina, and J. R. Portillo. “Fuzzy logic programs as hypergraphs. Termination results”. In: _Fuzzy Sets and Systems_ 445 (Sep. 2022), p. 22–42. ISSN: 0165-0114. DOI: [10.1016/j.fss.2022.02.001](https://doi.org/10.1016%2Fj.fss.2022.02.001). URL: [http://dx.doi.org/10.1016/j.fss.2022.02.001](http://dx.doi.org/10.1016/j.fss.2022.02.001).

<a name=bib-Duque_2019></a>[[12]](#cite-Duque_2019) P. Duque and L. Cervantes-Cervantes. “Responsabilidad Social Universitaria: una revisión sistemática y análisis bibliométrico”. In: _Estudios Gerenciales_ (Dec. 2019), p. 451–464. ISSN: 0123-5923. DOI: [10.18046/j.estger.2019.153.3389](https://doi.org/10.18046%2Fj.estger.2019.153.3389). URL: [http://dx.doi.org/10.18046/j.estger.2019.153.3389](http://dx.doi.org/10.18046/j.estger.2019.153.3389).

<a name=bib-Montes_2018></a>[[13]](#cite-Montes_2018) I. Montes, E. Miranda, and P. Vicig. “2-Monotone outer approximations of coherent lower probabilities”. In: _International Journal of Approximate Reasoning_ 101 (Oct. 2018), p. 181–205. ISSN: 0888-613X. DOI: [10.1016/j.ijar.2018.07.004](https://doi.org/10.1016%2Fj.ijar.2018.07.004). URL: [http://dx.doi.org/10.1016/j.ijar.2018.07.004](http://dx.doi.org/10.1016/j.ijar.2018.07.004).

<a name=bib-P_kala_2023></a>[[14]](#cite-P_kala_2023) B. Pękala, K. Garwol, J. Czuma, et al. “Early detection of the risk of depressive episodes using a proprietary diagnostic test by new epistemic similarity measures”. In: _Applied Soft Computing_ 148 (Nov. 2023), p. 110910. ISSN: 1568-4946. DOI: [10.1016/j.asoc.2023.110910](https://doi.org/10.1016%2Fj.asoc.2023.110910). URL: [http://dx.doi.org/10.1016/j.asoc.2023.110910](http://dx.doi.org/10.1016/j.asoc.2023.110910).

<a name=bib-Rueda_2020></a>[[15]](#cite-Rueda_2020) R. Rueda, L. Ruiz, M. Cuéllar, et al. “An Ant Colony Optimization approach for symbolic regression using Straight Line Programs. Application to energy consumption modelling”. In: _International Journal of Approximate Reasoning_ 121 (Jun. 2020), p. 23–38. ISSN: 0888-613X. DOI: [10.1016/j.ijar.2020.03.005](https://doi.org/10.1016%2Fj.ijar.2020.03.005). URL: [http://dx.doi.org/10.1016/j.ijar.2020.03.005](http://dx.doi.org/10.1016/j.ijar.2020.03.005).

<a name=bib-Trejos_Salazar_2021></a>[[16]](#cite-Trejos_Salazar_2021) D. F. Trejos-Salazar, P. L. Duque-Hurtado, L. A. Montoya-Restrepo, et al. “Neuroeconomía: una revisión basada en técnicas de mapeo científico”. In: _Revista de Investigación, Desarrollo e Innovación_ 11.2 (Feb. 2021), p. 243–260. ISSN: 2027-8306. DOI: [10.19053/20278306.v11.n2.2021.12754](https://doi.org/10.19053%2F20278306.v11.n2.2021.12754). URL: [http://dx.doi.org/10.19053/20278306.v11.n2.2021.12754](http://dx.doi.org/10.19053/20278306.v11.n2.2021.12754).

<a name=bib-Valverde_Albacete_2021></a>[[17]](#cite-Valverde_Albacete_2021) F. J. Valverde-Albacete and C. Peláez-Moreno. “Four-Fold Formal Concept Analysis Based on Complete Idempotent Semifields”. In: _Mathematics_ 9.2 (Jan. 2021), p. 173. ISSN: 2227-7390. DOI: [10.3390/math9020173](https://doi.org/10.3390%2Fmath9020173). URL: [http://dx.doi.org/10.3390/math9020173](http://dx.doi.org/10.3390/math9020173).

