---
title: Relational fuzzy Galois connections
author:
- <a href='/people/staff/ipcabrera/' style='color:rgb(100,0,50);'>Inma P. Cabrera</a>
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '2017'
categories: uncategorised
slug: 2017/ReFuGaCo
details: Joint 17th World Congress of International Fuzzy Systems Association and
  9th International Conference on Soft Computing and Intelligent Systems, {IFSA-SCIS}
  2017, Otsu, Japan, June 27-30, 2017 , pages 1--6.
doi: 10.1109/IFSA-SCIS.2017.8023288
---



# Abstract


We propose a suitable generalization of the notion of Galois connection whose components are fuzzy relations. We prove that the construction embeds Yao's notion of fuzzy Galois connection as a particular case. Although the natural framework for the proposed notion is that of fuzzy preposets, we also prove that it behaves properly with respect to the formation of quotient with respect to the fuzzy symmetric kernel relation.








# Citation
Please, cite this work as:


<a name=bib-Cabrera2017b></a>[[CCO17]](#cite-Cabrera2017b) I. P. Cabrera, P. Cordero, and M. Ojeda-Aciego. “Relational fuzzy Galois connections”. In: _Joint 17th World Congress of International Fuzzy Systems Association and 9th International Conference on Soft Computing and Intelligent Systems, IFSA-SCIS 2017, Otsu, Japan, June 27-30, 2017_. IEEE, 2017, pp. 1-6. DOI: [10.1109/IFSA-SCIS.2017.8023288](https://doi.org/10.1109%2FIFSA-SCIS.2017.8023288). URL: [https://doi.org/10.1109/IFSA-SCIS.2017.8023288](https://doi.org/10.1109/IFSA-SCIS.2017.8023288).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Cabrera2017b,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Inma P. Cabrera and Pablo Cordero and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Joint 17th World Congress of International Fuzzy Systems Association and 9th International Conference on Soft Computing and Intelligent Systems, {IFSA-SCIS} 2017, Otsu, Japan, June 27-30, 2017},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Relational fuzzy Galois connections},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2017},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {1--6},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {{IEEE}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/ifsa/CabreraCO17.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1109/IFSA-SCIS.2017.8023288},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Wed, 16 Oct 2019 14:14:50 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1109/IFSA-SCIS.2017.8023288},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1109/IFSA-SCIS.2017.8023288" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1109/IFSA-SCIS.2017.8023288" class="plumx-details" data-site="plum" data-hide-when-empty="true">Relational fuzzy Galois connections</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1109/IFSA-SCIS.2017.8023288"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```





