---
title: '{FD3:} {A} Functional Dependencies Data Dictionary'
author:
- <a href='/people/staff/enciso/' style='color:rgb(100,0,50);'>Manuel Enciso</a>
- <a href='/people/staff/amora/' style='color:rgb(100,0,50);'>Ángel Mora</a>
date: '2002'
categories: uncategorised
slug: 2002/FuDeDaDi
details: '{ICEIS} 2002, Proceedings of the 4st International Conference on Enterprise
  Information Systems, Ciudad Real, Spain, April 2-6, 2002 , pages 807--810.'
---



# Abstract


In this paper, we propose the use of a Functional Dependencies Data Dictionary (FD3) to facilitate the integration of Heterogeneous Systems. The heart of this approach is the notion of Functional Dependence (FD). We present a formal language, the Extended Functional Dependencies (EFD) Logic suitable to carry out integration tasks. The set of FDs contained in the data model is directly translated into a EFD logic theory. FD3 integrates the EFD logic sub-theories in a unique and unified EFD logic theory. EFD axiomatic system eases the design of automatic integration process. To communicate the information of the EFD logic theory, we introduce a High Level Functional Dependencies (HLFD) Data Model which is used in a similar way as the Entity/Relationship Model. The HLFD data model can be deduced automatically from EFD logic theory.








# Citation
Please, cite this work as:


<a name=bib-Enciso2002></a>[[EM02]](#cite-Enciso2002) M. Enciso and Á. Mora. “FD3: A Functional Dependencies Data Dictionary”. In: _ICEIS 2002, Proceedings of the 4st International Conference on Enterprise Information Systems, Ciudad Real, Spain, April 2-6, 2002_. 2002, pp. 807-810.

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Enciso2002,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Manuel Enciso and {\a'A}ngel Mora},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {{ICEIS} 2002, Proceedings of the 4st International Conference on Enterprise Information Systems, Ciudad Real, Spain, April 2-6, 2002},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {{FD3:} {A} Functional Dependencies Data Dictionary},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2002},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {807--810},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {In this paper, we propose the use of a Functional Dependencies Data Dictionary (FD3) to facilitate the integration of Heterogeneous Systems. The heart of this approach is the notion of Functional Dependence (FD). We present a formal language, the Extended Functional Dependencies (EFD) Logic suitable to carry out integration tasks. The set of FDs contained in the data model is directly translated into a EFD logic theory. FD3 integrates the EFD logic sub-theories in a unique and unified EFD logic theory. EFD axiomatic system eases the design of automatic integration process. To communicate the information of the EFD logic theory, we introduce a High Level Functional Dependencies (HLFD) Data Model which is used in a similar way as the Entity/Relationship Model. The HLFD data model can be deduced automatically from EFD logic theory.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/iceis/EncisoM02.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 23 Sep 2022 01:00:00 +0200},<br>}

:::








