---
title: Reducing the search space by closure and simplification paradigms
author:
- Fernando Benito Picazo
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/enciso/' style='color:rgb(100,0,50);'>Manuel Enciso</a>
- <a href='/people/staff/amora/' style='color:rgb(100,0,50);'>Ángel Mora</a>
date: '2017'
categories: uncategorised
slug: 2017/ReSeSpClSiPa
details: J. Supercomput. vol. 73 (1), pages 75--87.
doi: 10.1007/S11227-016-1622-1
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Picazo2017></a>[[Pic+17]](#cite-Picazo2017) F. B. Picazo, P. Cordero, M. Enciso, et al. “Reducing the search space by closure and simplification paradigms”. In: _J. Supercomput._ 73.1 (2017), pp. 75-87. DOI: [10.1007/S11227-016-1622-1](https://doi.org/10.1007%2FS11227-016-1622-1). URL: [https://doi.org/10.1007/s11227-016-1622-1](https://doi.org/10.1007/s11227-016-1622-1).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{Picazo2017,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Fernando Benito Picazo and Pablo Cordero and Manuel Enciso and {\a'A}ngel Mora},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {J. Supercomput.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Reducing the search space by closure and simplification paradigms},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2017},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number = {1},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {75--87},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {73},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/tjs/PicazoCEM17.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/S11227-016-1622-1},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Wed, 28 Sep 2022 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/s11227-016-1622-1},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/S11227-016-1622-1" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/S11227-016-1622-1" class="plumx-details" data-site="plum" data-hide-when-empty="true">Reducing the search space by closure and simplification paradigms</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1007/S11227-016-1622-1"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Benito_Picazo_2018></a>[[1]](#cite-Benito_Picazo_2018) F. Benito-Picazo, P. Cordero, M. Enciso, et al. “Minimal generators, an affordable approach by means of massive computation”. In: _The Journal of Supercomputing_ 75.3 (Jun. 2018), p. 1350–1367. ISSN: 1573-0484. DOI: [10.1007/s11227-018-2453-z](https://doi.org/10.1007%2Fs11227-018-2453-z). URL: [http://dx.doi.org/10.1007/s11227-018-2453-z](http://dx.doi.org/10.1007/s11227-018-2453-z).

<a name=bib-Takhanov_2022></a>[[2]](#cite-Takhanov_2022) R. Takhanov. “The algebraic structure of the densification and the sparsification tasks for CSPs”. In: _Constraints_ 28.1 (Dec. 2022), p. 13–44. ISSN: 1572-9354. DOI: [10.1007/s10601-022-09340-1](https://doi.org/10.1007%2Fs10601-022-09340-1). URL: [http://dx.doi.org/10.1007/s10601-022-09340-1](http://dx.doi.org/10.1007/s10601-022-09340-1).

