---
title: Fuzzy logic programming via multilattices
author:
- Jesús Medina
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
- Jorge Ruiz-Calvi~no
date: '2007'
categories: uncategorised
slug: 2007/FuLoPrViMu
details: Fuzzy Sets Syst. vol. 158 (6), pages 674--688.
doi: 10.1016/J.FSS.2006.11.006
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Medina2007></a>[[MOR07]](#cite-Medina2007) J. Medina, M. Ojeda-Aciego, and J. Ruiz-Calvi~no. “Fuzzy logic programming via multilattices”. In: _Fuzzy Sets Syst._ 158.6 (2007), pp. 674-688. DOI: [10.1016/J.FSS.2006.11.006](https://doi.org/10.1016%2FJ.FSS.2006.11.006). URL: [https://doi.org/10.1016/j.fss.2006.11.006](https://doi.org/10.1016/j.fss.2006.11.006).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{Medina2007,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Jes{\a'u}s Medina and Manuel Ojeda-Aciego and Jorge Ruiz-Calvi~no},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Fuzzy Sets Syst.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Fuzzy logic programming via multilattices},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2007},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number = {6},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {674--688},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {158},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/fss/MedinaOR07.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1016/J.FSS.2006.11.006},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Sun, 06 Oct 2024 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1016/j.fss.2006.11.006},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1016/J.FSS.2006.11.006" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1016/J.FSS.2006.11.006" class="plumx-details" data-site="plum" data-hide-when-empty="true">Fuzzy logic programming via multilattices</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1016/J.FSS.2006.11.006"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Cabrera_2009></a>[[1]](#cite-Cabrera_2009) I. P. Cabrera, P. Cordero, G. Gutiérrez, et al. “Congruence relations on some hyperstructures”. In: _Annals of Mathematics and Artificial Intelligence_ 56.3–4 (Jul. 2009), p. 361–370. ISSN: 1573-7470. DOI: [10.1007/s10472-009-9146-5](https://doi.org/10.1007%2Fs10472-009-9146-5). URL: [http://dx.doi.org/10.1007/s10472-009-9146-5](http://dx.doi.org/10.1007/s10472-009-9146-5).

<a name=bib-Cabrera_20091></a>[[2]](#cite-Cabrera_20091) I. P. Cabrera, P. Cordero, G. Gutiérrez, et al. “Fuzzy congruence relations on nd-groupoids”. In: _International Journal of Computer Mathematics_ 86.10–11 (Nov. 2009), p. 1684–1695. ISSN: 1029-0265. DOI: [10.1080/00207160902721797](https://doi.org/10.1080%2F00207160902721797). URL: [http://dx.doi.org/10.1080/00207160902721797](http://dx.doi.org/10.1080/00207160902721797).

<a name=bib-Cabrera_2011></a>[[3]](#cite-Cabrera_2011) I. P. Cabrera, P. Cordero, and M. Ojeda-Aciego. “Non-deterministic Algebraic Structures for Soft Computing”. In: _Advances in Computational Intelligence_. Springer Berlin Heidelberg, 2011, p. 437–444. ISBN: 9783642214981. DOI: [10.1007/978-3-642-21498-1_55](https://doi.org/10.1007%2F978-3-642-21498-1_55). URL: [http://dx.doi.org/10.1007/978-3-642-21498-1_55](http://dx.doi.org/10.1007/978-3-642-21498-1_55).

<a name=bib-Cabrera_2010></a>[[4]](#cite-Cabrera_2010) I. Cabrera, P. Cordero, G. Gutiérrez, et al. “A coalgebraic approach to non-determinism: Applications to multilattices”. In: _Information Sciences_ 180.22 (Nov. 2010), p. 4323–4335. ISSN: 0020-0255. DOI: [10.1016/j.ins.2010.07.002](https://doi.org/10.1016%2Fj.ins.2010.07.002). URL: [http://dx.doi.org/10.1016/j.ins.2010.07.002](http://dx.doi.org/10.1016/j.ins.2010.07.002).

<a name=bib-Cabrera_2012></a>[[5]](#cite-Cabrera_2012) I. Cabrera, P. Cordero, G. Gutiérrez, et al. “Finitary coalgebraic multisemilattices and multilattices”. In: _Applied Mathematics and Computation_ 219.1 (Sep. 2012), p. 31–44. ISSN: 0096-3003. DOI: [10.1016/j.amc.2011.10.081](https://doi.org/10.1016%2Fj.amc.2011.10.081). URL: [http://dx.doi.org/10.1016/j.amc.2011.10.081](http://dx.doi.org/10.1016/j.amc.2011.10.081).

<a name=bib-Cabrera_2014></a>[[6]](#cite-Cabrera_2014) I. Cabrera, P. Cordero, G. Gutiérrez, et al. “On residuation in multilattices: Filters, congruences, and homomorphisms”. In: _Fuzzy Sets and Systems_ 234 (Jan. 2014), p. 1–21. ISSN: 0165-0114. DOI: [10.1016/j.fss.2013.04.002](https://doi.org/10.1016%2Fj.fss.2013.04.002). URL: [http://dx.doi.org/10.1016/j.fss.2013.04.002](http://dx.doi.org/10.1016/j.fss.2013.04.002).

<a name=bib-Cordero_2011></a>[[7]](#cite-Cordero_2011) P. Cordero, M. Enciso, A. Mora, et al. “Specification and inference of fuzzy attributes”. In: _2011 IEEE Symposium on Foundations of Computational Intelligence (FOCI)_. IEEE, Apr. 2011, p. 107–114. DOI: [10.1109/foci.2011.5949472](https://doi.org/10.1109%2Ffoci.2011.5949472). URL: [http://dx.doi.org/10.1109/foci.2011.5949472](http://dx.doi.org/10.1109/foci.2011.5949472).

<a name=bib-Cornejo_2020></a>[[8]](#cite-Cornejo_2020) M. E. Cornejo, D. Lobo, and J. Medina. “Solving Generalized Equations with Bounded Variables and Multiple Residuated Operators”. In: _Mathematics_ 8.11 (Nov. 2020), p. 1992. ISSN: 2227-7390. DOI: [10.3390/math8111992](https://doi.org/10.3390%2Fmath8111992). URL: [http://dx.doi.org/10.3390/math8111992](http://dx.doi.org/10.3390/math8111992).

<a name=bib-Cornejo_2016></a>[[9]](#cite-Cornejo_2016) M. E. Cornejo, J. Medina, and E. Ramírez-Poussa. “Adjoint negations, more than residuated negations”. In: _Information Sciences_ 345 (Jun. 2016), p. 355–371. ISSN: 0020-0255. DOI: [10.1016/j.ins.2016.01.038](https://doi.org/10.1016%2Fj.ins.2016.01.038). URL: [http://dx.doi.org/10.1016/j.ins.2016.01.038](http://dx.doi.org/10.1016/j.ins.2016.01.038).

<a name=bib-Cornejo_2015></a>[[10]](#cite-Cornejo_2015) M. E. Cornejo, J. Medina, and E. Ramírez-Poussa. “Multi-adjoint algebras versus non-commutative residuated structures”. In: _International Journal of Approximate Reasoning_ 66 (Nov. 2015), p. 119–138. ISSN: 0888-613X. DOI: [10.1016/j.ijar.2015.08.003](https://doi.org/10.1016%2Fj.ijar.2015.08.003). URL: [http://dx.doi.org/10.1016/j.ijar.2015.08.003](http://dx.doi.org/10.1016/j.ijar.2015.08.003).

<a name=bib-D_az_2013></a>[[11]](#cite-D_az_2013) J. C. Díaz and J. Medina. “Multi-adjoint relation equations: Definition, properties and solutions using concept lattices”. In: _Information Sciences_ 253 (Dec. 2013), p. 100–109. ISSN: 0020-0255. DOI: [10.1016/j.ins.2013.07.024](https://doi.org/10.1016%2Fj.ins.2013.07.024). URL: [http://dx.doi.org/10.1016/j.ins.2013.07.024](http://dx.doi.org/10.1016/j.ins.2013.07.024).

<a name=bib-Di_kouam_Fotso_2024></a>[[12]](#cite-Di_kouam_Fotso_2024) L. É. Diékouam Fotso, C. P. Kengne, and D. C. Awouafack. “Fuzzy prime filter theorem in multilattices”. In: _Fuzzy Sets and Systems_ 497 (Dec. 2024), p. 109148. ISSN: 0165-0114. DOI: [10.1016/j.fss.2024.109148](https://doi.org/10.1016%2Fj.fss.2024.109148). URL: [http://dx.doi.org/10.1016/j.fss.2024.109148](http://dx.doi.org/10.1016/j.fss.2024.109148).

<a name=bib-Julian_Iranzo_2021></a>[[13]](#cite-Julian_Iranzo_2021) P. Julian-Iranzo and F. Saenz-Perez. “Proximity-Based Unification: An Efficient Implementation Method”. In: _IEEE Transactions on Fuzzy Systems_ 29.5 (May. 2021), p. 1238–1251. ISSN: 1941-0034. DOI: [10.1109/tfuzz.2020.2973129](https://doi.org/10.1109%2Ftfuzz.2020.2973129). URL: [http://dx.doi.org/10.1109/tfuzz.2020.2973129](http://dx.doi.org/10.1109/tfuzz.2020.2973129).

<a name=bib-Juli_n_Iranzo_2023></a>[[14]](#cite-Juli_n_Iranzo_2023) P. Julián-Iranzo and F. Sáenz-Pérez. “Bousi<mml:math xmlns:mml="http://www.w3.org/1998/Math/MathML" altimg="si139.svg" display="inline" id="d1e1172"><mml:mo>∼</mml:mo></mml:math>Prolog: Design and implementation of a proximity-based fuzzy logic programming language”. In: _Expert Systems with Applications_ 213 (Mar. 2023), p. 118858. ISSN: 0957-4174. DOI: [10.1016/j.eswa.2022.118858](https://doi.org/10.1016%2Fj.eswa.2022.118858). URL: [http://dx.doi.org/10.1016/j.eswa.2022.118858](http://dx.doi.org/10.1016/j.eswa.2022.118858).

<a name=bib-Medina_Moreno_2013></a>[[15]](#cite-Medina_Moreno_2013) J. Medina-Moreno, M. Ojeda-Aciego, and J. Ruiz-Calviño. “Concept-Forming Operators on Multilattices”. In: _Formal Concept Analysis_. Springer Berlin Heidelberg, 2013, p. 203–215. ISBN: 9783642383175. DOI: [10.1007/978-3-642-38317-5_13](https://doi.org/10.1007%2F978-3-642-38317-5_13). URL: [http://dx.doi.org/10.1007/978-3-642-38317-5_13](http://dx.doi.org/10.1007/978-3-642-38317-5_13).

<a name=bib-Medina_2016></a>[[16]](#cite-Medina_2016) J. Medina, M. Ojeda-Aciego, J. Pócs, et al. “On the Dedekind–MacNeille completion and formal concept analysis based on multilattices”. In: _Fuzzy Sets and Systems_ 303 (Nov. 2016), p. 1–20. ISSN: 0165-0114. DOI: [10.1016/j.fss.2016.01.007](https://doi.org/10.1016%2Fj.fss.2016.01.007). URL: [http://dx.doi.org/10.1016/j.fss.2016.01.007](http://dx.doi.org/10.1016/j.fss.2016.01.007).

<a name=bib-Morcillo_2012></a>[[17]](#cite-Morcillo_2012) P. J. Morcillo, G. Moreno, J. Penabad, et al. “Dedekind–MacNeille completion and Cartesian product of multi-adjoint lattices”. In: _International Journal of Computer Mathematics_ 89.13–14 (Sep. 2012), p. 1742–1752. ISSN: 1029-0265. DOI: [10.1080/00207160.2012.689826](https://doi.org/10.1080%2F00207160.2012.689826). URL: [http://dx.doi.org/10.1080/00207160.2012.689826](http://dx.doi.org/10.1080/00207160.2012.689826).

<a name=bib-Moreno_2014></a>[[18]](#cite-Moreno_2014) G. Moreno, J. Penabad, and C. Vázquez. “Beyond multi-adjoint logic programming”. In: _International Journal of Computer Mathematics_ 92.9 (Nov. 2014), p. 1956–1975. ISSN: 1029-0265. DOI: [10.1080/00207160.2014.975218](https://doi.org/10.1080%2F00207160.2014.975218). URL: [http://dx.doi.org/10.1080/00207160.2014.975218](http://dx.doi.org/10.1080/00207160.2014.975218).

<a name=bib-Nguepy_Dongmo_2024></a>[[19]](#cite-Nguepy_Dongmo_2024) G. Nguepy Dongmo, B. B. Koguep Njionou, L. Kwuida, et al. “Multilattice as the set of truth values for fuzzy rough sets”. In: _Journal of Applied Non-Classical Logics_ (Jul. 2024), p. 1–20. ISSN: 1958-5780. DOI: [10.1080/11663081.2024.2373016](https://doi.org/10.1080%2F11663081.2024.2373016). URL: [http://dx.doi.org/10.1080/11663081.2024.2373016](http://dx.doi.org/10.1080/11663081.2024.2373016).

<a name=bib-Nguepy_Dongmo_2023></a>[[20]](#cite-Nguepy_Dongmo_2023) G. Nguepy Dongmo, B. B. Koguep Njionou, L. Kwuida, et al. “Rough Fuzzy Concept Analysis via Multilattice”. In: _Rough Sets_. Springer Nature Switzerland, 2023, p. 495–508. ISBN: 9783031509599. DOI: [10.1007/978-3-031-50959-9_34](https://doi.org/10.1007%2F978-3-031-50959-9_34). URL: [http://dx.doi.org/10.1007/978-3-031-50959-9_34](http://dx.doi.org/10.1007/978-3-031-50959-9_34).

<a name=bib-Nguepy_Dongmo_2025></a>[[21]](#cite-Nguepy_Dongmo_2025) G. Nguepy Dongmo, B. Koguep Njionou, L. Kwuida, et al. “Roughness in formal concept analysis via multilattices”. In: _Fuzzy Sets and Systems_ 500 (Jan. 2025), p. 109179. ISSN: 0165-0114. DOI: [10.1016/j.fss.2024.109179](https://doi.org/10.1016%2Fj.fss.2024.109179). URL: [http://dx.doi.org/10.1016/j.fss.2024.109179](http://dx.doi.org/10.1016/j.fss.2024.109179).

<a name=bib-Straccia_2009></a>[[22]](#cite-Straccia_2009) U. Straccia, M. Ojeda-Aciego, and C. V. Damásio. “On Fixed-Points of Multivalued Functions on Complete Lattices and Their Application to Generalized Logic Programs”. In: _SIAM Journal on Computing_ 38.5 (Jan. 2009), p. 1881–1911. ISSN: 1095-7111. DOI: [10.1137/070695976](https://doi.org/10.1137%2F070695976). URL: [http://dx.doi.org/10.1137/070695976](http://dx.doi.org/10.1137/070695976).

<a name=bib-Xu_2019></a>[[23]](#cite-Xu_2019) Y. Xu, L. Liu, and X. Zhang. “Multilattices on typical hesitant fuzzy sets”. In: _Information Sciences_ 491 (Jul. 2019), p. 63–73. ISSN: 0020-0255. DOI: [10.1016/j.ins.2019.03.078](https://doi.org/10.1016%2Fj.ins.2019.03.078). URL: [http://dx.doi.org/10.1016/j.ins.2019.03.078](http://dx.doi.org/10.1016/j.ins.2019.03.078).

