---
title: 'On Adjunctions between Fuzzy Preordered Sets: Necessary Conditions'
author:
- Francisca García-Pardo
- <a href='/people/staff/ipcabrera/' style='color:rgb(100,0,50);'>Inma P. Cabrera</a>
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '2014'
categories: uncategorised
slug: 2014/AdFuPrNeCo
details: Rough Sets and Current Trends in Computing - 9th International Conference,
  {RSCTC} 2014, Granada and Madrid, Spain, July 9-13, 2014. Proceedings , Lecture
  Notes in Computer Science vol. 8536, pages 211--221.
doi: 10.1007/978-3-319-08644-6_22
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-GarciaPardo2014c></a>[[Gar+14]](#cite-GarciaPardo2014c) F. Garc\'\ia-Pardo, I. P. Cabrera, P. Cordero, et al. “On Adjunctions between Fuzzy Preordered Sets: Necessary Conditions”. In: _Rough Sets and Current Trends in Computing - 9th International Conference, RSCTC 2014, Granada and Madrid, Spain, July 9-13, 2014. Proceedings_. Ed. by C. Cornelis, M. Kryszkiewicz, D. Slezak, E. M. Ruiz, R. Bello and L. Shang. Vol. 8536. Lecture Notes in Computer Science. Springer, 2014, pp. 211-221. DOI: [10.1007/978-3-319-08644-6\_22](https://doi.org/10.1007%2F978-3-319-08644-6%5C_22). URL: [https://doi.org/10.1007/978-3-319-08644-6\_22](https://doi.org/10.1007/978-3-319-08644-6\_22).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{GarciaPardo2014c,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Francisca Garc\'\ia-Pardo and Inma P. Cabrera and Pablo Cordero and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Rough Sets and Current Trends in Computing - 9th International Conference, {RSCTC} 2014, Granada and Madrid, Spain, July 9-13, 2014. Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {On Adjunctions between Fuzzy Preordered Sets: Necessary Conditions},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2014},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Chris Cornelis and Marzena Kryszkiewicz and Dominik Slezak and Ernestina Menasalvas Ruiz and Rafael Bello and Lin Shang},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {211--221},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {8536},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/rsctc/Garcia-PardoCCO14.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/978-3-319-08644-6\_22},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Sat, 30 Sep 2023 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/978-3-319-08644-6\_22},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/978-3-319-08644-6_22" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/978-3-319-08644-6_22" class="plumx-details" data-site="plum" data-hide-when-empty="true">On Adjunctions between Fuzzy Preordered Sets: Necessary Conditions</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1007/978-3-319-08644-6_22"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Garcia_Pardo_2015></a>[[1]](#cite-Garcia_Pardo_2015) F. Garcia-Pardo, I. Cabrera, P. Cordero, et al. “On Fuzzy Preordered Sets and Monotone Galois Connections”. In: _2015 IEEE Symposium Series on Computational Intelligence_. IEEE, Dec. 2015, p. 990–994. DOI: [10.1109/ssci.2015.144](https://doi.org/10.1109%2Fssci.2015.144). URL: [http://dx.doi.org/10.1109/ssci.2015.144](http://dx.doi.org/10.1109/ssci.2015.144).

