---
title: On (fuzzy) closure systems in complete fuzzy lattices
author:
- <a href='/people/staff/manuojeda/' style='color:rgb(100,0,50);'>Manuel Ojeda Hernández</a>
- <a href='/people/staff/ipcabrera/' style='color:rgb(100,0,50);'>Inma P. Cabrera</a>
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
date: '2021'
categories: uncategorised
slug: 2021/ClSyCoFuLa
details: 30th {IEEE} International Conference on Fuzzy Systems, {FUZZ-IEEE} 2021,
  Luxembourg, July 11-14, 2021 , pages 1--6.
doi: 10.1109/FUZZ45933.2021.9494404
---



# Abstract


Two alternative definitions of closure system in complete fuzzy lattices are introduced, first as a crisp set and then as a fuzzy one. It is valuated in a complete Heyting algebra and follows the classical definition on complete lattices. The classical bijection between closure systems and fuzzy closure operators is preserved. Then, the notion is compared with the most used definition given by Bělohlávek on the fuzzy powerset lattice.








# Citation
Please, cite this work as:


<a name=bib-OjedaHernandez2021></a>[[Oje+21]](#cite-OjedaHernandez2021) M. Ojeda-Hernández, I. P. Cabrera, P. Cordero, et al. “On (fuzzy) closure systems in complete fuzzy lattices”. In: _30th IEEE International Conference on Fuzzy Systems, FUZZ-IEEE 2021, Luxembourg, July 11-14, 2021_. IEEE, 2021, pp. 1-6. DOI: [10.1109/FUZZ45933.2021.9494404](https://doi.org/10.1109%2FFUZZ45933.2021.9494404). URL: [https://doi.org/10.1109/FUZZ45933.2021.9494404](https://doi.org/10.1109/FUZZ45933.2021.9494404).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{OjedaHernandez2021,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Manuel Ojeda-Hern{\a'a}ndez and Inma P. Cabrera and Pablo Cordero and Emilio Mu~noz-Velasco},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {30th {IEEE} International Conference on Fuzzy Systems, {FUZZ-IEEE} 2021, Luxembourg, July 11-14, 2021},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {On (fuzzy) closure systems in complete fuzzy lattices},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2021},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {1--6},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {{IEEE}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/fuzzIEEE/Ojeda-Hernandez21.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1109/FUZZ45933.2021.9494404},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Tue, 21 Mar 2023 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1109/FUZZ45933.2021.9494404},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1109/FUZZ45933.2021.9494404" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1109/FUZZ45933.2021.9494404" class="plumx-details" data-site="plum" data-hide-when-empty="true">On (fuzzy) closure systems in complete fuzzy lattices</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1109/FUZZ45933.2021.9494404"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Ojeda_Hern_ndez_2021></a>[[1]](#cite-Ojeda_Hern_ndez_2021) M. Ojeda-Hernández, I. P. Cabrera, P. Cordero, et al. “Closure Systems as a Fuzzy Extension of Meet-subsemilattices”. In: _Joint Proceedings of the 19th World Congress of the International Fuzzy Systems Association (IFSA), the 12th Conference of the European Society for Fuzzy Logic and Technology (EUSFLAT), and the 11th International Summer School on Aggregation Operators (AGOP)_. ifsa-eusflat-agop-21. Atlantis Press, 2021. DOI: [10.2991/asum.k.210827.006](https://doi.org/10.2991%2Fasum.k.210827.006). URL: [http://dx.doi.org/10.2991/asum.k.210827.006](http://dx.doi.org/10.2991/asum.k.210827.006).

<a name=bib-Ojeda_Hern_ndez_20231></a>[[2]](#cite-Ojeda_Hern_ndez_20231) M. Ojeda-Hernández, I. P. Cabrera, P. Cordero, et al. “On Pseudointents in Fuzzy Formal Concept Analysis”. In: _Graph-Based Representation and Reasoning_. Springer Nature Switzerland, 2023, p. 36–40. ISBN: 9783031409608. DOI: [10.1007/978-3-031-40960-8_4](https://doi.org/10.1007%2F978-3-031-40960-8_4). URL: [http://dx.doi.org/10.1007/978-3-031-40960-8_4](http://dx.doi.org/10.1007/978-3-031-40960-8_4).

<a name=bib-Ojeda_Hern_ndez_2023></a>[[3]](#cite-Ojeda_Hern_ndez_2023) M. Ojeda-Hernández, I. P. Cabrera, P. Cordero, et al. “On the Commutative Diagrams Among Galois Connections Involved in Closure Structures”. In: _Formal Concept Analysis_. Springer Nature Switzerland, 2023, p. 49–63. ISBN: 9783031359491. DOI: [10.1007/978-3-031-35949-1_4](https://doi.org/10.1007%2F978-3-031-35949-1_4). URL: [http://dx.doi.org/10.1007/978-3-031-35949-1_4](http://dx.doi.org/10.1007/978-3-031-35949-1_4).

<a name=bib-Ojeda_Hern_ndez_2022></a>[[4]](#cite-Ojeda_Hern_ndez_2022) M. Ojeda-Hernández, I. P. Cabrera, P. Cordero, et al. “Relational Extension of Closure Structures”. In: _Information Processing and Management of Uncertainty in Knowledge-Based Systems_. Springer International Publishing, 2022, p. 77–86. ISBN: 9783031089718. DOI: [10.1007/978-3-031-08971-8_7](https://doi.org/10.1007%2F978-3-031-08971-8_7). URL: [http://dx.doi.org/10.1007/978-3-031-08971-8_7](http://dx.doi.org/10.1007/978-3-031-08971-8_7).

