---
author:
- E. Mérida-Casermeiro
- <a href='/people/staff/dominlopez/' style='color:rgb(100,0,50);'>Domingo López Rodríguez</a>
- J.M. Ortiz-de-Lazcano-Lobato
Status: Published
date: '2008-01-01'
slug: 2008-advancingai
title: An approach to artificial concept learning based on human concept learning
  by using artificial neural networks
categories: Neural networks
header_image: ~
details: Advancing Artificial Intelligence Through Biological Process Applications,
  <em>pp. 130-145</em>
doi: 10.4018/978-1-59904-996-0.ch008
link: 2008-advancingai/paper.pdf
project: ''
keywords: ''
---


# Abstract


In this chapter, two important issues concerning associative memory by neural networks are studied: a new model of hebbian learning, as well as the effect of the network capacity when retrieving patterns and performing clustering tasks. Particularly, an explanation of the energy function when the capacity is exceeded: the limitation in pattern storage implies that similar patterns are going to be identified by the network, therefore forming different clusters. This ability can be translated as an unsupervised learning of pattern clusters, with one major advantage over most clustering algorithms: the number of data classes is automatically learned, as confirmed by the experiments. Two methods to reinforce learning are proposed to improve the quality of the clustering, by enhancing the learning of patterns relationships. As a related issue, a study on the net capacity, depending on the number of neurons and possible outputs, is presented, and some interesting conclusions are commented.







# Citation
Please, cite this work as:


<a name=bib-MeridaCasermeiro2008></a>[[MLO08]](#cite-MeridaCasermeiro2008) E. Mérida-Casermeiro, D. López-Rodríguez, and J. Ortiz-de-Lazcano-Lobato. _An approach to artificial concept learning based on human concept learning by using artificial neural networks_. IGI Global, 2008, pp. 130-145. DOI: [10.4018/978-1-59904-996-0.ch008](https://doi.org/10.4018%2F978-1-59904-996-0.ch008). URL: [https://www.scopus.com/inward/record.uri?eid=2-s2.0-84899353027&doi=10.4018

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Book{MeridaCasermeiro2008,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {E. Mérida-Casermeiro and D. López-Rodríguez and J.M. Ortiz-de-Lazcano-Lobato},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {IGI Global},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {An approach to artificial concept learning based on human concept learning by using artificial neural networks},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2008},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {In this chapter, two important issues concerning associative memory by neural networks are studied: a new model of hebbian learning, as well as the effect of the network capacity when retrieving patterns and performing clustering tasks. Particularly, an explanation of the energy function when the capacity is exceeded: the limitation in pattern storage implies that similar patterns are going to be identified by the network, therefore forming different clusters. This ability can be translated as an unsupervised learning of pattern clusters, with one major advantage over most clustering algorithms: the number of data classes is automatically learned, as confirmed by the experiments. Two methods to reinforce learning are proposed to improve the quality of the clustering, by enhancing the learning of patterns relationships. As a related issue, a study on the net capacity, depending on the number of neurons and possible outputs, is presented, and some interesting conclusions are commented. © 2009, IGI Global.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  document_type = {Book Chapter},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.4018/978-1-59904-996-0.ch008},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Advancing Artificial Intelligence Through Biological Process Applications},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {130-145},<br>&nbsp;&nbsp;&nbsp;&nbsp;  source = {Scopus},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://www.scopus.com/inward/record.uri?eid=2-s2.0-84899353027&doi=10.4018%2f978-1-59904-996-0.ch008&partnerID=40&md5=9628e1467301f479b3293dc932c844b0},<br>}

:::


