---
author:
- Estrella Rodríguez-Lorenzo
- Karell Bertet
- Pablo Cordero
- Manuel Enciso
- Ángel Mora
Status: Published
date: '2018-11-20T00:00:00Z'
slug: 2018-dam
title: Direct-optimal basis computation by means of the fusion of simplification rules
categories:
- Simplification logic
- Formal concept analysis
header_image: ~
details: <em>Discrete Applied Mathematics</em> 249, pp. 106 - 119
doi: 10.1016/j.dam.2017.12.031
project: ~
keywords: Direct-optimal basis; Closure; Simplification Logic
---



# Abstract

The importance of the computation of direct bases of implications has been motivated by several authors in different areas. They emphasize the use of direct bases in several problems, where a large number of closures are needed. The more efficient the basis computation is, the better performance the methods solving these problems has. Here, we propose a new method, named SLgetdo, to calculate the direct-optimal basis. The main characteristic of SLgetdo is the full integration of simplification paradigm, providing a limited rise of the implicational set throughout its execution. We have showed the better behavior of SLgetdo in an empirical experiment. The general conclusion is that it improves the performance of previous methods, providing a better management of time and space resources.







# Citation
Please, cite this work as:


<a name=bib-RODRIGUEZLORENZO2018106></a>[[Rod+18]](#cite-RODRIGUEZLORENZO2018106) E. Rodríguez-Lorenzo, K. Bertet, P. Cordero, et al. “Direct-optimal basis computation by means of the fusion of simplification rules”. In: _Discrete Applied Mathematics_ 249 (2018). Concept Lattices and Applications: Recent Advances and New Opportunities, pp. 106-119. ISSN: 0166-218X. DOI: [https://doi.org/10.1016/j.dam.2017.12.031](https://doi.org/https%3A%2F%2Fdoi.org%2F10.1016%2Fj.dam.2017.12.031). URL: [https://www.sciencedirect.com/science/article/pii/S0166218X1730611X](https://www.sciencedirect.com/science/article/pii/S0166218X1730611X).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@article{RODRIGUEZLORENZO2018106,<br>&nbsp;&nbsp;&nbsp;&nbsp;title = {Direct-optimal basis computation by means of the fusion of simplification rules},<br>&nbsp;&nbsp;&nbsp;&nbsp;journal = {Discrete Applied Mathematics},<br>&nbsp;&nbsp;&nbsp;&nbsp;volume = {249},<br>&nbsp;&nbsp;&nbsp;&nbsp;pages = {106-119},<br>&nbsp;&nbsp;&nbsp;&nbsp;year = {2018},<br>&nbsp;&nbsp;&nbsp;&nbsp;note = {Concept Lattices and Applications: Recent Advances and New Opportunities},<br>&nbsp;&nbsp;&nbsp;&nbsp;issn = {0166-218X},<br>&nbsp;&nbsp;&nbsp;&nbsp;doi = {https://doi.org/10.1016/j.dam.2017.12.031},<br>&nbsp;&nbsp;&nbsp;&nbsp;url = {https://www.sciencedirect.com/science/article/pii/S0166218X1730611X},<br>&nbsp;&nbsp;&nbsp;&nbsp;author = {Estrella Rodríguez-Lorenzo and Karell Bertet and Pablo Cordero and Manuel Enciso and Ángel Mora},<br>&nbsp;&nbsp;&nbsp;&nbsp;keywords = {Direct-optimal basis, Closure, Simplification Logic},<br>&nbsp;&nbsp;&nbsp;&nbsp;abstract = {The importance of the computation of direct bases of implications has been motivated by several authors in different areas. They emphasize the use of direct bases in several problems, where a large number of closures are needed. The more efficient the basis computation is, the better performance the methods solving these problems has. Here, we propose a new method, named SLgetdo, to calculate the direct-optimal basis. The main characteristic of SLgetdo is the full integration of simplification paradigm, providing a limited rise of the implicational set throughout its execution. We have showed the better behavior of SLgetdo in an empirical experiment. The general conclusion is that it improves the performance of previous methods, providing a better management of time and space resources.}<br>}

:::


