---
author:
- Gloria Gálan-Marín
- Enrique Mérida-Casermeiro
- <a href='/people/staff/dominlopez/' style='color:rgb(100,0,50);'>Domingo López Rodríguez</a>
Status: Published
date: '2007-10-01'
slug: 2007-npl
title: Improving neural networks for mechanism kinematic chain isomorphism identification
categories:
- Neural networks
- Combinatorial optimization
header_image: ~
details: <em>Neural Processing Letters</em> vol 26 (2), 133-143
doi: 10.1007/s11063-007-9047-8
link: 2007-npl/paper.pdf
project: ~
keywords: ''
---


# Abstract


Detection of isomorphism among kinematic chains is essential in mechanical design, but difficult and computationally expensive. It has been shown that both traditional methods and previously presented neural networks still have a lot to be desired in aspects such as simplifying procedure of identification and adapting automatic computation. Therefore, a new algorithm based on a competitive Hopfield network is developed for automatic computation in the kinematic chain isomorphism problem. The neural approach provides directly interpretable solutions and does not demand tuning of parameters. We have tested the algorithm by solving problems reported in the recent mechanical literature. Simulation results show the effectiveness of the network that rapidly identifies isomorphic kinematic chains.





# Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```


# Citation
Please, cite this work as:


<a name=bib-galan2007improving></a>[[GML07]](#cite-galan2007improving) G. Galan-Marin, E. Merida-Casermeiro, and D. Lopez-Rodriguez. “Improving neural networks for mechanism kinematic chain isomorphism identification”. In: _Neural processing letters_ 26.2 (2007), pp. 133-143.

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@article{galan2007improving,<br>&nbsp;&nbsp;&nbsp;&nbsp;  title={Improving neural networks for mechanism kinematic chain isomorphism identification},<br>&nbsp;&nbsp;&nbsp;&nbsp;  author={Galan-Marin, Gloria and Merida-Casermeiro, Enrique and Lopez-Rodriguez, Domingo},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal={Neural processing letters},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume={26},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number={2},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages={133--143},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year={2007},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher={Springer}<br>}

:::


