---
title: From an Implicational System to its Corresponding D-basis
author:
- Estrella Rodríguez Lorenzo
- Kira V. Adaricheva
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/enciso/' style='color:rgb(100,0,50);'>Manuel Enciso</a>
- <a href='/people/staff/amora/' style='color:rgb(100,0,50);'>Ángel Mora</a>
date: '2015'
categories: uncategorised
slug: 2015/ImSyCo
details: Proceedings of the Twelfth International Conference on Concept Lattices and
  Their Applications, Clermont-Ferrand, France, October 13-16, 2015 , {CEUR} Workshop
  Proceedings vol. 1466, pages 217--228.
---



# Abstract


Closure system is a fundamental concept appearing in several areas such as databases, formal concept analysis, artificial intelligence,  etc. It is well-known that there exists a connection between a closure operator on a set and the lattice of its closed sets. Furthermore, the closure system can be replaced by a set of implications but this set has usually a lot of redundancy inducing non desired properties. In the literature, there is a common interest in the search of the minimality of a set of implications because of the importance of bases. The well-known Duquenne-Guigues basis satisfies this minimality condition. However, several authors emphasize the relevance of the optimality in order to reduce the size of implications in the basis. In addition to this, some bases have been defined to improve the computation of closures relying on the directness property. The efficiency of computation with
the direct basis is achieved due to the fact that the closure is computed in one traversal. In this work, we focus on the D-basis, which is ordered-direct. An open problem is to obtain it from an arbitrary implicational system, so it is our aim in this paper. We introduce a method to compute the D-basis by means of minimal generators calculated using the Simplification Logic for implications.








# Citation
Please, cite this work as:


<a name=bib-Lorenzo2015></a>[[Rod+15]](#cite-Lorenzo2015) E. Rodr\'\iguezLorenzo, K. V. Adaricheva, P. Cordero, et al. “From an Implicational System to its Corresponding D-basis”. In: _Proceedings of the Twelfth International Conference on Concept Lattices and Their Applications, Clermont-Ferrand, France, October 13-16, 2015_. Ed. by S. B. Yahia and J. Konecny. Vol. 1466. CEUR Workshop Proceedings. CEUR-WS.org, 2015, pp. 217-228. URL: [https://ceur-ws.org/Vol-1466/paper18.pdf](https://ceur-ws.org/Vol-1466/paper18.pdf).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Lorenzo2015,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Estrella Rodr\'\iguez Lorenzo and Kira V. Adaricheva and Pablo Cordero and Manuel Enciso and {\a'A}ngel Mora},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Proceedings of the Twelfth International Conference on Concept Lattices and Their Applications, Clermont-Ferrand, France, October 13-16, 2015},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {From an Implicational System to its Corresponding D-basis},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2015},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Sadok Ben Yahia and Jan Konecny},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {217--228},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {CEUR-WS.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {{CEUR} Workshop Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {1466},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {Closure system is a fundamental concept appearing in several areas such as databases, formal concept analysis, artificial intelligence,  etc. It is well-known that there exists a connection between a closure operator on a set and the lattice of its closed sets. Furthermore, the closure system can be replaced by a set of implications but this set has usually a lot of redundancy inducing non desired properties. In the literature, there is a common interest in the search of the minimality of a set of implications because of the importance of bases. The well-known Duquenne-Guigues basis satisfies this minimality condition. However, several authors emphasize the relevance of the optimality in order to reduce the size of implications in the basis. In addition to this, some bases have been defined to improve the computation of closures relying on the directness property. The efficiency of computation with<br>&nbsp;&nbsp;&nbsp;&nbsp;the direct basis is achieved due to the fact that the closure is computed in one traversal. In this work, we focus on the D-basis, which is ordered-direct. An open problem is to obtain it from an arbitrary implicational system, so it is our aim in this paper. We introduce a method to compute the D-basis by means of minimal generators calculated using the Simplification Logic for implications.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/cla/LorenzoACEM15.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 10 Mar 2023 16:22:10 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://ceur-ws.org/Vol-1466/paper18.pdf},<br>}

:::








