---
title: Analysis of Fuzzy Vector Spaces as an Algebraic Framework for Flag Codes
author:
- <a href='/people/staff/cbejines/' style='color:rgb(100,0,50);'>Carlos Bejines</a>
- <a href='/people/staff/manuojeda/' style='color:rgb(100,0,50);'>Manuel Ojeda Hernández</a>
- <a href='/people/staff/dominlopez/' style='color:rgb(100,0,50);'>Domingo López Rodríguez</a>
date: '2024-02-05'
categories: Fuzzy sets
header_image: ~
doi: 10.3390/math12030498
slug: 2024/AnFuVeSpAlFrFlCo
keywords: ''
project: 2023-valid
details: Mathematics vol. 12 (3), article number 498.
listing:
- id: funding
  contents: funding.yml
  type: default
  sort: date desc
---




# Abstract

Flag codes are a recent network coding strategy based on linear algebra. Fuzzy vector subspaces extend the notions of classical linear algebra. They can be seen as abstractions of flags to the point that several fuzzy vector subspaces can be identified to the same flag, which naturally induces an equivalence relation on the set of fuzzy vector subspaces. The main contributions of this work are the methodological abstraction of flags and flag codes in terms of fuzzy vector subspaces, as well as the generalisation of three distinct equivalence relations that originated from the fuzzy subgroup theory and study of their connection with flag codes, computing the number of equivalence classes in the discrete case, which represent the number of essentially distinct flags, and a comprehensive analysis of such relations and the properties of the corresponding quotient sets.


# Funding
::: {.callout-note appearance='minimal' collapse=false}
## Projects funding this work

:::{#funding}
:::
:::








# Citation
Please, cite this work as:


<a name=bib-math12030498></a>[[BOL24]](#cite-math12030498) C. Bejines, M. Ojeda-Hernández, and D. López-Rodríguez. “Analysis of Fuzzy Vector Spaces as an Algebraic Framework for Flag Codes”. In: _Mathematics_ 12.3 (2024). ISSN: 2227-7390. DOI: [10.3390/math12030498](https://doi.org/10.3390%2Fmath12030498). URL: [https://www.mdpi.com/2227-7390/12/3/498](https://www.mdpi.com/2227-7390/12/3/498).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{math12030498,<br>&nbsp;&nbsp;&nbsp;&nbsp;AUTHOR = {Bejines, Carlos and Ojeda-Hernández, Manuel and López-Rodríguez, Domingo},<br>&nbsp;&nbsp;&nbsp;&nbsp;TITLE = {Analysis of Fuzzy Vector Spaces as an Algebraic Framework for Flag Codes},<br>&nbsp;&nbsp;&nbsp;&nbsp;JOURNAL = {Mathematics},<br>&nbsp;&nbsp;&nbsp;&nbsp;VOLUME = {12},<br>&nbsp;&nbsp;&nbsp;&nbsp;YEAR = {2024},<br>&nbsp;&nbsp;&nbsp;&nbsp;NUMBER = {3},<br>&nbsp;&nbsp;&nbsp;&nbsp;ARTICLE-NUMBER = {498},<br>&nbsp;&nbsp;&nbsp;&nbsp;URL = {https://www.mdpi.com/2227-7390/12/3/498},<br>&nbsp;&nbsp;&nbsp;&nbsp;ISSN = {2227-7390},<br>&nbsp;&nbsp;&nbsp;&nbsp;ABSTRACT = {Flag codes are a recent network coding strategy based on linear algebra. Fuzzy vector subspaces extend the notions of classical linear algebra. They can be seen as abstractions of flags to the point that several fuzzy vector subspaces can be identified to the same flag, which naturally induces an equivalence relation on the set of fuzzy vector subspaces. The main contributions of this work are the methodological abstraction of flags and flag codes in terms of fuzzy vector subspaces, as well as the generalisation of three distinct equivalence relations that originated from the fuzzy subgroup theory and study of their connection with flag codes, computing the number of equivalence classes in the discrete case, which represent the number of essentially distinct flags, and a comprehensive analysis of such relations and the properties of the corresponding quotient sets.},<br>&nbsp;&nbsp;&nbsp;&nbsp;DOI = {10.3390/math12030498}<br>}

:::






## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


NULL


