---
title: 'Conference paper accepted: <em>A Novel Competitive Network Approach to Object
  Tracking</em>'
author: Juan M. Ortiz-de-Lazcano-Lobato, Rafael M. Luque, Domingo López-Rodríguez,
  Esteban J. Palomo
date: '2008-01-01'
categories:
- Image processing
- Neural networks
---

The work <u>A Novel Competitive Network Approach to Object Tracking</u> has been published in <em><em>Proceedings of the 2008 UK Workshop on Computational Intelligence</em></em>.

<u>Abstract</u>:



The aim of this paper is to present a novel method for tracking moving objects for video-surveillance. It is based on a growing competitive neural network where the number of neurons can be automatically increased or decreased in order to get a one-to-one association between objects currently in the scene and neurons. This association is kept in each frame, what constitutes the foundations of this tracking system. Experiments show that our method is capable to accurately track objects in real-world video sequences.




For more details on this work, visit <a href='/publications/conferences/2008-ukci'>its own page</a>.
