---
title: On the Existence of Right Adjoints for Surjective Mappings between Fuzzy Structures
author:
- <a href='/people/staff/ipcabrera/' style='color:rgb(100,0,50);'>Inma P. Cabrera</a>
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- Francisca García-Pardo
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
- Bernard De Baets
date: '2016'
categories: uncategorised
slug: 2016/ExRiAdSuMaFuSt
details: Proceedings of the Thirteenth International Conference on Concept Lattices
  and Their Applications, Moscow, Russia, July 18-22, 2016 , {CEUR} Workshop Proceedings
  vol. 1624, pages 97--108.
---



# Abstract


We continue our study of the characterization of existence of adjunctions (isotone Galois connections) whose codomain is insufficiently structured. This paper focuses on the fuzzy case in which we have a fuzzy ordering ρA on A and a surjective mapping f : hA, ≈Ai → hB, ≈Bi compatible with respect to the fuzzy equivalences ≈A and ≈B. Specifically, the problem is to find a fuzzy ordering ρB and a compatible mappingg : hB, ≈Bi → hA, ≈Ai such that the pair (f, g) is a fuzzy adjunction.








# Citation
Please, cite this work as:


<a name=bib-Cabrera2016></a>[[Cab+16]](#cite-Cabrera2016) I. P. Cabrera, P. Cordero, F. Garc\'\ia-Pardo, et al. “On the Existence of Right Adjoints for Surjective Mappings between Fuzzy Structures”. In: _Proceedings of the Thirteenth International Conference on Concept Lattices and Their Applications, Moscow, Russia, July 18-22, 2016_. Ed. by M. Huchard and S. O. Kuznetsov. Vol. 1624. CEUR Workshop Proceedings. CEUR-WS.org, 2016, pp. 97-108. URL: [https://ceur-ws.org/Vol-1624/paper8.pdf](https://ceur-ws.org/Vol-1624/paper8.pdf).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Cabrera2016,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Inma P. Cabrera and Pablo Cordero and Francisca Garc\'\ia-Pardo and Manuel Ojeda-Aciego and Bernard De Baets},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Proceedings of the Thirteenth International Conference on Concept Lattices and Their Applications, Moscow, Russia, July 18-22, 2016},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {On the Existence of Right Adjoints for Surjective Mappings between Fuzzy Structures},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2016},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Marianne Huchard and Sergei O. Kuznetsov},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {97--108},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {CEUR-WS.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {{CEUR} Workshop Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {1624},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {We continue our study of the characterization of existence of adjunctions (isotone Galois connections) whose codomain is insufficiently structured. This paper focuses on the fuzzy case in which we have a fuzzy ordering ρA on A and a surjective mapping f : hA, ≈Ai → hB, ≈Bi compatible with respect to the fuzzy equivalences ≈A and ≈B. Specifically, the problem is to find a fuzzy ordering ρB and a compatible mappingg : hB, ≈Bi → hA, ≈Ai such that the pair (f, g) is a fuzzy adjunction.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/cla/CabreraCGOB16.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 10 Mar 2023 16:22:10 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://ceur-ws.org/Vol-1624/paper8.pdf},<br>}

:::








