---
author:
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/enciso/' style='color:rgb(100,0,50);'>Manuel Enciso</a>
- <a href='/people/staff/dominlopez/' style='color:rgb(100,0,50);'>Domingo López Rodríguez</a>
- <a href='/people/staff/amora/' style='color:rgb(100,0,50);'>Ángel Mora</a>
Status: Published
date: '2022-09-01T00:00:00Z'
slug: 2022/FoCoAnR
selected: yes
title: fcaR, Formal Concept Analysis with R
categories:
- Formal concept analysis
- R package
header_image: ~
details: <em>The R Journal</em>
doi: 10.32614/RJ-2022-014
link: 2022-rjournal/paper.pdf
project: 2019-flair
keywords: Formal concept analysis, R package
listing:
- id: funding
  contents: funding.yml
  type: default
  sort: date desc
---


# Abstract


Formal concept analysis (FCA) is a solid mathematical framework to manage information based on logic and lattice theory. It defines two explicit representations of the knowledge present in a dataset as concepts and implications. This paper describes an R package called fcaR that implements FCA's core notions and techniques. Additionally, it implements the extension of FCA to fuzzy datasets and a simplification logic to develop automated reasoning tools. This package is the first to implement FCA techniques in R. Therefore, emphasis has been put on defining classes and methods that could be reusable and extensible by the community. Furthermore, the package incorporates an interface with the arules package, probably the most used package regarding association rules, closely related to FCA. Finally, we show an application of the use of the package to design a recommender system based on logic for diagnosis in neurological pathologies.




# Funding
::: {.callout-note appearance='minimal' collapse=false}
## Projects funding this work

:::{#funding}
:::
:::









# Citation
Please, cite this work as:


<a name=bib-RJ-2022-014></a>[[Cor+22]](#cite-RJ-2022-014) P. Cordero, M. Enciso, D. López-Rodríguez, et al. “fcaR, Formal Concept Analysis with R”. In: _The R Journal_ 14 (1 2022). https://doi.org/10.32614/RJ-2022-014, pp. 341-361. ISSN: 2073-4859. DOI: [10.32614/RJ-2022-014](https://doi.org/10.32614%2FRJ-2022-014).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@article{RJ-2022-014,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Pablo Cordero  and Manuel Enciso and Domingo {López-Rodríguez} and Ángel Mora},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {fcaR, Formal Concept Analysis with R},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {The R Journal},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2022},<br>&nbsp;&nbsp;&nbsp;&nbsp;  note = {https://doi.org/10.32614/RJ-2022-014},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.32614/RJ-2022-014},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {14},<br>&nbsp;&nbsp;&nbsp;&nbsp;  issue = {1},<br>&nbsp;&nbsp;&nbsp;&nbsp;  issn = {2073-4859},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {341-361}<br>}

:::



# Bibliometric data

## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Antoni_2024></a>[[1]](#cite-Antoni_2024) Ľ. Antoni, P. Eliaš, J. Guniš, et al. “Bimorphisms and attribute implications in heterogeneous formal contexts”. In: _International Journal of Approximate Reasoning_ 172 (Sep. 2024), p. 109245. ISSN: 0888-613X. DOI: [10.1016/j.ijar.2024.109245](https://doi.org/10.1016%2Fj.ijar.2024.109245). URL: [http://dx.doi.org/10.1016/j.ijar.2024.109245](http://dx.doi.org/10.1016/j.ijar.2024.109245).

<a name=bib-Hanika_2024></a>[[2]](#cite-Hanika_2024) T. Hanika and R. Jäschke. “A Repository for Formal Contexts”. In: _Conceptual Knowledge Structures_. Springer Nature Switzerland, 2024, p. 182–197. ISBN: 9783031678684. DOI: [10.1007/978-3-031-67868-4_13](https://doi.org/10.1007%2F978-3-031-67868-4_13). URL: [http://dx.doi.org/10.1007/978-3-031-67868-4_13](http://dx.doi.org/10.1007/978-3-031-67868-4_13).

<a name=bib-Kr_dlo_2023></a>[[3]](#cite-Kr_dlo_2023) O. Krídlo, D. López-Rodríguez, L. Antoni, et al. “Connecting concept lattices with bonds induced by external information”. In: _Information Sciences_ 648 (Nov. 2023), p. 119498. ISSN: 0020-0255. DOI: [10.1016/j.ins.2023.119498](https://doi.org/10.1016%2Fj.ins.2023.119498). URL: [http://dx.doi.org/10.1016/j.ins.2023.119498](http://dx.doi.org/10.1016/j.ins.2023.119498).

<a name=bib-L_pez_Rodr_guez_2024></a>[[4]](#cite-L_pez_Rodr_guez_2024) D. López-Rodríguez and M. Ojeda-Hernández. “Rearrangement of Fuzzy Formal Contexts for Reducing Cost of Algorithms”. In: _Conceptual Knowledge Structures_. Springer Nature Switzerland, 2024, p. 113–122. ISBN: 9783031678684. DOI: [10.1007/978-3-031-67868-4_8](https://doi.org/10.1007%2F978-3-031-67868-4_8). URL: [http://dx.doi.org/10.1007/978-3-031-67868-4_8](http://dx.doi.org/10.1007/978-3-031-67868-4_8).

<a name=bib-Ojeda_Hern_ndez_20241></a>[[5]](#cite-Ojeda_Hern_ndez_20241) M. Ojeda-Hernández and D. López-Rodríguez. “Enhancing Performance of FCA Algorithms via Rearrangement of Formal Contexts”. In: _2024 IEEE International Conference on Fuzzy Systems (FUZZ-IEEE)_. IEEE, Jun. 2024, p. 1–6. DOI: [10.1109/fuzz-ieee60900.2024.10612009](https://doi.org/10.1109%2Ffuzz-ieee60900.2024.10612009). URL: [http://dx.doi.org/10.1109/fuzz-ieee60900.2024.10612009](http://dx.doi.org/10.1109/fuzz-ieee60900.2024.10612009).

<a name=bib-Ojeda_Hern_ndez_2024></a>[[6]](#cite-Ojeda_Hern_ndez_2024) M. Ojeda-Hernández, D. López-Rodríguez, and Á. Mora. “A Formal Concept Analysis approach to hierarchical description of malware threats”. In: _Forensic Science International: Digital Investigation_ 50 (Sep. 2024), p. 301797. ISSN: 2666-2817. DOI: [10.1016/j.fsidi.2024.301797](https://doi.org/10.1016%2Fj.fsidi.2024.301797). URL: [http://dx.doi.org/10.1016/j.fsidi.2024.301797](http://dx.doi.org/10.1016/j.fsidi.2024.301797).

<a name=bib-Ojeda_Hern_ndez_2023></a>[[7]](#cite-Ojeda_Hern_ndez_2023) M. Ojeda-Hernández, D. López-Rodríguez, and Á. Mora. “Lexicon-based sentiment analysis in texts using Formal Concept Analysis”. In: _International Journal of Approximate Reasoning_ 155 (Apr. 2023), p. 104–112. ISSN: 0888-613X. DOI: [10.1016/j.ijar.2023.02.001](https://doi.org/10.1016%2Fj.ijar.2023.02.001). URL: [http://dx.doi.org/10.1016/j.ijar.2023.02.001](http://dx.doi.org/10.1016/j.ijar.2023.02.001).

<a name=bib-Rungruang_2024></a>[[8]](#cite-Rungruang_2024) C. Rungruang, P. Riyapan, A. Intarasit, et al. “RFM model customer segmentation based on hierarchical approach using FCA”. In: _Expert Systems with Applications_ 237 (Mar. 2024), p. 121449. ISSN: 0957-4174. DOI: [10.1016/j.eswa.2023.121449](https://doi.org/10.1016%2Fj.eswa.2023.121449). URL: [http://dx.doi.org/10.1016/j.eswa.2023.121449](http://dx.doi.org/10.1016/j.eswa.2023.121449).

<a name=bib-Sokol_2023></a>[[9]](#cite-Sokol_2023) P. Sokol, Ľ. Antoni, O. Krídlo, et al. “Formal concept analysis approach to understand digital evidence relationships”. In: _International Journal of Approximate Reasoning_ 159 (Aug. 2023), p. 108940. ISSN: 0888-613X. DOI: [10.1016/j.ijar.2023.108940](https://doi.org/10.1016%2Fj.ijar.2023.108940). URL: [http://dx.doi.org/10.1016/j.ijar.2023.108940](http://dx.doi.org/10.1016/j.ijar.2023.108940).

<a name=bib-Valverde_Albacete_2024></a>[[10]](#cite-Valverde_Albacete_2024) F. J. Valverde-Albacete and C. Peláez-Moreno. “A Formalization of Multilabel Classification in Terms of Lattice Theory and Information Theory: Concerning Datasets”. In: _Mathematics_ 12.2 (Jan. 2024), p. 346. ISSN: 2227-7390. DOI: [10.3390/math12020346](https://doi.org/10.3390%2Fmath12020346). URL: [http://dx.doi.org/10.3390/math12020346](http://dx.doi.org/10.3390/math12020346).

<a name=bib-Yao_2023></a>[[11]](#cite-Yao_2023) L. Yao, S. Wang, Q. Li, et al. “Continuous lattices in formal concept analysis”. In: _Soft Computing_ 28.2 (Dec. 2023), p. 955–962. ISSN: 1433-7479. DOI: [10.1007/s00500-023-09462-5](https://doi.org/10.1007%2Fs00500-023-09462-5). URL: [http://dx.doi.org/10.1007/s00500-023-09462-5](http://dx.doi.org/10.1007/s00500-023-09462-5).


