---
title: Revising the link between L-Chu correspondences and completely lattice L-ordered
  sets
author:
- Ondrej Kridlo
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '2014'
categories: uncategorised
slug: 2014/ReLiCoCoLaSe
details: Ann. Math. Artif. Intell. vol. 72 (1-2), pages 91--113.
doi: 10.1007/S10472-014-9416-8
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Kridlo2014></a>[[KO14]](#cite-Kridlo2014) O. Kridlo and M. Ojeda-Aciego. “Revising the link between L-Chu correspondences and completely lattice L-ordered sets”. In: _Ann. Math. Artif. Intell._ 72.1-2 (2014), pp. 91-113. DOI: [10.1007/S10472-014-9416-8](https://doi.org/10.1007%2FS10472-014-9416-8). URL: [https://doi.org/10.1007/s10472-014-9416-8](https://doi.org/10.1007/s10472-014-9416-8).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{Kridlo2014,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Ondrej Kridlo and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Ann. Math. Artif. Intell.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Revising the link between L-Chu correspondences and completely lattice L-ordered sets},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2014},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number = {1-2},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {91--113},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {72},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/amai/KridloO14.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/S10472-014-9416-8},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Tue, 29 Dec 2020 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/s10472-014-9416-8},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/S10472-014-9416-8" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/S10472-014-9416-8" class="plumx-details" data-site="plum" data-hide-when-empty="true">Revising the link between L-Chu correspondences and completely lattice L-ordered sets</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1007/S10472-014-9416-8"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Antoni_2020></a>[[1]](#cite-Antoni_2020) Ľ. Antoni, D. Bruothová, J. Guniš, et al. “Attribute Exploration in Formal Concept Analysis and Measuring of Pupils’ Computational Thinking”. In: _Towards Digital Intelligence Society_. Springer International Publishing, Dec. 2020, p. 160–180. ISBN: 9783030638726. DOI: [10.1007/978-3-030-63872-6_8](https://doi.org/10.1007%2F978-3-030-63872-6_8). URL: [http://dx.doi.org/10.1007/978-3-030-63872-6_8](http://dx.doi.org/10.1007/978-3-030-63872-6_8).

<a name=bib-Antoni_20171></a>[[2]](#cite-Antoni_20171) L. Antoni, I. P. Cabrera, S. Krajči, et al. “The Chu construction and generalized formal concept analysis”. In: _International Journal of General Systems_ 46.5 (Jul. 2017), p. 458–474. ISSN: 1563-5104. DOI: [10.1080/03081079.2017.1349579](https://doi.org/10.1080%2F03081079.2017.1349579). URL: [http://dx.doi.org/10.1080/03081079.2017.1349579](http://dx.doi.org/10.1080/03081079.2017.1349579).

<a name=bib-Antoni_2016></a>[[3]](#cite-Antoni_2016) L. Antoni, S. Krajči, and O. Krídlo. “Constraint heterogeneous concept lattices and concept lattices with heterogeneous hedges”. In: _Fuzzy Sets and Systems_ 303 (Nov. 2016), p. 21–37. ISSN: 0165-0114. DOI: [10.1016/j.fss.2015.12.007](https://doi.org/10.1016%2Fj.fss.2015.12.007). URL: [http://dx.doi.org/10.1016/j.fss.2015.12.007](http://dx.doi.org/10.1016/j.fss.2015.12.007).

<a name=bib-Antoni_2018></a>[[4]](#cite-Antoni_2018) L. Antoni, S. Krajči, and O. Krídlo. “On Fuzzy Generalizations of Concept Lattices”. In: _Interactions Between Computational Intelligence and Mathematics_. Springer International Publishing, 2018, p. 79–103. ISBN: 9783319746814. DOI: [10.1007/978-3-319-74681-4_6](https://doi.org/10.1007%2F978-3-319-74681-4_6). URL: [http://dx.doi.org/10.1007/978-3-319-74681-4_6](http://dx.doi.org/10.1007/978-3-319-74681-4_6).

<a name=bib-Antoni_20181></a>[[5]](#cite-Antoni_20181) L. Antoni, S. Krajči, and O. Krídlo. “On stability of fuzzy formal concepts over randomized one-sided formal context”. In: _Fuzzy Sets and Systems_ 333 (Feb. 2018), p. 36–53. ISSN: 0165-0114. DOI: [10.1016/j.fss.2017.04.006](https://doi.org/10.1016%2Fj.fss.2017.04.006). URL: [http://dx.doi.org/10.1016/j.fss.2017.04.006](http://dx.doi.org/10.1016/j.fss.2017.04.006).

<a name=bib-Antoni_2017></a>[[6]](#cite-Antoni_2017) L. Antoni, S. Krajči, and O. Krídlo. “Representation of fuzzy subsets by Galois connections”. In: _Fuzzy Sets and Systems_ 326 (Nov. 2017), p. 52–68. ISSN: 0165-0114. DOI: [10.1016/j.fss.2017.05.020](https://doi.org/10.1016%2Fj.fss.2017.05.020). URL: [http://dx.doi.org/10.1016/j.fss.2017.05.020](http://dx.doi.org/10.1016/j.fss.2017.05.020).

<a name=bib-Eklund_2014></a>[[7]](#cite-Eklund_2014) P. Eklund, M. Á. Galán García, J. Kortelainen, et al. “Monadic Formal Concept Analysis”. In: _Rough Sets and Current Trends in Soft Computing_. Springer International Publishing, 2014, p. 201–210. ISBN: 9783319086446. DOI: [10.1007/978-3-319-08644-6_21](https://doi.org/10.1007%2F978-3-319-08644-6_21). URL: [http://dx.doi.org/10.1007/978-3-319-08644-6_21](http://dx.doi.org/10.1007/978-3-319-08644-6_21).

<a name=bib-Kr_dlo_2022></a>[[8]](#cite-Kr_dlo_2022) O. Krídlo, Ľ. Antoni, and S. Krajči. “Selection of appropriate bonds between <mml:math xmlns:mml="http://www.w3.org/1998/Math/MathML" altimg="si295.svg"><mml:mrow><mml:mi mathvariant="script">L</mml:mi></mml:mrow></mml:math>-fuzzy formal contexts for recommendation tasks”. In: _Information Sciences_ 606 (Aug. 2022), p. 21–37. ISSN: 0020-0255. DOI: [10.1016/j.ins.2022.05.047](https://doi.org/10.1016%2Fj.ins.2022.05.047). URL: [http://dx.doi.org/10.1016/j.ins.2022.05.047](http://dx.doi.org/10.1016/j.ins.2022.05.047).

<a name=bib-Kr_dlo_2023></a>[[9]](#cite-Kr_dlo_2023) O. Krídlo, D. López-Rodríguez, L. Antoni, et al. “Connecting concept lattices with bonds induced by external information”. In: _Information Sciences_ 648 (Nov. 2023), p. 119498. ISSN: 0020-0255. DOI: [10.1016/j.ins.2023.119498](https://doi.org/10.1016%2Fj.ins.2023.119498). URL: [http://dx.doi.org/10.1016/j.ins.2023.119498](http://dx.doi.org/10.1016/j.ins.2023.119498).

<a name=bib-Kr_dlo_2019></a>[[10]](#cite-Kr_dlo_2019) O. Krídlo and M. Ojeda-Aciego. “Relating Hilbert-Chu Correspondences and Big Toy Models for Quantum Mechanics”. In: _Computational Intelligence and Mathematics for Tackling Complex Problems_. Springer International Publishing, May. 2019, p. 75–80. ISBN: 9783030160241. DOI: [10.1007/978-3-030-16024-1_10](https://doi.org/10.1007%2F978-3-030-16024-1_10). URL: [http://dx.doi.org/10.1007/978-3-030-16024-1_10](http://dx.doi.org/10.1007/978-3-030-16024-1_10).

<a name=bib-Kr_dlo_20221></a>[[11]](#cite-Kr_dlo_20221) O. Krídlo, M. Ojeda-Aciego, T. Put, et al. “On Some Categories Underlying Knowledge Graphs”. In: _Computational Intelligence and Mathematics for Tackling Complex Problems 2_. Springer International Publishing, 2022, p. 199–205. ISBN: 9783030888176. DOI: [10.1007/978-3-030-88817-6_23](https://doi.org/10.1007%2F978-3-030-88817-6_23). URL: [http://dx.doi.org/10.1007/978-3-030-88817-6_23](http://dx.doi.org/10.1007/978-3-030-88817-6_23).

