---
title: 'Conference paper accepted: <em>How to provide light to COVID data by means
  of FCA</em>'
author: Domingo López-Rodríguez, P. Cordero, M. Enciso, A. Mora
date: '2021-06-29'
categories: Formal concept analysis
---

The work <u>How to provide light to COVID data by means of FCA</u> has been published in <em>RealDataFCA Workshop, jointly with International Conference on Formal Concept Analysis (ICFCA) 2021</em>.

<u>Abstract</u>:



COVID data are usually presented in a non-structured format and mainly
  focused on healthy issues (incidence, mortality, etc). At the same time, Governments
  have designed a set of measures to deal with the Pandemic. In addition, several
  institutions have studied the economical effects of the situation in each country.
  In this work, we combine these three data sources and  illustrate how Formal Concept
  Analysis can become a useful tool to discover relationships among these three views
  of the situation: health, politics and economy. Our aim is to provide an implication-driven
  approach to discover knowledge behind the data.





For more details on this work, visit <a href='/publications/conferences/2021-realdatafca'>its own page</a>.
