---
title: The Direct-optimal Basis via Reductions
author:
- Estrella Rodríguez Lorenzo
- Karell Bertet
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/enciso/' style='color:rgb(100,0,50);'>Manuel Enciso</a>
- <a href='/people/staff/amora/' style='color:rgb(100,0,50);'>Ángel Mora</a>
date: '2014'
categories: uncategorised
slug: 2014/BaViRe
details: Proceedings of the Eleventh International Conference on Concept Lattices
  and Their Applications, Ko{\v{s}}ice, Slovakia, October 7-10, 2014 , {CEUR} Workshop
  Proceedings vol. 1252, pages 145--156.
---



# Abstract


Formal Concept Analysis has become a real approach in the trend Information-Knowledge-Wisdom. It turns around the mining of a
data set to built a concept lattice which provides an strong structure of the knowledge. Implications play the role of an alternative specification of this concept lattice and may be managed by means of inference rules. This syntactic treatment is guided by several properties like directness, minimality, optimality, etc. In this work, we propose a method to calculate the direct-optimal basis  equivalent to a given Implicational System. Our method deals with unitary and non-unitary implications. Moreover, it shows a better performance that previous methods in the literature by means of the use of Simplification Logic and reduction paradigm, which remains narrow implications in any stage of the process. We have also developed an empirical study to compare our method with previous approaches in the literature.








# Citation
Please, cite this work as:


<a name=bib-Lorenzo2014></a>[[Rod+14]](#cite-Lorenzo2014) E. Rodr\'\iguezLorenzo, K. Bertet, P. Cordero, et al. “The Direct-optimal Basis via Reductions”. In: _Proceedings of the Eleventh International Conference on Concept Lattices and Their Applications, Košice, Slovakia, October 7-10, 2014_. Ed. by K. Bertet and S. Rudolph. Vol. 1252. CEUR Workshop Proceedings. CEUR-WS.org, 2014, pp. 145-156. URL: [https://ceur-ws.org/Vol-1252/cla2014\_submission\_18.pdf](https://ceur-ws.org/Vol-1252/cla2014\_submission\_18.pdf).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Lorenzo2014,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Estrella Rodr\'\iguez Lorenzo and Karell Bertet and Pablo Cordero and Manuel Enciso and {\a'A}ngel Mora},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Proceedings of the Eleventh International Conference on Concept Lattices and Their Applications, Ko{\v{s}}ice, Slovakia, October 7-10, 2014},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {The Direct-optimal Basis via Reductions},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2014},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Karell Bertet and Sebastian Rudolph},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {145--156},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {CEUR-WS.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {{CEUR} Workshop Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {1252},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {Formal Concept Analysis has become a real approach in the trend Information-Knowledge-Wisdom. It turns around the mining of a<br>&nbsp;&nbsp;&nbsp;&nbsp;data set to built a concept lattice which provides an strong structure of the knowledge. Implications play the role of an alternative specification of this concept lattice and may be managed by means of inference rules. This syntactic treatment is guided by several properties like directness, minimality, optimality, etc. In this work, we propose a method to calculate the direct-optimal basis  equivalent to a given Implicational System. Our method deals with unitary and non-unitary implications. Moreover, it shows a better performance that previous methods in the literature by means of the use of Simplification Logic and reduction paradigm, which remains narrow implications in any stage of the process. We have also developed an empirical study to compare our method with previous approaches in the literature.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/cla/LorenzoBCEM14.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 10 Mar 2023 16:22:10 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://ceur-ws.org/Vol-1252/cla2014\_submission\_18.pdf},<br>}

:::








