---
title: Using Intensifying Hedges to Reduce Size of Multi-adjoint Concept Lattices
  with Heterogeneous Conjunctors
author:
- Jan Konecny
- Jesús Medina
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '2012'
categories: uncategorised
slug: 2012/UsInHeReSiCoLaHeCo
details: Proceedings of The Ninth International Conference on Concept Lattices and
  Their Applications, Fuengirola (M{\'{a}}laga), Spain, October 11-14, 2012 , {CEUR}
  Workshop Proceedings vol. 972, pages 245--256.
---



# Abstract


In this work we focus on the use of intensifying hedges as a tool to reduce the size of the recently introduced multi-adjoint concept
lattices with heterogeneous conjunctors.








# Citation
Please, cite this work as:


<a name=bib-Konecny2012></a>[[KMO12]](#cite-Konecny2012) J. Konecny, J. Medina, and M. Ojeda-Aciego. “Using Intensifying Hedges to Reduce Size of Multi-adjoint Concept Lattices with Heterogeneous Conjunctors”. In: _Proceedings of The Ninth International Conference on Concept Lattices and Their Applications, Fuengirola (Málaga), Spain, October 11-14, 2012_. Ed. by L. Szathmary and U. Priss. Vol. 972. CEUR Workshop Proceedings. CEUR-WS.org, 2012, pp. 245-256. URL: [https://ceur-ws.org/Vol-972/paper21.pdf](https://ceur-ws.org/Vol-972/paper21.pdf).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Konecny2012,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Jan Konecny and Jes{\a'u}s Medina and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Proceedings of The Ninth International Conference on Concept Lattices and Their Applications, Fuengirola (M{\'{a}}laga), Spain, October 11-14, 2012},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Using Intensifying Hedges to Reduce Size of Multi-adjoint Concept Lattices with Heterogeneous Conjunctors},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2012},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Laszlo Szathmary and Uta Priss},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {245--256},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {CEUR-WS.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {{CEUR} Workshop Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {972},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {In this work we focus on the use of intensifying hedges as a tool to reduce the size of the recently introduced multi-adjoint concept<br>&nbsp;&nbsp;&nbsp;&nbsp;lattices with heterogeneous conjunctors.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/cla/KonecnyMO12.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 10 Mar 2023 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://ceur-ws.org/Vol-972/paper21.pdf},<br>}

:::








