---
title: Fast(er) Reasoning in Interval Temporal Logic
author:
- Davide Bresolin
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
- Guido Sciavicco
date: '2017'
categories: uncategorised
slug: 2017/ReInTeLo
details: 26th {EACSL} Annual Conference on Computer Science Logic, {CSL} 2017, August
  20-24, 2017, Stockholm, Sweden , LIPIcs vol. 82, pages 17:1--17:17.
doi: 10.4230/LIPICS.CSL.2017.17
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Bresolin2017a></a>[[BMS17]](#cite-Bresolin2017a) D. Bresolin, E. Mu~noz-Velasco, and G. Sciavicco. “Fast(er) Reasoning in Interval Temporal Logic”. In: _26th EACSL Annual Conference on Computer Science Logic, CSL 2017, August 20-24, 2017, Stockholm, Sweden_. Ed. by V. Goranko and M. Dam. Vol. 82. LIPIcs. Schloss Dagstuhl - Leibniz-Zentrum für Informatik, 2017, pp. 17:1-17:17. DOI: [10.4230/LIPICS.CSL.2017.17](https://doi.org/10.4230%2FLIPICS.CSL.2017.17). URL: [https://doi.org/10.4230/LIPIcs.CSL.2017.17](https://doi.org/10.4230/LIPIcs.CSL.2017.17).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Bresolin2017a,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Davide Bresolin and Emilio Mu~noz-Velasco and Guido Sciavicco},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {26th {EACSL} Annual Conference on Computer Science Logic, {CSL} 2017, August 20-24, 2017, Stockholm, Sweden},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Fast(er) Reasoning in Interval Temporal Logic},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2017},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Valentin Goranko and Mads Dam},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {17:1--17:17},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Schloss Dagstuhl - Leibniz-Zentrum f{\"{u}}r Informatik},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {LIPIcs},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {82},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/csl/BresolinMS17.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.4230/LIPICS.CSL.2017.17},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Wed, 07 Dec 2022 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.4230/LIPIcs.CSL.2017.17},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.4230/LIPICS.CSL.2017.17" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.4230/LIPICS.CSL.2017.17" class="plumx-details" data-site="plum" data-hide-when-empty="true">Fast(er) Reasoning in Interval Temporal Logic</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.4230/LIPICS.CSL.2017.17"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Wa_ga_2019></a>[[1]](#cite-Wa_ga_2019) P. A. Wałęga. “Hybrid fragments of Halpern–Shoham logic and their expressive power”. In: _Theoretical Computer Science_ 797 (Dec. 2019), p. 102–128. ISSN: 0304-3975. DOI: [10.1016/j.tcs.2019.01.014](https://doi.org/10.1016%2Fj.tcs.2019.01.014). URL: [http://dx.doi.org/10.1016/j.tcs.2019.01.014](http://dx.doi.org/10.1016/j.tcs.2019.01.014).

