---
title: A hybrid qualitative approach for relative movements
author:
- Joanna Golinska-Pilarek
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
date: '2015'
categories: uncategorised
slug: 2015/HyQuApReMo
details: Log. J. {IGPL} vol. 23 (3), pages 410--420.
doi: 10.1093/JIGPAL/JZV012
---



# Abstract


Journal Article A hybrid qualitative approach for relative movements Get access Joanna Golińska-Pilarek, Joanna Golińska-Pilarek * Institute of Philosophy, University of Warsaw, Poland *E-mail: j.golinska@uw.edu.pl Search for other works by this author on: Oxford Academic Google Scholar Emilio Muñoz-Velasco Emilio Muñoz-Velasco Department of Applied Mathematics, University of Málaga, Spain Search for other works by this author on: Oxford Academic Google Scholar Logic Journal of the IGPL, Volume 23, Issue 3, June 2015, Pages 410–420, https://doi.org/10.1093/jigpal/jzv012 Published: 03 April 2015 Article history Received: 12 November 2014 Published: 03 April 2015








# Citation
Please, cite this work as:


<a name=bib-GolinskaPilarek2015></a>[[GM15]](#cite-GolinskaPilarek2015) J. Golinska-Pilarek and E. Mu~noz-Velasco. “A hybrid qualitative approach for relative movements”. In: _Log. J. IGPL_ 23.3 (2015), pp. 410-420. DOI: [10.1093/JIGPAL/JZV012](https://doi.org/10.1093%2FJIGPAL%2FJZV012). URL: [https://doi.org/10.1093/jigpal/jzv012](https://doi.org/10.1093/jigpal/jzv012).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{GolinskaPilarek2015,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Joanna Golinska-Pilarek and Emilio Mu~noz-Velasco},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Log. J. {IGPL}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {A hybrid qualitative approach for relative movements},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2015},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number = {3},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {410--420},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {23},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/igpl/Golinska-Pilarek15.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1093/JIGPAL/JZV012},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 06 Mar 2020 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1093/jigpal/jzv012},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1093/JIGPAL/JZV012" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1093/JIGPAL/JZV012" class="plumx-details" data-site="plum" data-hide-when-empty="true">A hybrid qualitative approach for relative movements</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1093/JIGPAL/JZV012"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Burrieza_2019></a>[[1]](#cite-Burrieza_2019) A. Burrieza, E. Muñoz-Velasco, and M. Ojeda-Aciego. “A flexible logic-based approach to closeness using order of magnitude qualitative reasoning”. In: _Logic Journal of the IGPL_ 28.1 (Dec. 2019), p. 121–133. ISSN: 1368-9894. DOI: [10.1093/jigpal/jzz076](https://doi.org/10.1093%2Fjigpal%2Fjzz076). URL: [http://dx.doi.org/10.1093/jigpal/jzz076](http://dx.doi.org/10.1093/jigpal/jzz076).

<a name=bib-Burrieza_2016></a>[[2]](#cite-Burrieza_2016) A. Burrieza, E. Muñoz-Velasco, and M. Ojeda-Aciego. “A Hybrid Approach to Closeness in the Framework of Order of Magnitude Qualitative Reasoning”. In: _Hybrid Artificial Intelligent Systems_. Springer International Publishing, 2016, p. 721–729. ISBN: 9783319320342. DOI: [10.1007/978-3-319-32034-2_60](https://doi.org/10.1007%2F978-3-319-32034-2_60). URL: [http://dx.doi.org/10.1007/978-3-319-32034-2_60](http://dx.doi.org/10.1007/978-3-319-32034-2_60).

