---
title: On Self-Aggregations of Min-Subgroups
author:
- <a href='/people/staff/cbejines/' style='color:rgb(100,0,50);'>Carlos Bejines</a>
- Sergio Ardanza-Trevijano
- Jorge Elorza
date: '2021'
categories: uncategorised
slug: 2021/SeAgMiSu
details: Axioms vol. 10 (3), pages 201.
doi: 10.3390/AXIOMS10030201
---



# Abstract


Preservation of structures under aggregation functions is an active area of research with applications in many fields. Among such structures, min-subgroups play an important role, for instance, in mathematical morphology, where they can be used to model translation invariance. Aggregation of min-subgroups has only been studied for binary aggregation functions. However, results concerning preservation of the min-subgroup structure under binary aggregations do not generalize to aggregation functions with arbitrary input size since they are not associative. In this article, we prove that arbitrary self-aggregation functions preserve the min-subgroup structure. Moreover, we show that whenever the aggregation function is strictly increasing on its diagonal, a min-subgroup and its self-aggregation have the same level sets.








# Citation
Please, cite this work as:


<a name=bib-DBLPjournalsaxiomsBejinesAE21></a>[[BAE21]](#cite-DBLPjournalsaxiomsBejinesAE21) C. Bejines, S. Ardanza-Trevijano, and J. Elorza. “On Self-Aggregations of Min-Subgroups”. In: _Axioms_ 10.3 (2021), p. 201. DOI: [10.3390/AXIOMS10030201](https://doi.org/10.3390%2FAXIOMS10030201). URL: [https://doi.org/10.3390/axioms10030201](https://doi.org/10.3390/axioms10030201).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{DBLP:journals/axioms/BejinesAE21,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Carlos Bejines and Sergio Ardanza-Trevijano and Jorge Elorza},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {On Self-Aggregations of Min-Subgroups},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Axioms},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {10},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number = {3},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {201},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2021},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.3390/axioms10030201},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.3390/AXIOMS10030201},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Mon, 28 Aug 2023 21:28:02 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/axioms/BejinesAE21.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.3390/AXIOMS10030201" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.3390/AXIOMS10030201" class="plumx-details" data-site="plum" data-hide-when-empty="true">On Self-Aggregations of Min-Subgroups</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.3390/AXIOMS10030201"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a
name=bib-Ardanza_Trevijano_2023></a>[[1]](#cite-Ardanza_Trevijano_2023)
S. Ardanza-Trevijano, M. Chasco, J. Elorza, et al.
“Aggregation of T-subgroups”. In: _Fuzzy Sets and
Systems_ 463 (Jul. 2023), p. 108390. ISSN: 0165-0114.
DOI:
[10.1016/j.fss.2022.08.022](https://doi.org/10.1016%2Fj.fss.2022.08.022).
URL:
[http://dx.doi.org/10.1016/j.fss.2022.08.022](http://dx.doi.org/10.1016/j.fss.2022.08.022).

<a name=bib-Bejines_2023></a>[[2]](#cite-Bejines_2023)
C. Bejines. “Aggregation of fuzzy vector spaces”. In:
_Kybernetika_ (Dec. 2023), p. 752–767. ISSN: 1805-949X.
DOI:
[10.14736/kyb-2023-5-0752](https://doi.org/10.14736%2Fkyb-2023-5-0752).
URL:
[http://dx.doi.org/10.14736/kyb-2023-5-0752](http://dx.doi.org/10.14736/kyb-2023-5-0752).

<a
name=bib-Talavera_2024></a>[[3]](#cite-Talavera_2024)
F. J. Talavera, C. Bejines, S. Ardanza-Trevijano, et
al. “Aggregation of fuzzy graphs”. In: _International
Journal of Approximate Reasoning_ 172 (Sep. 2024), p.
109243. ISSN: 0888-613X. DOI:
[10.1016/j.ijar.2024.109243](https://doi.org/10.1016%2Fj.ijar.2024.109243).
URL:
[http://dx.doi.org/10.1016/j.ijar.2024.109243](http://dx.doi.org/10.1016/j.ijar.2024.109243).

