---
title: Formal concept analysis with negative attributes for forgery detection
author:
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
- José Manuel Rodríguez-Jiménez
date: '2021'
categories: uncategorised
slug: 2021/FoCoAnNeAtFoDe
details: []
doi: 10.1002/CMM4.1124
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-OjedaAciego2021></a>[[OR21]](#cite-OjedaAciego2021) M. Ojeda-Aciego and J. M. Rodr\'\iguez-Jiménez. “Formal concept analysis with negative attributes for forgery detection”. In: _Comput. Math. Methods_ 3.6 (2021). DOI: [10.1002/CMM4.1124](https://doi.org/10.1002%2FCMM4.1124). URL: [https://doi.org/10.1002/cmm4.1124](https://doi.org/10.1002/cmm4.1124).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{OjedaAciego2021,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Manuel Ojeda-Aciego and Jos{\a'e} Manuel Rodr\'\iguez-Jim{\a'e}nez},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Comput. Math. Methods},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Formal concept analysis with negative attributes for forgery detection},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2021},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number = {6},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {3},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/cmm/OjedaAciegoR21.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1002/CMM4.1124},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Tue, 31 Jan 2023 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1002/cmm4.1124},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1002/CMM4.1124" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1002/CMM4.1124" class="plumx-details" data-site="plum" data-hide-when-empty="true">Formal concept analysis with negative attributes for forgery detection</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1002/CMM4.1124"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Devlin_2024></a>[[1]](#cite-Devlin_2024) C. Devlin, M. Morelato, and S. Baechler. “Forensic intelligence: Expanding the potential of forensic document examination”. In: _WIREs Forensic Science_ 6.5 (Jul. 2024). ISSN: 2573-9468. DOI: [10.1002/wfs2.1528](https://doi.org/10.1002%2Fwfs2.1528). URL: [http://dx.doi.org/10.1002/wfs2.1528](http://dx.doi.org/10.1002/wfs2.1528).

<a name=bib-Ojeda_Aciego_2022></a>[[2]](#cite-Ojeda_Aciego_2022) M. Ojeda-Aciego and J. M. Rodríguez-Jiménez. “Advances in Forgery Detection of Driving Licences Using Truthfulness Degrees”. In: _Computational Intelligence and Mathematics for Tackling Complex Problems 4_. Springer International Publishing, Sep. 2022, p. 145–151. ISBN: 9783031077074. DOI: [10.1007/978-3-031-07707-4_18](https://doi.org/10.1007%2F978-3-031-07707-4_18). URL: [http://dx.doi.org/10.1007/978-3-031-07707-4_18](http://dx.doi.org/10.1007/978-3-031-07707-4_18).

<a name=bib-Sokol_2023></a>[[3]](#cite-Sokol_2023) P. Sokol, Ľ. Antoni, O. Krídlo, et al. “Formal concept analysis approach to understand digital evidence relationships”. In: _International Journal of Approximate Reasoning_ 159 (Aug. 2023), p. 108940. ISSN: 0888-613X. DOI: [10.1016/j.ijar.2023.108940](https://doi.org/10.1016%2Fj.ijar.2023.108940). URL: [http://dx.doi.org/10.1016/j.ijar.2023.108940](http://dx.doi.org/10.1016/j.ijar.2023.108940).

