---
title: Relational Galois connections between transitive fuzzy digraphs
type: journals
author:
- <a href='/people/staff/ipcabrera/' style='color:rgb(100,0,50);'>Inmaculada de las
  Peñas Cabrera</a>
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero Ortega</a>
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda Aciego</a>
- Bernard De Baets
date: '2020-01-01'
categories:
- Formal concept analysis
- Fuzzy logic
- Fuzzy sets
- Uncertainty
doi: 10.1002/mma.6302
slug: 2020-IPC-PC-EMV-MOA-BDB-Relational
keywords: ''
project: 2019-flair
details: Mathematical Methods in the Applied Sciences vol. 43 (9), pages 5673 – 5680.
listing:
- id: funding
  contents: funding.yml
  type: default
  sort: date desc
---




# Abstract

Fuzzy-directed graphs are often chosen as the data structure to model and implement solutions to several problems in the applied sciences. Galois connections have also shown to be useful both in theoretical and in practical problems.

In this paper, the notion of relational Galois connection is extended to be applied between transitive fuzzy directed graphs. In this framework, the components of the connection are crisp relations satisfying certain reasonable properties given in terms of the so-called full powering.


# Funding
::: {.callout-note appearance='minimal' collapse=false}
## Projects funding this work

:::{#funding}
:::
:::




# Citation
Please, cite this work as:


<a name=bib-Cabrera20205673></a>[[Cab+20]](#cite-Cabrera20205673) I. P. Cabrera, P. Cordero, E. Muñoz-Velasco, et al. “Relational Galois connections between transitive fuzzy digraphs”. In: _Mathematical Methods in the Applied Sciences_ 43.9 (2020). Cited by: 8, p. 5673 – 5680. DOI: [10.1002/mma.6302](https://doi.org/10.1002%2Fmma.6302). URL: [https://www.scopus.com/inward/record.uri?eid=2-s2.0-85084927857&doi=10.1002

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@ARTICLE{Cabrera20205673,<br>&nbsp;&nbsp;&nbsp;&nbsp;	author = {Cabrera, Inma P. and Cordero, Pablo and Muñoz-Velasco, Emilio and Ojeda-Aciego, Manuel and De Baets, Bernard},<br>&nbsp;&nbsp;&nbsp;&nbsp;	title = {Relational Galois connections between transitive fuzzy digraphs},<br>&nbsp;&nbsp;&nbsp;&nbsp;	year = {2020},<br>&nbsp;&nbsp;&nbsp;&nbsp;	journal = {Mathematical Methods in the Applied Sciences},<br>&nbsp;&nbsp;&nbsp;&nbsp;	volume = {43},<br>&nbsp;&nbsp;&nbsp;&nbsp;	number = {9},<br>&nbsp;&nbsp;&nbsp;&nbsp;	pages = {5673 – 5680},<br>&nbsp;&nbsp;&nbsp;&nbsp;	doi = {10.1002/mma.6302},<br>&nbsp;&nbsp;&nbsp;&nbsp;	url = {https://www.scopus.com/inward/record.uri?eid=2-s2.0-85084927857&doi=10.1002%2fmma.6302&partnerID=40&md5=f62ecd3bbabdb3af560c55aac0694690},<br>&nbsp;&nbsp;&nbsp;&nbsp;	type = {Article},<br>&nbsp;&nbsp;&nbsp;&nbsp;	publication_stage = {Final},<br>&nbsp;&nbsp;&nbsp;&nbsp;	source = {Scopus},<br>&nbsp;&nbsp;&nbsp;&nbsp;	note = {Cited by: 8}<br>}

:::

