---
title: '{CAISL:} Simplification Logic for Conditional Attribute Implications'
author:
- Estrella Rodríguez Lorenzo
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/enciso/' style='color:rgb(100,0,50);'>Manuel Enciso</a>
- Rokia Missaoui
- <a href='/people/staff/amora/' style='color:rgb(100,0,50);'>Ángel Mora</a>
date: '2016'
categories: uncategorised
slug: 2016/SiLoCoAtIm
details: Proceedings of the Thirteenth International Conference on Concept Lattices
  and Their Applications, Moscow, Russia, July 18-22, 2016 , {CEUR} Workshop Proceedings
  vol. 1624, pages 337--348.
---



# Abstract


In this work, we present a sound and complete axiomatic system for conditional attribute implications (CAI s) in Triadic Concept
Analysis (TCA). Our approach is strongly based on the Simplification paradigm which offers a more suitable way for automated reasoning than the one based on Armstrong’s Axioms. We also present an automated method to prove the derivability of a CAI from a set of CAI s.








# Citation
Please, cite this work as:


<a name=bib-Lorenzo2016></a>[[Rod+16]](#cite-Lorenzo2016) E. Rodr\'\iguezLorenzo, P. Cordero, M. Enciso, et al. “CAISL: Simplification Logic for Conditional Attribute Implications”. In: _Proceedings of the Thirteenth International Conference on Concept Lattices and Their Applications, Moscow, Russia, July 18-22, 2016_. Ed. by M. Huchard and S. O. Kuznetsov. Vol. 1624. CEUR Workshop Proceedings. CEUR-WS.org, 2016, pp. 337-348. URL: [https://ceur-ws.org/Vol-1624/paper26.pdf](https://ceur-ws.org/Vol-1624/paper26.pdf).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Lorenzo2016,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Estrella Rodr\'\iguez Lorenzo and Pablo Cordero and Manuel Enciso and Rokia Missaoui and {\a'A}ngel Mora},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Proceedings of the Thirteenth International Conference on Concept Lattices and Their Applications, Moscow, Russia, July 18-22, 2016},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {{CAISL:} Simplification Logic for Conditional Attribute Implications},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2016},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Marianne Huchard and Sergei O. Kuznetsov},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {337--348},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {CEUR-WS.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {{CEUR} Workshop Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {1624},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {In this work, we present a sound and complete axiomatic system for conditional attribute implications (CAI s) in Triadic Concept<br>&nbsp;&nbsp;&nbsp;&nbsp;Analysis (TCA). Our approach is strongly based on the Simplification paradigm which offers a more suitable way for automated reasoning than the one based on Armstrong’s Axioms. We also present an automated method to prove the derivability of a CAI from a set of CAI s.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/cla/LorenzoCEMB16.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 10 Mar 2023 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://ceur-ws.org/Vol-1624/paper26.pdf},<br>}

:::








