---
title: A neural implementation of multi-adjoint logic programming
author:
- Jesús Medina
- Enrique Mérida Casermeiro
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '2004'
categories: uncategorised
slug: 2004/NeImLoPr
details: J. Appl. Log. vol. 2 (3), pages 301--324.
doi: 10.1016/J.JAL.2004.03.006
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Medina2004a></a>[[MCO04]](#cite-Medina2004a) J. Medina, E. M. Casermeiro, and M. Ojeda-Aciego. “A neural implementation of multi-adjoint logic programming”. In: _J. Appl. Log._ 2.3 (2004), pp. 301-324. DOI: [10.1016/J.JAL.2004.03.006](https://doi.org/10.1016%2FJ.JAL.2004.03.006). URL: [https://doi.org/10.1016/j.jal.2004.03.006](https://doi.org/10.1016/j.jal.2004.03.006).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{Medina2004a,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Jes{\a'u}s Medina and Enrique M{\a'e}rida Casermeiro and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {J. Appl. Log.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {A neural implementation of multi-adjoint logic programming},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2004},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number = {3},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {301--324},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {2},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/japll/MedinaCO04.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1016/J.JAL.2004.03.006},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Tue, 16 Feb 2021 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1016/j.jal.2004.03.006},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1016/J.JAL.2004.03.006" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1016/J.JAL.2004.03.006" class="plumx-details" data-site="plum" data-hide-when-empty="true">A neural implementation of multi-adjoint logic programming</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1016/J.JAL.2004.03.006"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Abubakar_2023></a>[[1]](#cite-Abubakar_2023) H. Abubakar and S. Yusuf. “Logic-Based Reverse Analysis: A Covid-19 Surveillance Data Set Classification Problem”. In: _Journal of Basic and Applied Research in Biomedicine_ 9.1 (Nov. 2023), p. 17–25. ISSN: 2413-7014. DOI: [10.51152/jbarbiomed.v9i1.227](https://doi.org/10.51152%2Fjbarbiomed.v9i1.227). URL: [http://dx.doi.org/10.51152/jbarbiomed.v9i1.227](http://dx.doi.org/10.51152/jbarbiomed.v9i1.227).

<a name=bib-Chortaras_2006></a>[[2]](#cite-Chortaras_2006) A. Chortaras, G. Stamou, and A. Stafylopatis. “Adaptation of Weighted Fuzzy Programs”. In: _Artificial Neural Networks – ICANN 2006_. Springer Berlin Heidelberg, 2006, p. 45–54. ISBN: 9783540388739. DOI: [10.1007/11840930_5](https://doi.org/10.1007%2F11840930_5). URL: [http://dx.doi.org/10.1007/11840930_5](http://dx.doi.org/10.1007/11840930_5).

<a name=bib-Chortaras_2008></a>[[3]](#cite-Chortaras_2008) A. Chortaras, G. Stamou, and A. Stafylopatis. “Connectionist weighted fuzzy logic programs”. In: _Neurocomputing_ 71.13–15 (Aug. 2008), p. 2456–2469. ISSN: 0925-2312. DOI: [10.1016/j.neucom.2007.11.034](https://doi.org/10.1016%2Fj.neucom.2007.11.034). URL: [http://dx.doi.org/10.1016/j.neucom.2007.11.034](http://dx.doi.org/10.1016/j.neucom.2007.11.034).

<a name=bib-CHORTARAS_2009></a>[[4]](#cite-CHORTARAS_2009) A. CHORTARAS, G. STAMOU, and A. STAFYLOPATIS. “DEFINITION AND ADAPTATION OF WEIGHTED FUZZY LOGIC PROGRAMS”. In: _International Journal of Uncertainty, Fuzziness and Knowledge-Based Systems_ 17.01 (Feb. 2009), p. 85–135. ISSN: 1793-6411. DOI: [10.1142/s0218488509005759](https://doi.org/10.1142%2Fs0218488509005759). URL: [http://dx.doi.org/10.1142/s0218488509005759](http://dx.doi.org/10.1142/s0218488509005759).

<a name=bib-Chortaras_20061></a>[[5]](#cite-Chortaras_20061) A. Chortaras, G. Stamou, A. Stafylopatis, et al. “A Connectionist Model for Weighted Fuzzy Programs”. In: _The 2006 IEEE International Joint Conference on Neural Network Proceedings_. IEEE, 2006, p. 3055–3062. DOI: [10.1109/ijcnn.2006.247265](https://doi.org/10.1109%2Fijcnn.2006.247265). URL: [http://dx.doi.org/10.1109/ijcnn.2006.247265](http://dx.doi.org/10.1109/ijcnn.2006.247265).

<a name=bib-Cornejo_2018></a>[[6]](#cite-Cornejo_2018) M. E. Cornejo, D. Lobo, and J. Medina. “Syntax and semantics of multi-adjoint normal logic programming”. In: _Fuzzy Sets and Systems_ 345 (Aug. 2018), p. 41–62. ISSN: 0165-0114. DOI: [10.1016/j.fss.2017.12.009](https://doi.org/10.1016%2Fj.fss.2017.12.009). URL: [http://dx.doi.org/10.1016/j.fss.2017.12.009](http://dx.doi.org/10.1016/j.fss.2017.12.009).

<a name=bib-Damasio_2006></a>[[7]](#cite-Damasio_2006) C. Damasio, J. Medina, and M. Ojeda-Aciego. “A Tabulation Proof Procedure for First-order Residuated Logic Programs: Soundness, Completeness and Optimizations”. In: _2006 IEEE International Conference on Fuzzy Systems_. IEEE, 2006, p. 2004–2011. DOI: [10.1109/fuzzy.2006.1681978](https://doi.org/10.1109%2Ffuzzy.2006.1681978). URL: [http://dx.doi.org/10.1109/fuzzy.2006.1681978](http://dx.doi.org/10.1109/fuzzy.2006.1681978).

<a name=bib-de_Lima_2020></a>[[8]](#cite-de_Lima_2020) A. A. de Lima, B. Bedregal, and I. Mezzomo. “Ordinal sums of the main classes of fuzzy negations and the natural negations of t-norms, t-conorms and fuzzy implications”. In: _International Journal of Approximate Reasoning_ 116 (Jan. 2020), p. 19–32. ISSN: 0888-613X. DOI: [10.1016/j.ijar.2019.10.004](https://doi.org/10.1016%2Fj.ijar.2019.10.004). URL: [http://dx.doi.org/10.1016/j.ijar.2019.10.004](http://dx.doi.org/10.1016/j.ijar.2019.10.004).

<a name=bib-Madrid_2023></a>[[9]](#cite-Madrid_2023) N. Madrid and M. Ojeda-Aciego. “The f-index of inclusion as optimal adjoint pair for fuzzy modus ponens”. In: _Fuzzy Sets and Systems_ 466 (Aug. 2023), p. 108474. ISSN: 0165-0114. DOI: [10.1016/j.fss.2023.01.009](https://doi.org/10.1016%2Fj.fss.2023.01.009). URL: [http://dx.doi.org/10.1016/j.fss.2023.01.009](http://dx.doi.org/10.1016/j.fss.2023.01.009).

<a name=bib-Medina_2010></a>[[10]](#cite-Medina_2010) J. Medina. “Adjoint Pairs on Interval-Valued Fuzzy Sets”. In: _Information Processing and Management of Uncertainty in Knowledge-Based Systems. Applications_. Springer Berlin Heidelberg, 2010, p. 430–439. ISBN: 9783642140587. DOI: [10.1007/978-3-642-14058-7_45](https://doi.org/10.1007%2F978-3-642-14058-7_45). URL: [http://dx.doi.org/10.1007/978-3-642-14058-7_45](http://dx.doi.org/10.1007/978-3-642-14058-7_45).

<a name=bib-Medina_2004></a>[[11]](#cite-Medina_2004) J. Medina, E. Mérida-Casermeiro, and M. Ojeda-Aciego. “Decomposing Ordinal Sums in Neural Multi-adjoint Logic Programs”. In: _Advances in Artificial Intelligence – IBERAMIA 2004_. Springer Berlin Heidelberg, 2004, p. 717–726. ISBN: 9783540304982. DOI: [10.1007/978-3-540-30498-2_72](https://doi.org/10.1007%2F978-3-540-30498-2_72). URL: [http://dx.doi.org/10.1007/978-3-540-30498-2_72](http://dx.doi.org/10.1007/978-3-540-30498-2_72).

<a name=bib-Medina_2005></a>[[12]](#cite-Medina_2005) J. Medina, E. Mérida-Casermeiro, and M. Ojeda-Aciego. “Interval-Valued Neural Multi-adjoint Logic Programs”. In: _Mechanisms, Symbols, and Models Underlying Cognition_. Springer Berlin Heidelberg, 2005, p. 518–527. ISBN: 9783540316725. DOI: [10.1007/11499220_53](https://doi.org/10.1007%2F11499220_53). URL: [http://dx.doi.org/10.1007/11499220_53](http://dx.doi.org/10.1007/11499220_53).

<a name=bib-Xu_2013></a>[[13]](#cite-Xu_2013) Y. Xu, J. Liu, X. Zhong, et al. “Multiary α-Resolution Principle for a Lattice-Valued Logic”. In: _IEEE Transactions on Fuzzy Systems_ 21.5 (Oct. 2013), p. 898–912. ISSN: 1941-0034. DOI: [10.1109/tfuzz.2012.2236095](https://doi.org/10.1109%2Ftfuzz.2012.2236095). URL: [http://dx.doi.org/10.1109/tfuzz.2012.2236095](http://dx.doi.org/10.1109/tfuzz.2012.2236095).

