---
title: 'Extracting Interval Temporal Logic Rules: {A} First Approach'
author:
- Davide Bresolin
- Enrico Cominato
- Simone Gnani
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
- Guido Sciavicco
date: '2018'
categories: uncategorised
slug: 2018/ExInTeLoFiAp
details: 25th International Symposium on Temporal Representation and Reasoning, {TIME}
  2018, Warsaw, Poland, October 15-17, 2018 , LIPIcs vol. 120, pages 7:1--7:15.
doi: 10.4230/LIPICS.TIME.2018.7
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Bresolin2018a></a>[[Bre+18]](#cite-Bresolin2018a) D. Bresolin, E. Cominato, S. Gnani, et al. “Extracting Interval Temporal Logic Rules: A First Approach”. In: _25th International Symposium on Temporal Representation and Reasoning, TIME 2018, Warsaw, Poland, October 15-17, 2018_. Ed. by N. Alechina, K. Nørvåg and W. Penczek. Vol. 120. LIPIcs. Schloss Dagstuhl - Leibniz-Zentrum für Informatik, 2018, pp. 7:1-7:15. DOI: [10.4230/LIPICS.TIME.2018.7](https://doi.org/10.4230%2FLIPICS.TIME.2018.7). URL: [https://doi.org/10.4230/LIPIcs.TIME.2018.7](https://doi.org/10.4230/LIPIcs.TIME.2018.7).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Bresolin2018a,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Davide Bresolin and Enrico Cominato and Simone Gnani and Emilio Mu~noz-Velasco and Guido Sciavicco},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {25th International Symposium on Temporal Representation and Reasoning, {TIME} 2018, Warsaw, Poland, October 15-17, 2018},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Extracting Interval Temporal Logic Rules: {A} First Approach},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2018},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Natasha Alechina and Kjetil N{\o}rv{\r a}g and Wojciech Penczek},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {7:1--7:15},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Schloss Dagstuhl - Leibniz-Zentrum f{\"{u}}r Informatik},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {LIPIcs},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {120},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/time/BresolinCGMS18.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.4230/LIPICS.TIME.2018.7},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Wed, 07 Dec 2022 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.4230/LIPIcs.TIME.2018.7},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.4230/LIPICS.TIME.2018.7" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.4230/LIPICS.TIME.2018.7" class="plumx-details" data-site="plum" data-hide-when-empty="true">Extracting Interval Temporal Logic Rules: {A} First Approach</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.4230/LIPICS.TIME.2018.7"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Sciavicco_2019></a>[[1]](#cite-Sciavicco_2019) G. Sciavicco, I. E. Stan, and A. Vaccari. “Towards a General Method for Logical Rule Extraction from Time Series”. In: _From Bioinspired Systems and Biomedical Applications to Machine Learning_. Springer International Publishing, 2019, p. 3–12. ISBN: 9783030196516. DOI: [10.1007/978-3-030-19651-6_1](https://doi.org/10.1007%2F978-3-030-19651-6_1). URL: [http://dx.doi.org/10.1007/978-3-030-19651-6_1](http://dx.doi.org/10.1007/978-3-030-19651-6_1).

