---
title: 'Conference paper accepted: <em>Using Logic to Determine Key Items in Math
  Education</em>'
author: Manuel Ojeda-Hernández, Francisco Pérez-Gámez, Ángel Mora Bonilla, Domingo
  López-Rodríguez
date: '2021-07-20'
categories:
- E-learning
- Formal concept analysis
- Fuzzy logic
comments:
  giscus:
    repo: quarto-dev/quarto-docs
---

The work <u>Using Logic to Determine Key Items in Math Education</u> has been published in <em>IADIS International Conference e-Learning 2021 (part of MCCSIS 2021)</em>.

<u>Abstract</u>:



Due to the COVID-19 restrictions, high-schools in Spain are having both online and in-class lectures.  As a result, the students can use not only the information provided by the teachers in class, but they can also use several other methods such as videos and online examples that allow the students to have materials from different places. In this paper, we analyse the Mathematics results of the first two terms in a secondary school from Andalusia. This analysis can help find the central units of the subject found, that is, giving enough background knowledge to keep up with the module.  When these are found, the teachers can improve the learning and the results in the following years.




For more details on this work, visit <a href='/publications/conferences/2021-e-learning'>its own page</a>.
