---
title: Increasing the efficiency of automated theorem proving
author:
- Gabriel Aguilera
- <a href='/people/staff/ipguzman/' style='color:rgb(100,0,50);'>Inma P. de Guzmán</a>
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '1995'
categories: uncategorised
slug: 1995/InEfAuThPr
details: J. Appl. Non Class. Logics vol. 5 (1), pages 9--29.
doi: 10.1080/11663081.1995.10510841
---



# Abstract


ABSTRACT In this work a new Automated Theorem Prover (ATP) via refutation for classical logic and which does not require the conversion to clausal form, named TAS-D++, is introduced. The main objective in the design of this ATP was to obtain a parallel and computationally efficient method naturally extensible to non-standard logics (concretely, to temporal logics, see [12]). TAS-D++ works by using transformations of the syntactic trees of the formulas and, as tableaux and matrix style provers [6, 15, 16], it is Gentzen-based. Its power is mainly based in the efficient extraction of implicit information in the syntactic trees (in difference with the standard ATPs via refutation) to detect both: • simultaneously unsatisfiable or equivalent formulas to that being studied • valid, unsatisfiable, equivalent or equal subformulas. TAS-D++ is sound and complete and, moreover, it is a method that generates countermodels in a natural way.








# Citation
Please, cite this work as:


<a name=bib-Aguilera1995></a>[[AGO95]](#cite-Aguilera1995) G. Aguilera, I. P. de Guzmán, and M. Ojeda-Aciego. “Increasing the efficiency of automated theorem proving”. In: _J. Appl. Non Class. Logics_ 5.1 (1995), pp. 9-29. DOI: [10.1080/11663081.1995.10510841](https://doi.org/10.1080%2F11663081.1995.10510841). URL: [https://doi.org/10.1080/11663081.1995.10510841](https://doi.org/10.1080/11663081.1995.10510841).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{Aguilera1995,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Gabriel Aguilera and Inman P. {de Guzm{\a'a}n} and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {J. Appl. Non Class. Logics},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Increasing the efficiency of automated theorem proving},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {1995},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number = {1},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {9--29},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {5},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/jancl/AguileraGO95.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1080/11663081.1995.10510841},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 26 May 2023 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1080/11663081.1995.10510841},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1080/11663081.1995.10510841" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1080/11663081.1995.10510841" class="plumx-details" data-site="plum" data-hide-when-empty="true">Increasing the efficiency of automated theorem proving</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1080/11663081.1995.10510841"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Aguilera_1999></a>[[1]](#cite-Aguilera_1999) G. Aguilera, I. P. de Guzmán, M. Ojeda-Aciego, et al. “Reducing signed propositional formulas”. In: _Soft Computing - A Fusion of Foundations, Methodologies and Applications_ 2.4 (Feb. 1999), p. 157–166. ISSN: 1433-7479. DOI: [10.1007/s005000050048](https://doi.org/10.1007%2Fs005000050048). URL: [http://dx.doi.org/10.1007/s005000050048](http://dx.doi.org/10.1007/s005000050048).

<a name=bib-Altamirano_2000></a>[[2]](#cite-Altamirano_2000) E. Altamirano and G. Escalada-Imaz. “An Efficient Proof Method for Non-clausal Reasoning”. In: _Foundations of Intelligent Systems_. Springer Berlin Heidelberg, 2000, p. 534–542. ISBN: 9783540399636. DOI: [10.1007/3-540-39963-1_56](https://doi.org/10.1007%2F3-540-39963-1_56). URL: [http://dx.doi.org/10.1007/3-540-39963-1_56](http://dx.doi.org/10.1007/3-540-39963-1_56).

<a name=bib-Altamirano_20001></a>[[3]](#cite-Altamirano_20001) E. Altamirano and G. Escalada-Imaz. “Finding Tractable Formulas in NNF”. In: _Computational Logic — CL 2000_. Springer Berlin Heidelberg, 2000, p. 493–507. ISBN: 9783540449577. DOI: [10.1007/3-540-44957-4_33](https://doi.org/10.1007%2F3-540-44957-4_33). URL: [http://dx.doi.org/10.1007/3-540-44957-4_33](http://dx.doi.org/10.1007/3-540-44957-4_33).

<a name=bib-Enciso_1996></a>[[4]](#cite-Enciso_1996) M. Enciso, I. P. Guzmán, and C. Rossi. “Temporal reasoning over linear discrete time”. In: _Logics in Artificial Intelligence_. Springer Berlin Heidelberg, 1996, p. 303–319. ISBN: 9783540706434. DOI: [10.1007/3-540-61630-6_22](https://doi.org/10.1007%2F3-540-61630-6_22). URL: [http://dx.doi.org/10.1007/3-540-61630-6_22](http://dx.doi.org/10.1007/3-540-61630-6_22).

<a name=bib-Guti_rrez_2000></a>[[5]](#cite-Guti_rrez_2000) G. Gutiérrez, I. P. de Guzmán, J. Martínez, et al. “Reduction Theorems for Boolean Formulas Using Δ-Trees”. In: _Logics in Artificial Intelligence_. Springer Berlin Heidelberg, 2000, p. 179–192. ISBN: 9783540400066. DOI: [10.1007/3-540-40006-0_13](https://doi.org/10.1007%2F3-540-40006-0_13). URL: [http://dx.doi.org/10.1007/3-540-40006-0_13](http://dx.doi.org/10.1007/3-540-40006-0_13).

<a name=bib-de_Guzm_n_1999></a>[[6]](#cite-de_Guzm_n_1999) I. P. de Guzmán, P. Cordero, and M. Enciso. “Structure Theorems for Closed Sets of Implicates/Implicants in Temporal Logic”. In: _Progress in Artificial Intelligence_. Springer Berlin Heidelberg, 1999, p. 193–207. ISBN: 9783540481591. DOI: [10.1007/3-540-48159-1_14](https://doi.org/10.1007%2F3-540-48159-1_14). URL: [http://dx.doi.org/10.1007/3-540-48159-1_14](http://dx.doi.org/10.1007/3-540-48159-1_14).

<a name=bib-de_Guzm_n_1998></a>[[7]](#cite-de_Guzm_n_1998) I. P. de Guzmán, M. Ojeda-Aciego, and A. Valverde. “Implicates and Reduction Techniques for Temporal Logics”. In: _Logics in Artificial Intelligence_. Springer Berlin Heidelberg, 1998, p. 309–323. ISBN: 9783540495451. DOI: [10.1007/3-540-49545-2_21](https://doi.org/10.1007%2F3-540-49545-2_21). URL: [http://dx.doi.org/10.1007/3-540-49545-2_21](http://dx.doi.org/10.1007/3-540-49545-2_21).

<a name=bib-H_hnle_2001></a>[[8]](#cite-H_hnle_2001) R. Hähnle. “Advanced Many-Valued Logics”. In: _Handbook of Philosophical Logic_. Springer Netherlands, 2001, p. 297–395. ISBN: 9789401704526. DOI: [10.1007/978-94-017-0452-6_5](https://doi.org/10.1007%2F978-94-017-0452-6_5). URL: [http://dx.doi.org/10.1007/978-94-017-0452-6_5](http://dx.doi.org/10.1007/978-94-017-0452-6_5).

<a name=bib-httpsdoiorg1022028d291-25703></a>[[9]](#cite-httpsdoiorg1022028d291-25703) U. Hustadt. _Resolution-based decision procedures for subclasses of first-order logic_. En. 1999. DOI: [10.22028/D291-25703](https://doi.org/10.22028%2FD291-25703). URL: [https://publikationen.sulb.uni-saarland.de/handle/20.500.11880/25759](https://publikationen.sulb.uni-saarland.de/handle/20.500.11880/25759).

<a name=bib-Imaz_2023></a>[[10]](#cite-Imaz_2023) G. E. Imaz. “A first polynomial non-clausal class in many-valued logic”. In: _Fuzzy Sets and Systems_ 456 (Mar. 2023), p. 1–37. ISSN: 0165-0114. DOI: [10.1016/j.fss.2022.10.008](https://doi.org/10.1016%2Fj.fss.2022.10.008). URL: [http://dx.doi.org/10.1016/j.fss.2022.10.008](http://dx.doi.org/10.1016/j.fss.2022.10.008).

