---
title: A logic framework for reasoning with movement based on fuzzy qualitative representation
author:
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
- Alfredo Burrieza
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '2014'
categories: uncategorised
slug: 2014/LoFrReMoBaFuQuRe
details: Fuzzy Sets Syst. vol. 242 , pages 114--131.
doi: 10.1016/J.FSS.2013.07.014
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-MunozVelasco2014></a>[[MBO14]](#cite-MunozVelasco2014) E. Mu~noz-Velasco, A. Burrieza, and M. Ojeda-Aciego. “A logic framework for reasoning with movement based on fuzzy qualitative representation”. In: _Fuzzy Sets Syst._ 242 (2014), pp. 114-131. DOI: [10.1016/J.FSS.2013.07.014](https://doi.org/10.1016%2FJ.FSS.2013.07.014). URL: [https://doi.org/10.1016/j.fss.2013.07.014](https://doi.org/10.1016/j.fss.2013.07.014).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{MunozVelasco2014,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Emilio Mu~noz-Velasco and Alfredo Burrieza and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Fuzzy Sets Syst.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {A logic framework for reasoning with movement based on fuzzy qualitative representation},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2014},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {114--131},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {242},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/fss/Munoz-VelascoBO14.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1016/J.FSS.2013.07.014},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Wed, 19 Feb 2020 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1016/j.fss.2013.07.014},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1016/J.FSS.2013.07.014" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1016/J.FSS.2013.07.014" class="plumx-details" data-site="plum" data-hide-when-empty="true">A logic framework for reasoning with movement based on fuzzy qualitative representation</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1016/J.FSS.2013.07.014"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Burrieza_2019></a>[[1]](#cite-Burrieza_2019) A. Burrieza, E. Muñoz-Velasco, and M. Ojeda-Aciego. “A flexible logic-based approach to closeness using order of magnitude qualitative reasoning”. In: _Logic Journal of the IGPL_ 28.1 (Dec. 2019), p. 121–133. ISSN: 1368-9894. DOI: [10.1093/jigpal/jzz076](https://doi.org/10.1093%2Fjigpal%2Fjzz076). URL: [http://dx.doi.org/10.1093/jigpal/jzz076](http://dx.doi.org/10.1093/jigpal/jzz076).

<a name=bib-Burrieza_2016></a>[[2]](#cite-Burrieza_2016) A. Burrieza, E. Muñoz-Velasco, and M. Ojeda-Aciego. “A Hybrid Approach to Closeness in the Framework of Order of Magnitude Qualitative Reasoning”. In: _Hybrid Artificial Intelligent Systems_. Springer International Publishing, 2016, p. 721–729. ISBN: 9783319320342. DOI: [10.1007/978-3-319-32034-2_60](https://doi.org/10.1007%2F978-3-319-32034-2_60). URL: [http://dx.doi.org/10.1007/978-3-319-32034-2_60](http://dx.doi.org/10.1007/978-3-319-32034-2_60).

<a name=bib-Burrieza_2018></a>[[3]](#cite-Burrieza_2018) A. Burrieza, E. Muñoz-Velasco, and M. Ojeda-Aciego. “Logics for Order-of-Magnitude Qualitative Reasoning: Formalizing Negligibility”. In: _Ewa Orłowska on Relational Methods in Logic and Computer Science_. Springer International Publishing, 2018, p. 203–231. ISBN: 9783319978796. DOI: [10.1007/978-3-319-97879-6_8](https://doi.org/10.1007%2F978-3-319-97879-6_8). URL: [http://dx.doi.org/10.1007/978-3-319-97879-6_8](http://dx.doi.org/10.1007/978-3-319-97879-6_8).

<a name=bib-Davari_2019></a>[[4]](#cite-Davari_2019) S. Davari and N. Ghadiri. “Fuzzy Region Connection Calculus and Its Application in Fuzzy Spatial Skyline Queries”. In: _Intelligent Computing_. Springer International Publishing, 2019, p. 659–677. ISBN: 9783030228712. DOI: [10.1007/978-3-030-22871-2_45](https://doi.org/10.1007%2F978-3-030-22871-2_45). URL: [http://dx.doi.org/10.1007/978-3-030-22871-2_45](http://dx.doi.org/10.1007/978-3-030-22871-2_45).

<a name=bib-Goli_ska_Pilarek_2015></a>[[5]](#cite-Goli_ska_Pilarek_2015) J. Goli ska-Pilarek and E. Munoz-Velasco. “A hybrid qualitative approach for relative movements”. In: _Logic Journal of IGPL_ 23.3 (Apr. 2015), p. 410–420. ISSN: 1368-9894. DOI: [10.1093/jigpal/jzv012](https://doi.org/10.1093%2Fjigpal%2Fjzv012). URL: [http://dx.doi.org/10.1093/jigpal/jzv012](http://dx.doi.org/10.1093/jigpal/jzv012).

<a name=bib-Sioutis_2014></a>[[6]](#cite-Sioutis_2014) M. Sioutis, J. Condotta, Y. Salhi, et al. “A Qualitative Spatio-Temporal Framework Based on Point Algebra”. In: _Artificial Intelligence: Methodology, Systems, and Applications_. Springer International Publishing, 2014, p. 117–128. ISBN: 9783319105543. DOI: [10.1007/978-3-319-10554-3_11](https://doi.org/10.1007%2F978-3-319-10554-3_11). URL: [http://dx.doi.org/10.1007/978-3-319-10554-3_11](http://dx.doi.org/10.1007/978-3-319-10554-3_11).

<a name=bib-Wa_ga_2021></a>[[7]](#cite-Wa_ga_2021) P. A. Wałęga and M. Zawidzki. “Subject-oriented spatial logic”. In: _Information and Computation_ 280 (Oct. 2021), p. 104643. ISSN: 0890-5401. DOI: [10.1016/j.ic.2020.104643](https://doi.org/10.1016%2Fj.ic.2020.104643). URL: [http://dx.doi.org/10.1016/j.ic.2020.104643](http://dx.doi.org/10.1016/j.ic.2020.104643).

<a name=bib-Wa_ga_2015></a>[[8]](#cite-Wa_ga_2015) P. Wałęga and E. Muñoz-Velasco. “A Movement Control System Based on Qualitative Reasoning”. In: _10th International Conference on Soft Computing Models in Industrial and Environmental Applications_. Springer International Publishing, 2015, p. 179–189. ISBN: 9783319197197. DOI: [10.1007/978-3-319-19719-7_16](https://doi.org/10.1007%2F978-3-319-19719-7_16). URL: [http://dx.doi.org/10.1007/978-3-319-19719-7_16](http://dx.doi.org/10.1007/978-3-319-19719-7_16).

