---
title: Fuzzy relational Galois connections between fuzzy transitive digraphs
type: journals
author:
- <a href='/people/staff/ipcabrera/' style='color:rgb(100,0,50);'>Inma P. Cabrera</a>
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
- Bernard De Baets
date: '2023-01-01'
categories:
- Formal concept analysis
- Fuzzy logic
- Fuzzy sets
- Uncertainty
doi: 10.1016/j.fss.2022.12.012
slug: 2023/FuReGaCoFuTrDi
keywords: ''
project: 2019-flair
details: 'Fuzzy Sets Syst. 463: 108456'
listing:
- id: funding
  contents: funding.yml
  type: default
  sort: date desc
---



# Abstract

We present a fuzzy version of the notion of relational Galois connection between fuzzy transitive directed graphs (fuzzy T-digraphs) on the specific setting in which the underlying algebra of truth values is a complete Heyting algebra. The components of such fuzzy Galois connection are fuzzy relations satisfying certain reasonable properties expressed in terms of the so-called full powering. Moreover, we provide a necessary and sufficient condition under which it is possible to construct a right adjoint for a given fuzzy relation between a fuzzy T-digraph and an unstructured set.


# Funding
::: {.callout-note appearance='minimal' collapse=false}
## Projects funding this work

:::{#funding}
:::
:::








# Citation
Please, cite this work as:


<a name=bib-Cabrera2023></a>[[Cab+23]](#cite-Cabrera2023) I. Cabrera, P. Cordero, E. Muñoz-Velasco, et al. “Fuzzy relational Galois connections between fuzzy transitive digraphs”. In: _Fuzzy Sets and Systems_ 463 (2023). Cited by: 0; All Open Access, Green Open Access, Hybrid Gold Open Access. DOI: [10.1016/j.fss.2022.12.012](https://doi.org/10.1016%2Fj.fss.2022.12.012). URL: [https://www.scopus.com/inward/record.uri?eid=2-s2.0-85146018750&doi=10.1016

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@ARTICLE{Cabrera2023,<br>&nbsp;&nbsp;&nbsp;&nbsp;	author = {Cabrera, I.P. and Cordero, P. and Muñoz-Velasco, E. and Ojeda-Aciego, M. and De Baets, B.},<br>&nbsp;&nbsp;&nbsp;&nbsp;	title = {Fuzzy relational Galois connections between fuzzy transitive digraphs},<br>&nbsp;&nbsp;&nbsp;&nbsp;	year = {2023},<br>&nbsp;&nbsp;&nbsp;&nbsp;	journal = {Fuzzy Sets and Systems},<br>&nbsp;&nbsp;&nbsp;&nbsp;	volume = {463},<br>&nbsp;&nbsp;&nbsp;&nbsp;	doi = {10.1016/j.fss.2022.12.012},<br>&nbsp;&nbsp;&nbsp;&nbsp;	url = {https://www.scopus.com/inward/record.uri?eid=2-s2.0-85146018750&doi=10.1016%2fj.fss.2022.12.012&partnerID=40&md5=ab3b57e7c17a2ee95c32bf4300fc353d},<br>&nbsp;&nbsp;&nbsp;&nbsp;	type = {Article},<br>&nbsp;&nbsp;&nbsp;&nbsp;	publication_stage = {Final},<br>&nbsp;&nbsp;&nbsp;&nbsp;	source = {Scopus},<br>&nbsp;&nbsp;&nbsp;&nbsp;	note = {Cited by: 0; All Open Access, Green Open Access, Hybrid Gold Open Access}<br>}

:::



# Bibliometric data


The following data has been extracted from free resources such as [OpenAlex](https://openalex.org/) or [Dimensions](https://app.dimensions.ai/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1016/j.fss.2022.12.012" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1016/j.fss.2022.12.012" class="plumx-details" data-site="plum" data-hide-when-empty="true">Fuzzy relational Galois connections between fuzzy transitive digraphs</a></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Ojeda_Hern_ndez_2022></a>[[1]](#cite-Ojeda_Hern_ndez_2022) M. Ojeda-Hernández, I. P. Cabrera, P. Cordero, et al. “Fuzzy closure relations”. In: _Fuzzy Sets and Systems_ 450 (Dec. 2022), p. 118–132. ISSN: 0165-0114. DOI: [10.1016/j.fss.2022.05.016](https://doi.org/10.1016%2Fj.fss.2022.05.016). URL: [http://dx.doi.org/10.1016/j.fss.2022.05.016](http://dx.doi.org/10.1016/j.fss.2022.05.016).


