---
title: A First Order Temporal Logic for Behavior Representation
author:
- Carlos Rossi
- <a href='/people/staff/enciso/' style='color:rgb(100,0,50);'>Manuel Enciso</a>
- <a href='/people/staff/amora/' style='color:rgb(100,0,50);'>Ángel Mora</a>
date: '2004'
categories: uncategorised
slug: 2004/FiOrTeLoBeRe
details: Advances in Artificial Intelligence - {IBERAMIA} 2004, 9th Ibero-American
  Conference on AI, Puebla, Mexico, November 22-26, 2004, Proceedings , Lecture Notes
  in Computer Science vol. 3315, pages 408--418.
doi: 10.1007/978-3-540-30498-2_41
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Rossi2004a></a>[[REM04]](#cite-Rossi2004a) C. Rossi, M. Enciso, and Á. Mora. “A First Order Temporal Logic for Behavior Representation”. In: _Advances in Artificial Intelligence - IBERAMIA 2004, 9th Ibero-American Conference on AI, Puebla, Mexico, November 22-26, 2004, Proceedings_. Ed. by C. Lema\^\itre, C. A. R. Garc\'\ia and J. A. González. Vol. 3315. Lecture Notes in Computer Science. Springer, 2004, pp. 408-418. DOI: [10.1007/978-3-540-30498-2\_41](https://doi.org/10.1007%2F978-3-540-30498-2%5C_41). URL: [https://doi.org/10.1007/978-3-540-30498-2\_41](https://doi.org/10.1007/978-3-540-30498-2\_41).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Rossi2004a,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Carlos Rossi and Manuel Enciso and {\a'A}ngel Mora},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Advances in Artificial Intelligence - {IBERAMIA} 2004, 9th Ibero-American Conference on AI, Puebla, Mexico, November 22-26, 2004, Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {A First Order Temporal Logic for Behavior Representation},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2004},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Christian Lema\^\itre and Carlos A. Reyes Garc\'\ia and Jes{\a'u}s A. Gonz{\a'a}lez},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {408--418},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {3315},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/iberamia/RossiEM04.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/978-3-540-30498-2\_41},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 23 Sep 2022 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/978-3-540-30498-2\_41},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/978-3-540-30498-2_41" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/978-3-540-30498-2_41" class="plumx-details" data-site="plum" data-hide-when-empty="true">A First Order Temporal Logic for Behavior Representation</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1007/978-3-540-30498-2_41"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Besson_2012></a>[[1]](#cite-Besson_2012) J. Besson, A. Lupeikienė, and V. Medvedev. “Comparing Real and Intended System Usages: A Case for Web Portal”. In: _Informatica_ 23.2 (Jan. 2012), p. 191–201. ISSN: 1822-8844. DOI: [10.15388/informatica.2012.356](https://doi.org/10.15388%2Finformatica.2012.356). URL: [http://dx.doi.org/10.15388/informatica.2012.356](http://dx.doi.org/10.15388/informatica.2012.356).

