---
author: Enrique Mérida Casermeiro, Domingo López-Rodríguez, Juan Miguel Ortiz-de-Lazcano-Lobato
Status: Published
date: '2006-04-01'
slug: 2006-esann
title: Enhanced maxcut clustering with multivalued neural networks and functional
  annealing
categories:
- Combinatorial optimization
- Neural networks
header_image: ~
details: ESANN 2006 Proceedings - 14th European Symposium on Artificial Neural Networks,
  <em>pp. 25&ndash;30</em>
doi: ''
link: 2006-esann/paper.pdf
project: ''
keywords: Combinatorial optimization, Optimization, Combinatorial optimization problems,
  Its efficiencies, Local optima, MAX-CUT problem, Multi-valued, NP Complete, Optimization
  method, Recurrent models, Recurrent neural networks
---



# Abstract


In this work a new algorithm to improve the performance of optimization methods, by means of avoiding certain local optima, is described. Its theoretical bases are presented in a rigorous, but intuitive, way. It has been applied concretely to the case of recurrent neural networks, in particular to MREM, a multivalued recurrent model, that has proved to obtain very good results when dealing with NP-complete combinatorial optimization problems. In order to show its efficiency, the well-known MaxCut problem for graphs has been selected as benchmark. Our proposal outperforms other specialized and powerful techniques, as shown by simulations.







# Citation
Please, cite this work as:


<a name=bib-Casermeiro2006></a>[[CLO06]](#cite-Casermeiro2006) E. M. Casermeiro, D. López-Rodríguez, and J. M. Ortiz-de-Lazcano-Lobato. “Enhanced maxcut clustering with multivalued neural networks and functional annealing”. In: _ESANN 2006, 14th European Symposium on Artificial Neural Networks, Bruges, Belgium, April 26-28, 2006, Proceedings_. d-side publication, 2006, pp. 25-30. URL: [https://www.elen.ucl.ac.be/Proceedings/esann/esannpdf/es2006-86.pdf](https://www.elen.ucl.ac.be/Proceedings/esann/esannpdf/es2006-86.pdf).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Casermeiro2006,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Enrique Mérida Casermeiro and Domingo López-Rodríguez and Juan Miguel Ortiz-de-Lazcano-Lobato},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {{ESANN} 2006, 14th European Symposium on Artificial Neural Networks, Bruges, Belgium, April 26-28, 2006, Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Enhanced maxcut clustering with multivalued neural networks and functional annealing},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2006},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {25--30},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {d-side publication},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {In this work a new algorithm to improve the performance of optimization methods, by means of avoiding certain local optima, is described. Its theoretical bases are presented in a rigorous, but intuitive, way. It has been applied concretely to the case of recurrent neural networks, in particular to MREM, a multivalued recurrent model, that has proved to obtain very good results when dealing with NP-complete combinatorial optimization problems. In order to show its efficiency, the well-known MaxCut problem for graphs has been selected as benchmark. Our proposal outperforms other specialized and powerful techniques, as shown by simulations. © 2006 i6doc.com publication. All rights reserved.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/esann/CasermeiroLO06.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  document_type = {Conference Paper},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {ESANN 2006 Proceedings - European Symposium on Artificial Neural Networks},<br>&nbsp;&nbsp;&nbsp;&nbsp;  keywords = {Combinatorial optimization; Optimization, Combinatorial optimization problems; Its efficiencies; Local optima; MAX-CUT problem; Multi-valued; NP Complete; Optimization method; Recurrent models, Recurrent neural networks},<br>&nbsp;&nbsp;&nbsp;&nbsp;  source = {Scopus},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Thu, 12 Mar 2020 11:36:02 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://www.elen.ucl.ac.be/Proceedings/esann/esannpdf/es2006-86.pdf},<br>}

:::


