---
author:
- J. Pérez
- A. Rodríguez
- J.F. Chico
- Domingo López-Rodríguez
- M. Ujaldón
Status: Published
date: '2018-12-01'
slug: 2018-gpu
title: 'Energy-aware acceleration on GPUs: Findings on a bioinformatics benchmark'
categories: Neuroimage
header_image: ~
details: '<em>Sustainable Computing: Informatics and Systems</em> vol. 20, pp. 88
  -- 101'
doi: 10.1016/j.suscom.2018.01.001
link: 2018-gpu/paper.pdf
project: ~
keywords: ''
---


# Abstract


This paper performs a complete study on performance and energy efficiency of biomedical codes when accelerated on GPUs (Graphics Processing Units). We have selected a benchmark composed of three different building blocks which constitute the pillars of four popular biomedical applications: Q-norm, for the quantile normalization of gene expressions, reg f3d, for the registration of 3D images within the NiftyReg library, bedpostx (from the FSL neuroimaging package) and a multi-tensor tractography for the analysis of diffusion images. We try to identify (1) potential scenarios where performance per watt can be optimal in large-scale biomedical applications, and (2) the ideal GPU platform among a wide range of models, including low power Tegras, popular GeForces and high-end Titans. Experimental results conclude that data locality and arithmetic intensity represent the most rewarding ways on the road to high performance bioinformatics when power is a major concern.





# Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```


# Citation
Please, cite this work as:


<a name=bib-perez2018energy></a>[[Pér+18]](#cite-perez2018energy) J. Pérez, A. Rodríguez, J. F. Chico, et al. “Energy-aware acceleration on GPUs: findings on a bioinformatics benchmark”. In: _Sustainable Computing: Informatics and Systems_ 20 (2018), pp. 88-101. DOI: [10.1016/j.suscom.2018.01.001](https://doi.org/10.1016%2Fj.suscom.2018.01.001).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@article{perez2018energy,<br>&nbsp;&nbsp;&nbsp;&nbsp;  title={Energy-aware acceleration on GPUs: findings on a bioinformatics benchmark},<br>&nbsp;&nbsp;&nbsp;&nbsp;  author={Pérez, Jesús and Rodríguez, Andrés and Chico, Juan Francisco and López-Rodríguez, Domingo and Ujaldón, Manuel},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal={Sustainable Computing: Informatics and Systems},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume={20},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages={88--101},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year={2018},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher={Elsevier},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi={10.1016/j.suscom.2018.01.001}<br>}

:::


