---
title: On the Dedekind-MacNeille completion and formal concept analysis based on multilattices
author:
- Jesús Medina-Moreno
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
- Jozef Pócs
- Eloísa Ramírez-Poussa
date: '2016'
categories: uncategorised
slug: 2016/CoFoCoAnBaMu
details: Fuzzy Sets Syst. vol. 303 , pages 1--20.
doi: 10.1016/J.FSS.2016.01.007
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-MedinaMoreno2016></a>[[Med+16]](#cite-MedinaMoreno2016) J. Medina-Moreno, M. Ojeda-Aciego, J. Pócs, et al. “On the Dedekind-MacNeille completion and formal concept analysis based on multilattices”. In: _Fuzzy Sets Syst._ 303 (2016), pp. 1-20. DOI: [10.1016/J.FSS.2016.01.007](https://doi.org/10.1016%2FJ.FSS.2016.01.007). URL: [https://doi.org/10.1016/j.fss.2016.01.007](https://doi.org/10.1016/j.fss.2016.01.007).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{MedinaMoreno2016,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Jes{\a'u}s Medina-Moreno and Manuel Ojeda-Aciego and Jozef P{\a'o}cs and Elo\'\isa Ram\'\irez-Poussa},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Fuzzy Sets Syst.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {On the Dedekind-MacNeille completion and formal concept analysis based on multilattices},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2016},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {1--20},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {303},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/fss/Medina-MorenoOP16.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1016/J.FSS.2016.01.007},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Mon, 15 Jun 2020 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1016/j.fss.2016.01.007},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1016/J.FSS.2016.01.007" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1016/J.FSS.2016.01.007" class="plumx-details" data-site="plum" data-hide-when-empty="true">On the Dedekind-MacNeille completion and formal concept analysis based on multilattices</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1016/J.FSS.2016.01.007"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Antoni_2024></a>[[1]](#cite-Antoni_2024) Ľ. Antoni, P. Eliaš, J. Guniš, et al. “Bimorphisms and attribute implications in heterogeneous formal contexts”. In: _International Journal of Approximate Reasoning_ 172 (Sep. 2024), p. 109245. ISSN: 0888-613X. DOI: [10.1016/j.ijar.2024.109245](https://doi.org/10.1016%2Fj.ijar.2024.109245). URL: [http://dx.doi.org/10.1016/j.ijar.2024.109245](http://dx.doi.org/10.1016/j.ijar.2024.109245).

<a name=bib-Antoni_2023></a>[[2]](#cite-Antoni_2023) L. Antoni, P. Eliaš, T. Horváth, et al. “Squared Symmetric Formal Contexts and Their Connections with Correlation Matrices”. In: _Graph-Based Representation and Reasoning_. Springer Nature Switzerland, 2023, p. 19–27. ISBN: 9783031409608. DOI: [10.1007/978-3-031-40960-8_2](https://doi.org/10.1007%2F978-3-031-40960-8_2). URL: [http://dx.doi.org/10.1007/978-3-031-40960-8_2](http://dx.doi.org/10.1007/978-3-031-40960-8_2).

<a name=bib-Antoni_2022></a>[[3]](#cite-Antoni_2022) Ľ. Antoni, P. Eliaš, S. Krajči, et al. “Heterogeneous formal context and its decomposition by heterogeneous fuzzy subsets”. In: _Fuzzy Sets and Systems_ 451 (Dec. 2022), p. 361–384. ISSN: 0165-0114. DOI: [10.1016/j.fss.2022.05.015](https://doi.org/10.1016%2Fj.fss.2022.05.015). URL: [http://dx.doi.org/10.1016/j.fss.2022.05.015](http://dx.doi.org/10.1016/j.fss.2022.05.015).

<a name=bib-Antoni_2018></a>[[4]](#cite-Antoni_2018) L. Antoni, S. Krajči, and O. Krídlo. “On Fuzzy Generalizations of Concept Lattices”. In: _Interactions Between Computational Intelligence and Mathematics_. Springer International Publishing, 2018, p. 79–103. ISBN: 9783319746814. DOI: [10.1007/978-3-319-74681-4_6](https://doi.org/10.1007%2F978-3-319-74681-4_6). URL: [http://dx.doi.org/10.1007/978-3-319-74681-4_6](http://dx.doi.org/10.1007/978-3-319-74681-4_6).

<a name=bib-Antoni_20181></a>[[5]](#cite-Antoni_20181) L. Antoni, S. Krajči, and O. Krídlo. “On stability of fuzzy formal concepts over randomized one-sided formal context”. In: _Fuzzy Sets and Systems_ 333 (Feb. 2018), p. 36–53. ISSN: 0165-0114. DOI: [10.1016/j.fss.2017.04.006](https://doi.org/10.1016%2Fj.fss.2017.04.006). URL: [http://dx.doi.org/10.1016/j.fss.2017.04.006](http://dx.doi.org/10.1016/j.fss.2017.04.006).

<a name=bib-Antoni_2017></a>[[6]](#cite-Antoni_2017) L. Antoni, S. Krajči, and O. Krídlo. “Representation of fuzzy subsets by Galois connections”. In: _Fuzzy Sets and Systems_ 326 (Nov. 2017), p. 52–68. ISSN: 0165-0114. DOI: [10.1016/j.fss.2017.05.020](https://doi.org/10.1016%2Fj.fss.2017.05.020). URL: [http://dx.doi.org/10.1016/j.fss.2017.05.020](http://dx.doi.org/10.1016/j.fss.2017.05.020).

<a name=bib-Chen_2021></a>[[7]](#cite-Chen_2021) J. M. Chen, M. U. Rehman, and X. V. Vo. “Clustering commodity markets in space and time: Clarifying returns, volatility, and trading regimes through unsupervised machine learning”. In: _Resources Policy_ 73 (Oct. 2021), p. 102162. ISSN: 0301-4207. DOI: [10.1016/j.resourpol.2021.102162](https://doi.org/10.1016%2Fj.resourpol.2021.102162). URL: [http://dx.doi.org/10.1016/j.resourpol.2021.102162](http://dx.doi.org/10.1016/j.resourpol.2021.102162).

<a name=bib-Cornejo_2022></a>[[8]](#cite-Cornejo_2022) M. E. Cornejo, J. C. Díaz-Moreno, and J. Medina. “Generalized quantifiers in formal concept analysis”. In: _Journal of Computational and Applied Mathematics_ 404 (Apr. 2022), p. 113772. ISSN: 0377-0427. DOI: [10.1016/j.cam.2021.113772](https://doi.org/10.1016%2Fj.cam.2021.113772). URL: [http://dx.doi.org/10.1016/j.cam.2021.113772](http://dx.doi.org/10.1016/j.cam.2021.113772).

<a name=bib-Cornejo_2021></a>[[9]](#cite-Cornejo_2021) M. E. Cornejo, L. Fariñas del Cerro, and J. Medina. “A logical characterization of multi-adjoint algebras”. In: _Fuzzy Sets and Systems_ 425 (Nov. 2021), p. 140–156. ISSN: 0165-0114. DOI: [10.1016/j.fss.2021.02.003](https://doi.org/10.1016%2Fj.fss.2021.02.003). URL: [http://dx.doi.org/10.1016/j.fss.2021.02.003](http://dx.doi.org/10.1016/j.fss.2021.02.003).

<a name=bib-Cornejo_2020></a>[[10]](#cite-Cornejo_2020) M. E. Cornejo, D. Lobo, and J. Medina. “Solving Generalized Equations with Bounded Variables and Multiple Residuated Operators”. In: _Mathematics_ 8.11 (Nov. 2020), p. 1992. ISSN: 2227-7390. DOI: [10.3390/math8111992](https://doi.org/10.3390%2Fmath8111992). URL: [http://dx.doi.org/10.3390/math8111992](http://dx.doi.org/10.3390/math8111992).

<a name=bib-Cornejo_2023></a>[[11]](#cite-Cornejo_2023) M. E. Cornejo, J. Medina, E. Ramírez-Poussa, et al. “Preferences in discrete multi-adjoint formal concept analysis”. In: _Information Sciences_ 650 (Dec. 2023), p. 119507. ISSN: 0020-0255. DOI: [10.1016/j.ins.2023.119507](https://doi.org/10.1016%2Fj.ins.2023.119507). URL: [http://dx.doi.org/10.1016/j.ins.2023.119507](http://dx.doi.org/10.1016/j.ins.2023.119507).

<a name=bib-Elia__2024></a>[[12]](#cite-Elia__2024) P. Eliaš, L. Antoni, O. Krídlo, et al. “Additional Notes on Heterogeneous Concept-Forming Operators”. In: _Computational Intelligence and Mathematics for Tackling Complex Problems 5_. Springer Nature Switzerland, 2024, p. 1–7. ISBN: 9783031469794. DOI: [10.1007/978-3-031-46979-4_1](https://doi.org/10.1007%2F978-3-031-46979-4_1). URL: [http://dx.doi.org/10.1007/978-3-031-46979-4_1](http://dx.doi.org/10.1007/978-3-031-46979-4_1).

<a name=bib-Koguep_Njionou_2023></a>[[13]](#cite-Koguep_Njionou_2023) B. B. Koguep Njionou, L. Kwuida, and C. Lele. “Formal Concepts and Residuation on Multilattices”. In: _Fundamenta Informaticae_ 188.4 (Jun. 2023), p. 217–237. ISSN: 1875-8681. DOI: [10.3233/fi-222147](https://doi.org/10.3233%2Ffi-222147). URL: [http://dx.doi.org/10.3233/fi-222147](http://dx.doi.org/10.3233/fi-222147).

<a name=bib-Lai_2021></a>[[14]](#cite-Lai_2021) H. Lai and L. Shen. “Multi-adjoint concept lattices via quantaloid-enriched categories”. In: _Fuzzy Sets and Systems_ 405 (Feb. 2021), p. 74–87. ISSN: 0165-0114. DOI: [10.1016/j.fss.2020.03.007](https://doi.org/10.1016%2Fj.fss.2020.03.007). URL: [http://dx.doi.org/10.1016/j.fss.2020.03.007](http://dx.doi.org/10.1016/j.fss.2020.03.007).

<a name=bib-Xu_2019></a>[[15]](#cite-Xu_2019) Y. Xu, L. Liu, and X. Zhang. “Multilattices on typical hesitant fuzzy sets”. In: _Information Sciences_ 491 (Jul. 2019), p. 63–73. ISSN: 0020-0255. DOI: [10.1016/j.ins.2019.03.078](https://doi.org/10.1016%2Fj.ins.2019.03.078). URL: [http://dx.doi.org/10.1016/j.ins.2019.03.078](http://dx.doi.org/10.1016/j.ins.2019.03.078).

