---
title: Relational dual tableau decision procedure for modal logic {K}
author:
- Joanna Golinska-Pilarek
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
- Angel Mora-Bonilla
date: '2012'
categories: uncategorised
slug: 2012/ReDuTaDePrMoLo
details: Log. J. {IGPL} vol. 20 (4), pages 747--756.
doi: 10.1093/JIGPAL/JZR019
---



# Abstract


Journal Article Relational dual tableau decision procedure for modal logic K Get access Joanna Golińska-Pilarek, Joanna Golińska-Pilarek Institute of Philosophy, University of Warsaw and National Institute of Telecommunications, Poland.E-mail: j.golinska@uw.edu.pl Search for other works by this author on: Oxford Academic Google Scholar Emilio Muñoz-Velasco, Emilio Muñoz-Velasco Department of Applied Mathematics, University of Málaga, Málaga, Spain.E-mail: emilio@ctima.uma.es; amora@ctima.uma.es Search for other works by this author on: Oxford Academic Google Scholar Angel Mora-Bonilla Angel Mora-Bonilla Department of Applied Mathematics, University of Málaga, Málaga, Spain.E-mail: emilio@ctima.uma.es; amora@ctima.uma.es Search for other works by this author on: Oxford Academic Google Scholar Logic Journal of the IGPL, Volume 20, Issue 4, August 2012, Pages 747–756, https://doi.org/10.1093/jigpal/jzr019 Published: 10 February 2011 Article history Received: 02 January 2011 Published: 10 February 2011








# Citation
Please, cite this work as:


<a name=bib-GolinskaPilarek2012></a>[[GMM12]](#cite-GolinskaPilarek2012) J. Golinska-Pilarek, E. Mu~noz-Velasco, and A. Mora-Bonilla. “Relational dual tableau decision procedure for modal logic K”. In: _Log. J. IGPL_ 20.4 (2012), pp. 747-756. DOI: [10.1093/JIGPAL/JZR019](https://doi.org/10.1093%2FJIGPAL%2FJZR019). URL: [https://doi.org/10.1093/jigpal/jzr019](https://doi.org/10.1093/jigpal/jzr019).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{GolinskaPilarek2012,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Joanna Golinska-Pilarek and Emilio Mu~noz-Velasco and Angel Mora-Bonilla},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Log. J. {IGPL}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Relational dual tableau decision procedure for modal logic {K}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2012},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number = {4},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {747--756},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {20},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/igpl/Golinska-PilarekMB12.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1093/JIGPAL/JZR019},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 23 Sep 2022 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1093/jigpal/jzr019},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1093/JIGPAL/JZR019" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1093/JIGPAL/JZR019" class="plumx-details" data-site="plum" data-hide-when-empty="true">Relational dual tableau decision procedure for modal logic {K}</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1093/JIGPAL/JZR019"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Burrieza_2018></a>[[1]](#cite-Burrieza_2018) A. Burrieza, E. Muñoz-Velasco, and M. Ojeda-Aciego. “Logics for Order-of-Magnitude Qualitative Reasoning: Formalizing Negligibility”. In: _Ewa Orłowska on Relational Methods in Logic and Computer Science_. Springer International Publishing, 2018, p. 203–231. ISBN: 9783319978796. DOI: [10.1007/978-3-319-97879-6_8](https://doi.org/10.1007%2F978-3-319-97879-6_8). URL: [http://dx.doi.org/10.1007/978-3-319-97879-6_8](http://dx.doi.org/10.1007/978-3-319-97879-6_8).

<a name=bib-Cantone_2018></a>[[2]](#cite-Cantone_2018) D. Cantone and M. Nicolosi-Asmundo. “Dual Tableau-Based Decision Procedures for Fragments of the Logic of Binary Relations”. In: _Ewa Orłowska on Relational Methods in Logic and Computer Science_. Springer International Publishing, 2018, p. 169–202. ISBN: 9783319978796. DOI: [10.1007/978-3-319-97879-6_7](https://doi.org/10.1007%2F978-3-319-97879-6_7). URL: [http://dx.doi.org/10.1007/978-3-319-97879-6_7](http://dx.doi.org/10.1007/978-3-319-97879-6_7).

<a name=bib-Corchado_2011></a>[[3]](#cite-Corchado_2011) E. Corchado and P. Novais. “Special issue: SOCO 2010-CMMSE 2010”. In: _Logic Journal of IGPL_ 20.4 (Apr. 2011), p. 645–647. ISSN: 1368-9894. DOI: [10.1093/jigpal/jzr012](https://doi.org/10.1093%2Fjigpal%2Fjzr012). URL: [http://dx.doi.org/10.1093/jigpal/jzr012](http://dx.doi.org/10.1093/jigpal/jzr012).

<a name=bib-Doherty_2018></a>[[4]](#cite-Doherty_2018) P. Doherty and A. Szałas. “Signed Dual Tableaux for Kleene Answer Set Programs”. In: _Ewa Orłowska on Relational Methods in Logic and Computer Science_. Springer International Publishing, 2018, p. 233–252. ISBN: 9783319978796. DOI: [10.1007/978-3-319-97879-6_9](https://doi.org/10.1007%2F978-3-319-97879-6_9). URL: [http://dx.doi.org/10.1007/978-3-319-97879-6_9](http://dx.doi.org/10.1007/978-3-319-97879-6_9).

<a name=bib-Goli_ska_Pilarek_2014></a>[[5]](#cite-Goli_ska_Pilarek_2014) J. Golińska-Pilarek, T. Huuskonen, and E. Muñoz-Velasco. “Relational dual tableau decision procedures and their applications to modal and intuitionistic logics”. In: _Annals of Pure and Applied Logic_ 165.2 (Feb. 2014), p. 409–427. ISSN: 0168-0072. DOI: [10.1016/j.apal.2013.06.003](https://doi.org/10.1016%2Fj.apal.2013.06.003). URL: [http://dx.doi.org/10.1016/j.apal.2013.06.003](http://dx.doi.org/10.1016/j.apal.2013.06.003).

<a name=bib-Goli_ska_Pilarek_20141></a>[[6]](#cite-Goli_ska_Pilarek_20141) J. Golińska-Pilarek, E. Muñoz-Velasco, and A. Mora. “Deterministic Tableau-Decision Procedure via Reductions for Modal Logic K”. In: _International Joint Conference SOCO’13-CISIS’13-ICEUTE’13_. Springer International Publishing, 2014, p. 429–438. ISBN: 9783319018546. DOI: [10.1007/978-3-319-01854-6_44](https://doi.org/10.1007%2F978-3-319-01854-6_44). URL: [http://dx.doi.org/10.1007/978-3-319-01854-6_44](http://dx.doi.org/10.1007/978-3-319-01854-6_44).

