---
title: Implementing a relational theorem prover for modal logic
author:
- <a href='/people/staff/amora/' style='color:rgb(100,0,50);'>Ángel Mora</a>
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
- Joanna Golinska-Pilarek
date: '2011'
categories: uncategorised
slug: 2011/ImReThPrMoLo
details: Int. J. Comput. Math. vol. 88 (9), pages 1869--1884.
doi: 10.1080/00207160.2010.493211
---



# Abstract


An automatic theorem prover for a proof system in the style of dual tableaux for the relational logic associated with modal logic has been introduced. Although there are many well-known implementations of provers for modal logic, as far as we know, it is the first implementation of a specific relational prover for a standard modal logic. There are two main contributions in this paper. First, the implementation of new rules, called () and (), which substitute the classical relational rules for composition and negation of composition in order to guarantee not only that every proof tree is finite but also to decrease the number of applied rules in dual tableaux. Second, the implementation of an order of application of the rules which ensures that the proof tree obtained is unique. As a consequence, we have implemented a decision procedure for modal logic . Moreover, this work would be the basis for successive extensions of this logic, such as , and .








# Citation
Please, cite this work as:


<a name=bib-Mora2011a></a>[[MMG11]](#cite-Mora2011a) Á. Mora, E. Mu~noz-Velasco, and J. Golinska-Pilarek. “Implementing a relational theorem prover for modal logic”. In: _Int. J. Comput. Math._ 88.9 (2011), pp. 1869-1884. DOI: [10.1080/00207160.2010.493211](https://doi.org/10.1080%2F00207160.2010.493211). URL: [https://doi.org/10.1080/00207160.2010.493211](https://doi.org/10.1080/00207160.2010.493211).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{Mora2011a,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {{\a'A}ngel Mora and Emilio Mu~noz-Velasco and Joanna Golinska-Pilarek},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Int. J. Comput. Math.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Implementing a relational theorem prover for modal logic},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2011},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number = {9},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {1869--1884},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {88},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/ijcm/MoraMG11.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1080/00207160.2010.493211},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 23 Sep 2022 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1080/00207160.2010.493211},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1080/00207160.2010.493211" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1080/00207160.2010.493211" class="plumx-details" data-site="plum" data-hide-when-empty="true">Implementing a relational theorem prover for modal logic</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1080/00207160.2010.493211"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Burrieza_2018></a>[[1]](#cite-Burrieza_2018) A. Burrieza, E. Muñoz-Velasco, and M. Ojeda-Aciego. “Logics for Order-of-Magnitude Qualitative Reasoning: Formalizing Negligibility”. In: _Ewa Orłowska on Relational Methods in Logic and Computer Science_. Springer International Publishing, 2018, p. 203–231. ISBN: 9783319978796. DOI: [10.1007/978-3-319-97879-6_8](https://doi.org/10.1007%2F978-3-319-97879-6_8). URL: [http://dx.doi.org/10.1007/978-3-319-97879-6_8](http://dx.doi.org/10.1007/978-3-319-97879-6_8).

<a name=bib-Cantone_2014></a>[[2]](#cite-Cantone_2014) D. Cantone, J. Golińska-Pilarek, and M. Nicolosi-Asmundo. “A Relational Dual Tableau Decision Procedure for Multimodal and Description Logics”. In: _Hybrid Artificial Intelligence Systems_. Springer International Publishing, 2014, p. 466–477. ISBN: 9783319076171. DOI: [10.1007/978-3-319-07617-1_41](https://doi.org/10.1007%2F978-3-319-07617-1_41). URL: [http://dx.doi.org/10.1007/978-3-319-07617-1_41](http://dx.doi.org/10.1007/978-3-319-07617-1_41).

<a name=bib-Cantone_2018></a>[[3]](#cite-Cantone_2018) D. Cantone and M. Nicolosi-Asmundo. “Dual Tableau-Based Decision Procedures for Fragments of the Logic of Binary Relations”. In: _Ewa Orłowska on Relational Methods in Logic and Computer Science_. Springer International Publishing, 2018, p. 169–202. ISBN: 9783319978796. DOI: [10.1007/978-3-319-97879-6_7](https://doi.org/10.1007%2F978-3-319-97879-6_7). URL: [http://dx.doi.org/10.1007/978-3-319-97879-6_7](http://dx.doi.org/10.1007/978-3-319-97879-6_7).

<a name=bib-httpsdoiorg1048550arxiv180207508></a>[[4]](#cite-httpsdoiorg1048550arxiv180207508) D. Cantone, M. Nicolosi-Asmundo, and E. Orłowska. _A Dual Tableau-based Decision Procedure for a Relational Logic with the Universal Relation (Extended Version)_. 2018. DOI: [10.48550/ARXIV.1802.07508](https://doi.org/10.48550%2FARXIV.1802.07508). URL: [https://arxiv.org/abs/1802.07508](https://arxiv.org/abs/1802.07508).

<a name=bib-Da_Silveira_2022></a>[[5]](#cite-Da_Silveira_2022) A. A. Da Silveira, R. Ribeiro, M. A. Nunes, et al. “A Sound Deep Embedding of Arbitrary Normal Modal Logics in Coq”. In: _Proceedings of the XXVI Brazilian Symposium on Programming Languages_. SBLP 2022. ACM, Oct. 2022, p. 1–7. DOI: [10.1145/3561320.3561329](https://doi.org/10.1145%2F3561320.3561329). URL: [http://dx.doi.org/10.1145/3561320.3561329](http://dx.doi.org/10.1145/3561320.3561329).

<a name=bib-Goli_ska_Pilarek_2014></a>[[6]](#cite-Goli_ska_Pilarek_2014) J. Golińska-Pilarek, T. Huuskonen, and E. Muñoz-Velasco. “Relational dual tableau decision procedures and their applications to modal and intuitionistic logics”. In: _Annals of Pure and Applied Logic_ 165.2 (Feb. 2014), p. 409–427. ISSN: 0168-0072. DOI: [10.1016/j.apal.2013.06.003](https://doi.org/10.1016%2Fj.apal.2013.06.003). URL: [http://dx.doi.org/10.1016/j.apal.2013.06.003](http://dx.doi.org/10.1016/j.apal.2013.06.003).

<a name=bib-Golinska_Pilarek_2011></a>[[7]](#cite-Golinska_Pilarek_2011) J. Golinska-Pilarek, E. Munoz-Velasco, and A. Mora-Bonilla. “Relational dual tableau decision procedure for modal logic K”. In: _Logic Journal of IGPL_ 20.4 (Feb. 2011), p. 747–756. ISSN: 1368-9894. DOI: [10.1093/jigpal/jzr019](https://doi.org/10.1093%2Fjigpal%2Fjzr019). URL: [http://dx.doi.org/10.1093/jigpal/jzr019](http://dx.doi.org/10.1093/jigpal/jzr019).

<a name=bib-Madrid_2012></a>[[8]](#cite-Madrid_2012) N. Madrid and M. Ojeda-Aciego. “On the existence and unicity of stable models in normal residuated logic programs”. In: _International Journal of Computer Mathematics_ 89.3 (Feb. 2012), p. 310–324. ISSN: 1029-0265. DOI: [10.1080/00207160.2011.580842](https://doi.org/10.1080%2F00207160.2011.580842). URL: [http://dx.doi.org/10.1080/00207160.2011.580842](http://dx.doi.org/10.1080/00207160.2011.580842).

<a name=bib-Vigo_Aguiar_2011></a>[[9]](#cite-Vigo_Aguiar_2011) J. Vigo-Aguiar and J. A. Lopez-Ramos. “Applications of computational mathematics in science and engineering”. In: _International Journal of Computer Mathematics_ 88.9 (Jun. 2011), p. 1805–1807. ISSN: 1029-0265. DOI: [10.1080/00207160.2011.578828](https://doi.org/10.1080%2F00207160.2011.578828). URL: [http://dx.doi.org/10.1080/00207160.2011.578828](http://dx.doi.org/10.1080/00207160.2011.578828).

