---
title: 'Conference paper accepted: <em>Theoretical Study on the Capacity of Associative
  Memory with Multiple Reference Points</em>'
author: Enrique Mérida Casermeiro, Domingo López-Rodríguez, Gloria Galán Marín, Juan
  Miguel Ortiz-de-Lazcano-Lobato
date: '2007-01-01'
categories:
- Pattern recognition
- Neural networks
---

The work <u>Theoretical Study on the Capacity of Associative Memory with Multiple Reference Points</u> has been published in <em>Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics), (4527), PART 1, <em>pp. 292&ndash;302</em></em>.

<u>Abstract</u>:



An extension to Hopfield's model of associative memory is studied in the present work. In particular, this paper is focused in giving solutions to the two main problems present in the model: the apparition of spurious patterns in the learning phase (implying the well-known and undesirable effect of storing the opposite pattern) and the problem of its reduced capacity (the probability of error in the retrieving phase increases as the number of stored patterns grows). In this work, a method to avoid spurious patterns is presented and studied, and an explanation to the previously mentioned effect is given. Another novel technique to increase the capacity of a network is proposed here, based on the idea of using several reference points when storing patterns. It is studied in depth, and an explicit formula for the capacity of the network is provided. This formula shows the linear dependence of the capacity of the new model on the number of reference points, implying the increase of the capacity in mis model. © Springer-Verlag Berlin Heidelberg 2007.




For more details on this work, visit <a href='/publications/conferences/2007-iwinac'>its own page</a>.
