---
title: Improving Recommender Systems with Simplification Logic to Manage Implications
  with Grades
author:
- José Luis Leiva
- <a href='/people/staff/enciso/' style='color:rgb(100,0,50);'>Manuel Enciso</a>
- Carlos Rossi
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/amora/' style='color:rgb(100,0,50);'>Ángel Mora</a>
- Antonio Guevara
date: '2013'
categories: uncategorised
slug: 2013/ImReSySiLoMaImGr
details: Software Technologies - 8th International Joint Conference, {ICSOFT} 2013,
  Reykjavik, Iceland, July 29-31, 2013, Revised Selected Papers , Communications in
  Computer and Information Science vol. 457, pages 290--305.
doi: 10.1007/978-3-662-44920-2_18
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Leiva2013></a>[[Lei+13]](#cite-Leiva2013) J. L. Leiva, M. Enciso, C. Rossi, et al. “Improving Recommender Systems with Simplification Logic to Manage Implications with Grades”. In: _Software Technologies - 8th International Joint Conference, ICSOFT 2013, Reykjavik, Iceland, July 29-31, 2013, Revised Selected Papers_. Ed. by J. Cordeiro and M. van Sinderen. Vol. 457. Communications in Computer and Information Science. Springer, 2013, pp. 290-305. DOI: [10.1007/978-3-662-44920-2\_18](https://doi.org/10.1007%2F978-3-662-44920-2%5C_18). URL: [https://doi.org/10.1007/978-3-662-44920-2\_18](https://doi.org/10.1007/978-3-662-44920-2\_18).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Leiva2013,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Jos{\a'e} Luis Leiva and Manuel Enciso and Carlos Rossi and Pablo Cordero and {\a'A}ngel Mora and Antonio Guevara},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Software Technologies - 8th International Joint Conference, {ICSOFT} 2013, Reykjavik, Iceland, July 29-31, 2013, Revised Selected Papers},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Improving Recommender Systems with Simplification Logic to Manage Implications with Grades},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2013},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Jos{\a'e} Cordeiro and Marten {van Sinderen}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {290--305},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Communications in Computer and Information Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {457},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/icsoft/LeivaERCMG13a.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/978-3-662-44920-2\_18},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 23 Sep 2022 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/978-3-662-44920-2\_18},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/978-3-662-44920-2_18" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/978-3-662-44920-2_18" class="plumx-details" data-site="plum" data-hide-when-empty="true">Improving Recommender Systems with Simplification Logic to Manage Implications with Grades</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1007/978-3-662-44920-2_18"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Cordero_2015></a>[[1]](#cite-Cordero_2015) P. Cordero, M. Enciso, A. Mora, et al. “Knowledge discovery in social networks by using a logic-based treatment of implications”. In: _Knowledge-Based Systems_ 87 (Oct. 2015), p. 16–25. ISSN: 0950-7051. DOI: [10.1016/j.knosys.2015.07.018](https://doi.org/10.1016%2Fj.knosys.2015.07.018). URL: [http://dx.doi.org/10.1016/j.knosys.2015.07.018](http://dx.doi.org/10.1016/j.knosys.2015.07.018).

