---
title: Deterministic Tableau-Decision Procedure via Reductions for Modal Logic {K}
author:
- Joanna Golinska-Pilarek
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
- <a href='/people/staff/amora/' style='color:rgb(100,0,50);'>Ángel Mora</a>
date: '2013'
categories: uncategorised
slug: 2013/DePrViReMoLo
details: International Joint Conference SOCO'13-CISIS'13-ICEUTE'13 - Salamanca, Spain,
  September 11th-13th, 2013 Proceedings , Advances in Intelligent Systems and Computing
  vol. 239, pages 429--438.
doi: 10.1007/978-3-319-01854-6_44
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-GolinskaPilarek2013></a>[[GMM13]](#cite-GolinskaPilarek2013) J. Golinska-Pilarek, E. Mu~noz-Velasco, and Á. Mora. “Deterministic Tableau-Decision Procedure via Reductions for Modal Logic K”. In: _International Joint Conference SOCO'13-CISIS'13-ICEUTE'13 - Salamanca, Spain, September 11th-13th, 2013 Proceedings_. Ed. by Á. Herrero, B. Baruque, F. Klett, A. Abraham, V. Snásel, A. C. P. de Leon Ferreira, P. Garc\'\iaBringas, I. Zelinka, H. Quintián and E. Corchado. Vol. 239. Advances in Intelligent Systems and Computing. Springer, 2013, pp. 429-438. DOI: [10.1007/978-3-319-01854-6\_44](https://doi.org/10.1007%2F978-3-319-01854-6%5C_44). URL: [https://doi.org/10.1007/978-3-319-01854-6\_44](https://doi.org/10.1007/978-3-319-01854-6\_44).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{GolinskaPilarek2013,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Joanna Golinska-Pilarek and Emilio Mu~noz-Velasco and {\a'A}ngel Mora},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {International Joint Conference SOCO'13-CISIS'13-ICEUTE'13 - Salamanca, Spain, September 11th-13th, 2013 Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Deterministic Tableau-Decision Procedure via Reductions for Modal Logic {K}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2013},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {{\a'A}lvaro Herrero and Bruno Baruque and Fanny Klett and Ajith Abraham and V{\a'a}clav Sn{\a'a}sel and Andr{\a'e} Carlos Ponce {de Leon Ferreira} and Pablo Garc\'\ia Bringas and Ivan Zelinka and H{\a'e}ctor Quinti{\a'a}n and Emilio Corchado},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {429--438},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Advances in Intelligent Systems and Computing},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {239},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/softcomp/Golinska-PilarekMM13.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/978-3-319-01854-6\_44},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 23 Sep 2022 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/978-3-319-01854-6\_44},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/978-3-319-01854-6_44" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/978-3-319-01854-6_44" class="plumx-details" data-site="plum" data-hide-when-empty="true">Deterministic Tableau-Decision Procedure via Reductions for Modal Logic {K}</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1007/978-3-319-01854-6_44"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Goli_ska_Pilarek_2016></a>[[1]](#cite-Goli_ska_Pilarek_2016) J. Golińska-Pilarek, E. Muñoz-Velasco, and A. Mora. “Tableau reductions: Towards an optimal decision procedure for the modal necessity”. In: _Journal of Applied Logic_ 17 (Sep. 2016), p. 14–24. ISSN: 1570-8683. DOI: [10.1016/j.jal.2015.09.005](https://doi.org/10.1016%2Fj.jal.2015.09.005). URL: [http://dx.doi.org/10.1016/j.jal.2015.09.005](http://dx.doi.org/10.1016/j.jal.2015.09.005).

