---
title: Multi-adjoint t-concept lattices
author:
- Jesús Medina
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '2010'
categories: uncategorised
slug: 2010/La
details: Inf. Sci. vol. 180 (5), pages 712--725.
doi: 10.1016/J.INS.2009.11.018
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Medina2010></a>[[MO10]](#cite-Medina2010) J. Medina and M. Ojeda-Aciego. “Multi-adjoint t-concept lattices”. In: _Inf. Sci._ 180.5 (2010), pp. 712-725. DOI: [10.1016/J.INS.2009.11.018](https://doi.org/10.1016%2FJ.INS.2009.11.018). URL: [https://doi.org/10.1016/j.ins.2009.11.018](https://doi.org/10.1016/j.ins.2009.11.018).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{Medina2010,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Jes{\a'u}s Medina and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Inf. Sci.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Multi-adjoint t-concept lattices},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2010},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number = {5},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {712--725},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {180},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/isci/MedinaO10.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1016/J.INS.2009.11.018},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Thu, 07 Jan 2021 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1016/j.ins.2009.11.018},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1016/J.INS.2009.11.018" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1016/J.INS.2009.11.018" class="plumx-details" data-site="plum" data-hide-when-empty="true">Multi-adjoint t-concept lattices</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1016/J.INS.2009.11.018"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Aliev_2011></a>[[1]](#cite-Aliev_2011) R. Aliev and A. Tserkovny. “Systemic approach to fuzzy logic formalization for approximate reasoning”. In: _Information Sciences_ 181.6 (Mar. 2011), p. 1045–1059. ISSN: 0020-0255. DOI: [10.1016/j.ins.2010.11.021](https://doi.org/10.1016%2Fj.ins.2010.11.021). URL: [http://dx.doi.org/10.1016/j.ins.2010.11.021](http://dx.doi.org/10.1016/j.ins.2010.11.021).

<a name=bib-Antoni_2014></a>[[2]](#cite-Antoni_2014) L. Antoni, S. Krajči, O. Krídlo, et al. “On heterogeneous formal contexts”. In: _Fuzzy Sets and Systems_ 234 (Jan. 2014), p. 22–33. ISSN: 0165-0114. DOI: [10.1016/j.fss.2013.04.008](https://doi.org/10.1016%2Fj.fss.2013.04.008). URL: [http://dx.doi.org/10.1016/j.fss.2013.04.008](http://dx.doi.org/10.1016/j.fss.2013.04.008).

<a name=bib-Ayub_2021></a>[[3]](#cite-Ayub_2021) S. Ayub, S. Abdullah, F. Ghani, et al. “Cubic fuzzy Heronian mean Dombi aggregation operators and their application on multi-attribute decision-making problem”. In: _Soft Computing_ 25.6 (Feb. 2021), p. 4175–4189. ISSN: 1433-7479. DOI: [10.1007/s00500-020-05512-4](https://doi.org/10.1007%2Fs00500-020-05512-4). URL: [http://dx.doi.org/10.1007/s00500-020-05512-4](http://dx.doi.org/10.1007/s00500-020-05512-4).

<a name=bib-Cornejo_2015></a>[[4]](#cite-Cornejo_2015) M. E. Cornejo, J. Medina, and E. Ramírez-Poussa. “Attribute reduction in multi-adjoint concept lattices”. In: _Information Sciences_ 294 (Feb. 2015), p. 41–56. ISSN: 0020-0255. DOI: [10.1016/j.ins.2014.09.033](https://doi.org/10.1016%2Fj.ins.2014.09.033). URL: [http://dx.doi.org/10.1016/j.ins.2014.09.033](http://dx.doi.org/10.1016/j.ins.2014.09.033).

<a name=bib-Cornejo_2018></a>[[5]](#cite-Cornejo_2018) M. E. Cornejo, J. Medina, and E. Ramírez-Poussa. “Characterizing reducts in multi-adjoint concept lattices”. In: _Information Sciences_ 422 (Jan. 2018), p. 364–376. ISSN: 0020-0255. DOI: [10.1016/j.ins.2017.08.099](https://doi.org/10.1016%2Fj.ins.2017.08.099). URL: [http://dx.doi.org/10.1016/j.ins.2017.08.099](http://dx.doi.org/10.1016/j.ins.2017.08.099).

<a name=bib-D_az_2013></a>[[6]](#cite-D_az_2013) J. C. Díaz and J. Medina. “Multi-adjoint relation equations: Definition, properties and solutions using concept lattices”. In: _Information Sciences_ 253 (Dec. 2013), p. 100–109. ISSN: 0020-0255. DOI: [10.1016/j.ins.2013.07.024](https://doi.org/10.1016%2Fj.ins.2013.07.024). URL: [http://dx.doi.org/10.1016/j.ins.2013.07.024](http://dx.doi.org/10.1016/j.ins.2013.07.024).

<a name=bib-Estaji_2012></a>[[7]](#cite-Estaji_2012) A. Estaji, M. Hooshmandasl, and B. Davvaz. “Rough set theory applied to lattice theory”. In: _Information Sciences_ 200 (Oct. 2012), p. 108–122. ISSN: 0020-0255. DOI: [10.1016/j.ins.2012.02.060](https://doi.org/10.1016%2Fj.ins.2012.02.060). URL: [http://dx.doi.org/10.1016/j.ins.2012.02.060](http://dx.doi.org/10.1016/j.ins.2012.02.060).

<a name=bib-Eugenia_Cornejo_2013></a>[[8]](#cite-Eugenia_Cornejo_2013) M. Eugenia Cornejo, J. Medina, and E. Ramírez. “A comparative study of adjoint triples”. In: _Fuzzy Sets and Systems_ 211 (Jan. 2013), p. 1–14. ISSN: 0165-0114. DOI: [10.1016/j.fss.2012.05.004](https://doi.org/10.1016%2Fj.fss.2012.05.004). URL: [http://dx.doi.org/10.1016/j.fss.2012.05.004](http://dx.doi.org/10.1016/j.fss.2012.05.004).

<a name=bib-Hayat_2018></a>[[9]](#cite-Hayat_2018) K. Hayat, M. I. Ali, B. Cao, et al. “Another View of Aggregation Operators on Group-Based Generalized Intuitionistic Fuzzy Soft Sets: Multi-Attribute Decision Making Methods”. In: _Symmetry_ 10.12 (Dec. 2018), p. 753. ISSN: 2073-8994. DOI: [10.3390/sym10120753](https://doi.org/10.3390%2Fsym10120753). URL: [http://dx.doi.org/10.3390/sym10120753](http://dx.doi.org/10.3390/sym10120753).

<a name=bib-Hu_2019></a>[[10]](#cite-Hu_2019) J. Hu, L. Pan, Y. Yang, et al. “A group medical diagnosis model based on intuitionistic fuzzy soft sets”. In: _Applied Soft Computing_ 77 (Apr. 2019), p. 453–466. ISSN: 1568-4946. DOI: [10.1016/j.asoc.2019.01.041](https://doi.org/10.1016%2Fj.asoc.2019.01.041). URL: [http://dx.doi.org/10.1016/j.asoc.2019.01.041](http://dx.doi.org/10.1016/j.asoc.2019.01.041).

<a name=bib-Kang_2013></a>[[11]](#cite-Kang_2013) X. Kang, D. Li, S. Wang, et al. “Rough set model based on formal concept analysis”. In: _Information Sciences_ 222 (Feb. 2013), p. 611–625. ISSN: 0020-0255. DOI: [10.1016/j.ins.2012.07.052](https://doi.org/10.1016%2Fj.ins.2012.07.052). URL: [http://dx.doi.org/10.1016/j.ins.2012.07.052](http://dx.doi.org/10.1016/j.ins.2012.07.052).

<a name=bib-Khan_2018></a>[[12]](#cite-Khan_2018) Q. Khan, P. Liu, T. Mahmood, et al. “Some Interval Neutrosophic Dombi Power Bonferroni Mean Operators and Their Application in Multi–Attribute Decision–Making”. In: _Symmetry_ 10.10 (Oct. 2018), p. 459. ISSN: 2073-8994. DOI: [10.3390/sym10100459](https://doi.org/10.3390%2Fsym10100459). URL: [http://dx.doi.org/10.3390/sym10100459](http://dx.doi.org/10.3390/sym10100459).

<a name=bib-Li_2016></a>[[13]](#cite-Li_2016) K. Li, M. Shao, and W. Wu. “A data reduction method in formal fuzzy contexts”. In: _International Journal of Machine Learning and Cybernetics_ 8.4 (Jan. 2016), p. 1145–1155. ISSN: 1868-808X. DOI: [10.1007/s13042-015-0485-8](https://doi.org/10.1007%2Fs13042-015-0485-8). URL: [http://dx.doi.org/10.1007/s13042-015-0485-8](http://dx.doi.org/10.1007/s13042-015-0485-8).

<a name=bib-Medina_2012></a>[[14]](#cite-Medina_2012) J. Medina and M. Ojeda-Aciego. “On multi-adjoint concept lattices based on heterogeneous conjunctors”. In: _Fuzzy Sets and Systems_ 208 (Dec. 2012), p. 95–110. ISSN: 0165-0114. DOI: [10.1016/j.fss.2012.02.008](https://doi.org/10.1016%2Fj.fss.2012.02.008). URL: [http://dx.doi.org/10.1016/j.fss.2012.02.008](http://dx.doi.org/10.1016/j.fss.2012.02.008).

<a name=bib-Outrata_2012></a>[[15]](#cite-Outrata_2012) J. Outrata and V. Vychodil. “Fast algorithm for computing fixpoints of Galois connections induced by object-attribute relational data”. In: _Information Sciences_ 185.1 (Feb. 2012), p. 114–127. ISSN: 0020-0255. DOI: [10.1016/j.ins.2011.09.023](https://doi.org/10.1016%2Fj.ins.2011.09.023). URL: [http://dx.doi.org/10.1016/j.ins.2011.09.023](http://dx.doi.org/10.1016/j.ins.2011.09.023).

<a name=bib-P_cs_2012></a>[[16]](#cite-P_cs_2012) J. Pócs. “Note on generating fuzzy concept lattices via Galois connections”. In: _Information Sciences_ 185.1 (Feb. 2012), p. 128–136. ISSN: 0020-0255. DOI: [10.1016/j.ins.2011.09.021](https://doi.org/10.1016%2Fj.ins.2011.09.021). URL: [http://dx.doi.org/10.1016/j.ins.2011.09.021](http://dx.doi.org/10.1016/j.ins.2011.09.021).

<a name=bib-Radovi__2018></a>[[17]](#cite-Radovi__2018) D. Radović, Ž. Stević, D. Pamučar, et al. “Measuring Performance in Transportation Companies in Developing Countries: A Novel Rough ARAS Model”. In: _Symmetry_ 10.10 (Sep. 2018), p. 434. ISSN: 2073-8994. DOI: [10.3390/sym10100434](https://doi.org/10.3390%2Fsym10100434). URL: [http://dx.doi.org/10.3390/sym10100434](http://dx.doi.org/10.3390/sym10100434).

<a name=bib-Rodcha_2019></a>[[18]](#cite-Rodcha_2019) R. Rodcha, N. K. Tripathi, and R. Prasad Shrestha. “Comparison of Cash Crop Suitability Assessment Using Parametric, AHP, and FAHP Methods”. In: _Land_ 8.5 (May. 2019), p. 79. ISSN: 2073-445X. DOI: [10.3390/land8050079](https://doi.org/10.3390%2Fland8050079). URL: [http://dx.doi.org/10.3390/land8050079](http://dx.doi.org/10.3390/land8050079).

<a name=bib-Shao_2016></a>[[19]](#cite-Shao_2016) M. Shao, Y. Leung, X. Wang, et al. “Granular reducts of formal fuzzy contexts”. In: _Knowledge-Based Systems_ 114 (Dec. 2016), p. 156–166. ISSN: 0950-7051. DOI: [10.1016/j.knosys.2016.10.010](https://doi.org/10.1016%2Fj.knosys.2016.10.010). URL: [http://dx.doi.org/10.1016/j.knosys.2016.10.010](http://dx.doi.org/10.1016/j.knosys.2016.10.010).

<a name=bib-Shao_2015></a>[[20]](#cite-Shao_2015) M. Shao, H. Yang, and W. Wu. “Knowledge reduction in formal fuzzy contexts”. In: _Knowledge-Based Systems_ 73 (Jan. 2015), p. 265–275. ISSN: 0950-7051. DOI: [10.1016/j.knosys.2014.10.008](https://doi.org/10.1016%2Fj.knosys.2014.10.008). URL: [http://dx.doi.org/10.1016/j.knosys.2014.10.008](http://dx.doi.org/10.1016/j.knosys.2014.10.008).

<a name=bib-Wang_2018></a>[[21]](#cite-Wang_2018) R. Wang, J. Wang, H. Gao, et al. “Methods for MADM with Picture Fuzzy Muirhead Mean Operators and Their Application for Evaluating the Financial Investment Risk”. In: _Symmetry_ 11.1 (Dec. 2018), p. 6. ISSN: 2073-8994. DOI: [10.3390/sym11010006](https://doi.org/10.3390%2Fsym11010006). URL: [http://dx.doi.org/10.3390/sym11010006](http://dx.doi.org/10.3390/sym11010006).

<a name=bib-Xu_2014></a>[[22]](#cite-Xu_2014) W. Xu, J. Pang, and S. Luo. “A novel cognitive system model and approach to transformation of information granules”. In: _International Journal of Approximate Reasoning_ 55.3 (Mar. 2014), p. 853–866. ISSN: 0888-613X. DOI: [10.1016/j.ijar.2013.10.002](https://doi.org/10.1016%2Fj.ijar.2013.10.002). URL: [http://dx.doi.org/10.1016/j.ijar.2013.10.002](http://dx.doi.org/10.1016/j.ijar.2013.10.002).

<a name=bib-Zhang_2018></a>[[23]](#cite-Zhang_2018) C. Zhang, J. Hu, J. Qiu, et al. “A Novel Fuzzy Observer-Based Steering Control Approach for Path Tracking in Autonomous Vehicles”. In: _IEEE Transactions on Fuzzy Systems_ (2018), p. 1–1. ISSN: 1941-0034. DOI: [10.1109/tfuzz.2018.2856187](https://doi.org/10.1109%2Ftfuzz.2018.2856187). URL: [http://dx.doi.org/10.1109/tfuzz.2018.2856187](http://dx.doi.org/10.1109/tfuzz.2018.2856187).

<a name=bib-Zhang_20181></a>[[24]](#cite-Zhang_20181) H. Zhang, R. Zhang, H. Huang, et al. “Some Picture Fuzzy Dombi Heronian Mean Operators with Their Application to Multi-Attribute Decision-Making”. In: _Symmetry_ 10.11 (Nov. 2018), p. 593. ISSN: 2073-8994. DOI: [10.3390/sym10110593](https://doi.org/10.3390%2Fsym10110593). URL: [http://dx.doi.org/10.3390/sym10110593](http://dx.doi.org/10.3390/sym10110593).

