---
title: Publication of <em>K-pages graph drawing with multivalued neural networks</em>
author: Domingo López-Rodríguez, E. Mérida-Casermeiro, J.M. Ortíz-de-Lazcano-Lobato,
  G. Galán-Marín
date: '2007-01-01'
categories:
- Neural networks
- Combinatorial optimization
---

The work <u>K-pages graph drawing with multivalued neural networks</u> has been published in <em>Artificial Neural Networks - {ICANN} 2007, 17th International Conference, Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics), (4669 LNCS), PART 2, <em>pp. 816-825</em></em>.

<u>Abstract</u>:


In this paper, the K-pages graph layout problem is solved by a new neural model. This model consists of two neural networks performing jointly in order to minimize the same energy function. The neural technique applied to this problem allows to reduce the energy function by changing outputs from both networks -outputs of first network representing location of nodes in the nodes line, while the outputs of the second one meaning the page where the edges are drawn. A detailed description of the model is presented, and the technique to minimize an energy function is fully described. It has proved to be a very competitive and efficient algorithm, in terms of quality of solutions and computational time, when compared to the state-of-the-art heuristic methods specifically designed for this problem. Some simulation results are presented in this paper, to show the comparative efficiency of the methods. © Springer-Verlag Berlin Heidelberg 2007.

