---
title: 'URSUS_LST: URban SUStainability intelligent system for predicting the impact
  of urban green infrastructure on land surface temperatures'
author:
- Francisco Rodríguez-Gómez
- José del Campo-Ávila
- Luis Pérez-Urrestarazu
- <a href='/people/staff/dominlopez/' style='color:rgb(100,0,50);'>Domingo López Rodríguez</a>
date: '2025'
categories: uncategorised
slug: 2025/UrSuInSyPrImUrGrInLaSuTe
details: Environmental Modelling & Software vol. 186 , pages 106364.
doi: 10.1016/j.envsoft.2025.106364
keywords: Expert system, Urban greening, Urban heat island, Regression models, Open-source
project: 2019-ursus-dm
listing:
- id: funding
  contents: funding.yml
  type: default
  sort: date desc
---



# Abstract


Mitigating Urban Heat Island (UHI) effects has become a challenge to improve urban sustainability. The simulation tool URSUS_LST has been developed to allow urban planners to estimate how the addition of different green infrastructure elements would affect temperature. To achieve this, a new methodology was defined based on data mining, geospatial image processing and the knowledge of experts in the domain that predicts the Land Surface Temperature (LST) of any location within a city. It consists of a first data mining phase in which the real LST and the different urban elements of the nearby environment are considered: buildings, vegetation and water bodies. In a second phase, different regression models are induced to predict LST. Additionally, considering the most accurate models, the relevant attributes and their relationships are identified. A real application of the tool in the city of Malaga (Spain) has been used as an example of its usefulness.



# Funding
::: {.callout-note appearance='minimal' collapse=false}
## Projects funding this work

:::{#funding}
:::
:::






# Citation
Please, cite this work as:


<a name=bib-RODRIGUEZGOMEZ2025106364></a>[[Rod+25]](#cite-RODRIGUEZGOMEZ2025106364) F. Rodríguez-Gómez, J. del Campo-Ávila, L. Pérez-Urrestarazu, et al. “URSUS_LST: URban SUStainability intelligent system for predicting the impact of urban green infrastructure on land surface temperatures”. In: _Environmental Modelling & Software_ 186 (2025), p. 106364. ISSN: 1364-8152. DOI: [https://doi.org/10.1016/j.envsoft.2025.106364](https://doi.org/https%3A%2F%2Fdoi.org%2F10.1016%2Fj.envsoft.2025.106364). URL: [https://www.sciencedirect.com/science/article/pii/S1364815225000489](https://www.sciencedirect.com/science/article/pii/S1364815225000489).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{RODRIGUEZGOMEZ2025106364,<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {URSUS_LST: URban SUStainability intelligent system for predicting the impact of urban green infrastructure on land surface temperatures},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Environmental Modelling & Software},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {186},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {106364},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2025},<br>&nbsp;&nbsp;&nbsp;&nbsp;  issn = {1364-8152},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {https://doi.org/10.1016/j.envsoft.2025.106364},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://www.sciencedirect.com/science/article/pii/S1364815225000489},<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Francisco Rodr{\a'\i}guez-G{\a'o}mez and Jos{\a'e} {del Campo-{\a'A}vila} and Luis P{\a'e}rez-Urrestarazu and Domingo L{\a'o}pez-Rodr{\a'\i}guez},<br>&nbsp;&nbsp;&nbsp;&nbsp;  keywords = {Expert system, Urban greening, Urban heat island, Regression models, Open-source},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {Mitigating Urban Heat Island (UHI) effects has become a challenge to improve urban sustainability. The simulation tool URSUS_LST has been developed to allow urban planners to estimate how the addition of different green infrastructure elements would affect temperature. To achieve this, a new methodology was defined based on data mining, geospatial image processing and the knowledge of experts in the domain that predicts the Land Surface Temperature (LST) of any location within a city. It consists of a first data mining phase in which the real LST and the different urban elements of the nearby environment are considered: buildings, vegetation and water bodies. In a second phase, different regression models are induced to predict LST. Additionally, considering the most accurate models, the relevant attributes and their relationships are identified. A real application of the tool in the city of Malaga (Spain) has been used as an example of its usefulness.},<br>}

:::








