---
author: Manuel Ojeda-Hernández, Francisco Pérez-Gámez, Ángel Mora Bonilla, Domingo
  López-Rodríguez
Status: Published
date: '2021-07-20'
slug: 2021/UsLoDeKeItMaEd
title: Using Logic to Determine Key Items in Math Education
categories:
- E-learning
- Formal concept analysis
- Fuzzy logic
header_image: ~
details: IADIS International Conference e-Learning 2021 (part of MCCSIS 2021)
link: 2021-e-learning/paper.pdf
project: 2019-PIE-clustering
keywords: ''
listing:
- id: funding
  contents: funding.yml
  type: default
  sort: date desc
---


# Abstract


Due to the COVID-19 restrictions, high-schools in Spain are having both online and in-class lectures.  As a result, the students can use not only the information provided by the teachers in class, but they can also use several other methods such as videos and online examples that allow the students to have materials from different places. In this paper, we analyse the Mathematics results of the first two terms in a secondary school from Andalusia. This analysis can help find the central units of the subject found, that is, giving enough background knowledge to keep up with the module.  When these are found, the teachers can improve the learning and the results in the following years.




# Funding
::: {.callout-note appearance='minimal' collapse=false}
## Projects funding this work

:::{#funding}
:::
:::









# Citation
Please, cite this work as:


<a name=bib-Ojeda-Hernandez202162></a>[[Oje+21]](#cite-Ojeda-Hernandez202162) M. Ojeda-Hernández, F. Pérez-Gámez, Á. Mora-Bonilla, et al. “Using logic to determine key items in math education”. In: _15th International Conference e-Learning, EL 2021 - Held at the 15th Multi-Conference on Computer Science and Information Systems, MCCSIS 2021_. IADIS, 2021, pp. 62-69. ISBN: 9789898704290. URL: [https://www.scopus.com/inward/record.uri?eid=2-s2.0-85117688099&partnerID=40&md5=85bb65037a2dc1d70fbb879fe2b905e2](https://www.scopus.com/inward/record.uri?eid=2-s2.0-85117688099&partnerID=40&md5=85bb65037a2dc1d70fbb879fe2b905e2).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@inproceedings{Ojeda-Hernandez202162,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Ojeda-Hernández, M. and Pérez-Gámez, F. and Mora-Bonilla, Á. and López-Rodríguez, D.},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Using logic to determine key items in math education},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle={15th International Conference e-Learning, EL 2021 - Held at the 15th Multi-Conference on Computer Science and Information Systems, MCCSIS 2021},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2021},<br>&nbsp;&nbsp;&nbsp;&nbsp;pages={62-69},<br>&nbsp;&nbsp;&nbsp;&nbsp;url={https://www.scopus.com/inward/record.uri?eid=2-s2.0-85117688099&partnerID=40&md5=85bb65037a2dc1d70fbb879fe2b905e2},<br>&nbsp;&nbsp;&nbsp;&nbsp;abstract={Due to the COVID-19 restrictions, high-schools in Spain are having both online and in-class lectures. As a result, the students can use not only the information provided by the teachers in class, but they can also use several other methods such as videos and online examples that allow the students to have materials from different places. In this paper, we analyse the Mathematics results of the first two terms in a secondary school from Andalusia. This analysis can help find the central units of the subject found, that is, giving enough background knowledge to keep up with the module. When these are found, the teachers can improve the learning and the results in the following years. © 15th International Conference e-Learning, EL 2021 - Held at the 15th Multi-Conference on Computer Science and Information Systems, MCCSIS 2021. All rights reserved.},<br>&nbsp;&nbsp;&nbsp;&nbsp;author_keywords={E-Learning Assessment Tools;  Formal Concept Analysis;  Implications;  Knowledge Mining},<br>&nbsp;&nbsp;&nbsp;&nbsp;keywords={Data mining;  Formal concept analysis;  Information systems;  Information use;  Students, Assessment tool;  E - learning;  E-learning assessment tool;  Formal concepts analysis;  Higher School;  Implication;  In-class lectures;  Knowledge mining;  Learning assessment;  Teachers', E-learning},<br>&nbsp;&nbsp;&nbsp;&nbsp;publisher={IADIS},<br>&nbsp;&nbsp;&nbsp;&nbsp;isbn={9789898704290}<br>}

:::









