---
author: Ezequiel López-Rubio, Juan Miguel Ortiz-de-Lazcano-Lobato, Domingo López-Rodríguez,
  María del Carmen Vargas-González
Status: Published
date: '2007-01-01'
slug: 2007-icann2
title: Soft Clustering for Nonparametric Probability Density Function Estimation
header_image: ~
categories: Neural networks
details: Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial
  Intelligence and Lecture Notes in Bioinformatics), (4668 LNCS), PART 1, <em>pp.
  707-716</em>
doi: 10.1007/978-3-540-74690-4_72
link: 2007-icann2/paper.pdf
project: ''
keywords: ''
---


# Abstract


We present a nonparametric probability density estimation model. The classical Parzen window approach builds a spherical Gaussian density around every input sample. Our method has a first stage where hard neighbourhoods are determined for every sample. Then soft clusters are considered to merge the information coming from several hard neighbourhoods. Our proposal estimates the local principal directions to yield a specific Gaussian mixture component for each soft cluster. This leads to outperform other proposals where local parameter selection is not allowed and/or there are no smoothing strategies, like the manifold Parzen windows. © Springer-Verlag Berlin Heidelberg 2007.





# Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```


# Citation
Please, cite this work as:


<a name=bib-LopezRubio2007></a>[[Lóp+07]](#cite-LopezRubio2007) E. López-Rubio, J. M. Ortiz-de-Lazcano-Lobato, D. López-Rodríguez, et al. “Soft Clustering for Nonparametric Probability Density Function Estimation”. In: _Artificial Neural Networks - ICANN 2007, 17th International Conference, Porto, Portugal, September 9-13, 2007, Proceedings, Part I_. Ed. by J. M. de á, L. A. Alexandre, W. Duch and D. P. Mandic. Vol. 4668 LNCS. Lecture Notes in Computer Science PART 1. cited By 0; Conference of 17th International Conference on Artificial Neural Networks, ICANN 2007 ; Conference Date: 9 September 2007 Through 13 September 2007; Conference Code:70943. Porto: Springer Verlag, 2007, pp. 707-716. DOI: [10.1007/978-3-540-74690-4_72](https://doi.org/10.1007%2F978-3-540-74690-4_72). URL: [https://doi.org/10.1007/978-3-540-74690-4_72](https://doi.org/10.1007/978-3-540-74690-4_72).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{LopezRubio2007,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Ezequiel López-Rubio and Juan Miguel Ortiz-de-Lazcano-Lobato and Domingo López-Rodríguez and María {del Carmen Vargas-González}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Artificial Neural Networks - {ICANN} 2007, 17th International Conference, Porto, Portugal, September 9-13, 2007, Proceedings, Part {I}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Soft Clustering for Nonparametric Probability Density Function Estimation},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2007},<br>&nbsp;&nbsp;&nbsp;&nbsp;  address = {Porto},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Joaquim Marques de á and Luís A. Alexandre and Wlodzislaw Duch and Danilo P. Mandic},<br>&nbsp;&nbsp;&nbsp;&nbsp;  note = {cited By 0; Conference of 17th International Conference on Artificial Neural Networks, ICANN 2007 ; Conference Date: 9 September 2007 Through 13 September 2007; Conference Code:70943},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number = {PART 1},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {707-716},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer Verlag},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {4668 LNCS},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {We present a nonparametric probability density estimation model. The classical Parzen window approach builds a spherical Gaussian density around every input sample. Our method has a first stage where hard neighbourhoods are determined for every sample. Then soft clusters are considered to merge the information coming from several hard neighbourhoods. Our proposal estimates the local principal directions to yield a specific Gaussian mixture component for each soft cluster. This leads to outperform other proposals where local parameter selection is not allowed and/or there are no smoothing strategies, like the manifold Parzen windows. © Springer-Verlag Berlin Heidelberg 2007.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  author_keywords = {Nonparametric modeling; Parzen windows; Probability density estimation; Soft clustering},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/icann/Lopez-RubioOLV07.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  document_type = {Conference Paper},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/978-3-540-74690-4_72},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)},<br>&nbsp;&nbsp;&nbsp;&nbsp;  source = {Scopus},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/978-3-540-74690-4_72},<br>}

:::


