---
title: Generalizations of lattices via non-deterministic operators
author:
- Javier Martínez
- Gloria Gutiérrez
- Inmaculada Perez de Guzmán
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
date: '2005'
categories: uncategorised
slug: 2005/GeLaViOp
details: Discret. Math. vol. 295 (1-3), pages 107--141.
doi: 10.1016/J.DISC.2004.08.043
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Martinez2005></a>[[Mar+05]](#cite-Martinez2005) J. Mart\'\inez, G. Gutiérrez, I. P. de Guzmán, et al. “Generalizations of lattices via non-deterministic operators”. In: _Discret. Math._ 295.1-3 (2005), pp. 107-141. DOI: [10.1016/J.DISC.2004.08.043](https://doi.org/10.1016%2FJ.DISC.2004.08.043). URL: [https://doi.org/10.1016/j.disc.2004.08.043](https://doi.org/10.1016/j.disc.2004.08.043).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{Martinez2005,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Javier Mart\'\inez and Gloria Guti{\a'e}rrez and Inmaculada Perez {de Guzm{\a'a}n} and Pablo Cordero},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Discret. Math.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Generalizations of lattices via non-deterministic operators},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2005},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number = {1-3},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {107--141},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {295},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/dm/MartinezGGC05.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1016/J.DISC.2004.08.043},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Tue, 29 Aug 2023 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1016/j.disc.2004.08.043},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1016/J.DISC.2004.08.043" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1016/J.DISC.2004.08.043" class="plumx-details" data-site="plum" data-hide-when-empty="true">Generalizations of lattices via non-deterministic operators</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1016/J.DISC.2004.08.043"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Belfodil_2020></a>[[1]](#cite-Belfodil_2020) A. Belfodil, S. O. Kuznetsov, and M. Kaytoue. “On pattern setups and pattern multistructures”. In: _International Journal of General Systems_ 49.8 (Sep. 2020), p. 785–818. ISSN: 1563-5104. DOI: [10.1080/03081079.2020.1806832](https://doi.org/10.1080%2F03081079.2020.1806832). URL: [http://dx.doi.org/10.1080/03081079.2020.1806832](http://dx.doi.org/10.1080/03081079.2020.1806832).

<a name=bib-Cabrera_2009></a>[[2]](#cite-Cabrera_2009) I. P. Cabrera, P. Cordero, G. Gutiérrez, et al. “Congruence relations on some hyperstructures”. In: _Annals of Mathematics and Artificial Intelligence_ 56.3–4 (Jul. 2009), p. 361–370. ISSN: 1573-7470. DOI: [10.1007/s10472-009-9146-5](https://doi.org/10.1007%2Fs10472-009-9146-5). URL: [http://dx.doi.org/10.1007/s10472-009-9146-5](http://dx.doi.org/10.1007/s10472-009-9146-5).

<a name=bib-Cabrera_20091></a>[[3]](#cite-Cabrera_20091) I. P. Cabrera, P. Cordero, G. Gutiérrez, et al. “Fuzzy congruence relations on nd-groupoids”. In: _International Journal of Computer Mathematics_ 86.10–11 (Nov. 2009), p. 1684–1695. ISSN: 1029-0265. DOI: [10.1080/00207160902721797](https://doi.org/10.1080%2F00207160902721797). URL: [http://dx.doi.org/10.1080/00207160902721797](http://dx.doi.org/10.1080/00207160902721797).

<a name=bib-Cabrera_2011></a>[[4]](#cite-Cabrera_2011) I. P. Cabrera, P. Cordero, and M. Ojeda-Aciego. “Non-deterministic Algebraic Structures for Soft Computing”. In: _Advances in Computational Intelligence_. Springer Berlin Heidelberg, 2011, p. 437–444. ISBN: 9783642214981. DOI: [10.1007/978-3-642-21498-1_55](https://doi.org/10.1007%2F978-3-642-21498-1_55). URL: [http://dx.doi.org/10.1007/978-3-642-21498-1_55](http://dx.doi.org/10.1007/978-3-642-21498-1_55).

<a name=bib-Cabrera_2010></a>[[5]](#cite-Cabrera_2010) I. Cabrera, P. Cordero, G. Gutiérrez, et al. “A coalgebraic approach to non-determinism: Applications to multilattices”. In: _Information Sciences_ 180.22 (Nov. 2010), p. 4323–4335. ISSN: 0020-0255. DOI: [10.1016/j.ins.2010.07.002](https://doi.org/10.1016%2Fj.ins.2010.07.002). URL: [http://dx.doi.org/10.1016/j.ins.2010.07.002](http://dx.doi.org/10.1016/j.ins.2010.07.002).

<a name=bib-Cabrera_2012></a>[[6]](#cite-Cabrera_2012) I. Cabrera, P. Cordero, G. Gutiérrez, et al. “Finitary coalgebraic multisemilattices and multilattices”. In: _Applied Mathematics and Computation_ 219.1 (Sep. 2012), p. 31–44. ISSN: 0096-3003. DOI: [10.1016/j.amc.2011.10.081](https://doi.org/10.1016%2Fj.amc.2011.10.081). URL: [http://dx.doi.org/10.1016/j.amc.2011.10.081](http://dx.doi.org/10.1016/j.amc.2011.10.081).

<a name=bib-Cabrera_2014></a>[[7]](#cite-Cabrera_2014) I. Cabrera, P. Cordero, G. Gutiérrez, et al. “On residuation in multilattices: Filters, congruences, and homomorphisms”. In: _Fuzzy Sets and Systems_ 234 (Jan. 2014), p. 1–21. ISSN: 0165-0114. DOI: [10.1016/j.fss.2013.04.002](https://doi.org/10.1016%2Fj.fss.2013.04.002). URL: [http://dx.doi.org/10.1016/j.fss.2013.04.002](http://dx.doi.org/10.1016/j.fss.2013.04.002).

<a name=bib-Cordero_2008></a>[[8]](#cite-Cordero_2008) P. Cordero, A. Mora, I. de Guzmán, et al. “Non-deterministic ideal operators: An adequate tool for formalization in Data Bases”. In: _Discrete Applied Mathematics_ 156.6 (Mar. 2008), p. 911–923. ISSN: 0166-218X. DOI: [10.1016/j.dam.2007.02.014](https://doi.org/10.1016%2Fj.dam.2007.02.014). URL: [http://dx.doi.org/10.1016/j.dam.2007.02.014](http://dx.doi.org/10.1016/j.dam.2007.02.014).

<a name=bib-Di_kouam_Fotso_2024></a>[[9]](#cite-Di_kouam_Fotso_2024) L. É. Diékouam Fotso, C. P. Kengne, and D. C. Awouafack. “Fuzzy prime filter theorem in multilattices”. In: _Fuzzy Sets and Systems_ 497 (Dec. 2024), p. 109148. ISSN: 0165-0114. DOI: [10.1016/j.fss.2024.109148](https://doi.org/10.1016%2Fj.fss.2024.109148). URL: [http://dx.doi.org/10.1016/j.fss.2024.109148](http://dx.doi.org/10.1016/j.fss.2024.109148).

<a name=bib-Maffeu_2019></a>[[10]](#cite-Maffeu_2019) L. N. Maffeu, C. Lele, J. B. Nganou, et al. “Multiplicative and implicative derivations on residuated multilattices”. In: _Soft Computing_ 23.23 (Jun. 2019), p. 12199–12208. ISSN: 1433-7479. DOI: [10.1007/s00500-019-04184-z](https://doi.org/10.1007%2Fs00500-019-04184-z). URL: [http://dx.doi.org/10.1007/s00500-019-04184-z](http://dx.doi.org/10.1007/s00500-019-04184-z).

<a name=bib-Medina_Moreno_2013></a>[[11]](#cite-Medina_Moreno_2013) J. Medina-Moreno, M. Ojeda-Aciego, and J. Ruiz-Calviño. “Concept-Forming Operators on Multilattices”. In: _Formal Concept Analysis_. Springer Berlin Heidelberg, 2013, p. 203–215. ISBN: 9783642383175. DOI: [10.1007/978-3-642-38317-5_13](https://doi.org/10.1007%2F978-3-642-38317-5_13). URL: [http://dx.doi.org/10.1007/978-3-642-38317-5_13](http://dx.doi.org/10.1007/978-3-642-38317-5_13).

<a name=bib-Medina_2007></a>[[12]](#cite-Medina_2007) J. Medina, M. Ojeda-Aciego, and J. Ruiz-Calviño. “Fuzzy logic programming via multilattices”. In: _Fuzzy Sets and Systems_ 158.6 (Mar. 2007), p. 674–688. ISSN: 0165-0114. DOI: [10.1016/j.fss.2006.11.006](https://doi.org/10.1016%2Fj.fss.2006.11.006). URL: [http://dx.doi.org/10.1016/j.fss.2006.11.006](http://dx.doi.org/10.1016/j.fss.2006.11.006).

<a name=bib-Medina_2006></a>[[13]](#cite-Medina_2006) J. Medina, M. Ojeda-Aciego, and J. Ruiz-Calviño. “Multi-lattices as a Basis for Generalized Fuzzy Logic Programming”. In: _Fuzzy Logic and Applications_. Springer Berlin Heidelberg, 2006, p. 61–70. ISBN: 9783540325307. DOI: [10.1007/11676935_8](https://doi.org/10.1007%2F11676935_8). URL: [http://dx.doi.org/10.1007/11676935_8](http://dx.doi.org/10.1007/11676935_8).

<a name=bib-Nguepy_Dongmo_2024></a>[[14]](#cite-Nguepy_Dongmo_2024) G. Nguepy Dongmo, B. B. Koguep Njionou, L. Kwuida, et al. “Multilattice as the set of truth values for fuzzy rough sets”. In: _Journal of Applied Non-Classical Logics_ (Jul. 2024), p. 1–20. ISSN: 1958-5780. DOI: [10.1080/11663081.2024.2373016](https://doi.org/10.1080%2F11663081.2024.2373016). URL: [http://dx.doi.org/10.1080/11663081.2024.2373016](http://dx.doi.org/10.1080/11663081.2024.2373016).

<a name=bib-Nguepy_Dongmo_2023></a>[[15]](#cite-Nguepy_Dongmo_2023) G. Nguepy Dongmo, B. B. Koguep Njionou, L. Kwuida, et al. “Rough Fuzzy Concept Analysis via Multilattice”. In: _Rough Sets_. Springer Nature Switzerland, 2023, p. 495–508. ISBN: 9783031509599. DOI: [10.1007/978-3-031-50959-9_34](https://doi.org/10.1007%2F978-3-031-50959-9_34). URL: [http://dx.doi.org/10.1007/978-3-031-50959-9_34](http://dx.doi.org/10.1007/978-3-031-50959-9_34).

<a name=bib-Straccia_2009></a>[[16]](#cite-Straccia_2009) U. Straccia, M. Ojeda-Aciego, and C. V. Damásio. “On Fixed-Points of Multivalued Functions on Complete Lattices and Their Application to Generalized Logic Programs”. In: _SIAM Journal on Computing_ 38.5 (Jan. 2009), p. 1881–1911. ISSN: 1095-7111. DOI: [10.1137/070695976](https://doi.org/10.1137%2F070695976). URL: [http://dx.doi.org/10.1137/070695976](http://dx.doi.org/10.1137/070695976).

<a name=bib-Zedam_2024></a>[[17]](#cite-Zedam_2024) L. Zedam and B. De Baets. “Weaker forms of increasingness of binary operations and their role in the characterization of meet and join operations”. In: _Fuzzy Sets and Systems_ 497 (Dec. 2024), p. 109116. ISSN: 0165-0114. DOI: [10.1016/j.fss.2024.109116](https://doi.org/10.1016%2Fj.fss.2024.109116). URL: [http://dx.doi.org/10.1016/j.fss.2024.109116](http://dx.doi.org/10.1016/j.fss.2024.109116).

