---
title: A Non-explosive Treatment of Functional Dependencies Using Rewriting Logic
author:
- Gabriel Aguilera
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/enciso/' style='color:rgb(100,0,50);'>Manuel Enciso</a>
- <a href='/people/staff/amora/' style='color:rgb(100,0,50);'>Ángel Mora</a>
- Inmaculada Perez de Guzmán
date: '2004'
categories: uncategorised
slug: 2004/TrFuDeUsReLo
details: Advances in Artificial Intelligence - {SBIA} 2004, 17th Brazilian Symposium
  on Artificial Intelligence, S{\~{a}}o Luis, Maranh{\~{a}}o, Brazil, September 29
  - October 1, 2004, Proceedings , Lecture Notes in Computer Science vol. 3171, pages
  31--40.
doi: 10.1007/978-3-540-28645-5_4
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Aguilera2004></a>[[Agu+04]](#cite-Aguilera2004) G. Aguilera, P. Cordero, M. Enciso, et al. “A Non-explosive Treatment of Functional Dependencies Using Rewriting Logic”. In: _Advances in Artificial Intelligence - SBIA 2004, 17th Brazilian Symposium on Artificial Intelligence, S~ao Luis, Maranh~ao, Brazil, September 29 - October 1, 2004, Proceedings_. Ed. by A. L. C. Bazzan and S. Labidi. Vol. 3171. Lecture Notes in Computer Science. Springer, 2004, pp. 31-40. DOI: [10.1007/978-3-540-28645-5\_4](https://doi.org/10.1007%2F978-3-540-28645-5%5C_4). URL: [https://doi.org/10.1007/978-3-540-28645-5\_4](https://doi.org/10.1007/978-3-540-28645-5\_4).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Aguilera2004,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Gabriel Aguilera and Pablo Cordero and Manuel Enciso and {\a'A}ngel Mora and Inmaculada Perez {de Guzm{\a'a}n}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Advances in Artificial Intelligence - {SBIA} 2004, 17th Brazilian Symposium on Artificial Intelligence, S{\~{a}}o Luis, Maranh{\~{a}}o, Brazil, September 29 - October 1, 2004, Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {A Non-explosive Treatment of Functional Dependencies Using Rewriting Logic},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2004},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Ana L. C. Bazzan and Sofiane Labidi},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {31--40},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {3171},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/sbia/AguileraCEMG04.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/978-3-540-28645-5\_4},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 26 May 2023 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/978-3-540-28645-5\_4},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/978-3-540-28645-5_4" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/978-3-540-28645-5_4" class="plumx-details" data-site="plum" data-hide-when-empty="true">A Non-explosive Treatment of Functional Dependencies Using Rewriting Logic</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1007/978-3-540-28645-5_4"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Belohlavek_2012></a>[[1]](#cite-Belohlavek_2012) R. Belohlavek, P. Cordero, M. Enciso, et al. “An Efficient Reasoning Method for Dependencies over Similarity and Ordinal Data”. In: _Modeling Decisions for Artificial Intelligence_. Springer Berlin Heidelberg, 2012, p. 408–419. ISBN: 9783642346200. DOI: [10.1007/978-3-642-34620-0_36](https://doi.org/10.1007%2F978-3-642-34620-0_36). URL: [http://dx.doi.org/10.1007/978-3-642-34620-0_36](http://dx.doi.org/10.1007/978-3-642-34620-0_36).

<a name=bib-Cordero_2011></a>[[2]](#cite-Cordero_2011) P. Cordero, M. Enciso, A. Mora, et al. “An Efficient Algorithm for Reasoning about Fuzzy Functional Dependencies”. In: _Advances in Computational Intelligence_. Springer Berlin Heidelberg, 2011, p. 412–420. ISBN: 9783642214981. DOI: [10.1007/978-3-642-21498-1_52](https://doi.org/10.1007%2F978-3-642-21498-1_52). URL: [http://dx.doi.org/10.1007/978-3-642-21498-1_52](http://dx.doi.org/10.1007/978-3-642-21498-1_52).

<a name=bib-Cordero_2008></a>[[3]](#cite-Cordero_2008) P. Cordero, A. Mora, I. de Guzmán, et al. “Non-deterministic ideal operators: An adequate tool for formalization in Data Bases”. In: _Discrete Applied Mathematics_ 156.6 (Mar. 2008), p. 911–923. ISSN: 0166-218X. DOI: [10.1016/j.dam.2007.02.014](https://doi.org/10.1016%2Fj.dam.2007.02.014). URL: [http://dx.doi.org/10.1016/j.dam.2007.02.014](http://dx.doi.org/10.1016/j.dam.2007.02.014).

<a name=bib-Hamrouni_2012></a>[[4]](#cite-Hamrouni_2012) T. Hamrouni. “Key roles of closed sets and minimal generators in concise representations of frequent patterns”. In: _Intelligent Data Analysis_ 16.4 (Jul. 2012), p. 581–631. ISSN: 1088-467X. DOI: [10.3233/ida-2012-0540](https://doi.org/10.3233%2Fida-2012-0540). URL: [http://dx.doi.org/10.3233/ida-2012-0540](http://dx.doi.org/10.3233/ida-2012-0540).

<a name=bib-Mora_2006></a>[[5]](#cite-Mora_2006) A. Mora, G. Aguilera, M. Enciso, et al. “A new closure algorithm based in logic: SLFD-Closure versus classical closures.” In: _INTELIGENCIA ARTIFICIAL_ 10.31 (Dec. 2006). ISSN: 1137-3601. DOI: [10.4114/ia.v10i31.935](https://doi.org/10.4114%2Fia.v10i31.935). URL: [http://dx.doi.org/10.4114/ia.v10i31.935](http://dx.doi.org/10.4114/ia.v10i31.935).

<a name=bib-Mora_2012></a>[[6]](#cite-Mora_2012) A. Mora, P. Cordero, M. Enciso, et al. “Closure via functional dependence simplification”. In: _International Journal of Computer Mathematics_ 89.4 (Mar. 2012), p. 510–526. ISSN: 1029-0265. DOI: [10.1080/00207160.2011.644275](https://doi.org/10.1080%2F00207160.2011.644275). URL: [http://dx.doi.org/10.1080/00207160.2011.644275](http://dx.doi.org/10.1080/00207160.2011.644275).

<a name=bib-Urbanova_2014></a>[[7]](#cite-Urbanova_2014) L. Urbanova and V. Vychodil. “Derivation digraphs for dependencies in ordinal and similarity-based data”. In: _Information Sciences_ 268 (Jun. 2014), p. 381–396. ISSN: 0020-0255. DOI: [10.1016/j.ins.2013.12.046](https://doi.org/10.1016%2Fj.ins.2013.12.046). URL: [http://dx.doi.org/10.1016/j.ins.2013.12.046](http://dx.doi.org/10.1016/j.ins.2013.12.046).

