---
title: '{MAT} Logic: {A} Temporal{\texttimes}Modal Logic with Non-deterministic Operators
  to Deal with Interactive Systems in Communication Technologies'
author:
- Gabriel Aguilera
- Alfredo Burrieza
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- Inmaculada Perez de Guzmán
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
date: '2006'
categories: uncategorised
slug: 2006/LoOpDeInSyCoTe
details: Advances in Artificial Intelligence - {IBERAMIA-SBIA} 2006, 2nd International
  Joint Conference, 10th Ibero-American Conference on AI, 18th Brazilian {AI} Symposium,
  Ribeir{\~{a}}o Preto, Brazil, October 23-27, 2006, Proceedings , Lecture Notes in
  Computer Science vol. 4140, pages 602--611.
doi: 10.1007/11874850_64
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Aguilera2006></a>[[Agu+06]](#cite-Aguilera2006) G. Aguilera, A. Burrieza, P. Cordero, et al. “MAT Logic: A Temporal×Modal Logic with Non-deterministic Operators to Deal with Interactive Systems in Communication Technologies”. In: _Advances in Artificial Intelligence - IBERAMIA-SBIA 2006, 2nd International Joint Conference, 10th Ibero-American Conference on AI, 18th Brazilian AI Symposium, Ribeir~ao Preto, Brazil, October 23-27, 2006, Proceedings_. Ed. by J. S. Sichman, H. Coelho and S. O. Rezende. Vol. 4140. Lecture Notes in Computer Science. Springer, 2006, pp. 602-611. DOI: [10.1007/11874850\_64](https://doi.org/10.1007%2F11874850%5C_64). URL: [https://doi.org/10.1007/11874850\_64](https://doi.org/10.1007/11874850\_64).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Aguilera2006,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Gabriel Aguilera and Alfredo Burrieza and Pablo Cordero and Inmaculada Perez {de Guzm{\a'a}n} and Emilio Mu~noz-Velasco},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Advances in Artificial Intelligence - {IBERAMIA-SBIA} 2006, 2nd International Joint Conference, 10th Ibero-American Conference on AI, 18th Brazilian {AI} Symposium, Ribeir{\~{a}}o Preto, Brazil, October 23-27, 2006, Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {{MAT} Logic: {A} Temporal{\texttimes}Modal Logic with Non-deterministic Operators to Deal with Interactive Systems in Communication Technologies},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2006},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Jaime Sim~ao Sichman and Helder Coelho and Solange Oliveira Rezende},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {602--611},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {4140},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/iberamia/AguileraBCGM06.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/11874850\_64},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 26 May 2023 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/11874850\_64},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/11874850_64" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/11874850_64" class="plumx-details" data-site="plum" data-hide-when-empty="true">{MAT} Logic: {A} Temporal{\texttimes}Modal Logic with Non-deterministic Operators to Deal with Interactive Systems in Communication Technologies</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1007/11874850_64"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Burrieza_2008></a>[[1]](#cite-Burrieza_2008) A. Burrieza, I. P. De Guzmán, and E. Muñoz-Velasco. “Generalization of some properties of relations in the context of functional temporal×modal logic”. In: _International Journal of Computer Mathematics_ 85.3–4 (Apr. 2008), p. 371–383. ISSN: 1029-0265. DOI: [10.1080/00207160701210141](https://doi.org/10.1080%2F00207160701210141). URL: [http://dx.doi.org/10.1080/00207160701210141](http://dx.doi.org/10.1080/00207160701210141).

<a name=bib-Burrieza_2017></a>[[2]](#cite-Burrieza_2017) A. Burrieza, I. Fortes, and I. P. de Guzmán. “Completeness of a functional system for surjective functions”. In: _Mathematical Logic Quarterly_ 63.6 (Dec. 2017), p. 574–597. ISSN: 1521-3870. DOI: [10.1002/malq.201600011](https://doi.org/10.1002%2Fmalq.201600011). URL: [http://dx.doi.org/10.1002/malq.201600011](http://dx.doi.org/10.1002/malq.201600011).

<a name=bib-Burrieza_2010></a>[[3]](#cite-Burrieza_2010) A. Burrieza, I. P. de Guzmán, and E. Muñoz‐Velasco. “Analyzing completeness of axiomatic functional systems for temporal × modal logics”. In: _Mathematical Logic Quarterly_ 56.1 (Jan. 2010), p. 89–102. ISSN: 1521-3870. DOI: [10.1002/malq.200810038](https://doi.org/10.1002%2Fmalq.200810038). URL: [http://dx.doi.org/10.1002/malq.200810038](http://dx.doi.org/10.1002/malq.200810038).

<a name=bib-Cabrera_2010></a>[[4]](#cite-Cabrera_2010) I. Cabrera, P. Cordero, G. Gutiérrez, et al. “A coalgebraic approach to non-determinism: Applications to multilattices”. In: _Information Sciences_ 180.22 (Nov. 2010), p. 4323–4335. ISSN: 0020-0255. DOI: [10.1016/j.ins.2010.07.002](https://doi.org/10.1016%2Fj.ins.2010.07.002). URL: [http://dx.doi.org/10.1016/j.ins.2010.07.002](http://dx.doi.org/10.1016/j.ins.2010.07.002).

<a name=bib-Sun_2017></a>[[5]](#cite-Sun_2017) M. Sun, J. Wu, C. Liu, et al. “The Method of Test Oracle Generation Based on Event Temporal Logic”. In: _2017 International Conference on Computer Technology, Electronics and Communication (ICCTEC)_. IEEE, Dec. 2017, p. 664–670. DOI: [10.1109/icctec.2017.00149](https://doi.org/10.1109%2Ficctec.2017.00149). URL: [http://dx.doi.org/10.1109/icctec.2017.00149](http://dx.doi.org/10.1109/icctec.2017.00149).

