---
author:
- Estrella Rodríguez-Lorenzo
- Karell Bertet
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/enciso/' style='color:rgb(100,0,50);'>Manuel Enciso</a>
- <a href='/people/staff/amora/' style='color:rgb(100,0,50);'>Ángel Mora</a>
Status: Published
date: '2018-11-20T00:00:00Z'
slug: 2018/BaCoMeFuSiRu
title: Direct-optimal basis computation by means of the fusion of simplification rules
categories:
- Simplification logic
- Formal concept analysis
header_image: ~
details: <em>Discrete Applied Mathematics</em> 249, pp. 106 - 119
doi: 10.1016/j.dam.2017.12.031
project: ~
keywords: Direct-optimal basis; Closure; Simplification Logic
---


# Abstract

The importance of the computation of direct bases of implications has been motivated by several authors in different areas. They emphasize the use of direct bases in several problems, where a large number of closures are needed. The more efficient the basis computation is, the better performance the methods solving these problems has. Here, we propose a new method, named SLgetdo, to calculate the direct-optimal basis. The main characteristic of SLgetdo is the full integration of simplification paradigm, providing a limited rise of the implicational set throughout its execution. We have showed the better behavior of SLgetdo in an empirical experiment. The general conclusion is that it improves the performance of previous methods, providing a better management of time and space resources.












# Citation
Please, cite this work as:


<a name=bib-RODRIGUEZLORENZO2018106></a>[[Rod+18]](#cite-RODRIGUEZLORENZO2018106) E. Rodríguez-Lorenzo, K. Bertet, P. Cordero, et al. “Direct-optimal basis computation by means of the fusion of simplification rules”. In: _Discrete Applied Mathematics_ 249 (2018). Concept Lattices and Applications: Recent Advances and New Opportunities, pp. 106-119. ISSN: 0166-218X. DOI: [https://doi.org/10.1016/j.dam.2017.12.031](https://doi.org/https%3A%2F%2Fdoi.org%2F10.1016%2Fj.dam.2017.12.031). URL: [https://www.sciencedirect.com/science/article/pii/S0166218X1730611X](https://www.sciencedirect.com/science/article/pii/S0166218X1730611X).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@article{RODRIGUEZLORENZO2018106,<br>&nbsp;&nbsp;&nbsp;&nbsp;title = {Direct-optimal basis computation by means of the fusion of simplification rules},<br>&nbsp;&nbsp;&nbsp;&nbsp;journal = {Discrete Applied Mathematics},<br>&nbsp;&nbsp;&nbsp;&nbsp;volume = {249},<br>&nbsp;&nbsp;&nbsp;&nbsp;pages = {106-119},<br>&nbsp;&nbsp;&nbsp;&nbsp;year = {2018},<br>&nbsp;&nbsp;&nbsp;&nbsp;note = {Concept Lattices and Applications: Recent Advances and New Opportunities},<br>&nbsp;&nbsp;&nbsp;&nbsp;issn = {0166-218X},<br>&nbsp;&nbsp;&nbsp;&nbsp;doi = {https://doi.org/10.1016/j.dam.2017.12.031},<br>&nbsp;&nbsp;&nbsp;&nbsp;url = {https://www.sciencedirect.com/science/article/pii/S0166218X1730611X},<br>&nbsp;&nbsp;&nbsp;&nbsp;author = {Estrella Rodríguez-Lorenzo and Karell Bertet and Pablo Cordero and Manuel Enciso and Ángel Mora},<br>&nbsp;&nbsp;&nbsp;&nbsp;keywords = {Direct-optimal basis, Closure, Simplification Logic},<br>&nbsp;&nbsp;&nbsp;&nbsp;abstract = {The importance of the computation of direct bases of implications has been motivated by several authors in different areas. They emphasize the use of direct bases in several problems, where a large number of closures are needed. The more efficient the basis computation is, the better performance the methods solving these problems has. Here, we propose a new method, named SLgetdo, to calculate the direct-optimal basis. The main characteristic of SLgetdo is the full integration of simplification paradigm, providing a limited rise of the implicational set throughout its execution. We have showed the better behavior of SLgetdo in an empirical experiment. The general conclusion is that it improves the performance of previous methods, providing a better management of time and space resources.}<br>}

:::



# Bibliometric data


The following data has been extracted from free resources such as [OpenAlex](https://openalex.org/) or [Dimensions](https://app.dimensions.ai/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1016/j.dam.2017.12.031" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1016/j.dam.2017.12.031" class="plumx-details" data-site="plum" data-hide-when-empty="true">Direct-optimal basis computation by means of the fusion of simplification rules</a></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Cordero_2022></a>[[1]](#cite-Cordero_2022) P. Cordero, M. Enciso, A. Mora, et al. “Interactive Search by Using Minimal Generators”. In: _Computational Intelligence and Mathematics for Tackling Complex Problems 2_. Springer International Publishing, 2022, p. 147–153. ISBN: 9783030888176. DOI: [10.1007/978-3-030-88817-6_17](https://doi.org/10.1007%2F978-3-030-88817-6_17). URL: [http://dx.doi.org/10.1007/978-3-030-88817-6_17](http://dx.doi.org/10.1007/978-3-030-88817-6_17).

<a name=bib-Cordero_2020></a>[[2]](#cite-Cordero_2020) P. Cordero, M. Enciso, Á. Mora, et al. “A Formal Concept Analysis Approach to Cooperative Conversational Recommendation”. In: _International Journal of Computational Intelligence Systems_ 13.1 (2020), p. 1243. ISSN: 1875-6883. DOI: [10.2991/ijcis.d.200806.001](https://doi.org/10.2991%2Fijcis.d.200806.001). URL: [http://dx.doi.org/10.2991/ijcis.d.200806.001](http://dx.doi.org/10.2991/ijcis.d.200806.001).

<a name=bib-Cornejo_2022></a>[[3]](#cite-Cornejo_2022) M. E. Cornejo, J. Medina, and C. Rubio-Manzano. “Formal Analysis of Solar Power and Weather Data”. In: _Computational Intelligence and Mathematics for Tackling Complex Problems 2_. Springer International Publishing, 2022, p. 81–89. ISBN: 9783030888176. DOI: [10.1007/978-3-030-88817-6_10](https://doi.org/10.1007%2F978-3-030-88817-6_10). URL: [http://dx.doi.org/10.1007/978-3-030-88817-6_10](http://dx.doi.org/10.1007/978-3-030-88817-6_10).

<a name=bib-Dubois_2025></a>[[4]](#cite-Dubois_2025) D. Dubois, J. Medina, and H. Prade. “Extracting attribute implications from a formal context: Unifying the basic approaches”. In: _Information Sciences_ 689 (Jan. 2025), p. 121419. ISSN: 0020-0255. DOI: [10.1016/j.ins.2024.121419](https://doi.org/10.1016%2Fj.ins.2024.121419). URL: [http://dx.doi.org/10.1016/j.ins.2024.121419](http://dx.doi.org/10.1016/j.ins.2024.121419).

<a name=bib-Dubois_2021></a>[[5]](#cite-Dubois_2021) D. Dubois, J. Medina, H. Prade, et al. “Disjunctive attribute dependencies in formal concept analysis under the epistemic view of formal contexts”. In: _Information Sciences_ 561 (Jun. 2021), p. 31–51. ISSN: 0020-0255. DOI: [10.1016/j.ins.2020.12.085](https://doi.org/10.1016%2Fj.ins.2020.12.085). URL: [http://dx.doi.org/10.1016/j.ins.2020.12.085](http://dx.doi.org/10.1016/j.ins.2020.12.085).

<a name=bib-L_pez_Rodr_guez_2021></a>[[6]](#cite-L_pez_Rodr_guez_2021) D. López-Rodríguez, E. Muñoz-Velasco, and M. Ojeda-Aciego. “Formal Methods in FCA and Big Data”. In: _Complex Data Analytics with Formal Concept Analysis_. Springer International Publishing, Dec. 2021, p. 201–224. ISBN: 9783030932787. DOI: [10.1007/978-3-030-93278-7_9](https://doi.org/10.1007%2F978-3-030-93278-7_9). URL: [http://dx.doi.org/10.1007/978-3-030-93278-7_9](http://dx.doi.org/10.1007/978-3-030-93278-7_9).

<a name=bib-Ojeda_Hern_ndez_2022></a>[[7]](#cite-Ojeda_Hern_ndez_2022) M. Ojeda-Hernández, I. P. Cabrera, and P. Cordero. “Quasi-closed elements in fuzzy posets”. In: _Journal of Computational and Applied Mathematics_ 404 (Apr. 2022), p. 113390. ISSN: 0377-0427. DOI: [10.1016/j.cam.2021.113390](https://doi.org/10.1016%2Fj.cam.2021.113390). URL: [http://dx.doi.org/10.1016/j.cam.2021.113390](http://dx.doi.org/10.1016/j.cam.2021.113390).

<a name=bib-Pattison_2021></a>[[8]](#cite-Pattison_2021) T. Pattison, M. Enciso, Á. Mora, et al. “Scalable Visual Analytics in FCA”. In: _Complex Data Analytics with Formal Concept Analysis_. Springer International Publishing, Dec. 2021, p. 167–200. ISBN: 9783030932787. DOI: [10.1007/978-3-030-93278-7_8](https://doi.org/10.1007%2F978-3-030-93278-7_8). URL: [http://dx.doi.org/10.1007/978-3-030-93278-7_8](http://dx.doi.org/10.1007/978-3-030-93278-7_8).

<a name=bib-P_rez_G_mez_2022></a>[[9]](#cite-P_rez_G_mez_2022) F. Pérez-Gámez, D. López-Rodríguez, P. Cordero, et al. “Simplifying Implications with Positive and Negative Attributes: A Logic-Based Approach”. In: _Mathematics_ 10.4 (Feb. 2022), p. 607. ISSN: 2227-7390. DOI: [10.3390/math10040607](https://doi.org/10.3390%2Fmath10040607). URL: [http://dx.doi.org/10.3390/math10040607](http://dx.doi.org/10.3390/math10040607).


