---
title: 'Tableau reductions: Towards an optimal decision procedure for the modal necessity'
author:
- Joanna Golinska-Pilarek
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
- <a href='/people/staff/amora/' style='color:rgb(100,0,50);'>Ángel Mora</a>
date: '2016'
categories: uncategorised
slug: 2016/TaToOpDePrMoNe
details: J. Appl. Log. vol. 17 , pages 14--24.
doi: 10.1016/J.JAL.2015.09.005
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-GolinskaPilarek2016></a>[[GMM16]](#cite-GolinskaPilarek2016) J. Golinska-Pilarek, E. Mu~noz-Velasco, and Á. Mora. “Tableau reductions: Towards an optimal decision procedure for the modal necessity”. In: _J. Appl. Log._ 17 (2016), pp. 14-24. DOI: [10.1016/J.JAL.2015.09.005](https://doi.org/10.1016%2FJ.JAL.2015.09.005). URL: [https://doi.org/10.1016/j.jal.2015.09.005](https://doi.org/10.1016/j.jal.2015.09.005).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{GolinskaPilarek2016,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Joanna Golinska-Pilarek and Emilio Mu~noz-Velasco and {\a'A}ngel Mora},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {J. Appl. Log.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Tableau reductions: Towards an optimal decision procedure for the modal necessity},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2016},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {14--24},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {17},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/japll/Golinska-Pilarek16.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1016/J.JAL.2015.09.005},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 23 Sep 2022 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1016/j.jal.2015.09.005},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1016/J.JAL.2015.09.005" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1016/J.JAL.2015.09.005" class="plumx-details" data-site="plum" data-hide-when-empty="true">Tableau reductions: Towards an optimal decision procedure for the modal necessity</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1016/J.JAL.2015.09.005"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Burrieza_2018></a>[[1]](#cite-Burrieza_2018) A. Burrieza, E. Muñoz-Velasco, and M. Ojeda-Aciego. “Logics for Order-of-Magnitude Qualitative Reasoning: Formalizing Negligibility”. In: _Ewa Orłowska on Relational Methods in Logic and Computer Science_. Springer International Publishing, 2018, p. 203–231. ISBN: 9783319978796. DOI: [10.1007/978-3-319-97879-6_8](https://doi.org/10.1007%2F978-3-319-97879-6_8). URL: [http://dx.doi.org/10.1007/978-3-319-97879-6_8](http://dx.doi.org/10.1007/978-3-319-97879-6_8).

