---
title: The number of t-norms on some special lattices
author:
- <a href='/people/staff/cbejines/' style='color:rgb(100,0,50);'>Carlos Bejines</a>
- Michaela Brutenicová
- María Jesús Chasco
- Jorge Elorza
- Vladimír Janis
date: '2021'
categories: uncategorised
slug: 2021/NuSpLa
details: Fuzzy Sets Syst. vol. 408 , pages 26--43.
doi: 10.1016/J.FSS.2020.03.014
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Bejines2021a></a>[[Bej+21]](#cite-Bejines2021a) C. Bejines, M. Brutenicová, M. Chasco, et al. “The number of t-norms on some special lattices”. In: _Fuzzy Sets Syst._ 408 (2021), pp. 26-43. DOI: [10.1016/J.FSS.2020.03.014](https://doi.org/10.1016%2FJ.FSS.2020.03.014). URL: [https://doi.org/10.1016/j.fss.2020.03.014](https://doi.org/10.1016/j.fss.2020.03.014).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{Bejines2021a,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Carlos Bejines and Michaela Brutenicov{\a'a} and Mar\'\ia Jes{\a'u}s Chasco and Jorge Elorza and Vladim\'\ir Janis},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Fuzzy Sets Syst.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {The number of t-norms on some special lattices},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2021},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {26--43},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {408},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/fss/BejinesBCEJ21.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1016/J.FSS.2020.03.014},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Sat, 30 Sep 2023 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1016/j.fss.2020.03.014},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1016/J.FSS.2020.03.014" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1016/J.FSS.2020.03.014" class="plumx-details" data-site="plum" data-hide-when-empty="true">The number of t-norms on some special lattices</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1016/J.FSS.2020.03.014"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Bejines_20221></a>[[1]](#cite-Bejines_20221) C. Bejines. “T-norms and t-conorms on a family of lattices”. In: _Fuzzy Sets and Systems_ 439 (Jul. 2022), p. 55–74. ISSN: 0165-0114. DOI: [10.1016/j.fss.2021.05.008](https://doi.org/10.1016%2Fj.fss.2021.05.008). URL: [http://dx.doi.org/10.1016/j.fss.2021.05.008](http://dx.doi.org/10.1016/j.fss.2021.05.008).

<a name=bib-Bejines_2022></a>[[2]](#cite-Bejines_2022) C. Bejines and M. Navara. “The Fibonacci sequence in the description of maximal discrete Archimedean t-norms”. In: _Fuzzy Sets and Systems_ 451 (Dec. 2022), p. 94–112. ISSN: 0165-0114. DOI: [10.1016/j.fss.2022.08.012](https://doi.org/10.1016%2Fj.fss.2022.08.012). URL: [http://dx.doi.org/10.1016/j.fss.2022.08.012](http://dx.doi.org/10.1016/j.fss.2022.08.012).

<a name=bib-Bejines_2023></a>[[3]](#cite-Bejines_2023) C. Bejines and M. Ojeda-Hernández. “Counting semicopulas on finite structures”. In: _Fuzzy Sets and Systems_ 462 (Jun. 2023), p. 108405. ISSN: 0165-0114. DOI: [10.1016/j.fss.2022.09.011](https://doi.org/10.1016%2Fj.fss.2022.09.011). URL: [http://dx.doi.org/10.1016/j.fss.2022.09.011](http://dx.doi.org/10.1016/j.fss.2022.09.011).

<a name=bib-Karmakar_2022></a>[[4]](#cite-Karmakar_2022) S. Karmakar and S. K. De. “A study of an EOQ model where the demand depends on time and varying number of tourists using fuzzy triangular norms”. In: _Journal of Ambient Intelligence and Humanized Computing_ 14.10 (Apr. 2022), p. 13543–13558. ISSN: 1868-5145. DOI: [10.1007/s12652-022-03821-0](https://doi.org/10.1007%2Fs12652-022-03821-0). URL: [http://dx.doi.org/10.1007/s12652-022-03821-0](http://dx.doi.org/10.1007/s12652-022-03821-0).

<a name=bib-Munar_2024></a>[[5]](#cite-Munar_2024) M. Munar, M. Couceiro, S. Massanet, et al. “A survey on the enumeration of classes of logical connectives and aggregation functions defined on a finite chain, with new results”. In: _Fuzzy Sets and Systems_ 490 (Aug. 2024), p. 109023. ISSN: 0165-0114. DOI: [10.1016/j.fss.2024.109023](https://doi.org/10.1016%2Fj.fss.2024.109023). URL: [http://dx.doi.org/10.1016/j.fss.2024.109023](http://dx.doi.org/10.1016/j.fss.2024.109023).

<a name=bib-Munar_2023></a>[[6]](#cite-Munar_2023) M. Munar, S. Massanet, and D. Ruiz-Aguilera. “A review on logical connectives defined on finite chains”. In: _Fuzzy Sets and Systems_ 462 (Jun. 2023), p. 108469. ISSN: 0165-0114. DOI: [10.1016/j.fss.2023.01.004](https://doi.org/10.1016%2Fj.fss.2023.01.004). URL: [http://dx.doi.org/10.1016/j.fss.2023.01.004](http://dx.doi.org/10.1016/j.fss.2023.01.004).

<a name=bib-Munar_20231></a>[[7]](#cite-Munar_20231) M. Munar, S. Massanet, and D. Ruiz-Aguilera. “A study on the cardinality of some families of discrete operators through alternating sign matrices”. In: _Information Sciences_ 639 (Aug. 2023), p. 118571. ISSN: 0020-0255. DOI: [10.1016/j.ins.2023.01.040](https://doi.org/10.1016%2Fj.ins.2023.01.040). URL: [http://dx.doi.org/10.1016/j.ins.2023.01.040](http://dx.doi.org/10.1016/j.ins.2023.01.040).

<a name=bib-Qiao_2022></a>[[8]](#cite-Qiao_2022) J. Qiao. “Constructions of quasi-overlap functions and their generalized forms on bounded partially ordered sets”. In: _Fuzzy Sets and Systems_ 446 (Oct. 2022), p. 68–92. ISSN: 0165-0114. DOI: [10.1016/j.fss.2021.03.004](https://doi.org/10.1016%2Fj.fss.2021.03.004). URL: [http://dx.doi.org/10.1016/j.fss.2021.03.004](http://dx.doi.org/10.1016/j.fss.2021.03.004).

