---
title: Scalable Visual Analytics in {FCA}
author:
- Tim Pattison
- <a href='/people/staff/enciso/' style='color:rgb(100,0,50);'>Manuel Enciso</a>
- <a href='/people/staff/amora/' style='color:rgb(100,0,50);'>Ángel Mora</a>
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- Derek Weber
- Michael Broughton
date: '2022'
categories: uncategorised
slug: 2022/ScViAn
details: Complex Data Analytics with Formal Concept Analysis , pages 167--200.
doi: 10.1007/978-3-030-93278-7_8
---



# Abstract


We adopt a visual analytic approach to FCA by combining computational analysis with interactive visualisation. Scaling FCA to the interactive analysis of large data sets poses four fundamental challenges: the time required to enumerate the vertices, arcs and labels of the lattice digraph; the difficulty of responsive presentation of, and meaningful user interaction with, a large digraph; the time required to enumerate (a basis for) all valid implications; and the discovery of insightful implications. This chapter briefly surveys potential solutions to these scalability challenges posed by big data volumes, and describes software prototypes and coordinated visualisations which explore some of them.








# Citation
Please, cite this work as:


<a name=bib-Pattison2022></a>[[Pat+22]](#cite-Pattison2022) T. Pattison, M. Enciso, Á. Mora, et al. “Scalable Visual Analytics in FCA”. In: _Complex Data Analytics with Formal Concept Analysis_. Ed. by R. Missaoui, L. Kwuida and T. Abdessalem. Springer International Publishing, 2022, pp. 167-200. DOI: [10.1007/978-3-030-93278-7\_8](https://doi.org/10.1007%2F978-3-030-93278-7%5C_8). URL: [https://doi.org/10.1007/978-3-030-93278-7\_8](https://doi.org/10.1007/978-3-030-93278-7\_8).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InCollection{Pattison2022,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Tim Pattison and Manuel Enciso and {\a'A}ngel Mora and Pablo Cordero and Derek Weber and Michael Broughton},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Complex Data Analytics with Formal Concept Analysis},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer International Publishing},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Scalable Visual Analytics in {FCA}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2022},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Rokia Missaoui and L{\a'e}onard Kwuida and Talel Abdessalem},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {167--200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {We adopt a visual analytic approach to FCA by combining computational analysis with interactive visualisation. Scaling FCA to the interactive analysis of large data sets poses four fundamental challenges: the time required to enumerate the vertices, arcs and labels of the lattice digraph; the difficulty of responsive presentation of, and meaningful user interaction with, a large digraph; the time required to enumerate (a basis for) all valid implications; and the discovery of insightful implications. This chapter briefly surveys potential solutions to these scalability challenges posed by big data volumes, and describes software prototypes and coordinated visualisations which explore some of them.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/books/sp/missaoui2022/PattisonEMCWB22.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/978-3-030-93278-7\_8},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Sun, 06 Oct 2024 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/978-3-030-93278-7\_8},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/978-3-030-93278-7_8" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/978-3-030-93278-7_8" class="plumx-details" data-site="plum" data-hide-when-empty="true">Scalable Visual Analytics in {FCA}</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1007/978-3-030-93278-7_8"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Pattison_2024></a>[[1]](#cite-Pattison_2024) T. Pattison. “Spanning Concept Trees: Algorithms and Interaction”. In: _Conceptual Knowledge Structures_. Springer Nature Switzerland, 2024, p. 166–181. ISBN: 9783031678684. DOI: [10.1007/978-3-031-67868-4_12](https://doi.org/10.1007%2F978-3-031-67868-4_12). URL: [http://dx.doi.org/10.1007/978-3-031-67868-4_12](http://dx.doi.org/10.1007/978-3-031-67868-4_12).

