---
title: Extending formal concept analysis using intuitionistic l-fuzzy sets
author:
- Ondrej Kridlo
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '2017'
categories: uncategorised
slug: 2017/ExFoCoAnUsInSe
details: 2017 {IEEE} International Conference on Fuzzy Systems, {FUZZ-IEEE} 2017,
  Naples, Italy, July 9-12, 2017 , pages 1--6.
doi: 10.1109/FUZZ-IEEE.2017.8015570
---



# Abstract


A two-fold general approach to the theory of formal concept analysis is introduced by considering intuitionistic fuzzy sets valued on a residuated lattice as underlying structure for the construction.








# Citation
Please, cite this work as:


<a name=bib-Kridlo2017></a>[[KO17]](#cite-Kridlo2017) O. Kridlo and M. Ojeda-Aciego. “Extending formal concept analysis using intuitionistic l-fuzzy sets”. In: _2017 IEEE International Conference on Fuzzy Systems, FUZZ-IEEE 2017, Naples, Italy, July 9-12, 2017_. IEEE, 2017, pp. 1-6. DOI: [10.1109/FUZZ-IEEE.2017.8015570](https://doi.org/10.1109%2FFUZZ-IEEE.2017.8015570). URL: [https://doi.org/10.1109/FUZZ-IEEE.2017.8015570](https://doi.org/10.1109/FUZZ-IEEE.2017.8015570).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Kridlo2017,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Ondrej Kridlo and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {2017 {IEEE} International Conference on Fuzzy Systems, {FUZZ-IEEE} 2017, Naples, Italy, July 9-12, 2017},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Extending formal concept analysis using intuitionistic l-fuzzy sets},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2017},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {1--6},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {{IEEE}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/fuzzIEEE/KridloO17.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1109/FUZZ-IEEE.2017.8015570},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Tue, 29 Dec 2020 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1109/FUZZ-IEEE.2017.8015570},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1109/FUZZ-IEEE.2017.8015570" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1109/FUZZ-IEEE.2017.8015570" class="plumx-details" data-site="plum" data-hide-when-empty="true">Extending formal concept analysis using intuitionistic l-fuzzy sets</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1109/FUZZ-IEEE.2017.8015570"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Gong_2024></a>[[1]](#cite-Gong_2024) Z. Gong and J. Zhang. “$$\delta $$-granular reduction in formal fuzzy contexts: Boolean reasoning, graph represent and their algorithms”. In: _Soft Computing_ 28.19 (Jul. 2024), p. 10873–10896. ISSN: 1433-7479. DOI: [10.1007/s00500-024-09875-w](https://doi.org/10.1007%2Fs00500-024-09875-w). URL: [http://dx.doi.org/10.1007/s00500-024-09875-w](http://dx.doi.org/10.1007/s00500-024-09875-w).

<a name=bib-Kridlo_2022></a>[[2]](#cite-Kridlo_2022) O. Kridlo and M. Ojeda-Aciego. “Classifying Adjoint Pairs and Adjoint Triples in an Atanassov $L$-Fuzzy Framework”. In: _IEEE Transactions on Fuzzy Systems_ 30.3 (Mar. 2022), p. 863–868. ISSN: 1941-0034. DOI: [10.1109/tfuzz.2020.3038482](https://doi.org/10.1109%2Ftfuzz.2020.3038482). URL: [http://dx.doi.org/10.1109/tfuzz.2020.3038482](http://dx.doi.org/10.1109/tfuzz.2020.3038482).

<a name=bib-Kridlo_2017></a>[[3]](#cite-Kridlo_2017) O. Kridlo and M. Ojeda-Aciego. “Towards intuitionistic L-fuzzy formal t-concepts”. In: _2017 Joint 17th World Congress of International Fuzzy Systems Association and 9th International Conference on Soft Computing and Intelligent Systems (IFSA-SCIS)_. IEEE, Jun. 2017, p. 1–6. DOI: [10.1109/ifsa-scis.2017.8023268](https://doi.org/10.1109%2Fifsa-scis.2017.8023268). URL: [http://dx.doi.org/10.1109/ifsa-scis.2017.8023268](http://dx.doi.org/10.1109/ifsa-scis.2017.8023268).

<a name=bib-Kr_dlo_2018></a>[[4]](#cite-Kr_dlo_2018) O. Krídlo and M. Ojeda-Aciego. “An Adjoint Pair for Intuitionistic L-Fuzzy Values”. In: _Trends in Mathematics and Computational Intelligence_. Springer International Publishing, Oct. 2018, p. 167–173. ISBN: 9783030004859. DOI: [10.1007/978-3-030-00485-9_19](https://doi.org/10.1007%2F978-3-030-00485-9_19). URL: [http://dx.doi.org/10.1007/978-3-030-00485-9_19](http://dx.doi.org/10.1007/978-3-030-00485-9_19).

<a name=bib-Liang_2022></a>[[5]](#cite-Liang_2022) M. Liang, J. Mi, T. Feng, et al. “Attribute reduction in intuitionistic fuzzy formal concepts”. In: _Journal of Intelligent &amp; Fuzzy Systems_ 43.3 (Jul. 2022), p. 3561–3573. ISSN: 1875-8967. DOI: [10.3233/jifs-202719](https://doi.org/10.3233%2Fjifs-202719). URL: [http://dx.doi.org/10.3233/jifs-202719](http://dx.doi.org/10.3233/jifs-202719).

<a name=bib-Zou_2021></a>[[6]](#cite-Zou_2021) L. Zou, H. Lin, X. Song, et al. “Rule extraction based on linguistic-valued intuitionistic fuzzy layered concept lattice”. In: _International Journal of Approximate Reasoning_ 133 (Jun. 2021), p. 1–16. ISSN: 0888-613X. DOI: [10.1016/j.ijar.2020.12.018](https://doi.org/10.1016%2Fj.ijar.2020.12.018). URL: [http://dx.doi.org/10.1016/j.ijar.2020.12.018](http://dx.doi.org/10.1016/j.ijar.2020.12.018).

