---
title: Computing Left-Minimal Direct Basis of implications
author:
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/enciso/' style='color:rgb(100,0,50);'>Manuel Enciso</a>
- <a href='/people/staff/amora/' style='color:rgb(100,0,50);'>Ángel Mora</a>
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '2013'
categories: uncategorised
slug: 2013/CoDiBaIm
details: Proceedings of the Tenth International Conference on Concept Lattices and
  Their Applications, La Rochelle, France, October 15-18, 2013 , {CEUR} Workshop Proceedings
  vol. 1062, pages 293--298.
---



# Abstract


The most popular basis in Formal Concept Analysis is the Duquenne-Guigues basis, which ensure minimality in the number of dependencies and it is built with pseudo-intents, and some method to calculate these basis from an arbitrary set of implications have been introduced. We propose in this paper, an automated method to calculate a left-minimal direct basis from the set of all implications built between a closed set and its corresponding minimal generators. The new basis also has the minimal property demanded in the Duquenne-Guigues basis. It is minimal in the cardinal of the set of implications, and minimal in the size of the left-hand side of the implications.








# Citation
Please, cite this work as:


<a name=bib-Cordero2013></a>[[Cor+13]](#cite-Cordero2013) P. Cordero, M. Enciso, Á. Mora, et al. “Computing Left-Minimal Direct Basis of implications”. In: _Proceedings of the Tenth International Conference on Concept Lattices and Their Applications, La Rochelle, France, October 15-18, 2013_. Ed. by M. Ojeda-Aciego and J. Outrata. Vol. 1062. CEUR Workshop Proceedings. CEUR-WS.org, 2013, pp. 293-298. URL: [https://ceur-ws.org/Vol-1062/paper\_short4.pdf](https://ceur-ws.org/Vol-1062/paper\_short4.pdf).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Cordero2013,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Pablo Cordero and Manuel Enciso and {\a'A}ngel Mora and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Proceedings of the Tenth International Conference on Concept Lattices and Their Applications, La Rochelle, France, October 15-18, 2013},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Computing Left-Minimal Direct Basis of implications},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2013},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Manuel Ojeda-Aciego and Jan Outrata},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {293--298},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {CEUR-WS.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {{CEUR} Workshop Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {1062},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {The most popular basis in Formal Concept Analysis is the Duquenne-Guigues basis, which ensure minimality in the number of dependencies and it is built with pseudo-intents, and some method to calculate these basis from an arbitrary set of implications have been introduced. We propose in this paper, an automated method to calculate a left-minimal direct basis from the set of all implications built between a closed set and its corresponding minimal generators. The new basis also has the minimal property demanded in the Duquenne-Guigues basis. It is minimal in the cardinal of the set of implications, and minimal in the size of the left-hand side of the implications.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/cla/CorderoEMO13.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 10 Mar 2023 16:22:10 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://ceur-ws.org/Vol-1062/paper\_short4.pdf},<br>}

:::








