---
title: Specification and inference of fuzzy attributes
author:
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/enciso/' style='color:rgb(100,0,50);'>Manuel Enciso</a>
- <a href='/people/staff/amora/' style='color:rgb(100,0,50);'>Ángel Mora</a>
- Inmaculada Perez de Guzmán
- José Manuel Rodríguez-Jiménez
date: '2011'
categories: uncategorised
slug: 2011/SpInFuAt
details: Proceedings of the {IEEE} Symposium on Foundations of Computational Intelligence,
  {FOCI} 2011, part of the {IEEE} Symposium Series on Computational Intelligence 2011,
  Paris, France, 11-15 April 2011 , pages 107--114.
doi: 10.1109/FOCI.2011.5949472
---



# Abstract


In this work, an extension of the database relational model which incorporates vague or imprecise data is presented. Specifically, we extend the concept of functional dependency to Fuzzy Attributes Tables. This extension is based on the use of a residuated lattice as a truthfulness value set. For this goal, the domains are enriched with fuzzy similarity relations, the atomic values of the tables become fuzzy, and the functional dependencies are also fuzzy and based on the similarity relations. Moreover, we introduce a sound and complete axiomatic system to manipulate these dependencies, named Simplification Logic for fuzzy functional dependencies.








# Citation
Please, cite this work as:


<a name=bib-Cordero2011></a>[[Cor+11]](#cite-Cordero2011) P. Cordero, M. Enciso, Á. Mora, et al. “Specification and inference of fuzzy attributes”. In: _Proceedings of the IEEE Symposium on Foundations of Computational Intelligence, FOCI 2011, part of the IEEE Symposium Series on Computational Intelligence 2011, Paris, France, 11-15 April 2011_. IEEE, 2011, pp. 107-114. DOI: [10.1109/FOCI.2011.5949472](https://doi.org/10.1109%2FFOCI.2011.5949472). URL: [https://doi.org/10.1109/FOCI.2011.5949472](https://doi.org/10.1109/FOCI.2011.5949472).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Cordero2011,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Pablo Cordero and Manuel Enciso and {\a'A}ngel Mora and Inmaculada Perez {de Guzm{\a'a}n} and Jos{\a'e} Manuel Rodr\'\iguez-Jim{\a'e}nez},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Proceedings of the {IEEE} Symposium on Foundations of Computational Intelligence, {FOCI} 2011, part of the {IEEE} Symposium Series on Computational Intelligence 2011, Paris, France, 11-15 April 2011},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Specification and inference of fuzzy attributes},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2011},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {107--114},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {{IEEE}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/foci/CorderoEMGR11.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1109/FOCI.2011.5949472},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 23 Sep 2022 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1109/FOCI.2011.5949472},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1109/FOCI.2011.5949472" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1109/FOCI.2011.5949472" class="plumx-details" data-site="plum" data-hide-when-empty="true">Specification and inference of fuzzy attributes</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1109/FOCI.2011.5949472"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Belohlavek_2013></a>[[1]](#cite-Belohlavek_2013) R. Belohlavek and V. Vychodil. “Relational algebra for multi-ranked similarity-based databases”. In: _2013 IEEE Symposium on Foundations of Computational Intelligence (FOCI)_. IEEE, Apr. 2013, p. 1–8. DOI: [10.1109/foci.2013.6602448](https://doi.org/10.1109%2Ffoci.2013.6602448). URL: [http://dx.doi.org/10.1109/foci.2013.6602448](http://dx.doi.org/10.1109/foci.2013.6602448).

<a name=bib-Je_kov__2017></a>[[2]](#cite-Je_kov__2017) L. Ježková, P. Cordero, and M. Enciso. “Fuzzy functional dependencies: A comparative survey”. In: _Fuzzy Sets and Systems_ 317 (Jun. 2017), p. 88–120. ISSN: 0165-0114. DOI: [10.1016/j.fss.2016.06.019](https://doi.org/10.1016%2Fj.fss.2016.06.019). URL: [http://dx.doi.org/10.1016/j.fss.2016.06.019](http://dx.doi.org/10.1016/j.fss.2016.06.019).

<a name=bib-Rodr_guez_Jim_nez_2013></a>[[3]](#cite-Rodr_guez_Jim_nez_2013) J. M. Rodríguez-Jiménez, P. Cordero, M. Enciso, et al. “Automated Inference with Fuzzy Functional Dependencies over Graded Data”. In: _Advances in Computational Intelligence_. Springer Berlin Heidelberg, 2013, p. 254–265. ISBN: 9783642386824. DOI: [10.1007/978-3-642-38682-4_29](https://doi.org/10.1007%2F978-3-642-38682-4_29). URL: [http://dx.doi.org/10.1007/978-3-642-38682-4_29](http://dx.doi.org/10.1007/978-3-642-38682-4_29).

<a name=bib-Rodriguez_Jimenez_2015></a>[[4]](#cite-Rodriguez_Jimenez_2015) J. Rodriguez-Jimenez, E. Rodriguez-Lorenzo, P. Cordero, et al. “A Normal Form for Fuzzy Functional Dependencies”. In: _2015 IEEE Symposium Series on Computational Intelligence_. IEEE, Dec. 2015, p. 984–989. DOI: [10.1109/ssci.2015.143](https://doi.org/10.1109%2Fssci.2015.143). URL: [http://dx.doi.org/10.1109/ssci.2015.143](http://dx.doi.org/10.1109/ssci.2015.143).

