---
title: Reduction Theorems for Boolean Formulas Using Delta-Trees
author:
- Gloria Gutiérrez
- <a href='/people/staff/ipguzman/' style='color:rgb(100,0,50);'>Inma P. de Guzmán</a>
- Javier Martínez
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
- Agustín Valverde
date: '2000'
categories: uncategorised
slug: 2000/ReThBoFoUs
details: Logics in Artificial Intelligence, European Workshop, {JELIA} 2000 Malaga,
  Spain, September 29 - October 2, 2000, Proceedings , Lecture Notes in Computer Science
  vol. 1919, pages 179--192.
doi: 10.1007/3-540-40006-0_13
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Gutierrez2000></a>[[Gut+00]](#cite-Gutierrez2000) G. Gutiérrez, I. P. de Guzmán, J. Mart\'\inez, et al. “Reduction Theorems for Boolean Formulas Using Delta-Trees”. In: _Logics in Artificial Intelligence, European Workshop, JELIA 2000 Malaga, Spain, September 29 - October 2, 2000, Proceedings_. Ed. by M. Ojeda-Aciego, I. P. de Guzmán, G. Brewka and L. Pereira. Vol. 1919. Lecture Notes in Computer Science. Springer, 2000, pp. 179-192. DOI: [10.1007/3-540-40006-0\_13](https://doi.org/10.1007%2F3-540-40006-0%5C_13). URL: [https://doi.org/10.1007/3-540-40006-0\_13](https://doi.org/10.1007/3-540-40006-0\_13).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Gutierrez2000,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Gloria Guti{\a'e}rrez and Inman P. {de Guzm{\a'a}n} and Javier Mart\'\inez and Manuel Ojeda-Aciego and Agust\'\in Valverde},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Logics in Artificial Intelligence, European Workshop, {JELIA} 2000 Malaga, Spain, September 29 - October 2, 2000, Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Reduction Theorems for Boolean Formulas Using Delta-Trees},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2000},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Manuel Ojeda-Aciego and Inman P. {de Guzm{\a'a}n} and Gerhard Brewka and Lu\'\is Moniz Pereira},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {179--192},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {1919},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/jelia/GutierrezGMOV00.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/3-540-40006-0\_13},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Tue, 29 Aug 2023 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/3-540-40006-0\_13},<br>}

:::






## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Cordero_2002></a>[[1]](#cite-Cordero_2002) P. Cordero, M. Enciso, and I. de Guzmán. “Bases for closed sets of implicants and implicates in temporal logic”. In: _Acta Informatica_ 38.9 (Aug. 2002), p. 599–619. ISSN: 1432-0525. DOI: [10.1007/s00236-002-0087-2](https://doi.org/10.1007%2Fs00236-002-0087-2). URL: [http://dx.doi.org/10.1007/s00236-002-0087-2](http://dx.doi.org/10.1007/s00236-002-0087-2).

<a name=bib-Cordero_2004></a>[[2]](#cite-Cordero_2004) P. Cordero, G. Gutiérrez, J. Martínez, et al. “A New Algebraic Tool for Automatic Theorem Provers”. In: _Annals of Mathematics and Artificial Intelligence_ 42.4 (Dec. 2004), p. 369–398. ISSN: 1012-2443. DOI: [10.1023/b:amai.0000038312.77514.3c](https://doi.org/10.1023%2Fb%3Aamai.0000038312.77514.3c). URL: [http://dx.doi.org/10.1023/b:amai.0000038312.77514.3c](http://dx.doi.org/10.1023/b:amai.0000038312.77514.3c).

<a name=bib-Mart_nez_2005></a>[[3]](#cite-Mart_nez_2005) J. Martínez, G. Gutiérrez, I. de Guzmán, et al. “Generalizations of lattices via non-deterministic operators”. In: _Discrete Mathematics_ 295.1–3 (May. 2005), p. 107–141. ISSN: 0012-365X. DOI: [10.1016/j.disc.2004.08.043](https://doi.org/10.1016%2Fj.disc.2004.08.043). URL: [http://dx.doi.org/10.1016/j.disc.2004.08.043](http://dx.doi.org/10.1016/j.disc.2004.08.043).

