---
title: Horn Fragments of the Halpern-Shoham Interval Temporal Logic
author:
- Davide Bresolin
- Agi Kurucz
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
- Vladislav Ryzhikov
- Guido Sciavicco
- Michael Zakharyaschev
date: '2017'
categories: uncategorised
slug: 2017/HoFrInTeLo
details: '{ACM} Trans. Comput. Log. vol. 18 (3), pages 22:1--22:39.'
doi: 10.1145/3105909
---



# Abstract


We investigate the satisfiability problem for Horn fragments of the Halpern-Shoham interval temporal logic depending on the type (box or diamond) of the interval modal operators, the type of the underlying linear order (discrete or dense), and the type of semantics for the interval relations (reflexive or irreflexive). For example, we show that satisfiability of Horn formulas with diamonds is undecidable for any type of linear orders and semantics. On the contrary, satisfiability of Horn formulas with boxes is tractable over both discrete and dense orders under the reflexive semantics and over dense orders under the irreflexive semantics but becomes undecidable over discrete orders under the irreflexive semantics. Satisfiability of binary Horn formulas with both boxes and diamonds is always undecidable under the irreflexive semantics.








# Citation
Please, cite this work as:


<a name=bib-Bresolin2017></a>[[Bre+17]](#cite-Bresolin2017) D. Bresolin, A. Kurucz, E. Mu~noz-Velasco, et al. “Horn Fragments of the Halpern-Shoham Interval Temporal Logic”. In: _ACM Trans. Comput. Log._ 18.3 (2017), pp. 22:1-22:39. DOI: [10.1145/3105909](https://doi.org/10.1145%2F3105909). URL: [https://doi.org/10.1145/3105909](https://doi.org/10.1145/3105909).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{Bresolin2017,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Davide Bresolin and Agi Kurucz and Emilio Mu~noz-Velasco and Vladislav Ryzhikov and Guido Sciavicco and Michael Zakharyaschev},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {{ACM} Trans. Comput. Log.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Horn Fragments of the Halpern-Shoham Interval Temporal Logic},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2017},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number = {3},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {22:1--22:39},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {18},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/tocl/BresolinKMRSZ17.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1145/3105909},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Sat, 30 Sep 2023 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1145/3105909},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1145/3105909" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1145/3105909" class="plumx-details" data-site="plum" data-hide-when-empty="true">Horn Fragments of the Halpern-Shoham Interval Temporal Logic</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1145/3105909"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Brandt_2017></a>[[1]](#cite-Brandt_2017) S. Brandt, E. Güzel Kalaycı, R. Kontchakov, et al. “Ontology-Based Data Access with a Horn Fragment of Metric Temporal Logic”. In: _Proceedings of the AAAI Conference on Artificial Intelligence_ 31.1 (Feb. 2017). ISSN: 2159-5399. DOI: [10.1609/aaai.v31i1.10696](https://doi.org/10.1609%2Faaai.v31i1.10696). URL: [http://dx.doi.org/10.1609/aaai.v31i1.10696](http://dx.doi.org/10.1609/aaai.v31i1.10696).

<a name=bib-Brandt_2018></a>[[2]](#cite-Brandt_2018) S. Brandt, E. G. Kalaycı, V. Ryzhikov, et al. “Querying Log Data with Metric Temporal Logic”. In: _Journal of Artificial Intelligence Research_ 62 (Aug. 2018), p. 829–877. ISSN: 1076-9757. DOI: [10.1613/jair.1.11229](https://doi.org/10.1613%2Fjair.1.11229). URL: [http://dx.doi.org/10.1613/jair.1.11229](http://dx.doi.org/10.1613/jair.1.11229).

<a name=bib-Bresolin_2017></a>[[3]](#cite-Bresolin_2017) D. Bresolin, A. Kurucz, E. Muñoz-Velasco, et al. “Horn Fragments of the Halpern-Shoham Interval Temporal Logic”. In: _ACM Transactions on Computational Logic_ 18.3 (Jul. 2017), p. 1–39. ISSN: 1557-945X. DOI: [10.1145/3105909](https://doi.org/10.1145%2F3105909). URL: [http://dx.doi.org/10.1145/3105909](http://dx.doi.org/10.1145/3105909).

<a name=bib-Bresolin_2016></a>[[4]](#cite-Bresolin_2016) D. Bresolin, E. Muñoz-Velasco, and G. Sciavicco. “On the Complexity of Fragments of Horn Modal Logics”. In: _2016 23rd International Symposium on Temporal Representation and Reasoning (TIME)_. IEEE, Oct. 2016, p. 186–195. DOI: [10.1109/time.2016.27](https://doi.org/10.1109%2Ftime.2016.27). URL: [http://dx.doi.org/10.1109/time.2016.27](http://dx.doi.org/10.1109/time.2016.27).

<a name=bib-Bresolin_20161></a>[[5]](#cite-Bresolin_20161) D. Bresolin, E. Muñoz-Velasco, and G. Sciavicco. “On the Expressive Power of Sub-Propositional Fragments of Modal Logic”. In: _Electronic Proceedings in Theoretical Computer Science_ 226 (Sep. 2016), p. 91–104. ISSN: 2075-2180. DOI: [10.4204/eptcs.226.7](https://doi.org/10.4204%2Feptcs.226.7). URL: [http://dx.doi.org/10.4204/eptcs.226.7](http://dx.doi.org/10.4204/eptcs.226.7).

<a name=bib-Conradie_2023></a>[[6]](#cite-Conradie_2023) W. Conradie, D. Della Monica, E. Muñoz-Velasco, et al. “Fuzzy Halpern and Shoham’s interval temporal logics”. In: _Fuzzy Sets and Systems_ 456 (Mar. 2023), p. 107–124. ISSN: 0165-0114. DOI: [10.1016/j.fss.2022.05.014](https://doi.org/10.1016%2Fj.fss.2022.05.014). URL: [http://dx.doi.org/10.1016/j.fss.2022.05.014](http://dx.doi.org/10.1016/j.fss.2022.05.014).

<a name=bib-Mu_oz_Velasco_2019></a>[[7]](#cite-Mu_oz_Velasco_2019) E. Muñoz-Velasco, M. Pelegrín, P. Sala, et al. “On coarser interval temporal logics”. In: _Artificial Intelligence_ 266 (Jan. 2019), p. 1–26. ISSN: 0004-3702. DOI: [10.1016/j.artint.2018.09.001](https://doi.org/10.1016%2Fj.artint.2018.09.001). URL: [http://dx.doi.org/10.1016/j.artint.2018.09.001](http://dx.doi.org/10.1016/j.artint.2018.09.001).

<a name=bib-Pagliarini_2024></a>[[8]](#cite-Pagliarini_2024) G. Pagliarini, S. Scaboro, G. Serra, et al. “Neural-symbolic temporal decision trees for multivariate time series classification”. In: _Information and Computation_ 301 (Dec. 2024), p. 105209. ISSN: 0890-5401. DOI: [10.1016/j.ic.2024.105209](https://doi.org/10.1016%2Fj.ic.2024.105209). URL: [http://dx.doi.org/10.1016/j.ic.2024.105209](http://dx.doi.org/10.1016/j.ic.2024.105209).

<a name=bib-Pagliarini_2021></a>[[9]](#cite-Pagliarini_2021) G. Pagliarini and G. Sciavicco. “Decision Tree Learning with Spatial Modal Logics”. In: _Electronic Proceedings in Theoretical Computer Science_ 346 (Sep. 2021), p. 273–290. ISSN: 2075-2180. DOI: [10.4204/eptcs.346.18](https://doi.org/10.4204%2Feptcs.346.18). URL: [http://dx.doi.org/10.4204/eptcs.346.18](http://dx.doi.org/10.4204/eptcs.346.18).

<a name=bib-Pagliarini_2023></a>[[10]](#cite-Pagliarini_2023) G. Pagliarini and G. Sciavicco. “Interpretable land cover classification with modal decision trees”. In: _European Journal of Remote Sensing_ 56.1 (Dec. 2023). ISSN: 2279-7254. DOI: [10.1080/22797254.2023.2262738](https://doi.org/10.1080%2F22797254.2023.2262738). URL: [http://dx.doi.org/10.1080/22797254.2023.2262738](http://dx.doi.org/10.1080/22797254.2023.2262738).

<a name=bib-Schneider_2020></a>[[11]](#cite-Schneider_2020) T. Schneider and M. Šimkus. “Ontologies and Data Management: A Brief Survey”. In: _KI - Künstliche Intelligenz_ 34.3 (Aug. 2020), p. 329–353. ISSN: 1610-1987. DOI: [10.1007/s13218-020-00686-3](https://doi.org/10.1007%2Fs13218-020-00686-3). URL: [http://dx.doi.org/10.1007/s13218-020-00686-3](http://dx.doi.org/10.1007/s13218-020-00686-3).

<a name=bib-Sciavicco_2019></a>[[12]](#cite-Sciavicco_2019) G. Sciavicco, I. E. Stan, and A. Vaccari. “Towards a General Method for Logical Rule Extraction from Time Series”. In: _From Bioinspired Systems and Biomedical Applications to Machine Learning_. Springer International Publishing, 2019, p. 3–12. ISBN: 9783030196516. DOI: [10.1007/978-3-030-19651-6_1](https://doi.org/10.1007%2F978-3-030-19651-6_1). URL: [http://dx.doi.org/10.1007/978-3-030-19651-6_1](http://dx.doi.org/10.1007/978-3-030-19651-6_1).

<a name=bib-Wa_ga_2016></a>[[13]](#cite-Wa_ga_2016) P. A. Wałęga. “Computational Complexity of a Hybridized Horn Fragment of Halpern-Shoham Logic”. In: _Logic and Its Applications_. Springer Berlin Heidelberg, Dec. 2016, p. 224–238. ISBN: 9783662540695. DOI: [10.1007/978-3-662-54069-5_17](https://doi.org/10.1007%2F978-3-662-54069-5_17). URL: [http://dx.doi.org/10.1007/978-3-662-54069-5_17](http://dx.doi.org/10.1007/978-3-662-54069-5_17).

<a name=bib-Wa_ga_20191></a>[[14]](#cite-Wa_ga_20191) P. A. Wałęga. “Computational Complexity of Core Fragments of Modal Logics T, K4, and S4”. In: _Logics in Artificial Intelligence_. Springer International Publishing, 2019, p. 744–759. ISBN: 9783030195700. DOI: [10.1007/978-3-030-19570-0_48](https://doi.org/10.1007%2F978-3-030-19570-0_48). URL: [http://dx.doi.org/10.1007/978-3-030-19570-0_48](http://dx.doi.org/10.1007/978-3-030-19570-0_48).

<a name=bib-Wa_ga_20231></a>[[15]](#cite-Wa_ga_20231) P. A. Wałęga. “Computational complexity of hybrid interval temporal logics”. In: _Annals of Pure and Applied Logic_ 174.1 (Jan. 2023), p. 103165. ISSN: 0168-0072. DOI: [10.1016/j.apal.2022.103165](https://doi.org/10.1016%2Fj.apal.2022.103165). URL: [http://dx.doi.org/10.1016/j.apal.2022.103165](http://dx.doi.org/10.1016/j.apal.2022.103165).

<a name=bib-Wa_ga_2019></a>[[16]](#cite-Wa_ga_2019) P. A. Wałęga. “Hybrid fragments of Halpern–Shoham logic and their expressive power”. In: _Theoretical Computer Science_ 797 (Dec. 2019), p. 102–128. ISSN: 0304-3975. DOI: [10.1016/j.tcs.2019.01.014](https://doi.org/10.1016%2Fj.tcs.2019.01.014). URL: [http://dx.doi.org/10.1016/j.tcs.2019.01.014](http://dx.doi.org/10.1016/j.tcs.2019.01.014).

<a name=bib-Wa_ga_2017></a>[[17]](#cite-Wa_ga_2017) P. A. Wałęga. “Searching for Well-Behaved Fragments of Halpern-Shoham Logic”. In: _Proceedings of the Twenty-Sixth International Joint Conference on Artificial Intelligence_. IJCAI-2017. International Joint Conferences on Artificial Intelligence Organization, Aug. 2017, p. 5219–5220. DOI: [10.24963/ijcai.2017/769](https://doi.org/10.24963%2Fijcai.2017%2F769). URL: [http://dx.doi.org/10.24963/ijcai.2017/769](http://dx.doi.org/10.24963/ijcai.2017/769).

<a name=bib-Wa_ga_2023></a>[[18]](#cite-Wa_ga_2023) P. A. Wałęga, M. Zawidzki, and C. Haase. “Computing All Facts Entailed By An LTL Specification”. In: _Proceedings of the Twentieth International Conference on Principles of Knowledge Representation and Reasoning_. KR-2023. International Joint Conferences on Artificial Intelligence Organization, Sep. 2023, p. 679–689. DOI: [10.24963/kr.2023/66](https://doi.org/10.24963%2Fkr.2023%2F66). URL: [http://dx.doi.org/10.24963/kr.2023/66](http://dx.doi.org/10.24963/kr.2023/66).

