---
title: Concept-Forming Operators on Multilattices
author:
- Jesús Medina-Moreno
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
- Jorge Ruiz-Calvi~no
date: '2013'
categories: uncategorised
slug: 2013/OpMu
details: Formal Concept Analysis, 11th International Conference, {ICFCA} 2013, Dresden,
  Germany, May 21-24, 2013. Proceedings , Lecture Notes in Computer Science vol. 7880,
  pages 203--215.
doi: 10.1007/978-3-642-38317-5_13
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-MedinaMoreno2013></a>[[MOR13]](#cite-MedinaMoreno2013) J. Medina-Moreno, M. Ojeda-Aciego, and J. Ruiz-Calvi~no. “Concept-Forming Operators on Multilattices”. In: _Formal Concept Analysis, 11th International Conference, ICFCA 2013, Dresden, Germany, May 21-24, 2013. Proceedings_. Ed. by P. Cellier, F. Distel and B. Ganter. Vol. 7880. Lecture Notes in Computer Science. Springer, 2013, pp. 203-215. DOI: [10.1007/978-3-642-38317-5\_13](https://doi.org/10.1007%2F978-3-642-38317-5%5C_13). URL: [https://doi.org/10.1007/978-3-642-38317-5\_13](https://doi.org/10.1007/978-3-642-38317-5\_13).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{MedinaMoreno2013,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Jes{\a'u}s Medina-Moreno and Manuel Ojeda-Aciego and Jorge Ruiz-Calvi~no},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Formal Concept Analysis, 11th International Conference, {ICFCA} 2013, Dresden, Germany, May 21-24, 2013. Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Concept-Forming Operators on Multilattices},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2013},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Peggy Cellier and Felix Distel and Bernhard Ganter},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {203--215},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {7880},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/icfca/Medina-MorenoOR13.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/978-3-642-38317-5\_13},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Sun, 06 Oct 2024 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/978-3-642-38317-5\_13},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/978-3-642-38317-5_13" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/978-3-642-38317-5_13" class="plumx-details" data-site="plum" data-hide-when-empty="true">Concept-Forming Operators on Multilattices</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1007/978-3-642-38317-5_13"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Ben_tez_Caballero_2018></a>[[1]](#cite-Ben_tez_Caballero_2018) M. J. Benítez-Caballero, J. Medina, E. Ramírez-Poussa, et al. “Bireducts with tolerance relations”. In: _Information Sciences_ 435 (Apr. 2018), p. 26–39. ISSN: 0020-0255. DOI: [10.1016/j.ins.2017.12.037](https://doi.org/10.1016%2Fj.ins.2017.12.037). URL: [http://dx.doi.org/10.1016/j.ins.2017.12.037](http://dx.doi.org/10.1016/j.ins.2017.12.037).

<a name=bib-Cornejo_2016></a>[[2]](#cite-Cornejo_2016) M. E. Cornejo, J. Medina, and E. Ramírez-Poussa. “Adjoint negations, more than residuated negations”. In: _Information Sciences_ 345 (Jun. 2016), p. 355–371. ISSN: 0020-0255. DOI: [10.1016/j.ins.2016.01.038](https://doi.org/10.1016%2Fj.ins.2016.01.038). URL: [http://dx.doi.org/10.1016/j.ins.2016.01.038](http://dx.doi.org/10.1016/j.ins.2016.01.038).

<a name=bib-httpsdoiorg1048550arxiv200803690></a>[[3]](#cite-httpsdoiorg1048550arxiv200803690) G. N. Dongmo, B. B. K. NJIONOU, L. Kwuida, et al. _Residuated Multilattice as set of Truth Values for Fuzzy Rough Sets_. 2020. DOI: [10.48550/ARXIV.2008.03690](https://doi.org/10.48550%2FARXIV.2008.03690). URL: [https://arxiv.org/abs/2008.03690](https://arxiv.org/abs/2008.03690).

<a name=bib-Garc_a_Pardo_2014></a>[[4]](#cite-Garc_a_Pardo_2014) F. García-Pardo, I. Cabrera, P. Cordero, et al. “On the definition of suitable orderings to generate adjunctions over an unstructured codomain”. In: _Information Sciences_ 286 (Dec. 2014), p. 173–187. ISSN: 0020-0255. DOI: [10.1016/j.ins.2014.07.006](https://doi.org/10.1016%2Fj.ins.2014.07.006). URL: [http://dx.doi.org/10.1016/j.ins.2014.07.006](http://dx.doi.org/10.1016/j.ins.2014.07.006).

<a name=bib-Koguep_Njionou_2023></a>[[5]](#cite-Koguep_Njionou_2023) B. B. Koguep Njionou, L. Kwuida, and C. Lele. “Formal Concepts and Residuation on Multilattices”. In: _Fundamenta Informaticae_ 188.4 (Jun. 2023), p. 217–237. ISSN: 1875-8681. DOI: [10.3233/fi-222147](https://doi.org/10.3233%2Ffi-222147). URL: [http://dx.doi.org/10.3233/fi-222147](http://dx.doi.org/10.3233/fi-222147).

<a name=bib-Kr_dlo_2016></a>[[6]](#cite-Kr_dlo_2016) O. Krídlo, S. Krajči, and L. Antoni. “Formal concept analysis of higher order”. In: _International Journal of General Systems_ 45.2 (Jan. 2016), p. 116–134. ISSN: 1563-5104. DOI: [10.1080/03081079.2015.1072924](https://doi.org/10.1080%2F03081079.2015.1072924). URL: [http://dx.doi.org/10.1080/03081079.2015.1072924](http://dx.doi.org/10.1080/03081079.2015.1072924).

<a name=bib-Medina_2016></a>[[7]](#cite-Medina_2016) J. Medina, M. Ojeda-Aciego, J. Pócs, et al. “On the Dedekind–MacNeille completion and formal concept analysis based on multilattices”. In: _Fuzzy Sets and Systems_ 303 (Nov. 2016), p. 1–20. ISSN: 0165-0114. DOI: [10.1016/j.fss.2016.01.007](https://doi.org/10.1016%2Fj.fss.2016.01.007). URL: [http://dx.doi.org/10.1016/j.fss.2016.01.007](http://dx.doi.org/10.1016/j.fss.2016.01.007).

<a name=bib-Nguepy_Dongmo_2024></a>[[8]](#cite-Nguepy_Dongmo_2024) G. Nguepy Dongmo, B. B. Koguep Njionou, L. Kwuida, et al. “Multilattice as the set of truth values for fuzzy rough sets”. In: _Journal of Applied Non-Classical Logics_ (Jul. 2024), p. 1–20. ISSN: 1958-5780. DOI: [10.1080/11663081.2024.2373016](https://doi.org/10.1080%2F11663081.2024.2373016). URL: [http://dx.doi.org/10.1080/11663081.2024.2373016](http://dx.doi.org/10.1080/11663081.2024.2373016).

<a name=bib-Nguepy_Dongmo_2023></a>[[9]](#cite-Nguepy_Dongmo_2023) G. Nguepy Dongmo, B. B. Koguep Njionou, L. Kwuida, et al. “Rough Fuzzy Concept Analysis via Multilattice”. In: _Rough Sets_. Springer Nature Switzerland, 2023, p. 495–508. ISBN: 9783031509599. DOI: [10.1007/978-3-031-50959-9_34](https://doi.org/10.1007%2F978-3-031-50959-9_34). URL: [http://dx.doi.org/10.1007/978-3-031-50959-9_34](http://dx.doi.org/10.1007/978-3-031-50959-9_34).

<a name=bib-Nguepy_Dongmo_2025></a>[[10]](#cite-Nguepy_Dongmo_2025) G. Nguepy Dongmo, B. Koguep Njionou, L. Kwuida, et al. “Roughness in formal concept analysis via multilattices”. In: _Fuzzy Sets and Systems_ 500 (Jan. 2025), p. 109179. ISSN: 0165-0114. DOI: [10.1016/j.fss.2024.109179](https://doi.org/10.1016%2Fj.fss.2024.109179). URL: [http://dx.doi.org/10.1016/j.fss.2024.109179](http://dx.doi.org/10.1016/j.fss.2024.109179).

<a name=bib-Shemis_2021></a>[[11]](#cite-Shemis_2021) E. Shemis and A. Mohammed. “A comprehensive review on updating concept lattices and its application in updating association rules”. In: _WIREs Data Mining and Knowledge Discovery_ 11.2 (Jan. 2021). ISSN: 1942-4795. DOI: [10.1002/widm.1401](https://doi.org/10.1002%2Fwidm.1401). URL: [http://dx.doi.org/10.1002/widm.1401](http://dx.doi.org/10.1002/widm.1401).

