---
title: Fuzzy closure systems over Heyting algebras as fixed points of a fuzzy Galois
  connection
author:
- <a href='/people/staff/manuojeda/' style='color:rgb(100,0,50);'>Manuel Ojeda Hernández</a>
- <a href='/people/staff/ipcabrera/' style='color:rgb(100,0,50);'>Inma P. Cabrera</a>
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
date: '2022'
categories: uncategorised
slug: 2022/FuClSyHeAlFiPoFuGaCo
details: Proceedings of the Sixteenth International Conference on Concept Lattices
  and Their Applications {(CLA} 2022) Tallinn, Estonia, June 20-22, 2022., Tallinn,
  Estonia, June 20-22, 2022 , {CEUR} Workshop Proceedings vol. 3308, pages 9--18.
---



# Abstract


Galois connections are useful to model solutions for both pure and application-oriented problems. Throughout the paper, the general framework is a complete fuzzy lattice over a Heyting algebra. We have established a fuzzy Galois connection between the fuzzy powerset lattice and the set of functions in 𝐴. Furthermore, the fixed points, or formal concepts, of this fuzzy Galois connection are exactly the fuzzy closure systems and fuzzy closure operators on 𝐴. The extension of this fuzzy Galois connection to the general framework is discussed but the study of the fixed points is still an open problem.








# Citation
Please, cite this work as:


<a name=bib-OjedaHernandez2022c></a>[[Oje+22]](#cite-OjedaHernandez2022c) M. Ojeda-Hernández, I. P. Cabrera, P. Cordero, et al. “Fuzzy closure systems over Heyting algebras as fixed points of a fuzzy Galois connection”. In: _Proceedings of the Sixteenth International Conference on Concept Lattices and Their Applications (CLA 2022) Tallinn, Estonia, June 20-22, 2022., Tallinn, Estonia, June 20-22, 2022_. Ed. by P. Cordero and O. Kr\'\idlo. Vol. 3308. CEUR Workshop Proceedings. CEUR-WS.org, 2022, pp. 9-18. URL: [https://ceur-ws.org/Vol-3308/Paper01.pdf](https://ceur-ws.org/Vol-3308/Paper01.pdf).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{OjedaHernandez2022c,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Manuel Ojeda-Hern{\a'a}ndez and Inma P. Cabrera and Pablo Cordero and Emilio Mu~noz-Velasco},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Proceedings of the Sixteenth International Conference on Concept Lattices and Their Applications {(CLA} 2022) Tallinn, Estonia, June 20-22, 2022., Tallinn, Estonia, June 20-22, 2022},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Fuzzy closure systems over Heyting algebras as fixed points of a fuzzy Galois connection},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2022},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Pablo Cordero and Ondrej Kr\'\idlo},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {9--18},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {CEUR-WS.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {{CEUR} Workshop Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {3308},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {Galois connections are useful to model solutions for both pure and application-oriented problems. Throughout the paper, the general framework is a complete fuzzy lattice over a Heyting algebra. We have established a fuzzy Galois connection between the fuzzy powerset lattice and the set of functions in 𝐴. Furthermore, the fixed points, or formal concepts, of this fuzzy Galois connection are exactly the fuzzy closure systems and fuzzy closure operators on 𝐴. The extension of this fuzzy Galois connection to the general framework is discussed but the study of the fixed points is still an open problem.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/cla/Ojeda-Hernandez22.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 10 Mar 2023 16:22:10 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://ceur-ws.org/Vol-3308/Paper01.pdf},<br>}

:::








