---
author: Domingo López-Rodríguez, E. Mérida-Casermeiro, G. Galán-Marín, J.M. Ortiz-de-Lazcano-Lobato
Status: Published
date: '2007-01-01'
slug: 2007-ki
title: 'Stochastic functional annealing as optimization technique: Application to
  the traveling salesman problem with recurrent networks'
categories:
- Neural networks
- Combinatorial optimization
header_image: ~
details: Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial
  Intelligence and Lecture Notes in Bioinformatics), (4667 LNAI), <em>pp. 397-411</em>
doi: 10.1007/978-3-540-74565-5_30
link: 2007-ki/paper.pdf
project: ''
keywords: Computational efficiency, Convergence of numerical methods, Finite difference
  method, Hopfield neural networks, Traveling salesman problem, Discrete neural networks,
  Stochastic functional annealing, Stochastic methods, Stochastic models
---


# Abstract


In this work, a new stochastic method for optimization problems is developed. Its theoretical bases guaranteeing the convergence of the method to a minimum of the objective function are presented, by using quite general hypotheses. Its application to recurrent discrete neural networks is also developed, focusing in the multivalued MREM model, a generalization of Hopfield's. In order to test the efficiency of this new method, we study the well-known Traveling Salesman Problem. Experimental results will show that this new model outperforms other techniques, achieving better results, even on average, than other methods. © Springer-Verlag Berlin Heidelberg 2007.







# Citation
Please, cite this work as:


<a name=bib-LopezRodriguez2007a></a>[[Lóp+07]](#cite-LopezRodriguez2007a) D. López-Rodríguez, E. Mérida-Casermeiro, G. Galán-Marín, et al. “Stochastic functional annealing as optimization technique: Application to the traveling salesman problem with recurrent networks”. In: _KI 2007: Advances in Artificial Intelligence, 30th Annual German Conference on AI, KI 2007, Osnabrück, Germany, September 10-13, 2007, Proceedings_. Ed. by J. Hertzberg, M. Beetz and R. Englert. Vol. 4667 LNAI. Lecture Notes in Computer Science. cited By 0; Conference of 30th Annual German Conference on Artificial Intelligence, KI 2007 ; Conference Date: 10 September 2007 Through 13 September 2007; Conference Code:70942. Osnabruck: Springer Verlag, 2007, pp. 397-411. DOI: [10.1007/978-3-540-74565-5_30](https://doi.org/10.1007%2F978-3-540-74565-5_30). URL:
[https://doi.org/10.1007/978-3-540-74565-5_30](https://doi.org/10.1007/978-3-540-74565-5_30).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{LopezRodriguez2007a,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {D. López-Rodríguez and E. Mérida-Casermeiro and G. Galán-Marín and J.M. Ortiz-de-Lazcano-Lobato},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {{KI} 2007: Advances in Artificial Intelligence, 30th Annual German Conference on AI, {KI} 2007, Osnabr{\"{u}}ck, Germany, September 10-13, 2007, Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Stochastic functional annealing as optimization technique: Application to the traveling salesman problem with recurrent networks},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2007},<br>&nbsp;&nbsp;&nbsp;&nbsp;  address = {Osnabruck},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Joachim Hertzberg and Michael Beetz and Roman Englert},<br>&nbsp;&nbsp;&nbsp;&nbsp;  note = {cited By 0; Conference of 30th Annual German Conference on Artificial Intelligence, KI 2007 ; Conference Date: 10 September 2007 Through 13 September 2007; Conference Code:70942},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {397-411},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer Verlag},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {4667 LNAI},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {In this work, a new stochastic method for optimization problems is developed. Its theoretical bases guaranteeing the convergence of the method to a minimum of the objective function are presented, by using quite general hypotheses. Its application to recurrent discrete neural networks is also developed, focusing in the multivalued MREM model, a generalization of Hopfield's. In order to test the efficiency of this new method, we study the well-known Traveling Salesman Problem. Experimental results will show that this new model outperforms other techniques, achieving better results, even on average, than other methods. © Springer-Verlag Berlin Heidelberg 2007.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/ki/Lopez-RodriguezCMO07.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  document_type = {Conference Paper},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/978-3-540-74565-5_30},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)},<br>&nbsp;&nbsp;&nbsp;&nbsp;  keywords = {Computational efficiency; Convergence of numerical methods; Finite difference method; Hopfield neural networks; Traveling salesman problem, Discrete neural networks; Stochastic functional annealing; Stochastic methods, Stochastic models},<br>&nbsp;&nbsp;&nbsp;&nbsp;  source = {Scopus},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/978-3-540-74565-5_30},<br>}

:::


