---
title: Aggregation of indistinguishability operators
author:
- <a href='/people/staff/cbejines/' style='color:rgb(100,0,50);'>Carlos Bejines</a>
- Sergio Ardanza-Trevijano
- María Jesús Chasco
- Jorge Elorza
date: '2022'
categories: uncategorised
slug: 2022/AgInOp
details: Fuzzy Sets Syst. vol. 446 , pages 53--67.
doi: 10.1016/J.FSS.2021.04.023
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Bejines2022a></a>[[Bej+22]](#cite-Bejines2022a) C. Bejines, S. Ardanza-Trevijano, M. Chasco, et al. “Aggregation of indistinguishability operators”. In: _Fuzzy Sets Syst._ 446 (2022), pp. 53-67. DOI: [10.1016/J.FSS.2021.04.023](https://doi.org/10.1016%2FJ.FSS.2021.04.023). URL: [https://doi.org/10.1016/j.fss.2021.04.023](https://doi.org/10.1016/j.fss.2021.04.023).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{Bejines2022a,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Carlos Bejines and Sergio Ardanza-Trevijano and Mar\'\ia Jes{\a'u}s Chasco and Jorge Elorza},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Fuzzy Sets Syst.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Aggregation of indistinguishability operators},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2022},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {53--67},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {446},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/fss/BejinesACE22.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1016/J.FSS.2021.04.023},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Mon, 28 Aug 2023 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1016/j.fss.2021.04.023},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1016/J.FSS.2021.04.023" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1016/J.FSS.2021.04.023" class="plumx-details" data-site="plum" data-hide-when-empty="true">Aggregation of indistinguishability operators</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1016/J.FSS.2021.04.023"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Bejines_2023></a>[[1]](#cite-Bejines_2023) C. Bejines. “Aggregation of fuzzy vector spaces”. In: _Kybernetika_ (Dec. 2023), p. 752–767. ISSN: 1805-949X. DOI: [10.14736/kyb-2023-5-0752](https://doi.org/10.14736%2Fkyb-2023-5-0752). URL: [http://dx.doi.org/10.14736/kyb-2023-5-0752](http://dx.doi.org/10.14736/kyb-2023-5-0752).

<a name=bib-Bejines_2021></a>[[2]](#cite-Bejines_2021) C. Bejines, S. Ardanza-Trevijano, and J. Elorza. “On Self-Aggregations of Min-Subgroups”. In: _Axioms_ 10.3 (Aug. 2021), p. 201. ISSN: 2075-1680. DOI: [10.3390/axioms10030201](https://doi.org/10.3390%2Faxioms10030201). URL: [http://dx.doi.org/10.3390/axioms10030201](http://dx.doi.org/10.3390/axioms10030201).

<a name=bib-Bejines_20231></a>[[3]](#cite-Bejines_20231) C. Bejines, D. López-Rodríguez, and M. Ojeda-Hernández. “Aggregation Functions and Extent Structure Preservation in Formal Concept Analysis”. In: _Graph-Based Representation and Reasoning_. Springer Nature Switzerland, 2023, p. 28–35. ISBN: 9783031409608. DOI: [10.1007/978-3-031-40960-8_3](https://doi.org/10.1007%2F978-3-031-40960-8_3). URL: [http://dx.doi.org/10.1007/978-3-031-40960-8_3](http://dx.doi.org/10.1007/978-3-031-40960-8_3).

<a name=bib-Gonz_lez_Hedstr_m_2021></a>[[4]](#cite-Gonz_lez_Hedstr_m_2021) J. González-Hedström, J. Miñana, and O. Valero. “Aggregation of Indistinguishability Fuzzy Relations Revisited”. In: _Mathematics_ 9.12 (Jun. 2021), p. 1441. ISSN: 2227-7390. DOI: [10.3390/math9121441](https://doi.org/10.3390%2Fmath9121441). URL: [http://dx.doi.org/10.3390/math9121441](http://dx.doi.org/10.3390/math9121441).

<a name=bib-Gonz_lez_Hedstr_m_2024></a>[[5]](#cite-Gonz_lez_Hedstr_m_2024) J. González-Hedström, J. Miñana, and O. Valero. “Fuzzy preorders and generalized distances: The aggregation problem revisited”. In: _Fuzzy Sets and Systems_ 474 (Jan. 2024), p. 108760. ISSN: 0165-0114. DOI: [10.1016/j.fss.2023.108760](https://doi.org/10.1016%2Fj.fss.2023.108760). URL: [http://dx.doi.org/10.1016/j.fss.2023.108760](http://dx.doi.org/10.1016/j.fss.2023.108760).

<a name=bib-Gonz_lez_Hedstr_m_2022></a>[[6]](#cite-Gonz_lez_Hedstr_m_2022) J. González-Hedström, J. Miñana, and O. Valero. “Relaxed Indistinguishability Relations and Relaxed Metrics: The Aggregation Problem”. In: _Axioms_ 11.9 (Aug. 2022), p. 431. ISSN: 2075-1680. DOI: [10.3390/axioms11090431](https://doi.org/10.3390%2Faxioms11090431). URL: [http://dx.doi.org/10.3390/axioms11090431](http://dx.doi.org/10.3390/axioms11090431).

<a name=bib-Talavera_2024></a>[[7]](#cite-Talavera_2024) F. J. Talavera, C. Bejines, S. Ardanza-Trevijano, et al. “Aggregation of fuzzy graphs”. In: _International Journal of Approximate Reasoning_ 172 (Sep. 2024), p. 109243. ISSN: 0888-613X. DOI: [10.1016/j.ijar.2024.109243](https://doi.org/10.1016%2Fj.ijar.2024.109243). URL: [http://dx.doi.org/10.1016/j.ijar.2024.109243](http://dx.doi.org/10.1016/j.ijar.2024.109243).

