---
author: Ángel Mora Bonilla, Enrique Mérida Casermeiro, Domingo López-Rodríguez
Status: Published
date: '2010-07-01'
slug: 2010-iceis
title: Improving Moodle with WIRIS and M-QIT
categories: E-learning
header_image: ~
details: <em>Proceedings of the 12th International Conference on Enterprise Information
  Systems</em>, Volume 4
doi: 10.5220/0002894500750080
link: 2010-iceis/paper.pdf
project: ~
keywords: ''
---


# Abstract


Moodle is one of the most extended LMS. Moodle allows the collaborative learning where students and teachers collaborate on the daily work. But problems with Moodle arise in our scientific context. Although Moodle can preview LaTeX code, not all the possibilities of LaTeX are available and it is very good for scientific teachers but hard for students, so, the mathematical formulas are usually replaced by non-standard versions of them written in ASCII. Another problem with Moodle is the difficulty of reusing quizzes. We present two tools that improve Moodle in three aspects: representation of math formulas, mathematical computation, and improving the learning units for the students. WIRIS is a powerful editor and allows interacting by using mathematic formulas in an easy way and developing new learning units with mathematical computation via web; M-QIT is a new tool able to manage and reutilize quizzes and questions available in previous courses in Moodle.







# Citation
Please, cite this work as:


<a name=bib-BonillaCL10></a>[[BCL10]](#cite-BonillaCL10) A. M. Bonilla, E. M. Casermeiro, and D. López-Rodríguez. “Improving Moodle with WIRIS and M-QIT”. In: _ICEIS 2010 - Proceedings of the 12th International Conference on Enterprise Information Systems, Volume 4, SAIC, Funchal, Madeira, Portugal, June 8 - 12, 2010_. Ed. by J. Filipe and J. Cordeiro. SciTePress, 2010, pp. 75-80.

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@inproceedings{BonillaCL10,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author    = {Angel Mora Bonilla and<br>&nbsp;&nbsp;&nbsp;&nbsp;               Enrique Mérida Casermeiro and<br>&nbsp;&nbsp;&nbsp;&nbsp;               Domingo López{-}Rodríguez},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor    = {Joaquim Filipe and<br>&nbsp;&nbsp;&nbsp;&nbsp;               José Cordeiro},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title     = {Improving Moodle with {WIRIS} and {M-QIT}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {{ICEIS} 2010 - Proceedings of the 12th International Conference on<br>&nbsp;&nbsp;&nbsp;&nbsp;               Enterprise Information Systems, Volume 4, SAIC, Funchal, Madeira,<br>&nbsp;&nbsp;&nbsp;&nbsp;               Portugal, June 8 - 12, 2010},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages     = {75--80},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {SciTePress},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year      = {2010},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Tue, 04 Jan 2011 09:39:17 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl    = {https://dblp.org/rec/conf/iceis/BonillaCL10.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org}<br>}

:::


