---
author:
- Ondrej Krídlo
- <a href='/people/staff/dominlopez/' style='color:rgb(100,0,50);'>Domingo López Rodríguez</a>
- Lubomir Antoni
- Peter Eliaš
- Stanislav Krajči
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
Status: Published
selected: yes
date: '2023-08-03T00:00:00Z'
slug: 2023/CoCoLaBoInExIn
title: Connecting concept lattices with bonds induced by external information
categories: Formal concept analysis
header_image: ~
details: <em>Information Sciences</em>, vol. 648, november 2023, article 119498
doi: 10.1016/j.ins.2023.119498
link: 2023-insci/paper.pdf
project: 2023-valid
keywords: Formal Concept Analysis, Intercontextual structures, Bonds
listing:
- id: funding
  contents: funding.yml
  type: default
  sort: date desc
---


# Abstract


In Formal Concept Analysis (FCA), $\mathcal L$-bonds represent relationships between $\mathcal L$-formal contexts. Choosing the appropriate bond between $\mathcal L$-fuzzy formal contexts is an important challenge for its application in recommendation tasks. Recent work introduced two constructions of bonds, given by direct products of two $\mathcal L$-fuzzy formal contexts, and showed their usefulness in a particular application. In this paper, we present further theoretical and experimental results on these constructions; in particular, we provide extended interpretations of both rigorous and benevolent concept-forming operators, introduce new theoretical properties of the proposed bonds to connect two concept lattices given external information, and finally present the experimental study of the upper bounds.




# Funding
::: {.callout-note appearance='minimal' collapse=false}
## Projects funding this work

:::{#funding}
:::
:::









# Citation
Please, cite this work as:


<a name=bib-insci2023></a>[[Krí+23]](#cite-insci2023) O. Krídlo, D. López-Rodríguez, L. Antoni, et al. “Connecting concept lattices with bonds induced by external information”. In: _Information Sciences_ (2023), p. 119498.

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@article{insci2023,<br>&nbsp;&nbsp;&nbsp;&nbsp;  title={Connecting concept lattices with bonds induced by external information},<br>&nbsp;&nbsp;&nbsp;&nbsp;  author={Ondrej Krídlo and Domingo López-Rodríguez and Lubomir Antoni and Peter Eliaš and Stanislav Krajči and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal={Information Sciences},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages={119498},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year={2023},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher={Elsevier}<br>}

:::



# Bibliometric data


The following data has been extracted from free resources such as [OpenAlex](https://openalex.org/) or [Dimensions](https://app.dimensions.ai/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1016/j.ins.2023.119498" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1016/j.ins.2023.119498" class="plumx-details" data-site="plum" data-hide-when-empty="true">Connecting concept lattices with bonds induced by external information</a></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Arag_n_2024></a>[[1]](#cite-Arag_n_2024) R. G. Aragón, J. Medina, and S. Molina-Ruiz. “The Notion of Bond in the Multi-adjoint Concept Lattice Framework”. In: _Advances in Artificial Intelligence_. Springer Nature Switzerland, 2024, p. 243–253. ISBN: 9783031627996. DOI: [10.1007/978-3-031-62799-6_25](https://doi.org/10.1007%2F978-3-031-62799-6_25). URL: [http://dx.doi.org/10.1007/978-3-031-62799-6_25](http://dx.doi.org/10.1007/978-3-031-62799-6_25).

<a name=bib-Dubois_2025></a>[[2]](#cite-Dubois_2025) D. Dubois, J. Medina, and H. Prade. “Extracting attribute implications from a formal context: Unifying the basic approaches”. In: _Information Sciences_ 689 (Jan. 2025), p. 121419. ISSN: 0020-0255. DOI: [10.1016/j.ins.2024.121419](https://doi.org/10.1016%2Fj.ins.2024.121419). URL: [http://dx.doi.org/10.1016/j.ins.2024.121419](http://dx.doi.org/10.1016/j.ins.2024.121419).


