---
title: An Axiomatic System for Conditional Attribute Implications in Triadic Concept
  Analysis
author:
- Estrella Rodríguez Lorenzo
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/enciso/' style='color:rgb(100,0,50);'>Manuel Enciso</a>
- Rokia Missaoui
- <a href='/people/staff/amora/' style='color:rgb(100,0,50);'>Ángel Mora</a>
date: '2017'
categories: uncategorised
slug: 2017/AxSyCoAtImTrCoAn
details: Int. J. Intell. Syst. vol. 32 (8), pages 760--777.
doi: 10.1002/INT.21888
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Lorenzo2017a></a>[[Rod+17]](#cite-Lorenzo2017a) E. Rodr\'\iguezLorenzo, P. Cordero, M. Enciso, et al. “An Axiomatic System for Conditional Attribute Implications in Triadic Concept Analysis”. In: _Int. J. Intell. Syst._ 32.8 (2017), pp. 760-777. DOI: [10.1002/INT.21888](https://doi.org/10.1002%2FINT.21888). URL: [https://doi.org/10.1002/int.21888](https://doi.org/10.1002/int.21888).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{Lorenzo2017a,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Estrella Rodr\'\iguez Lorenzo and Pablo Cordero and Manuel Enciso and Rokia Missaoui and {\a'A}ngel Mora},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Int. J. Intell. Syst.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {An Axiomatic System for Conditional Attribute Implications in Triadic Concept Analysis},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2017},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number = {8},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {760--777},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {32},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/ijis/LorenzoCEMB17.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1002/INT.21888},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Wed, 28 Sep 2022 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1002/int.21888},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1002/INT.21888" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1002/INT.21888" class="plumx-details" data-site="plum" data-hide-when-empty="true">An Axiomatic System for Conditional Attribute Implications in Triadic Concept Analysis</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1002/INT.21888"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Bazin_2020></a>[[1]](#cite-Bazin_2020) A. Bazin. “On implication bases in <mml:math xmlns:mml="http://www.w3.org/1998/Math/MathML" display="inline" overflow="scroll" id="d1e417" altimg="si6.gif"><mml:mi>n</mml:mi></mml:math>-lattices”. In: _Discrete Applied Mathematics_ 273 (Feb. 2020), p. 21–29. ISSN: 0166-218X. DOI: [10.1016/j.dam.2019.02.044](https://doi.org/10.1016%2Fj.dam.2019.02.044). URL: [http://dx.doi.org/10.1016/j.dam.2019.02.044](http://dx.doi.org/10.1016/j.dam.2019.02.044).

<a name=bib-P_rez_G_mez_2023></a>[[2]](#cite-P_rez_G_mez_2023) F. Pérez-Gámez, P. Cordero, M. Enciso, et al. “Simplification logic for the management of unknown information”. In: _Information Sciences_ 634 (Jul. 2023), p. 505–519. ISSN: 0020-0255. DOI: [10.1016/j.ins.2023.03.015](https://doi.org/10.1016%2Fj.ins.2023.03.015). URL: [http://dx.doi.org/10.1016/j.ins.2023.03.015](http://dx.doi.org/10.1016/j.ins.2023.03.015).

<a name=bib-Shao_2019></a>[[3]](#cite-Shao_2019) M. Shao, W. Wu, and C. Wang. “Axiomatic characterizations of adjoint generalized (dual) concept systems”. In: _Journal of Intelligent &amp; Fuzzy Systems_ 37.3 (Oct. 2019), p. 3629–3638. ISSN: 1875-8967. DOI: [10.3233/jifs-182612](https://doi.org/10.3233%2Fjifs-182612). URL: [http://dx.doi.org/10.3233/jifs-182612](http://dx.doi.org/10.3233/jifs-182612).

<a name=bib-Tang_2021></a>[[4]](#cite-Tang_2021) Y. Tang, Q. Fan, C. Chang, et al. “Construction Method of Triadic Concept Based on Linguistic Term Sets”. In: _2021 13th International Conference on Intelligent Human-Machine Systems and Cybernetics (IHMSC)_. IEEE, Aug. 2021, p. 186–189. DOI: [10.1109/ihmsc52134.2021.00050](https://doi.org/10.1109%2Fihmsc52134.2021.00050). URL: [http://dx.doi.org/10.1109/ihmsc52134.2021.00050](http://dx.doi.org/10.1109/ihmsc52134.2021.00050).

