---
title: 'QModeling: a Multiplatform, Easy-to-Use and Open-Source Toolbox for {PET}
  Kinetic Analysis'
author:
- Francisco Javier López-González
- José Paredes-Pacheco
- Karl Thurnhofer-Hemsi
- Carlos Rossi
- <a href='/people/staff/enciso/' style='color:rgb(100,0,50);'>Manuel Enciso</a>
- Daniel Toro-Flores
- Belén Murcia-Casas
- Antonio L. Gutiérrez-Cardo
- Núria Roé-Vellvé
date: '2019'
categories: uncategorised
slug: 2019/ToKiAn
details: Neuroinformatics vol. 17 (1), pages 103--114.
doi: 10.1007/S12021-018-9384-Y
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-LopezGonzalez2019></a>[[Lóp+19]](#cite-LopezGonzalez2019) F. J. López-González, J. Paredes-Pacheco, K. Thurnhofer-Hemsi, et al. “QModeling: a Multiplatform, Easy-to-Use and Open-Source Toolbox for PET Kinetic Analysis”. In: _Neuroinformatics_ 17.1 (2019), pp. 103-114. DOI: [10.1007/S12021-018-9384-Y](https://doi.org/10.1007%2FS12021-018-9384-Y). URL: [https://doi.org/10.1007/s12021-018-9384-y](https://doi.org/10.1007/s12021-018-9384-y).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{LopezGonzalez2019,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Francisco Javier L{\a'o}pez-Gonz{\a'a}lez and Jos{\a'e} Paredes-Pacheco and Karl Thurnhofer-Hemsi and Carlos Rossi and Manuel Enciso and Daniel Toro-Flores and Bel{\a'e}n Murcia-Casas and Antonio L. Guti{\a'e}rrez-Cardo and N{\a'u}ria Ro{\a'e}-Vellv{\a'e}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Neuroinformatics},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {QModeling: a Multiplatform, Easy-to-Use and Open-Source Toolbox for {PET} Kinetic Analysis},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2019},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number = {1},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {103--114},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {17},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/ni/Lopez-GonzalezP19.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/S12021-018-9384-Y},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Tue, 07 May 2024 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/s12021-018-9384-y},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/S12021-018-9384-Y" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/S12021-018-9384-Y" class="plumx-details" data-site="plum" data-hide-when-empty="true">QModeling: a Multiplatform, Easy-to-Use and Open-Source Toolbox for {PET} Kinetic Analysis</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1007/S12021-018-9384-Y"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Chen_2021></a>[[1]](#cite-Chen_2021) X. Chen, Y. Liu, D. Pan, et al. “68Ga-NOTA PET imaging for gastric emptying assessment in mice”. In: _BMC Gastroenterology_ 21.1 (Feb. 2021). ISSN: 1471-230X. DOI: [10.1186/s12876-021-01642-7](https://doi.org/10.1186%2Fs12876-021-01642-7). URL: [http://dx.doi.org/10.1186/s12876-021-01642-7](http://dx.doi.org/10.1186/s12876-021-01642-7).

<a name=bib-Chiotis_2023></a>[[2]](#cite-Chiotis_2023) K. Chiotis, C. Johansson, E. Rodriguez-Vieitez, et al. “Tracking reactive astrogliosis in autosomal dominant and sporadic Alzheimer’s disease with multi-modal PET and plasma GFAP”. In: _Molecular Neurodegeneration_ 18.1 (Sep. 2023). ISSN: 1750-1326. DOI: [10.1186/s13024-023-00647-y](https://doi.org/10.1186%2Fs13024-023-00647-y). URL: [http://dx.doi.org/10.1186/s13024-023-00647-y](http://dx.doi.org/10.1186/s13024-023-00647-y).

<a name=bib-Jiao_2023></a>[[3]](#cite-Jiao_2023) J. Jiao, F. Heeman, R. Dixon, et al. “NiftyPAD - Novel Python Package for Quantitative Analysis of Dynamic PET Data”. In: _Neuroinformatics_ 21.2 (Jan. 2023), p. 457–468. ISSN: 1559-0089. DOI: [10.1007/s12021-022-09616-0](https://doi.org/10.1007%2Fs12021-022-09616-0). URL: [http://dx.doi.org/10.1007/s12021-022-09616-0](http://dx.doi.org/10.1007/s12021-022-09616-0).

<a name=bib-Meindl_2024></a>[[4]](#cite-Meindl_2024) M. Meindl, A. Zatcepin, J. Gnörich, et al. “Assessment of [18F]PI-2620 Tau-PET Quantification via Non-Invasive Automatized Image Derived Input Function”. In: _European Journal of Nuclear Medicine and Molecular Imaging_ 51.11 (May. 2024), p. 3252–3266. ISSN: 1619-7089. DOI: [10.1007/s00259-024-06741-7](https://doi.org/10.1007%2Fs00259-024-06741-7). URL: [http://dx.doi.org/10.1007/s00259-024-06741-7](http://dx.doi.org/10.1007/s00259-024-06741-7).

<a name=bib-Puri_2022></a>[[5]](#cite-Puri_2022) T. Puri, M. L. Frost, A. E. B. Moore, et al. “Input function and modeling for determining bone metabolic flux using [18F] sodium fluoride PET imaging: A step‐by‐step guide”. In: _Medical Physics_ 50.4 (Dec. 2022), p. 2071–2088. ISSN: 2473-4209. DOI: [10.1002/mp.16125](https://doi.org/10.1002%2Fmp.16125). URL: [http://dx.doi.org/10.1002/mp.16125](http://dx.doi.org/10.1002/mp.16125).

<a name=bib-Rodriguez_Vieitez_2024></a>[[6]](#cite-Rodriguez_Vieitez_2024) E. Rodriguez-Vieitez, A. Kumar, M. Malarte, et al. “Imaging Neuroinflammation: Quantification of Astrocytosis in a Multitracer PET Approach”. In: _Biomarkers for Alzheimer’s Disease Drug Development_. Springer US, 2024, p. 195–218. ISBN: 9781071637746. DOI: [10.1007/978-1-0716-3774-6_13](https://doi.org/10.1007%2F978-1-0716-3774-6_13). URL: [http://dx.doi.org/10.1007/978-1-0716-3774-6_13](http://dx.doi.org/10.1007/978-1-0716-3774-6_13).

<a name=bib-Roemer_2024></a>[[7]](#cite-Roemer_2024) S. N. Roemer, M. Brendel, J. Gnörich, et al. “Subcortical tau is linked to hypoperfusion in connected cortical regions in 4-repeat tauopathies”. In: _Brain_ 147.7 (Jun. 2024), p. 2428–2439. ISSN: 1460-2156. DOI: [10.1093/brain/awae174](https://doi.org/10.1093%2Fbrain%2Fawae174). URL: [http://dx.doi.org/10.1093/brain/awae174](http://dx.doi.org/10.1093/brain/awae174).

<a name=bib-Sabaroedin_2022></a>[[8]](#cite-Sabaroedin_2022) K. Sabaroedin, A. Razi, S. Chopra, et al. “Frontostriatothalamic effective connectivity and dopaminergic function in the psychosis continuum”. In: _Brain_ 146.1 (Jan. 2022), p. 372–386. ISSN: 1460-2156. DOI: [10.1093/brain/awac018](https://doi.org/10.1093%2Fbrain%2Fawac018). URL: [http://dx.doi.org/10.1093/brain/awac018](http://dx.doi.org/10.1093/brain/awac018).

<a name=bib-Theis_2024></a>[[9]](#cite-Theis_2024) H. Theis, M. T. Barbe, A. Drzezga, et al. “Progressive Supranuclear Palsy: Subcortical Tau Depositions Are Associated with Cortical Perfusion in Frontal and Limbic Regions”. In: _Journal of Parkinson’s Disease_ 14.6 (Jul. 2024), p. 1271–1276. ISSN: 1877-718X. DOI: [10.3233/jpd-240210](https://doi.org/10.3233%2Fjpd-240210). URL: [http://dx.doi.org/10.3233/jpd-240210](http://dx.doi.org/10.3233/jpd-240210).

<a name=bib-Theis_2023></a>[[10]](#cite-Theis_2023) H. Theis, G. N. Bischof, N. Brüggemann, et al. “In Vivo Measurement of Tau Depositions in Anti-IgLON5 Disease Using [18F]PI-2620 PET”. In: _Neurology_ 101.22 (Nov. 2023). ISSN: 1526-632X. DOI: [10.1212/wnl.0000000000207870](https://doi.org/10.1212%2Fwnl.0000000000207870). URL: [http://dx.doi.org/10.1212/wnl.0000000000207870](http://dx.doi.org/10.1212/wnl.0000000000207870).

<a name=bib-Vizza_2024></a>[[11]](#cite-Vizza_2024) P. Vizza, E. Succurro, G. Pozzi, et al. “A Methodology to Measure Glucose Metabolism by Quantitative Analysis of PET Images”. In: _Journal of Healthcare Informatics Research_ 8.4 (Sep. 2024), p. 640–657. ISSN: 2509-498X. DOI: [10.1007/s41666-024-00172-7](https://doi.org/10.1007%2Fs41666-024-00172-7). URL: [http://dx.doi.org/10.1007/s41666-024-00172-7](http://dx.doi.org/10.1007/s41666-024-00172-7).

<a name=bib-Yun_2022></a>[[12]](#cite-Yun_2022) J. Yun and Y. Kim. “Deficits of Neurotransmitter Systems and Altered Brain Connectivity in Major Depression: A Translational Neuroscience Perspective”. In: _Translational Research Methods for Major Depressive Disorder_. Springer US, 2022, p. 311–324. ISBN: 9781071620830. DOI: [10.1007/978-1-0716-2083-0_14](https://doi.org/10.1007%2F978-1-0716-2083-0_14). URL: [http://dx.doi.org/10.1007/978-1-0716-2083-0_14](http://dx.doi.org/10.1007/978-1-0716-2083-0_14).

