---
title: Multi-adjoint Logic Programming with Continuous Semantics
author:
- Jesús Medina
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
- Peter Vojtás
date: '2001'
categories: uncategorised
slug: 2001/LoPrCoSe
details: Logic Programming and Nonmonotonic Reasoning, 6th International Conference,
  {LPNMR} 2001, Vienna, Austria, September 17-19, 2001, Proceedings , Lecture Notes
  in Computer Science vol. 2173, pages 351--364.
doi: 10.1007/3-540-45402-0_26
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Medina2001d></a>[[MOV01]](#cite-Medina2001d) J. Medina, M. Ojeda-Aciego, and P. Vojtás. “Multi-adjoint Logic Programming with Continuous Semantics”. In: _Logic Programming and Nonmonotonic Reasoning, 6th International Conference, LPNMR 2001, Vienna, Austria, September 17-19, 2001, Proceedings_. Ed. by T. Eiter, W. Faber and M. Truszczynski. Vol. 2173. Lecture Notes in Computer Science. Springer, 2001, pp. 351-364. DOI: [10.1007/3-540-45402-0\_26](https://doi.org/10.1007%2F3-540-45402-0%5C_26). URL: [https://doi.org/10.1007/3-540-45402-0\_26](https://doi.org/10.1007/3-540-45402-0\_26).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Medina2001d,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Jes{\a'u}s Medina and Manuel Ojeda-Aciego and Peter Vojt{\a'a}s},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Logic Programming and Nonmonotonic Reasoning, 6th International Conference, {LPNMR} 2001, Vienna, Austria, September 17-19, 2001, Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Multi-adjoint Logic Programming with Continuous Semantics},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2001},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Thomas Eiter and Wolfgang Faber and Miroslaw Truszczynski},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {351--364},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {2173},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/lpnmr/MedinaOV01.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/3-540-45402-0\_26},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Thu, 07 Jan 2021 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/3-540-45402-0\_26},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/3-540-45402-0_26" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/3-540-45402-0_26" class="plumx-details" data-site="plum" data-hide-when-empty="true">Multi-adjoint Logic Programming with Continuous Semantics</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1007/3-540-45402-0_26"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Antoni_2014></a>[[1]](#cite-Antoni_2014) L. Antoni, S. Krajči, O. Krídlo, et al. “On heterogeneous formal contexts”. In: _Fuzzy Sets and Systems_ 234 (Jan. 2014), p. 22–33. ISSN: 0165-0114. DOI: [10.1016/j.fss.2013.04.008](https://doi.org/10.1016%2Fj.fss.2013.04.008). URL: [http://dx.doi.org/10.1016/j.fss.2013.04.008](http://dx.doi.org/10.1016/j.fss.2013.04.008).

<a name=bib-Cornejo_2018></a>[[2]](#cite-Cornejo_2018) M. E. Cornejo, D. Lobo, and J. Medina. “Syntax and semantics of multi-adjoint normal logic programming”. In: _Fuzzy Sets and Systems_ 345 (Aug. 2018), p. 41–62. ISSN: 0165-0114. DOI: [10.1016/j.fss.2017.12.009](https://doi.org/10.1016%2Fj.fss.2017.12.009). URL: [http://dx.doi.org/10.1016/j.fss.2017.12.009](http://dx.doi.org/10.1016/j.fss.2017.12.009).

<a name=bib-Cornejo_2021></a>[[3]](#cite-Cornejo_2021) M. E. Cornejo, J. Medina, and E. Ramírez-Poussa. “Algebraic structure and characterization of adjoint triples”. In: _Fuzzy Sets and Systems_ 425 (Nov. 2021), p. 117–139. ISSN: 0165-0114. DOI: [10.1016/j.fss.2021.02.002](https://doi.org/10.1016%2Fj.fss.2021.02.002). URL: [http://dx.doi.org/10.1016/j.fss.2021.02.002](http://dx.doi.org/10.1016/j.fss.2021.02.002).

<a name=bib-Cornejo_2015></a>[[4]](#cite-Cornejo_2015) M. E. Cornejo, J. Medina, and E. Ramírez-Poussa. “Multi-adjoint algebras versus non-commutative residuated structures”. In: _International Journal of Approximate Reasoning_ 66 (Nov. 2015), p. 119–138. ISSN: 0888-613X. DOI: [10.1016/j.ijar.2015.08.003](https://doi.org/10.1016%2Fj.ijar.2015.08.003). URL: [http://dx.doi.org/10.1016/j.ijar.2015.08.003](http://dx.doi.org/10.1016/j.ijar.2015.08.003).

<a name=bib-Dam_sio_2004></a>[[5]](#cite-Dam_sio_2004) C. V. Damásio, J. Medina, and M. Ojeda-Aciego. “Sorted Multi-adjoint Logic Programs: Termination Results and Applications”. In: _Logics in Artificial Intelligence_. Springer Berlin Heidelberg, 2004, p. 252–265. ISBN: 9783540302278. DOI: [10.1007/978-3-540-30227-8_23](https://doi.org/10.1007%2F978-3-540-30227-8_23). URL: [http://dx.doi.org/10.1007/978-3-540-30227-8_23](http://dx.doi.org/10.1007/978-3-540-30227-8_23).

<a name=bib-Dam_sio_20011></a>[[6]](#cite-Dam_sio_20011) C. V. Damásio and L. M. Pereira. “Antitonic Logic Programs”. In: _Logic Programming and Nonmotonic Reasoning_. Springer Berlin Heidelberg, 2001, p. 379–393. ISBN: 9783540454021. DOI: [10.1007/3-540-45402-0_28](https://doi.org/10.1007%2F3-540-45402-0_28). URL: [http://dx.doi.org/10.1007/3-540-45402-0_28](http://dx.doi.org/10.1007/3-540-45402-0_28).

<a name=bib-Dam_sio_2001></a>[[7]](#cite-Dam_sio_2001) C. V. Damásio and L. M. Pereira. “Monotonic and Residuated Logic Programs”. In: _Symbolic and Quantitative Approaches to Reasoning with Uncertainty_. Springer Berlin Heidelberg, 2001, p. 748–759. ISBN: 9783540446521. DOI: [10.1007/3-540-44652-4_66](https://doi.org/10.1007%2F3-540-44652-4_66). URL: [http://dx.doi.org/10.1007/3-540-44652-4_66](http://dx.doi.org/10.1007/3-540-44652-4_66).

<a name=bib-D_az_2013></a>[[8]](#cite-D_az_2013) J. C. Díaz and J. Medina. “Multi-adjoint relation equations: Definition, properties and solutions using concept lattices”. In: _Information Sciences_ 253 (Dec. 2013), p. 100–109. ISSN: 0020-0255. DOI: [10.1016/j.ins.2013.07.024](https://doi.org/10.1016%2Fj.ins.2013.07.024). URL: [http://dx.doi.org/10.1016/j.ins.2013.07.024](http://dx.doi.org/10.1016/j.ins.2013.07.024).

<a name=bib-Dubois_2007></a>[[9]](#cite-Dubois_2007) D. Dubois, F. Esteva, L. Godo, et al. “Fuzzy-Set Based Logics — an History-Oriented Presentation of their Main Developments”. In: _The Many Valued and Nonmonotonic Turn in Logic_. Elsevier, 2007, p. 325–449. ISBN: 9780444516237. DOI: [10.1016/s1874-5857(07)80009-4](https://doi.org/10.1016%2Fs1874-5857%2807%2980009-4). URL: [http://dx.doi.org/10.1016/s1874-5857(07)80009-4](http://dx.doi.org/10.1016/s1874-5857(07)80009-4).

<a name=bib-Eugenia_Cornejo_2013></a>[[10]](#cite-Eugenia_Cornejo_2013) M. Eugenia Cornejo, J. Medina, and E. Ramírez. “A comparative study of adjoint triples”. In: _Fuzzy Sets and Systems_ 211 (Jan. 2013), p. 1–14. ISSN: 0165-0114. DOI: [10.1016/j.fss.2012.05.004](https://doi.org/10.1016%2Fj.fss.2012.05.004). URL: [http://dx.doi.org/10.1016/j.fss.2012.05.004](http://dx.doi.org/10.1016/j.fss.2012.05.004).

<a name=bib-Gerla_2005></a>[[11]](#cite-Gerla_2005) G. Gerla. “Fuzzy Logic Programming and Fuzzy Control”. In: _Studia Logica_ 79.2 (Mar. 2005), p. 231–254. ISSN: 1572-8730. DOI: [10.1007/s11225-005-2977-0](https://doi.org/10.1007%2Fs11225-005-2977-0). URL: [http://dx.doi.org/10.1007/s11225-005-2977-0](http://dx.doi.org/10.1007/s11225-005-2977-0).

<a name=bib-Guadarrama_2004></a>[[12]](#cite-Guadarrama_2004) S. Guadarrama, S. Muñoz, and C. Vaucheret. “Fuzzy Prolog: a new approach using soft constraints propagation”. In: _Fuzzy Sets and Systems_ 144.1 (May. 2004), p. 127–150. ISSN: 0165-0114. DOI: [10.1016/j.fss.2003.10.017](https://doi.org/10.1016%2Fj.fss.2003.10.017). URL: [http://dx.doi.org/10.1016/j.fss.2003.10.017](http://dx.doi.org/10.1016/j.fss.2003.10.017).

<a name=bib-Juli_n_Iranzo_2015></a>[[13]](#cite-Juli_n_Iranzo_2015) P. Julián-Iranzo and C. Rubio-Manzano. “Proximity-based unification theory”. In: _Fuzzy Sets and Systems_ 262 (Mar. 2015), p. 21–43. ISSN: 0165-0114. DOI: [10.1016/j.fss.2014.07.006](https://doi.org/10.1016%2Fj.fss.2014.07.006). URL: [http://dx.doi.org/10.1016/j.fss.2014.07.006](http://dx.doi.org/10.1016/j.fss.2014.07.006).

<a name=bib-Juli_n_2005></a>[[14]](#cite-Juli_n_2005) P. Julián, G. Moreno, and J. Penabad. “On fuzzy unfolding: A multi-adjoint approach”. In: _Fuzzy Sets and Systems_ 154.1 (Aug. 2005), p. 16–33. ISSN: 0165-0114. DOI: [10.1016/j.fss.2005.03.013](https://doi.org/10.1016%2Fj.fss.2005.03.013). URL: [http://dx.doi.org/10.1016/j.fss.2005.03.013](http://dx.doi.org/10.1016/j.fss.2005.03.013).

<a name=bib-Lobo_2023></a>[[15]](#cite-Lobo_2023) D. Lobo, V. López‐Marchante, and J. Medina. “On the impact of sup‐compositions in the resolution of multi‐adjoint relation equations”. In: _Mathematical Methods in the Applied Sciences_ 46.14 (Jun. 2023), p. 15581–15598. ISSN: 1099-1476. DOI: [10.1002/mma.9414](https://doi.org/10.1002%2Fmma.9414). URL: [http://dx.doi.org/10.1002/mma.9414](http://dx.doi.org/10.1002/mma.9414).

<a name=bib-Madrid_2011></a>[[16]](#cite-Madrid_2011) N. Madrid and M. Ojeda-Aciego. “Measuring Inconsistency in Fuzzy Answer Set Semantics”. In: _IEEE Transactions on Fuzzy Systems_ 19.4 (Aug. 2011), p. 605–622. ISSN: 1941-0034. DOI: [10.1109/tfuzz.2011.2114669](https://doi.org/10.1109%2Ftfuzz.2011.2114669). URL: [http://dx.doi.org/10.1109/tfuzz.2011.2114669](http://dx.doi.org/10.1109/tfuzz.2011.2114669).

<a name=bib-Medina_2012></a>[[17]](#cite-Medina_2012) J. Medina. “Multi-adjoint property-oriented and object-oriented concept lattices”. In: _Information Sciences_ 190 (May. 2012), p. 95–106. ISSN: 0020-0255. DOI: [10.1016/j.ins.2011.11.016](https://doi.org/10.1016%2Fj.ins.2011.11.016). URL: [http://dx.doi.org/10.1016/j.ins.2011.11.016](http://dx.doi.org/10.1016/j.ins.2011.11.016).

<a name=bib-Medina_2007></a>[[18]](#cite-Medina_2007) J. Medina, M. Ojeda-Aciego, and J. Ruiz-Calviño. “Fuzzy logic programming via multilattices”. In: _Fuzzy Sets and Systems_ 158.6 (Mar. 2007), p. 674–688. ISSN: 0165-0114. DOI: [10.1016/j.fss.2006.11.006](https://doi.org/10.1016%2Fj.fss.2006.11.006). URL: [http://dx.doi.org/10.1016/j.fss.2006.11.006](http://dx.doi.org/10.1016/j.fss.2006.11.006).

<a name=bib-Medina_2004></a>[[19]](#cite-Medina_2004) J. Medina, M. Ojeda-Aciego, A. Valverde, et al. “Towards Biresiduated Multi-adjoint Logic Programming”. In: _Current Topics in Artificial Intelligence_. Springer Berlin Heidelberg, 2004, p. 608–617. ISBN: 9783540259459. DOI: [10.1007/978-3-540-25945-9_60](https://doi.org/10.1007%2F978-3-540-25945-9_60). URL: [http://dx.doi.org/10.1007/978-3-540-25945-9_60](http://dx.doi.org/10.1007/978-3-540-25945-9_60).

<a name=bib-Medina_2001></a>[[20]](#cite-Medina_2001) J. Medina, M. Ojeda-Aciego, and P. Vojtáš. “A Procedural Semantics for Multi-adjoint Logic Programming”. In: _Progress in Artificial Intelligence_. Springer Berlin Heidelberg, 2001, p. 290–297. ISBN: 9783540453291. DOI: [10.1007/3-540-45329-6_29](https://doi.org/10.1007%2F3-540-45329-6_29). URL: [http://dx.doi.org/10.1007/3-540-45329-6_29](http://dx.doi.org/10.1007/3-540-45329-6_29).

<a name=bib-Medina_20041></a>[[21]](#cite-Medina_20041) J. Medina, M. Ojeda-Aciego, and P. Vojtáš. “Similarity-based unification: a multi-adjoint approach”. In: _Fuzzy Sets and Systems_ 146.1 (Aug. 2004), p. 43–62. ISSN: 0165-0114. DOI: [10.1016/j.fss.2003.11.005](https://doi.org/10.1016%2Fj.fss.2003.11.005). URL: [http://dx.doi.org/10.1016/j.fss.2003.11.005](http://dx.doi.org/10.1016/j.fss.2003.11.005).

<a name=bib-Morcillo_2010></a>[[22]](#cite-Morcillo_2010) P. J. Morcillo, G. Moreno, J. Penabad, et al. “A Practical Management of Fuzzy Truth-Degrees Using FLOPER”. In: _Semantic Web Rules_. Springer Berlin Heidelberg, 2010, p. 20–34. ISBN: 9783642162893. DOI: [10.1007/978-3-642-16289-3_4](https://doi.org/10.1007%2F978-3-642-16289-3_4). URL: [http://dx.doi.org/10.1007/978-3-642-16289-3_4](http://dx.doi.org/10.1007/978-3-642-16289-3_4).

<a name=bib-Moreno_2014></a>[[23]](#cite-Moreno_2014) G. Moreno and C. Vázquez. “Fuzzy Logic Programming in Action with &amp;lt;i&amp;gt;FLOPER&amp;lt;/i&amp;gt;”. In: _Journal of Software Engineering and Applications_ 07.04 (2014), p. 273–298. ISSN: 1945-3124. DOI: [10.4236/jsea.2014.74028](https://doi.org/10.4236%2Fjsea.2014.74028). URL: [http://dx.doi.org/10.4236/jsea.2014.74028](http://dx.doi.org/10.4236/jsea.2014.74028).

<a name=bib-Munoz_Hernandez_2011></a>[[24]](#cite-Munoz_Hernandez_2011) S. Munoz-Hernandez, V. Pablos-Ceruelo, and H. Strass. “RFuzzy: Syntax, semantics and implementation details of a simple and expressive fuzzy tool over Prolog”. In: _Information Sciences_ 181.10 (May. 2011), p. 1951–1970. ISSN: 0020-0255. DOI: [10.1016/j.ins.2010.07.033](https://doi.org/10.1016%2Fj.ins.2010.07.033). URL: [http://dx.doi.org/10.1016/j.ins.2010.07.033](http://dx.doi.org/10.1016/j.ins.2010.07.033).

<a name=bib-Straccia_2008></a>[[25]](#cite-Straccia_2008) U. Straccia. “Managing Uncertainty and Vagueness in Description Logics, Logic Programs and Description Logic Programs”. In: _Reasoning Web_. Springer Berlin Heidelberg, 2008, p. 54–103. ISBN: 9783540856580. DOI: [10.1007/978-3-540-85658-0_2](https://doi.org/10.1007%2F978-3-540-85658-0_2). URL: [http://dx.doi.org/10.1007/978-3-540-85658-0_2](http://dx.doi.org/10.1007/978-3-540-85658-0_2).

