---
title: 'Multi-adjoint Logic Programming: {A} Neural Net Approach'
author:
- Jesús Medina
- Enrique Mérida Casermeiro
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '2002'
categories: uncategorised
slug: 2002/LoNeNeAp
details: Logic Programming, 18th International Conference, {ICLP} 2002, Copenhagen,
  Denmark, July 29 - August 1, 2002, Proceedings , Lecture Notes in Computer Science
  vol. 2401, pages 468.
doi: 10.1007/3-540-45619-8_33
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Medina2002a></a>[[MCO02]](#cite-Medina2002a) J. Medina, E. M. Casermeiro, and M. Ojeda-Aciego. “Multi-adjoint Logic Programming: A Neural Net Approach”. In: _Logic Programming, 18th International Conference, ICLP 2002, Copenhagen, Denmark, July 29 - August 1, 2002, Proceedings_. Ed. by P. J. Stuckey. Vol. 2401. Lecture Notes in Computer Science. Springer, 2002, p. 468. DOI: [10.1007/3-540-45619-8\_33](https://doi.org/10.1007%2F3-540-45619-8%5C_33). URL: [https://doi.org/10.1007/3-540-45619-8\_33](https://doi.org/10.1007/3-540-45619-8\_33).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Medina2002a,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Jes{\a'u}s Medina and Enrique M{\a'e}rida Casermeiro and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Logic Programming, 18th International Conference, {ICLP} 2002, Copenhagen, Denmark, July 29 - August 1, 2002, Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Multi-adjoint Logic Programming: {A} Neural Net Approach},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2002},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Peter J. Stuckey},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {468},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {2401},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/iclp/MedinaCO02.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/3-540-45619-8\_33},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Thu, 07 Jan 2021 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/3-540-45619-8\_33},<br>}

:::






## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Medina_2002></a>[[1]](#cite-Medina_2002) J. Medina, E. Mérida-Casermeiro, and M. Ojeda-Aciego. “A Neural Approach to Abductive Multi-adjoint Reasoning”. In: _Artificial Intelligence: Methodology, Systems, and Applications_. Springer Berlin Heidelberg, 2002, p. 213–222. ISBN: 9783540461487. DOI: [10.1007/3-540-46148-5_22](https://doi.org/10.1007%2F3-540-46148-5_22). URL: [http://dx.doi.org/10.1007/3-540-46148-5_22](http://dx.doi.org/10.1007/3-540-46148-5_22).

<a name=bib-Medina_2004></a>[[2]](#cite-Medina_2004) J. Medina, M. Ojeda-Aciego, and P. Vojtáš. “Similarity-based unification: a multi-adjoint approach”. In: _Fuzzy Sets and Systems_ 146.1 (Aug. 2004), p. 43–62. ISSN: 0165-0114. DOI: [10.1016/j.fss.2003.11.005](https://doi.org/10.1016%2Fj.fss.2003.11.005). URL: [http://dx.doi.org/10.1016/j.fss.2003.11.005](http://dx.doi.org/10.1016/j.fss.2003.11.005).

