---
title: Indexed Flows in Temporal x Modal Logic with Functional Semantics
author:
- Alfredo Burrieza
- <a href='/people/staff/ipguzman/' style='color:rgb(100,0,50);'>Inma P. de Guzmán</a>
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
date: '2002'
categories: uncategorised
slug: 2002/InFlTeXMoLoFuSe
details: 9th International Symposium on Temporal Representation and Reasoning, TIME-2002,
  Manchester, UK, July 7-9, 2002 , pages 146--153.
doi: 10.1109/TIME.2002.1027488
---



# Abstract


Two classical semantical approaches to studying logics which combine time and modality are the T /spl times/ W-frames and Kamp-frames (Thomason (1984)). In this paper we study a new kind of frame that extends the one introduced in Burrieza et al. (2002). The motivation is twofold: theoretical, i.e., representing properties of the basic theory of functions (definability); and practical, their use in computational applications (considering time-flows as memory of computers connected in a net, each computer with its own clock). Specifically, we present a temporal /spl times/ modal (labelled) logic, whose semantics are given by ind-functional frames in which accessibility functions are used in order to interconnect time-flows. This way, we can: (i) specify to what time-flow we want to go; (ii) carry out different comparisons among worlds with different time measures; and (iii) define properties of certain kinds of functions (in particular, of total, injective, surjective, constant, increasing and decreasing functions), without the need to resort to second-order theories. In addition, we define a minimal axiomatic system and give the completeness theorem (Henkin-style).








# Citation
Please, cite this work as:


<a name=bib-Burrieza2002></a>[[BGM02]](#cite-Burrieza2002) A. Burrieza, I. P. de Guzmán, and E. Mu~noz-Velasco. “Indexed Flows in Temporal x Modal Logic with Functional Semantics”. In: _9th International Symposium on Temporal Representation and Reasoning, TIME-2002, Manchester, UK, July 7-9, 2002_. IEEE Computer Society, 2002, pp. 146-153. DOI: [10.1109/TIME.2002.1027488](https://doi.org/10.1109%2FTIME.2002.1027488). URL: [https://doi.org/10.1109/TIME.2002.1027488](https://doi.org/10.1109/TIME.2002.1027488).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Burrieza2002,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Alfredo Burrieza and Inman P. {de Guzm{\a'a}n} and Emilio Mu~noz-Velasco},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {9th International Symposium on Temporal Representation and Reasoning, TIME-2002, Manchester, UK, July 7-9, 2002},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Indexed Flows in Temporal x Modal Logic with Functional Semantics},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2002},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {146--153},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {{IEEE} Computer Society},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/time/BurriezaGM02.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1109/TIME.2002.1027488},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 24 Mar 2023 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1109/TIME.2002.1027488},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1109/TIME.2002.1027488" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1109/TIME.2002.1027488" class="plumx-details" data-site="plum" data-hide-when-empty="true">Indexed Flows in Temporal x Modal Logic with Functional Semantics</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1109/TIME.2002.1027488"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Aguilera_2006></a>[[1]](#cite-Aguilera_2006) G. Aguilera, A. Burrieza, P. Cordero, et al. “MAT Logic: A Temporal×Modal Logic with Non-deterministic Operators to Deal with Interactive Systems in Communication Technologies”. In: _Advances in Artificial Intelligence - IBERAMIA-SBIA 2006_. Springer Berlin Heidelberg, 2006, p. 602–611. ISBN: 9783540454649. DOI: [10.1007/11874850_64](https://doi.org/10.1007%2F11874850_64). URL: [http://dx.doi.org/10.1007/11874850_64](http://dx.doi.org/10.1007/11874850_64).

<a name=bib-Burrieza_2008></a>[[2]](#cite-Burrieza_2008) A. Burrieza, I. P. De Guzmán, and E. Muñoz-Velasco. “Generalization of some properties of relations in the context of functional temporal×modal logic”. In: _International Journal of Computer Mathematics_ 85.3–4 (Apr. 2008), p. 371–383. ISSN: 1029-0265. DOI: [10.1080/00207160701210141](https://doi.org/10.1080%2F00207160701210141). URL: [http://dx.doi.org/10.1080/00207160701210141](http://dx.doi.org/10.1080/00207160701210141).

<a name=bib-Burrieza_2017></a>[[3]](#cite-Burrieza_2017) A. Burrieza, I. Fortes, and I. P. de Guzmán. “Completeness of a functional system for surjective functions”. In: _Mathematical Logic Quarterly_ 63.6 (Dec. 2017), p. 574–597. ISSN: 1521-3870. DOI: [10.1002/malq.201600011](https://doi.org/10.1002%2Fmalq.201600011). URL: [http://dx.doi.org/10.1002/malq.201600011](http://dx.doi.org/10.1002/malq.201600011).

<a name=bib-Burrieza_2009></a>[[4]](#cite-Burrieza_2009) A. Burrieza, I. P. de Guzmán, and E. Muñoz-Velasco. “Functional systems in the context of temporal×modal logics with indexed flows”. In: _International Journal of Computer Mathematics_ 86.10–11 (Nov. 2009), p. 1696–1706. ISSN: 1029-0265. DOI: [10.1080/00207160902795619](https://doi.org/10.1080%2F00207160902795619). URL: [http://dx.doi.org/10.1080/00207160902795619](http://dx.doi.org/10.1080/00207160902795619).

<a name=bib-Burrieza_2010></a>[[5]](#cite-Burrieza_2010) A. Burrieza, I. P. de Guzmán, and E. Muñoz‐Velasco. “Analyzing completeness of axiomatic functional systems for temporal × modal logics”. In: _Mathematical Logic Quarterly_ 56.1 (Jan. 2010), p. 89–102. ISSN: 1521-3870. DOI: [10.1002/malq.200810038](https://doi.org/10.1002%2Fmalq.200810038). URL: [http://dx.doi.org/10.1002/malq.200810038](http://dx.doi.org/10.1002/malq.200810038).

