---
title: Isotone L-bonds
author:
- Jan Konecny
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '2013'
categories: uncategorised
slug: 2013/Is
details: Proceedings of the Tenth International Conference on Concept Lattices and
  Their Applications, La Rochelle, France, October 15-18, 2013 , {CEUR} Workshop Proceedings
  vol. 1062, pages 153--162.
---



# Abstract


L-bonds represent relationships between formal contexts. We study properties of these intercontextual structures w.r.t. isotone conceptforming operators in fuzzy setting. We also focus on the direct product of two formal fuzzy contexts and show conditions under which a bond can be obtained as an intent of the product. In addition, we show that the previously studied properties of their antitone counterparts can be easily derived from the present results.








# Citation
Please, cite this work as:


<a name=bib-Konecny2013></a>[[KO13]](#cite-Konecny2013) J. Konecny and M. Ojeda-Aciego. “Isotone L-bonds”. In: _Proceedings of the Tenth International Conference on Concept Lattices and Their Applications, La Rochelle, France, October 15-18, 2013_. Ed. by M. Ojeda-Aciego and J. Outrata. Vol. 1062. CEUR Workshop Proceedings. CEUR-WS.org, 2013, pp. 153-162. URL: [https://ceur-ws.org/Vol-1062/paper13.pdf](https://ceur-ws.org/Vol-1062/paper13.pdf).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Konecny2013,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Jan Konecny and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Proceedings of the Tenth International Conference on Concept Lattices and Their Applications, La Rochelle, France, October 15-18, 2013},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Isotone L-bonds},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2013},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Manuel Ojeda-Aciego and Jan Outrata},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {153--162},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {CEUR-WS.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {{CEUR} Workshop Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {1062},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {L-bonds represent relationships between formal contexts. We study properties of these intercontextual structures w.r.t. isotone conceptforming operators in fuzzy setting. We also focus on the direct product of two formal fuzzy contexts and show conditions under which a bond can be obtained as an intent of the product. In addition, we show that the previously studied properties of their antitone counterparts can be easily derived from the present results.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/cla/KonecnyO13.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 10 Mar 2023 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://ceur-ws.org/Vol-1062/paper13.pdf},<br>}

:::








