---
title: Non-commutativity and Expressive Deductive Logic Databases
author:
- Stanislav Krajci
- Rastislav Lencses
- Jesús Medina
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
- Agustín Valverde
- Peter Vojtás
date: '2002'
categories: uncategorised
slug: 2002/ExDeLoDa
details: Logics in Artificial Intelligence, European Conference, {JELIA} 2002, Cosenza,
  Italy, September, 23-26, Proceedings , Lecture Notes in Computer Science vol. 2424,
  pages 149--160.
doi: 10.1007/3-540-45757-7_13
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Krajci2002a></a>[[Kra+02]](#cite-Krajci2002a) S. Krajci, R. Lencses, J. Medina, et al. “Non-commutativity and Expressive Deductive Logic Databases”. In: _Logics in Artificial Intelligence, European Conference, JELIA 2002, Cosenza, Italy, September, 23-26, Proceedings_. Ed. by S. Flesca, S. Greco, N. Leone and G. Ianni. Vol. 2424. Lecture Notes in Computer Science. Springer, 2002, pp. 149-160. DOI: [10.1007/3-540-45757-7\_13](https://doi.org/10.1007%2F3-540-45757-7%5C_13). URL: [https://doi.org/10.1007/3-540-45757-7\_13](https://doi.org/10.1007/3-540-45757-7\_13).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Krajci2002a,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Stanislav Krajci and Rastislav Lencses and Jes{\a'u}s Medina and Manuel Ojeda-Aciego and Agust\'\in Valverde and Peter Vojt{\a'a}s},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Logics in Artificial Intelligence, European Conference, {JELIA} 2002, Cosenza, Italy, September, 23-26, Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Non-commutativity and Expressive Deductive Logic Databases},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2002},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Sergio Flesca and Sergio Greco and Nicola Leone and Giovambattista Ianni},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {149--160},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {2424},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/jelia/KrajciLMOVV02.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/3-540-45757-7\_13},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Thu, 07 Jan 2021 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/3-540-45757-7\_13},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/3-540-45757-7_13" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/3-540-45757-7_13" class="plumx-details" data-site="plum" data-hide-when-empty="true">Non-commutativity and Expressive Deductive Logic Databases</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1007/3-540-45757-7_13"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Kalafut_2025></a>[[1]](#cite-Kalafut_2025) J. Kalafut and A. Mesiarová-Zemánková. “Decomposition of pseudo-uninorms with continuous underlying functions via ordinal sum”. In: _Information Sciences_ 690 (Feb. 2025), p. 121573. ISSN: 0020-0255. DOI: [10.1016/j.ins.2024.121573](https://doi.org/10.1016%2Fj.ins.2024.121573). URL: [http://dx.doi.org/10.1016/j.ins.2024.121573](http://dx.doi.org/10.1016/j.ins.2024.121573).

