---
title: Partial formal contexts with degrees
author:
- <a href='/people/staff/franperezgamez/' style='color:rgb(100,0,50);'>Francisco Pérez
  Gámez</a>
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/enciso/' style='color:rgb(100,0,50);'>Manuel Enciso</a>
- <a href='/people/staff/amora/' style='color:rgb(100,0,50);'>Ángel Mora</a>
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '2022'
categories: uncategorised
slug: 2022/PaFoCoDe
details: Proceedings of the Sixteenth International Conference on Concept Lattices
  and Their Applications {(CLA} 2022) Tallinn, Estonia, June 20-22, 2022., Tallinn,
  Estonia, June 20-22, 2022 , {CEUR} Workshop Proceedings vol. 3308, pages 35--44.
---



# Abstract


Partial formal contexts are trivalued contexts that, besides allowing to establish whether a property is satisfied or not, allow to represent situations in which there is ignorance about whether a property is satisfied. This can be useful, not only for the cases in which the modeled phenomenon has intrinsically unknown information, but also when summarizing information from a formal context by grouping similar rows. In this paper, we prospect for its extension including degrees of knowledge.








# Citation
Please, cite this work as:


<a name=bib-PerezGamez2022a></a>[[Pér+22]](#cite-PerezGamez2022a) F. Pérez-Gámez, P. Cordero, M. Enciso, et al. “Partial formal contexts with degrees”. In: _Proceedings of the Sixteenth International Conference on Concept Lattices and Their Applications (CLA 2022) Tallinn, Estonia, June 20-22, 2022., Tallinn, Estonia, June 20-22, 2022_. Ed. by P. Cordero and O. Kr\'\idlo. Vol. 3308. CEUR Workshop Proceedings. CEUR-WS.org, 2022, pp. 35-44. URL: [https://ceur-ws.org/Vol-3308/Paper03.pdf](https://ceur-ws.org/Vol-3308/Paper03.pdf).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{PerezGamez2022a,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Francisco P{\a'e}rez-G{\a'a}mez and Pablo Cordero and Manuel Enciso and {\a'A}ngel Mora and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Proceedings of the Sixteenth International Conference on Concept Lattices and Their Applications {(CLA} 2022) Tallinn, Estonia, June 20-22, 2022., Tallinn, Estonia, June 20-22, 2022},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Partial formal contexts with degrees},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2022},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Pablo Cordero and Ondrej Kr\'\idlo},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {35--44},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {CEUR-WS.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {{CEUR} Workshop Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {3308},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {Partial formal contexts are trivalued contexts that, besides allowing to establish whether a property is satisfied or not, allow to represent situations in which there is ignorance about whether a property is satisfied. This can be useful, not only for the cases in which the modeled phenomenon has intrinsically unknown information, but also when summarizing information from a formal context by grouping similar rows. In this paper, we prospect for its extension including degrees of knowledge.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/cla/Perez-GamezCE0O22.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 10 Mar 2023 16:22:10 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://ceur-ws.org/Vol-3308/Paper03.pdf},<br>}

:::








