---
title: 'A coalgebraic approach to non-determinism: Applications to multilattices'
author:
- <a href='/people/staff/ipcabrera/' style='color:rgb(100,0,50);'>Inma P. Cabrera</a>
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- Gloria Gutiérrez
- Javier Martínez
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '2010'
categories: uncategorised
slug: 2010/CoApApMu
details: Inf. Sci. vol. 180 (22), pages 4323--4335.
doi: 10.1016/J.INS.2010.07.002
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Cabrera2010></a>[[Cab+10]](#cite-Cabrera2010) I. P. Cabrera, P. Cordero, G. Gutiérrez, et al. “A coalgebraic approach to non-determinism: Applications to multilattices”. In: _Inf. Sci._ 180.22 (2010), pp. 4323-4335. DOI: [10.1016/J.INS.2010.07.002](https://doi.org/10.1016%2FJ.INS.2010.07.002). URL: [https://doi.org/10.1016/j.ins.2010.07.002](https://doi.org/10.1016/j.ins.2010.07.002).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{Cabrera2010,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Inma P. Cabrera and Pablo Cordero and Gloria Guti{\a'e}rrez and Javier Mart\'\inez and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Inf. Sci.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {A coalgebraic approach to non-determinism: Applications to multilattices},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2010},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number = {22},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {4323--4335},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {180},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/isci/CabreraCGMO10.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1016/J.INS.2010.07.002},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Tue, 29 Aug 2023 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1016/j.ins.2010.07.002},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1016/J.INS.2010.07.002" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1016/J.INS.2010.07.002" class="plumx-details" data-site="plum" data-hide-when-empty="true">A coalgebraic approach to non-determinism: Applications to multilattices</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1016/J.INS.2010.07.002"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Cabrera_2011></a>[[1]](#cite-Cabrera_2011) I. P. Cabrera, P. Cordero, and M. Ojeda-Aciego. “Non-deterministic Algebraic Structures for Soft Computing”. In: _Advances in Computational Intelligence_. Springer Berlin Heidelberg, 2011, p. 437–444. ISBN: 9783642214981. DOI: [10.1007/978-3-642-21498-1_55](https://doi.org/10.1007%2F978-3-642-21498-1_55). URL: [http://dx.doi.org/10.1007/978-3-642-21498-1_55](http://dx.doi.org/10.1007/978-3-642-21498-1_55).

<a name=bib-Cabrera_2012></a>[[2]](#cite-Cabrera_2012) I. Cabrera, P. Cordero, G. Gutiérrez, et al. “Finitary coalgebraic multisemilattices and multilattices”. In: _Applied Mathematics and Computation_ 219.1 (Sep. 2012), p. 31–44. ISSN: 0096-3003. DOI: [10.1016/j.amc.2011.10.081](https://doi.org/10.1016%2Fj.amc.2011.10.081). URL: [http://dx.doi.org/10.1016/j.amc.2011.10.081](http://dx.doi.org/10.1016/j.amc.2011.10.081).

<a name=bib-Cabrera_2014></a>[[3]](#cite-Cabrera_2014) I. Cabrera, P. Cordero, G. Gutiérrez, et al. “On residuation in multilattices: Filters, congruences, and homomorphisms”. In: _Fuzzy Sets and Systems_ 234 (Jan. 2014), p. 1–21. ISSN: 0165-0114. DOI: [10.1016/j.fss.2013.04.002](https://doi.org/10.1016%2Fj.fss.2013.04.002). URL: [http://dx.doi.org/10.1016/j.fss.2013.04.002](http://dx.doi.org/10.1016/j.fss.2013.04.002).

<a name=bib-Garc_a_Pardo_2014></a>[[4]](#cite-Garc_a_Pardo_2014) F. García-Pardo, I. Cabrera, P. Cordero, et al. “On the definition of suitable orderings to generate adjunctions over an unstructured codomain”. In: _Information Sciences_ 286 (Dec. 2014), p. 173–187. ISSN: 0020-0255. DOI: [10.1016/j.ins.2014.07.006](https://doi.org/10.1016%2Fj.ins.2014.07.006). URL: [http://dx.doi.org/10.1016/j.ins.2014.07.006](http://dx.doi.org/10.1016/j.ins.2014.07.006).

<a name=bib-Morcillo_2012></a>[[5]](#cite-Morcillo_2012) P. J. Morcillo, G. Moreno, J. Penabad, et al. “Dedekind–MacNeille completion and Cartesian product of multi-adjoint lattices”. In: _International Journal of Computer Mathematics_ 89.13–14 (Sep. 2012), p. 1742–1752. ISSN: 1029-0265. DOI: [10.1080/00207160.2012.689826](https://doi.org/10.1080%2F00207160.2012.689826). URL: [http://dx.doi.org/10.1080/00207160.2012.689826](http://dx.doi.org/10.1080/00207160.2012.689826).

<a name=bib-Ling_Wei_2012></a>[[6]](#cite-Ling_Wei_2012) L. Wei and T. Li. “Rules acquisition in consistent formal decision contexts”. In: _2012 International Conference on Machine Learning and Cybernetics_. IEEE, Jul. 2012, p. 801–805. DOI: [10.1109/icmlc.2012.6359028](https://doi.org/10.1109%2Ficmlc.2012.6359028). URL: [http://dx.doi.org/10.1109/icmlc.2012.6359028](http://dx.doi.org/10.1109/icmlc.2012.6359028).

<a name=bib-Wei_2012></a>[[7]](#cite-Wei_2012) L. Wei and Q. Wan. “Approximate Concepts Based on N-Scale Relation”. In: _Rough Sets and Current Trends in Computing_. Springer Berlin Heidelberg, 2012, p. 332–340. ISBN: 9783642321153. DOI: [10.1007/978-3-642-32115-3_39](https://doi.org/10.1007%2F978-3-642-32115-3_39). URL: [http://dx.doi.org/10.1007/978-3-642-32115-3_39](http://dx.doi.org/10.1007/978-3-642-32115-3_39).

