---
title: Restricted Delta-Trees in Multiple-Valued Logics
author:
- <a href='/people/staff/ipguzman/' style='color:rgb(100,0,50);'>Inma P. de Guzmán</a>
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
- Agustín Valverde
date: '2002'
categories: uncategorised
slug: 2002/ReLo
details: 'Artificial Intelligence: Methodology, Systems, and Applications, 10th International
  Conference, {AIMSA} 2002, Varna, Bulgaria, September 4-6, 2002, Proceedings , Lecture
  Notes in Computer Science vol. 2443, pages 223--232.'
doi: 10.1007/3-540-46148-5_23
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Guzman2002></a>[[GOA02]](#cite-Guzman2002) I. P. de Guzmán, M. Ojeda-Aciego, and Agust\'\inValverde. “Restricted Delta-Trees in Multiple-Valued Logics”. In: _Artificial Intelligence: Methodology, Systems, and Applications, 10th International Conference, AIMSA 2002, Varna, Bulgaria, September 4-6, 2002, Proceedings_. Ed. by D. Scott. Vol. 2443. Lecture Notes in Computer Science. Springer, 2002, pp. 223-232. DOI: [10.1007/3-540-46148-5\_23](https://doi.org/10.1007%2F3-540-46148-5%5C_23). URL: [https://doi.org/10.1007/3-540-46148-5\_23](https://doi.org/10.1007/3-540-46148-5\_23).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Guzman2002,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Inman P. {de Guzm{\a'a}n} and Manuel Ojeda-Aciego and Agust\'\in Valverde},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Artificial Intelligence: Methodology, Systems, and Applications, 10th International Conference, {AIMSA} 2002, Varna, Bulgaria, September 4-6, 2002, Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Restricted Delta-Trees in Multiple-Valued Logics},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2002},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Donia Scott},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {223--232},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {2443},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/aimsa/GuzmanOV02.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/3-540-46148-5\_23},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Sun, 21 May 2017 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/3-540-46148-5\_23},<br>}

:::






## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-de_Guzm_n_2002></a>[[1]](#cite-de_Guzm_n_2002) I. P. de Guzmán, M. Ojeda-Aciego, and A. Valverde. “Restricted Δ-Trees and Reduction Theorems in Multiple-Valued Logics”. In: _Advances in Artificial Intelligence — IBERAMIA 2002_. Springer Berlin Heidelberg, 2002, p. 161–171. ISBN: 9783540361312. DOI: [10.1007/3-540-36131-6_17](https://doi.org/10.1007%2F3-540-36131-6_17). URL: [http://dx.doi.org/10.1007/3-540-36131-6_17](http://dx.doi.org/10.1007/3-540-36131-6_17).

