---
title: Computing non-redundant sets of functional dependencies via simplification
author:
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/enciso/' style='color:rgb(100,0,50);'>Manuel Enciso</a>
- <a href='/people/staff/amora/' style='color:rgb(100,0,50);'>Ángel Mora</a>
- José Manuel Rodríguez-Jiménez
date: '2013'
categories: uncategorised
slug: 2013/CoSeFuDeViSi
details: '{IEEE} Symposium on Foundations of Computational Intelligence, {FOCI} 2013,
  Singapore, Singapore, April 16-19, 2013 , pages 9--14.'
doi: 10.1109/FOCI.2013.6602449
---



# Abstract


Functional dependencies may be considered the skeleton of the Relational Database Model. They describe binary relations between sets of attributes and they characterize the database structure. A way to ensure solid specifications is to transform set of functional dependencies into an equivalent one with less redundancy. In this work we consider a fuzzy extension of the notion of functional dependencies which is consistent with the Armstrong axioms. We improve the well known notion of Duquenne-Guigues basis by enriching the minimality criteria and we introduce a method to remove redundancy in the basis.








# Citation
Please, cite this work as:


<a name=bib-Cordero2013a></a>[[Cor+13]](#cite-Cordero2013a) P. Cordero, M. Enciso, Á. Mora, et al. “Computing non-redundant sets of functional dependencies via simplification”. In: _IEEE Symposium on Foundations of Computational Intelligence, FOCI 2013, Singapore, Singapore, April 16-19, 2013_. IEEE, 2013, pp. 9-14. DOI: [10.1109/FOCI.2013.6602449](https://doi.org/10.1109%2FFOCI.2013.6602449). URL: [https://doi.org/10.1109/FOCI.2013.6602449](https://doi.org/10.1109/FOCI.2013.6602449).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Cordero2013a,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Pablo Cordero and Manuel Enciso and {\a'A}ngel Mora and Jos{\a'e} Manuel Rodr\'\iguez-Jim{\a'e}nez},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {{IEEE} Symposium on Foundations of Computational Intelligence, {FOCI} 2013, Singapore, Singapore, April 16-19, 2013},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Computing non-redundant sets of functional dependencies via simplification},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2013},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {9--14},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {{IEEE}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/foci/CorderoEMR13.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1109/FOCI.2013.6602449},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 23 Sep 2022 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1109/FOCI.2013.6602449},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1109/FOCI.2013.6602449" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1109/FOCI.2013.6602449" class="plumx-details" data-site="plum" data-hide-when-empty="true">Computing non-redundant sets of functional dependencies via simplification</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1109/FOCI.2013.6602449"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Cordero_2022></a>[[1]](#cite-Cordero_2022) P. Cordero, M. Enciso, A. Mora, et al. “Interactive Search by Using Minimal Generators”. In: _Computational Intelligence and Mathematics for Tackling Complex Problems 2_. Springer International Publishing, 2022, p. 147–153. ISBN: 9783030888176. DOI: [10.1007/978-3-030-88817-6_17](https://doi.org/10.1007%2F978-3-030-88817-6_17). URL: [http://dx.doi.org/10.1007/978-3-030-88817-6_17](http://dx.doi.org/10.1007/978-3-030-88817-6_17).

<a name=bib-Cordero_2020></a>[[2]](#cite-Cordero_2020) P. Cordero, M. Enciso, Á. Mora, et al. “A Formal Concept Analysis Approach to Cooperative Conversational Recommendation”. In: _International Journal of Computational Intelligence Systems_ 13.1 (2020), p. 1243. ISSN: 1875-6883. DOI: [10.2991/ijcis.d.200806.001](https://doi.org/10.2991%2Fijcis.d.200806.001). URL: [http://dx.doi.org/10.2991/ijcis.d.200806.001](http://dx.doi.org/10.2991/ijcis.d.200806.001).

<a name=bib-Triska_2015></a>[[3]](#cite-Triska_2015) J. Triska and V. Vychodil. “Graded data dependencies in relational databases: Reasoning with similarity of time”. In: _2015 Annual Conference of the North American Fuzzy Information Processing Society (NAFIPS) held jointly with 2015 5th World Conference on Soft Computing (WConSC)_. IEEE, Aug. 2015, p. 1–6. DOI: [10.1109/nafips-wconsc.2015.7284170](https://doi.org/10.1109%2Fnafips-wconsc.2015.7284170). URL: [http://dx.doi.org/10.1109/nafips-wconsc.2015.7284170](http://dx.doi.org/10.1109/nafips-wconsc.2015.7284170).

