---
title: Similarities between powersets of terms
author:
- Patrik Eklund
- Maria A. Galán
- Jesús Medina
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
- Agustín Valverde
date: '2004'
categories: uncategorised
slug: 2004/SiPoTe
details: Fuzzy Sets Syst. vol. 144 (1), pages 213--225.
doi: 10.1016/J.FSS.2003.10.021
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Eklund2004></a>[[Ekl+04]](#cite-Eklund2004) P. Eklund, M. A. Galán, J. Medina, et al. “Similarities between powersets of terms”. In: _Fuzzy Sets Syst._ 144.1 (2004), pp. 213-225. DOI: [10.1016/J.FSS.2003.10.021](https://doi.org/10.1016%2FJ.FSS.2003.10.021). URL: [https://doi.org/10.1016/j.fss.2003.10.021](https://doi.org/10.1016/j.fss.2003.10.021).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{Eklund2004,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Patrik Eklund and Maria A. Gal{\a'a}n and Jes{\a'u}s Medina and Manuel Ojeda-Aciego and Agust\'\in Valverde},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Fuzzy Sets Syst.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Similarities between powersets of terms},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2004},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number = {1},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {213--225},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {144},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/fss/EklundGMOV04.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1016/J.FSS.2003.10.021},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Thu, 07 Jan 2021 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1016/j.fss.2003.10.021},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1016/J.FSS.2003.10.021" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1016/J.FSS.2003.10.021" class="plumx-details" data-site="plum" data-hide-when-empty="true">Similarities between powersets of terms</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1016/J.FSS.2003.10.021"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Brazhnik_2007></a>[[1]](#cite-Brazhnik_2007) O. Brazhnik. “Databases and the geometry of knowledge”. In: _Data &amp; Knowledge Engineering_ 61.2 (May. 2007), p. 207–227. ISSN: 0169-023X. DOI: [10.1016/j.datak.2006.05.005](https://doi.org/10.1016%2Fj.datak.2006.05.005). URL: [http://dx.doi.org/10.1016/j.datak.2006.05.005](http://dx.doi.org/10.1016/j.datak.2006.05.005).

<a name=bib-Chen_20101></a>[[2]](#cite-Chen_20101) Y. Chen, Y. Chen, and M. Wu. “An expert recommendation system for product empirical knowledge consultation”. In: _2010 3rd International Conference on Computer Science and Information Technology_. IEEE, Jul. 2010, p. 23–27. DOI: [10.1109/iccsit.2010.5563845](https://doi.org/10.1109%2Ficcsit.2010.5563845). URL: [http://dx.doi.org/10.1109/iccsit.2010.5563845](http://dx.doi.org/10.1109/iccsit.2010.5563845).

<a name=bib-Chen_2010></a>[[3]](#cite-Chen_2010) Y. Chen, Y. Chen, and M. Wu. “Development of an Ontology-based Expert Recommendation System for Product Empirical Knowledge Consultation”. In: _Concurrent Engineering_ 18.3 (Jun. 2010), p. 233–253. ISSN: 1531-2003. DOI: [10.1177/1063293x10373824](https://doi.org/10.1177%2F1063293x10373824). URL: [http://dx.doi.org/10.1177/1063293x10373824](http://dx.doi.org/10.1177/1063293x10373824).

<a name=bib-Denniston_2016></a>[[4]](#cite-Denniston_2016) J. T. Denniston, A. Melton, S. E. Rodabaugh, et al. “Topological systems as a framework for institutions”. In: _Fuzzy Sets and Systems_ 298 (Sep. 2016), p. 91–108. ISSN: 0165-0114. DOI: [10.1016/j.fss.2015.08.009](https://doi.org/10.1016%2Fj.fss.2015.08.009). URL: [http://dx.doi.org/10.1016/j.fss.2015.08.009](http://dx.doi.org/10.1016/j.fss.2015.08.009).

<a name=bib-Dubey_2018></a>[[5]](#cite-Dubey_2018) M. K. Dubey, V. K. Yadav, and S. P. Tiwari. “On the Category of Quantale-Semimodules”. In: _Progress in Advanced Computing and Intelligent Engineering_. Springer Singapore, Jul. 2018, p. 595–605. ISBN: 9789811302244. DOI: [10.1007/978-981-13-0224-4_54](https://doi.org/10.1007%2F978-981-13-0224-4_54). URL: [http://dx.doi.org/10.1007/978-981-13-0224-4_54](http://dx.doi.org/10.1007/978-981-13-0224-4_54).

<a name=bib-Eklund_2009></a>[[6]](#cite-Eklund_2009) P. Eklund. “Early diagnosis of cognitive disorder based on ground categories for decision support structures”. In: _2009 IEEE International Conference on Fuzzy Systems_. IEEE, Aug. 2009, p. 997–1002. DOI: [10.1109/fuzzy.2009.5277098](https://doi.org/10.1109%2Ffuzzy.2009.5277098). URL: [http://dx.doi.org/10.1109/fuzzy.2009.5277098](http://dx.doi.org/10.1109/fuzzy.2009.5277098).

<a name=bib-Eklund_2007></a>[[7]](#cite-Eklund_2007) P. Eklund, M. Galán, J. Medina, et al. “Powersets of terms and composite monads”. In: _Fuzzy Sets and Systems_ 158.23 (Dec. 2007), p. 2552–2574. ISSN: 0165-0114. DOI: [10.1016/j.fss.2007.06.002](https://doi.org/10.1016%2Fj.fss.2007.06.002). URL: [http://dx.doi.org/10.1016/j.fss.2007.06.002](http://dx.doi.org/10.1016/j.fss.2007.06.002).

<a name=bib-Eklund_2012></a>[[8]](#cite-Eklund_2012) P. Eklund, J. Kortelainen, and L. N. Stout. “Adding fuzziness to terms and powerobjects using a monadic approach”. In: _Fuzzy Sets and Systems_ 192 (Apr. 2012), p. 104–122. ISSN: 0165-0114. DOI: [10.1016/j.fss.2010.10.014](https://doi.org/10.1016%2Fj.fss.2010.10.014). URL: [http://dx.doi.org/10.1016/j.fss.2010.10.014](http://dx.doi.org/10.1016/j.fss.2010.10.014).

<a name=bib-Mo_k__2015></a>[[9]](#cite-Mo_k__2015) J. Močkǒ. “Closure theories of powerset theories”. In: _Tatra Mountains Mathematical Publications_ 64.1 (Sep. 2015), p. 101–126. ISSN: 1210-3195. DOI: [10.1515/tmmp-2015-0045](https://doi.org/10.1515%2Ftmmp-2015-0045). URL: [http://dx.doi.org/10.1515/tmmp-2015-0045](http://dx.doi.org/10.1515/tmmp-2015-0045).

<a name=bib-Mo_ko__2021></a>[[10]](#cite-Mo_ko__2021) J. Močkoř. “Relational, closure and partition powerset theories”. In: _Fuzzy Sets and Systems_ 420 (Sep. 2021), p. 100–122. ISSN: 0165-0114. DOI: [10.1016/j.fss.2020.11.009](https://doi.org/10.1016%2Fj.fss.2020.11.009). URL: [http://dx.doi.org/10.1016/j.fss.2020.11.009](http://dx.doi.org/10.1016/j.fss.2020.11.009).

