---
title: Thresholded Tabulation in a Fuzzy Logic Setting
author:
- Pascual Julián Iranzo
- Jesús Medina
- Ginés Moreno
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '2008'
categories: uncategorised
slug: 2008/ThTaFuLoSe
details: Proceedings of the Eighth Spanish Conference on Programming and Computer
  Languages, {PROLE} 2008, Gij{\'{o}}n, Spain, October 8-10, 2008 , Electronic Notes
  in Theoretical Computer Science vol. 248, pages 115--130.
doi: 10.1016/J.ENTCS.2009.07.063
---



# Abstract


Fuzzy logic programming represents a flexible and powerful declarative paradigm amalgamating fuzzy logic and logic programming, for which there exists different promising approaches described in the literature. In this paper we propose an improved fuzzy query answering procedure for the so called multi-adjoint logic programming approach, which avoids the re-evaluation of goals and the generation of useless computations thanks to the combined use of tabulation with thresholding techniques. The general idea is that, when trying to perform a computation step by using a given program rule R, we firstly analyze if such step might contribute to reach further significant solutions (non tabulated yet). When it is the case, it is possible to avoid a useless computation step via a rule R by using thresholds and filters based on the truth degree of R, as well as a safe, accurate and dynamic estimation of the maximum truth degree associated to its body.








# Citation
Please, cite this work as:


<a name=bib-Iranzo2008></a>[[Ira+08]](#cite-Iranzo2008) P. J. Iranzo, J. Medina, G. Moreno, et al. “Thresholded Tabulation in a Fuzzy Logic Setting”. In: _Proceedings of the Eighth Spanish Conference on Programming and Computer Languages, PROLE 2008, Gijón, Spain, October 8-10, 2008_. Ed. by J. M. Almendros-Jiménez. Vol. 248. Electronic Notes in Theoretical Computer Science. Elsevier, 2008, pp. 115-130. DOI: [10.1016/J.ENTCS.2009.07.063](https://doi.org/10.1016%2FJ.ENTCS.2009.07.063). URL: [https://doi.org/10.1016/j.entcs.2009.07.063](https://doi.org/10.1016/j.entcs.2009.07.063).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Iranzo2008,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Pascual Juli{\a'a}n Iranzo and Jes{\a'u}s Medina and Gin{\a'e}s Moreno and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Proceedings of the Eighth Spanish Conference on Programming and Computer Languages, {PROLE} 2008, Gij{\'{o}}n, Spain, October 8-10, 2008},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Thresholded Tabulation in a Fuzzy Logic Setting},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2008},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Jes{\a'u}s Manuel Almendros-Jim{\a'e}nez},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {115--130},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Elsevier},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Electronic Notes in Theoretical Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {248},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/entcs/IranzoMMO09.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1016/J.ENTCS.2009.07.063},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Thu, 09 Mar 2023 14:51:20 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1016/j.entcs.2009.07.063},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1016/J.ENTCS.2009.07.063" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1016/J.ENTCS.2009.07.063" class="plumx-details" data-site="plum" data-hide-when-empty="true">Thresholded Tabulation in a Fuzzy Logic Setting</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1016/J.ENTCS.2009.07.063"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-D_az_Moreno_2022></a>[[1]](#cite-D_az_Moreno_2022) J. C. Díaz-Moreno, J. Medina, and J. R. Portillo. “Fuzzy logic programs as hypergraphs. Termination results”. In: _Fuzzy Sets and Systems_ 445 (Sep. 2022), p. 22–42. ISSN: 0165-0114. DOI: [10.1016/j.fss.2022.02.001](https://doi.org/10.1016%2Fj.fss.2022.02.001). URL: [http://dx.doi.org/10.1016/j.fss.2022.02.001](http://dx.doi.org/10.1016/j.fss.2022.02.001).

<a name=bib-Guerrero_2017></a>[[2]](#cite-Guerrero_2017) J. A. Guerrero, F. Mendieta, G. Moreno, et al. “Testing properties of fuzzy connectives and truth degrees with the latticemaker tool”. In: _2017 IEEE Symposium Series on Computational Intelligence (SSCI)_. IEEE, Nov. 2017, p. 1–8. DOI: [10.1109/ssci.2017.8280961](https://doi.org/10.1109%2Fssci.2017.8280961). URL: [http://dx.doi.org/10.1109/ssci.2017.8280961](http://dx.doi.org/10.1109/ssci.2017.8280961).

<a name=bib-Guerrero_2015></a>[[3]](#cite-Guerrero_2015) J. Guerrero, M. Del Senor Martinez, G. Moreno, et al. “Designing Lattices of Truth Degrees for Fuzzy Logic Programming Environments”. In: _2015 IEEE Symposium Series on Computational Intelligence_. IEEE, Dec. 2015, p. 995–1004. DOI: [10.1109/ssci.2015.145](https://doi.org/10.1109%2Fssci.2015.145). URL: [http://dx.doi.org/10.1109/ssci.2015.145](http://dx.doi.org/10.1109/ssci.2015.145).

<a name=bib-Juli_n_Iranzo_2020></a>[[4]](#cite-Juli_n_Iranzo_2020) P. Julián-Iranzo, G. Moreno, and J. A. Riaza. “The Fuzzy Logic Programming language FASILL: Design and implementation”. In: _International Journal of Approximate Reasoning_ 125 (Oct. 2020), p. 139–168. ISSN: 0888-613X. DOI: [10.1016/j.ijar.2020.06.002](https://doi.org/10.1016%2Fj.ijar.2020.06.002). URL: [http://dx.doi.org/10.1016/j.ijar.2020.06.002](http://dx.doi.org/10.1016/j.ijar.2020.06.002).

<a name=bib-Juli_n_2010></a>[[5]](#cite-Juli_n_2010) P. Julián, J. Medina, G. Moreno, et al. “Efficient Thresholded Tabulation for Fuzzy Query Answering”. In: _Foundations of Reasoning under Uncertainty_. Springer Berlin Heidelberg, 2010, p. 125–141. ISBN: 9783642107283. DOI: [10.1007/978-3-642-10728-3_7](https://doi.org/10.1007%2F978-3-642-10728-3_7). URL: [http://dx.doi.org/10.1007/978-3-642-10728-3_7](http://dx.doi.org/10.1007/978-3-642-10728-3_7).

<a name=bib-Le_2015></a>[[6]](#cite-Le_2015) V. H. Le and F. Liu. “Tabulation proof procedures for fuzzy linguistic logic programming”. In: _International Journal of Approximate Reasoning_ 63 (Aug. 2015), p. 62–88. ISSN: 0888-613X. DOI: [10.1016/j.ijar.2015.06.001](https://doi.org/10.1016%2Fj.ijar.2015.06.001). URL: [http://dx.doi.org/10.1016/j.ijar.2015.06.001](http://dx.doi.org/10.1016/j.ijar.2015.06.001).

<a name=bib-Morcillo_2010></a>[[7]](#cite-Morcillo_2010) P. J. Morcillo, G. Moreno, J. Penabad, et al. “A Practical Management of Fuzzy Truth-Degrees Using FLOPER”. In: _Semantic Web Rules_. Springer Berlin Heidelberg, 2010, p. 20–34. ISBN: 9783642162893. DOI: [10.1007/978-3-642-16289-3_4](https://doi.org/10.1007%2F978-3-642-16289-3_4). URL: [http://dx.doi.org/10.1007/978-3-642-16289-3_4](http://dx.doi.org/10.1007/978-3-642-16289-3_4).

<a name=bib-Morcillo_2011></a>[[8]](#cite-Morcillo_2011) P. Morcillo, G. Moreno, J. Penabad, et al. “Declarative Traces into Fuzzy Computed Answers”. In: _Rule-Based Reasoning, Programming, and Applications_. Springer Berlin Heidelberg, 2011, p. 170–185. ISBN: 9783642225468. DOI: [10.1007/978-3-642-22546-8_14](https://doi.org/10.1007%2F978-3-642-22546-8_14). URL: [http://dx.doi.org/10.1007/978-3-642-22546-8_14](http://dx.doi.org/10.1007/978-3-642-22546-8_14).

<a name=bib-Moreno_2014></a>[[9]](#cite-Moreno_2014) G. Moreno, J. Penabad, and C. Vázquez. “Beyond multi-adjoint logic programming”. In: _International Journal of Computer Mathematics_ 92.9 (Nov. 2014), p. 1956–1975. ISSN: 1029-0265. DOI: [10.1080/00207160.2014.975218](https://doi.org/10.1080%2F00207160.2014.975218). URL: [http://dx.doi.org/10.1080/00207160.2014.975218](http://dx.doi.org/10.1080/00207160.2014.975218).

<a name=bib-Moreno_2019></a>[[10]](#cite-Moreno_2019) G. Moreno and J. A. Riaza. “An Online Tool for Unfolding Symbolic Fuzzy Logic Programs”. In: _Advances in Computational Intelligence_. Springer International Publishing, 2019, p. 475–487. ISBN: 9783030205188. DOI: [10.1007/978-3-030-20518-8_40](https://doi.org/10.1007%2F978-3-030-20518-8_40). URL: [http://dx.doi.org/10.1007/978-3-030-20518-8_40](http://dx.doi.org/10.1007/978-3-030-20518-8_40).

