---
author:
- Angel Mora Bonilla
- Domingo López-Rodríguez
- Manuel Enciso
- Pablo Cordero
Status: Published
date: '2022-10-05T00:00:00Z'
slug: 2022-escim
title: Knowledge Discovery in Malware Datasets using Formal Concept Analysis
categories: Formal concept analysis
header_image: ~
details: <em>14th European Symposium on Computational Intelligence and Mathematics</em>
link: 2022-escim/PAPER.pdf
project: 2019-flair
keywords: Formal concept analysis, Mixed attributes, Concept lattice
listing:
- id: funding
  contents: funding.yml
  type: default
  sort: date desc
---


# Abstract


Intelligent malware detection is a problem that is generating growing interest in the industry due to the increase in the diversity of threats and attacks suffered by small users to large organisations or governments, in many cases compromising sensitive information and without ruling out possible economic consequences.

Among the different problems that arise in this area, the homogenisation of the nomenclature of malware threats stands out, as different antivirus engines or applications often use different names for the same threat or the same family of threats, which is related to the problem of malware family classification. 

Another big open problem in this field is the definition of methodologies that allow optimising the detection process itself of new threats, since the different engines have different detection capabilities and no single software can detect all the threats at one point, thus there is a need of determining which combination or possible combinations of engines cover the majority of detection and which features present in malicious software allow us to detect it at an early stage.

In this paper, we propose the use of formal concept analysis (FCA) to exploit the existing knowledge in previous threat and malware databases by different detection engines. In this formal framework, based on lattice theory and logic, we can build a lattice where threat sets are organised hierarchically according to specialisation-generalisation criteria, which provides us with a direct approach to  setting up a unified taxonomy of malware.

On the other hand, the use of FCA itself enables the discovery of logical rules and the application of automated reasoning methods whose objective is to simplify the detection process without losing information or threat detection capacity and even increasing this capacity.

In this sense, our proposal differs from previous ones in that it does not use statistical criteria, but rather an exhaustive analysis and mathematical modelling of the knowledge contained in malware databases, so that the models obtained are based on logical and algebraic tools and offer a greater degree of interpretability and explainability than previous proposals.




# Funding
::: {.callout-note appearance='minimal' collapse=false}
## Projects funding this work

:::{#funding}
:::
:::




# Citation
Please, cite this work as:


<a name=bib-escim2022></a>[[Bon+22]](#cite-escim2022) A. M. Bonilla, D. López-Rodríguez, M. Enciso, et al. “Knowledge Discovery in Malware Datasets using Formal Concept Analysis”. In: _Book of Abstracts, 14th European Symposium on Computational Intelligence and Mathematics, ESCIM 2022, Naples, Italy, October 2-5, 2022_. Ed. by L. T. Kóczy, J. Medina, R. G. Aragón, F. Chacón-Gómez, J. Kacprzyk, M. E. Cornejo-Piñero, D. Lobo, F. J. Ocaña-Alcázar and E. Ramírez-Poussa. 2022, pp. 6-7. URL: [http://escim2022.uca.es/wp-content/uploads/BoA_ESCIM2022_final.pdf](http://escim2022.uca.es/wp-content/uploads/BoA_ESCIM2022_final.pdf).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@inproceedings{escim2022,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author    = {Angel Mora Bonilla and Domingo López-Rodríguez and Manuel Enciso and Pablo Cordero},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor    = {László T. Kóczy and Jesús Medina and Roberto G. Aragón and Fernando Chacón-Gómez and Janusz Kacprzyk and M. Eugenia Cornejo-Piñero and David Lobo and Francisco J. Ocaña-Alcázar and Eloísa Ramírez-Poussa},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title     = {Knowledge Discovery in Malware Datasets using Formal Concept Analysis},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Book of Abstracts, 14th European Symposium on Computational Intelligence and Mathematics, {ESCIM} 2022, Naples, Italy, October 2-5, 2022},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages     = {6--7},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year      = {2022},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url       = {http://escim2022.uca.es/wp-content/uploads/BoA_ESCIM2022_final.pdf}<br>}

:::


