---
title: On Reachability of Minimal Models of Multilattice-Based Logic Programs
author:
- Jesús Medina
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
- Jorge Ruiz-Calvi~no
date: '2007'
categories: uncategorised
slug: 2007/ReMiMoLoPr
details: '{MICAI} 2007: Advances in Artificial Intelligence, 6th Mexican International
  Conference on Artificial Intelligence, Aguascalientes, Mexico, November 4-10, 2007,
  Proceedings , Lecture Notes in Computer Science vol. 4827, pages 271--282.'
doi: 10.1007/978-3-540-76631-5_26
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Medina2007c></a>[[MOR07]](#cite-Medina2007c) J. Medina, M. Ojeda-Aciego, and J. Ruiz-Calvi~no. “On Reachability of Minimal Models of Multilattice-Based Logic Programs”. In: _MICAI 2007: Advances in Artificial Intelligence, 6th Mexican International Conference on Artificial Intelligence, Aguascalientes, Mexico, November 4-10, 2007, Proceedings_. Ed. by A. F. Gelbukh and A. F. K. Morales. Vol. 4827. Lecture Notes in Computer Science. Springer, 2007, pp. 271-282. DOI: [10.1007/978-3-540-76631-5\_26](https://doi.org/10.1007%2F978-3-540-76631-5%5C_26). URL: [https://doi.org/10.1007/978-3-540-76631-5\_26](https://doi.org/10.1007/978-3-540-76631-5\_26).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Medina2007c,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Jes{\a'u}s Medina and Manuel Ojeda-Aciego and Jorge Ruiz-Calvi~no},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {{MICAI} 2007: Advances in Artificial Intelligence, 6th Mexican International Conference on Artificial Intelligence, Aguascalientes, Mexico, November 4-10, 2007, Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {On Reachability of Minimal Models of Multilattice-Based Logic Programs},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2007},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Alexander F. Gelbukh and Angel Fernando Kuri Morales},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {271--282},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {4827},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/micai/MedinaOR07.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/978-3-540-76631-5\_26},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Sun, 06 Oct 2024 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/978-3-540-76631-5\_26},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/978-3-540-76631-5_26" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/978-3-540-76631-5_26" class="plumx-details" data-site="plum" data-hide-when-empty="true">On Reachability of Minimal Models of Multilattice-Based Logic Programs</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1007/978-3-540-76631-5_26"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Morcillo_2012></a>[[1]](#cite-Morcillo_2012) P. J. Morcillo, G. Moreno, J. Penabad, et al. “Dedekind–MacNeille completion and Cartesian product of multi-adjoint lattices”. In: _International Journal of Computer Mathematics_ 89.13–14 (Sep. 2012), p. 1742–1752. ISSN: 1029-0265. DOI: [10.1080/00207160.2012.689826](https://doi.org/10.1080%2F00207160.2012.689826). URL: [http://dx.doi.org/10.1080/00207160.2012.689826](http://dx.doi.org/10.1080/00207160.2012.689826).

<a name=bib-Moreno_2014></a>[[2]](#cite-Moreno_2014) G. Moreno, J. Penabad, and C. Vázquez. “Beyond multi-adjoint logic programming”. In: _International Journal of Computer Mathematics_ 92.9 (Nov. 2014), p. 1956–1975. ISSN: 1029-0265. DOI: [10.1080/00207160.2014.975218](https://doi.org/10.1080%2F00207160.2014.975218). URL: [http://dx.doi.org/10.1080/00207160.2014.975218](http://dx.doi.org/10.1080/00207160.2014.975218).

