---
title: Quality Improvement in Data Models with \emph{SL}\({}_{\mbox{FD}}\)-based {OCL}
  Constraints
author:
- Rosario Baena
- Roberto Aragón
- <a href='/people/staff/enciso/' style='color:rgb(100,0,50);'>Manuel Enciso</a>
- Carlos Rossi
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/amora/' style='color:rgb(100,0,50);'>Ángel Mora</a>
date: '2013'
categories: uncategorised
slug: 2013/QuImDaMoCo
details: '{ICSOFT} 2013 - Proceedings of the 8th International Joint Conference on
  Software Technologies, Reykjav{\''{\i}}k, Iceland, 29-31 July, 2013 , pages 563--569.'
doi: 10.5220/0004593405630569
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Baena2013></a>[[Bae+13]](#cite-Baena2013) R. Baena, R. Aragón, M. Enciso, et al. “Quality Improvement in Data Models with _SL_\(_\mboxFD\)-based OCL Constraints”. In: _ICSOFT 2013 - Proceedings of the 8th International Joint Conference on Software Technologies, Reykjav\'\ik, Iceland, 29-31 July, 2013_. Ed. by J. Cordeiro, D. A. Marca and M. van Sinderen. SciTePress, 2013, pp. 563-569. DOI: [10.5220/0004593405630569](https://doi.org/10.5220%2F0004593405630569). URL: [https://doi.org/10.5220/0004593405630569](https://doi.org/10.5220/0004593405630569).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Baena2013,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Rosario Baena and Roberto Arag{\a'o}n and Manuel Enciso and Carlos Rossi and Pablo Cordero and {\a'A}ngel Mora},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {{ICSOFT} 2013 - Proceedings of the 8th International Joint Conference on Software Technologies, Reykjav{\'{\i}}k, Iceland, 29-31 July, 2013},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Quality Improvement in Data Models with \emph{SL}\({}_{\mbox{FD}}\)-based {OCL} Constraints},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2013},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Jos{\a'e} Cordeiro and David A. Marca and Marten {van Sinderen}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {563--569},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {SciTePress},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/icsoft/BaenaAERCM13.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.5220/0004593405630569},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 23 Sep 2022 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.5220/0004593405630569},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.5220/0004593405630569" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.5220/0004593405630569" class="plumx-details" data-site="plum" data-hide-when-empty="true">Quality Improvement in Data Models with \emph{SL}\({}_{\mbox{FD}}\)-based {OCL} Constraints</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.5220/0004593405630569"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Sal_2024></a>[[1]](#cite-Sal_2024) B. Sal, D. García-Saiz, A. de la Vega, et al. “Domain-specific languages for the automated generation of datasets for industry 4.0 applications”. In: _Journal of Industrial Information Integration_ 41 (Sep. 2024), p. 100657. ISSN: 2452-414X. DOI: [10.1016/j.jii.2024.100657](https://doi.org/10.1016%2Fj.jii.2024.100657). URL: [http://dx.doi.org/10.1016/j.jii.2024.100657](http://dx.doi.org/10.1016/j.jii.2024.100657).

