---
author: Enrique Mérida Casermeiro, Domingo López-Rodríguez, Gloria Galán Marín, Juan
  Miguel Ortiz-de-Lazcano-Lobato
Status: Published
date: '2007-01-01'
slug: 2007/ThStCaAsMeMuRePo
title: Theoretical Study on the Capacity of Associative Memory with Multiple Reference
  Points
categories:
- Pattern recognition
- Neural networks
header_image: ~
details: Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial
  Intelligence and Lecture Notes in Bioinformatics), (4527), PART 1, <em>pp. 292&ndash;302</em>
doi: 10.1007/978-3-540-73053-8_29
link: 2007-iwinac/paper.pdf
project: ''
keywords: Learning systems, Pattern recognition, Probability, Problem solving, Linear
  dependence, Reference points, Computation theory
---


# Abstract


An extension to Hopfield's model of associative memory is studied in the present work. In particular, this paper is focused in giving solutions to the two main problems present in the model: the apparition of spurious patterns in the learning phase (implying the well-known and undesirable effect of storing the opposite pattern) and the problem of its reduced capacity (the probability of error in the retrieving phase increases as the number of stored patterns grows). In this work, a method to avoid spurious patterns is presented and studied, and an explanation to the previously mentioned effect is given. Another novel technique to increase the capacity of a network is proposed here, based on the idea of using several reference points when storing patterns. It is studied in depth, and an explicit formula for the capacity of the network is provided. This formula shows the linear dependence of the capacity of the new model on the number of reference points, implying the increase of the capacity in mis model. © Springer-Verlag Berlin Heidelberg 2007.












# Citation
Please, cite this work as:


<a name=bib-Casermeiro2007d></a>[[Cas+07]](#cite-Casermeiro2007d) E. M. Casermeiro, D. López-Rodríguez, G. G. Marín, et al. “Theoretical Study on the Capacity of Associative Memory with Multiple Reference Points”. In: _Bio-inspired Modeling of Cognitive Tasks, Second International Work-Conference on the Interplay Between Natural and Artificial Computation, IWINAC 2007, La Manga del Mar Menor, Spain, June 18-21, 2007, Proceedings, Part I_. Ed. by J. Mira and J. R. Álvarez. Vol. 4527. Lecture Notes in Computer Science PART 1. cited By 0; Conference of 2nd International Work-Conference on the Interplay Between Natural and Artificial Computation, IWINAC 2007 ; Conference Date: 18 June 2007 Through 21 June 2007; Conference Code:70787. La Manga del Mar Menor: Springer, 2007, pp. 292-302. DOI: [10.1007/978-3-540-73053-8_29](https://doi.org/10.1007%2F978-3-540-73053-8_29). URL:
[https://doi.org/10.1007/978-3-540-73053-8_29](https://doi.org/10.1007/978-3-540-73053-8_29).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Casermeiro2007d,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Enrique Mérida Casermeiro and Domingo López-Rodríguez and Gloria Galán Marín and Juan Miguel Ortiz-de-Lazcano-Lobato},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Bio-inspired Modeling of Cognitive Tasks, Second International Work-Conference on the Interplay Between Natural and Artificial Computation, {IWINAC} 2007, La Manga del Mar Menor, Spain, June 18-21, 2007, Proceedings, Part {I}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Theoretical Study on the Capacity of Associative Memory with Multiple Reference Points},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2007},<br>&nbsp;&nbsp;&nbsp;&nbsp;  address = {La Manga del Mar Menor},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {José Mira and José R. {\a'A}lvarez},<br>&nbsp;&nbsp;&nbsp;&nbsp;  note = {cited By 0; Conference of 2nd International Work-Conference on the Interplay Between Natural and Artificial Computation, IWINAC 2007 ; Conference Date: 18 June 2007 Through 21 June 2007; Conference Code:70787},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number = {PART 1},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {292--302},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {4527},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {An extension to Hopfield's model of associative memory is studied in the present work. In particular, this paper is focused in giving solutions to the two main problems present in the model: the apparition of spurious patterns in the learning phase (implying the well-known and undesirable effect of storing the opposite pattern) and the problem of its reduced capacity (the probability of error in the retrieving phase increases as the number of stored patterns grows). In this work, a method to avoid spurious patterns is presented and studied, and an explanation to the previously mentioned effect is given. Another novel technique to increase the capacity of a network is proposed here, based on the idea of using several reference points when storing patterns. It is studied in depth, and an explicit formula for the capacity of the network is provided. This formula shows the linear dependence of the capacity of the new model on the number of reference points, implying the increase of the capacity in mis model. © Springer-Verlag Berlin Heidelberg 2007.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/iwinac/CasermeiroLMO07.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  document_type = {Conference Paper},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/978-3-540-73053-8_29},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)},<br>&nbsp;&nbsp;&nbsp;&nbsp;  keywords = {Learning systems; Pattern recognition; Probability; Problem solving, Linear dependence; Reference points, Computation theory},<br>&nbsp;&nbsp;&nbsp;&nbsp;  source = {Scopus},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/978-3-540-73053-8_29},<br>}

:::






## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


NULL


