---
title: Structure Theorems for Closed Sets of Implicates/ Implicants in Temporal Logic
author:
- <a href='/people/staff/ipguzman/' style='color:rgb(100,0,50);'>Inma P. de Guzmán</a>
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/enciso/' style='color:rgb(100,0,50);'>Manuel Enciso</a>
date: '1999'
categories: uncategorised
slug: 1999/StThClSeImTeLo
details: Progress in Artificial Intelligence, 9th Portuguese Conference on Artificial
  Intelligence, {EPIA} '99, {\'{E}}vora, Portugal, September 21-24, 1999, Proceedings,
  Lecture Notes in Computer Science vol. 1695, pages 193--207.
doi: 10.1007/3-540-48159-1_14
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Guzman1999></a>[[GCE99]](#cite-Guzman1999) I. P. de Guzmán, P. Cordero, and M. Enciso. “Structure Theorems for Closed Sets of Implicates/ Implicants in Temporal Logic”. In: _Progress in Artificial Intelligence, 9th Portuguese Conference on Artificial Intelligence, EPIA '99, Évora, Portugal, September 21-24, 1999, Proceedings_. Ed. by P. Barahona and J. J. Alferes. Vol. 1695. Lecture Notes in Computer Science. Springer, 1999, pp. 193-207. DOI: [10.1007/3-540-48159-1\_14](https://doi.org/10.1007%2F3-540-48159-1%5C_14). URL: [https://doi.org/10.1007/3-540-48159-1\_14](https://doi.org/10.1007/3-540-48159-1\_14).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Guzman1999,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Inman P. {de Guzm{\a'a}n} and Pablo Cordero and Manuel Enciso},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Progress in Artificial Intelligence, 9th Portuguese Conference on Artificial Intelligence, {EPIA} '99, {\'{E}}vora, Portugal, September 21-24, 1999, Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Structure Theorems for Closed Sets of Implicates/ Implicants in Temporal Logic},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {1999},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Pedro Barahona and Jos{\a'e} J{\a'u}lio Alferes},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {193--207},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {1695},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/epia/GuzmanCE99.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/3-540-48159-1\_14},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Tue, 14 May 2019 10:00:41 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/3-540-48159-1\_14},<br>}

:::






## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Cordero_2004></a>[[1]](#cite-Cordero_2004) P. Cordero, G. Gutiérrez, J. Martínez, et al. “A New Algebraic Tool for Automatic Theorem Provers”. In: _Annals of Mathematics and Artificial Intelligence_ 42.4 (Dec. 2004), p. 369–398. ISSN: 1012-2443. DOI: [10.1023/b:amai.0000038312.77514.3c](https://doi.org/10.1023%2Fb%3Aamai.0000038312.77514.3c). URL: [http://dx.doi.org/10.1023/b:amai.0000038312.77514.3c](http://dx.doi.org/10.1023/b:amai.0000038312.77514.3c).

<a name=bib-Mart_nez_2005></a>[[2]](#cite-Mart_nez_2005) J. Martínez, G. Gutiérrez, I. de Guzmán, et al. “Generalizations of lattices via non-deterministic operators”. In: _Discrete Mathematics_ 295.1–3 (May. 2005), p. 107–141. ISSN: 0012-365X. DOI: [10.1016/j.disc.2004.08.043](https://doi.org/10.1016%2Fj.disc.2004.08.043). URL: [http://dx.doi.org/10.1016/j.disc.2004.08.043](http://dx.doi.org/10.1016/j.disc.2004.08.043).

