---
title: Publication of <em>Stochastic multivalued network for optimization. Application
  to the graph MaxCut problem</em>
author: Domingo López-Rodríguez, E. Mérida-Casermeiro, J.M. Ortiz-De-Lazcano-Lobato
date: '2006-11-01'
categories:
- Neural networks
- Combinatorial optimization
---

The work <u>Stochastic multivalued network for optimization. Application to the graph MaxCut problem</u> has been published in <em>International Conference on Computational Intelligence, Man-Machine Systems and Cybernetics - Proceedings, (1), <em>pp. 111-116</em></em>.

<u>Abstract</u>:


The aim of this paper is to present the stochastic version of the multivalued neural model MREM, which has achieved very good results in many applications, as an optimization technique. The purpose of this stochastic version is to avoid certain local minima of the objective function minimized by the network, that is, the energy function. To this end, the description of the theoretical bases of this model, guaranteeing the convergence to minima, is carried out rigorously. In order to show the efficiency of this new model, the model, in its two versions, deterministic and stochastic, has been applied to the resolution of the well-known problem of graph partition, MaxCut. Computational experiments show that in most cases the stochastic model achieves better results than the deterministic one.

