---
title: 'Relational Galois connections between transitive digraphs: Characterization
  and construction'
type: journals
author:
- <a href='/people/staff/ipcabrera/' style='color:rgb(100,0,50);'>Inmaculada de las
  Peñas Cabrera</a>
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero Ortega</a>
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda Aciego</a>
- Bernard De Baets
date: '2020-01-01'
categories:
- Formal concept analysis
- Fuzzy logic
- Fuzzy sets
- Uncertainty
doi: 10.1016/j.ins.2020.01.034
slug: 2020-IPC-PC-EMV-MOA-BDB-Relational
keywords: ''
project: 2019-flair
details: Information Sciences vol. 519 , pages 439 – 450.
listing:
- id: funding
  contents: funding.yml
  type: default
  sort: date desc
---




# Abstract

This paper focuses on a twofold relational generalization of the notion of Galois connection. It is twofold because it is defined between sets endowed with arbitrary transitive relations and, moreover, both components of the connection are relations, not necessarily functions. A characterization theorem of the notion of relational Galois connection is provided and, then, it is proved that a suitable notion of closure can be obtained within this framework. Finally, we state a necessary and sufficient condition that allows to build a relational Galois connection starting from a single transitive digraph and a single binary relation.


# Funding
::: {.callout-note appearance='minimal' collapse=false}
## Projects funding this work

:::{#funding}
:::
:::




# Citation
Please, cite this work as:


<a name=bib-Cabrera2020439></a>[[Cab+20]](#cite-Cabrera2020439) I. P. Cabrera, P. Cordero, E. Muñoz-Velasco, et al. “Relational Galois connections between transitive digraphs: Characterization and construction”. In: _Information Sciences_ 519 (2020). Cited by: 8; All Open Access, Green Open Access, p. 439 – 450. DOI: [10.1016/j.ins.2020.01.034](https://doi.org/10.1016%2Fj.ins.2020.01.034). URL: [https://www.scopus.com/inward/record.uri?eid=2-s2.0-85079160299&doi=10.1016

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@ARTICLE{Cabrera2020439,<br>&nbsp;&nbsp;&nbsp;&nbsp;	author = {Cabrera, Inma P. and Cordero, Pablo and Muñoz-Velasco, Emilio and Ojeda-Aciego, Manuel and De Baets, Bernard},<br>&nbsp;&nbsp;&nbsp;&nbsp;	title = {Relational Galois connections between transitive digraphs: Characterization and construction},<br>&nbsp;&nbsp;&nbsp;&nbsp;	year = {2020},<br>&nbsp;&nbsp;&nbsp;&nbsp;	journal = {Information Sciences},<br>&nbsp;&nbsp;&nbsp;&nbsp;	volume = {519},<br>&nbsp;&nbsp;&nbsp;&nbsp;	pages = {439 – 450},<br>&nbsp;&nbsp;&nbsp;&nbsp;	doi = {10.1016/j.ins.2020.01.034},<br>&nbsp;&nbsp;&nbsp;&nbsp;	url = {https://www.scopus.com/inward/record.uri?eid=2-s2.0-85079160299&doi=10.1016%2fj.ins.2020.01.034&partnerID=40&md5=2d80ac2cb125c6e9326073eb92a4f5a4},<br>&nbsp;&nbsp;&nbsp;&nbsp;	type = {Article},<br>&nbsp;&nbsp;&nbsp;&nbsp;	publication_stage = {Final},<br>&nbsp;&nbsp;&nbsp;&nbsp;	source = {Scopus},<br>&nbsp;&nbsp;&nbsp;&nbsp;	note = {Cited by: 8; All Open Access, Green Open Access}<br>}

:::

