---
title: A Multi-adjoint Logic Approach to Abductive Reasoning
author:
- Jesús Medina
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
- Peter Vojtás
date: '2001'
categories: uncategorised
slug: 2001/LoApAbRe
details: Logic Programming, 17th International Conference, {ICLP} 2001, Paphos, Cyprus,
  November 26 - December 1, 2001, Proceedings , Lecture Notes in Computer Science
  vol. 2237, pages 269--283.
doi: 10.1007/3-540-45635-X_26
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Medina2001c></a>[[MOV01]](#cite-Medina2001c) J. Medina, M. Ojeda-Aciego, and P. Vojtás. “A Multi-adjoint Logic Approach to Abductive Reasoning”. In: _Logic Programming, 17th International Conference, ICLP 2001, Paphos, Cyprus, November 26 - December 1, 2001, Proceedings_. Ed. by P. Codognet. Vol. 2237. Lecture Notes in Computer Science. Springer, 2001, pp. 269-283. DOI: [10.1007/3-540-45635-X\_26](https://doi.org/10.1007%2F3-540-45635-X%5C_26). URL: [https://doi.org/10.1007/3-540-45635-X\_26](https://doi.org/10.1007/3-540-45635-X\_26).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Medina2001c,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Jes{\a'u}s Medina and Manuel Ojeda-Aciego and Peter Vojt{\a'a}s},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Logic Programming, 17th International Conference, {ICLP} 2001, Paphos, Cyprus, November 26 - December 1, 2001, Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {A Multi-adjoint Logic Approach to Abductive Reasoning},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2001},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Philippe Codognet},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {269--283},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {2237},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/iclp/MedinaOV01.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/3-540-45635-X\_26},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Thu, 07 Jan 2021 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/3-540-45635-X\_26},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/3-540-45635-X_26" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/3-540-45635-X_26" class="plumx-details" data-site="plum" data-hide-when-empty="true">A Multi-adjoint Logic Approach to Abductive Reasoning</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1007/3-540-45635-X_26"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Bauters_2014></a>[[1]](#cite-Bauters_2014) K. Bauters, S. Schockaert, M. De Cock, et al. “Semantics for possibilistic answer set programs: Uncertain rules versus rules with uncertain conclusions”. In: _International Journal of Approximate Reasoning_ 55.2 (Jan. 2014), p. 739–761. ISSN: 0888-613X. DOI: [10.1016/j.ijar.2013.09.006](https://doi.org/10.1016%2Fj.ijar.2013.09.006). URL: [http://dx.doi.org/10.1016/j.ijar.2013.09.006](http://dx.doi.org/10.1016/j.ijar.2013.09.006).

<a name=bib-Cornejo_2022></a>[[2]](#cite-Cornejo_2022) M. E. Cornejo, L. Fariñas del Cerro, and J. Medina. “Multi-adjoint Lattice Logic. Properties and Query Answering”. In: _Progress in Artificial Intelligence_. Springer International Publishing, 2022, p. 701–712. ISBN: 9783031164743. DOI: [10.1007/978-3-031-16474-3_57](https://doi.org/10.1007%2F978-3-031-16474-3_57). URL: [http://dx.doi.org/10.1007/978-3-031-16474-3_57](http://dx.doi.org/10.1007/978-3-031-16474-3_57).

<a name=bib-Cornejo_2018></a>[[3]](#cite-Cornejo_2018) M. E. Cornejo, D. Lobo, and J. Medina. “Syntax and semantics of multi-adjoint normal logic programming”. In: _Fuzzy Sets and Systems_ 345 (Aug. 2018), p. 41–62. ISSN: 0165-0114. DOI: [10.1016/j.fss.2017.12.009](https://doi.org/10.1016%2Fj.fss.2017.12.009). URL: [http://dx.doi.org/10.1016/j.fss.2017.12.009](http://dx.doi.org/10.1016/j.fss.2017.12.009).

<a name=bib-Cornejo_2021></a>[[4]](#cite-Cornejo_2021) M. E. Cornejo and J. Medina. “Right Adjoint Algebras Versus Operator Left Residuated Posets”. In: _Rough Sets_. Springer International Publishing, 2021, p. 180–191. ISBN: 9783030873349. DOI: [10.1007/978-3-030-87334-9_15](https://doi.org/10.1007%2F978-3-030-87334-9_15). URL: [http://dx.doi.org/10.1007/978-3-030-87334-9_15](http://dx.doi.org/10.1007/978-3-030-87334-9_15).

<a name=bib-Guller_2004></a>[[5]](#cite-Guller_2004) D. Guller. “Model and Fixpoint Semantics for Fuzzy Disjunctive Programs with Weak Similarity”. In: _Innovations in Intelligent Systems_. Springer Berlin Heidelberg, 2004, p. 151–202. ISBN: 9783540396154. DOI: [10.1007/978-3-540-39615-4_7](https://doi.org/10.1007%2F978-3-540-39615-4_7). URL: [http://dx.doi.org/10.1007/978-3-540-39615-4_7](http://dx.doi.org/10.1007/978-3-540-39615-4_7).

<a name=bib-Horiuchi_2020></a>[[6]](#cite-Horiuchi_2020) K. Horiuchi, B. Šešelja, and A. Tepavčević. “Trice-valued fuzzy sets: Mathematical model for three-way decisions”. In: _Information Sciences_ 507 (Jan. 2020), p. 574–584. ISSN: 0020-0255. DOI: [10.1016/j.ins.2018.09.007](https://doi.org/10.1016%2Fj.ins.2018.09.007). URL: [http://dx.doi.org/10.1016/j.ins.2018.09.007](http://dx.doi.org/10.1016/j.ins.2018.09.007).

<a name=bib-Medina_2002></a>[[7]](#cite-Medina_2002) J. Medina, E. Mérida-Casermeiro, and M. Ojeda-Aciego. “A Neural Approach to Abductive Multi-adjoint Reasoning”. In: _Artificial Intelligence: Methodology, Systems, and Applications_. Springer Berlin Heidelberg, 2002, p. 213–222. ISBN: 9783540461487. DOI: [10.1007/3-540-46148-5_22](https://doi.org/10.1007%2F3-540-46148-5_22). URL: [http://dx.doi.org/10.1007/3-540-46148-5_22](http://dx.doi.org/10.1007/3-540-46148-5_22).

<a name=bib-Medina_2003></a>[[8]](#cite-Medina_2003) J. Medina, E. Mérida-Casermeiro, and M. Ojeda-Aciego. “A neural approach to extended logic programs”. In: _Computational Methods in Neural Modeling_. Springer Berlin Heidelberg, 2003, p. 654–661. ISBN: 9783540448686. DOI: [10.1007/3-540-44868-3_83](https://doi.org/10.1007%2F3-540-44868-3_83). URL: [http://dx.doi.org/10.1007/3-540-44868-3_83](http://dx.doi.org/10.1007/3-540-44868-3_83).

<a name=bib-Medina_2001></a>[[9]](#cite-Medina_2001) J. Medina, M. Ojeda-Aciego, and P. Vojtáš. “A Procedural Semantics for Multi-adjoint Logic Programming”. In: _Progress in Artificial Intelligence_. Springer Berlin Heidelberg, 2001, p. 290–297. ISBN: 9783540453291. DOI: [10.1007/3-540-45329-6_29](https://doi.org/10.1007%2F3-540-45329-6_29). URL: [http://dx.doi.org/10.1007/3-540-45329-6_29](http://dx.doi.org/10.1007/3-540-45329-6_29).

<a name=bib-Moreno_2014></a>[[10]](#cite-Moreno_2014) G. Moreno, J. Penabad, and C. Vázquez. “Beyond multi-adjoint logic programming”. In: _International Journal of Computer Mathematics_ 92.9 (Nov. 2014), p. 1956–1975. ISSN: 1029-0265. DOI: [10.1080/00207160.2014.975218](https://doi.org/10.1080%2F00207160.2014.975218). URL: [http://dx.doi.org/10.1080/00207160.2014.975218](http://dx.doi.org/10.1080/00207160.2014.975218).

<a name=bib-Pazos_2003></a>[[11]](#cite-Pazos_2003) J. Pazos, A. Rodríguez-Patón, and A. Silva. “Solving SAT in Linear Time with a Neural-like Membrane System”. In: _Computational Methods in Neural Modeling_. Springer Berlin Heidelberg, 2003, p. 662–669. ISBN: 9783540448686. DOI: [10.1007/3-540-44868-3_84](https://doi.org/10.1007%2F3-540-44868-3_84). URL: [http://dx.doi.org/10.1007/3-540-44868-3_84](http://dx.doi.org/10.1007/3-540-44868-3_84).

<a name=bib-Schockaert_2012></a>[[12]](#cite-Schockaert_2012) S. Schockaert, J. Janssen, and D. Vermeir. “Fuzzy Equilibrium Logic: Declarative Problem Solving in Continuous Domains”. In: _ACM Transactions on Computational Logic_ 13.4 (Oct. 2012), p. 1–39. ISSN: 1557-945X. DOI: [10.1145/2362355.2362361](https://doi.org/10.1145%2F2362355.2362361). URL: [http://dx.doi.org/10.1145/2362355.2362361](http://dx.doi.org/10.1145/2362355.2362361).

