---
title: Reductions for non-clausal theorem proving
author:
- Gabriel Aguilera
- <a href='/people/staff/ipguzman/' style='color:rgb(100,0,50);'>Inma P. de Guzmán</a>
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
- Agustín Valverde
date: '2001'
categories: uncategorised
slug: 2001/ReThPr
details: Theor. Comput. Sci. vol. 266 (1-2), pages 81--112.
doi: 10.1016/S0304-3975(00)00044-X
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Aguilera2001></a>[[Agu+01]](#cite-Aguilera2001) G. Aguilera, I. P. de Guzmán, M. Ojeda-Aciego, et al. “Reductions for non-clausal theorem proving”. In: _Theor. Comput. Sci._ 266.1-2 (2001), pp. 81-112. DOI: [10.1016/S0304-3975(00)00044-X](https://doi.org/10.1016%2FS0304-3975%2800%2900044-X). URL: [https://doi.org/10.1016/S0304-3975(00)00044-X](https://doi.org/10.1016/S0304-3975(00)00044-X).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{Aguilera2001,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Gabriel Aguilera and Inman P. {de Guzm{\a'a}n} and Manuel Ojeda-Aciego and Agust\'\in Valverde},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Theor. Comput. Sci.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Reductions for non-clausal theorem proving},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2001},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number = {1-2},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {81--112},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {266},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/tcs/AguileraGOV01.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1016/S0304-3975(00)00044-X},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 26 May 2023 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1016/S0304-3975(00)00044-X},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1016/S0304-3975(00)00044-X" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1016/S0304-3975(00)00044-X" class="plumx-details" data-site="plum" data-hide-when-empty="true">Reductions for non-clausal theorem proving</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1016/S0304-3975(00)00044-X"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Aguilera_Venegas_2015></a>[[1]](#cite-Aguilera_Venegas_2015) G. Aguilera-Venegas, J. L. Galán-García, M. á. Galán-García, et al. “Teaching Semantic Tableaux Method for Propositional Classical Logic with a CAS”. In: _International Journal for Technology in Mathematics Education_ 22.2 (Jun. 2015), p. 85–91. ISSN: 1744-2710. DOI: [10.1564/tme_v22.2.07](https://doi.org/10.1564%2Ftme_v22.2.07). URL: [http://dx.doi.org/10.1564/tme_v22.2.07](http://dx.doi.org/10.1564/tme_v22.2.07).

<a name=bib-Aguilera_1999></a>[[2]](#cite-Aguilera_1999) G. Aguilera, I. P. de Guzmán, M. Ojeda-Aciego, et al. “Reducing signed propositional formulas”. In: _Soft Computing - A Fusion of Foundations, Methodologies and Applications_ 2.4 (Feb. 1999), p. 157–166. ISSN: 1433-7479. DOI: [10.1007/s005000050048](https://doi.org/10.1007%2Fs005000050048). URL: [http://dx.doi.org/10.1007/s005000050048](http://dx.doi.org/10.1007/s005000050048).

<a name=bib-Cordero_2002></a>[[3]](#cite-Cordero_2002) P. Cordero, M. Enciso, and I. de Guzmán. “Bases for closed sets of implicants and implicates in temporal logic”. In: _Acta Informatica_ 38.9 (Aug. 2002), p. 599–619. ISSN: 1432-0525. DOI: [10.1007/s00236-002-0087-2](https://doi.org/10.1007%2Fs00236-002-0087-2). URL: [http://dx.doi.org/10.1007/s00236-002-0087-2](http://dx.doi.org/10.1007/s00236-002-0087-2).

<a name=bib-Cordero_2004></a>[[4]](#cite-Cordero_2004) P. Cordero, G. Gutiérrez, J. Martínez, et al. “A New Algebraic Tool for Automatic Theorem Provers”. In: _Annals of Mathematics and Artificial Intelligence_ 42.4 (Dec. 2004), p. 369–398. ISSN: 1012-2443. DOI: [10.1023/b:amai.0000038312.77514.3c](https://doi.org/10.1023%2Fb%3Aamai.0000038312.77514.3c). URL: [http://dx.doi.org/10.1023/b:amai.0000038312.77514.3c](http://dx.doi.org/10.1023/b:amai.0000038312.77514.3c).

<a name=bib-Ferrari_2012></a>[[5]](#cite-Ferrari_2012) M. Ferrari, C. Fiorentini, and G. Fiorino. “Simplification Rules for Intuitionistic Propositional Tableaux”. In: _ACM Transactions on Computational Logic_ 13.2 (Apr. 2012), p. 1–23. ISSN: 1557-945X. DOI: [10.1145/2159531.2159536](https://doi.org/10.1145%2F2159531.2159536). URL: [http://dx.doi.org/10.1145/2159531.2159536](http://dx.doi.org/10.1145/2159531.2159536).

<a name=bib-Guti_rrez_2000></a>[[6]](#cite-Guti_rrez_2000) G. Gutiérrez, I. P. de Guzmán, J. Martínez, et al. “Reduction Theorems for Boolean Formulas Using Δ-Trees”. In: _Logics in Artificial Intelligence_. Springer Berlin Heidelberg, 2000, p. 179–192. ISBN: 9783540400066. DOI: [10.1007/3-540-40006-0_13](https://doi.org/10.1007%2F3-540-40006-0_13). URL: [http://dx.doi.org/10.1007/3-540-40006-0_13](http://dx.doi.org/10.1007/3-540-40006-0_13).

<a name=bib-de_Guzm_n_20021></a>[[7]](#cite-de_Guzm_n_20021) I. de Guzmán, M. Ojeda-Aciego, and A. Valverde. “Restricted Δ-Trees in Multiple-Valued Logics”. In: _Artificial Intelligence: Methodology, Systems, and Applications_. Springer Berlin Heidelberg, 2002, p. 223–232. ISBN: 9783540461487. DOI: [10.1007/3-540-46148-5_23](https://doi.org/10.1007%2F3-540-46148-5_23). URL: [http://dx.doi.org/10.1007/3-540-46148-5_23](http://dx.doi.org/10.1007/3-540-46148-5_23).

<a name=bib-de_Guzm_n_2002></a>[[8]](#cite-de_Guzm_n_2002) I. P. de Guzmán, M. Ojeda-Aciego, and A. Valverde. “Restricted Δ-Trees and Reduction Theorems in Multiple-Valued Logics”. In: _Advances in Artificial Intelligence — IBERAMIA 2002_. Springer Berlin Heidelberg, 2002, p. 161–171. ISBN: 9783540361312. DOI: [10.1007/3-540-36131-6_17](https://doi.org/10.1007%2F3-540-36131-6_17). URL: [http://dx.doi.org/10.1007/3-540-36131-6_17](http://dx.doi.org/10.1007/3-540-36131-6_17).

<a name=bib-He_2012></a>[[9]](#cite-He_2012) X. He, Y. Xu, J. Liu, et al. “α-Generalized lock resolution method in linguistic truth-valued lattice-valued logic”. In: _International Journal of Computational Intelligence Systems_ 5.6 (2012), p. 1120. ISSN: 1875-6883. DOI: [10.1080/18756891.2012.747665](https://doi.org/10.1080%2F18756891.2012.747665). URL: [http://dx.doi.org/10.1080/18756891.2012.747665](http://dx.doi.org/10.1080/18756891.2012.747665).

<a name=bib-Imaz_2023></a>[[10]](#cite-Imaz_2023) G. E. Imaz. “A first polynomial non-clausal class in many-valued logic”. In: _Fuzzy Sets and Systems_ 456 (Mar. 2023), p. 1–37. ISSN: 0165-0114. DOI: [10.1016/j.fss.2022.10.008](https://doi.org/10.1016%2Fj.fss.2022.10.008). URL: [http://dx.doi.org/10.1016/j.fss.2022.10.008](http://dx.doi.org/10.1016/j.fss.2022.10.008).

<a name=bib-Ma_2007></a>[[11]](#cite-Ma_2007) J. Ma, W. Li, D. Ruan, et al. “Filter-based resolution principle for lattice-valued propositional logic LP(X)”. In: _Information Sciences_ 177.4 (Feb. 2007), p. 1046–1062. ISSN: 0020-0255. DOI: [10.1016/j.ins.2006.07.027](https://doi.org/10.1016%2Fj.ins.2006.07.027). URL: [http://dx.doi.org/10.1016/j.ins.2006.07.027](http://dx.doi.org/10.1016/j.ins.2006.07.027).

<a name=bib-Mart_n_Mateos_2003></a>[[12]](#cite-Mart_n_Mateos_2003) F. J. Martín-Mateos, J. A. Alonso, M. J. Hidalgo, et al. “Verification in ACL2 of a Generic Framework to Synthesize SAT-Provers”. In: _Logic Based Program Synthesis and Transformation_. Springer Berlin Heidelberg, 2003, p. 182–198. ISBN: 9783540450139. DOI: [10.1007/3-540-45013-0_15](https://doi.org/10.1007%2F3-540-45013-0_15). URL: [http://dx.doi.org/10.1007/3-540-45013-0_15](http://dx.doi.org/10.1007/3-540-45013-0_15).

<a name=bib-Mart_nez_2005></a>[[13]](#cite-Mart_nez_2005) J. Martínez, G. Gutiérrez, I. de Guzmán, et al. “Generalizations of lattices via non-deterministic operators”. In: _Discrete Mathematics_ 295.1–3 (May. 2005), p. 107–141. ISSN: 0012-365X. DOI: [10.1016/j.disc.2004.08.043](https://doi.org/10.1016%2Fj.disc.2004.08.043). URL: [http://dx.doi.org/10.1016/j.disc.2004.08.043](http://dx.doi.org/10.1016/j.disc.2004.08.043).

<a name=bib-Ojeda_Aciego_2004></a>[[14]](#cite-Ojeda_Aciego_2004) M. Ojeda-Aciego and A. Valverde. “tascpl: TAS Solver for Classical Propositional Logic”. In: _Logics in Artificial Intelligence_. Springer Berlin Heidelberg, 2004, p. 738–741. ISBN: 9783540302278. DOI: [10.1007/978-3-540-30227-8_70](https://doi.org/10.1007%2F978-3-540-30227-8_70). URL: [http://dx.doi.org/10.1007/978-3-540-30227-8_70](http://dx.doi.org/10.1007/978-3-540-30227-8_70).

<a name=bib-Pearce_2000></a>[[15]](#cite-Pearce_2000) D. Pearce, I. P. de Guzmán, and A. Valverde. “Computing Equilibrium Models Using Signed Formulas”. In: _Computational Logic — CL 2000_. Springer Berlin Heidelberg, 2000, p. 688–702. ISBN: 9783540449577. DOI: [10.1007/3-540-44957-4_46](https://doi.org/10.1007%2F3-540-44957-4_46). URL: [http://dx.doi.org/10.1007/3-540-44957-4_46](http://dx.doi.org/10.1007/3-540-44957-4_46).

<a name=bib-Xu_2013></a>[[16]](#cite-Xu_2013) Y. Xu, J. Liu, X. Zhong, et al. “Multiary α-Resolution Principle for a Lattice-Valued Logic”. In: _IEEE Transactions on Fuzzy Systems_ 21.5 (Oct. 2013), p. 898–912. ISSN: 1941-0034. DOI: [10.1109/tfuzz.2012.2236095](https://doi.org/10.1109%2Ftfuzz.2012.2236095). URL: [http://dx.doi.org/10.1109/tfuzz.2012.2236095](http://dx.doi.org/10.1109/tfuzz.2012.2236095).

<a name=bib-Zhong_2012></a>[[17]](#cite-Zhong_2012) X. Zhong, Y. Xu, J. Liu, et al. “General form of α-resolution principle for linguistic truth-valued lattice-valued logic”. In: _Soft Computing_ 16.10 (Jun. 2012), p. 1767–1781. ISSN: 1433-7479. DOI: [10.1007/s00500-012-0860-2](https://doi.org/10.1007%2Fs00500-012-0860-2). URL: [http://dx.doi.org/10.1007/s00500-012-0860-2](http://dx.doi.org/10.1007/s00500-012-0860-2).

