---
title: A Similarity-Based Unification Model for Flexible Querying
author:
- Stanislav Krajci
- Rastislav Lencses
- Jesús Medina
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
- Peter Vojtás
date: '2002'
categories: uncategorised
slug: 2002/UnMoFlQu
details: Flexible Query Answering Systems, 5th International Conference, {FQAS} 2002,
  Copenhagen, Denmark, October 27-29, 2002, Proceedings , Lecture Notes in Computer
  Science vol. 2522, pages 263--273.
doi: 10.1007/3-540-36109-X_21
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Krajci2002></a>[[Kra+02]](#cite-Krajci2002) S. Krajci, R. Lencses, J. Medina, et al. “A Similarity-Based Unification Model for Flexible Querying”. In: _Flexible Query Answering Systems, 5th International Conference, FQAS 2002, Copenhagen, Denmark, October 27-29, 2002, Proceedings_. Ed. by T. Andreasen, A. Motro, H. Christiansen and H. L. Larsen. Vol. 2522. Lecture Notes in Computer Science. Springer, 2002, pp. 263-273. DOI: [10.1007/3-540-36109-X\_21](https://doi.org/10.1007%2F3-540-36109-X%5C_21). URL: [https://doi.org/10.1007/3-540-36109-X\_21](https://doi.org/10.1007/3-540-36109-X\_21).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Krajci2002,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Stanislav Krajci and Rastislav Lencses and Jes{\a'u}s Medina and Manuel Ojeda-Aciego and Peter Vojt{\a'a}s},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Flexible Query Answering Systems, 5th International Conference, {FQAS} 2002, Copenhagen, Denmark, October 27-29, 2002, Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {A Similarity-Based Unification Model for Flexible Querying},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2002},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Troels Andreasen and Amihai Motro and Henning Christiansen and Henrik Legind Larsen},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {263--273},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {2522},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/fqas/KrajciLMOV02.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/3-540-36109-X\_21},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Thu, 07 Jan 2021 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/3-540-36109-X\_21},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/3-540-36109-X_21" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/3-540-36109-X_21" class="plumx-details" data-site="plum" data-hide-when-empty="true">A Similarity-Based Unification Model for Flexible Querying</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1007/3-540-36109-X_21"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Krajca_2013></a>[[1]](#cite-Krajca_2013) P. Krajca and V. Vychodil. “Foundations of relational similarity-based query language RESIQL”. In: _2013 IEEE Symposium on Foundations of Computational Intelligence (FOCI)_. IEEE, Apr. 2013, p. 15–23. DOI: [10.1109/foci.2013.6602450](https://doi.org/10.1109%2Ffoci.2013.6602450). URL: [http://dx.doi.org/10.1109/foci.2013.6602450](http://dx.doi.org/10.1109/foci.2013.6602450).

<a name=bib-Medina_2004></a>[[2]](#cite-Medina_2004) J. Medina, M. Ojeda-Aciego, and P. Vojtáš. “Similarity-based unification: a multi-adjoint approach”. In: _Fuzzy Sets and Systems_ 146.1 (Aug. 2004), p. 43–62. ISSN: 0165-0114. DOI: [10.1016/j.fss.2003.11.005](https://doi.org/10.1016%2Fj.fss.2003.11.005). URL: [http://dx.doi.org/10.1016/j.fss.2003.11.005](http://dx.doi.org/10.1016/j.fss.2003.11.005).

