---
author: Enrique Mérida Casermeiro, Domingo López-Rodríguez, Gloria Galán Marín, Juan
  Miguel Ortiz-de-Lazcano-Lobato
Status: Published
date: '2007-01-01'
slug: 2007/ImPrCoLeRuAdTeVeQu
title: Improved Production of Competitive Learning Rules with an Additional Term for
  Vector Quantization
categories:
- Competitive learning
- Neural networks
- Image processing
header_image: ~
details: Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial
  Intelligence and Lecture Notes in Bioinformatics), (4431), PART 1, <em>pp. 461&ndash;469</em>
doi: 10.1007/978-3-540-71618-1_51
link: 2007-icannga2/paper.pdf
project: ''
keywords: Mathematical models, Perturbation techniques, Vector quantization, Competitive
  learning, Distortion function, Learning rules, Specialized literature, Learning
  systems
---


# Abstract


In this work, a general framework for developing learning rules with an added term (perturbation term) is presented. Many learning rules commonly cited in the specialized literature can be derived from this general framework. This framework allows us to introduce some knowledge about vector quantization (as an optimization problem) in the distortion function in order to derive a new learning rule that uses that information to avoid certain local minima of the distortion function, leading to better performance than classical models. Computational experiments in image compression show that our proposed rule, derived from this general framework, can achieve better results than simple competitive learning and other models, with codebooks of less distortion. © Springer-Verlag Berlin Heidelberg 2007.












# Citation
Please, cite this work as:


<a name=bib-Casermeiro2007b></a>[[Cas+07]](#cite-Casermeiro2007b) E. M. Casermeiro, D. López-Rodríguez, G. G. Marín, et al. “Improved Production of Competitive Learning Rules with an Additional Term for Vector Quantization”. In: _Adaptive and Natural Computing Algorithms, 8th International Conference, ICANNGA 2007, Warsaw, Poland, April 11-14, 2007, Proceedings, Part I_. Ed. by B. Beliczynski, A. Dzielinski, M. Iwanowski and B. Ribeiro. Vol. 4431. Lecture Notes in Computer Science PART 1. cited By 1; Conference of 8th International Conference on Adaptive and Natural Computing Algorithms, ICANNGA 2007 ; Conference Date: 11 April 2007 Through 14 April 2007; Conference Code:71057. Warsaw: Springer, 2007, pp. 461-469. DOI: [10.1007/978-3-540-71618-1_51](https://doi.org/10.1007%2F978-3-540-71618-1_51). URL:
[https://doi.org/10.1007/978-3-540-71618-1_51](https://doi.org/10.1007/978-3-540-71618-1_51).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Casermeiro2007b,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Enrique Mérida Casermeiro and Domingo López-Rodríguez and Gloria Galán Marín and Juan Miguel Ortiz-de-Lazcano-Lobato},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Adaptive and Natural Computing Algorithms, 8th International Conference, {ICANNGA} 2007, Warsaw, Poland, April 11-14, 2007, Proceedings, Part {I}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Improved Production of Competitive Learning Rules with an Additional Term for Vector Quantization},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2007},<br>&nbsp;&nbsp;&nbsp;&nbsp;  address = {Warsaw},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Bartlomiej Beliczynski and Andrzej Dzielinski and Marcin Iwanowski and Bernardete Ribeiro},<br>&nbsp;&nbsp;&nbsp;&nbsp;  note = {cited By 1; Conference of 8th International Conference on Adaptive and Natural Computing Algorithms, ICANNGA 2007 ; Conference Date: 11 April 2007 Through 14 April 2007; Conference Code:71057},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number = {PART 1},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {461--469},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {4431},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {In this work, a general framework for developing learning rules with an added term (perturbation term) is presented. Many learning rules commonly cited in the specialized literature can be derived from this general framework. This framework allows us to introduce some knowledge about vector quantization (as an optimization problem) in the distortion function in order to derive a new learning rule that uses that information to avoid certain local minima of the distortion function, leading to better performance than classical models. Computational experiments in image compression show that our proposed rule, derived from this general framework, can achieve better results than simple competitive learning and other models, with codebooks of less distortion. © Springer-Verlag Berlin Heidelberg 2007.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/icannga/CasermeiroLMO07.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  document_type = {Conference Paper},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/978-3-540-71618-1_51},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)},<br>&nbsp;&nbsp;&nbsp;&nbsp;  keywords = {Mathematical models; Perturbation techniques; Vector quantization, Competitive learning; Distortion function; Learning rules; Specialized literature, Learning systems},<br>&nbsp;&nbsp;&nbsp;&nbsp;  source = {Scopus},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/978-3-540-71618-1_51},<br>}

:::



# Bibliometric data


The following data has been extracted from free resources such as [OpenAlex](https://openalex.org/) or [Dimensions](https://app.dimensions.ai/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/978-3-540-71618-1_51" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/978-3-540-71618-1_51" class="plumx-details" data-site="plum" data-hide-when-empty="true">Improved Production of Competitive Learning Rules with an Additional Term for Vector Quantization</a></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Liu_2014></a>[[1]](#cite-Liu_2014) R. Liu, B. Li, L. Zhang, et al. “A new two-step learning vector quantization algorithm for image compression”. In: _Transactions of the Institute of Measurement and Control_ 37.1 (Jun. 2014), p. 3–14. ISSN: 1477-0369. DOI: [10.1177/0142331213520178](https://doi.org/10.1177%2F0142331213520178). URL: [http://dx.doi.org/10.1177/0142331213520178](http://dx.doi.org/10.1177/0142331213520178).


