---
title: Closeness and Distance Relations in Order of Magnitude Qualitative Reasoning
  via {PDL}
author:
- Alfredo Burrieza
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '2009'
categories: uncategorised
slug: 2009/ClDiReOrMaQuReVi
details: Current Topics in Artificial Intelligence, 13th Conference of the Spanish
  Association for Artificial Intelligence, {CAEPIA} 2009, Seville, Spain, November
  9-13, 2009. Selected Papers , Lecture Notes in Computer Science vol. 5988, pages
  71--80.
doi: 10.1007/978-3-642-14264-2_8
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Burrieza2009a></a>[[BMO09]](#cite-Burrieza2009a) A. Burrieza, E. Mu~noz-Velasco, and M. Ojeda-Aciego. “Closeness and Distance Relations in Order of Magnitude Qualitative Reasoning via PDL”. In: _Current Topics in Artificial Intelligence, 13th Conference of the Spanish Association for Artificial Intelligence, CAEPIA 2009, Seville, Spain, November 9-13, 2009. Selected Papers_. Ed. by P. Meseguer, L. Mandow and R. M. Gasca. Vol. 5988. Lecture Notes in Computer Science. Springer, 2009, pp. 71-80. DOI: [10.1007/978-3-642-14264-2\_8](https://doi.org/10.1007%2F978-3-642-14264-2%5C_8). URL: [https://doi.org/10.1007/978-3-642-14264-2\_8](https://doi.org/10.1007/978-3-642-14264-2\_8).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Burrieza2009a,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Alfredo Burrieza and Emilio Mu~noz-Velasco and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Current Topics in Artificial Intelligence, 13th Conference of the Spanish Association for Artificial Intelligence, {CAEPIA} 2009, Seville, Spain, November 9-13, 2009. Selected Papers},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Closeness and Distance Relations in Order of Magnitude Qualitative Reasoning via {PDL}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2009},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Pedro Meseguer and Lawrence Mandow and Rafael M. Gasca},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {71--80},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {5988},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/caepia/BurriezaMO09.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/978-3-642-14264-2\_8},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Tue, 14 May 2019 10:00:50 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/978-3-642-14264-2\_8},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/978-3-642-14264-2_8" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/978-3-642-14264-2_8" class="plumx-details" data-site="plum" data-hide-when-empty="true">Closeness and Distance Relations in Order of Magnitude Qualitative Reasoning via {PDL}</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1007/978-3-642-14264-2_8"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Goli_ska_Pilarek_2012></a>[[1]](#cite-Goli_ska_Pilarek_2012) J. Golińska-Pilarek and E. Muñoz-Velasco. “Reasoning with Qualitative Velocity: Towards a Hybrid Approach”. In: _Hybrid Artificial Intelligent Systems_. Springer Berlin Heidelberg, 2012, p. 635–646. ISBN: 9783642289422. DOI: [10.1007/978-3-642-28942-2_57](https://doi.org/10.1007%2F978-3-642-28942-2_57). URL: [http://dx.doi.org/10.1007/978-3-642-28942-2_57](http://dx.doi.org/10.1007/978-3-642-28942-2_57).

