---
author: Enrique Mérida Casermeiro, Domingo López-Rodríguez
Status: Published
date: '2005-01-01'
slug: 2005-iwann1
title: Graph Partitioning via Recurrent Multivalued Neural Networks
categories:
- Combinatorial optimization
- Neural networks
header_image: ~
details: International Work-Conference on Artificial Neural Networks (IWANN) 2005,
  Lecture Notes in Computer Science, (3512), <em>pp. 1149&ndash;1156</em>
doi: 10.1007/11494669_141
link: 2005-iwann1/paper.pdf
project: ''
keywords: Algorithms, Computational methods, Computer simulation, Graph theory, Optimization,
  Problem solving, Computational time, Graph partitioning, Optimization problems,
  Neural networks
---



# Abstract


In this work, the well-known Graph Partitioning (GP) problem for undirected weighted graphs has been studied from two points of view: maximizing (MaxCut) or minimizing (MinCut) the cost of the cut induced in the graph by the partition. An unified model, based on a neural technique for optimization problems, has been applied to these two concrete problems. A detailed description of the model is presented, and the technique to minimize an energy function, that measures the goodness of solutions, is fully described. Some techniques to escape from local optima are presented as well. It has proved to be a very competitive and efficient algorithm, in terms of quality of solutions and computational time, when compared to the state-of-the-art methods. Some simulation results are presented in this paper, to show the comparative efficiency of the methods.





# Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```


# Citation
Please, cite this work as:


<a name=bib-Casermeiro2005a></a>[[CL05]](#cite-Casermeiro2005a) E. M. Casermeiro and D. López-Rodríguez. “Graph Partitioning via Recurrent Multivalued Neural Networks”. In: _Computational Intelligence and Bioinspired Systems, 8th International Work-Conference on Artificial Neural Networks, IWANN 2005, Vilanova i la Geltrú, Barcelona, Spain, June 8-10, 2005, Proceedings_. Ed. by J. Cabestany, A. Prieto and F. S. Hernández. Vol. 3512. Lecture Notes in Computer Science. Vilanova i la Geltru: Springer, 2005, pp. 1149-1156. DOI: [10.1007/11494669_141](https://doi.org/10.1007%2F11494669_141). URL: [https://doi.org/10.1007/11494669\_141](https://doi.org/10.1007/11494669\_141).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Casermeiro2005a,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Enrique Mérida Casermeiro and Domingo López-Rodríguez},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Computational Intelligence and Bioinspired Systems, 8th International Work-Conference on Artificial Neural Networks, {IWANN} 2005, Vilanova i la Geltrú, Barcelona, Spain, June 8-10, 2005, Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Graph Partitioning via Recurrent Multivalued Neural Networks},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2005},<br>&nbsp;&nbsp;&nbsp;&nbsp;  address = {Vilanova i la Geltru},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Joan Cabestany and Alberto Prieto and Francisco Sandoval Hernández},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {1149--1156},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {3512},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {In this work, the well-known Graph Partitioning (GP) problem for undirected weighted graphs has been studied from two points of view: maximizing (MaxCut) or minimizing (MinCut) the cost of the cut induced in the graph by the partition. An unified model, based on a neural technique for optimization problems, has been applied to these two concrete problems. A detailed description of the model is presented, and the technique to minimize an energy function, that measures the goodness of solutions, is fully described. Some techniques to escape from local optima are presented as well. It has proved to be a very competitive and efficient algorithm, in terms of quality of solutions and computational time, when compared to the state-of-the-art methods. Some simulation results are presented in this paper, to show the comparative efficiency of the methods. © Springer-Verlag Berlin Heidelberg 2005.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/iwann/CasermeiroL05.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  document_type = {Conference Paper},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/11494669_141},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  keywords = {Algorithms; Computational methods; Computer simulation; Graph theory; Optimization; Problem solving, Computational time; Graph partitioning; Optimization problems, Neural networks},<br>&nbsp;&nbsp;&nbsp;&nbsp;  source = {Scopus},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Tue, 14 May 2019 10:00:51 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/11494669\_141},<br>}

:::


