---
author: Ángel Mora Bonilla, Domingo López-Rodríguez, Enrique Mérida-Casermeiro
Status: Published
date: '2007-08-01T00:00:00Z'
slug: 2007-blended
title: 'HECACEJ: B-Learning Tool for Static Content Creation in Joomla!'
categories: E-learning
header_image: ~
details: <em>Workshop on Blended Learning</em> 2007
doi: ''
link: 2007-blended/paper.pdf
project: ~
keywords: B-learning, LMS, CMS, Joomla!, Integration of tools
---



# Abstract


In this work we have reviewed the concepts of Learning Managementystem (LMS), Learning Content Management System (LCMS) and Content Management System (CMS). Their main features are studied, and a comparison among them is presented, along with a summary of some well- known integrations between LMS and CMS. Another important point in this work is presenting HECACEJ, a B-learning tool designed to create static content in Joomla! This tool is a specific content manager for publishing the material for a subject, which does not need help from the administration menu of Joomla! (difficult to use by a non-expert professor) and is able to publish these contents in Joomla! main menu. This tool eases the publication of B- learning contents (class notes, past exams, professors' data, etc.) in a static web page that can be accessed from the main menu of the platform Joomla!, which provides facilities for manipulating the contents but it was not developed ad- hoc for our proposal.





# Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```


# Citation
Please, cite this work as:


<a name=bib-mora2007hecacej></a>[[Mor+07]](#cite-mora2007hecacej) A. Mora-Bonilla, D. López-Rodríguez, E. Mérida-Casermeiro, et al. “HECACEJ: B-Learning Tool for Static Content Creation in Joomla!” In: _Blended Learning_. Vol. 2007. 2007, pp. 227-236.

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@inproceedings{mora2007hecacej,<br>&nbsp;&nbsp;&nbsp;&nbsp;  title={HECACEJ: B-Learning Tool for Static Content Creation in Joomla!},<br>&nbsp;&nbsp;&nbsp;&nbsp;  author={Mora-Bonilla, Angel and López-Rodríguez, Domingo and Mérida-Casermeiro, Enrique and Merino-Córdoba, Salvador},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle={Blended Learning},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume={2007},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages={227--236},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year={2007}<br>}

:::


