---
title: A graphical approach to monad compositions
author:
- Patrik Eklund
- Maria A. Galán
- Jesús Medina
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
- Agustín Valverde
date: '2000'
categories: uncategorised
slug: 2000/GrApMoCo
details: First Irish Conference on the Mathematical Foundations of Computer Science
  and Information Technology, {MFCSIT} 2000, Cork, Ireland, July 20-21, 2000 , Electronic
  Notes in Theoretical Computer Science vol. 40, pages 145--160.
doi: 10.1016/S1571-0661(05)80041-6
---



# Abstract


In this paper we show how composite expressions involving natural transformations can be pictorially represented in order to provide graphical proof support for providing monad compositions. Examples are drawn using powerset monads composed with the term monad.








# Citation
Please, cite this work as:


<a name=bib-Eklund2000></a>[[Ekl+00]](#cite-Eklund2000) P. Eklund, M. A. Galán, J. Medina, et al. “A graphical approach to monad compositions”. In: _First Irish Conference on the Mathematical Foundations of Computer Science and Information Technology, MFCSIT 2000, Cork, Ireland, July 20-21, 2000_. Ed. by T. Hurley, M. M. an Airchinnigh, M. P. Schellekens and A. K. Seda. Vol. 40. Electronic Notes in Theoretical Computer Science. Elsevier, 2000, pp. 145-160. DOI: [10.1016/S1571-0661(05)80041-6](https://doi.org/10.1016%2FS1571-0661%2805%2980041-6). URL: [https://doi.org/10.1016/S1571-0661(05)80041-6](https://doi.org/10.1016/S1571-0661(05)80041-6).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Eklund2000,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Patrik Eklund and Maria A. Gal{\a'a}n and Jes{\a'u}s Medina and Manuel Ojeda-Aciego and Agust\'\in Valverde},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {First Irish Conference on the Mathematical Foundations of Computer Science and Information Technology, {MFCSIT} 2000, Cork, Ireland, July 20-21, 2000},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {A graphical approach to monad compositions},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2000},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Ted Hurley and M\'\iche{\a'a}l Mac {an Airchinnigh} and Michel P. Schellekens and Anthony Karel Seda},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {145--160},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Elsevier},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Electronic Notes in Theoretical Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {40},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/entcs/EklundGMOV00.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1016/S1571-0661(05)80041-6},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Wed, 30 Nov 2022 10:58:03 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1016/S1571-0661(05)80041-6},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1016/S1571-0661(05)80041-6" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1016/S1571-0661(05)80041-6" class="plumx-details" data-site="plum" data-hide-when-empty="true">A graphical approach to monad compositions</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1016/S1571-0661(05)80041-6"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Eklund_2002></a>[[1]](#cite-Eklund_2002) P. Eklund, M. Galán, J. Medina, et al. “A categorical approach to unification of generalised terms1 1This work has been developed as a cooperation organised within COST 274.” In: _Electronic Notes in Theoretical Computer Science_ 66.5 (Dec. 2002), p. 41–51. ISSN: 1571-0661. DOI: [10.1016/s1571-0661(04)80513-9](https://doi.org/10.1016%2Fs1571-0661%2804%2980513-9). URL: [http://dx.doi.org/10.1016/s1571-0661(04)80513-9](http://dx.doi.org/10.1016/s1571-0661(04)80513-9).

<a name=bib-Kozen_2006></a>[[2]](#cite-Kozen_2006) D. Kozen, C. Kreitz, and E. Richter. “Automating Proofs in Category Theory”. In: _Automated Reasoning_. Springer Berlin Heidelberg, 2006, p. 392–407. ISBN: 9783540371885. DOI: [10.1007/11814771_34](https://doi.org/10.1007%2F11814771_34). URL: [http://dx.doi.org/10.1007/11814771_34](http://dx.doi.org/10.1007/11814771_34).

<a name=bib-Motara_2021></a>[[3]](#cite-Motara_2021) Y. M. Motara. “High-Level Modelling for Typed Functional Programming”. In: _Trends in Functional Programming_. Springer International Publishing, 2021, p. 69–94. ISBN: 9783030839789. DOI: [10.1007/978-3-030-83978-9_4](https://doi.org/10.1007%2F978-3-030-83978-9_4). URL: [http://dx.doi.org/10.1007/978-3-030-83978-9_4](http://dx.doi.org/10.1007/978-3-030-83978-9_4).

<a name=bib-Motara_2020></a>[[4]](#cite-Motara_2020) Y. M. Motara. “String Diagrams for Modelling Functional Programming”. In: _2020 2nd International Multidisciplinary Information Technology and Engineering Conference (IMITEC)_. IEEE, Nov. 2020, p. 1–7. DOI: [10.1109/imitec50163.2020.9334072](https://doi.org/10.1109%2Fimitec50163.2020.9334072). URL: [http://dx.doi.org/10.1109/imitec50163.2020.9334072](http://dx.doi.org/10.1109/imitec50163.2020.9334072).

