---
author:
- Ondrej Krídlo
- Domingo López-Rodríguez
- Lubomir Antoni
- Peter Eliaš
- Stanislav Krajči
- Manuel Ojeda-Aciego
Status: Published
selected: yes
date: '2023-08-03T00:00:00Z'
slug: 2023-insci
title: Connecting concept lattices with bonds induced by external information
categories: Formal concept analysis
header_image: ~
details: <em>Information Sciences</em>, vol. 648, november 2023, article 119498
doi: 10.1016/j.ins.2023.119498
link: 2023-insci/paper.pdf
project: 2023-valid
keywords: Formal Concept Analysis, Intercontextual structures, Bonds
listing:
- id: funding
  contents: funding.yml
  type: default
  sort: date desc
---



# Abstract


In Formal Concept Analysis (FCA), $\mathcal L$-bonds represent relationships between $\mathcal L$-formal contexts. Choosing the appropriate bond between $\mathcal L$-fuzzy formal contexts is an important challenge for its application in recommendation tasks. Recent work introduced two constructions of bonds, given by direct products of two $\mathcal L$-fuzzy formal contexts, and showed their usefulness in a particular application. In this paper, we present further theoretical and experimental results on these constructions; in particular, we provide extended interpretations of both rigorous and benevolent concept-forming operators, introduce new theoretical properties of the proposed bonds to connect two concept lattices given external information, and finally present the experimental study of the upper bounds.




# Funding
::: {.callout-note appearance='minimal' collapse=false}
## Projects funding this work

:::{#funding}
:::
:::




# Citation
Please, cite this work as:


<a name=bib-insci2023></a>[[Krí+23]](#cite-insci2023) O. Krídlo, D. López-Rodríguez, L. Antoni, et al. “Connecting concept lattices with bonds induced by external information”. In: _Information Sciences_ (2023), p. 119498.

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@article{insci2023,<br>&nbsp;&nbsp;&nbsp;&nbsp;  title={Connecting concept lattices with bonds induced by external information},<br>&nbsp;&nbsp;&nbsp;&nbsp;  author={Ondrej Krídlo and Domingo López-Rodríguez and Lubomir Antoni and Peter Eliaš and Stanislav Krajči and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal={Information Sciences},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages={119498},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year={2023},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher={Elsevier}<br>}

:::


