---
author:
- Pablo Cordero
- Manuel Enciso
- Domingo López-Rodríguez
- Ángel Mora
Status: Published
date: '2022-09-01T00:00:00Z'
slug: 2022-rjournal
selected: yes
title: fcaR, Formal Concept Analysis with R
categories:
- Formal concept analysis
- R package
header_image: ~
details: <em>The R Journal</em>
doi: 10.32614/RJ-2022-014
link: 2022-rjournal/paper.pdf
project: 2019-flair
keywords: Formal concept analysis, R package
listing:
- id: funding
  contents: funding.yml
  type: default
  sort: date desc
---



# Abstract


Formal concept analysis (FCA) is a solid mathematical framework to manage information based on logic and lattice theory. It defines two explicit representations of the knowledge present in a dataset as concepts and implications. This paper describes an R package called fcaR that implements FCA's core notions and techniques. Additionally, it implements the extension of FCA to fuzzy datasets and a simplification logic to develop automated reasoning tools. This package is the first to implement FCA techniques in R. Therefore, emphasis has been put on defining classes and methods that could be reusable and extensible by the community. Furthermore, the package incorporates an interface with the arules package, probably the most used package regarding association rules, closely related to FCA. Finally, we show an application of the use of the package to design a recommender system based on logic for diagnosis in neurological pathologies.




# Funding
::: {.callout-note appearance='minimal' collapse=false}
## Projects funding this work

:::{#funding}
:::
:::


# Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```


# Citation
Please, cite this work as:


<a name=bib-RJ-2022-014></a>[[Cor+22]](#cite-RJ-2022-014) P. Cordero, M. Enciso, D. López-Rodríguez, et al. “fcaR, Formal Concept Analysis with R”. In: _The R Journal_ 14 (1 2022). https://doi.org/10.32614/RJ-2022-014, pp. 341-361. ISSN: 2073-4859. DOI: [10.32614/RJ-2022-014](https://doi.org/10.32614%2FRJ-2022-014).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@article{RJ-2022-014,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Pablo Cordero  and Manuel Enciso and Domingo {López-Rodríguez} and Ángel Mora},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {fcaR, Formal Concept Analysis with R},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {The R Journal},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2022},<br>&nbsp;&nbsp;&nbsp;&nbsp;  note = {https://doi.org/10.32614/RJ-2022-014},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.32614/RJ-2022-014},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {14},<br>&nbsp;&nbsp;&nbsp;&nbsp;  issue = {1},<br>&nbsp;&nbsp;&nbsp;&nbsp;  issn = {2073-4859},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {341-361}<br>}

:::


