---
title: A Propositional Dynamic Logic Approach for Order of Magnitude Reasoning
author:
- Alfredo Burrieza
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '2008'
categories: uncategorised
slug: 2008/PrDyLoApOrMaRe
details: Advances in Artificial Intelligence - {IBERAMIA} 2008, 11th Ibero-American
  Conference on AI, Lisbon, Portugal, October 14-17, 2008. Proceedings , Lecture Notes
  in Computer Science vol. 5290, pages 11--20.
doi: 10.1007/978-3-540-88309-8_2
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Burrieza2008a></a>[[BMO08]](#cite-Burrieza2008a) A. Burrieza, E. Mu~noz-Velasco, and M. Ojeda-Aciego. “A Propositional Dynamic Logic Approach for Order of Magnitude Reasoning”. In: _Advances in Artificial Intelligence - IBERAMIA 2008, 11th Ibero-American Conference on AI, Lisbon, Portugal, October 14-17, 2008. Proceedings_. Ed. by H. Geffner, R. Prada, I. M. Alexandre and N. David. Vol. 5290. Lecture Notes in Computer Science. Springer, 2008, pp. 11-20. DOI: [10.1007/978-3-540-88309-8\_2](https://doi.org/10.1007%2F978-3-540-88309-8%5C_2). URL: [https://doi.org/10.1007/978-3-540-88309-8\_2](https://doi.org/10.1007/978-3-540-88309-8\_2).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Burrieza2008a,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Alfredo Burrieza and Emilio Mu~noz-Velasco and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Advances in Artificial Intelligence - {IBERAMIA} 2008, 11th Ibero-American Conference on AI, Lisbon, Portugal, October 14-17, 2008. Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {A Propositional Dynamic Logic Approach for Order of Magnitude Reasoning},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2008},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Hector Geffner and Rui Prada and Isabel Machado Alexandre and Nuno David},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {11--20},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {5290},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/iberamia/BurriezaMO08.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/978-3-540-88309-8\_2},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Wed, 02 Aug 2023 10:13:48 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/978-3-540-88309-8\_2},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/978-3-540-88309-8_2" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/978-3-540-88309-8_2" class="plumx-details" data-site="plum" data-hide-when-empty="true">A Propositional Dynamic Logic Approach for Order of Magnitude Reasoning</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1007/978-3-540-88309-8_2"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Burrieza_2010></a>[[1]](#cite-Burrieza_2010) A. Burrieza, E. Muñoz-Velasco, and M. Ojeda-Aciego. “Closeness and Distance Relations in Order of Magnitude Qualitative Reasoning via PDL”. In: _Current Topics in Artificial Intelligence_. Springer Berlin Heidelberg, 2010, p. 71–80. ISBN: 9783642142642. DOI: [10.1007/978-3-642-14264-2_8](https://doi.org/10.1007%2F978-3-642-14264-2_8). URL: [http://dx.doi.org/10.1007/978-3-642-14264-2_8](http://dx.doi.org/10.1007/978-3-642-14264-2_8).

<a name=bib-Burrieza_2018></a>[[2]](#cite-Burrieza_2018) A. Burrieza, E. Muñoz-Velasco, and M. Ojeda-Aciego. “Logics for Order-of-Magnitude Qualitative Reasoning: Formalizing Negligibility”. In: _Ewa Orłowska on Relational Methods in Logic and Computer Science_. Springer International Publishing, 2018, p. 203–231. ISBN: 9783319978796. DOI: [10.1007/978-3-319-97879-6_8](https://doi.org/10.1007%2F978-3-319-97879-6_8). URL: [http://dx.doi.org/10.1007/978-3-319-97879-6_8](http://dx.doi.org/10.1007/978-3-319-97879-6_8).

