---
author:
- Pablo Cordero
- Manuel Enciso
- Ángel Mora
- Vilem Vychodil
Status: Published
date: '2020-08-06'
slug: 2020-ijgs
title: 'Parameterized simplification logic I: reasoning with implications and classes
  of closure operators'
categories: Simplification logic
header_image: ~
details: <em>International Journal of General Systems</em> vol 49 (7), pp. 724 --
  746
doi: 10.1080/03081079.2020.1831484
project: ~
keywords: Closure operator; lattice theory; completeness; if-then rules; isotone Galois
  connection
---


# Abstract


In this paper, we present a general inference system for reasoning with if-then rules. They are defined using general lattice-theoretic notions and their semantics is defined using particular closure operators parameterized by systems of isotone Galois connections. In this general setting, we introduce a simplification logic, show its sound and complete axiomatization, and deal with related issues. The presented results can be seen as forming parameterized framework for dealing with if-then rules that allows to focus on particular dependencies obtained by choices of parameterizations.







# Citation
Please, cite this work as:


<a name=bib-doi1010800308107920201831484></a>[[PV20]](#cite-doi1010800308107920201831484) A. M. Pablo Cordero Manuel Enciso and V. Vychodil. “Parameterized simplification logic I: reasoning with implications and classes of closure operators”. In: _International Journal of General Systems_ 49.7 (2020), pp. 724-746. DOI: [10.1080/03081079.2020.1831484](https://doi.org/10.1080%2F03081079.2020.1831484). eprint:

https://doi.org/10.1080/03081079.2020.1831484

. URL: [

https://doi.org/10.1080/03081079.2020.1831484

](

https://doi.org/10.1080/03081079.2020.1831484

).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@article{doi:10.1080/03081079.2020.1831484,<br>&nbsp;&nbsp;&nbsp;&nbsp;author = {Pablo Cordero, Manuel Enciso, Angel Mora and Vilem Vychodil},<br>&nbsp;&nbsp;&nbsp;&nbsp;title = {Parameterized simplification logic I: reasoning with implications and classes of closure operators},<br>&nbsp;&nbsp;&nbsp;&nbsp;journal = {International Journal of General Systems},<br>&nbsp;&nbsp;&nbsp;&nbsp;volume = {49},<br>&nbsp;&nbsp;&nbsp;&nbsp;number = {7},<br>&nbsp;&nbsp;&nbsp;&nbsp;pages = {724-746},<br>&nbsp;&nbsp;&nbsp;&nbsp;year = {2020},<br>&nbsp;&nbsp;&nbsp;&nbsp;publisher = {Taylor & Francis},<br>&nbsp;&nbsp;&nbsp;&nbsp;doi = {10.1080/03081079.2020.1831484},<br>&nbsp;&nbsp;&nbsp;&nbsp;<br>&nbsp;&nbsp;&nbsp;&nbsp;<br>&nbsp;&nbsp;&nbsp;&nbsp;URL = { <br>&nbsp;&nbsp;&nbsp;&nbsp;    <br>&nbsp;&nbsp;&nbsp;&nbsp;        https://doi.org/10.1080/03081079.2020.1831484<br>&nbsp;&nbsp;&nbsp;&nbsp;    <br>&nbsp;&nbsp;&nbsp;&nbsp;    <br>&nbsp;&nbsp;&nbsp;&nbsp;<br>&nbsp;&nbsp;&nbsp;&nbsp;},<br>&nbsp;&nbsp;&nbsp;&nbsp;eprint = { <br>&nbsp;&nbsp;&nbsp;&nbsp;    <br>&nbsp;&nbsp;&nbsp;&nbsp;        https://doi.org/10.1080/03081079.2020.1831484<br>&nbsp;&nbsp;&nbsp;&nbsp;    <br>&nbsp;&nbsp;&nbsp;&nbsp;    <br>&nbsp;&nbsp;&nbsp;&nbsp;<br>&nbsp;&nbsp;&nbsp;&nbsp;}<br>&nbsp;&nbsp;&nbsp;&nbsp;<br>}

:::


