---
title: Publication of <em>fcaR, Formal Concept Analysis with R</em>
author:
- Pablo Cordero
- Manuel Enciso
- Domingo López-Rodríguez
- Ángel Mora
date: '2022-09-01T00:00:00Z'
categories:
- Formal concept analysis
- R package
---

The work <u>fcaR, Formal Concept Analysis with R</u> has been published in <em><em>The R Journal</em></em>.

<u>Abstract</u>:


Formal concept analysis (FCA) is a solid mathematical framework to manage information based on logic and lattice theory. It defines two explicit representations of the knowledge present in a dataset as concepts and implications. This paper describes an R package called fcaR that implements FCA's core notions and techniques. Additionally, it implements the extension of FCA to fuzzy datasets and a simplification logic to develop automated reasoning tools. This package is the first to implement FCA techniques in R. Therefore, emphasis has been put on defining classes and methods that could be reusable and extensible by the community. Furthermore, the package incorporates an interface with the arules package, probably the most used package regarding association rules, closely related to FCA. Finally, we show an application of the use of the package to design a recommender system based on logic for diagnosis in neurological pathologies.

