---
title: A new deduction system for deciding validity in modal logic {K}
author:
- Joanna Golinska-Pilarek
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
- <a href='/people/staff/amora/' style='color:rgb(100,0,50);'>Ángel Mora</a>
date: '2011'
categories: uncategorised
slug: 2011/NeDeSyDeVaMoLo
details: Log. J. {IGPL} vol. 19 (2), pages 425--434.
doi: 10.1093/JIGPAL/JZQ033
---



# Abstract


A new deduction system for deciding validity for the minimal decidable normal modal logic K is presented in this article. Modal logics could be very helpful in modelling dynamic and reactive systems such as bio-inspired systems and process algebras. In fact, recently the Connectionist Modal Logics has been presented, which combines the strengths of modal logics and neural networks. Thus, modal logic K is the basis for these approaches. Soundness, completeness and the fact that the system itself is a decision procedure are proved in this article. The main advantages of this approach are: first, the system is deterministic, i.e. it generates one proof tree for a given formula; second, the system is a validity-checker, hence it generates a proof of a formula (if such exists); and third, the language of deduction and the language of a logic coincide. Some of these advantages are compared with other classical approaches.








# Citation
Please, cite this work as:


<a name=bib-GolinskaPilarek2011></a>[[GMM11]](#cite-GolinskaPilarek2011) J. Golinska-Pilarek, E. Mu~noz-Velasco, and Á. Mora. “A new deduction system for deciding validity in modal logic K”. In: _Log. J. IGPL_ 19.2 (2011), pp. 425-434. DOI: [10.1093/JIGPAL/JZQ033](https://doi.org/10.1093%2FJIGPAL%2FJZQ033). URL: [https://doi.org/10.1093/jigpal/jzq033](https://doi.org/10.1093/jigpal/jzq033).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{GolinskaPilarek2011,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Joanna Golinska-Pilarek and Emilio Mu~noz-Velasco and {\a'A}ngel Mora},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Log. J. {IGPL}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {A new deduction system for deciding validity in modal logic {K}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2011},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number = {2},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {425--434},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {19},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/igpl/Golinska-PilarekMM11.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1093/JIGPAL/JZQ033},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 23 Sep 2022 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1093/jigpal/jzq033},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1093/JIGPAL/JZQ033" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1093/JIGPAL/JZQ033" class="plumx-details" data-site="plum" data-hide-when-empty="true">A new deduction system for deciding validity in modal logic {K}</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1093/JIGPAL/JZQ033"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Burrieza_2018></a>[[1]](#cite-Burrieza_2018) A. Burrieza, E. Muñoz-Velasco, and M. Ojeda-Aciego. “Logics for Order-of-Magnitude Qualitative Reasoning: Formalizing Negligibility”. In: _Ewa Orłowska on Relational Methods in Logic and Computer Science_. Springer International Publishing, 2018, p. 203–231. ISBN: 9783319978796. DOI: [10.1007/978-3-319-97879-6_8](https://doi.org/10.1007%2F978-3-319-97879-6_8). URL: [http://dx.doi.org/10.1007/978-3-319-97879-6_8](http://dx.doi.org/10.1007/978-3-319-97879-6_8).

<a name=bib-Cantone_2014></a>[[2]](#cite-Cantone_2014) D. Cantone, J. Golińska-Pilarek, and M. Nicolosi-Asmundo. “A Relational Dual Tableau Decision Procedure for Multimodal and Description Logics”. In: _Hybrid Artificial Intelligence Systems_. Springer International Publishing, 2014, p. 466–477. ISBN: 9783319076171. DOI: [10.1007/978-3-319-07617-1_41](https://doi.org/10.1007%2F978-3-319-07617-1_41). URL: [http://dx.doi.org/10.1007/978-3-319-07617-1_41](http://dx.doi.org/10.1007/978-3-319-07617-1_41).

<a name=bib-Cantone_2018></a>[[3]](#cite-Cantone_2018) D. Cantone and M. Nicolosi-Asmundo. “Dual Tableau-Based Decision Procedures for Fragments of the Logic of Binary Relations”. In: _Ewa Orłowska on Relational Methods in Logic and Computer Science_. Springer International Publishing, 2018, p. 169–202. ISBN: 9783319978796. DOI: [10.1007/978-3-319-97879-6_7](https://doi.org/10.1007%2F978-3-319-97879-6_7). URL: [http://dx.doi.org/10.1007/978-3-319-97879-6_7](http://dx.doi.org/10.1007/978-3-319-97879-6_7).

<a name=bib-httpsdoiorg1048550arxiv180207508></a>[[4]](#cite-httpsdoiorg1048550arxiv180207508) D. Cantone, M. Nicolosi-Asmundo, and E. Orłowska. _A Dual Tableau-based Decision Procedure for a Relational Logic with the Universal Relation (Extended Version)_. 2018. DOI: [10.48550/ARXIV.1802.07508](https://doi.org/10.48550%2FARXIV.1802.07508). URL: [https://arxiv.org/abs/1802.07508](https://arxiv.org/abs/1802.07508).

<a name=bib-Corchado_2010></a>[[5]](#cite-Corchado_2010) E. Corchado and M. Wozniak. “Editorial: Neuro-symbolic Algorithms and Models for Bio-inspired Systems”. In: _Logic Journal of IGPL_ 19.2 (Jul. 2010), p. 289–292. ISSN: 1368-9894. DOI: [10.1093/jigpal/jzq026](https://doi.org/10.1093%2Fjigpal%2Fjzq026). URL: [http://dx.doi.org/10.1093/jigpal/jzq026](http://dx.doi.org/10.1093/jigpal/jzq026).

<a name=bib-Goli_ska_Pilarek_2014></a>[[6]](#cite-Goli_ska_Pilarek_2014) J. Golińska-Pilarek, T. Huuskonen, and E. Muñoz-Velasco. “Relational dual tableau decision procedures and their applications to modal and intuitionistic logics”. In: _Annals of Pure and Applied Logic_ 165.2 (Feb. 2014), p. 409–427. ISSN: 0168-0072. DOI: [10.1016/j.apal.2013.06.003](https://doi.org/10.1016%2Fj.apal.2013.06.003). URL: [http://dx.doi.org/10.1016/j.apal.2013.06.003](http://dx.doi.org/10.1016/j.apal.2013.06.003).

<a name=bib-Golinska_Pilarek_2011></a>[[7]](#cite-Golinska_Pilarek_2011) J. Golinska-Pilarek, E. Munoz-Velasco, and A. Mora-Bonilla. “Relational dual tableau decision procedure for modal logic K”. In: _Logic Journal of IGPL_ 20.4 (Feb. 2011), p. 747–756. ISSN: 1368-9894. DOI: [10.1093/jigpal/jzr019](https://doi.org/10.1093%2Fjigpal%2Fjzr019). URL: [http://dx.doi.org/10.1093/jigpal/jzr019](http://dx.doi.org/10.1093/jigpal/jzr019).

