---
title: Implementation of a Tableau-based Satisfiability Checker for {HS3}
author:
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
- Guido Sciavicco
- Ionel Eduard Stan
date: '2017'
categories: uncategorised
slug: 2017/ImSaCh
details: Joint Proceedings of the 18th Italian Conference on Theoretical Computer
  Science and the 32nd Italian Conference on Computational Logic co-located with the
  2017 {IEEE} International Workshop on Measurements and Networking {(2017} {IEEE}
  M{\&}N), Naples, Italy, September 26-28, 2017 , {CEUR} Workshop Proceedings vol.
  1949, pages 326--340.
---



# Abstract


Although there exist several decidable fragments of Halpern and Shoham’s interval temporal logic HS, the computational complexity of their satisfiability problem tend to be generally high. Recently, the fragment HS3 of HS, based on coarser-than-Allen’s relations, has been introduced, and it has been proven to be not only decidable, but also relatively efficient. In this paper we describe an implementation of a tableau-based satisfiability checker for HS3 interpreted in the class of all finite linear orders.








# Citation
Please, cite this work as:


<a name=bib-MunozVelasco2017></a>[[MSS17]](#cite-MunozVelasco2017) E. Mu~noz-Velasco, G. Sciavicco, and I. E. Stan. “Implementation of a Tableau-based Satisfiability Checker for HS3”. In: _Joint Proceedings of the 18th Italian Conference on Theoretical Computer Science and the 32nd Italian Conference on Computational Logic co-located with the 2017 IEEE International Workshop on Measurements and Networking (2017 IEEE M&N), Naples, Italy, September 26-28, 2017_. Ed. by D. D. Monica, A. Murano, S. Rubin and L. Sauro. Vol. 1949. CEUR Workshop Proceedings. CEUR-WS.org, 2017, pp. 326-340. URL: [https://ceur-ws.org/Vol-1949/CILCpaper09.pdf](https://ceur-ws.org/Vol-1949/CILCpaper09.pdf).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{MunozVelasco2017,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Emilio Mu~noz-Velasco and Guido Sciavicco and Ionel Eduard Stan},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Joint Proceedings of the 18th Italian Conference on Theoretical Computer Science and the 32nd Italian Conference on Computational Logic co-located with the 2017 {IEEE} International Workshop on Measurements and Networking {(2017} {IEEE} M{\&}N), Naples, Italy, September 26-28, 2017},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Implementation of a Tableau-based Satisfiability Checker for {HS3}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2017},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Dario Della Monica and Aniello Murano and Sasha Rubin and Luigi Sauro},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {326--340},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {CEUR-WS.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {{CEUR} Workshop Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {1949},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {Although there exist several decidable fragments of Halpern and Shoham’s interval temporal logic HS, the computational complexity of their satisfiability problem tend to be generally high. Recently, the fragment HS3 of HS, based on coarser-than-Allen’s relations, has been introduced, and it has been proven to be not only decidable, but also relatively efficient. In this paper we describe an implementation of a tableau-based satisfiability checker for HS3 interpreted in the class of all finite linear orders.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/ictcs/Munoz-VelascoSS17.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 10 Mar 2023 16:23:17 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://ceur-ws.org/Vol-1949/CILCpaper09.pdf},<br>}

:::








