---
author:
- Domingo López-Rodríguez
- E. Mérida-Casermeiro
- J.M. Ortiz-de-Lazcano-Lobato
Status: Published
date: '2007-01-01'
slug: 2007-wseastm
title: Stochastic multivalued network for optimization. Application to the graph MaxCut
  problem
categories:
- Combinatorial optimization
- Neural networks
header_image: ~
details: WSEAS Transactions on Mathematics, (6), 3, <em>pp. 500-505</em>
doi: ''
link: 2007-wseastm/paper.pdf
project: ''
cite: yes
keywords: Computational efficiency, Graph theory, Mathematical models, Optimization,
  Stochastic models, Graph partition, Local minima, Stochastic dynamics, Neural networks
---


# Abstract


The aim of this paper is to present the stochastic version of the multivalued neural model MREM, which has achieved very good results in many applications, as an optimization technique. The purpose of this stochastic version is to avoid certain local minima of the objective function minimized by the network, that is, the energy function. To this end, the description of the theoretical bases of this model, guaranteeing the convergence to minima, is carried out rigorously. In order to show the efficiency of this new model, the model, in its two versions, deterministic and stochastic, has been applied to the resolution of the well-known problem of graph partition, MaxCut. Computational experiments show that in most cases the stochastic model achieves better results than the deterministic one.





# Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```


# Citation
Please, cite this work as:


<a name=bib-LopezRodriguez2007></a>[[LMO07]](#cite-LopezRodriguez2007) D. López-Rodríguez, E. Mérida-Casermeiro, and J. Ortiz-de-Lazcano-Lobato. “Stochastic multivalued network for optimization. Application to the graph MaxCut problem”. In: _WSEAS Transactions on Mathematics_ 6.3 (2007). cited By 0, pp. 500-505. URL: [https://www.scopus.com/inward/record.uri?eid=2-s2.0-33847621572&partnerID=40&md5=be8fe4152a9d2279f0a282de53806edb](https://www.scopus.com/inward/record.uri?eid=2-s2.0-33847621572&partnerID=40&md5=be8fe4152a9d2279f0a282de53806edb).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{LopezRodriguez2007,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {D. López-Rodríguez and E. Mérida-Casermeiro and J.M. Ortiz-de-Lazcano-Lobato},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {WSEAS Transactions on Mathematics},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Stochastic multivalued network for optimization. Application to the graph MaxCut problem},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2007},<br>&nbsp;&nbsp;&nbsp;&nbsp;  note = {cited By 0},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number = {3},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {500-505},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {6},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {The aim of this paper is to present the stochastic version of the multivalued neural model MREM, which has achieved very good results in many applications, as an optimization technique. The purpose of this stochastic version is to avoid certain local minima of the objective function minimized by the network, that is, the energy function. To this end, the description of the theoretical bases of this model, guaranteeing the convergence to minima, is carried out rigorously. In order to show the efficiency of this new model, the model, in its two versions, deterministic and stochastic, has been applied to the resolution of the well-known problem of graph partition, MaxCut. Computational experiments show that in most cases the stochastic model achieves better results than the deterministic one.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  author_keywords = {Graph problems; Neural networks; Optimization problems; Stochastic dynamics},<br>&nbsp;&nbsp;&nbsp;&nbsp;  document_type = {Article},<br>&nbsp;&nbsp;&nbsp;&nbsp;  keywords = {Computational efficiency; Graph theory; Mathematical models; Optimization; Stochastic models, Graph partition; Local minima; Stochastic dynamics, Neural networks},<br>&nbsp;&nbsp;&nbsp;&nbsp;  source = {Scopus},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://www.scopus.com/inward/record.uri?eid=2-s2.0-33847621572&partnerID=40&md5=be8fe4152a9d2279f0a282de53806edb},<br>}

:::


