---
title: Non-deterministic Algebraic Structures for Soft Computing
author:
- <a href='/people/staff/ipcabrera/' style='color:rgb(100,0,50);'>Inma P. Cabrera</a>
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '2011'
categories: uncategorised
slug: 2011/AlStSoCo
details: Advances in Computational Intelligence - 11th International Work-Conference
  on Artificial Neural Networks, {IWANN} 2011, Torremolinos-M{\'{a}}laga, Spain, June
  8-10, 2011, Proceedings, Part {II} , Lecture Notes in Computer Science vol. 6692,
  pages 437--444.
doi: 10.1007/978-3-642-21498-1_55
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Cabrera2011></a>[[CCO11]](#cite-Cabrera2011) I. P. Cabrera, P. Cordero, and M. Ojeda-Aciego. “Non-deterministic Algebraic Structures for Soft Computing”. In: _Advances in Computational Intelligence - 11th International Work-Conference on Artificial Neural Networks, IWANN 2011, Torremolinos-Málaga, Spain, June 8-10, 2011, Proceedings, Part II_. Ed. by J. Cabestany, I. Rojas and G. J. Caparrós. Vol. 6692. Lecture Notes in Computer Science. Springer, 2011, pp. 437-444. DOI: [10.1007/978-3-642-21498-1\_55](https://doi.org/10.1007%2F978-3-642-21498-1%5C_55). URL: [https://doi.org/10.1007/978-3-642-21498-1\_55](https://doi.org/10.1007/978-3-642-21498-1\_55).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Cabrera2011,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Inma P. Cabrera and Pablo Cordero and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Advances in Computational Intelligence - 11th International Work-Conference on Artificial Neural Networks, {IWANN} 2011, Torremolinos-M{\'{a}}laga, Spain, June 8-10, 2011, Proceedings, Part {II}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Non-deterministic Algebraic Structures for Soft Computing},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2011},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Joan Cabestany and Ignacio Rojas and Gonzalo Joya Caparr{\a'o}s},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {437--444},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {6692},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/iwann/CabreraCO11.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/978-3-642-21498-1\_55},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Tue, 14 May 2019 10:00:51 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/978-3-642-21498-1\_55},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/978-3-642-21498-1_55" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/978-3-642-21498-1_55" class="plumx-details" data-site="plum" data-hide-when-empty="true">Non-deterministic Algebraic Structures for Soft Computing</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1007/978-3-642-21498-1_55"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Kalampakas_2015></a>[[1]](#cite-Kalampakas_2015) A. Kalampakas and O. Louscou-Bozapalidou. “Syntactic Nondeterministic Monoids”. In: _Journal of Discrete Mathematical Sciences and Cryptography_ 18.6 (Nov. 2015), p. 717–726. ISSN: 2169-0065. DOI: [10.1080/09720529.2014.943462](https://doi.org/10.1080%2F09720529.2014.943462). URL: [http://dx.doi.org/10.1080/09720529.2014.943462](http://dx.doi.org/10.1080/09720529.2014.943462).

<a name=bib-Morcillo_2012></a>[[2]](#cite-Morcillo_2012) P. J. Morcillo, G. Moreno, J. Penabad, et al. “Dedekind–MacNeille completion and Cartesian product of multi-adjoint lattices”. In: _International Journal of Computer Mathematics_ 89.13–14 (Sep. 2012), p. 1742–1752. ISSN: 1029-0265. DOI: [10.1080/00207160.2012.689826](https://doi.org/10.1080%2F00207160.2012.689826). URL: [http://dx.doi.org/10.1080/00207160.2012.689826](http://dx.doi.org/10.1080/00207160.2012.689826).

