---
title: A View of f-indexes of Inclusion Under Different Axiomatic Definitions of Fuzzy
  Inclusion
author:
- Nicolás Madrid
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '2017'
categories: uncategorised
slug: 2017/ViInDiAxDeFuIn
details: Scalable Uncertainty Management - 11th International Conference, {SUM} 2017,
  Granada, Spain, October 4-6, 2017, Proceedings , Lecture Notes in Computer Science
  vol. 10564, pages 307--318.
doi: 10.1007/978-3-319-67582-4_22
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Madrid2017a></a>[[MO17]](#cite-Madrid2017a) N. Madrid and M. Ojeda-Aciego. “A View of f-indexes of Inclusion Under Different Axiomatic Definitions of Fuzzy Inclusion”. In: _Scalable Uncertainty Management - 11th International Conference, SUM 2017, Granada, Spain, October 4-6, 2017, Proceedings_. Ed. by Seraf\'\inMoral, O. Pivert, D. Sánchez and N. Mar\'\in. Vol. 10564. Lecture Notes in Computer Science. Springer, 2017, pp. 307-318. DOI: [10.1007/978-3-319-67582-4\_22](https://doi.org/10.1007%2F978-3-319-67582-4%5C_22). URL: [https://doi.org/10.1007/978-3-319-67582-4\_22](https://doi.org/10.1007/978-3-319-67582-4\_22).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Madrid2017a,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Nicol{\a'a}s Madrid and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Scalable Uncertainty Management - 11th International Conference, {SUM} 2017, Granada, Spain, October 4-6, 2017, Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {A View of f-indexes of Inclusion Under Different Axiomatic Definitions of Fuzzy Inclusion},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2017},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Seraf\'\in Moral and Olivier Pivert and Daniel S{\a'a}nchez and Nicol{\a'a}s Mar\'\in},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {307--318},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {10564},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/sum/MadridO17.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/978-3-319-67582-4\_22},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Mon, 03 Jan 2022 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/978-3-319-67582-4\_22},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/978-3-319-67582-4_22" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/978-3-319-67582-4_22" class="plumx-details" data-site="plum" data-hide-when-empty="true">A View of f-indexes of Inclusion Under Different Axiomatic Definitions of Fuzzy Inclusion</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1007/978-3-319-67582-4_22"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Flaminio_2023></a>[[1]](#cite-Flaminio_2023) T. Flaminio, L. Godo, N. Madrid, et al. “A Logic to Reason About f-Indices of Inclusion over Ł$$_n$$”. In: _Fuzzy Logic and Technology, and Aggregation Operators_. Springer Nature Switzerland, 2023, p. 530–539. ISBN: 9783031399657. DOI: [10.1007/978-3-031-39965-7_44](https://doi.org/10.1007%2F978-3-031-39965-7_44). URL: [http://dx.doi.org/10.1007/978-3-031-39965-7_44](http://dx.doi.org/10.1007/978-3-031-39965-7_44).

<a name=bib-Madrid_2020></a>[[2]](#cite-Madrid_2020) N. Madrid, J. Medina, and E. Ramírez-Poussa. “Rough sets based on Galois connections”. In: _International Journal of Applied Mathematics and Computer Science_ 30.2 (2020). ISSN: 2083-8492. DOI: [10.34768/amcs-2020-0023](https://doi.org/10.34768%2Famcs-2020-0023). URL: [http://dx.doi.org/10.34768/amcs-2020-0023](http://dx.doi.org/10.34768/amcs-2020-0023).

<a name=bib-Madrid_20241></a>[[3]](#cite-Madrid_20241) N. Madrid and M. Ojeda-Aciego. “Approaching the square of opposition in terms of the f-indexes of inclusion and contradiction”. In: _Fuzzy Sets and Systems_ 476 (Jan. 2024), p. 108769. ISSN: 0165-0114. DOI: [10.1016/j.fss.2023.108769](https://doi.org/10.1016%2Fj.fss.2023.108769). URL: [http://dx.doi.org/10.1016/j.fss.2023.108769](http://dx.doi.org/10.1016/j.fss.2023.108769).

<a name=bib-Madrid_20202></a>[[4]](#cite-Madrid_20202) N. Madrid and M. Ojeda-Aciego. “Functional degrees of inclusion and similarity between L-fuzzy sets”. In: _Fuzzy Sets and Systems_ 390 (Jul. 2020), p. 1–22. ISSN: 0165-0114. DOI: [10.1016/j.fss.2019.03.018](https://doi.org/10.1016%2Fj.fss.2019.03.018). URL: [http://dx.doi.org/10.1016/j.fss.2019.03.018](http://dx.doi.org/10.1016/j.fss.2019.03.018).

<a name=bib-Madrid_2021></a>[[5]](#cite-Madrid_2021) N. Madrid and M. Ojeda-Aciego. “Measures of inclusion and entropy based on the φ-index of inclusion”. In: _Fuzzy Sets and Systems_ 423 (Oct. 2021), p. 29–54. ISSN: 0165-0114. DOI: [10.1016/j.fss.2021.01.011](https://doi.org/10.1016%2Fj.fss.2021.01.011). URL: [http://dx.doi.org/10.1016/j.fss.2021.01.011](http://dx.doi.org/10.1016/j.fss.2021.01.011).

<a name=bib-Madrid_20201></a>[[6]](#cite-Madrid_20201) N. Madrid and M. Ojeda-Aciego. “On Contradiction and Inclusion Using Functional Degrees”. In: _International Journal of Computational Intelligence Systems_ 13.1 (2020), p. 464. ISSN: 1875-6883. DOI: [10.2991/ijcis.d.200409.001](https://doi.org/10.2991%2Fijcis.d.200409.001). URL: [http://dx.doi.org/10.2991/ijcis.d.200409.001](http://dx.doi.org/10.2991/ijcis.d.200409.001).

<a name=bib-Madrid_2023></a>[[7]](#cite-Madrid_2023) N. Madrid and M. Ojeda-Aciego. “The f-index of inclusion as optimal adjoint pair for fuzzy modus ponens”. In: _Fuzzy Sets and Systems_ 466 (Aug. 2023), p. 108474. ISSN: 0165-0114. DOI: [10.1016/j.fss.2023.01.009](https://doi.org/10.1016%2Fj.fss.2023.01.009). URL: [http://dx.doi.org/10.1016/j.fss.2023.01.009](http://dx.doi.org/10.1016/j.fss.2023.01.009).

<a name=bib-Madrid_2024></a>[[8]](#cite-Madrid_2024) N. Madrid and E. Ramírez-Poussa. “Analysis of the $$\varphi $$-Index of Inclusion Restricted to a Set of Indexes”. In: _Information Processing and Management of Uncertainty in Knowledge-Based Systems_. Springer Nature Switzerland, 2024, p. 3–11. ISBN: 9783031740039. DOI: [10.1007/978-3-031-74003-9_1](https://doi.org/10.1007%2F978-3-031-74003-9_1). URL: [http://dx.doi.org/10.1007/978-3-031-74003-9_1](http://dx.doi.org/10.1007/978-3-031-74003-9_1).

