---
title: Satisfiability Testing for Boolean Formulas Using Delta-trees
author:
- Gloria Gutiérrez
- <a href='/people/staff/ipguzman/' style='color:rgb(100,0,50);'>Inma P. de Guzmán</a>
- Javier Martínez
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
- Agustín Valverde
date: '2002'
categories: uncategorised
slug: 2002/SaTeBoFoUs
details: Stud Logica vol. 72 (1), pages 85--112.
doi: 10.1023/A:1020530109551
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Gutierrez2002></a>[[Gut+02]](#cite-Gutierrez2002) G. Gutiérrez, I. P. de Guzmán, J. Mart\'\inez, et al. “Satisfiability Testing for Boolean Formulas Using Delta-trees”. In: _Stud Logica_ 72.1 (2002), pp. 85-112. DOI: [10.1023/A:1020530109551](https://doi.org/10.1023%2FA%3A1020530109551). URL: [https://doi.org/10.1023/A:1020530109551](https://doi.org/10.1023/A:1020530109551).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{Gutierrez2002,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Gloria Guti{\a'e}rrez and Inman P. {de Guzm{\a'a}n} and Javier Mart\'\inez and Manuel Ojeda-Aciego and Agust\'\in Valverde},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Stud Logica},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Satisfiability Testing for Boolean Formulas Using Delta-trees},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2002},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number = {1},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {85--112},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {72},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/sLogica/GutierrezGMOV02.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1023/A:1020530109551},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Tue, 29 Aug 2023 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1023/A:1020530109551},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1023/A:1020530109551" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1023/A:1020530109551" class="plumx-details" data-site="plum" data-hide-when-empty="true">Satisfiability Testing for Boolean Formulas Using Delta-trees</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1023/A:1020530109551"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-de_Guzm_n_2002></a>[[1]](#cite-de_Guzm_n_2002) I. de Guzmán, M. Ojeda-Aciego, and A. Valverde. “Restricted Δ-Trees in Multiple-Valued Logics”. In: _Artificial Intelligence: Methodology, Systems, and Applications_. Springer Berlin Heidelberg, 2002, p. 223–232. ISBN: 9783540461487. DOI: [10.1007/3-540-46148-5_23](https://doi.org/10.1007%2F3-540-46148-5_23). URL: [http://dx.doi.org/10.1007/3-540-46148-5_23](http://dx.doi.org/10.1007/3-540-46148-5_23).

<a name=bib-de_Guzm_n_20021></a>[[2]](#cite-de_Guzm_n_20021) I. P. de Guzmán, M. Ojeda-Aciego, and A. Valverde. “Restricted Δ-Trees and Reduction Theorems in Multiple-Valued Logics”. In: _Advances in Artificial Intelligence — IBERAMIA 2002_. Springer Berlin Heidelberg, 2002, p. 161–171. ISBN: 9783540361312. DOI: [10.1007/3-540-36131-6_17](https://doi.org/10.1007%2F3-540-36131-6_17). URL: [http://dx.doi.org/10.1007/3-540-36131-6_17](http://dx.doi.org/10.1007/3-540-36131-6_17).

<a name=bib-Mart_nez_2005></a>[[3]](#cite-Mart_nez_2005) J. Martínez, G. Gutiérrez, I. de Guzmán, et al. “Generalizations of lattices via non-deterministic operators”. In: _Discrete Mathematics_ 295.1–3 (May. 2005), p. 107–141. ISSN: 0012-365X. DOI: [10.1016/j.disc.2004.08.043](https://doi.org/10.1016%2Fj.disc.2004.08.043). URL: [http://dx.doi.org/10.1016/j.disc.2004.08.043](http://dx.doi.org/10.1016/j.disc.2004.08.043).

<a name=bib-Ojeda_Aciego_2004></a>[[4]](#cite-Ojeda_Aciego_2004) M. Ojeda-Aciego and A. Valverde. “tascpl: TAS Solver for Classical Propositional Logic”. In: _Logics in Artificial Intelligence_. Springer Berlin Heidelberg, 2004, p. 738–741. ISBN: 9783540302278. DOI: [10.1007/978-3-540-30227-8_70](https://doi.org/10.1007%2F978-3-540-30227-8_70). URL: [http://dx.doi.org/10.1007/978-3-540-30227-8_70](http://dx.doi.org/10.1007/978-3-540-30227-8_70).

