---
title: Time Series Checking with Fuzzy Interval Temporal Logics
author:
- Willem Conradie
- Dario Della Monica
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
- Guido Sciavicco
- Ionel Eduard Stan
date: '2020'
categories: uncategorised
slug: 2020/TiSeChFuInTeLo
details: Proceedings of the 21st Italian Conference on Theoretical Computer Science,
  Ischia, Italy, September 14-16, 2020 , {CEUR} Workshop Proceedings vol. 2756, pages
  250--262.
---



# Abstract


Model checking is a very well-known problem, with many practical applications. A possible variation of such a problem in the interval logic setting is the so-called finite model checking, that consists of verifying an interval temporal logic formula, typically of Halpern and Shoham’s logic of Allen’s relations HS, on a fully represented finite interval model. Multivariate time series are collections of temporally ordered sets of values, and they allow to describe a variety of situations, such as the medical history of an hospitalized patient or the sensor values during a plane flight. In this paper we argue how the recently introduced fuzzy generalization of interval temporal logic is a suitable language in which interesting properties of a multivariate time series can be expressed and checked, and we define, solve, and discuss the complexity of the multivariate time series fuzzy interval logic checking problem.








# Citation
Please, cite this work as:


<a name=bib-Conradie2020a></a>[[Con+20]](#cite-Conradie2020a) W. Conradie, D. D. Monica, E. Mu~noz-Velasco, et al. “Time Series Checking with Fuzzy Interval Temporal Logics”. In: _Proceedings of the 21st Italian Conference on Theoretical Computer Science, Ischia, Italy, September 14-16, 2020_. Ed. by G. Cordasco, L. Gargano and A. A. Rescigno. Vol. 2756. CEUR Workshop Proceedings. CEUR-WS.org, 2020, pp. 250-262. URL: [https://ceur-ws.org/Vol-2756/paper\_29.pdf](https://ceur-ws.org/Vol-2756/paper\_29.pdf).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Conradie2020a,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Willem Conradie and Dario Della Monica and Emilio Mu~noz-Velasco and Guido Sciavicco and Ionel Eduard Stan},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Proceedings of the 21st Italian Conference on Theoretical Computer Science, Ischia, Italy, September 14-16, 2020},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Time Series Checking with Fuzzy Interval Temporal Logics},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2020},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Gennaro Cordasco and Luisa Gargano and Adele A. Rescigno},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {250--262},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {CEUR-WS.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {{CEUR} Workshop Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {2756},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {Model checking is a very well-known problem, with many practical applications. A possible variation of such a problem in the interval logic setting is the so-called finite model checking, that consists of verifying an interval temporal logic formula, typically of Halpern and Shoham’s logic of Allen’s relations HS, on a fully represented finite interval model. Multivariate time series are collections of temporally ordered sets of values, and they allow to describe a variety of situations, such as the medical history of an hospitalized patient or the sensor values during a plane flight. In this paper we argue how the recently introduced fuzzy generalization of interval temporal logic is a suitable language in which interesting properties of a multivariate time series can be expressed and checked, and we define, solve, and discuss the complexity of the multivariate time series fuzzy interval logic checking problem.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/ictcs/ConradieMMSS20.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 10 Mar 2023 16:23:17 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://ceur-ws.org/Vol-2756/paper\_29.pdf},<br>}

:::








