---
author: Ángel Mora, Enrique Mérida-Casermeiro, Domingo López-Rodríguez
Status: Published
date: '2006-07-01'
slug: 2006/DeViLeCoSuNuMeMo
title: Development of a virtual learning community for the subject Numerical Methods
  under Moodle
categories: E-learning
header_image: ~
details: <em>Current Developments in Technology-Assisted Education</em> 2006
link: 2006-m-icte/paper.pdf
project: ~
keywords: E-learning, Mathematics teaching, Moodle, Virtual Teaching
---


# Abstract


MetNum is a meeting point for the students of the subject “Numerical Methods” of the Engineering School of Informatics in the University of Málaga since 2003-2004. The former platform, existent in the University of Málaga, was firstly used, and results were improved quickly. The basic tools we worked with in MetNum were distribution lists and forums, as a means to encourage and guide students’ daily work. Since the year 2004-2005, MetNum has been developed under Moodle. The new tools provided by this platform have been exhaustively applied. We would like to emphasize the ability of Moodle to directly make a preview of LaTeX code, which is usually used to present mathematical material.












# Citation
Please, cite this work as:


<a name=bib-mora2006development></a>[[MML06]](#cite-mora2006development) Á. Mora, E. Mérida, and D. López-Rodríguez. “Development of a virtual learning community for the subject numerical methods under Moodle”. In: _Current developments in technology assisted education-m-ICTE_. 2006, pp. 361-365.

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@inproceedings{mora2006development,<br>&nbsp;&nbsp;&nbsp;&nbsp;  title={Development of a virtual learning community for the subject numerical methods under Moodle},<br>&nbsp;&nbsp;&nbsp;&nbsp;  author={Mora, Ángel and Mérida, E and López-Rodríguez, D},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle={Current developments in technology assisted education-m-ICTE},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages={361--365},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year={2006}<br>}

:::









