---
title: 'Relational Galois connections between transitive digraphs: Characterization
  and construction'
type: journals
author:
- <a href='/people/staff/ipcabrera/' style='color:rgb(100,0,50);'>Inma P. Cabrera</a>
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
- Bernard De Baets
date: '2020-01-01'
categories:
- Formal concept analysis
- Fuzzy logic
- Fuzzy sets
- Uncertainty
doi: 10.1016/j.ins.2020.01.034
slug: 2020/ReGaCoTrChCo
keywords: ''
project: 2019-flair
details: Information Sciences vol. 519 , pages 439 – 450.
listing:
- id: funding
  contents: funding.yml
  type: default
  sort: date desc
---




# Abstract

This paper focuses on a twofold relational generalization of the notion of Galois connection. It is twofold because it is defined between sets endowed with arbitrary transitive relations and, moreover, both components of the connection are relations, not necessarily functions. A characterization theorem of the notion of relational Galois connection is provided and, then, it is proved that a suitable notion of closure can be obtained within this framework. Finally, we state a necessary and sufficient condition that allows to build a relational Galois connection starting from a single transitive digraph and a single binary relation.


# Funding
::: {.callout-note appearance='minimal' collapse=false}
## Projects funding this work

:::{#funding}
:::
:::








# Citation
Please, cite this work as:


<a name=bib-Cabrera2020439></a>[[Cab+20]](#cite-Cabrera2020439) I. P. Cabrera, P. Cordero, E. Muñoz-Velasco, et al. “Relational Galois connections between transitive digraphs: Characterization and construction”. In: _Information Sciences_ 519 (2020). Cited by: 8; All Open Access, Green Open Access, p. 439 – 450. DOI: [10.1016/j.ins.2020.01.034](https://doi.org/10.1016%2Fj.ins.2020.01.034). URL: [https://www.scopus.com/inward/record.uri?eid=2-s2.0-85079160299&doi=10.1016

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@ARTICLE{Cabrera2020439,<br>&nbsp;&nbsp;&nbsp;&nbsp;	author = {Cabrera, Inma P. and Cordero, Pablo and Muñoz-Velasco, Emilio and Ojeda-Aciego, Manuel and De Baets, Bernard},<br>&nbsp;&nbsp;&nbsp;&nbsp;	title = {Relational Galois connections between transitive digraphs: Characterization and construction},<br>&nbsp;&nbsp;&nbsp;&nbsp;	year = {2020},<br>&nbsp;&nbsp;&nbsp;&nbsp;	journal = {Information Sciences},<br>&nbsp;&nbsp;&nbsp;&nbsp;	volume = {519},<br>&nbsp;&nbsp;&nbsp;&nbsp;	pages = {439 – 450},<br>&nbsp;&nbsp;&nbsp;&nbsp;	doi = {10.1016/j.ins.2020.01.034},<br>&nbsp;&nbsp;&nbsp;&nbsp;	url = {https://www.scopus.com/inward/record.uri?eid=2-s2.0-85079160299&doi=10.1016%2fj.ins.2020.01.034&partnerID=40&md5=2d80ac2cb125c6e9326073eb92a4f5a4},<br>&nbsp;&nbsp;&nbsp;&nbsp;	type = {Article},<br>&nbsp;&nbsp;&nbsp;&nbsp;	publication_stage = {Final},<br>&nbsp;&nbsp;&nbsp;&nbsp;	source = {Scopus},<br>&nbsp;&nbsp;&nbsp;&nbsp;	note = {Cited by: 8; All Open Access, Green Open Access}<br>}

:::



# Bibliometric data

## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Arag_n_20211></a>[[1]](#cite-Arag_n_20211) R. G. Aragón, J. Medina, and E. Ramírez-Poussa. “Characterization of the Infimum of Classes Induced by an Attribute Reduction in FCA”. In: _Computational Intelligence and Mathematics for Tackling Complex Problems 3_. Springer International Publishing, Aug. 2021, p. 73–79. ISBN: 9783030749705. DOI: [10.1007/978-3-030-74970-5_9](https://doi.org/10.1007%2F978-3-030-74970-5_9). URL: [http://dx.doi.org/10.1007/978-3-030-74970-5_9](http://dx.doi.org/10.1007/978-3-030-74970-5_9).

<a name=bib-Arag_n_2021></a>[[2]](#cite-Arag_n_2021) R. G. Aragón, J. Medina, and E. Ramírez-Poussa. “Identifying Non-Sublattice Equivalence Classes Induced by an Attribute Reduction in FCA”. In: _Mathematics_ 9.5 (Mar. 2021), p. 565. ISSN: 2227-7390. DOI: [10.3390/math9050565](https://doi.org/10.3390%2Fmath9050565). URL: [http://dx.doi.org/10.3390/math9050565](http://dx.doi.org/10.3390/math9050565).

<a name=bib-Cabrera_2022></a>[[3]](#cite-Cabrera_2022) I. P. Cabrera, P. Cordero, E. Muñoz-Velasco, et al. “On the Definition of Fuzzy Relational Galois Connections Between Fuzzy Transitive Digraphs”. In: _Information Processing and Management of Uncertainty in Knowledge-Based Systems_. Springer International Publishing, 2022, p. 100–106. ISBN: 9783031089718. DOI: [10.1007/978-3-031-08971-8_9](https://doi.org/10.1007%2F978-3-031-08971-8_9). URL: [http://dx.doi.org/10.1007/978-3-031-08971-8_9](http://dx.doi.org/10.1007/978-3-031-08971-8_9).

<a name=bib-Cabrera_2023></a>[[4]](#cite-Cabrera_2023) I. Cabrera, P. Cordero, E. Muñoz-Velasco, et al. “Fuzzy relational Galois connections between fuzzy transitive digraphs”. In: _Fuzzy Sets and Systems_ 463 (Jul. 2023), p. 108456. ISSN: 0165-0114. DOI: [10.1016/j.fss.2022.12.012](https://doi.org/10.1016%2Fj.fss.2022.12.012). URL: [http://dx.doi.org/10.1016/j.fss.2022.12.012](http://dx.doi.org/10.1016/j.fss.2022.12.012).

<a name=bib-Madrid_2023></a>[[5]](#cite-Madrid_2023) N. Madrid and M. Ojeda-Aciego. “The f-index of inclusion as optimal adjoint pair for fuzzy modus ponens”. In: _Fuzzy Sets and Systems_ 466 (Aug. 2023), p. 108474. ISSN: 0165-0114. DOI: [10.1016/j.fss.2023.01.009](https://doi.org/10.1016%2Fj.fss.2023.01.009). URL: [http://dx.doi.org/10.1016/j.fss.2023.01.009](http://dx.doi.org/10.1016/j.fss.2023.01.009).

<a name=bib-Ojeda_Hernandez_2021></a>[[6]](#cite-Ojeda_Hernandez_2021) M. Ojeda-Hernandez, I. P. Cabrera, P. Cordero, et al. “On (fuzzy) closure systems in complete fuzzy lattices”. In: _2021 IEEE International Conference on Fuzzy Systems (FUZZ-IEEE)_. IEEE, Jul. 2021, p. 1–6. DOI: [10.1109/fuzz45933.2021.9494404](https://doi.org/10.1109%2Ffuzz45933.2021.9494404). URL: [http://dx.doi.org/10.1109/fuzz45933.2021.9494404](http://dx.doi.org/10.1109/fuzz45933.2021.9494404).

<a name=bib-Ojeda_Hern_ndez_2022></a>[[7]](#cite-Ojeda_Hern_ndez_2022) M. Ojeda-Hernández, I. P. Cabrera, P. Cordero, et al. “Fuzzy closure relations”. In: _Fuzzy Sets and Systems_ 450 (Dec. 2022), p. 118–132. ISSN: 0165-0114. DOI: [10.1016/j.fss.2022.05.016](https://doi.org/10.1016%2Fj.fss.2022.05.016). URL: [http://dx.doi.org/10.1016/j.fss.2022.05.016](http://dx.doi.org/10.1016/j.fss.2022.05.016).

<a name=bib-Ojeda_Hern_ndez_2023></a>[[8]](#cite-Ojeda_Hern_ndez_2023) M. Ojeda-Hernández, I. P. Cabrera, P. Cordero, et al. “Fuzzy closure structures as formal concepts”. In: _Fuzzy Sets and Systems_ 463 (Jul. 2023), p. 108458. ISSN: 0165-0114. DOI: [10.1016/j.fss.2022.12.014](https://doi.org/10.1016%2Fj.fss.2022.12.014). URL: [http://dx.doi.org/10.1016/j.fss.2022.12.014](http://dx.doi.org/10.1016/j.fss.2022.12.014).


