---
title: Fuzzy Logic, Soft Computing, and Applications
author:
- <a href='/people/staff/ipcabrera/' style='color:rgb(100,0,50);'>Inma P. Cabrera</a>
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '2009'
categories: uncategorised
slug: 2009/FuSoAp
details: 'Bio-Inspired Systems: Computational and Ambient Intelligence, 10th International
  Work-Conference on Artificial Neural Networks, {IWANN} 2009, Salamanca, Spain, June
  10-12, 2009. Proceedings, Part {I} , Lecture Notes in Computer Science vol. 5517,
  pages 236--244.'
doi: 10.1007/978-3-642-02478-8_30
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Cabrera2009c></a>[[CCO09]](#cite-Cabrera2009c) I. P. Cabrera, P. Cordero, and M. Ojeda-Aciego. “Fuzzy Logic, Soft Computing, and Applications”. In: _Bio-Inspired Systems: Computational and Ambient Intelligence, 10th International Work-Conference on Artificial Neural Networks, IWANN 2009, Salamanca, Spain, June 10-12, 2009. Proceedings, Part I_. Ed. by J. Cabestany, F. S. Hernández, A. Prieto and J. M. Corchado. Vol. 5517. Lecture Notes in Computer Science. Springer, 2009, pp. 236-244. DOI: [10.1007/978-3-642-02478-8\_30](https://doi.org/10.1007%2F978-3-642-02478-8%5C_30). URL: [https://doi.org/10.1007/978-3-642-02478-8\_30](https://doi.org/10.1007/978-3-642-02478-8\_30).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Cabrera2009c,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Inma P. Cabrera and Pablo Cordero and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Bio-Inspired Systems: Computational and Ambient Intelligence, 10th International Work-Conference on Artificial Neural Networks, {IWANN} 2009, Salamanca, Spain, June 10-12, 2009. Proceedings, Part {I}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Fuzzy Logic, Soft Computing, and Applications},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2009},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Joan Cabestany and Francisco Sandoval Hern{\a'a}ndez and Alberto Prieto and Juan M. Corchado},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {236--244},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {5517},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/iwann/CabreraCO09.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/978-3-642-02478-8\_30},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 06 Dec 2019 09:55:14 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/978-3-642-02478-8\_30},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/978-3-642-02478-8_30" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/978-3-642-02478-8_30" class="plumx-details" data-site="plum" data-hide-when-empty="true">Fuzzy Logic, Soft Computing, and Applications</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1007/978-3-642-02478-8_30"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Alsyouf_2011></a>[[1]](#cite-Alsyouf_2011) I. Alsyouf. “Wind energy system reliability and maintainability, and operation and maintenance strategies”. In: _Wind Energy Systems_. Elsevier, 2011, p. 303–328. ISBN: 9781845695804. DOI: [10.1533/9780857090638.3.303](https://doi.org/10.1533%2F9780857090638.3.303). URL: [http://dx.doi.org/10.1533/9780857090638.3.303](http://dx.doi.org/10.1533/9780857090638.3.303).

<a name=bib-Cordov_s_2014></a>[[2]](#cite-Cordov_s_2014) T. C. Cordovés, A. R. Suárez, and R. A. E. Andrade. “Knowledge Discovery by Fuzzy Predicates”. In: _Soft Computing for Business Intelligence_. Springer Berlin Heidelberg, 2014, p. 187–196. ISBN: 9783642537370. DOI: [10.1007/978-3-642-53737-0_13](https://doi.org/10.1007%2F978-3-642-53737-0_13). URL: [http://dx.doi.org/10.1007/978-3-642-53737-0_13](http://dx.doi.org/10.1007/978-3-642-53737-0_13).

<a name=bib-Ghandar_2016></a>[[3]](#cite-Ghandar_2016) A. Ghandar, Z. Michalewicz, and R. Zurbruegg. “The relationship between model complexity and forecasting performance for computer intelligence optimization in finance”. In: _International Journal of Forecasting_ 32.3 (Jul. 2016), p. 598–613. ISSN: 0169-2070. DOI: [10.1016/j.ijforecast.2015.10.003](https://doi.org/10.1016%2Fj.ijforecast.2015.10.003). URL: [http://dx.doi.org/10.1016/j.ijforecast.2015.10.003](http://dx.doi.org/10.1016/j.ijforecast.2015.10.003).

<a name=bib-Gupta_2021></a>[[4]](#cite-Gupta_2021) M. Gupta, P. Garg, and P. Agarwal. “Ant Colony Optimization Technique in Soft Computational Data Research for NP-Hard Problems”. In: _Artificial Intelligence for a Sustainable Industry 4.0_. Springer International Publishing, 2021, p. 197–211. ISBN: 9783030770709. DOI: [10.1007/978-3-030-77070-9_12](https://doi.org/10.1007%2F978-3-030-77070-9_12). URL: [http://dx.doi.org/10.1007/978-3-030-77070-9_12](http://dx.doi.org/10.1007/978-3-030-77070-9_12).

<a name=bib-Iqbal_2021></a>[[5]](#cite-Iqbal_2021) N. Iqbal and J. Sang. “Fuzzy Logic Testing Approach for Measuring Software Completeness”. In: _Symmetry_ 13.4 (Apr. 2021), p. 604. ISSN: 2073-8994. DOI: [10.3390/sym13040604](https://doi.org/10.3390%2Fsym13040604). URL: [http://dx.doi.org/10.3390/sym13040604](http://dx.doi.org/10.3390/sym13040604).

<a name=bib-Kaur_2016></a>[[6]](#cite-Kaur_2016) D. Kaur. “Simulations of Various Applications of Fuzzy Logic using the MATLAB”. In: _International Journal of Computer Applications_ 141.13 (May. 2016), p. 39–45. ISSN: 0975-8887. DOI: [10.5120/ijca2016909746](https://doi.org/10.5120%2Fijca2016909746). URL: [http://dx.doi.org/10.5120/ijca2016909746](http://dx.doi.org/10.5120/ijca2016909746).

<a name=bib-Kerdegari_2015></a>[[7]](#cite-Kerdegari_2015) H. Kerdegari, S. Mokaram, K. Samsudin, et al. “A pervasive neural network based fall detection system on smart phone”. In: _Journal of Ambient Intelligence and Smart Environments_ 7.2 (2015), p. 221–230. ISSN: 1876-1364. DOI: [10.3233/ais-150306](https://doi.org/10.3233%2Fais-150306). URL: [http://dx.doi.org/10.3233/ais-150306](http://dx.doi.org/10.3233/ais-150306).

<a name=bib-Kumar_2022></a>[[8]](#cite-Kumar_2022) L. Kumar, S. Srivastava, R. Gupta, et al. “Soft Computing Applications in Solving Real Life Problems”. In: _SSRN Electronic Journal_ (2022). ISSN: 1556-5068. DOI: [10.2139/ssrn.4157331](https://doi.org/10.2139%2Fssrn.4157331). URL: [http://dx.doi.org/10.2139/ssrn.4157331](http://dx.doi.org/10.2139/ssrn.4157331).

<a name=bib-Loh_2010></a>[[9]](#cite-Loh_2010) P. K. K. Loh and D. Subramanian. “Fuzzy Classification Metrics for Scanner Assessment and Vulnerability Reporting”. In: _IEEE Transactions on Information Forensics and Security_ 5.4 (Dec. 2010), p. 613–624. ISSN: 1556-6021. DOI: [10.1109/tifs.2010.2075926](https://doi.org/10.1109%2Ftifs.2010.2075926). URL: [http://dx.doi.org/10.1109/tifs.2010.2075926](http://dx.doi.org/10.1109/tifs.2010.2075926).

<a name=bib-Mankad_2013></a>[[10]](#cite-Mankad_2013) K. Mankad and P. S. Sajja. “Measuring Human Intelligence by Applying Soft Computing Techniques: A Genetic Fuzzy Approach”. In: _Diagnostic Test Approaches to Machine Learning and Commonsense Reasoning Systems_. IGI Global, 2013, p. 130–155. DOI: [10.4018/978-1-4666-1900-5.ch006](https://doi.org/10.4018%2F978-1-4666-1900-5.ch006). URL: [http://dx.doi.org/10.4018/978-1-4666-1900-5.ch006](http://dx.doi.org/10.4018/978-1-4666-1900-5.ch006).

<a name=bib-Nagpal_2017></a>[[11]](#cite-Nagpal_2017) R. Nagpal, D. Mehrotra, and P. K. Bhatia. “The State of Art in Website Usability Evaluation Methods”. In: _Design Solutions for User-Centric Information Systems_. IGI Global, 2017, p. 275–296. DOI: [10.4018/978-1-5225-1944-7.ch015](https://doi.org/10.4018%2F978-1-5225-1944-7.ch015). URL: [http://dx.doi.org/10.4018/978-1-5225-1944-7.ch015](http://dx.doi.org/10.4018/978-1-5225-1944-7.ch015).

<a name=bib-Pei_2015></a>[[12]](#cite-Pei_2015) Z. Pei and L. Yi. “A note on operations of hesitant fuzzy sets”. In: _International Journal of Computational Intelligence Systems_ 8.2 (2015), p. 226. ISSN: 1875-6883. DOI: [10.1080/18756891.2015.1001947](https://doi.org/10.1080%2F18756891.2015.1001947). URL: [http://dx.doi.org/10.1080/18756891.2015.1001947](http://dx.doi.org/10.1080/18756891.2015.1001947).

<a name=bib-Qin_2010></a>[[13]](#cite-Qin_2010) K. Qin and Z. Hong. “On soft equality”. In: _Journal of Computational and Applied Mathematics_ 234.5 (Jul. 2010), p. 1347–1355. ISSN: 0377-0427. DOI: [10.1016/j.cam.2010.02.028](https://doi.org/10.1016%2Fj.cam.2010.02.028). URL: [http://dx.doi.org/10.1016/j.cam.2010.02.028](http://dx.doi.org/10.1016/j.cam.2010.02.028).

