---
author: Domingo López-Rodríguez, Ángel Mora, Manuel Ojeda-Hernández
Status: Published
date: '2022-06-21T00:00:00Z'
slug: 2022/ReAlFuCoLa
title: Revisiting Algorithms for Fuzzy Concept Lattices
categories: Formal concept analysis
header_image: ~
details: the <em>16th International Conference on Concept Lattices and Applications
  2022</em>
link: 2022-cla/paper.pdf
project: 2019-flair
keywords: Formal concept analysis, Concept lattice, Algorithms
listing:
- id: funding
  contents: funding.yml
  type: default
  sort: date desc
---


# Abstract


A central notion in Formal Concept Analysis is the concept lattice. This lattice allows describing a hierarchical biclustering between objects and attributes of a formal context, whose hierarchy is defined by an order that expresses the specialisation-generalisation relationship between concepts. It is a fundamental way of representing the knowledge implicit in the context. Therefore, in practice, due to its theoretical complexity, it is necessary to define computationally efficient algorithms for its calculation. In the literature, several algorithms, using different approaches, have been proposed for the computation of the lattice in the classical framework, where the presence of an attribute in an object is modelled as a binary value, indicating that the attribute is either present or absent. However, it is possible to extend this framework to take into account the different degrees to which an attribute could be present in an object. Through this extension, it is possible to model fuzzy situations where the attribute is not 100% present in an object, giving flexibility to the model. In this paper, we review some of the best known algorithms for the calculation of the concept lattice in the binary version, and we extend them for the calculation of the fuzzy concept lattice, presenting the most significant differences with respect to the original binary versions. In addition, we will present examples of the execution of these new versions of the algorithms.




# Funding
::: {.callout-note appearance='minimal' collapse=false}
## Projects funding this work

:::{#funding}
:::
:::









# Citation
Please, cite this work as:


<a name=bib-CLA2022Revisiting></a>[[LMO22]](#cite-CLA2022Revisiting) D. López-Rodríguez, Á. Mora, and M. Ojeda-Hernández. “Revisiting Algorithms for Fuzzy Concept Lattices”. In: _The 16th International Conference on Concept Lattices and Applications_. CLA. 2022, pp. 107 - 118.

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@inproceedings{CLA2022Revisiting,<br>&nbsp;&nbsp;&nbsp;&nbsp;  title={Revisiting Algorithms for Fuzzy Concept Lattices},<br>&nbsp;&nbsp;&nbsp;&nbsp;  author={López-Rodríguez, D. and Mora, Á., and Ojeda-Hernández, M.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle={The 16th International Conference on Concept Lattices and Applications},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages={107 -- 118},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year={2022},<br>&nbsp;&nbsp;&nbsp;&nbsp;  organization={CLA}<br>}

:::









