---
title: Analyzing completeness of axiomatic functional systems for temporal {\texttimes}
  modal logics
author:
- Alfredo Burrieza
- Inmaculada Perez de Guzmán
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
date: '2010'
categories: uncategorised
slug: 2010/AnCoAxFuSyTeMoLo
details: Math. Log. Q. vol. 56 (1), pages 89--102.
doi: 10.1002/MALQ.200810038
---



# Abstract


Abstract In previous works, we presented a modification of the usual possible world semantics by introducing an independent temporal structure in each world and using accessibility functions to represent the relation among them. Different properties ofthe accessibility functions (being injective, surjective, increasing, etc.) have been considered and axiomatic systems (called functional) which define these properties have been given. Only a few ofthese systems have been proved tobe complete. The aim ofthis paper is to make a progress in the study ofcompleteness for functional systems. For this end, we use indexes as names for temporal flows and give new proofs of completeness. Specifically, we focus our attention on the system which defines injectivity, because the system which defines this property without using indexes was proved to be incomplete in previous works. The only system considered which remains incomplete is the one which defines surjectivity, even ifwe consider a sequence ofnatural extensions ofthe previous one (© 2010 WILEY‐VCH Verlag GmbH &amp; Co. KGaA, Weinheim)








# Citation
Please, cite this work as:


<a name=bib-Burrieza2010></a>[[BGM10]](#cite-Burrieza2010) A. Burrieza, I. P. de Guzmán, and E. Mu~noz-Velasco. “Analyzing completeness of axiomatic functional systems for temporal × modal logics”. In: _Math. Log. Q._ 56.1 (2010), pp. 89-102. DOI: [10.1002/MALQ.200810038](https://doi.org/10.1002%2FMALQ.200810038). URL: [https://doi.org/10.1002/malq.200810038](https://doi.org/10.1002/malq.200810038).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{Burrieza2010,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Alfredo Burrieza and Inmaculada Perez {de Guzm{\a'a}n} and Emilio Mu~noz-Velasco},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Math. Log. Q.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Analyzing completeness of axiomatic functional systems for temporal {\texttimes} modal logics},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2010},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number = {1},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {89--102},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {56},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/mlq/BurriezaGM10.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1002/MALQ.200810038},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Tue, 06 Jun 2017 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1002/malq.200810038},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1002/MALQ.200810038" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1002/MALQ.200810038" class="plumx-details" data-site="plum" data-hide-when-empty="true">Analyzing completeness of axiomatic functional systems for temporal {\texttimes} modal logics</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1002/MALQ.200810038"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Burrieza_2017></a>[[1]](#cite-Burrieza_2017) A. Burrieza, I. Fortes, and I. P. de Guzmán. “Completeness of a functional system for surjective functions”. In: _Mathematical Logic Quarterly_ 63.6 (Dec. 2017), p. 574–597. ISSN: 1521-3870. DOI: [10.1002/malq.201600011](https://doi.org/10.1002%2Fmalq.201600011). URL: [http://dx.doi.org/10.1002/malq.201600011](http://dx.doi.org/10.1002/malq.201600011).

<a name=bib-Burrieza_2009></a>[[2]](#cite-Burrieza_2009) A. Burrieza, I. P. de Guzmán, and E. Muñoz-Velasco. “Functional systems in the context of temporal×modal logics with indexed flows”. In: _International Journal of Computer Mathematics_ 86.10–11 (Nov. 2009), p. 1696–1706. ISSN: 1029-0265. DOI: [10.1080/00207160902795619](https://doi.org/10.1080%2F00207160902795619). URL: [http://dx.doi.org/10.1080/00207160902795619](http://dx.doi.org/10.1080/00207160902795619).

