---
title: 'Sorted Multi-adjoint Logic Programs: Termination Results and Applications'
author:
- Carlos Viegas Damásio
- Jesús Medina
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '2004'
categories: uncategorised
slug: 2004/SoLoTeReAp
details: Logics in Artificial Intelligence, 9th European Conference, {JELIA} 2004,
  Lisbon, Portugal, September 27-30, 2004, Proceedings , Lecture Notes in Computer
  Science vol. 3229, pages 252--265.
doi: 10.1007/978-3-540-30227-8_23
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Damasio2004a></a>[[DMO04]](#cite-Damasio2004a) C. V. Damásio, J. Medina, and M. Ojeda-Aciego. “Sorted Multi-adjoint Logic Programs: Termination Results and Applications”. In: _Logics in Artificial Intelligence, 9th European Conference, JELIA 2004, Lisbon, Portugal, September 27-30, 2004, Proceedings_. Ed. by J. J. Alferes and J. A. Leite. Vol. 3229. Lecture Notes in Computer Science. Springer, 2004, pp. 252-265. DOI: [10.1007/978-3-540-30227-8\_23](https://doi.org/10.1007%2F978-3-540-30227-8%5C_23). URL: [https://doi.org/10.1007/978-3-540-30227-8\_23](https://doi.org/10.1007/978-3-540-30227-8\_23).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Damasio2004a,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Carlos Viegas Dam{\a'a}sio and Jes{\a'u}s Medina and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Logics in Artificial Intelligence, 9th European Conference, {JELIA} 2004, Lisbon, Portugal, September 27-30, 2004, Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Sorted Multi-adjoint Logic Programs: Termination Results and Applications},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2004},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Jos{\a'e} J{\a'u}lio Alferes and Jo~ao Alexandre Leite},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {252--265},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {3229},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/jelia/DamasioMO04.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/978-3-540-30227-8\_23},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Tue, 07 May 2024 20:11:09 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/978-3-540-30227-8\_23},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/978-3-540-30227-8_23" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/978-3-540-30227-8_23" class="plumx-details" data-site="plum" data-hide-when-empty="true">Sorted Multi-adjoint Logic Programs: Termination Results and Applications</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1007/978-3-540-30227-8_23"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Dam_sio_2004></a>[[1]](#cite-Dam_sio_2004) C. V. Damásio, J. Medina, and M. Ojeda-Aciego. “Sorted Multi-adjoint Logic Programs: Termination Results and Applications”. In: _Logics in Artificial Intelligence_. Springer Berlin Heidelberg, 2004, p. 252–265. ISBN: 9783540302278. DOI: [10.1007/978-3-540-30227-8_23](https://doi.org/10.1007%2F978-3-540-30227-8_23). URL: [http://dx.doi.org/10.1007/978-3-540-30227-8_23](http://dx.doi.org/10.1007/978-3-540-30227-8_23).

<a name=bib-Damasio_2006></a>[[2]](#cite-Damasio_2006) C. Damasio, J. Medina, and M. Ojeda-Aciego. “A Tabulation Proof Procedure for First-order Residuated Logic Programs: Soundness, Completeness and Optimizations”. In: _2006 IEEE International Conference on Fuzzy Systems_. IEEE, 2006, p. 2004–2011. DOI: [10.1109/fuzzy.2006.1681978](https://doi.org/10.1109%2Ffuzzy.2006.1681978). URL: [http://dx.doi.org/10.1109/fuzzy.2006.1681978](http://dx.doi.org/10.1109/fuzzy.2006.1681978).

<a name=bib-Dam_sio_2007></a>[[3]](#cite-Dam_sio_2007) C. Damásio, J. Medina, and M. Ojeda-Aciego. “Termination of logic programs with imperfect information: applications and query procedure”. In: _Journal of Applied Logic_ 5.3 (Sep. 2007), p. 435–458. ISSN: 1570-8683. DOI: [10.1016/j.jal.2006.03.004](https://doi.org/10.1016%2Fj.jal.2006.03.004). URL: [http://dx.doi.org/10.1016/j.jal.2006.03.004](http://dx.doi.org/10.1016/j.jal.2006.03.004).

<a name=bib-Eugenia_Cornejo_2013></a>[[4]](#cite-Eugenia_Cornejo_2013) M. Eugenia Cornejo, J. Medina, and E. Ramírez. “A comparative study of adjoint triples”. In: _Fuzzy Sets and Systems_ 211 (Jan. 2013), p. 1–14. ISSN: 0165-0114. DOI: [10.1016/j.fss.2012.05.004](https://doi.org/10.1016%2Fj.fss.2012.05.004). URL: [http://dx.doi.org/10.1016/j.fss.2012.05.004](http://dx.doi.org/10.1016/j.fss.2012.05.004).

<a name=bib-Janssen_2008></a>[[5]](#cite-Janssen_2008) J. Janssen, S. Heymans, D. Vermeir, et al. “Compiling Fuzzy Answer Set Programs to Fuzzy Propositional Theories”. In: _Logic Programming_. Springer Berlin Heidelberg, 2008, p. 362–376. ISBN: 9783540899822. DOI: [10.1007/978-3-540-89982-2_34](https://doi.org/10.1007%2F978-3-540-89982-2_34). URL: [http://dx.doi.org/10.1007/978-3-540-89982-2_34](http://dx.doi.org/10.1007/978-3-540-89982-2_34).

<a name=bib-Janssen_2012></a>[[6]](#cite-Janssen_2012) J. Janssen, S. Schockaert, D. Vermeir, et al. “A core language for fuzzy answer set programming”. In: _International Journal of Approximate Reasoning_ 53.4 (Jun. 2012), p. 660–692. ISSN: 0888-613X. DOI: [10.1016/j.ijar.2012.01.005](https://doi.org/10.1016%2Fj.ijar.2012.01.005). URL: [http://dx.doi.org/10.1016/j.ijar.2012.01.005](http://dx.doi.org/10.1016/j.ijar.2012.01.005).

<a name=bib-Janssen_2009></a>[[7]](#cite-Janssen_2009) J. Janssen, S. Schockaert, D. Vermeir, et al. “General Fuzzy Answer Set Programs”. In: _Fuzzy Logic and Applications_. Springer Berlin Heidelberg, 2009, p. 352–359. ISBN: 9783642022821. DOI: [10.1007/978-3-642-02282-1_44](https://doi.org/10.1007%2F978-3-642-02282-1_44). URL: [http://dx.doi.org/10.1007/978-3-642-02282-1_44](http://dx.doi.org/10.1007/978-3-642-02282-1_44).

<a name=bib-JANSSEN_2011></a>[[8]](#cite-JANSSEN_2011) J. JANSSEN, D. VERMEIR, S. SCHOCKAERT, et al. “Reducing fuzzy answer set programming to model finding in fuzzy logics”. In: _Theory and Practice of Logic Programming_ 12.6 (Jun. 2011), p. 811–842. ISSN: 1475-3081. DOI: [10.1017/s1471068411000093](https://doi.org/10.1017%2Fs1471068411000093). URL: [http://dx.doi.org/10.1017/s1471068411000093](http://dx.doi.org/10.1017/s1471068411000093).

<a name=bib-Juli_n_2009></a>[[9]](#cite-Juli_n_2009) P. Julián, G. Moreno, and J. Penabad. “An improved reductant calculus using fuzzy partial evaluation techniques”. In: _Fuzzy Sets and Systems_ 160.2 (Jan. 2009), p. 162–181. ISSN: 0165-0114. DOI: [10.1016/j.fss.2008.05.006](https://doi.org/10.1016%2Fj.fss.2008.05.006). URL: [http://dx.doi.org/10.1016/j.fss.2008.05.006](http://dx.doi.org/10.1016/j.fss.2008.05.006).

<a name=bib-Kuhr_2015></a>[[10]](#cite-Kuhr_2015) T. Kuhr and V. Vychodil. “Fuzzy logic programming reduced to reasoning with attribute implications”. In: _Fuzzy Sets and Systems_ 262 (Mar. 2015), p. 1–20. ISSN: 0165-0114. DOI: [10.1016/j.fss.2014.04.013](https://doi.org/10.1016%2Fj.fss.2014.04.013). URL: [http://dx.doi.org/10.1016/j.fss.2014.04.013](http://dx.doi.org/10.1016/j.fss.2014.04.013).

<a name=bib-Medina_Moreno_2013></a>[[11]](#cite-Medina_Moreno_2013) J. Medina-Moreno, M. Ojeda-Aciego, and J. Ruiz-Calviño. “Concept-Forming Operators on Multilattices”. In: _Formal Concept Analysis_. Springer Berlin Heidelberg, 2013, p. 203–215. ISBN: 9783642383175. DOI: [10.1007/978-3-642-38317-5_13](https://doi.org/10.1007%2F978-3-642-38317-5_13). URL: [http://dx.doi.org/10.1007/978-3-642-38317-5_13](http://dx.doi.org/10.1007/978-3-642-38317-5_13).

<a name=bib-Medina_2007></a>[[12]](#cite-Medina_2007) J. Medina, M. Ojeda-Aciego, and J. Ruiz-Calviño. “Fuzzy logic programming via multilattices”. In: _Fuzzy Sets and Systems_ 158.6 (Mar. 2007), p. 674–688. ISSN: 0165-0114. DOI: [10.1016/j.fss.2006.11.006](https://doi.org/10.1016%2Fj.fss.2006.11.006). URL: [http://dx.doi.org/10.1016/j.fss.2006.11.006](http://dx.doi.org/10.1016/j.fss.2006.11.006).

<a name=bib-Schockaert_2012></a>[[13]](#cite-Schockaert_2012) S. Schockaert, J. Janssen, and D. Vermeir. “Fuzzy Equilibrium Logic: Declarative Problem Solving in Continuous Domains”. In: _ACM Transactions on Computational Logic_ 13.4 (Oct. 2012), p. 1–39. ISSN: 1557-945X. DOI: [10.1145/2362355.2362361](https://doi.org/10.1145%2F2362355.2362361). URL: [http://dx.doi.org/10.1145/2362355.2362361](http://dx.doi.org/10.1145/2362355.2362361).

<a name=bib-Schockaert_2009></a>[[14]](#cite-Schockaert_2009) S. Schockaert, J. Janssen, D. Vermeir, et al. “Answer Sets in a Fuzzy Equilibrium Logic”. In: _Web Reasoning and Rule Systems_. Springer Berlin Heidelberg, 2009, p. 135–149. ISBN: 9783642050824. DOI: [10.1007/978-3-642-05082-4_10](https://doi.org/10.1007%2F978-3-642-05082-4_10). URL: [http://dx.doi.org/10.1007/978-3-642-05082-4_10](http://dx.doi.org/10.1007/978-3-642-05082-4_10).

<a name=bib-Straccia_2006></a>[[15]](#cite-Straccia_2006) U. Straccia. “Chapter 7 Uncertainty and description logic programs over lattices”. In: _Fuzzy Logic and the Semantic Web_. Elsevier, 2006, p. 115–133. DOI: [10.1016/s1574-9576(06)80009-2](https://doi.org/10.1016%2Fs1574-9576%2806%2980009-2). URL: [http://dx.doi.org/10.1016/s1574-9576(06)80009-2](http://dx.doi.org/10.1016/s1574-9576(06)80009-2).

<a name=bib-Straccia_2008></a>[[16]](#cite-Straccia_2008) U. Straccia. “Managing Uncertainty and Vagueness in Description Logics, Logic Programs and Description Logic Programs”. In: _Reasoning Web_. Springer Berlin Heidelberg, 2008, p. 54–103. ISBN: 9783540856580. DOI: [10.1007/978-3-540-85658-0_2](https://doi.org/10.1007%2F978-3-540-85658-0_2). URL: [http://dx.doi.org/10.1007/978-3-540-85658-0_2](http://dx.doi.org/10.1007/978-3-540-85658-0_2).

<a name=bib-Straccia_20051></a>[[17]](#cite-Straccia_20051) U. Straccia. “Query Answering in Normal Logic Programs Under Uncertainty”. In: _Symbolic and Quantitative Approaches to Reasoning with Uncertainty_. Springer Berlin Heidelberg, 2005, p. 687–700. ISBN: 9783540318880. DOI: [10.1007/11518655_58](https://doi.org/10.1007%2F11518655_58). URL: [http://dx.doi.org/10.1007/11518655_58](http://dx.doi.org/10.1007/11518655_58).

<a name=bib-Straccia_2005></a>[[18]](#cite-Straccia_2005) U. Straccia. “Uncertainty Management in Logic Programming: Simple and Effective Top-Down Query Answering”. In: _Knowledge-Based Intelligent Information and Engineering Systems_. Springer Berlin Heidelberg, 2005, p. 753–760. ISBN: 9783540319863. DOI: [10.1007/11552451_103](https://doi.org/10.1007%2F11552451_103). URL: [http://dx.doi.org/10.1007/11552451_103](http://dx.doi.org/10.1007/11552451_103).

<a name=bib-Straccia_2012></a>[[19]](#cite-Straccia_2012) U. Straccia and N. Madrid. “A top-k query answering procedure for fuzzy logic programming”. In: _Fuzzy Sets and Systems_ 205 (Oct. 2012), p. 1–29. ISSN: 0165-0114. DOI: [10.1016/j.fss.2012.01.016](https://doi.org/10.1016%2Fj.fss.2012.01.016). URL: [http://dx.doi.org/10.1016/j.fss.2012.01.016](http://dx.doi.org/10.1016/j.fss.2012.01.016).

<a name=bib-Van_Nieuwenborgh_2007></a>[[20]](#cite-Van_Nieuwenborgh_2007) D. Van Nieuwenborgh, M. De Cock, and D. Vermeir. “An introduction to fuzzy answer set programming”. In: _Annals of Mathematics and Artificial Intelligence_ 50.3–4 (Jul. 2007), p. 363–388. ISSN: 1573-7470. DOI: [10.1007/s10472-007-9080-3](https://doi.org/10.1007%2Fs10472-007-9080-3). URL: [http://dx.doi.org/10.1007/s10472-007-9080-3](http://dx.doi.org/10.1007/s10472-007-9080-3).

<a name=bib-Van_Nieuwenborgh_2006></a>[[21]](#cite-Van_Nieuwenborgh_2006) D. Van Nieuwenborgh, M. De Cock, and D. Vermeir. “Fuzzy Answer Set Programming”. In: _Logics in Artificial Intelligence_. Springer Berlin Heidelberg, 2006, p. 359–372. ISBN: 9783540396277. DOI: [10.1007/11853886_30](https://doi.org/10.1007%2F11853886_30). URL: [http://dx.doi.org/10.1007/11853886_30](http://dx.doi.org/10.1007/11853886_30).

