---
title: Monadic Formal Concept Analysis
author:
- Patrik Eklund
- María Ángeles Galán García
- Jari Kortelainen
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '2014'
categories: uncategorised
slug: 2014/MoFoCoAn
details: Rough Sets and Current Trends in Computing - 9th International Conference,
  {RSCTC} 2014, Granada and Madrid, Spain, July 9-13, 2014. Proceedings , Lecture
  Notes in Computer Science vol. 8536, pages 201--210.
doi: 10.1007/978-3-319-08644-6_21
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Eklund2014></a>[[Ekl+14]](#cite-Eklund2014) P. Eklund, M. G. Garc\'\ia, J. Kortelainen, et al. “Monadic Formal Concept Analysis”. In: _Rough Sets and Current Trends in Computing - 9th International Conference, RSCTC 2014, Granada and Madrid, Spain, July 9-13, 2014. Proceedings_. Ed. by C. Cornelis, M. Kryszkiewicz, D. Slezak, E. M. Ruiz, R. Bello and L. Shang. Vol. 8536. Lecture Notes in Computer Science. Springer, 2014, pp. 201-210. DOI: [10.1007/978-3-319-08644-6\_21](https://doi.org/10.1007%2F978-3-319-08644-6%5C_21). URL: [https://doi.org/10.1007/978-3-319-08644-6\_21](https://doi.org/10.1007/978-3-319-08644-6\_21).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Eklund2014,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Patrik Eklund and Mar\'\ia {\a'A}ngeles Gal{\a'a}n Garc\'\ia and Jari Kortelainen and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Rough Sets and Current Trends in Computing - 9th International Conference, {RSCTC} 2014, Granada and Madrid, Spain, July 9-13, 2014. Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Monadic Formal Concept Analysis},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2014},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Chris Cornelis and Marzena Kryszkiewicz and Dominik Slezak and Ernestina Menasalvas Ruiz and Rafael Bello and Lin Shang},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {201--210},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {8536},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/rsctc/EklundGKO14.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/978-3-319-08644-6\_21},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Sun, 02 Oct 2022 16:14:17 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/978-3-319-08644-6\_21},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/978-3-319-08644-6_21" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/978-3-319-08644-6_21" class="plumx-details" data-site="plum" data-hide-when-empty="true">Monadic Formal Concept Analysis</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1007/978-3-319-08644-6_21"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Eklund_2016></a>[[1]](#cite-Eklund_2016) P. Eklund. “The Syntax of Many-Valued Relations”. In: _Information Processing and Management of Uncertainty in Knowledge-Based Systems_. Springer International Publishing, 2016, p. 61–68. ISBN: 9783319405810. DOI: [10.1007/978-3-319-40581-0_6](https://doi.org/10.1007%2F978-3-319-40581-0_6). URL: [http://dx.doi.org/10.1007/978-3-319-40581-0_6](http://dx.doi.org/10.1007/978-3-319-40581-0_6).

<a name=bib-Eklund_2018></a>[[2]](#cite-Eklund_2018) P. Eklund and M. Galán-García. “Rough Objects in Monoidal Closed Categories”. In: _Algebraic Methods in General Rough Sets_. Springer International Publishing, 2018, p. 641–655. ISBN: 9783030011628. DOI: [10.1007/978-3-030-01162-8_8](https://doi.org/10.1007%2F978-3-030-01162-8_8). URL: [http://dx.doi.org/10.1007/978-3-030-01162-8_8](http://dx.doi.org/10.1007/978-3-030-01162-8_8).

<a name=bib-Eklund_2019></a>[[3]](#cite-Eklund_2019) P. Eklund and M. Löfstrand. “Uncertainty of value and structure”. In: _Proceedings of the 2019 Conference of the International Fuzzy Systems Association and the European Society for Fuzzy Logic and Technology (EUSFLAT 2019)_. eusflat-19. Atlantis Press, 2019. DOI: [10.2991/eusflat-19.2019.52](https://doi.org/10.2991%2Feusflat-19.2019.52). URL: [http://dx.doi.org/10.2991/eusflat-19.2019.52](http://dx.doi.org/10.2991/eusflat-19.2019.52).

<a name=bib-Nourani_2017></a>[[4]](#cite-Nourani_2017) C. F. Nourani and P. Eklund. “Concepts Ontology Algebras and Role Descriptions”. In: _Position Papers of the 2017 Federated Conference on Computer Science and Information Systems_. Vol. 12. FedCSIS 2017. PTI, Sep. 2017, p. 25–32. DOI: [10.15439/2017f554](https://doi.org/10.15439%2F2017f554). URL: [http://dx.doi.org/10.15439/2017f554](http://dx.doi.org/10.15439/2017f554).

