---
title: Bases via Minimal Generators
author:
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/enciso/' style='color:rgb(100,0,50);'>Manuel Enciso</a>
- <a href='/people/staff/amora/' style='color:rgb(100,0,50);'>Ángel Mora</a>
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '2013'
categories: uncategorised
slug: 2013/BaViMiGe
details: Proceedings of the International Workshop "What can {FCA} do for Artificial
  Intelligence?" {(FCA4AI} at {IJCAI} 2013), Beijing, China, August 5, 2013 , {CEUR}
  Workshop Proceedings vol. 1058, pages 33--36.
---



# Abstract


The concept lattice corresponding to a context may be alternatively specified by means of attribute implications. One outstanding problem in formal concept analysis and other areas is the study of the equivalences between a given set of implications and its corresponding basis (notice that there exists a wide range of approaches to basis in the literature). In this work we introduce a method to provide a Duquenne-Guigues basis corresponding to the minimal generators and their closed sets from a context








# Citation
Please, cite this work as:


<a name=bib-Cordero2013b></a>[[Cor+13]](#cite-Cordero2013b) P. Cordero, M. Enciso, Á. Mora, et al. “Bases via Minimal Generators”. In: _Proceedings of the International Workshop "What can FCA do for Artificial Intelligence?" (FCA4AI at IJCAI 2013), Beijing, China, August 5, 2013_. Ed. by S. O. Kuznetsov, A. Napoli and S. Rudolph. Vol. 1058. CEUR Workshop Proceedings. CEUR-WS.org, 2013, pp. 33-36. URL: [https://ceur-ws.org/Vol-1058/paper4.pdf](https://ceur-ws.org/Vol-1058/paper4.pdf).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Cordero2013b,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Pablo Cordero and Manuel Enciso and {\a'A}ngel Mora and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Proceedings of the International Workshop "What can {FCA} do for Artificial Intelligence?" {(FCA4AI} at {IJCAI} 2013), Beijing, China, August 5, 2013},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Bases via Minimal Generators},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2013},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Sergei O. Kuznetsov and Amedeo Napoli and Sebastian Rudolph},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {33--36},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {CEUR-WS.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {{CEUR} Workshop Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {1058},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {The concept lattice corresponding to a context may be alternatively specified by means of attribute implications. One outstanding problem in formal concept analysis and other areas is the study of the equivalences between a given set of implications and its corresponding basis (notice that there exists a wide range of approaches to basis in the literature). In this work we introduce a method to provide a Duquenne-Guigues basis corresponding to the minimal generators and their closed sets from a context},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/ijcai/CorderoEBO13.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 10 Mar 2023 16:23:32 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://ceur-ws.org/Vol-1058/paper4.pdf},<br>}

:::








