---
author: E. López-Rubio, J.M. Ortiz-de-Lazcano-Lobato, Domingo López-Rodríguez, E.
  Mérida-Casermeiro, M.D.C. Vargas-González
Status: Published
date: '2006-01-01'
slug: 2006-asc
title: Global-local learning strategies in probabilistic principal components analysis
categories:
- Neural networks
- Competitive learning
- Principal component analysis
header_image: ~
details: Proceedings of the 10th IASTED International Conference on Artificial Intelligence
  and Soft Computing, ASC 2006, <em>pp. 46-51</em>
doi: ''
link: 2006-asc/paper.pdf
project: ''
keywords: Artificial intelligence, Education, Neural networks, Probability, Soft computing,
  Basis vectors, Competition rules, Competitive learning, Competitive learnings, Learning
  processes, Local learning strategies, Local PCA, Neural models, Pca models, Principal
  components analyses, Principal directions, Principal component analysis
---



# Abstract


We present a neural model which extends classical competitive learning by performing a Probabilistic Principal Components Analysis at each neuron. In the learning process is utilized a competition rule which try to get the better representation of the dataset while maintaining the homogeneity of the formed clusters. The model also has the ability to learn the number of basis vectors required to represent the principal directions of each cluster, so it overcomes a drawback of most local PCA models, where the dimensionality of a cluster must be fixed a priori.







# Citation
Please, cite this work as:


<a name=bib-LopezRubio2006></a>[[Lóp+06]](#cite-LopezRubio2006) E. López-Rubio, J. Ortiz-de-Lazcano-Lobato, D. López-Rodríguez, et al. “Global-local learning strategies in probabilistic principal components analysis”. In: _Artificial Intelligence and Soft Computing, August 28-30, 2006, Palma de Mallorca, Spain_. Ed. by A. P. del Pobil. cited By 0; Conference of 10th IASTED International Conference on Artificial Intelligence and Soft Computing, ASC 2006 ; Conference Date: 28 August 2006 Through 30 August 2006; Conference Code:74030. Palma de Mallorca: IASTED/ACTA Press, 2006, pp. 46-51. URL: [https://www.scopus.com/inward/record.uri?eid=2-s2.0-56149099517&partnerID=40&md5=d435d7f751c9133a83357d3c5c884fd0](https://www.scopus.com/inward/record.uri?eid=2-s2.0-56149099517&partnerID=40&md5=d435d7f751c9133a83357d3c5c884fd0).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{LopezRubio2006,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {E. López-Rubio and J.M. Ortiz-de-Lazcano-Lobato and D. López-Rodríguez and E. Mérida-Casermeiro and M.D.C. Vargas-González},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Artificial Intelligence and Soft Computing, August 28-30, 2006, Palma de Mallorca, Spain},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Global-local learning strategies in probabilistic principal components analysis},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2006},<br>&nbsp;&nbsp;&nbsp;&nbsp;  address = {Palma de Mallorca},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Angel P. {del Pobil}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  note = {cited By 0; Conference of 10th IASTED International Conference on Artificial Intelligence and Soft Computing, ASC 2006 ; Conference Date: 28 August 2006 Through 30 August 2006; Conference Code:74030},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {46-51},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {{IASTED/ACTA} Press},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {We present a neural model which extends classical competitive learning by performing a Probabilistic Principal Components Analysis at each neuron. In the learning process is utilized a competition rule which try to get the better representation of the dataset while maintaining the homogeneity of the formed clusters. The model also has the ability to learn the number of basis vectors required to represent the principal directions of each cluster, so it overcomes a drawback of most local PCA models, where the dimensionality of a cluster must be fixed a priori.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  author_keywords = {Competitive learning; Local PCA; Neural networks},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/asc/Lopez-RubioOLCV06.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  document_type = {Conference Paper},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Proceedings of the 10th IASTED International Conference on Artificial Intelligence and Soft Computing, ASC 2006},<br>&nbsp;&nbsp;&nbsp;&nbsp;  keywords = {Artificial intelligence; Education; Neural networks; Probability; Soft computing, Basis vectors; Competition rules; Competitive learning; Competitive learnings; Learning processes; Local learning strategies; Local PCA; Neural models; Pca models; Principal components analyses; Principal directions, Principal component analysis},<br>&nbsp;&nbsp;&nbsp;&nbsp;  source = {Scopus},<br>&nbsp;&nbsp;&nbsp;&nbsp;  sponsors = {Int. Assoc. Science and Technology for Development (IASTED); Technical Committee on Artificial Intelligence and Expert Systems; Technical Committee on Soft Computing},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Thu, 18 Jul 2019 17:02:44 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://www.scopus.com/inward/record.uri?eid=2-s2.0-56149099517&partnerID=40&md5=d435d7f751c9133a83357d3c5c884fd0},<br>}

:::


