---
title: Towards a Sequent Calculus for Formal Contexts
author:
- Ondrej Kridlo
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '2016'
categories: uncategorised
slug: 2016/ToSeCaFoCo
details: Proceedings of the 5th International Workshop "What can {FCA} do for Artificial
  Intelligence"? co-located with the European Conference on Artificial Intelligence,
  FCA4AI@ECAI 2016, The Hague, the Netherlands, August 30, 2016 , {CEUR} Workshop
  Proceedings vol. 1703, pages 17--24.
---



# Abstract


This work focuses on the definition of a consequence relation between contexts with which we can decide whether certain contextual information is a logical consequence from a set of contexts considered as underlying hypotheses.








# Citation
Please, cite this work as:


<a name=bib-Kridlo2016></a>[[KO16]](#cite-Kridlo2016) O. Kridlo and M. Ojeda-Aciego. “Towards a Sequent Calculus for Formal Contexts”. In: _Proceedings of the 5th International Workshop "What can FCA do for Artificial Intelligence"? co-located with the European Conference on Artificial Intelligence, FCA4AI@ECAI 2016, The Hague, the Netherlands, August 30, 2016_. Ed. by S. O. Kuznetsov, A. Napoli and S. Rudolph. Vol. 1703. CEUR Workshop Proceedings. CEUR-WS.org, 2016, pp. 17-24. URL: [https://ceur-ws.org/Vol-1703/paper3.pdf](https://ceur-ws.org/Vol-1703/paper3.pdf).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Kridlo2016,  booktitle = {Proceedings of the 5th International Workshop "What can {FCA} do for Artificial Intelligence"? co-located with the European Conference on Artificial Intelligence, FCA4AI@ECAI 2016, The Hague, the Netherlands, August 30, 2016},<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Ondrej Kridlo and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Proceedings of the 5th International Workshop "What can {FCA} do for Artificial Intelligence"? co-located with the European Conference on Artificial Intelligence, FCA4AI@ECAI 2016, The Hague, the Netherlands, August 30, 2016},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Towards a Sequent Calculus for Formal Contexts},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2016},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Sergei O. Kuznetsov and Amedeo Napoli and Sebastian Rudolph},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {17--24},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {CEUR-WS.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {{CEUR} Workshop Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {1703},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {This work focuses on the definition of a consequence relation between contexts with which we can decide whether certain contextual information is a logical consequence from a set of contexts considered as underlying hypotheses.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/ecai/KridloO16.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 10 Mar 2023 16:22:14 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://ceur-ws.org/Vol-1703/paper3.pdf},<br>}

:::








