---
title: Formal Concept Analysis and Structures Underlying Quantum Logics
author:
- Ondrej Kridlo
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '2018'
categories: uncategorised
slug: 2018/FoCoAnStUnQuLo
details: Information Processing and Management of Uncertainty in Knowledge-Based Systems.
  Theory and Foundations - 17th International Conference, {IPMU} 2018, C{\'{a}}diz,
  Spain, June 11-15, 2018, Proceedings, Part {I} , Communications in Computer and
  Information Science vol. 853, pages 574--584.
doi: 10.1007/978-3-319-91473-2_49
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Kridlo2018></a>[[KO18]](#cite-Kridlo2018) O. Kridlo and M. Ojeda-Aciego. “Formal Concept Analysis and Structures Underlying Quantum Logics”. In: _Information Processing and Management of Uncertainty in Knowledge-Based Systems. Theory and Foundations - 17th International Conference, IPMU 2018, Cádiz, Spain, June 11-15, 2018, Proceedings, Part I_. Ed. by J. Medina, M. Ojeda-Aciego, J. L. V. Galdeano, D. A. Pelta, I. P. Cabrera, B. Bouchon-Meunier and R. R. Yager. Vol. 853. Communications in Computer and Information Science. Springer, 2018, pp. 574-584. DOI: [10.1007/978-3-319-91473-2\_49](https://doi.org/10.1007%2F978-3-319-91473-2%5C_49). URL: [https://doi.org/10.1007/978-3-319-91473-2\_49](https://doi.org/10.1007/978-3-319-91473-2\_49).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Kridlo2018,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Ondrej Kridlo and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Information Processing and Management of Uncertainty in Knowledge-Based Systems. Theory and Foundations - 17th International Conference, {IPMU} 2018, C{\'{a}}diz, Spain, June 11-15, 2018, Proceedings, Part {I}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Formal Concept Analysis and Structures Underlying Quantum Logics},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2018},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Jes{\a'u}s Medina and Manuel Ojeda-Aciego and Jos{\a'e} Luis Verdegay Galdeano and David A. Pelta and Inma P. Cabrera and Bernadette Bouchon-Meunier and Ronald R. Yager},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {574--584},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Communications in Computer and Information Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {853},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/ipmu/KridloO18.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/978-3-319-91473-2\_49},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Thu, 07 Jan 2021 08:57:40 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/978-3-319-91473-2\_49},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/978-3-319-91473-2_49" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/978-3-319-91473-2_49" class="plumx-details" data-site="plum" data-hide-when-empty="true">Formal Concept Analysis and Structures Underlying Quantum Logics</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1007/978-3-319-91473-2_49"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Cabrera_2019></a>[[1]](#cite-Cabrera_2019) I. P. Cabrera, P. Cordero, E. Muñoz-Velasco, et al. “A Relational Extension of Galois Connections”. In: _Formal Concept Analysis_. Springer International Publishing, 2019, p. 290–303. ISBN: 9783030214623. DOI: [10.1007/978-3-030-21462-3_19](https://doi.org/10.1007%2F978-3-030-21462-3_19). URL: [http://dx.doi.org/10.1007/978-3-030-21462-3_19](http://dx.doi.org/10.1007/978-3-030-21462-3_19).

<a name=bib-Cabrera_20191></a>[[2]](#cite-Cabrera_20191) I. P. Cabrera, P. Cordero, E. Muñoz-Velasco, et al. “Relational Connections Between Preordered Sets”. In: _Applied Physics, System Science and Computers III_. Springer International Publishing, 2019, p. 163–169. ISBN: 9783030215071. DOI: [10.1007/978-3-030-21507-1_24](https://doi.org/10.1007%2F978-3-030-21507-1_24). URL: [http://dx.doi.org/10.1007/978-3-030-21507-1_24](http://dx.doi.org/10.1007/978-3-030-21507-1_24).

<a name=bib-Cabrera_20192></a>[[3]](#cite-Cabrera_20192) I. P. Cabrera, P. Cordero, E. Muñoz-Velasco, et al. “Towards fuzzy relational Galois connections between fuzzy T-digraphs”. In: _Proceedings of the 2019 Conference of the International Fuzzy Systems Association and the European Society for Fuzzy Logic and Technology (EUSFLAT 2019)_. eusflat-19. Atlantis Press, 2019. DOI: [10.2991/eusflat-19.2019.112](https://doi.org/10.2991%2Feusflat-19.2019.112). URL: [http://dx.doi.org/10.2991/eusflat-19.2019.112](http://dx.doi.org/10.2991/eusflat-19.2019.112).

<a name=bib-Cabrera_2020></a>[[4]](#cite-Cabrera_2020) I. P. Cabrera, P. Cordero, E. Muñoz-Velasco, et al. “Relational Galois connections between transitive digraphs: Characterization and construction”. In: _Information Sciences_ 519 (May. 2020), p. 439–450. ISSN: 0020-0255. DOI: [10.1016/j.ins.2020.01.034](https://doi.org/10.1016%2Fj.ins.2020.01.034). URL: [http://dx.doi.org/10.1016/j.ins.2020.01.034](http://dx.doi.org/10.1016/j.ins.2020.01.034).

<a name=bib-Kr_dlo_2019></a>[[5]](#cite-Kr_dlo_2019) O. Krídlo and M. Ojeda-Aciego. “Relating Hilbert-Chu Correspondences and Big Toy Models for Quantum Mechanics”. In: _Computational Intelligence and Mathematics for Tackling Complex Problems_. Springer International Publishing, May. 2019, p. 75–80. ISBN: 9783030160241. DOI: [10.1007/978-3-030-16024-1_10](https://doi.org/10.1007%2F978-3-030-16024-1_10). URL: [http://dx.doi.org/10.1007/978-3-030-16024-1_10](http://dx.doi.org/10.1007/978-3-030-16024-1_10).

<a name=bib-Singh_2022></a>[[6]](#cite-Singh_2022) P. K. Singh. “Crisply Generated Complex Fuzzy Concepts Analysis Using Shannon Entropy”. In: _Neural Processing Letters_ 54.6 (May. 2022), p. 5643–5667. ISSN: 1573-773X. DOI: [10.1007/s11063-022-10878-7](https://doi.org/10.1007%2Fs11063-022-10878-7). URL: [http://dx.doi.org/10.1007/s11063-022-10878-7](http://dx.doi.org/10.1007/s11063-022-10878-7).

