---
title: 'Non-deterministic ideal operators: An adequate tool for formalization in Data
  Bases'
author:
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/amora/' style='color:rgb(100,0,50);'>Ángel Mora</a>
- <a href='/people/staff/ipguzman/' style='color:rgb(100,0,50);'>Inma P. de Guzmán</a>
- <a href='/people/staff/enciso/' style='color:rgb(100,0,50);'>Manuel Enciso</a>
date: '2008'
categories: uncategorised
slug: 2008/IdAdToFoDaBa
details: Discret. Appl. Math. vol. 156 (6), pages 911--923.
doi: 10.1016/J.DAM.2007.02.014
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Cordero2008></a>[[Cor+08]](#cite-Cordero2008) P. Cordero, Á. Mora, I. P. de Guzmán, et al. “Non-deterministic ideal operators: An adequate tool for formalization in Data Bases”. In: _Discret. Appl. Math._ 156.6 (2008), pp. 911-923. DOI: [10.1016/J.DAM.2007.02.014](https://doi.org/10.1016%2FJ.DAM.2007.02.014). URL: [https://doi.org/10.1016/j.dam.2007.02.014](https://doi.org/10.1016/j.dam.2007.02.014).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{Cordero2008,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Pablo Cordero and {\a'A}ngel Mora and Inman P. {de Guzm{\a'a}n} and Manuel Enciso},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Discret. Appl. Math.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Non-deterministic ideal operators: An adequate tool for formalization in Data Bases},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2008},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number = {6},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {911--923},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {156},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/dam/CorderoMGE08.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1016/J.DAM.2007.02.014},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 23 Sep 2022 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1016/j.dam.2007.02.014},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1016/J.DAM.2007.02.014" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1016/J.DAM.2007.02.014" class="plumx-details" data-site="plum" data-hide-when-empty="true">Non-deterministic ideal operators: An adequate tool for formalization in Data Bases</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1016/J.DAM.2007.02.014"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Cabrera_2010></a>[[1]](#cite-Cabrera_2010) I. Cabrera, P. Cordero, G. Gutiérrez, et al. “A coalgebraic approach to non-determinism: Applications to multilattices”. In: _Information Sciences_ 180.22 (Nov. 2010), p. 4323–4335. ISSN: 0020-0255. DOI: [10.1016/j.ins.2010.07.002](https://doi.org/10.1016%2Fj.ins.2010.07.002). URL: [http://dx.doi.org/10.1016/j.ins.2010.07.002](http://dx.doi.org/10.1016/j.ins.2010.07.002).

<a name=bib-Editor_2009></a>[[2]](#cite-Editor_2009) C. Editor. “Computer and Information Science, Vol. 2, No. 3, August 2009, all in one file, Part A”. In: _Computer and Information Science_ 2.3 (Jul. 2009). ISSN: 1913-8989. DOI: [10.5539/cis.v2n3p0a](https://doi.org/10.5539%2Fcis.v2n3p0a). URL: [http://dx.doi.org/10.5539/cis.v2n3p0a](http://dx.doi.org/10.5539/cis.v2n3p0a).

<a name=bib-Mora_2012></a>[[3]](#cite-Mora_2012) A. Mora, P. Cordero, M. Enciso, et al. “Closure via functional dependence simplification”. In: _International Journal of Computer Mathematics_ 89.4 (Mar. 2012), p. 510–526. ISSN: 1029-0265. DOI: [10.1080/00207160.2011.644275](https://doi.org/10.1080%2F00207160.2011.644275). URL: [http://dx.doi.org/10.1080/00207160.2011.644275](http://dx.doi.org/10.1080/00207160.2011.644275).

<a name=bib-Mora_2011></a>[[4]](#cite-Mora_2011) A. Mora, I. P. de Guzmán, M. Enciso, et al. “Ideal non-deterministic operators as a formal framework to reduce the key finding problem”. In: _International Journal of Computer Mathematics_ 88.9 (Jun. 2011), p. 1860–1868. ISSN: 1029-0265. DOI: [10.1080/00207160.2010.484488](https://doi.org/10.1080%2F00207160.2010.484488). URL: [http://dx.doi.org/10.1080/00207160.2010.484488](http://dx.doi.org/10.1080/00207160.2010.484488).

<a name=bib-Triska_2016></a>[[5]](#cite-Triska_2016) J. Triska and V. Vychodil. “Logic of temporal attribute implications”. In: _Annals of Mathematics and Artificial Intelligence_ 79.4 (Oct. 2016), p. 307–335. ISSN: 1573-7470. DOI: [10.1007/s10472-016-9526-6](https://doi.org/10.1007%2Fs10472-016-9526-6). URL: [http://dx.doi.org/10.1007/s10472-016-9526-6](http://dx.doi.org/10.1007/s10472-016-9526-6).

<a name=bib-Triska_2014></a>[[6]](#cite-Triska_2014) J. Triska and V. Vychodil. “Towards Armstrong-Style Inference System for Attribute Implications with Temporal Semantics”. In: _Modeling Decisions for Artificial Intelligence_. Springer International Publishing, 2014, p. 84–95. ISBN: 9783319120546. DOI: [10.1007/978-3-319-12054-6_8](https://doi.org/10.1007%2F978-3-319-12054-6_8). URL: [http://dx.doi.org/10.1007/978-3-319-12054-6_8](http://dx.doi.org/10.1007/978-3-319-12054-6_8).

<a name=bib-Vychodil_2015></a>[[7]](#cite-Vychodil_2015) V. Vychodil. “On minimal sets of graded attribute implications”. In: _Information Sciences_ 294 (Feb. 2015), p. 478–488. ISSN: 0020-0255. DOI: [10.1016/j.ins.2014.09.059](https://doi.org/10.1016%2Fj.ins.2014.09.059). URL: [http://dx.doi.org/10.1016/j.ins.2014.09.059](http://dx.doi.org/10.1016/j.ins.2014.09.059).

<a name=bib-Yan_2009></a>[[8]](#cite-Yan_2009) B. Yan. “Formulas of Retrieval Rate in Database Based on Normalization Design”. In: _Computer and Information Science_ 2.3 (Jul. 2009). ISSN: 1913-8989. DOI: [10.5539/cis.v2n3p32](https://doi.org/10.5539%2Fcis.v2n3p32). URL: [http://dx.doi.org/10.5539/cis.v2n3p32](http://dx.doi.org/10.5539/cis.v2n3p32).

