---
title: 'The Notion of Weak-Contradiction: Definition and Measures'
author:
- Humberto Bustince
- Nicolás Madrid
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '2015'
categories: uncategorised
slug: 2015/NoDeMe
details: '{IEEE} Trans. Fuzzy Syst. vol. 23 (4), pages 1057--1069.'
doi: 10.1109/TFUZZ.2014.2337934
---



# Abstract


In this paper, we present a way to represent contradiction between fuzzy sets. This representation is given in terms of the notion of f-weak-contradiction. Unlike other approaches, we do not define contradiction just by using one of the relations of f-weak-contradiction but by considering the whole set of relations. This consideration avoids the need to fix an operator beforehand in order to take into account all the information between two fuzzy sets. As a result, we characterize the contradiction between fuzzy sets and define a family of measures of contradiction satisfying four interesting properties: symmetry; antitonicity; if the intersection is empty, then the measure is one; and if there is an element in the intersection with degree of membership 1, then the measure is zero.








# Citation
Please, cite this work as:


<a name=bib-Bustince2015></a>[[BMO15]](#cite-Bustince2015) H. Bustince, N. Madrid, and M. Ojeda-Aciego. “The Notion of Weak-Contradiction: Definition and Measures”. In: _IEEE Trans. Fuzzy Syst._ 23.4 (2015), pp. 1057-1069. DOI: [10.1109/TFUZZ.2014.2337934](https://doi.org/10.1109%2FTFUZZ.2014.2337934). URL: [https://doi.org/10.1109/TFUZZ.2014.2337934](https://doi.org/10.1109/TFUZZ.2014.2337934).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{Bustince2015,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Humberto Bustince and Nicol{\a'a}s Madrid and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {{IEEE} Trans. Fuzzy Syst.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {The Notion of Weak-Contradiction: Definition and Measures},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2015},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number = {4},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {1057--1069},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {23},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/tfs/BustinceMO15.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1109/TFUZZ.2014.2337934},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Mon, 03 Jan 2022 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1109/TFUZZ.2014.2337934},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1109/TFUZZ.2014.2337934" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1109/TFUZZ.2014.2337934" class="plumx-details" data-site="plum" data-hide-when-empty="true">The Notion of Weak-Contradiction: Definition and Measures</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1109/TFUZZ.2014.2337934"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Ashraf_2018></a>[[1]](#cite-Ashraf_2018) Z. Ashraf, P. K. Muhuri, Q. M. D. Lohani, et al. “Type-2 fuzzy reliability–redundancy allocation problem and its solution using particle-swarm optimization algorithm”. In: _Granular Computing_ 4.2 (Jul. 2018), p. 145–166. ISSN: 2364-4974. DOI: [10.1007/s41066-018-0106-5](https://doi.org/10.1007%2Fs41066-018-0106-5). URL: [http://dx.doi.org/10.1007/s41066-018-0106-5](http://dx.doi.org/10.1007/s41066-018-0106-5).

<a name=bib-Cornejo_20201></a>[[2]](#cite-Cornejo_20201) M. E. Cornejo, D. Lobo, and J. Medina. “Extended multi-adjoint logic programming”. In: _Fuzzy Sets and Systems_ 388 (Jun. 2020), p. 124–145. ISSN: 0165-0114. DOI: [10.1016/j.fss.2019.03.016](https://doi.org/10.1016%2Fj.fss.2019.03.016). URL: [http://dx.doi.org/10.1016/j.fss.2019.03.016](http://dx.doi.org/10.1016/j.fss.2019.03.016).

<a name=bib-Cornejo_2020></a>[[3]](#cite-Cornejo_2020) M. E. Cornejo, D. Lobo, and J. Medina. “Relating Multi-Adjoint Normal Logic Programs to Core Fuzzy Answer Set Programs from a Semantical Approach”. In: _Mathematics_ 8.6 (Jun. 2020), p. 881. ISSN: 2227-7390. DOI: [10.3390/math8060881](https://doi.org/10.3390%2Fmath8060881). URL: [http://dx.doi.org/10.3390/math8060881](http://dx.doi.org/10.3390/math8060881).

<a name=bib-Cornejo_2017></a>[[4]](#cite-Cornejo_2017) M. E. Cornejo, D. Lobo, and J. Medina. “Selecting the Coherence Notion in Multi-adjoint Normal Logic Programming”. In: _Advances in Computational Intelligence_. Springer International Publishing, 2017, p. 447–457. ISBN: 9783319591537. DOI: [10.1007/978-3-319-59153-7_39](https://doi.org/10.1007%2F978-3-319-59153-7_39). URL: [http://dx.doi.org/10.1007/978-3-319-59153-7_39](http://dx.doi.org/10.1007/978-3-319-59153-7_39).

<a name=bib-Halas_2016></a>[[5]](#cite-Halas_2016) R. Halas, R. Mesiar, and J. Pocs. “Generators of Aggregation Functions and Fuzzy Connectives”. In: _IEEE Transactions on Fuzzy Systems_ 24.6 (Dec. 2016), p. 1690–1694. ISSN: 1941-0034. DOI: [10.1109/tfuzz.2016.2544353](https://doi.org/10.1109%2Ftfuzz.2016.2544353). URL: [http://dx.doi.org/10.1109/tfuzz.2016.2544353](http://dx.doi.org/10.1109/tfuzz.2016.2544353).

<a name=bib-Hala__2017></a>[[6]](#cite-Hala__2017) R. Halaš, R. Mesiar, and J. Pócs. “Description of sup- and inf-preserving aggregation functions via families of clusters in data tables”. In: _Information Sciences_ 400–401 (Aug. 2017), p. 173–183. ISSN: 0020-0255. DOI: [10.1016/j.ins.2017.02.060](https://doi.org/10.1016%2Fj.ins.2017.02.060). URL: [http://dx.doi.org/10.1016/j.ins.2017.02.060](http://dx.doi.org/10.1016/j.ins.2017.02.060).

<a name=bib-Madrid_2020></a>[[7]](#cite-Madrid_2020) N. Madrid, J. Medina, and E. Ramírez-Poussa. “Rough sets based on Galois connections”. In: _International Journal of Applied Mathematics and Computer Science_ 30.2 (2020). ISSN: 2083-8492. DOI: [10.34768/amcs-2020-0023](https://doi.org/10.34768%2Famcs-2020-0023). URL: [http://dx.doi.org/10.34768/amcs-2020-0023](http://dx.doi.org/10.34768/amcs-2020-0023).

<a name=bib-Madrid_2017></a>[[8]](#cite-Madrid_2017) N. Madrid and M. Ojeda-Aciego. “A View of f-indexes of Inclusion Under Different Axiomatic Definitions of Fuzzy Inclusion”. In: _Scalable Uncertainty Management_. Springer International Publishing, 2017, p. 307–318. ISBN: 9783319675824. DOI: [10.1007/978-3-319-67582-4_22](https://doi.org/10.1007%2F978-3-319-67582-4_22). URL: [http://dx.doi.org/10.1007/978-3-319-67582-4_22](http://dx.doi.org/10.1007/978-3-319-67582-4_22).

<a name=bib-Madrid_20241></a>[[9]](#cite-Madrid_20241) N. Madrid and M. Ojeda-Aciego. “Approaching the square of opposition in terms of the f-indexes of inclusion and contradiction”. In: _Fuzzy Sets and Systems_ 476 (Jan. 2024), p. 108769. ISSN: 0165-0114. DOI: [10.1016/j.fss.2023.108769](https://doi.org/10.1016%2Fj.fss.2023.108769). URL: [http://dx.doi.org/10.1016/j.fss.2023.108769](http://dx.doi.org/10.1016/j.fss.2023.108769).

<a name=bib-Madrid_2021></a>[[10]](#cite-Madrid_2021) N. Madrid and M. Ojeda-Aciego. “Approaching the Square of Oppositions in Terms of the f -indexes of Inclusion and Contradiction”. In: _Joint Proceedings of the 19th World Congress of the International Fuzzy Systems Association (IFSA), the 12th Conference of the European Society for Fuzzy Logic and Technology (EUSFLAT), and the 11th International Summer School on Aggregation Operators (AGOP)_. ifsa-eusflat-agop-21. Atlantis Press, 2021. DOI: [10.2991/asum.k.210827.055](https://doi.org/10.2991%2Fasum.k.210827.055). URL: [http://dx.doi.org/10.2991/asum.k.210827.055](http://dx.doi.org/10.2991/asum.k.210827.055).

<a name=bib-Madrid_20202></a>[[11]](#cite-Madrid_20202) N. Madrid and M. Ojeda-Aciego. “Functional degrees of inclusion and similarity between L-fuzzy sets”. In: _Fuzzy Sets and Systems_ 390 (Jul. 2020), p. 1–22. ISSN: 0165-0114. DOI: [10.1016/j.fss.2019.03.018](https://doi.org/10.1016%2Fj.fss.2019.03.018). URL: [http://dx.doi.org/10.1016/j.fss.2019.03.018](http://dx.doi.org/10.1016/j.fss.2019.03.018).

<a name=bib-Madrid_20201></a>[[12]](#cite-Madrid_20201) N. Madrid and M. Ojeda-Aciego. “On Contradiction and Inclusion Using Functional Degrees”. In: _International Journal of Computational Intelligence Systems_ 13.1 (2020), p. 464. ISSN: 1875-6883. DOI: [10.2991/ijcis.d.200409.001](https://doi.org/10.2991%2Fijcis.d.200409.001). URL: [http://dx.doi.org/10.2991/ijcis.d.200409.001](http://dx.doi.org/10.2991/ijcis.d.200409.001).

<a name=bib-Madrid_2022></a>[[13]](#cite-Madrid_2022) N. Madrid and M. Ojeda-Aciego. “Some Relationships Between the Notions of f-Inclusion and f-Contradiction”. In: _Computational Intelligence and Mathematics for Tackling Complex Problems 2_. Springer International Publishing, 2022, p. 175–181. ISBN: 9783030888176. DOI: [10.1007/978-3-030-88817-6_20](https://doi.org/10.1007%2F978-3-030-88817-6_20). URL: [http://dx.doi.org/10.1007/978-3-030-88817-6_20](http://dx.doi.org/10.1007/978-3-030-88817-6_20).

<a name=bib-Madrid_2023></a>[[14]](#cite-Madrid_2023) N. Madrid and M. Ojeda-Aciego. “The f-index of inclusion as optimal adjoint pair for fuzzy modus ponens”. In: _Fuzzy Sets and Systems_ 466 (Aug. 2023), p. 108474. ISSN: 0165-0114. DOI: [10.1016/j.fss.2023.01.009](https://doi.org/10.1016%2Fj.fss.2023.01.009). URL: [http://dx.doi.org/10.1016/j.fss.2023.01.009](http://dx.doi.org/10.1016/j.fss.2023.01.009).

<a name=bib-Madrid_2024></a>[[15]](#cite-Madrid_2024) N. Madrid and E. Ramírez-Poussa. “Analysis of the $$\varphi $$-Index of Inclusion Restricted to a Set of Indexes”. In: _Information Processing and Management of Uncertainty in Knowledge-Based Systems_. Springer Nature Switzerland, 2024, p. 3–11. ISBN: 9783031740039. DOI: [10.1007/978-3-031-74003-9_1](https://doi.org/10.1007%2F978-3-031-74003-9_1). URL: [http://dx.doi.org/10.1007/978-3-031-74003-9_1](http://dx.doi.org/10.1007/978-3-031-74003-9_1).

<a name=bib-Mendel_2015></a>[[16]](#cite-Mendel_2015) J. M. Mendel. “A comparison of three approaches for estimating (synthesizing) an interval type-2 fuzzy set model of a linguistic term for computing with words”. In: _Granular Computing_ 1.1 (Dec. 2015), p. 59–69. ISSN: 2364-4974. DOI: [10.1007/s41066-015-0009-7](https://doi.org/10.1007%2Fs41066-015-0009-7). URL: [http://dx.doi.org/10.1007/s41066-015-0009-7](http://dx.doi.org/10.1007/s41066-015-0009-7).

<a name=bib-Mendel_2017></a>[[17]](#cite-Mendel_2017) J. M. Mendel. “Type-2 Fuzzy Sets”. In: _Uncertain Rule-Based Fuzzy Systems_. Springer International Publishing, 2017, p. 259–306. ISBN: 9783319513706. DOI: [10.1007/978-3-319-51370-6_6](https://doi.org/10.1007%2F978-3-319-51370-6_6). URL: [http://dx.doi.org/10.1007/978-3-319-51370-6_6](http://dx.doi.org/10.1007/978-3-319-51370-6_6).

<a name=bib-Yang_2022></a>[[18]](#cite-Yang_2022) L. Yang and S. Zhang. “An Improved Fuzzy TOPSIS Based on Fuzzy Sets with Three Kinds of Negations”. In: _2022 34th Chinese Control and Decision Conference (CCDC)_. IEEE, Aug. 2022, p. 4847–4851. DOI: [10.1109/ccdc55256.2022.10034271](https://doi.org/10.1109%2Fccdc55256.2022.10034271). URL: [http://dx.doi.org/10.1109/ccdc55256.2022.10034271](http://dx.doi.org/10.1109/ccdc55256.2022.10034271).

<a name=bib-Zhang_2016></a>[[19]](#cite-Zhang_2016) S. Zhang and Y. Li. “A novel table look-up scheme based on GFScom and its application”. In: _Soft Computing_ 21.22 (Jun. 2016), p. 6767–6781. ISSN: 1433-7479. DOI: [10.1007/s00500-016-2226-7](https://doi.org/10.1007%2Fs00500-016-2226-7). URL: [http://dx.doi.org/10.1007/s00500-016-2226-7](http://dx.doi.org/10.1007/s00500-016-2226-7).

