---
title: Some Results About Fuzzy Consequence Operators and Fuzzy Preorders Using Conjunctors
author:
- <a href='/people/staff/cbejines/' style='color:rgb(100,0,50);'>Carlos Bejines</a>
- María Jesús Chasco
- Jorge Elorza
- Susana Montes
date: '2017'
categories: uncategorised
slug: 2017/ReFuCoOpFuPrUsCo
details: Aggregation Functions in Theory and in Practice, 9th International Summer
  School on Aggregation Functions, Sk{\"{o}}vde, Sweden, 19-22 June 2017 , Advances
  in Intelligent Systems and Computing vol. 581, pages 253--262.
doi: 10.1007/978-3-319-59306-7_26
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Bejines2017></a>[[Bej+17]](#cite-Bejines2017) C. Bejines, M. Chasco, J. Elorza, et al. “Some Results About Fuzzy Consequence Operators and Fuzzy Preorders Using Conjunctors”. In: _Aggregation Functions in Theory and in Practice, 9th International Summer School on Aggregation Functions, Skövde, Sweden, 19-22 June 2017_. Ed. by V. Torra, R. Mesiar and B. D. Baets. Vol. 581. Advances in Intelligent Systems and Computing. Springer, 2017, pp. 253-262. DOI: [10.1007/978-3-319-59306-7\_26](https://doi.org/10.1007%2F978-3-319-59306-7%5C_26). URL: [https://doi.org/10.1007/978-3-319-59306-7\_26](https://doi.org/10.1007/978-3-319-59306-7\_26).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Bejines2017,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Carlos Bejines and Mar\'\ia Jes{\a'u}s Chasco and Jorge Elorza and Susana Montes},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Aggregation Functions in Theory and in Practice, 9th International Summer School on Aggregation Functions, Sk{\"{o}}vde, Sweden, 19-22 June 2017},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Some Results About Fuzzy Consequence Operators and Fuzzy Preorders Using Conjunctors},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2017},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Vicen{\c c} Torra and Radko Mesiar and Bernard De Baets},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {253--262},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Advances in Intelligent Systems and Computing},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {581},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/agop/BejinesCEM17.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/978-3-319-59306-7\_26},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Tue, 07 May 2024 20:13:48 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/978-3-319-59306-7\_26},<br>}

:::








