---
title: Revisiting Reductants in the Multi-adjoint Logic Programming Framework
author:
- Pascual Julián Iranzo
- Jesús Medina
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '2014'
categories: uncategorised
slug: 2014/ReReLoPrFr
details: Logics in Artificial Intelligence - 14th European Conference, {JELIA} 2014,
  Funchal, Madeira, Portugal, September 24-26, 2014. Proceedings , Lecture Notes in
  Computer Science vol. 8761, pages 694--702.
doi: 10.1007/978-3-319-11558-0_53
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Iranzo2014></a>[[IMO14]](#cite-Iranzo2014) P. J. Iranzo, J. Medina, and M. Ojeda-Aciego. “Revisiting Reductants in the Multi-adjoint Logic Programming Framework”. In: _Logics in Artificial Intelligence - 14th European Conference, JELIA 2014, Funchal, Madeira, Portugal, September 24-26, 2014. Proceedings_. Ed. by E. Fermé and J. Leite. Vol. 8761. Lecture Notes in Computer Science. Springer, 2014, pp. 694-702. DOI: [10.1007/978-3-319-11558-0\_53](https://doi.org/10.1007%2F978-3-319-11558-0%5C_53). URL: [https://doi.org/10.1007/978-3-319-11558-0\_53](https://doi.org/10.1007/978-3-319-11558-0\_53).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Iranzo2014,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Pascual Juli{\a'a}n Iranzo and Jes{\a'u}s Medina and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Logics in Artificial Intelligence - 14th European Conference, {JELIA} 2014, Funchal, Madeira, Portugal, September 24-26, 2014. Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Revisiting Reductants in the Multi-adjoint Logic Programming Framework},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2014},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Eduardo Ferm{\a'e} and Jo~ao Leite},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {694--702},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {8761},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/jelia/Julian-IranzoMO14.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/978-3-319-11558-0\_53},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Thu, 07 Jan 2021 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/978-3-319-11558-0\_53},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/978-3-319-11558-0_53" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/978-3-319-11558-0_53" class="plumx-details" data-site="plum" data-hide-when-empty="true">Revisiting Reductants in the Multi-adjoint Logic Programming Framework</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1007/978-3-319-11558-0_53"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Juli_n_Iranzo_2017></a>[[1]](#cite-Juli_n_Iranzo_2017) P. Julián-Iranzo, J. Medina, and M. Ojeda-Aciego. “On reductants in the framework of multi-adjoint logic programming”. In: _Fuzzy Sets and Systems_ 317 (Jun. 2017), p. 27–43. ISSN: 0165-0114. DOI: [10.1016/j.fss.2016.09.004](https://doi.org/10.1016%2Fj.fss.2016.09.004). URL: [http://dx.doi.org/10.1016/j.fss.2016.09.004](http://dx.doi.org/10.1016/j.fss.2016.09.004).

