---
author:
- Dominik Dürrschnabel
- <a href='/people/staff/dominlopez/' style='color:rgb(100,0,50);'>Domingo López Rodríguez</a>
Status: Published
date: '2023-07-10'
slug: 2023/FoCoAn
title: Formal Concept Analysis
categories: Formal concept analysis
selected: yes
header_image: ~
details: 17th International Conference, ICFCA 2023, Kassel, Germany, July 17-21, 2023,
  Proceedings
doi: 10.1007/978-3-031-35949-1
project: ''
keywords: Formal concept analysis
---


# Abstract


The field of Formal Concept Analysis (FCA) originated in the 1980s in Darmstadt, Germany, as a subfield of mathematical order theory, building on earlier research and developments by other groups. The original motivation for FCA was to explore complete lattices as lattices of concepts, drawing inspiration from both Philosophy and Mathematics. Over time, FCA has evolved into a broad research area with applications far beyond its initial focus, including but not limited to logic, knowledge representation, unsupervised learning, data mining, human learning, and psychology.

This volume features the contributions accepted for the 17th International Conference on Formal Concept Analysis (ICFCA 2023), held during July 17 – 21, 2023, at University of Kassel, Germany. The International Conference on Formal Concept Analysis serves as a platform for researchers from FCA and related disciplines to showcase and exchange their research findings. Since its inaugural edition in 2003 in Darmstadt, Germany, ICFCA has been held annually in multiple locations across Europe, Africa, America, and Australia. In 2015, ICFCA became a biennial event to alternate with the Conference on Concept Lattices and Their Applications (CLA).

The previous edition, ICFCA 2021, organized by the *Université de Strasbourg* in France, was held online due to the COVID-19 pandemic. Now that conditions are beginning to return to the pre-pandemic situation, this edition will once again offer face-to-face opportunities as well as an online mode for the audience, making this the first hybrid ICFCA edition.

This year's ICFCA received 19 submissions from authors from ten countries. At least two different program committee members and one member of the editorial board reviewed each submission. Reviewing was done in a single-blinded fashion. Thirteen high-quality papers were selected for publication in this volume. This represents an acceptance rate of 67\%. 

The research part of this volume is divided into two distinct sections. First, in "Theory", we have collected papers that propose and review advances in theoretical aspects of FCA. The second section, "Applications and Visualization", consists of advances that deal with new algorithms, applications, and different approaches to visualization techniques.

In addition to the regular contributions, this volume also includes the abstracts of the six invited talks by outstanding researchers whom we were pleased to welcome to ICFCA 2023. In detail, we were pleased to host the following talks:

  - *How to Visualize Sets and Set Relations* by Oliver Deussen, Visual Computing, University of Konstanz, Germany
  - *Tangles: from Wittgenstein to graph minors and back* by Reinhard Diestel, Discrete Mathematics, University of Hamburg, Germany
  - *Formal Concept Analysis in Boolean Matrix Factorization: Algorithms and Extensions to Ordinal and Fuzzy-Valued Data* by Jan Konečný, Department of Computer Science, Palacký University Olomouc, Czech Republic
  - *On the $\varphi$-degree of inclusion* by Manuel Ojeda Aciego, Departmento de Matemática Aplicada, Universidad de Málaga, Spain 
  - *Logical foundations of categorization theory* by Alessandra Palmigiano, Department of Ethics, Governance and Society, Vrije Universiteit Amsterdam, Netherlands
  - *Modern Concepts of Dimension for Partially Ordered Sets* by William T. Trotter, School of Mathematics, Georgia Tech Institute, USA


Moreover, due to the recent computation of the ninth Dedekind number using techniques from FCA, this edition also includes a late-breaking result talk:

  - *Breaking the Barrier: A Computation of the Ninth Dedekind Number* by Christian Jäkel, Methods of Applied Algebra, Dresden University of Technology, Germany

We are deeply grateful to all the authors who submitted their papers to ICFCA 2023 as a venue to present their work. Our sincere appreciation goes to the members of the Editorial Board and Program Committee, as well as all the additional reviewers, whose timely and thorough reviews enabled the fruitful discussions of the high quality papers during the conference. We would also like to express our gratitude to the local organizers who were always quick to solve any problems that arose. We are very grateful to Springer for supporting the International Conference on Formal Concept Analysis and to the Department of Electrical Engineering and Computer Science and to the Research Center for Information System Design of the University of Kassel for hosting the event.












# Citation
Please, cite this work as:


<a name=bib-icfca2023></a>[[DL23]](#cite-icfca2023) D. Dürrschnabel and D. López-Rodríguez, ed. _Formal Concept Analysis - 17th International Conference, ICFCA 2023, Kassel, Germany, July 17-21, 2023, Proceedings_. Vol. 13934. Lecture Notes in Computer Science. Springer, 2023. ISBN: 978-3-031-35948-4. DOI: [10.1007/978-3-031-35949-1](https://doi.org/10.1007%2F978-3-031-35949-1).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@proceedings{icfca2023,<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor       = {Dominik D{\"{u}}rrschnabel and<br>&nbsp;&nbsp;&nbsp;&nbsp;                  Domingo L{\'{o}}pez{-}Rodríguez},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title        = {Formal Concept Analysis - 17th International Conference, {ICFCA} 2023,<br>&nbsp;&nbsp;&nbsp;&nbsp;                  Kassel, Germany, July 17-21, 2023, Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series       = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume       = {13934},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher    = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year         = {2023},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi          = {10.1007/978-3-031-35949-1},<br>&nbsp;&nbsp;&nbsp;&nbsp;  isbn         = {978-3-031-35948-4}<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/978-3-031-35949-1" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/978-3-031-35949-1" class="plumx-details" data-site="plum" data-hide-when-empty="true">Formal Concept Analysis</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1007/978-3-031-35949-1"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Anderson_2022></a>[[1]](#cite-Anderson_2022) M. W. R. Anderson and D. Millard. “Hypertext’s meta-history: Documenting in-conference citations, authors and keyword data, 1987-2021”. In: _Proceedings of the 33rd ACM Conference on Hypertext and Social Media_. HT ’22. ACM, Jun. 2022, p. 96–106. DOI: [10.1145/3511095.3531271](https://doi.org/10.1145%2F3511095.3531271). URL: [http://dx.doi.org/10.1145/3511095.3531271](http://dx.doi.org/10.1145/3511095.3531271).

<a name=bib-Belmouhcine_2014></a>[[2]](#cite-Belmouhcine_2014) A. Belmouhcine and M. Benkhalifa. “Hardware Implementation of Web Based Arabic Optical Character Recognition Units”. In: _Journal of Emerging Technologies in Web Intelligence_ 6.2 (May. 2014). ISSN: 1798-0461. DOI: [10.4304/jetwi.6.2.200-209](https://doi.org/10.4304%2Fjetwi.6.2.200-209). URL: [http://dx.doi.org/10.4304/jetwi.6.2.200-209](http://dx.doi.org/10.4304/jetwi.6.2.200-209).

<a name=bib-Fu_2013></a>[[3]](#cite-Fu_2013) Q. Fu, J. Lou, Q. Lin, et al. “Contextual analysis of program logs for understanding system behaviors”. In: _2013 10th Working Conference on Mining Software Repositories (MSR)_. IEEE, May. 2013. DOI: [10.1109/msr.2013.6624054](https://doi.org/10.1109%2Fmsr.2013.6624054). URL: [http://dx.doi.org/10.1109/msr.2013.6624054](http://dx.doi.org/10.1109/msr.2013.6624054).

<a name=bib-Li_2015></a>[[4]](#cite-Li_2015) X. Li and G. Li. “An Optimal Ontology Selecting Method”. In: _2015 International Conference on Network and Information Systems for Computers_. IEEE, Jan. 2015, p. 381–384. DOI: [10.1109/icnisc.2015.8](https://doi.org/10.1109%2Ficnisc.2015.8). URL: [http://dx.doi.org/10.1109/icnisc.2015.8](http://dx.doi.org/10.1109/icnisc.2015.8).


