---
title: 'Conference paper accepted: <em>Robust nonparametric probability density estimation
  by soft clustering</em>'
author: E. López-Rubio, J.M. Ortiz-De-Lazcano-Lobato, Domingo López-Rodríguez, M.
  Del Carmen Vargas-Gonzalez
date: '2008-01-01'
categories: Neural networks
---

The work <u>Robust nonparametric probability density estimation by soft clustering</u> has been published in <em>Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics), (5163 LNCS), PART 1, <em>pp. 155-164</em></em>.

<u>Abstract</u>:



A method to estimate the probability density function of multivariate distributions is presented. The classical Parzen window approach builds a spherical Gaussian density around every input sample. This choice of the kernel density yields poor robustness for real input datasets. We use multivariate Student-t distributions in order to improve the adaptation capability of the model. Our method has a first stage where hard neighbourhoods are determined for every sample. Then soft clusters are considered to merge the information coming from several hard neighbourhoods. Hence, a specific mixture component is learned for each soft cluster. This leads to outperform other proposals where the local kernel is not as robust and/or there are no smoothing strategies, like the manifold Parzen windows. © Springer-Verlag Berlin Heidelberg 2008.




For more details on this work, visit <a href='/publications/conferences/2008-icann2'>its own page</a>.
