---
title: Increasing the Efficiency of Minimal Key Enumeration Methods by Means of Parallelism
author:
- Fernando Benito Picazo
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/enciso/' style='color:rgb(100,0,50);'>Manuel Enciso</a>
- <a href='/people/staff/amora/' style='color:rgb(100,0,50);'>Ángel Mora</a>
date: '2014'
categories: uncategorised
slug: 2014/InEfMiKeEnMeMePa
details: '{ICSOFT-EA} 2014 - Proceedings of the 9th International Conference on Software
  Engineering and Applications, Vienna, Austria, 29-31 August, 2014 , pages 512--517.'
doi: 10.5220/0005108205120517
---



# Abstract


Finding all minimal keys in a table is a hard problem but also provides a lot of benefits in database design and optimization. Some of the methods proposed in the literature are based on logic and, more specifically on tableaux paradigm. The size of the problems such methods deal with is strongly limited, which implies that they cannot be applied to big database schemas. We have carried out an experimental analysis to compare the results obtained by these methods in order to estimate their limits. Although tableaux paradigm may be viewed as a search space guiding the key finding task, none of the previous algorithms have incorporated parallelism. In this work, we have developed two different versions of the algorithms, a sequential and a parallel one, stating clearly how parallelism could naturally be integrated and the benefits we get over efficiency. This work has also guided future work guidelines to improve future designs of these methods.








# Citation
Please, cite this work as:


<a name=bib-Picazo2014></a>[[Pic+14]](#cite-Picazo2014) F. B. Picazo, P. Cordero, M. Enciso, et al. “Increasing the Efficiency of Minimal Key Enumeration Methods by Means of Parallelism”. In: _ICSOFT-EA 2014 - Proceedings of the 9th International Conference on Software Engineering and Applications, Vienna, Austria, 29-31 August, 2014_. Ed. by A. Holzinger, T. Libourel, L. A. Maciaszek and S. J. Mellor. SciTePress, 2014, pp. 512-517. DOI: [10.5220/0005108205120517](https://doi.org/10.5220%2F0005108205120517). URL: [https://doi.org/10.5220/0005108205120517](https://doi.org/10.5220/0005108205120517).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Picazo2014,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Fernando Benito Picazo and Pablo Cordero and Manuel Enciso and {\a'A}ngel Mora},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {{ICSOFT-EA} 2014 - Proceedings of the 9th International Conference on Software Engineering and Applications, Vienna, Austria, 29-31 August, 2014},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Increasing the Efficiency of Minimal Key Enumeration Methods by Means of Parallelism},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2014},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Andreas Holzinger and Th{\a'e}r{\a`e}se Libourel and Leszek A. Maciaszek and Stephen J. Mellor},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {512--517},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {SciTePress},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/icsoft/PicazoCEM14.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.5220/0005108205120517},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 23 Sep 2022 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.5220/0005108205120517},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.5220/0005108205120517" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.5220/0005108205120517" class="plumx-details" data-site="plum" data-hide-when-empty="true">Increasing the Efficiency of Minimal Key Enumeration Methods by Means of Parallelism</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.5220/0005108205120517"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Benito_Picazo_2016></a>[[1]](#cite-Benito_Picazo_2016) F. Benito-Picazo, P. Cordero, M. Enciso, et al. “Reducing the search space by closure and simplification paradigms: A parallel key finding method”. In: _The Journal of Supercomputing_ 73.1 (Jan. 2016), p. 75–87. ISSN: 1573-0484. DOI: [10.1007/s11227-016-1622-1](https://doi.org/10.1007%2Fs11227-016-1622-1). URL: [http://dx.doi.org/10.1007/s11227-016-1622-1](http://dx.doi.org/10.1007/s11227-016-1622-1).

