---
title: A {PDL} Approach for Qualitative Velocity
author:
- Alfredo Burrieza
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '2011'
categories: uncategorised
slug: 2011/ApQuVe
details: Int. J. Uncertain. Fuzziness Knowl. Based Syst. vol. 19 (1), pages 11--26.
doi: 10.1142/S021848851100685X
---



# Abstract


We introduce the syntax, semantics, and an axiom system for a PDL-based extension of the logic for order of magnitude qualitative reasoning, developed in order to deal with the concept of qualitative velocity, which together with qualitative distance and orientation, are important notions in order to represent spatial reasoning for moving objects, such as robots. The main advantages of using a PDL-based approach are, on the one hand, all the well-known advantages of using logic in AI, and, on the other hand, the possibility of constructing complex relations from simpler ones, the flexibility for using different levels of granularity, its possible extension by adding other spatial components, and the use of a language close to programming languages.








# Citation
Please, cite this work as:


<a name=bib-Burrieza2011></a>[[BMO11]](#cite-Burrieza2011) A. Burrieza, E. Mu~noz-Velasco, and M. Ojeda-Aciego. “A PDL Approach for Qualitative Velocity”. In: _Int. J. Uncertain. Fuzziness Knowl. Based Syst._ 19.1 (2011), pp. 11-26. DOI: [10.1142/S021848851100685X](https://doi.org/10.1142%2FS021848851100685X). URL: [https://doi.org/10.1142/S021848851100685X](https://doi.org/10.1142/S021848851100685X).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{Burrieza2011,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Alfredo Burrieza and Emilio Mu~noz-Velasco and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Int. J. Uncertain. Fuzziness Knowl. Based Syst.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {A {PDL} Approach for Qualitative Velocity},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2011},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number = {1},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {11--26},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {19},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/ijufks/BurriezaMO11.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1142/S021848851100685X},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Thu, 18 Jun 2020 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1142/S021848851100685X},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1142/S021848851100685X" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1142/S021848851100685X" class="plumx-details" data-site="plum" data-hide-when-empty="true">A {PDL} Approach for Qualitative Velocity</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1142/S021848851100685X"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Burrieza_2016></a>[[1]](#cite-Burrieza_2016) A. Burrieza, E. Muñoz-Velasco, and M. Ojeda-Aciego. “A Hybrid Approach to Closeness in the Framework of Order of Magnitude Qualitative Reasoning”. In: _Hybrid Artificial Intelligent Systems_. Springer International Publishing, 2016, p. 721–729. ISBN: 9783319320342. DOI: [10.1007/978-3-319-32034-2_60](https://doi.org/10.1007%2F978-3-319-32034-2_60). URL: [http://dx.doi.org/10.1007/978-3-319-32034-2_60](http://dx.doi.org/10.1007/978-3-319-32034-2_60).

<a name=bib-Burrieza_2018></a>[[2]](#cite-Burrieza_2018) A. Burrieza, E. Muñoz-Velasco, and M. Ojeda-Aciego. “Logics for Order-of-Magnitude Qualitative Reasoning: Formalizing Negligibility”. In: _Ewa Orłowska on Relational Methods in Logic and Computer Science_. Springer International Publishing, 2018, p. 203–231. ISBN: 9783319978796. DOI: [10.1007/978-3-319-97879-6_8](https://doi.org/10.1007%2F978-3-319-97879-6_8). URL: [http://dx.doi.org/10.1007/978-3-319-97879-6_8](http://dx.doi.org/10.1007/978-3-319-97879-6_8).

<a name=bib-Cohen_Solal_2020></a>[[3]](#cite-Cohen_Solal_2020) Q. Cohen-Solal. “Tractable Fragments of Temporal Sequences of Topological Information”. In: _Principles and Practice of Constraint Programming_. Springer International Publishing, 2020, p. 107–125. ISBN: 9783030584757. DOI: [10.1007/978-3-030-58475-7_7](https://doi.org/10.1007%2F978-3-030-58475-7_7). URL: [http://dx.doi.org/10.1007/978-3-030-58475-7_7](http://dx.doi.org/10.1007/978-3-030-58475-7_7).

<a name=bib-Goli_ska_Pilarek_2015></a>[[4]](#cite-Goli_ska_Pilarek_2015) J. Goli ska-Pilarek and E. Munoz-Velasco. “A hybrid qualitative approach for relative movements”. In: _Logic Journal of IGPL_ 23.3 (Apr. 2015), p. 410–420. ISSN: 1368-9894. DOI: [10.1093/jigpal/jzv012](https://doi.org/10.1093%2Fjigpal%2Fjzv012). URL: [http://dx.doi.org/10.1093/jigpal/jzv012](http://dx.doi.org/10.1093/jigpal/jzv012).

<a name=bib-Goli_ska_Pilarek_2012></a>[[5]](#cite-Goli_ska_Pilarek_2012) J. Golińska-Pilarek and E. Muñoz-Velasco. “Reasoning with Qualitative Velocity: Towards a Hybrid Approach”. In: _Hybrid Artificial Intelligent Systems_. Springer Berlin Heidelberg, 2012, p. 635–646. ISBN: 9783642289422. DOI: [10.1007/978-3-642-28942-2_57](https://doi.org/10.1007%2F978-3-642-28942-2_57). URL: [http://dx.doi.org/10.1007/978-3-642-28942-2_57](http://dx.doi.org/10.1007/978-3-642-28942-2_57).

<a name=bib-Mu_oz_Velasco_2014></a>[[6]](#cite-Mu_oz_Velasco_2014) E. Muñoz-Velasco, A. Burrieza, and M. Ojeda-Aciego. “A logic framework for reasoning with movement based on fuzzy qualitative representation”. In: _Fuzzy Sets and Systems_ 242 (May. 2014), p. 114–131. ISSN: 0165-0114. DOI: [10.1016/j.fss.2013.07.014](https://doi.org/10.1016%2Fj.fss.2013.07.014). URL: [http://dx.doi.org/10.1016/j.fss.2013.07.014](http://dx.doi.org/10.1016/j.fss.2013.07.014).

<a name=bib-Sioutis_2014></a>[[7]](#cite-Sioutis_2014) M. Sioutis, J. Condotta, Y. Salhi, et al. “A Qualitative Spatio-Temporal Framework Based on Point Algebra”. In: _Artificial Intelligence: Methodology, Systems, and Applications_. Springer International Publishing, 2014, p. 117–128. ISBN: 9783319105543. DOI: [10.1007/978-3-319-10554-3_11](https://doi.org/10.1007%2F978-3-319-10554-3_11). URL: [http://dx.doi.org/10.1007/978-3-319-10554-3_11](http://dx.doi.org/10.1007/978-3-319-10554-3_11).

<a name=bib-httpsdoiorg1048550arxiv13077405></a>[[8]](#cite-httpsdoiorg1048550arxiv13077405) P. A. Wałȩga. _Reasoning for Moving Blocks Problem: Formal Representation and Implementation_. 2013. DOI: [10.48550/ARXIV.1307.7405](https://doi.org/10.48550%2FARXIV.1307.7405). URL: [https://arxiv.org/abs/1307.7405](https://arxiv.org/abs/1307.7405).

