---
title: Fuzzy closure relations
type: journals
author:
- <a href='/people/staff/manuojeda/' style='color:rgb(100,0,50);'>Manuel Ojeda Hernández</a>
- <a href='/people/staff/ipcabrera/' style='color:rgb(100,0,50);'>Inma P. Cabrera</a>
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
date: '2022-01-01'
categories:
- Formal concept analysis
- Fuzzy logic
- Fuzzy sets
- Uncertainty
doi: 10.1016/j.fss.2022.05.016
slug: 2022/FuClRe
keywords: ''
project: 2019-flair
details: Fuzzy Sets and Systems vol. 450 , pages 118 -- 132.
listing:
- id: funding
  contents: funding.yml
  type: default
  sort: date desc
---




# Abstract

The concept of closure operator is key in several branches of mathematics. In this paper, closure operators are extended to relational structures, more specifically to fuzzy relations in the framework of complete fuzzy lattices. The core of the work is the search for a suitable definition of (strong) fuzzy closure relation, that is, a fuzzy relation whose relation with fuzzy closure systems is one-to-one. The study of the properties of fuzzy closure systems and fuzzy relations helps narrow down this exploration until an appropriate definition is settled.


# Funding
::: {.callout-note appearance='minimal' collapse=false}
## Projects funding this work

:::{#funding}
:::
:::








# Citation
Please, cite this work as:


<a name=bib-Ojeda-Hernandez2022118></a>[[Oje+22]](#cite-Ojeda-Hernandez2022118) M. Ojeda-Hernandez, I. P. Cabrera, P. Cordero, et al. “Fuzzy closure relations”. In: _Fuzzy Sets and Systems_ 450 (2022). Cited by: 3; All Open Access, Green Open Access, Hybrid Gold Open Access, pp. 118 - 132. DOI: [10.1016/j.fss.2022.05.016](https://doi.org/10.1016%2Fj.fss.2022.05.016). URL: [https://www.scopus.com/inward/record.uri?eid=2-s2.0-85131416314&doi=10.1016

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@article{Ojeda-Hernandez2022118,<br>&nbsp;&nbsp;&nbsp;&nbsp;	Author = {Ojeda-Hernandez, Manuel and Cabrera, Inma P. and Cordero, Pablo and Mu{\~n}oz-Velasco, Emilio},<br>&nbsp;&nbsp;&nbsp;&nbsp;	Doi = {10.1016/j.fss.2022.05.016},<br>&nbsp;&nbsp;&nbsp;&nbsp;	Journal = {Fuzzy Sets and Systems},<br>&nbsp;&nbsp;&nbsp;&nbsp;	Note = {Cited by: 3; All Open Access, Green Open Access, Hybrid Gold Open Access},<br>&nbsp;&nbsp;&nbsp;&nbsp;	Pages = {118 -- 132},<br>&nbsp;&nbsp;&nbsp;&nbsp;	Publication_Stage = {Final},<br>&nbsp;&nbsp;&nbsp;&nbsp;	Source = {Scopus},<br>&nbsp;&nbsp;&nbsp;&nbsp;	Title = {Fuzzy closure relations},<br>&nbsp;&nbsp;&nbsp;&nbsp;	Type = {Article},<br>&nbsp;&nbsp;&nbsp;&nbsp;	Url = {https://www.scopus.com/inward/record.uri?eid=2-s2.0-85131416314&doi=10.1016%2fj.fss.2022.05.016&partnerID=40&md5=62334dfb2251d49373dcb9c0d75693d5},<br>&nbsp;&nbsp;&nbsp;&nbsp;	Volume = {450},<br>&nbsp;&nbsp;&nbsp;&nbsp;	Year = {2022},<br>&nbsp;&nbsp;&nbsp;&nbsp;	Bdsk-Url-1 = {https://www.scopus.com/inward/record.uri?eid=2-s2.0-85131416314&doi=10.1016%2fj.fss.2022.05.016&partnerID=40&md5=62334dfb2251d49373dcb9c0d75693d5},<br>&nbsp;&nbsp;&nbsp;&nbsp;	Bdsk-Url-2 = {http://dx.doi.org/10.1016/j.fss.2022.05.016}<br>}

:::



# Bibliometric data

## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Nesibe_Kesicio_lu_2024></a>[[1]](#cite-Nesibe_Kesicio_lu_2024) M. Nesibe Kesicioğlu and E. Kürkçü Çakar. “Closure operators constructed by logical operations on bounded lattices”. In: _Fuzzy Sets and Systems_ 484 (May. 2024), p. 108945. ISSN: 0165-0114. DOI: [10.1016/j.fss.2024.108945](https://doi.org/10.1016%2Fj.fss.2024.108945). URL: [http://dx.doi.org/10.1016/j.fss.2024.108945](http://dx.doi.org/10.1016/j.fss.2024.108945).

<a name=bib-Ojeda_Hern_ndez_20231></a>[[2]](#cite-Ojeda_Hern_ndez_20231) M. Ojeda-Hernández, I. P. Cabrera, P. Cordero, et al. “Fuzzy closure structures as formal concepts”. In: _Fuzzy Sets and Systems_ 463 (Jul. 2023), p. 108458. ISSN: 0165-0114. DOI: [10.1016/j.fss.2022.12.014](https://doi.org/10.1016%2Fj.fss.2022.12.014). URL: [http://dx.doi.org/10.1016/j.fss.2022.12.014](http://dx.doi.org/10.1016/j.fss.2022.12.014).

<a name=bib-Ojeda_Hern_ndez_2023></a>[[3]](#cite-Ojeda_Hern_ndez_2023) M. Ojeda-Hernández, I. P. Cabrera, P. Cordero, et al. “On the Commutative Diagrams Among Galois Connections Involved in Closure Structures”. In: _Formal Concept Analysis_. Springer Nature Switzerland, 2023, p. 49–63. ISBN: 9783031359491. DOI: [10.1007/978-3-031-35949-1_4](https://doi.org/10.1007%2F978-3-031-35949-1_4). URL: [http://dx.doi.org/10.1007/978-3-031-35949-1_4](http://dx.doi.org/10.1007/978-3-031-35949-1_4).


