---
author: S. Merino Córdoba, J. Martínez Del Castillo, G. Gutiérrez Barranco, A. Mora-Bonilla,
  Domingo López-Rodríguez, E. Mérida-Casermeiro
Status: Published
date: '2008-01-01'
slug: 2008/FeJoFu
title: 'Fnova: Fermat and joomla fusion'
categories: E-learning
header_image: ~
details: Proceedings of the IASTED International Conference on Internet and Multimedia
  Systems and Applications and Visual Communications, <em>pp. 15-20</em>
link: 2008-euroimsa/paper.pdf
project: ''
keywords: Applied mathematics, Bologna declarations, Class notes, Classical models,
  Discrete mathematics, Educational environments, ESHE, Higher educations, Joomla!,
  Mathematics, Moodle, Multi-media technologies, New tools, On-line resources, Practical
  problems, Telecommunication engineerings, Vectorial analysis, Web sites, Algebra,
  Communication, Differentiation (calculus), E-learning, Education computing, Image
  communication systems, Internet, Motion compensation, Numerical methods, Students,
  Teaching, Visual communication, World Wide Web, Multimedia systems
---


# Abstract


We present a work developed by a group of teachers in the Department of Applied Mathematics at the University of Malaga. Since 2002, FERMAT Project has  become an important meeting point between teachers and students for the subjects  of Numerical Methods, Algebra, Calculus, Vectorial Analysis, Differential Equations  and Discrete Mathematics in the degree of Telecommunication Engineering. Our main  goal was the development of an educational environment complementary to the classical  model of teaching, in order to get a gradual adaptation to the European Space for  Higher Education (ESHE) according to Bologna Declaration. Our method consists on  theoretical lessons using multimedia technologies and also practical sessions in  the laboratories. In these sessions the students solve practical problems with the  aid of the computer. On the other hand, we offer access to the resources in our  website (class notes, proposed and solved problems...), an also to on-line resources:  mail, forum, chat, videoconference... In a first step we create FERMAT website including  some resources that can be useful for students. The suggestions of these students  have been helpful for the development of the last version, named FNOVA. Thanks  to these suggestions we have introduced important improvements in this version of our new tool. These are those that we present in this paper.












# Citation
Please, cite this work as:


<a name=bib-Cordoba2008></a>[[Cór+08]](#cite-Cordoba2008) S. Córdoba, J. Del Castillo, G. Barranco, et al. “Fnova: Fermat and joomla fusion”. In: _Proceedings of the IASTED International Conference on Internet and Multimedia Systems and Applications and Visual Communications_. cited By 0; Conference of IASTED International Conference on Internet and Multimedia Systems and Applications and Visual Communications ; Conference Date: 17 March 2008 Through 18 March 2008; Conference Code:75520. Innsbruck, 2008, pp. 15-20. URL: [https://www.scopus.com/inward/record.uri?eid=2-s2.0-62649128925&partnerID=40&md5=b408a2435f4dd334f12eacb6e63a8b50](https://www.scopus.com/inward/record.uri?eid=2-s2.0-62649128925&partnerID=40&md5=b408a2435f4dd334f12eacb6e63a8b50).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Cordoba2008,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {S.M. Córdoba and J.M. {Del Castillo} and G.G. Barranco and A. Mora-Bonilla and D. López-Rodríguez and E. Mérida-Casermeiro},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Proceedings of the IASTED International Conference on Internet and Multimedia Systems and Applications and Visual Communications},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Fnova: Fermat and joomla fusion},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2008},<br>&nbsp;&nbsp;&nbsp;&nbsp;  address = {Innsbruck},<br>&nbsp;&nbsp;&nbsp;&nbsp;  note = {cited By 0; Conference of IASTED International Conference on Internet and Multimedia Systems and Applications and Visual Communications ; Conference Date: 17 March 2008 Through 18 March 2008; Conference Code:75520},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {15-20},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {We present a work developed by a group of teachers in the Department of Applied Mathematics at the University of Malaga. Since 2002, FERMAT1 Project has become an important meeting point between teachers and students for the subjects of Numerical Methods, Algebra, Calculus, Vectorial Analysis, Differential Equations and Discrete Mathematics in the degree of Telecommunication Engineering. Our main goal was the development of an educational environment complementary to the classical model of teaching, in order to get a gradual adaptation to the European Space for Higher Education (ESHE) according to Bologna Declaration. Our method consists on theoretical lessons using multimedia technologies and also practical sessions in the laboratories. In these sessions the students solve practical problems with the aid of the computer. On the other hand, we offer access to the resources in our website (class notes, proposed and solved problems...), an also to on-line resources: mail, forum, chat, videoconference... In a first step we create FERMAT website including some resources that can be useful for students. The suggestions of these students have been helpful for the development of the last version, named FNOVA2. Thanks to these suggestions we have introduced important improvements in this version of our new tool3. These are those that we present in this paper.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  author_keywords = {E-learning; ESHE; Joomla!; Mathematics; Moodle},<br>&nbsp;&nbsp;&nbsp;&nbsp;  document_type = {Conference Paper},<br>&nbsp;&nbsp;&nbsp;&nbsp;  keywords = {Applied mathematics; Bologna declarations; Class notes; Classical models; Discrete mathematics; Educational environments; ESHE; Higher educations; Joomla!; Mathematics; Moodle; Multi-media technologies; New tools; On-line resources; Practical problems; Telecommunication engineerings; Vectorial analysis; Web sites, Algebra; Communication; Differentiation (calculus); E-learning; Education computing; Image communication systems; Internet; Motion compensation; Numerical methods; Students; Teaching; Visual communication; World Wide Web, Multimedia systems},<br>&nbsp;&nbsp;&nbsp;&nbsp;  source = {Scopus},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://www.scopus.com/inward/record.uri?eid=2-s2.0-62649128925&partnerID=40&md5=b408a2435f4dd334f12eacb6e63a8b50},<br>}

:::









