---
title: On the Expressive Power of Sub-Propositional Fragments of Modal Logic
author:
- Davide Bresolin
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
- Guido Sciavicco
date: '2016'
categories: uncategorised
slug: 2016/ExPoFrMoLo
details: Proceedings of the Seventh International Symposium on Games, Automata, Logics
  and Formal Verification, GandALF 2016, Catania, Italy, 14-16 September 2016 , {EPTCS}
  vol. 226, pages 91--104.
doi: 10.4204/EPTCS.226.7
---



# Abstract


Modal logic is a paradigm for several useful and applicable formal systems in computer science. It generally retains the low complexity of classical propositional logic, but notable exceptions exist in the domains of description, temporal, and spatial logic, where the most expressive formalisms have a very high complexity or are even undecidable. In search of computationally well-behaved fragments, clausal forms and other sub-propositional restrictions of temporal and description logics have been recently studied. This renewed interest on sub-propositional logics, which mainly focus on the complexity of the various fragments, raise natural questions on their the relative expressive power, which we try to answer here for the basic multi-modal logic Kn. We consider the Horn and the Krom restrictions, as well as the combined restriction (known as the core fragment) of modal logic, and, orthogonally, the fragments that emerge by disallowing boxes or diamonds from positive literals. We study the problem in a very general setting, to ease transferring our results to other meaningful cases.








# Citation
Please, cite this work as:


<a name=bib-Bresolin2016a></a>[[BMS16]](#cite-Bresolin2016a) D. Bresolin, E. Mu~noz-Velasco, and G. Sciavicco. “On the Expressive Power of Sub-Propositional Fragments of Modal Logic”. In: _Proceedings of the Seventh International Symposium on Games, Automata, Logics and Formal Verification, GandALF 2016, Catania, Italy, 14-16 September 2016_. Ed. by D. Cantone and G. Delzanno. Vol. 226. EPTCS. 2016, pp. 91-104. DOI: [10.4204/EPTCS.226.7](https://doi.org/10.4204%2FEPTCS.226.7). URL: [https://doi.org/10.4204/EPTCS.226.7](https://doi.org/10.4204/EPTCS.226.7).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Bresolin2016a,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Davide Bresolin and Emilio Mu~noz-Velasco and Guido Sciavicco},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Proceedings of the Seventh International Symposium on Games, Automata, Logics and Formal Verification, GandALF 2016, Catania, Italy, 14-16 September 2016},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {On the Expressive Power of Sub-Propositional Fragments of Modal Logic},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2016},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Domenico Cantone and Giorgio Delzanno},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {91--104},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {{EPTCS}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {226},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/corr/BresolinMS16.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.4204/EPTCS.226.7},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Wed, 07 Dec 2022 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.4204/EPTCS.226.7},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.4204/EPTCS.226.7" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.4204/EPTCS.226.7" class="plumx-details" data-site="plum" data-hide-when-empty="true">On the Expressive Power of Sub-Propositional Fragments of Modal Logic</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.4204/EPTCS.226.7"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Jung_2019></a>[[1]](#cite-Jung_2019) J. C. Jung, F. Papacchini, F. Wolter, et al. “Model Comparison Games for Horn Description Logics”. In: _2019 34th Annual ACM/IEEE Symposium on Logic in Computer Science (LICS)_. IEEE, Jun. 2019, p. 1–14. DOI: [10.1109/lics.2019.8785658](https://doi.org/10.1109%2Flics.2019.8785658). URL: [http://dx.doi.org/10.1109/lics.2019.8785658](http://dx.doi.org/10.1109/lics.2019.8785658).

