---
title: Measures of inclusion and entropy based on the \emph{{\(\varphi\)}}-index of
  inclusion
author:
- Nicolás Madrid
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '2021'
categories: uncategorised
slug: 2021/MeInEnBaIn
details: Fuzzy Sets Syst. vol. 423 , pages 29--54.
doi: 10.1016/J.FSS.2021.01.011
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Madrid2021a></a>[[MO21]](#cite-Madrid2021a) N. Madrid and M. Ojeda-Aciego. “Measures of inclusion and entropy based on the _\(\varphi\)_-index of inclusion”. In: _Fuzzy Sets Syst._ 423 (2021), pp. 29-54. DOI: [10.1016/J.FSS.2021.01.011](https://doi.org/10.1016%2FJ.FSS.2021.01.011). URL: [https://doi.org/10.1016/j.fss.2021.01.011](https://doi.org/10.1016/j.fss.2021.01.011).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{Madrid2021a,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Nicol{\a'a}s Madrid and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Fuzzy Sets Syst.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Measures of inclusion and entropy based on the \emph{{\(\varphi\)}}-index of inclusion},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2021},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {29--54},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {423},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/fss/MadridO21a.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1016/J.FSS.2021.01.011},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Mon, 03 Jan 2022 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1016/j.fss.2021.01.011},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1016/J.FSS.2021.01.011" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1016/J.FSS.2021.01.011" class="plumx-details" data-site="plum" data-hide-when-empty="true">Measures of inclusion and entropy based on the \emph{{\(\varphi\)}}-index of inclusion</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1016/J.FSS.2021.01.011"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Dombi_2025></a>[[1]](#cite-Dombi_2025) J. Dombi and T. Jónás. “Approximate reasoning based on the preference implication”. In: _Fuzzy Sets and Systems_ 499 (Jan. 2025), p. 109187. ISSN: 0165-0114. DOI: [10.1016/j.fss.2024.109187](https://doi.org/10.1016%2Fj.fss.2024.109187). URL: [http://dx.doi.org/10.1016/j.fss.2024.109187](http://dx.doi.org/10.1016/j.fss.2024.109187).

<a name=bib-Magdalena_2024></a>[[2]](#cite-Magdalena_2024) L. Magdalena, C. Torres-Blanc, S. Cubillo, et al. “Different Types of Entropy Measures for Type-2 Fuzzy Sets”. In: _Axioms_ 13.8 (Aug. 2024), p. 556. ISSN: 2075-1680. DOI: [10.3390/axioms13080556](https://doi.org/10.3390%2Faxioms13080556). URL: [http://dx.doi.org/10.3390/axioms13080556](http://dx.doi.org/10.3390/axioms13080556).

<a name=bib-Torres_Blanc_2023></a>[[3]](#cite-Torres_Blanc_2023) C. Torres-Blanc, S. Cubillo, L. Magdalena, et al. “Antonyms of predicates on n-tuples of fuzzy sets. A characterization of involutions on [0,1]”. In: _Fuzzy Sets and Systems_ 463 (Jul. 2023), p. 108420. ISSN: 0165-0114. DOI: [10.1016/j.fss.2022.10.012](https://doi.org/10.1016%2Fj.fss.2022.10.012). URL: [http://dx.doi.org/10.1016/j.fss.2022.10.012](http://dx.doi.org/10.1016/j.fss.2022.10.012).

<a name=bib-Torres_Blanc_2025></a>[[4]](#cite-Torres_Blanc_2025) C. Torres-Blanc, J. Martinez-Mateo, S. Cubillo, et al. “Subsethood measures based on cardinality of type-2 fuzzy sets”. In: _Fuzzy Sets and Systems_ 499 (Jan. 2025), p. 109174. ISSN: 0165-0114. DOI: [10.1016/j.fss.2024.109174](https://doi.org/10.1016%2Fj.fss.2024.109174). URL: [http://dx.doi.org/10.1016/j.fss.2024.109174](http://dx.doi.org/10.1016/j.fss.2024.109174).

