---
title: Fuzzy closure structures as formal concepts II
type: journals
author:
- <a href='/people/staff/manuojeda/' style='color:rgb(100,0,50);'>Manuel Ojeda Hernández</a>
- <a href='/people/staff/ipcabrera/' style='color:rgb(100,0,50);'>Inma P. Cabrera</a>
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
date: '2023-01-01'
categories:
- Formal concept analysis
- Fuzzy logic
- Fuzzy sets
- Uncertainty
doi: 10.1016/j.fss.2023.108734
slug: 2023/FuClStFoCoIi
keywords: ''
project: 2019-flair
details: 'Fuzzy Sets Syst. 473: 108734'
listing:
- id: funding
  contents: funding.yml
  type: default
  sort: date desc
---




# Abstract

This paper is the natural extension of Fuzzy Closure Structures as Formal Concepts. In this paper we take into consideration the concept of closure system which is not dealt with in the previous one. Hence, a connection must be found between fuzzy ordered sets and a crisp ordered set. This problem is two-fold, the core of the fuzzy orders can be considered in order to complete the ensemble, or the crisp order can be fuzzified. Both ways are studied in the paper. The most interesting result is, similarly to the previous paper, that closure systems are formal concepts of these Galois connections as well.


# Funding
::: {.callout-note appearance='minimal' collapse=false}
## Projects funding this work

:::{#funding}
:::
:::








# Citation
Please, cite this work as:


<a name=bib-Ojeda-Hernandez2023></a>[[Her+23]](#cite-Ojeda-Hernandez2023) M. Hernández, I. P. Cabrera, P. Cordero, et al. “Fuzzy closure structures as formal concepts II”. In: _Fuzzy Sets and Systems_ 473 (2023). Cited by: 2; All Open Access, Green Open Access, Hybrid Gold Open Access. DOI: [10.1016/j.fss.2023.108734](https://doi.org/10.1016%2Fj.fss.2023.108734). URL: [https://www.scopus.com/inward/record.uri?eid=2-s2.0-85173012491&doi=10.1016

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@article{Ojeda-Hernandez2023,<br>&nbsp;&nbsp;&nbsp;&nbsp;	Author = {Hern\'andez, Manuel and Cabrera, Inma P. and Cordero, Pablo and Mu{\~n}oz-Velasco, Emilio},<br>&nbsp;&nbsp;&nbsp;&nbsp;	Doi = {10.1016/j.fss.2023.108734},<br>&nbsp;&nbsp;&nbsp;&nbsp;	Journal = {Fuzzy Sets and Systems},<br>&nbsp;&nbsp;&nbsp;&nbsp;	Note = {Cited by: 2; All Open Access, Green Open Access, Hybrid Gold Open Access},<br>&nbsp;&nbsp;&nbsp;&nbsp;	Publication_Stage = {Final},<br>&nbsp;&nbsp;&nbsp;&nbsp;	Source = {Scopus},<br>&nbsp;&nbsp;&nbsp;&nbsp;	Title = {Fuzzy closure structures as formal concepts II},<br>&nbsp;&nbsp;&nbsp;&nbsp;	Type = {Article},<br>&nbsp;&nbsp;&nbsp;&nbsp;	Url = {https://www.scopus.com/inward/record.uri?eid=2-s2.0-85173012491&doi=10.1016%2fj.fss.2023.108734&partnerID=40&md5=fc32c575cc11bc26c7969e3f76c6ed3c},<br>&nbsp;&nbsp;&nbsp;&nbsp;	Volume = {473},<br>&nbsp;&nbsp;&nbsp;&nbsp;	Year = {2023},<br>&nbsp;&nbsp;&nbsp;&nbsp;	Bdsk-Url-1 = {https://www.scopus.com/inward/record.uri?eid=2-s2.0-85173012491&doi=10.1016%2fj.fss.2023.108734&partnerID=40&md5=fc32c575cc11bc26c7969e3f76c6ed3c},<br>&nbsp;&nbsp;&nbsp;&nbsp;	Bdsk-Url-2 = {http://dx.doi.org/10.1016/j.fss.2023.108734}<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1016/j.fss.2023.108734" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1016/j.fss.2023.108734" class="plumx-details" data-site="plum" data-hide-when-empty="true">Fuzzy closure structures as formal concepts II</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1016/j.fss.2023.108734"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Cordero_2024></a>[[1]](#cite-Cordero_2024) P. Cordero, M. Enciso, Á. Mora, et al. “Attribute implications with unknown information based on weak Heyting algebras”. In: _Fuzzy Sets and Systems_ 490 (Aug. 2024), p. 109026. ISSN: 0165-0114. DOI: [10.1016/j.fss.2024.109026](https://doi.org/10.1016%2Fj.fss.2024.109026). URL: [http://dx.doi.org/10.1016/j.fss.2024.109026](http://dx.doi.org/10.1016/j.fss.2024.109026).

<a name=bib-Ojeda_Hern_ndez_2023></a>[[2]](#cite-Ojeda_Hern_ndez_2023) M. Ojeda-Hernández, I. P. Cabrera, P. Cordero, et al. “On the Commutative Diagrams Among Galois Connections Involved in Closure Structures”. In: _Formal Concept Analysis_. Springer Nature Switzerland, 2023, p. 49–63. ISBN: 9783031359491. DOI: [10.1007/978-3-031-35949-1_4](https://doi.org/10.1007%2F978-3-031-35949-1_4). URL: [http://dx.doi.org/10.1007/978-3-031-35949-1_4](http://dx.doi.org/10.1007/978-3-031-35949-1_4).

<a name=bib-Talavera_2024></a>[[3]](#cite-Talavera_2024) F. J. Talavera, C. Bejines, S. Ardanza-Trevijano, et al. “Aggregation of fuzzy graphs”. In: _International Journal of Approximate Reasoning_ 172 (Sep. 2024), p. 109243. ISSN: 0888-613X. DOI: [10.1016/j.ijar.2024.109243](https://doi.org/10.1016%2Fj.ijar.2024.109243). URL: [http://dx.doi.org/10.1016/j.ijar.2024.109243](http://dx.doi.org/10.1016/j.ijar.2024.109243).


