---
title: A Tool for User-guided Database Application Development - Automatic Design
  of {XML} Models using {CBD}
author:
- Carlos Rossi
- Antonio Guevara
- <a href='/people/staff/enciso/' style='color:rgb(100,0,50);'>Manuel Enciso</a>
- José Luis Caro
- <a href='/people/staff/amora/' style='color:rgb(100,0,50);'>Ángel Mora</a>
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
date: '2010'
categories: uncategorised
slug: 2010/ToDaApDeAuDeMoUs
details: '{ICSOFT} 2010 - Proceedings of the Fifth International Conference on Software
  and Data Technologies, Volume 2, Athens, Greece, July 22-24, 2010 , pages 195--200.'
---



# Abstract


Beyond the database normalization process, much work has been done on the use of functional dependencies
(FDs), their discovery using mining techniques, their use in query optimization and in the design of algorithms
dealing with the implication problem etc. Nevertheless, although much research expounds the benefits of using
functional dependencies, only a few modeling tools actually use them. In this work we present CBD, a new
software development tool which allows end users to specify their requirements. CBD allows the user to design
his/her own GUI for the application using forms and interface elements and it builds a meta-data dictionary
with information on functional dependencies. This data dictionary will be used to generate the unified data
model and a behavior model.








# Citation
Please, cite this work as:


<a name=bib-Rossi2010></a>[[Ros+10]](#cite-Rossi2010) C. Rossi, A. Guevara, M. Enciso, et al. “A Tool for User-guided Database Application Development - Automatic Design of XML Models using CBD”. In: _ICSOFT 2010 - Proceedings of the Fifth International Conference on Software and Data Technologies, Volume 2, Athens, Greece, July 22-24, 2010_. Ed. by J. A. M. Cordeiro, M. Virvou and B. Shishkov. SciTePress, 2010, pp. 195-200.

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Rossi2010,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Carlos Rossi and Antonio Guevara and Manuel Enciso and Jos{\a'e} Luis Caro and {\a'A}ngel Mora and Pablo Cordero},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {{ICSOFT} 2010 - Proceedings of the Fifth International Conference on Software and Data Technologies, Volume 2, Athens, Greece, July 22-24, 2010},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {A Tool for User-guided Database Application Development - Automatic Design of {XML} Models using {CBD}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2010},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Jos{\a'e} A. Moinhos Cordeiro and Maria Virvou and Boris Shishkov},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {195--200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {SciTePress},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {Beyond the database normalization process, much work has been done on the use of functional dependencies<br>&nbsp;&nbsp;&nbsp;&nbsp;(FDs), their discovery using mining techniques, their use in query optimization and in the design of algorithms<br>&nbsp;&nbsp;&nbsp;&nbsp;dealing with the implication problem etc. Nevertheless, although much research expounds the benefits of using<br>&nbsp;&nbsp;&nbsp;&nbsp;functional dependencies, only a few modeling tools actually use them. In this work we present CBD, a new<br>&nbsp;&nbsp;&nbsp;&nbsp;software development tool which allows end users to specify their requirements. CBD allows the user to design<br>&nbsp;&nbsp;&nbsp;&nbsp;his/her own GUI for the application using forms and interface elements and it builds a meta-data dictionary<br>&nbsp;&nbsp;&nbsp;&nbsp;with information on functional dependencies. This data dictionary will be used to generate the unified data<br>&nbsp;&nbsp;&nbsp;&nbsp;model and a behavior model.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/icsoft/RossiGECMC10.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 23 Sep 2022 01:00:00 +0200},<br>}

:::








