---
title: An Efficient Algorithm for Reasoning about Fuzzy Functional Dependencies
author:
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/enciso/' style='color:rgb(100,0,50);'>Manuel Enciso</a>
- <a href='/people/staff/amora/' style='color:rgb(100,0,50);'>Ángel Mora</a>
- Inmaculada Perez de Guzmán
- José Manuel Rodríguez-Jiménez
date: '2011'
categories: uncategorised
slug: 2011/EfAlReFuFuDe
details: Advances in Computational Intelligence - 11th International Work-Conference
  on Artificial Neural Networks, {IWANN} 2011, Torremolinos-M{\'{a}}laga, Spain, June
  8-10, 2011, Proceedings, Part {II} , Lecture Notes in Computer Science vol. 6692,
  pages 412--420.
doi: 10.1007/978-3-642-21498-1_52
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Cordero2011a></a>[[Cor+11]](#cite-Cordero2011a) P. Cordero, M. Enciso, Á. Mora, et al. “An Efficient Algorithm for Reasoning about Fuzzy Functional Dependencies”. In: _Advances in Computational Intelligence - 11th International Work-Conference on Artificial Neural Networks, IWANN 2011, Torremolinos-Málaga, Spain, June 8-10, 2011, Proceedings, Part II_. Ed. by J. Cabestany, I. Rojas and G. J. Caparrós. Vol. 6692. Lecture Notes in Computer Science. Springer, 2011, pp. 412-420. DOI: [10.1007/978-3-642-21498-1\_52](https://doi.org/10.1007%2F978-3-642-21498-1%5C_52). URL: [https://doi.org/10.1007/978-3-642-21498-1\_52](https://doi.org/10.1007/978-3-642-21498-1\_52).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Cordero2011a,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Pablo Cordero and Manuel Enciso and {\a'A}ngel Mora and Inmaculada Perez {de Guzm{\a'a}n} and Jos{\a'e} Manuel Rodr\'\iguez-Jim{\a'e}nez},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Advances in Computational Intelligence - 11th International Work-Conference on Artificial Neural Networks, {IWANN} 2011, Torremolinos-M{\'{a}}laga, Spain, June 8-10, 2011, Proceedings, Part {II}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {An Efficient Algorithm for Reasoning about Fuzzy Functional Dependencies},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2011},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Joan Cabestany and Ignacio Rojas and Gonzalo Joya Caparr{\a'o}s},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {412--420},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {6692},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/iwann/CorderoEMGR11.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/978-3-642-21498-1\_52},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 23 Sep 2022 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/978-3-642-21498-1\_52},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/978-3-642-21498-1_52" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/978-3-642-21498-1_52" class="plumx-details" data-site="plum" data-hide-when-empty="true">An Efficient Algorithm for Reasoning about Fuzzy Functional Dependencies</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1007/978-3-642-21498-1_52"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Badia_2018></a>[[1]](#cite-Badia_2018) A. Badia and D. Lemire. “On Desirable Semantics of Functional Dependencies over Databases with Incomplete Information”. In: _Fundamenta Informaticae_ 158.4 (Feb. 2018), p. 327–352. ISSN: 1875-8681. DOI: [10.3233/fi-2018-1651](https://doi.org/10.3233%2Ffi-2018-1651). URL: [http://dx.doi.org/10.3233/fi-2018-1651](http://dx.doi.org/10.3233/fi-2018-1651).

<a name=bib-Cordero_2018></a>[[2]](#cite-Cordero_2018) P. Cordero, M. Enciso, and A. Mora. “Directness in Fuzzy Formal Concept Analysis”. In: _Information Processing and Management of Uncertainty in Knowledge-Based Systems. Theory and Foundations_. Springer International Publishing, 2018, p. 585–595. ISBN: 9783319914732. DOI: [10.1007/978-3-319-91473-2_50](https://doi.org/10.1007%2F978-3-319-91473-2_50). URL: [http://dx.doi.org/10.1007/978-3-319-91473-2_50](http://dx.doi.org/10.1007/978-3-319-91473-2_50).

<a name=bib-Rodr_guez_Jim_nez_2013></a>[[3]](#cite-Rodr_guez_Jim_nez_2013) J. M. Rodríguez-Jiménez, P. Cordero, M. Enciso, et al. “Automated Inference with Fuzzy Functional Dependencies over Graded Data”. In: _Advances in Computational Intelligence_. Springer Berlin Heidelberg, 2013, p. 254–265. ISBN: 9783642386824. DOI: [10.1007/978-3-642-38682-4_29](https://doi.org/10.1007%2F978-3-642-38682-4_29). URL: [http://dx.doi.org/10.1007/978-3-642-38682-4_29](http://dx.doi.org/10.1007/978-3-642-38682-4_29).

<a name=bib-Rodriguez_Jimenez_2015></a>[[4]](#cite-Rodriguez_Jimenez_2015) J. Rodriguez-Jimenez, E. Rodriguez-Lorenzo, P. Cordero, et al. “A Normal Form for Fuzzy Functional Dependencies”. In: _2015 IEEE Symposium Series on Computational Intelligence_. IEEE, Dec. 2015, p. 984–989. DOI: [10.1109/ssci.2015.143](https://doi.org/10.1109%2Fssci.2015.143). URL: [http://dx.doi.org/10.1109/ssci.2015.143](http://dx.doi.org/10.1109/ssci.2015.143).

