---
title: Knowledge discovery in social networks by using a logic-based treatment of
  implications
author:
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/enciso/' style='color:rgb(100,0,50);'>Manuel Enciso</a>
- <a href='/people/staff/amora/' style='color:rgb(100,0,50);'>Ángel Mora</a>
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
- Carlos Rossi
date: '2015'
categories: uncategorised
slug: 2015/KnDiSoNeUsTrIm
details: Knowl. Based Syst. vol. 87 , pages 16--25.
doi: 10.1016/J.KNOSYS.2015.07.018
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Cordero2015></a>[[Cor+15]](#cite-Cordero2015) P. Cordero, M. Enciso, Á. Mora, et al. “Knowledge discovery in social networks by using a logic-based treatment of implications”. In: _Knowl. Based Syst._ 87 (2015), pp. 16-25. DOI: [10.1016/J.KNOSYS.2015.07.018](https://doi.org/10.1016%2FJ.KNOSYS.2015.07.018). URL: [https://doi.org/10.1016/j.knosys.2015.07.018](https://doi.org/10.1016/j.knosys.2015.07.018).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{Cordero2015,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Pablo Cordero and Manuel Enciso and {\a'A}ngel Mora and Manuel Ojeda-Aciego and Carlos Rossi},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Knowl. Based Syst.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Knowledge discovery in social networks by using a logic-based treatment of implications},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2015},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {16--25},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {87},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/kbs/CorderoEMOR15.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1016/J.KNOSYS.2015.07.018},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 23 Sep 2022 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1016/j.knosys.2015.07.018},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1016/J.KNOSYS.2015.07.018" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1016/J.KNOSYS.2015.07.018" class="plumx-details" data-site="plum" data-hide-when-empty="true">Knowledge discovery in social networks by using a logic-based treatment of implications</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1016/J.KNOSYS.2015.07.018"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Addam_2016></a>[[1]](#cite-Addam_2016) O. Addam, A. Chen, W. Hoang, et al. “Foreign exchange data crawling and analysis for knowledge discovery leading to informative decision making”. In: _Knowledge-Based Systems_ 102 (Jun. 2016), p. 1–19. ISSN: 0950-7051. DOI: [10.1016/j.knosys.2016.03.005](https://doi.org/10.1016%2Fj.knosys.2016.03.005). URL: [http://dx.doi.org/10.1016/j.knosys.2016.03.005](http://dx.doi.org/10.1016/j.knosys.2016.03.005).

<a name=bib-Antoni_2024></a>[[2]](#cite-Antoni_2024) Ľ. Antoni, P. Eliaš, J. Guniš, et al. “Bimorphisms and attribute implications in heterogeneous formal contexts”. In: _International Journal of Approximate Reasoning_ 172 (Sep. 2024), p. 109245. ISSN: 0888-613X. DOI: [10.1016/j.ijar.2024.109245](https://doi.org/10.1016%2Fj.ijar.2024.109245). URL: [http://dx.doi.org/10.1016/j.ijar.2024.109245](http://dx.doi.org/10.1016/j.ijar.2024.109245).

<a name=bib-Arag_n_2021></a>[[3]](#cite-Arag_n_2021) R. G. Aragón, J. Medina, and E. Ramírez-Poussa. “Identifying Non-Sublattice Equivalence Classes Induced by an Attribute Reduction in FCA”. In: _Mathematics_ 9.5 (Mar. 2021), p. 565. ISSN: 2227-7390. DOI: [10.3390/math9050565](https://doi.org/10.3390%2Fmath9050565). URL: [http://dx.doi.org/10.3390/math9050565](http://dx.doi.org/10.3390/math9050565).

<a name=bib-Benito_Picazo_2017></a>[[4]](#cite-Benito_Picazo_2017) F. Benito‐Picazo, M. Enciso, C. Rossi, et al. “Enhancing the conversational process by using a logical closure operator in phenotypes implications”. In: _Mathematical Methods in the Applied Sciences_ 41.3 (Feb. 2017), p. 1089–1100. ISSN: 1099-1476. DOI: [10.1002/mma.4338](https://doi.org/10.1002%2Fmma.4338). URL: [http://dx.doi.org/10.1002/mma.4338](http://dx.doi.org/10.1002/mma.4338).

<a name=bib-Cabrera_2018></a>[[5]](#cite-Cabrera_2018) I. P. Cabrera, P. Cordero, F. Garcia-Pardo, et al. “Galois Connections Between a Fuzzy Preordered Structure and a General Fuzzy Structure”. In: _IEEE Transactions on Fuzzy Systems_ 26.3 (Jun. 2018), p. 1274–1287. ISSN: 1941-0034. DOI: [10.1109/tfuzz.2017.2718495](https://doi.org/10.1109%2Ftfuzz.2017.2718495). URL: [http://dx.doi.org/10.1109/tfuzz.2017.2718495](http://dx.doi.org/10.1109/tfuzz.2017.2718495).

<a name=bib-Cordero_20201></a>[[6]](#cite-Cordero_20201) P. Cordero, M. Enciso, Á. Mora, et al. “A Formal Concept Analysis Approach to Cooperative Conversational Recommendation”. In: _International Journal of Computational Intelligence Systems_ 13.1 (2020), p. 1243. ISSN: 1875-6883. DOI: [10.2991/ijcis.d.200806.001](https://doi.org/10.2991%2Fijcis.d.200806.001). URL: [http://dx.doi.org/10.2991/ijcis.d.200806.001](http://dx.doi.org/10.2991/ijcis.d.200806.001).

<a name=bib-Cordero_2020></a>[[7]](#cite-Cordero_2020) P. Cordero, M. Enciso, A. Mora, et al. “Parameterized simplification logic I: reasoning with implications and classes of closure operators”. In: _International Journal of General Systems_ 49.7 (Oct. 2020), p. 724–746. ISSN: 1563-5104. DOI: [10.1080/03081079.2020.1831484](https://doi.org/10.1080%2F03081079.2020.1831484). URL: [http://dx.doi.org/10.1080/03081079.2020.1831484](http://dx.doi.org/10.1080/03081079.2020.1831484).

<a name=bib-Dubois_2021></a>[[8]](#cite-Dubois_2021) D. Dubois, J. Medina, H. Prade, et al. “Disjunctive attribute dependencies in formal concept analysis under the epistemic view of formal contexts”. In: _Information Sciences_ 561 (Jun. 2021), p. 31–51. ISSN: 0020-0255. DOI: [10.1016/j.ins.2020.12.085](https://doi.org/10.1016%2Fj.ins.2020.12.085). URL: [http://dx.doi.org/10.1016/j.ins.2020.12.085](http://dx.doi.org/10.1016/j.ins.2020.12.085).

<a name=bib-Huang_2016></a>[[9]](#cite-Huang_2016) C. Huang, B. Hu, G. Jiang, et al. “Modeling of agent-based complex network under cyber-violence”. In: _Physica A: Statistical Mechanics and its Applications_ 458 (Sep. 2016), p. 399–411. ISSN: 0378-4371. DOI: [10.1016/j.physa.2016.03.066](https://doi.org/10.1016%2Fj.physa.2016.03.066). URL: [http://dx.doi.org/10.1016/j.physa.2016.03.066](http://dx.doi.org/10.1016/j.physa.2016.03.066).

<a name=bib-Jelodar_2020></a>[[10]](#cite-Jelodar_2020) H. Jelodar, Y. Wang, M. Rabbani, et al. “A NLP framework based on meaningful latent-topic detection and sentiment analysis via fuzzy lattice reasoning on youtube comments”. In: _Multimedia Tools and Applications_ 80.3 (Sep. 2020), p. 4155–4181. ISSN: 1573-7721. DOI: [10.1007/s11042-020-09755-z](https://doi.org/10.1007%2Fs11042-020-09755-z). URL: [http://dx.doi.org/10.1007/s11042-020-09755-z](http://dx.doi.org/10.1007/s11042-020-09755-z).

<a name=bib-Kardo__2016></a>[[11]](#cite-Kardo__2016) F. Kardoš, J. Pócs, and J. Pócsová. “On concept reduction based on some graph properties”. In: _Knowledge-Based Systems_ 93 (Feb. 2016), p. 67–74. ISSN: 0950-7051. DOI: [10.1016/j.knosys.2015.11.003](https://doi.org/10.1016%2Fj.knosys.2015.11.003). URL: [http://dx.doi.org/10.1016/j.knosys.2015.11.003](http://dx.doi.org/10.1016/j.knosys.2015.11.003).

<a name=bib-Liu_2020></a>[[12]](#cite-Liu_2020) T. Liu, H. Zhang, and H. Zhang. “The Impact of Social Media on Risk Communication of Disasters—A Comparative Study Based on Sina Weibo Blogs Related to Tianjin Explosion and Typhoon Pigeon”. In: _International Journal of Environmental Research and Public Health_ 17.3 (Jan. 2020), p. 883. ISSN: 1660-4601. DOI: [10.3390/ijerph17030883](https://doi.org/10.3390%2Fijerph17030883). URL: [http://dx.doi.org/10.3390/ijerph17030883](http://dx.doi.org/10.3390/ijerph17030883).

<a name=bib-Luo_2023></a>[[13]](#cite-Luo_2023) X. Luo. “The Logic of Homophily Dynamics in Heterogeneous Networks: Axiomatization, Model Checking and Validity Checking”. In: _Mathematics_ 11.16 (Aug. 2023), p. 3484. ISSN: 2227-7390. DOI: [10.3390/math11163484](https://doi.org/10.3390%2Fmath11163484). URL: [http://dx.doi.org/10.3390/math11163484](http://dx.doi.org/10.3390/math11163484).

<a name=bib-Majeed_2020></a>[[14]](#cite-Majeed_2020) A. Majeed and I. Rauf. “Graph Theory: A Comprehensive Survey about Graph Theory Applications in Computer Science and Social Networks”. In: _Inventions_ 5.1 (Feb. 2020), p. 10. ISSN: 2411-5134. DOI: [10.3390/inventions5010010](https://doi.org/10.3390%2Finventions5010010). URL: [http://dx.doi.org/10.3390/inventions5010010](http://dx.doi.org/10.3390/inventions5010010).

<a name=bib-Medina_2017></a>[[15]](#cite-Medina_2017) J. Medina, K. Pakhomova, and E. Ramirez-Poussa. “Interpreting and analyzing a location-based social network by fuzzy formal contexts”. In: _2017 IEEE Symposium Series on Computational Intelligence (SSCI)_. IEEE, Nov. 2017, p. 1–6. DOI: [10.1109/ssci.2017.8285282](https://doi.org/10.1109%2Fssci.2017.8285282). URL: [http://dx.doi.org/10.1109/ssci.2017.8285282](http://dx.doi.org/10.1109/ssci.2017.8285282).

<a name=bib-Medina_2018></a>[[16]](#cite-Medina_2018) J. Medina, K. Pakhomova, and E. Ramírez-Poussa. “Recommendation Solution for a Locate-Based Social Network via Formal Concept Analysis”. In: _Trends in Mathematics and Computational Intelligence_. Springer International Publishing, Oct. 2018, p. 131–138. ISBN: 9783030004859. DOI: [10.1007/978-3-030-00485-9_15](https://doi.org/10.1007%2F978-3-030-00485-9_15). URL: [http://dx.doi.org/10.1007/978-3-030-00485-9_15](http://dx.doi.org/10.1007/978-3-030-00485-9_15).

<a name=bib-Neto_2018></a>[[17]](#cite-Neto_2018) S. M. Neto, S. Dias, R. Missaoui, et al. “Identification of substructures in complex networks using formal concept analysis”. In: _International Journal of Web Information Systems_ 14.3 (Aug. 2018), p. 281–298. ISSN: 1744-0084. DOI: [10.1108/ijwis-10-2017-0067](https://doi.org/10.1108%2Fijwis-10-2017-0067). URL: [http://dx.doi.org/10.1108/ijwis-10-2017-0067](http://dx.doi.org/10.1108/ijwis-10-2017-0067).

<a name=bib-Ojeda_Hern_ndez_2022></a>[[18]](#cite-Ojeda_Hern_ndez_2022) M. Ojeda-Hernández, I. P. Cabrera, and P. Cordero. “Quasi-closed elements in fuzzy posets”. In: _Journal of Computational and Applied Mathematics_ 404 (Apr. 2022), p. 113390. ISSN: 0377-0427. DOI: [10.1016/j.cam.2021.113390](https://doi.org/10.1016%2Fj.cam.2021.113390). URL: [http://dx.doi.org/10.1016/j.cam.2021.113390](http://dx.doi.org/10.1016/j.cam.2021.113390).

<a name=bib-P_rez_G_mez_2022></a>[[19]](#cite-P_rez_G_mez_2022) F. Pérez-Gámez, P. Cordero, M. Enciso, et al. “Computing the Mixed Concept Lattice”. In: _Information Processing and Management of Uncertainty in Knowledge-Based Systems_. Springer International Publishing, 2022, p. 87–99. ISBN: 9783031089718. DOI: [10.1007/978-3-031-08971-8_8](https://doi.org/10.1007%2F978-3-031-08971-8_8). URL: [http://dx.doi.org/10.1007/978-3-031-08971-8_8](http://dx.doi.org/10.1007/978-3-031-08971-8_8).

<a name=bib-Raissa_2018></a>[[20]](#cite-Raissa_2018) P. Raissa, S. Dias, M. Song, et al. “Minimal implications base for social network analysis”. In: _International Journal of Web Information Systems_ 14.1 (Apr. 2018), p. 62–77. ISSN: 1744-0084. DOI: [10.1108/ijwis-04-2017-0028](https://doi.org/10.1108%2Fijwis-04-2017-0028). URL: [http://dx.doi.org/10.1108/ijwis-04-2017-0028](http://dx.doi.org/10.1108/ijwis-04-2017-0028).

<a name=bib-Rodr_guez_Lorenzo_2017></a>[[21]](#cite-Rodr_guez_Lorenzo_2017) E. Rodríguez-Lorenzo, P. Cordero, M. Enciso, et al. “Canonical dichotomous direct bases”. In: _Information Sciences_ 376 (Jan. 2017), p. 39–53. ISSN: 0020-0255. DOI: [10.1016/j.ins.2016.10.004](https://doi.org/10.1016%2Fj.ins.2016.10.004). URL: [http://dx.doi.org/10.1016/j.ins.2016.10.004](http://dx.doi.org/10.1016/j.ins.2016.10.004).

<a name=bib-Silva_2018></a>[[22]](#cite-Silva_2018) P. R. Silva, S. M. Dias, W. C. Brandão, et al. “Professional Competence Identification Through Formal Concept Analysis”. In: _Enterprise Information Systems_. Springer International Publishing, 2018, p. 34–56. ISBN: 9783319933757. DOI: [10.1007/978-3-319-93375-7_3](https://doi.org/10.1007%2F978-3-319-93375-7_3). URL: [http://dx.doi.org/10.1007/978-3-319-93375-7_3](http://dx.doi.org/10.1007/978-3-319-93375-7_3).

<a name=bib-Singh_2024></a>[[23]](#cite-Singh_2024) S. S. Singh, S. Muhuri, S. Mishra, et al. “Social Network Analysis: A Survey on Process, Tools, and Application”. In: _ACM Computing Surveys_ 56.8 (Apr. 2024), p. 1–39. ISSN: 1557-7341. DOI: [10.1145/3648470](https://doi.org/10.1145%2F3648470). URL: [http://dx.doi.org/10.1145/3648470](http://dx.doi.org/10.1145/3648470).

<a name=bib-Zhang_2023></a>[[24]](#cite-Zhang_2023) S. Zhang, J. Zhang, J. Li, et al. “A user-guided reduction concept lattice and its algebraic structure”. In: _Expert Systems with Applications_ 217 (May. 2023), p. 119537. ISSN: 0957-4174. DOI: [10.1016/j.eswa.2023.119537](https://doi.org/10.1016%2Fj.eswa.2023.119537). URL: [http://dx.doi.org/10.1016/j.eswa.2023.119537](http://dx.doi.org/10.1016/j.eswa.2023.119537).

<a name=bib-Zhou_2023></a>[[25]](#cite-Zhou_2023) Y. Zhou, J. Li, H. Yang, et al. “Knowledge structures construction and learning paths recommendation based on formal contexts”. In: _International Journal of Machine Learning and Cybernetics_ 15.4 (Oct. 2023), p. 1605–1620. ISSN: 1868-808X. DOI: [10.1007/s13042-023-01985-5](https://doi.org/10.1007%2Fs13042-023-01985-5). URL: [http://dx.doi.org/10.1007/s13042-023-01985-5](http://dx.doi.org/10.1007/s13042-023-01985-5).

