---
author:
- Domingo López-Rodríguez
- Carlos Criado
Status: Published
date: '2004-11-01T00:00:00Z'
slug: 2004-jce
title: A Pedagogical Simulation of Maxwell's Demon
categories: E-learning
header_image: ~
details: <em>Journal of Chemical Education</em>, 81(11), pp. 1679
doi: 10.1021/ed081p1679.2
link: 2004-jce/paper.pdf
project: ~
keywords: Computer-based learning, Statistical mechanics
---



# Abstract


This program simulates, at the microscopic level, two gas chambers with an opening between them. The program allows users to set up simulations that illustrate the thermodynamics and statistical behavior of the system. The user determines the basis for whether the demon permits or denies passage of particles through the opening using information from the microscopic level.







# Citation
Please, cite this work as:


<a name=bib-criado2004></a>[[LC04]](#cite-criado2004) D. López and C. Criado. “A Pedagogical Simulation of Maxwells Demon Paradox”. In: _Journal of Chemical Education_ 81.11 (2004), p. 1679. DOI: [10.1021/ed081p1679.2](https://doi.org/10.1021%2Fed081p1679.2).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@article{criado2004,<br>&nbsp;&nbsp;&nbsp;&nbsp;author = {López, D. and Criado, C.},<br>&nbsp;&nbsp;&nbsp;&nbsp;title = {A Pedagogical Simulation of Maxwells Demon Paradox},<br>&nbsp;&nbsp;&nbsp;&nbsp;journal = {Journal of Chemical Education},<br>&nbsp;&nbsp;&nbsp;&nbsp;volume = {81},<br>&nbsp;&nbsp;&nbsp;&nbsp;number = {11},<br>&nbsp;&nbsp;&nbsp;&nbsp;pages = {1679},<br>&nbsp;&nbsp;&nbsp;&nbsp;year = {2004},<br>&nbsp;&nbsp;&nbsp;&nbsp;doi = {10.1021/ed081p1679.2},<br>&nbsp;&nbsp;&nbsp;&nbsp;abstract = { This program simulates, at the microscopic level, two gas chambers with an opening between them. The program allows users to set up simulations that illustrate the thermodynamics and statistical behavior of the system. The user determines the basis for whether the demon permits or denies passage of particles through the opening using information from the microscopic level. }<br>}

:::


