---
title: On the Complexity of Fragments of Horn Modal Logics
author:
- Davide Bresolin
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
- Guido Sciavicco
date: '2016'
categories: uncategorised
slug: 2016/CoFrHoMoLo
details: 23rd International Symposium on Temporal Representation and Reasoning, {TIME}
  2016, Kongens Lyngby, Denmark, October 17-19, 2016 , pages 186--195.
doi: 10.1109/TIME.2016.27
---



# Abstract


Modal logic is a paradigm for several useful and applicable formal systems in computer science, and, in particular, for temporal logics of various kinds. It generally retains the low complexity of classical propositional logic, but notable exceptions exist that present higher complexity or are even undecidable. In search of computationally well-behaved fragments, clausal forms and other sub-propositional restrictions of temporal and description logics have been recently studied. It is known that the Horn fragments of the modal logics between K and S4 are PSPACE-complete, keeping the same complexity of the the full propositional versions. In this paper, inspired by similar results in the temporal case, we sharpen the above result by showing that if we allow only box modalities in the language the Horn fragments of the modal logics between K and S4 become P-complete. Exploring the innermost reasons for the tractability of sub-Horn modal logics is a necessary condition to understand the behaviour of more expressive temporal and spatial languages under similar restrictions.








# Citation
Please, cite this work as:


<a name=bib-Bresolin2016></a>[[BMS16]](#cite-Bresolin2016) D. Bresolin, E. Mu~noz-Velasco, and G. Sciavicco. “On the Complexity of Fragments of Horn Modal Logics”. In: _23rd International Symposium on Temporal Representation and Reasoning, TIME 2016, Kongens Lyngby, Denmark, October 17-19, 2016_. Ed. by C. E. Dyreson, M. R. Hansen and L. Hunsberger. IEEE Computer Society, 2016, pp. 186-195. DOI: [10.1109/TIME.2016.27](https://doi.org/10.1109%2FTIME.2016.27). URL: [https://doi.org/10.1109/TIME.2016.27](https://doi.org/10.1109/TIME.2016.27).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Bresolin2016,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Davide Bresolin and Emilio Mu~noz-Velasco and Guido Sciavicco},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {23rd International Symposium on Temporal Representation and Reasoning, {TIME} 2016, Kongens Lyngby, Denmark, October 17-19, 2016},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {On the Complexity of Fragments of Horn Modal Logics},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2016},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Curtis E. Dyreson and Michael R. Hansen and Luke Hunsberger},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {186--195},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {{IEEE} Computer Society},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/time/BresolinMS16.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1109/TIME.2016.27},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 24 Mar 2023 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1109/TIME.2016.27},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1109/TIME.2016.27" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1109/TIME.2016.27" class="plumx-details" data-site="plum" data-hide-when-empty="true">On the Complexity of Fragments of Horn Modal Logics</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1109/TIME.2016.27"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Dziubi_ski_2021></a>[[1]](#cite-Dziubi_ski_2021) M. Dziubiński. “Modal context restriction for multiagent BDI logics”. In: _Artificial Intelligence Review_ 55.4 (Oct. 2021), p. 3075–3151. ISSN: 1573-7462. DOI: [10.1007/s10462-021-10064-6](https://doi.org/10.1007%2Fs10462-021-10064-6). URL: [http://dx.doi.org/10.1007/s10462-021-10064-6](http://dx.doi.org/10.1007/s10462-021-10064-6).

<a name=bib-Wa_ga_20191></a>[[2]](#cite-Wa_ga_20191) P. A. Wałęga. “Computational Complexity of Core Fragments of Modal Logics T, K4, and S4”. In: _Logics in Artificial Intelligence_. Springer International Publishing, 2019, p. 744–759. ISBN: 9783030195700. DOI: [10.1007/978-3-030-19570-0_48](https://doi.org/10.1007%2F978-3-030-19570-0_48). URL: [http://dx.doi.org/10.1007/978-3-030-19570-0_48](http://dx.doi.org/10.1007/978-3-030-19570-0_48).

<a name=bib-Wa_ga_2019></a>[[3]](#cite-Wa_ga_2019) P. A. Wałęga. “Hybrid fragments of Halpern–Shoham logic and their expressive power”. In: _Theoretical Computer Science_ 797 (Dec. 2019), p. 102–128. ISSN: 0304-3975. DOI: [10.1016/j.tcs.2019.01.014](https://doi.org/10.1016%2Fj.tcs.2019.01.014). URL: [http://dx.doi.org/10.1016/j.tcs.2019.01.014](http://dx.doi.org/10.1016/j.tcs.2019.01.014).

