---
title: Composing Submonads
author:
- Patrik Eklund
- Maria A. Galán
- Jesús Medina
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
- Agustín Valverde
date: '2001'
categories: uncategorised
slug: 2001/CoSu
details: 31st {IEEE} International Symposium on Multiple-Valued Logic, {ISMVL} 2001,
  Warsaw, Poland, May 22-24, 2001, Proceedings , pages 367--372.
doi: 10.1109/ISMVL.2001.924597
---



# Abstract


In this paper we use the concept of subfunctors and submonads in order to provide a technique for constructing new monads from given ones. We study some properties of these constructions and provide more examples on monad compositions.








# Citation
Please, cite this work as:


<a name=bib-Eklund2001></a>[[Ekl+01]](#cite-Eklund2001) P. Eklund, M. A. Galán, J. Medina, et al. “Composing Submonads”. In: _31st IEEE International Symposium on Multiple-Valued Logic, ISMVL 2001, Warsaw, Poland, May 22-24, 2001, Proceedings_. IEEE Computer Society, 2001, pp. 367-372. DOI: [10.1109/ISMVL.2001.924597](https://doi.org/10.1109%2FISMVL.2001.924597). URL: [https://doi.org/10.1109/ISMVL.2001.924597](https://doi.org/10.1109/ISMVL.2001.924597).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Eklund2001,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Patrik Eklund and Maria A. Gal{\a'a}n and Jes{\a'u}s Medina and Manuel Ojeda-Aciego and Agust\'\in Valverde},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {31st {IEEE} International Symposium on Multiple-Valued Logic, {ISMVL} 2001, Warsaw, Poland, May 22-24, 2001, Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Composing Submonads},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2001},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {367--372},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {{IEEE} Computer Society},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/ismvl/EklundGMOV01.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1109/ISMVL.2001.924597},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Thu, 23 Mar 2023 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1109/ISMVL.2001.924597},<br>}

:::






## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Eklund_2009></a>[[1]](#cite-Eklund_2009) P. Eklund. “Early diagnosis of cognitive disorder based on ground categories for decision support structures”. In: _2009 IEEE International Conference on Fuzzy Systems_. IEEE, Aug. 2009, p. 997–1002. DOI: [10.1109/fuzzy.2009.5277098](https://doi.org/10.1109%2Ffuzzy.2009.5277098). URL: [http://dx.doi.org/10.1109/fuzzy.2009.5277098](http://dx.doi.org/10.1109/fuzzy.2009.5277098).

<a name=bib-Eklund_2004></a>[[2]](#cite-Eklund_2004) P. Eklund, M. Galán, J. Medina, et al. “Similarities between powersets of terms”. In: _Fuzzy Sets and Systems_ 144.1 (May. 2004), p. 213–225. ISSN: 0165-0114. DOI: [10.1016/j.fss.2003.10.021](https://doi.org/10.1016%2Fj.fss.2003.10.021). URL: [http://dx.doi.org/10.1016/j.fss.2003.10.021](http://dx.doi.org/10.1016/j.fss.2003.10.021).

