---
title: On Pseudointents in Fuzzy Formal Concept Analysis
author:
- <a href='/people/staff/manuojeda/' style='color:rgb(100,0,50);'>Manuel Ojeda Hernández</a>
- <a href='/people/staff/ipcabrera/' style='color:rgb(100,0,50);'>Inma P. Cabrera</a>
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
date: '2023'
categories: uncategorised
slug: 2023/PsFuFoCoAn
details: Graph-Based Representation and Reasoning - 28th International Conference
  on Conceptual Structures, {ICCS} 2023, Berlin, Germany, September 11-13, 2023, Proceedings
  , Lecture Notes in Computer Science vol. 14133, pages 36--40.
doi: 10.1007/978-3-031-40960-8_4
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-OjedaHernandez2023b></a>[[Oje+23]](#cite-OjedaHernandez2023b) M. Ojeda-Hernández, I. P. Cabrera, P. Cordero, et al. “On Pseudointents in Fuzzy Formal Concept Analysis”. In: _Graph-Based Representation and Reasoning - 28th International Conference on Conceptual Structures, ICCS 2023, Berlin, Germany, September 11-13, 2023, Proceedings_. Ed. by M. Ojeda-Aciego, K. Sauerwald and R. Jäschke. Vol. 14133. Lecture Notes in Computer Science. Springer, 2023, pp. 36-40. DOI: [10.1007/978-3-031-40960-8\_4](https://doi.org/10.1007%2F978-3-031-40960-8%5C_4). URL: [https://doi.org/10.1007/978-3-031-40960-8\_4](https://doi.org/10.1007/978-3-031-40960-8\_4).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{OjedaHernandez2023b,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Manuel Ojeda-Hern{\a'a}ndez and Inma P. Cabrera and Pablo Cordero and Emilio Mu~noz-Velasco},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Graph-Based Representation and Reasoning - 28th International Conference on Conceptual Structures, {ICCS} 2023, Berlin, Germany, September 11-13, 2023, Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {On Pseudointents in Fuzzy Formal Concept Analysis},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2023},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Manuel Ojeda-Aciego and Kai Sauerwald and Robert J{\"a}schke},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {36--40},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {14133},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/iccs/OjedaHernandezCCM23.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/978-3-031-40960-8\_4},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Thu, 14 Sep 2023 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/978-3-031-40960-8\_4},<br>}

:::








