---
title: A Critical Analysis of the Theoretical Framework of the Extreme Learning Machine
author:
- Irina Perfilieva
- Nicolás Madrid
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
- Piotr Artiemjew
- Agnieszka Niemczynowicz
date: '2024'
categories: uncategorised
slug: 2024/CrAnThFrExLeMa
details: []
doi: 10.48550/ARXIV.2406.17427
---



# Abstract


Despite the number of successful applications of the Extreme Learning Machine (ELM), we show that its underlying foundational principles do not have a rigorous mathematical justification. Specifically, we refute the proofs of two main statements, and we also create a dataset that provides a counterexample to the ELM learning algorithm and explain its design, which leads to many such counterexamples. Finally, we provide alternative statements of the foundations, which justify the efficiency of ELM in some theoretical cases.








# Citation
Please, cite this work as:


<a name=bib-Perfilieva2024></a>[[Per+24]](#cite-Perfilieva2024) I. Perfilieva, N. Madrid, M. Ojeda-Aciego, et al. “A Critical Analysis of the Theoretical Framework of the Extreme Learning Machine”. In: _CoRR_ abs/2406.17427 (2024). DOI: [10.48550/ARXIV.2406.17427](https://doi.org/10.48550%2FARXIV.2406.17427). eprint: 2406.17427. URL: [https://doi.org/10.48550/arXiv.2406.17427](https://doi.org/10.48550/arXiv.2406.17427).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{Perfilieva2024,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Irina Perfilieva and Nicol{\a'a}s Madrid and Manuel Ojeda-Aciego and Piotr Artiemjew and Agnieszka Niemczynowicz},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {CoRR},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {A Critical Analysis of the Theoretical Framework of the Extreme Learning Machine},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2024},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {abs/2406.17427},<br>&nbsp;&nbsp;&nbsp;&nbsp;  archiveprefix = {arXiv},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/corr/abs-2406-17427.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.48550/ARXIV.2406.17427},<br>&nbsp;&nbsp;&nbsp;&nbsp;  eprint = {2406.17427},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Tue, 23 Jul 2024 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.48550/arXiv.2406.17427},<br>}

:::








