---
author: Domingo López-Rodríguez, E. Mérida-Casermeiro, J.M. Ortiz-De-Lazcano-Lobato
Status: Published
date: '2006-11-01'
slug: 2006/StMuNeApGrMaPr
title: Stochastic multivalued network for optimization. Application to the graph MaxCut
  problem
categories:
- Neural networks
- Combinatorial optimization
header_image: ~
details: International Conference on Computational Intelligence, Man-Machine Systems
  and Cybernetics - Proceedings, (1), <em>pp. 111-116</em>
link: 2006-wseas/paper.pdf
project: ''
keywords: Artificial intelligence, Interactive computer systems, Neural networks,
  Optimization, Stochastic models, Computational experiment, Energy functions, Graph
  problems, Multi-valued networks, Objective functions, Optimization problems, Optimization
  techniques, Stochastic dynamics, Stochastic systems
---


# Abstract


The aim of this paper is to present the stochastic version of the multivalued neural model MREM, which has achieved very good results in many applications, as an optimization technique. The purpose of this stochastic version is to avoid certain local minima of the objective function minimized by the network, that is, the energy function. To this end, the description of the theoretical bases of this model, guaranteeing the convergence to minima, is carried out rigorously. In order to show the efficiency of this new model, the model, in its two versions, deterministic and stochastic, has been applied to the resolution of the well-known problem of graph partition, MaxCut. Computational experiments show that in most cases the stochastic model achieves better results than the deterministic one.












# Citation
Please, cite this work as:


<a name=bib-LopezRodriguez2006></a>[[LMO06]](#cite-LopezRodriguez2006) D. López-Rodríguez, E. Mérida-Casermeiro, and J. Ortiz-De-Lazcano-Lobato. “Stochastic multivalued network for optimization. Application to the graph MaxCut problem”. In: _International Conference on Computational Intelligence, Man-Machine Systems and Cybernetics - Proceedings_. Ed. by M. N. Cecchi A.. Vol. 1. cited By 0; Conference of Proceedings of the 5th WSEAS International Conference on Computational Intelligence, Man-Machine Systems and Cybernetics, CIMMACS '06 ; Conference Date: 20 November 2006 Through 22 November 2006; Conference Code:106271. World Scientific and Engineering Academy and Society, 2006, pp. 111-116. URL:
[https://www.scopus.com/inward/record.uri?eid=2-s2.0-84905721381&partnerID=40&md5=d3a92408b239ff652b5fbf70437f6200](https://www.scopus.com/inward/record.uri?eid=2-s2.0-84905721381&partnerID=40&md5=d3a92408b239ff652b5fbf70437f6200).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{LopezRodriguez2006,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {D. López-Rodríguez and E. Mérida-Casermeiro and J.M. Ortiz-De-Lazcano-Lobato},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {International Conference on Computational Intelligence, Man-Machine Systems and Cybernetics - Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Stochastic multivalued network for optimization. Application to the graph MaxCut problem},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2006},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Mastorakis N. {Cecchi A.}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  note = {cited By 0; Conference of Proceedings of the 5th WSEAS International Conference on Computational Intelligence, Man-Machine Systems and Cybernetics, CIMMACS '06 ; Conference Date: 20 November 2006 Through 22 November 2006; Conference Code:106271},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {111-116},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {World Scientific and Engineering Academy and Society},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {1},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {The aim of this paper is to present the stochastic version of the multivalued neural model MREM, which has achieved very good results in many applications, as an optimization technique. The purpose of this stochastic version is to avoid certain local minima of the objective function minimized by the network, that is, the energy function. To this end, the description of the theoretical bases of this model, guaranteeing the convergence to minima, is carried out rigorously. In order to show the efficiency of this new model, the model, in its two versions, deterministic and stochastic, has been applied to the resolution of the well-known problem of graph partition, MaxCut. Computational experiments show that in most cases the stochastic model achieves better results than the deterministic one.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  author_keywords = {Graph Problems; Neural Networks; Optimization Problems; Stochastic Dynamics},<br>&nbsp;&nbsp;&nbsp;&nbsp;  document_type = {Conference Paper},<br>&nbsp;&nbsp;&nbsp;&nbsp;  keywords = {Artificial intelligence; Interactive computer systems; Neural networks; Optimization; Stochastic models, Computational experiment; Energy functions; Graph problems; Multi-valued networks; Objective functions; Optimization problems; Optimization techniques; Stochastic dynamics, Stochastic systems},<br>&nbsp;&nbsp;&nbsp;&nbsp;  source = {Scopus},<br>&nbsp;&nbsp;&nbsp;&nbsp;  sponsors = {WSEAS; WSEAS Transactions},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://www.scopus.com/inward/record.uri?eid=2-s2.0-84905721381&partnerID=40&md5=d3a92408b239ff652b5fbf70437f6200},<br>}

:::









