---
title: A Neural Approach to Abductive Multi-adjoint Reasoning
author:
- Jesús Medina
- Enrique Mérida Casermeiro
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '2002'
categories: uncategorised
slug: 2002/NeApAbRe
details: 'Artificial Intelligence: Methodology, Systems, and Applications, 10th International
  Conference, {AIMSA} 2002, Varna, Bulgaria, September 4-6, 2002, Proceedings , Lecture
  Notes in Computer Science vol. 2443, pages 213--222.'
doi: 10.1007/3-540-46148-5_22
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Medina2002></a>[[MCO02]](#cite-Medina2002) J. Medina, E. M. Casermeiro, and M. Ojeda-Aciego. “A Neural Approach to Abductive Multi-adjoint Reasoning”. In: _Artificial Intelligence: Methodology, Systems, and Applications, 10th International Conference, AIMSA 2002, Varna, Bulgaria, September 4-6, 2002, Proceedings_. Ed. by D. Scott. Vol. 2443. Lecture Notes in Computer Science. Springer, 2002, pp. 213-222. DOI: [10.1007/3-540-46148-5\_22](https://doi.org/10.1007%2F3-540-46148-5%5C_22). URL: [https://doi.org/10.1007/3-540-46148-5\_22](https://doi.org/10.1007/3-540-46148-5\_22).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Medina2002,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Jes{\a'u}s Medina and Enrique M{\a'e}rida Casermeiro and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Artificial Intelligence: Methodology, Systems, and Applications, 10th International Conference, {AIMSA} 2002, Varna, Bulgaria, September 4-6, 2002, Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {A Neural Approach to Abductive Multi-adjoint Reasoning},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2002},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Donia Scott},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {213--222},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {2443},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/aimsa/MedinaCO02.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/3-540-46148-5\_22},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Thu, 07 Jan 2021 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/3-540-46148-5\_22},<br>}

:::






## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Medina_2004></a>[[1]](#cite-Medina_2004) J. Medina, E. Mérida-Casermeiro, and M. Ojeda-Aciego. “A neural implementation of multi-adjoint logic programming”. In: _Journal of Applied Logic_ 2.3 (Sep. 2004), p. 301–324. ISSN: 1570-8683. DOI: [10.1016/j.jal.2004.03.006](https://doi.org/10.1016%2Fj.jal.2004.03.006). URL: [http://dx.doi.org/10.1016/j.jal.2004.03.006](http://dx.doi.org/10.1016/j.jal.2004.03.006).

<a name=bib-Medina_20041></a>[[2]](#cite-Medina_20041) J. Medina, E. Mérida-Casermeiro, and M. Ojeda-Aciego. “Decomposing Ordinal Sums in Neural Multi-adjoint Logic Programs”. In: _Advances in Artificial Intelligence – IBERAMIA 2004_. Springer Berlin Heidelberg, 2004, p. 717–726. ISBN: 9783540304982. DOI: [10.1007/978-3-540-30498-2_72](https://doi.org/10.1007%2F978-3-540-30498-2_72). URL: [http://dx.doi.org/10.1007/978-3-540-30498-2_72](http://dx.doi.org/10.1007/978-3-540-30498-2_72).

