---
title: Publication of <em>Global-local learning strategies in probabilistic principal
  components analysis</em>
author: E. López-Rubio, J.M. Ortiz-de-Lazcano-Lobato, Domingo López-Rodríguez, E.
  Mérida-Casermeiro, M.D.C. Vargas-González
date: '2006-01-01'
categories:
- Neural networks
- Competitive learning
- Principal component analysis
---

The work <u>Global-local learning strategies in probabilistic principal components analysis</u> has been published in <em>Proceedings of the 10th IASTED International Conference on Artificial Intelligence and Soft Computing, ASC 2006, <em>pp. 46-51</em></em>.

<u>Abstract</u>:


We present a neural model which extends classical competitive learning by performing a Probabilistic Principal Components Analysis at each neuron. In the learning process is utilized a competition rule which try to get the better representation of the dataset while maintaining the homogeneity of the formed clusters. The model also has the ability to learn the number of basis vectors required to represent the principal directions of each cluster, so it overcomes a drawback of most local PCA models, where the dimensionality of a cluster must be fixed a priori.

