---
author: Domingo López-Rodríguez, E. Mérida-Casermeiro, J.M. Ortíz-de-Lazcano-Lobato,
  G. Galán-Marín
Status: Published
date: '2007-01-01'
slug: 2007/GrDrMuNeNe
title: K-pages graph drawing with multivalued neural networks
categories:
- Neural networks
- Combinatorial optimization
header_image: ~
details: Artificial Neural Networks - {ICANN} 2007, 17th International Conference,
  Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial
  Intelligence and Lecture Notes in Bioinformatics), (4669 LNCS), PART 2, <em>pp.
  816-825</em>
doi: 10.1007/978-3-540-74695-9_84
link: 2007-icann/paper.pdf
project: ''
keywords: Algorithms, Edge detection, Function evaluation, Graph theory, Heuristic
  methods, Mathematical models, Efficient algorithms, Energy functions, Multivalued
  neural networks, Neural models, Multilayer neural networks
---


# Abstract


In this paper, the K-pages graph layout problem is solved by a new neural model. This model consists of two neural networks performing jointly in order to minimize the same energy function. The neural technique applied to this problem allows to reduce the energy function by changing outputs from both networks -outputs of first network representing location of nodes in the nodes line, while the outputs of the second one meaning the page where the edges are drawn. A detailed description of the model is presented, and the technique to minimize an energy function is fully described. It has proved to be a very competitive and efficient algorithm, in terms of quality of solutions and computational time, when compared to the state-of-the-art heuristic methods specifically designed for this problem. Some simulation results are presented in this paper, to show the comparative efficiency of the methods. © Springer-Verlag Berlin Heidelberg 2007.












# Citation
Please, cite this work as:


<a name=bib-LopezRodriguez2007b></a>[[Lóp+07]](#cite-LopezRodriguez2007b) D. López-Rodríguez, E. Mérida-Casermeiro, J. Ortíz-de-Lazcano-Lobato, et al. “K-pages graph drawing with multivalued neural networks”. In: _Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)_. Vol. 4669 LNCS. PART 2. cited By 7; Conference of 17th International Conference on Artificial Neural Networks, ICANN 2007 ; Conference Date: 9 September 2007 Through 13 September 2007; Conference Code:70943. Porto: Springer Verlag, 2007, pp. 816-825. DOI: [10.1007/978-3-540-74695-9_84](https://doi.org/10.1007%2F978-3-540-74695-9_84). URL: [https://www.scopus.com/inward/record.uri?eid=2-s2.0-38149053100&doi=10.1007

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{LopezRodriguez2007b,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {D. López-Rodríguez and E. Mérida-Casermeiro and J.M. Ortíz-de-Lazcano-Lobato and G. Galán-Marín},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {K-pages graph drawing with multivalued neural networks},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2007},<br>&nbsp;&nbsp;&nbsp;&nbsp;  address = {Porto},<br>&nbsp;&nbsp;&nbsp;&nbsp;  note = {cited By 7; Conference of 17th International Conference on Artificial Neural Networks, ICANN 2007 ; Conference Date: 9 September 2007 Through 13 September 2007; Conference Code:70943},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number = {PART 2},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {816-825},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer Verlag},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {4669 LNCS},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {In this paper, the K-pages graph layout problem is solved by a new neural model. This model consists of two neural networks performing jointly in order to minimize the same energy function. The neural technique applied to this problem allows to reduce the energy function by changing outputs from both networks -outputs of first network representing location of nodes in the nodes line, while the outputs of the second one meaning the page where the edges are drawn. A detailed description of the model is presented, and the technique to minimize an energy function is fully described. It has proved to be a very competitive and efficient algorithm, in terms of quality of solutions and computational time, when compared to the state-of-the-art heuristic methods specifically designed for this problem. Some simulation results are presented in this paper, to show the comparative efficiency of the methods. © Springer-Verlag Berlin Heidelberg 2007.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  document_type = {Conference Paper},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/978-3-540-74695-9_84},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)},<br>&nbsp;&nbsp;&nbsp;&nbsp;  keywords = {Algorithms; Edge detection; Function evaluation; Graph theory; Heuristic methods; Mathematical models, Efficient algorithms; Energy functions; Multivalued neural networks; Neural models, Multilayer neural networks},<br>&nbsp;&nbsp;&nbsp;&nbsp;  source = {Scopus},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://www.scopus.com/inward/record.uri?eid=2-s2.0-38149053100&doi=10.1007%2f978-3-540-74695-9_84&partnerID=40&md5=7233c2564e713f2a8c63119b2fbc9ed9},<br>}

:::



# Bibliometric data

## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Herr_n_2020></a>[[1]](#cite-Herr_n_2020) A. Herrán, J. M. Colmenar, and A. Duarte. “An efficient metaheuristic for the <mml:math xmlns:mml="http://www.w3.org/1998/Math/MathML" display="inline" id="d1e6879" altimg="si262.svg"><mml:mi>K</mml:mi></mml:math>-page crossing number minimization problem”. In: _Knowledge-Based Systems_ 207 (Nov. 2020), p. 106352. ISSN: 0950-7051. DOI: [10.1016/j.knosys.2020.106352](https://doi.org/10.1016%2Fj.knosys.2020.106352). URL: [http://dx.doi.org/10.1016/j.knosys.2020.106352](http://dx.doi.org/10.1016/j.knosys.2020.106352).

<a name=bib-Klawitter_2018></a>[[2]](#cite-Klawitter_2018) J. Klawitter, T. Mchedlidze, and M. Nöllenburg. “Experimental Evaluation of Book Drawing Algorithms”. In: _Graph Drawing and Network Visualization_. Springer International Publishing, 2018, p. 224–238. ISBN: 9783319739151. DOI: [10.1007/978-3-319-73915-1_19](https://doi.org/10.1007%2F978-3-319-73915-1_19). URL: [http://dx.doi.org/10.1007/978-3-319-73915-1_19](http://dx.doi.org/10.1007/978-3-319-73915-1_19).

<a name=bib-L_pez_Rodr_guez_2009></a>[[3]](#cite-L_pez_Rodr_guez_2009) D. López-Rodríguez and E. Mérida-Casermeiro. “Shortest Common Superstring Problem with Discrete Neural Networks”. In: _Adaptive and Natural Computing Algorithms_. Springer Berlin Heidelberg, 2009, p. 62–71. ISBN: 9783642049217. DOI: [10.1007/978-3-642-04921-7_7](https://doi.org/10.1007%2F978-3-642-04921-7_7). URL: [http://dx.doi.org/10.1007/978-3-642-04921-7_7](http://dx.doi.org/10.1007/978-3-642-04921-7_7).

<a name=bib-Luque_2008></a>[[4]](#cite-Luque_2008) R. Luque, D. López-Rodríguez, E. Mérida-Casermeiro, et al. “Video Object Segmentation with Multivalued Neural Networks”. In: _2008 Eighth International Conference on Hybrid Intelligent Systems_. IEEE, Sep. 2008, p. 613–618. DOI: [10.1109/his.2008.130](https://doi.org/10.1109%2Fhis.2008.130). URL: [http://dx.doi.org/10.1109/his.2008.130](http://dx.doi.org/10.1109/his.2008.130).

<a name=bib-M_rida_Casermeiro_2008></a>[[5]](#cite-M_rida_Casermeiro_2008) E. Mérida-Casermeiro and D. López-Rodríguez. “Drawing Graphs in Parallel Lines with Artificial Neural Networks”. In: _2008 Eighth International Conference on Hybrid Intelligent Systems_. IEEE, Sep. 2008, p. 667–671. DOI: [10.1109/his.2008.89](https://doi.org/10.1109%2Fhis.2008.89). URL: [http://dx.doi.org/10.1109/his.2008.89](http://dx.doi.org/10.1109/his.2008.89).

<a name=bib-Nielsen_2021></a>[[6]](#cite-Nielsen_2021) S. S. Nielsen, M. Ostaszewski, F. McGee, et al. “Machine Learning to Support the Presentation of Complex Pathway Graphs”. In: _IEEE/ACM Transactions on Computational Biology and Bioinformatics_ 18.3 (May. 2021), p. 1130–1141. ISSN: 2374-0043. DOI: [10.1109/tcbb.2019.2938501](https://doi.org/10.1109%2Ftcbb.2019.2938501). URL: [http://dx.doi.org/10.1109/tcbb.2019.2938501](http://dx.doi.org/10.1109/tcbb.2019.2938501).

<a name=bib-Satsangi_2013></a>[[7]](#cite-Satsangi_2013) D. Satsangi, K. Srivastava, and G. Srivastava. “$$K$$ -page crossing number minimization problem: An evaluation of heuristics and its solution using GESAKP”. In: _Memetic Computing_ 5.4 (May. 2013), p. 255–274. ISSN: 1865-9292. DOI: [10.1007/s12293-013-0115-5](https://doi.org/10.1007%2Fs12293-013-0115-5). URL: [http://dx.doi.org/10.1007/s12293-013-0115-5](http://dx.doi.org/10.1007/s12293-013-0115-5).


