---
title: 'New journal paper: <em>Minimal Generators from Positive and Negative Attributes:
  Analysing the Knowledge Space of a Mathematics Course</em>'
author:
- Manuel Ojeda‐Hernández
- Francisco Pérez‐Gámez
- Domingo López-Rodríguez
- Nicolás Madrid
- Ángel Mora
date: '2022-08-09T00:00:00Z'
categories:
- Formal concept analysis
- Fuzzy logic
- E-learning
---

The work <u>Minimal Generators from Positive and Negative Attributes: Analysing the Knowledge Space of a Mathematics Course</u> has been published in <em><em>International Journal of Computational Intelligence Systems</em>, 15:58</em>.

<u>Abstract</u>:



Formal concept analysis is a data analysis framework based on lattice theory. In this paper, we analyse the use, inside this framework, of positive and negative (mixed) attributes of a dataset, which has proved to represent more information on the use of just positive attributes. From a theoretical point of view, in this paper we show the structure and the relationships between minimal generators of  the simple and mixed concept lattices. From a practical point of view, the obtained theoretical results allow us to ensure a greater granularity in the retrieved information. Furthermore, due to the relationship between FCA and Knowledge Space theory, on a practical level, we analyse the marks of a Mathematics course to establish the knowledge structure of the course and determine the key items providing new relevant information that is not evident without the use of the proposed tools.





For more details on this work, visit <a href='/publications/journals/2022-ijcis'>its own page</a>.
