---
title: On Modal Logic Association Rule Mining
author:
- Ionel Eduard Stan
- Guido Sciavicco
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
- Giovanni Pagliarini
- Mauro Milella
- Andrea Paradiso
date: '2022'
categories: uncategorised
slug: 2022/MoLoAsRuMi
details: Proceedings of the 23rd Italian Conference on Theoretical Computer Science,
  {ICTCS} 2022, Rome, Italy, September 7-9, 2022 , {CEUR} Workshop Proceedings vol.
  3284, pages 53--65.
---



# Abstract


The most iconic duality of machine learning models is symbolic learning versus functional learning. While functional learning is based on a numerical approach to knowledge extraction and modelling, the purpose of symbolic machine learning is to extract knowledge from data in such a form that it can be understood, discussed, modified, and applied by humans, as well as serve as the basis of artificial intelligence applications. The typical problems associated with machine learning are classification and rule extraction; while classification can be dealt with using both functional and symbolic learning, rule extraction is essentially symbolic. One element common to nearly all definitions and tools for rule extraction is that they are applied to static datasets and based on propositional logic; unfortunately, very often real-world applications give rise to non-static sets of data (e.g., temporal, spatial, graph-based data) and may require more-than-propositional expressive power. In order to extract association rules from non-static data, in this paper we propose a definition of modal association rules based on modal logic, and we study how a standard rule extraction algorithm such as APRIORI can be generalized to the modal case while keeping the properties of the canonical, non-modal case, namely, correctness and completeness.








# Citation
Please, cite this work as:


<a name=bib-Stan2022></a>[[Sta+22]](#cite-Stan2022) I. E. Stan, G. Sciavicco, E. Mu~noz-Velasco, et al. “On Modal Logic Association Rule Mining”. In: _Proceedings of the 23rd Italian Conference on Theoretical Computer Science, ICTCS 2022, Rome, Italy, September 7-9, 2022_. Ed. by U. D. Lago and D. Gorla. Vol. 3284. CEUR Workshop Proceedings. CEUR-WS.org, 2022, pp. 53-65. URL: [https://ceur-ws.org/Vol-3284/492.pdf](https://ceur-ws.org/Vol-3284/492.pdf).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Stan2022,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Ionel Eduard Stan and Guido Sciavicco and Emilio Mu~noz-Velasco and Giovanni Pagliarini and Mauro Milella and Andrea Paradiso},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Proceedings of the 23rd Italian Conference on Theoretical Computer Science, {ICTCS} 2022, Rome, Italy, September 7-9, 2022},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {On Modal Logic Association Rule Mining},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2022},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Ugo Dal Lago and Daniele Gorla},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {53--65},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {CEUR-WS.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {{CEUR} Workshop Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {3284},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {The most iconic duality of machine learning models is symbolic learning versus functional learning. While functional learning is based on a numerical approach to knowledge extraction and modelling, the purpose of symbolic machine learning is to extract knowledge from data in such a form that it can be understood, discussed, modified, and applied by humans, as well as serve as the basis of artificial intelligence applications. The typical problems associated with machine learning are classification and rule extraction; while classification can be dealt with using both functional and symbolic learning, rule extraction is essentially symbolic. One element common to nearly all definitions and tools for rule extraction is that they are applied to static datasets and based on propositional logic; unfortunately, very often real-world applications give rise to non-static sets of data (e.g., temporal, spatial, graph-based data) and may require more-than-propositional expressive power. In order to extract association rules from non-static data, in this paper we propose a definition of modal association rules based on modal logic, and we study how a standard rule extraction algorithm such as APRIORI can be generalized to the modal case while keeping the properties of the canonical, non-modal case, namely, correctness and completeness.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/ictcs/StanSMPMP22.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 10 Mar 2023 16:23:17 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://ceur-ws.org/Vol-3284/492.pdf},<br>}

:::








