---
title: Systems of implications obtained using the Carve decomposition of a formal
  context
author:
- <a href='/people/staff/dominlopez/' style='color:rgb(100,0,50);'>Domingo López Rodríguez</a>
- <a href='/people/staff/manuojeda/' style='color:rgb(100,0,50);'>Manuel Ojeda Hernández</a>
- Tim Pattison
date: '2025-04-19'
categories:
- Formal concept analysis
- Implications
slug: 2025/SyImObUsCaDeFoCo
details: Knowledge-Based Systems  , pages 113475.
doi: 10.1016/j.knosys.2025.113475
keywords: Formal concept analysis, Implicational systems, Attribute implications,
  Divide-and-conquer algorithms, Knowledge representation
project: 2023-valid
listing:
- id: funding
  contents: funding.yml
  type: default
  sort: date desc
---



# Abstract


The Carve algorithm uses a divide-and-conquer strategy to compute the concept lattice of a formal context. The decomposition phase of the Carve algorithm discovers hierarchical structure in an amenable formal context, which the synthesis phase then exploits to construct the concept lattice from those of the component sub-contexts. In this paper, the problem of computing a sound and complete set of attribute implications via a refinement of the Carve decomposition is studied. Indeed, a set of rules is devised to obtain a set of valid implications which is proved to be complete. The refined decomposition and these rules are implemented in the novel Carve+ algorithm, whose runtime compares favourably with direct computation of the Duquenne–Guigues base of implications via the NextClosure algorithm.



# Funding
::: {.callout-note appearance='minimal' collapse=false}
## Projects funding this work

:::{#funding}
:::
:::






# Citation
Please, cite this work as:


<a name=bib-LOPEZRODRIGUEZ2025113475></a>[[LOP25]](#cite-LOPEZRODRIGUEZ2025113475) D. López-Rodríguez, M. Ojeda-Hernández, and T. Pattison. “Systems of implications obtained using the Carve decomposition of a formal context”. In: _Knowledge-Based Systems_ (2025), p. 113475. ISSN: 0950-7051. DOI: [https://doi.org/10.1016/j.knosys.2025.113475](https://doi.org/https%3A%2F%2Fdoi.org%2F10.1016%2Fj.knosys.2025.113475). URL: [https://www.sciencedirect.com/science/article/pii/S0950705125005210](https://www.sciencedirect.com/science/article/pii/S0950705125005210).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{LOPEZRODRIGUEZ2025113475,<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Systems of implications obtained using the Carve decomposition of a formal context},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Knowledge-Based Systems},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {113475},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2025},<br>&nbsp;&nbsp;&nbsp;&nbsp;  issn = {0950-7051},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {https://doi.org/10.1016/j.knosys.2025.113475},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://www.sciencedirect.com/science/article/pii/S0950705125005210},<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Domingo L{\a'o}pez-Rodr{\a'\i}guez and Manuel Ojeda-Hern{\a'a}ndez and Tim Pattison},<br>&nbsp;&nbsp;&nbsp;&nbsp;  keywords = {Formal concept analysis, Implicational systems, Attribute implications, Divide-and-conquer algorithms, Knowledge representation},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {The Carve algorithm uses a divide-and-conquer strategy to compute the concept lattice of a formal context. The decomposition phase of the Carve algorithm discovers hierarchical structure in an amenable formal context, which the synthesis phase then exploits to construct the concept lattice from those of the component sub-contexts. In this paper, the problem of computing a sound and complete set of attribute implications via a refinement of the Carve decomposition is studied. Indeed, a set of rules is devised to obtain a set of valid implications which is proved to be complete. The refined decomposition and these rules are implemented in the novel Carve+ algorithm, whose runtime compares favourably with direct computation of the Duquenne–Guigues base of implications via the NextClosure algorithm.},<br>}

:::








