---
title: On fuzzy relations, adjunctions, and functional fuzzy relations
author:
- <a href='/people/staff/ipcabrera/' style='color:rgb(100,0,50);'>Inma P. Cabrera</a>
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '2016'
categories: uncategorised
slug: 2016/FuFuFuRe
details: 2016 {IEEE} Symposium Series on Computational Intelligence, {SSCI} 2016,
  Athens, Greece, December 6-9, 2016 , pages 1--7.
doi: 10.1109/SSCI.2016.7850149
---



# Abstract


The problem of studying when a given a fuzzy relation can be characterized in terms of a fuzzy function is revisited. Although several authors have published works on the `functionality' of a fuzzy relation, we focus on a particular version which, to the best of our knowledge, fits better for the definition of adjunction between generalized fuzzy structures.








# Citation
Please, cite this work as:


<a name=bib-Cabrera2016a></a>[[CCO16]](#cite-Cabrera2016a) I. P. Cabrera, P. Cordero, and M. Ojeda-Aciego. “On fuzzy relations, adjunctions, and functional fuzzy relations”. In: _2016 IEEE Symposium Series on Computational Intelligence, SSCI 2016, Athens, Greece, December 6-9, 2016_. IEEE, 2016, pp. 1-7. DOI: [10.1109/SSCI.2016.7850149](https://doi.org/10.1109%2FSSCI.2016.7850149). URL: [https://doi.org/10.1109/SSCI.2016.7850149](https://doi.org/10.1109/SSCI.2016.7850149).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Cabrera2016a,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Inma P. Cabrera and Pablo Cordero and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {2016 {IEEE} Symposium Series on Computational Intelligence, {SSCI} 2016, Athens, Greece, December 6-9, 2016},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {On fuzzy relations, adjunctions, and functional fuzzy relations},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2016},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {1--7},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {{IEEE}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/ssci/CabreraCO16.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1109/SSCI.2016.7850149},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Wed, 16 Oct 2019 14:14:56 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1109/SSCI.2016.7850149},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1109/SSCI.2016.7850149" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1109/SSCI.2016.7850149" class="plumx-details" data-site="plum" data-hide-when-empty="true">On fuzzy relations, adjunctions, and functional fuzzy relations</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1109/SSCI.2016.7850149"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Cabrera_2017></a>[[1]](#cite-Cabrera_2017) I. P. Cabrera, P. Cordero, and M. Ojeda-Aciego. “Towards relational fuzzy adjunctions”. In: _2017 IEEE International Conference on Fuzzy Systems (FUZZ-IEEE)_. IEEE, Jul. 2017, p. 1–5. DOI: [10.1109/fuzz-ieee.2017.8015677](https://doi.org/10.1109%2Ffuzz-ieee.2017.8015677). URL: [http://dx.doi.org/10.1109/fuzz-ieee.2017.8015677](http://dx.doi.org/10.1109/fuzz-ieee.2017.8015677).

<a name=bib-Cabrera_20171></a>[[2]](#cite-Cabrera_20171) I. Cabrera, P. Cordero, and M. Ojeda-Aciego. “Galois connections in computational intelligence: A short survey”. In: _2017 IEEE Symposium Series on Computational Intelligence (SSCI)_. IEEE, Nov. 2017, p. 1–7. DOI: [10.1109/ssci.2017.8285310](https://doi.org/10.1109%2Fssci.2017.8285310). URL: [http://dx.doi.org/10.1109/ssci.2017.8285310](http://dx.doi.org/10.1109/ssci.2017.8285310).

