---
title: T-norms and t-conorms on a family of lattices
author: <a href='/people/staff/cbejines/' style='color:rgb(100,0,50);'>Carlos Bejines</a>
date: '2022'
categories: uncategorised
slug: 2022/FaLa
details: Fuzzy Sets Syst. vol. 439 , pages 55--74.
doi: 10.1016/J.FSS.2021.05.008
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Bejines2022></a>[[Bej22]](#cite-Bejines2022) C. Bejines. “T-norms and t-conorms on a family of lattices”. In: _Fuzzy Sets Syst._ 439 (2022), pp. 55-74. DOI: [10.1016/J.FSS.2021.05.008](https://doi.org/10.1016%2FJ.FSS.2021.05.008). URL: [https://doi.org/10.1016/j.fss.2021.05.008](https://doi.org/10.1016/j.fss.2021.05.008).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{Bejines2022,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Carlos Bejines},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Fuzzy Sets Syst.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {T-norms and t-conorms on a family of lattices},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2022},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {55--74},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {439},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/fss/Bejines22.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1016/J.FSS.2021.05.008},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Wed, 18 May 2022 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1016/j.fss.2021.05.008},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1016/J.FSS.2021.05.008" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1016/J.FSS.2021.05.008" class="plumx-details" data-site="plum" data-hide-when-empty="true">T-norms and t-conorms on a family of lattices</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1016/J.FSS.2021.05.008"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Bejines_2023></a>[[1]](#cite-Bejines_2023) C. Bejines and M. Ojeda-Hernández. “Counting semicopulas on finite structures”. In: _Fuzzy Sets and Systems_ 462 (Jun. 2023), p. 108405. ISSN: 0165-0114. DOI: [10.1016/j.fss.2022.09.011](https://doi.org/10.1016%2Fj.fss.2022.09.011). URL: [http://dx.doi.org/10.1016/j.fss.2022.09.011](http://dx.doi.org/10.1016/j.fss.2022.09.011).

<a name=bib-Munar_Covas_2023></a>[[2]](#cite-Munar_Covas_2023) M. Munar-Covas, S. Massanet, and D. Ruiz-Aguilera. “Why are Discrete Implications Necessary? An Analysis Through the Discretization Process”. In: _IEEE Transactions on Fuzzy Systems_ 31.5 (May. 2023), p. 1484–1496. ISSN: 1941-0034. DOI: [10.1109/tfuzz.2022.3204450](https://doi.org/10.1109%2Ftfuzz.2022.3204450). URL: [http://dx.doi.org/10.1109/tfuzz.2022.3204450](http://dx.doi.org/10.1109/tfuzz.2022.3204450).

<a name=bib-Munar_2024></a>[[3]](#cite-Munar_2024) M. Munar, M. Couceiro, S. Massanet, et al. “A survey on the enumeration of classes of logical connectives and aggregation functions defined on a finite chain, with new results”. In: _Fuzzy Sets and Systems_ 490 (Aug. 2024), p. 109023. ISSN: 0165-0114. DOI: [10.1016/j.fss.2024.109023](https://doi.org/10.1016%2Fj.fss.2024.109023). URL: [http://dx.doi.org/10.1016/j.fss.2024.109023](http://dx.doi.org/10.1016/j.fss.2024.109023).

<a name=bib-Munar_2023></a>[[4]](#cite-Munar_2023) M. Munar, S. Massanet, and D. Ruiz-Aguilera. “On the cardinality of some families of discrete connectives”. In: _Information Sciences_ 621 (Apr. 2023), p. 708–728. ISSN: 0020-0255. DOI: [10.1016/j.ins.2022.10.121](https://doi.org/10.1016%2Fj.ins.2022.10.121). URL: [http://dx.doi.org/10.1016/j.ins.2022.10.121](http://dx.doi.org/10.1016/j.ins.2022.10.121).

