---
title: A Generalized Framework to Consider Positive and Negative Attributes in Formal
  Concept Analysis
author:
- José Manuel Rodríguez-Jiménez
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/enciso/' style='color:rgb(100,0,50);'>Manuel Enciso</a>
- <a href='/people/staff/amora/' style='color:rgb(100,0,50);'>Ángel Mora</a>
date: '2014'
categories: uncategorised
slug: 2014/GeFrCoPoNeAtFoCoAn
details: Proceedings of the Eleventh International Conference on Concept Lattices
  and Their Applications, Ko{\v{s}}ice, Slovakia, October 7-10, 2014 , {CEUR} Workshop
  Proceedings vol. 1252, pages 267--278.
---



# Abstract


In Formal Concept Analysis the classical formal context is analized taking into account only the positive information, i.e. the presence of a property in an object. Nevertheless, the non presence of a property in an object also provides a significant knowledge which can only be partially considered with the classical approach. In this work we have modified the derivation operators to allow the treatment of both, positive and negative attributes which come from respectively, the presence and absence of the properties. In this work we define the new operators and we prove that they are a Galois connection. Finally, we have also studied the correspondence between the formal context in the new framework and the extended concept lattice, providing new interesting properties








# Citation
Please, cite this work as:


<a name=bib-RodriguezJimenez2014></a>[[Rod+14]](#cite-RodriguezJimenez2014) J. M. Rodr\'\iguez-Jiménez, P. Cordero, M. Enciso, et al. “A Generalized Framework to Consider Positive and Negative Attributes in Formal Concept Analysis”. In: _Proceedings of the Eleventh International Conference on Concept Lattices and Their Applications, Košice, Slovakia, October 7-10, 2014_. Ed. by K. Bertet and S. Rudolph. Vol. 1252. CEUR Workshop Proceedings. CEUR-WS.org, 2014, pp. 267-278. URL: [https://ceur-ws.org/Vol-1252/cla2014\_submission\_33.pdf](https://ceur-ws.org/Vol-1252/cla2014\_submission\_33.pdf).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{RodriguezJimenez2014,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Jos{\a'e} Manuel Rodr\'\iguez-Jim{\a'e}nez and Pablo Cordero and Manuel Enciso and {\a'A}ngel Mora},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Proceedings of the Eleventh International Conference on Concept Lattices and Their Applications, Ko{\v{s}}ice, Slovakia, October 7-10, 2014},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {A Generalized Framework to Consider Positive and Negative Attributes in Formal Concept Analysis},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2014},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Karell Bertet and Sebastian Rudolph},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {267--278},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {CEUR-WS.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {{CEUR} Workshop Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {1252},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {In Formal Concept Analysis the classical formal context is analized taking into account only the positive information, i.e. the presence of a property in an object. Nevertheless, the non presence of a property in an object also provides a significant knowledge which can only be partially considered with the classical approach. In this work we have modified the derivation operators to allow the treatment of both, positive and negative attributes which come from respectively, the presence and absence of the properties. In this work we define the new operators and we prove that they are a Galois connection. Finally, we have also studied the correspondence between the formal context in the new framework and the extended concept lattice, providing new interesting properties},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/cla/Rodriguez-JimenezCEM14.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 10 Mar 2023 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://ceur-ws.org/Vol-1252/cla2014\_submission\_33.pdf},<br>}

:::








