---
title: 'Conference paper accepted: <em>Red Multivaluada Estocástica para Optimización.
  Aplicación al Problema del MaxCut</em>'
author: Domingo López-Rodríguez, Enrique Mérida-Casermeiro, Juan Miguel Ortiz de Lazcano
  Lobato
date: '2007-07-01'
categories:
- Combinatorial optimization
- Neural networks
comments:
  giscus:
    repo: quarto-dev/quarto-docs
---

The work <u>Red Multivaluada Estocástica para Optimización. Aplicación al Problema del MaxCut</u> has been published in <em><em>Congreso Español sobre Metaheurísticas, Algoritmos Evolutivos y Bioinspirados 2007</em></em>.

<u>Abstract</u>:



El ob jetivo de este trabajo es presentar la versión estocástica del modelo neuronal multivaluado MREM, el cual ha conseguido muy buenos resultados en muchas aplicaciones, como técnica de optimización. El propósito de esta versión estocástica es el de evitar ciertos mínimos locales de la función objetivo minimizada por la red, esto es, la función de energía. Con este fin, describimos las bases teóricas de este nuevo modelo, que nos garantizan la convergencia de la red a un mínimo local, de una forma rigurosa. Para mostrar la eficiencia de esta versión, el modelo, en ambas versiones, determinista y estocástica, ha sido aplicado para resolver el ya conocido problema de la partición de un grafo, MaxCut. Los experimentos computacionales llevados a cabo nos muestran que el modelo estocástico obtiene mejores resultados que el determinista.




For more details on this work, visit <a href='/publications/conferences/2007-maeb'>its own page</a>.
