---
title: 'Similarity-based unification: a multi-adjoint approach'
author:
- Jesús Medina
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
- Peter Vojtás
date: '2004'
categories: uncategorised
slug: 2004/Ap
details: Fuzzy Sets Syst. vol. 146 (1), pages 43--62.
doi: 10.1016/J.FSS.2003.11.005
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Medina2004></a>[[MOV04]](#cite-Medina2004) J. Medina, M. Ojeda-Aciego, and P. Vojtás. “Similarity-based unification: a multi-adjoint approach”. In: _Fuzzy Sets Syst._ 146.1 (2004), pp. 43-62. DOI: [10.1016/J.FSS.2003.11.005](https://doi.org/10.1016%2FJ.FSS.2003.11.005). URL: [https://doi.org/10.1016/j.fss.2003.11.005](https://doi.org/10.1016/j.fss.2003.11.005).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{Medina2004,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Jes{\a'u}s Medina and Manuel Ojeda-Aciego and Peter Vojt{\a'a}s},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Fuzzy Sets Syst.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Similarity-based unification: a multi-adjoint approach},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2004},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number = {1},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {43--62},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {146},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/fss/MedinaOV04.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1016/J.FSS.2003.11.005},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Thu, 07 Jan 2021 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1016/j.fss.2003.11.005},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1016/J.FSS.2003.11.005" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1016/J.FSS.2003.11.005" class="plumx-details" data-site="plum" data-hide-when-empty="true">Similarity-based unification: a multi-adjoint approach</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1016/J.FSS.2003.11.005"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Antoni_2014></a>[[1]](#cite-Antoni_2014) L. Antoni, S. Krajči, O. Krídlo, et al. “On heterogeneous formal contexts”. In: _Fuzzy Sets and Systems_ 234 (Jan. 2014), p. 22–33. ISSN: 0165-0114. DOI: [10.1016/j.fss.2013.04.008](https://doi.org/10.1016%2Fj.fss.2013.04.008). URL: [http://dx.doi.org/10.1016/j.fss.2013.04.008](http://dx.doi.org/10.1016/j.fss.2013.04.008).

<a name=bib-Cornejo_2017></a>[[2]](#cite-Cornejo_2017) M. E. Cornejo, J. C. Díaz-Moreno, and J. Medina. “Multi-adjoint Relation Equations: A Decision Support System for Fuzzy Logic: MULTI-ADJOINT RELATION EQUATIONS”. In: _International Journal of Intelligent Systems_ 32.8 (Mar. 2017), p. 778–800. ISSN: 0884-8173. DOI: [10.1002/int.21889](https://doi.org/10.1002%2Fint.21889). URL: [http://dx.doi.org/10.1002/int.21889](http://dx.doi.org/10.1002/int.21889).

<a name=bib-Cornejo_2021></a>[[3]](#cite-Cornejo_2021) M. E. Cornejo, J. Medina, and E. Ramírez-Poussa. “Algebraic structure and characterization of adjoint triples”. In: _Fuzzy Sets and Systems_ 425 (Nov. 2021), p. 117–139. ISSN: 0165-0114. DOI: [10.1016/j.fss.2021.02.002](https://doi.org/10.1016%2Fj.fss.2021.02.002). URL: [http://dx.doi.org/10.1016/j.fss.2021.02.002](http://dx.doi.org/10.1016/j.fss.2021.02.002).

<a name=bib-Cornejo_2015></a>[[4]](#cite-Cornejo_2015) M. E. Cornejo, J. Medina, and E. Ramírez-Poussa. “Multi-adjoint algebras versus non-commutative residuated structures”. In: _International Journal of Approximate Reasoning_ 66 (Nov. 2015), p. 119–138. ISSN: 0888-613X. DOI: [10.1016/j.ijar.2015.08.003](https://doi.org/10.1016%2Fj.ijar.2015.08.003). URL: [http://dx.doi.org/10.1016/j.ijar.2015.08.003](http://dx.doi.org/10.1016/j.ijar.2015.08.003).

<a name=bib-Eugenia_Cornejo_2013></a>[[5]](#cite-Eugenia_Cornejo_2013) M. Eugenia Cornejo, J. Medina, and E. Ramírez. “A comparative study of adjoint triples”. In: _Fuzzy Sets and Systems_ 211 (Jan. 2013), p. 1–14. ISSN: 0165-0114. DOI: [10.1016/j.fss.2012.05.004](https://doi.org/10.1016%2Fj.fss.2012.05.004). URL: [http://dx.doi.org/10.1016/j.fss.2012.05.004](http://dx.doi.org/10.1016/j.fss.2012.05.004).

<a name=bib-Juli_n_Iranzo_2015></a>[[6]](#cite-Juli_n_Iranzo_2015) P. Julián-Iranzo, G. Moreno, J. Penabad, et al. “A Fuzzy Logic Programming Environment for Managing Similarity and Truth Degrees”. In: _Electronic Proceedings in Theoretical Computer Science_ 173 (Jan. 2015), p. 71–86. ISSN: 2075-2180. DOI: [10.4204/eptcs.173.6](https://doi.org/10.4204%2Feptcs.173.6). URL: [http://dx.doi.org/10.4204/eptcs.173.6](http://dx.doi.org/10.4204/eptcs.173.6).

<a name=bib-Juli_n_Iranzo_2017></a>[[7]](#cite-Juli_n_Iranzo_2017) P. Julián-Iranzo and C. Rubio-Manzano. “A sound and complete semantics for a similarity-based logic programming language”. In: _Fuzzy Sets and Systems_ 317 (Jun. 2017), p. 1–26. ISSN: 0165-0114. DOI: [10.1016/j.fss.2016.12.016](https://doi.org/10.1016%2Fj.fss.2016.12.016). URL: [http://dx.doi.org/10.1016/j.fss.2016.12.016](http://dx.doi.org/10.1016/j.fss.2016.12.016).

<a name=bib-Juli_n_Iranzo_20151></a>[[8]](#cite-Juli_n_Iranzo_20151) P. Julián-Iranzo and C. Rubio-Manzano. “Proximity-based unification theory”. In: _Fuzzy Sets and Systems_ 262 (Mar. 2015), p. 21–43. ISSN: 0165-0114. DOI: [10.1016/j.fss.2014.07.006](https://doi.org/10.1016%2Fj.fss.2014.07.006). URL: [http://dx.doi.org/10.1016/j.fss.2014.07.006](http://dx.doi.org/10.1016/j.fss.2014.07.006).

<a name=bib-Juli_n_Iranzo_2009></a>[[9]](#cite-Juli_n_Iranzo_2009) P. Julián-Iranzo, C. Rubio-Manzano, and J. Gallardo-Casero. “Bousi~Prolog: a Prolog Extension Language for Flexible Query Answering”. In: _Electronic Notes in Theoretical Computer Science_ 248 (Aug. 2009), p. 131–147. ISSN: 1571-0661. DOI: [10.1016/j.entcs.2009.07.064](https://doi.org/10.1016%2Fj.entcs.2009.07.064). URL: [http://dx.doi.org/10.1016/j.entcs.2009.07.064](http://dx.doi.org/10.1016/j.entcs.2009.07.064).

<a name=bib-Juli_n_2005></a>[[10]](#cite-Juli_n_2005) P. Julián, G. Moreno, and J. Penabad. “On fuzzy unfolding: A multi-adjoint approach”. In: _Fuzzy Sets and Systems_ 154.1 (Aug. 2005), p. 16–33. ISSN: 0165-0114. DOI: [10.1016/j.fss.2005.03.013](https://doi.org/10.1016%2Fj.fss.2005.03.013). URL: [http://dx.doi.org/10.1016/j.fss.2005.03.013](http://dx.doi.org/10.1016/j.fss.2005.03.013).

<a name=bib-Konecny_2014></a>[[11]](#cite-Konecny_2014) J. Konecny, J. Medina, and M. Ojeda-Aciego. “Multi-adjoint concept lattices with heterogeneous conjunctors and hedges”. In: _Annals of Mathematics and Artificial Intelligence_ 72.1–2 (Mar. 2014), p. 73–89. ISSN: 1573-7470. DOI: [10.1007/s10472-014-9405-y](https://doi.org/10.1007%2Fs10472-014-9405-y). URL: [http://dx.doi.org/10.1007/s10472-014-9405-y](http://dx.doi.org/10.1007/s10472-014-9405-y).

<a name=bib-LE_2009></a>[[12]](#cite-LE_2009) V. H. LE, F. LIU, and D. K. TRAN. “Fuzzy linguistic logic programming and its applications”. In: _Theory and Practice of Logic Programming_ 9.3 (May. 2009), p. 309–341. ISSN: 1475-3081. DOI: [10.1017/s1471068409003779](https://doi.org/10.1017%2Fs1471068409003779). URL: [http://dx.doi.org/10.1017/s1471068409003779](http://dx.doi.org/10.1017/s1471068409003779).

<a name=bib-Madrid_2011></a>[[13]](#cite-Madrid_2011) N. Madrid and M. Ojeda-Aciego. “Measuring Inconsistency in Fuzzy Answer Set Semantics”. In: _IEEE Transactions on Fuzzy Systems_ 19.4 (Aug. 2011), p. 605–622. ISSN: 1941-0034. DOI: [10.1109/tfuzz.2011.2114669](https://doi.org/10.1109%2Ftfuzz.2011.2114669). URL: [http://dx.doi.org/10.1109/tfuzz.2011.2114669](http://dx.doi.org/10.1109/tfuzz.2011.2114669).

<a name=bib-Madrid_2008></a>[[14]](#cite-Madrid_2008) N. Madrid and M. Ojeda-Aciego. “Towards a Fuzzy Answer Set Semantics for Residuated Logic Programs”. In: _2008 IEEE/WIC/ACM International Conference on Web Intelligence and Intelligent Agent Technology_. IEEE, Dec. 2008, p. 260–264. DOI: [10.1109/wiiat.2008.357](https://doi.org/10.1109%2Fwiiat.2008.357). URL: [http://dx.doi.org/10.1109/wiiat.2008.357](http://dx.doi.org/10.1109/wiiat.2008.357).

<a name=bib-Medina_2012></a>[[15]](#cite-Medina_2012) J. Medina. “Multi-adjoint property-oriented and object-oriented concept lattices”. In: _Information Sciences_ 190 (May. 2012), p. 95–106. ISSN: 0020-0255. DOI: [10.1016/j.ins.2011.11.016](https://doi.org/10.1016%2Fj.ins.2011.11.016). URL: [http://dx.doi.org/10.1016/j.ins.2011.11.016](http://dx.doi.org/10.1016/j.ins.2011.11.016).

<a name=bib-Medina_2013></a>[[16]](#cite-Medina_2013) J. Medina and M. Ojeda-Aciego. “Dual multi-adjoint concept lattices”. In: _Information Sciences_ 225 (Mar. 2013), p. 47–54. ISSN: 0020-0255. DOI: [10.1016/j.ins.2012.10.030](https://doi.org/10.1016%2Fj.ins.2012.10.030). URL: [http://dx.doi.org/10.1016/j.ins.2012.10.030](http://dx.doi.org/10.1016/j.ins.2012.10.030).

<a name=bib-Medina_2010></a>[[17]](#cite-Medina_2010) J. Medina and M. Ojeda-Aciego. “Multi-adjoint t-concept lattices”. In: _Information Sciences_ 180.5 (Mar. 2010), p. 712–725. ISSN: 0020-0255. DOI: [10.1016/j.ins.2009.11.018](https://doi.org/10.1016%2Fj.ins.2009.11.018). URL: [http://dx.doi.org/10.1016/j.ins.2009.11.018](http://dx.doi.org/10.1016/j.ins.2009.11.018).

<a name=bib-Medina_2009></a>[[18]](#cite-Medina_2009) J. Medina, M. Ojeda-Aciego, and J. Ruiz-Calviño. “Formal concept analysis via multi-adjoint concept lattices”. In: _Fuzzy Sets and Systems_ 160.2 (Jan. 2009), p. 130–144. ISSN: 0165-0114. DOI: [10.1016/j.fss.2008.05.004](https://doi.org/10.1016%2Fj.fss.2008.05.004). URL: [http://dx.doi.org/10.1016/j.fss.2008.05.004](http://dx.doi.org/10.1016/j.fss.2008.05.004).

<a name=bib-Medina_2024></a>[[19]](#cite-Medina_2024) J. Medina and J. A. Torné-Zambrano. “Preference in Multi-adjoint Logic Programming Based on Ordered Adjoint Pairs”. In: _Computational Intelligence and Mathematics for Tackling Complex Problems 5_. Springer Nature Switzerland, 2024, p. 93–99. ISBN: 9783031469794. DOI: [10.1007/978-3-031-46979-4_13](https://doi.org/10.1007%2F978-3-031-46979-4_13). URL: [http://dx.doi.org/10.1007/978-3-031-46979-4_13](http://dx.doi.org/10.1007/978-3-031-46979-4_13).

<a name=bib-Morcillo_2008></a>[[20]](#cite-Morcillo_2008) P. J. Morcillo and G. Moreno. “Programming with Fuzzy Logic Rules by Using the FLOPER Tool”. In: _Rule Representation, Interchange and Reasoning on the Web_. Springer Berlin Heidelberg, 2008, p. 119–126. ISBN: 9783540888086. DOI: [10.1007/978-3-540-88808-6_14](https://doi.org/10.1007%2F978-3-540-88808-6_14). URL: [http://dx.doi.org/10.1007/978-3-540-88808-6_14](http://dx.doi.org/10.1007/978-3-540-88808-6_14).

<a name=bib-Morcillo_2010></a>[[21]](#cite-Morcillo_2010) P. J. Morcillo, G. Moreno, J. Penabad, et al. “A Practical Management of Fuzzy Truth-Degrees Using FLOPER”. In: _Semantic Web Rules_. Springer Berlin Heidelberg, 2010, p. 20–34. ISBN: 9783642162893. DOI: [10.1007/978-3-642-16289-3_4](https://doi.org/10.1007%2F978-3-642-16289-3_4). URL: [http://dx.doi.org/10.1007/978-3-642-16289-3_4](http://dx.doi.org/10.1007/978-3-642-16289-3_4).

<a name=bib-Moreno_2014></a>[[22]](#cite-Moreno_2014) G. Moreno and C. Vázquez. “Fuzzy Logic Programming in Action with &amp;lt;i&amp;gt;FLOPER&amp;lt;/i&amp;gt;”. In: _Journal of Software Engineering and Applications_ 07.04 (2014), p. 273–298. ISSN: 1945-3124. DOI: [10.4236/jsea.2014.74028](https://doi.org/10.4236%2Fjsea.2014.74028). URL: [http://dx.doi.org/10.4236/jsea.2014.74028](http://dx.doi.org/10.4236/jsea.2014.74028).

<a name=bib-Munoz_Hernandez_2011></a>[[23]](#cite-Munoz_Hernandez_2011) S. Munoz-Hernandez, V. Pablos-Ceruelo, and H. Strass. “RFuzzy: Syntax, semantics and implementation details of a simple and expressive fuzzy tool over Prolog”. In: _Information Sciences_ 181.10 (May. 2011), p. 1951–1970. ISSN: 0020-0255. DOI: [10.1016/j.ins.2010.07.033](https://doi.org/10.1016%2Fj.ins.2010.07.033). URL: [http://dx.doi.org/10.1016/j.ins.2010.07.033](http://dx.doi.org/10.1016/j.ins.2010.07.033).

<a name=bib-Schockaert_2013></a>[[24]](#cite-Schockaert_2013) S. Schockaert and H. Prade. “Interpolative and extrapolative reasoning in propositional theories using qualitative knowledge about conceptual spaces”. In: _Artificial Intelligence_ 202 (Sep. 2013), p. 86–131. ISSN: 0004-3702. DOI: [10.1016/j.artint.2013.07.001](https://doi.org/10.1016%2Fj.artint.2013.07.001). URL: [http://dx.doi.org/10.1016/j.artint.2013.07.001](http://dx.doi.org/10.1016/j.artint.2013.07.001).

<a name=bib-Straccia_2008></a>[[25]](#cite-Straccia_2008) U. Straccia. “Managing Uncertainty and Vagueness in Description Logics, Logic Programs and Description Logic Programs”. In: _Reasoning Web_. Springer Berlin Heidelberg, 2008, p. 54–103. ISBN: 9783540856580. DOI: [10.1007/978-3-540-85658-0_2](https://doi.org/10.1007%2F978-3-540-85658-0_2). URL: [http://dx.doi.org/10.1007/978-3-540-85658-0_2](http://dx.doi.org/10.1007/978-3-540-85658-0_2).

