---
title: A Normal Form for Fuzzy Functional Dependencies
author:
- José Manuel Rodríguez-Jiménez
- Estrella Rodríguez Lorenzo
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/enciso/' style='color:rgb(100,0,50);'>Manuel Enciso</a>
- <a href='/people/staff/amora/' style='color:rgb(100,0,50);'>Ángel Mora</a>
date: '2015'
categories: uncategorised
slug: 2015/NoFoFuFuDe
details: '{IEEE} Symposium Series on Computational Intelligence, {SSCI} 2015, Cape
  Town, South Africa, December 7-10, 2015 , pages 984--989.'
doi: 10.1109/SSCI.2015.143
---



# Abstract


A fuzzy extension of the classical functional dependency is shown which associates a degree not only to the attributes but also to the functional dependency, providing the maximum level of uncertainty in tables. For this proposal the kernel is the use of Simplification Logic for these fuzzy functional dependencies, which ensures a solid and efficient approach to manage them in the fuzzy extension considered. An algorithm to compute closures for this fuzzy functional dependencies is outlined and a normal form for fuzzy functional dependencies named direct-optimal basis is proposed.








# Citation
Please, cite this work as:


<a name=bib-RodriguezJimenez2015></a>[[Rod+15]](#cite-RodriguezJimenez2015) J. M. Rodr\'\iguez-Jiménez, E. Rodr\'\iguezLorenzo, P. Cordero, et al. “A Normal Form for Fuzzy Functional Dependencies”. In: _IEEE Symposium Series on Computational Intelligence, SSCI 2015, Cape Town, South Africa, December 7-10, 2015_. IEEE, 2015, pp. 984-989. DOI: [10.1109/SSCI.2015.143](https://doi.org/10.1109%2FSSCI.2015.143). URL: [https://doi.org/10.1109/SSCI.2015.143](https://doi.org/10.1109/SSCI.2015.143).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{RodriguezJimenez2015,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Jos{\a'e} Manuel Rodr\'\iguez-Jim{\a'e}nez and Estrella Rodr\'\iguez Lorenzo and Pablo Cordero and Manuel Enciso and {\a'A}ngel Mora},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {{IEEE} Symposium Series on Computational Intelligence, {SSCI} 2015, Cape Town, South Africa, December 7-10, 2015},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {A Normal Form for Fuzzy Functional Dependencies},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2015},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {984--989},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {{IEEE}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/ssci/Rodriguez-Jimenez15.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1109/SSCI.2015.143},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 23 Sep 2022 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1109/SSCI.2015.143},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1109/SSCI.2015.143" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1109/SSCI.2015.143" class="plumx-details" data-site="plum" data-hide-when-empty="true">A Normal Form for Fuzzy Functional Dependencies</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1109/SSCI.2015.143"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Rodr_guez_Lorenzo_2017></a>[[1]](#cite-Rodr_guez_Lorenzo_2017) E. Rodríguez-Lorenzo, P. Cordero, M. Enciso, et al. “Canonical dichotomous direct bases”. In: _Information Sciences_ 376 (Jan. 2017), p. 39–53. ISSN: 0020-0255. DOI: [10.1016/j.ins.2016.10.004](https://doi.org/10.1016%2Fj.ins.2016.10.004). URL: [http://dx.doi.org/10.1016/j.ins.2016.10.004](http://dx.doi.org/10.1016/j.ins.2016.10.004).

