---
title: The Fibonacci sequence in the description of maximal discrete Archimedean t-norms
author:
- <a href='/people/staff/cbejines/' style='color:rgb(100,0,50);'>Carlos Bejines</a>
- Mirko Navara
date: '2022'
categories: uncategorised
slug: 2022/FiSeDeMaDiAr
details: Fuzzy Sets Syst. vol. 451 , pages 94--112.
doi: 10.1016/J.FSS.2022.08.012
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Bejines2022b></a>[[BN22]](#cite-Bejines2022b) C. Bejines and M. Navara. “The Fibonacci sequence in the description of maximal discrete Archimedean t-norms”. In: _Fuzzy Sets Syst._ 451 (2022), pp. 94-112. DOI: [10.1016/J.FSS.2022.08.012](https://doi.org/10.1016%2FJ.FSS.2022.08.012). URL: [https://doi.org/10.1016/j.fss.2022.08.012](https://doi.org/10.1016/j.fss.2022.08.012).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{Bejines2022b,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Carlos Bejines and Mirko Navara},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Fuzzy Sets Syst.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {The Fibonacci sequence in the description of maximal discrete Archimedean t-norms},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2022},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {94--112},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {451},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/fss/BejinesN22.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1016/J.FSS.2022.08.012},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Sun, 15 Jan 2023 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1016/j.fss.2022.08.012},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1016/J.FSS.2022.08.012" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1016/J.FSS.2022.08.012" class="plumx-details" data-site="plum" data-hide-when-empty="true">The Fibonacci sequence in the description of maximal discrete Archimedean t-norms</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1016/J.FSS.2022.08.012"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Bejines_2023></a>[[1]](#cite-Bejines_2023) C. Bejines and M. Ojeda-Hernández. “Counting semicopulas on finite structures”. In: _Fuzzy Sets and Systems_ 462 (Jun. 2023), p. 108405. ISSN: 0165-0114. DOI: [10.1016/j.fss.2022.09.011](https://doi.org/10.1016%2Fj.fss.2022.09.011). URL: [http://dx.doi.org/10.1016/j.fss.2022.09.011](http://dx.doi.org/10.1016/j.fss.2022.09.011).

<a name=bib-2023></a>[[2]](#cite-2023) M. R. Khan, K. Ullah, and Q. Khan. “Multi-attribute decision-making using Archimedean aggregation operator in T-spherical fuzzy environment”. In: _Reports in Mechanical Engineering_ 4.1 (Dec. 2023), p. 18–38. ISSN: 2683-5894. DOI: [10.31181/rme20031012023k](https://doi.org/10.31181%2Frme20031012023k). URL: [http://dx.doi.org/10.31181/rme20031012023k](http://dx.doi.org/10.31181/rme20031012023k).

<a name=bib-Munar_2024></a>[[3]](#cite-Munar_2024) M. Munar, M. Couceiro, S. Massanet, et al. “A survey on the enumeration of classes of logical connectives and aggregation functions defined on a finite chain, with new results”. In: _Fuzzy Sets and Systems_ 490 (Aug. 2024), p. 109023. ISSN: 0165-0114. DOI: [10.1016/j.fss.2024.109023](https://doi.org/10.1016%2Fj.fss.2024.109023). URL: [http://dx.doi.org/10.1016/j.fss.2024.109023](http://dx.doi.org/10.1016/j.fss.2024.109023).

<a name=bib-Qiao_2025></a>[[4]](#cite-Qiao_2025) J. Qiao. “Quasi-D-overlap functions: Construction and characterization”. In: _Fuzzy Sets and Systems_ 498 (Jan. 2025), p. 109138. ISSN: 0165-0114. DOI: [10.1016/j.fss.2024.109138](https://doi.org/10.1016%2Fj.fss.2024.109138). URL: [http://dx.doi.org/10.1016/j.fss.2024.109138](http://dx.doi.org/10.1016/j.fss.2024.109138).

