---
title: On the Affordance-Theoretic bases of the Landscape of Knowledge Paradigm
author:
- Francisco J. Valverde-Albacete
- Carmen Peláez-Moreno
- <a href='/people/staff/ipcabrera/' style='color:rgb(100,0,50);'>Inma P. Cabrera</a>
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '2022'
categories: uncategorised
slug: 2022/BaLaKnPa
details: Proceedings of the Sixteenth International Conference on Concept Lattices
  and Their Applications {(CLA} 2022) Tallinn, Estonia, June 20-22, 2022., Tallinn,
  Estonia, June 20-22, 2022 , {CEUR} Workshop Proceedings vol. 3308, pages 93--104.
---



# Abstract


In this paper we set out to understand the cognitive basis of Formal Concept Analysis used as an Exploratory Data Analysis framework under the guise of the Landscapes of Knowledge metaphor introduced by Wille. We show that it can be re-interpreted and extended in the framework of the Theory of Affordances from Ecological Psychology to provide not only different affordances for different flavours of formal analysis of the information captured by a formal context, but also a theory that sheds light on how we learn to do it, Perceptual Learning. This raises the issue of what it is that a formal analysis of a formal context provides. We introduce the concept of formal qualia as basic, incomparable, privative items of information afforded by each possible analysis and illustrate these concepts by the formal qualia provided by Formal Concept, Independence and Equivalence Analysis.








# Citation
Please, cite this work as:


<a name=bib-ValverdeAlbacete2022></a>[[Val+22]](#cite-ValverdeAlbacete2022) F. J. Valverde-Albacete, C. Peláez-Moreno, I. P. Cabrera, et al. “On the Affordance-Theoretic bases of the Landscape of Knowledge Paradigm”. In: _Proceedings of the Sixteenth International Conference on Concept Lattices and Their Applications (CLA 2022) Tallinn, Estonia, June 20-22, 2022., Tallinn, Estonia, June 20-22, 2022_. Ed. by P. Cordero and O. Kr\'\idlo. Vol. 3308. CEUR Workshop Proceedings. CEUR-WS.org, 2022, pp. 93-104. URL: [https://ceur-ws.org/Vol-3308/Paper08.pdf](https://ceur-ws.org/Vol-3308/Paper08.pdf).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{ValverdeAlbacete2022,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Francisco J. Valverde-Albacete and Carmen Pel{\a'a}ez-Moreno and Inma P. Cabrera and Pablo Cordero and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Proceedings of the Sixteenth International Conference on Concept Lattices and Their Applications {(CLA} 2022) Tallinn, Estonia, June 20-22, 2022., Tallinn, Estonia, June 20-22, 2022},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {On the Affordance-Theoretic bases of the Landscape of Knowledge Paradigm},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2022},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Pablo Cordero and Ondrej Kr\'\idlo},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {93--104},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {CEUR-WS.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {{CEUR} Workshop Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {3308},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {In this paper we set out to understand the cognitive basis of Formal Concept Analysis used as an Exploratory Data Analysis framework under the guise of the Landscapes of Knowledge metaphor introduced by Wille. We show that it can be re-interpreted and extended in the framework of the Theory of Affordances from Ecological Psychology to provide not only different affordances for different flavours of formal analysis of the information captured by a formal context, but also a theory that sheds light on how we learn to do it, Perceptual Learning. This raises the issue of what it is that a formal analysis of a formal context provides. We introduce the concept of formal qualia as basic, incomparable, privative items of information afforded by each possible analysis and illustrate these concepts by the formal qualia provided by Formal Concept, Independence and Equivalence Analysis.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/cla/Valverde-Albacete22.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 10 Mar 2023 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://ceur-ws.org/Vol-3308/Paper08.pdf},<br>}

:::








