---
author:
- <a href='/people/staff/manuojeda/' style='color:rgb(100,0,50);'>Manuel Ojeda Hernández</a>
- <a href='/people/staff/dominlopez/' style='color:rgb(100,0,50);'>Domingo López Rodríguez</a>
- <a href='/people/staff/amora/' style='color:rgb(100,0,50);'>Ángel Mora</a>
Status: Published
date: '2023-02-03T00:00:00Z'
slug: 2023/SeAnTeUsFoCoAn
title: Lexicon-based sentiment analysis in texts using Formal Concept Analysis
categories:
- Formal concept analysis
- Text mining
header_image: ~
details: <em>International Journal of Approximate Reasoning</em>, vol. 155, pp 104-112
doi: 10.1016/j.ijar.2023.02.001
link: 2023-ijar/paper.pdf
selected: yes
project: ~
keywords: Formal Concept Analysis, Sentiment analysis, Polarity analysis, Text mining,
  Lexicon
---


# Abstract


In this paper, we present a novel approach for sentiment analysis that uses Formal Concept Analysis (FCA) to create dictionaries for classification. Unlike other methods that rely on pre-defined lexicons, our approach allows for the creation of customised dictionaries that are tailored to the specific data and tasks. By using a dataset of tweets categorised into positive and negative polarity, we show that our approach achieves a better performance than other standard dictionaries.












# Citation
Please, cite this work as:


<a name=bib-ijar2023></a>[[OLM23]](#cite-ijar2023) M. Ojeda-Hernández, D. López-Rodríguez, and Á. Mora. “Lexicon-based sentiment analysis in texts using Formal Concept Analysis”. In: _International Journal of Approximate Reasoning_ 155 (2023), pp. 104-112. ISSN: 0888-613X. DOI: [https://doi.org/10.1016/j.ijar.2023.02.001](https://doi.org/https%3A%2F%2Fdoi.org%2F10.1016%2Fj.ijar.2023.02.001). URL: [https://www.sciencedirect.com/science/article/pii/S0888613X23000130](https://www.sciencedirect.com/science/article/pii/S0888613X23000130).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@article{ijar2023,<br>&nbsp;&nbsp;&nbsp;&nbsp;title = {Lexicon-based sentiment analysis in texts using Formal Concept Analysis},<br>&nbsp;&nbsp;&nbsp;&nbsp;journal = {International Journal of Approximate Reasoning},<br>&nbsp;&nbsp;&nbsp;&nbsp;volume = {155},<br>&nbsp;&nbsp;&nbsp;&nbsp;pages = {104-112},<br>&nbsp;&nbsp;&nbsp;&nbsp;year = {2023},<br>&nbsp;&nbsp;&nbsp;&nbsp;issn = {0888-613X},<br>&nbsp;&nbsp;&nbsp;&nbsp;doi = {https://doi.org/10.1016/j.ijar.2023.02.001},<br>&nbsp;&nbsp;&nbsp;&nbsp;url = {https://www.sciencedirect.com/science/article/pii/S0888613X23000130},<br>&nbsp;&nbsp;&nbsp;&nbsp;author = {Manuel Ojeda-Hernández and Domingo López-Rodríguez and Ángel Mora},<br>&nbsp;&nbsp;&nbsp;&nbsp;keywords = {Formal Concept Analysis, Sentiment analysis, Polarity analysis, Text mining, Lexicon}<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1016/j.ijar.2023.02.001" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1016/j.ijar.2023.02.001" class="plumx-details" data-site="plum" data-hide-when-empty="true">Lexicon-based sentiment analysis in texts using Formal Concept Analysis</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1016/j.ijar.2023.02.001"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Akande_2023></a>[[1]](#cite-Akande_2023) O. N. Akande, M. O. Lawrence, and P. Ogedebe. “Application of bidirectional LSTM deep learning technique for sentiment analysis of COVID-19 tweets: post-COVID vaccination era”. In: _Journal of Electrical Systems and Information Technology_ 10.1 (Nov. 2023). ISSN: 2314-7172. DOI: [10.1186/s43067-023-00118-w](https://doi.org/10.1186%2Fs43067-023-00118-w). URL: [http://dx.doi.org/10.1186/s43067-023-00118-w](http://dx.doi.org/10.1186/s43067-023-00118-w).

<a name=bib-Barik_2024></a>[[2]](#cite-Barik_2024) K. Barik and S. Misra. “Analysis of customer reviews with an improved VADER lexicon classifier”. In: _Journal of Big Data_ 11.1 (Jan. 2024). ISSN: 2196-1115. DOI: [10.1186/s40537-023-00861-x](https://doi.org/10.1186%2Fs40537-023-00861-x). URL: [http://dx.doi.org/10.1186/s40537-023-00861-x](http://dx.doi.org/10.1186/s40537-023-00861-x).

<a name=bib-Berutu_2023></a>[[3]](#cite-Berutu_2023) S. S. Berutu, H. Budiati, J. Jatmika, et al. “Data preprocessing approach for machine learning-based sentiment classification”. In: _JURNAL INFOTEL_ 15.4 (Nov. 2023), p. 317–325. ISSN: 2085-3688. DOI: [10.20895/infotel.v15i4.1030](https://doi.org/10.20895%2Finfotel.v15i4.1030). URL: [http://dx.doi.org/10.20895/infotel.v15i4.1030](http://dx.doi.org/10.20895/infotel.v15i4.1030).

<a name=bib-Chen_2024></a>[[4]](#cite-Chen_2024) Y. Chen, C. Hao, A. Zheng, et al. “Emotional Orientation in Peer Assessment: Impact on College Student Performance”. In: _The Asia-Pacific Education Researcher_ (Jul. 2024). ISSN: 2243-7908. DOI: [10.1007/s40299-024-00884-9](https://doi.org/10.1007%2Fs40299-024-00884-9). URL: [http://dx.doi.org/10.1007/s40299-024-00884-9](http://dx.doi.org/10.1007/s40299-024-00884-9).

<a name=bib-Cheng_2023></a>[[5]](#cite-Cheng_2023) Y. Cheng, C. Zhang, A. K. Sangaiah, et al. “Efficient Low-Resource Medical Information Processing Based on Semantic Analysis and Granular Computing”. In: _ACM Transactions on Asian and Low-Resource Language Information Processing_ (Oct. 2023). ISSN: 2375-4702. DOI: [10.1145/3626319](https://doi.org/10.1145%2F3626319). URL: [http://dx.doi.org/10.1145/3626319](http://dx.doi.org/10.1145/3626319).

<a name=bib-Hidayat_2024></a>[[6]](#cite-Hidayat_2024) T. Hidayat, A. Ahmad, and H. C. Ngo. “Non-redundant implicational base of formal context with constraints using SAT”. In: _PeerJ Computer Science_ 10 (Jan. 2024), p. e1806. ISSN: 2376-5992. DOI: [10.7717/peerj-cs.1806](https://doi.org/10.7717%2Fpeerj-cs.1806). URL: [http://dx.doi.org/10.7717/peerj-cs.1806](http://dx.doi.org/10.7717/peerj-cs.1806).

<a name=bib-Ho_2024></a>[[7]](#cite-Ho_2024) C. F. Ho, K. L. Chean, and T. M. Lim. “Leveraging Machine Translation to Enhance Sentiment Analysis on Multilingual Text”. In: _Proceedings of the 2024 13th International Conference on Software and Computer Applications_. ICSCA 2024. ACM, Feb. 2024, p. 242–248. DOI: [10.1145/3651781.3651819](https://doi.org/10.1145%2F3651781.3651819). URL: [http://dx.doi.org/10.1145/3651781.3651819](http://dx.doi.org/10.1145/3651781.3651819).

<a name=bib-Liagkouras_2024></a>[[8]](#cite-Liagkouras_2024) K. Liagkouras and K. Metaxiotis. “Extracting Sentiment from Business News Announcements for More Efficient Decision Making”. In: _Advances in Artificial Intelligence-Empowered Decision Support Systems_. Springer Nature Switzerland, 2024, p. 263–282. ISBN: 9783031623165. DOI: [10.1007/978-3-031-62316-5_11](https://doi.org/10.1007%2F978-3-031-62316-5_11). URL: [http://dx.doi.org/10.1007/978-3-031-62316-5_11](http://dx.doi.org/10.1007/978-3-031-62316-5_11).

<a name=bib-Liu_2025></a>[[9]](#cite-Liu_2025) H. Liu, X. Xin, W. Peng, et al. “Concept-driven knowledge distillation and pseudo label generation for continual named entity recognition”. In: _Expert Systems with Applications_ (Jan. 2025), p. 126546. ISSN: 0957-4174. DOI: [10.1016/j.eswa.2025.126546](https://doi.org/10.1016%2Fj.eswa.2025.126546). URL: [http://dx.doi.org/10.1016/j.eswa.2025.126546](http://dx.doi.org/10.1016/j.eswa.2025.126546).

<a name=bib-Liu_2024></a>[[10]](#cite-Liu_2024) S. Liu and Q. Liu. “A sentiment analysis model based on dynamic pre-training and stacked involutions”. In: _The Journal of Supercomputing_ 80.11 (Apr. 2024), p. 15613–15635. ISSN: 1573-0484. DOI: [10.1007/s11227-024-06052-6](https://doi.org/10.1007%2Fs11227-024-06052-6). URL: [http://dx.doi.org/10.1007/s11227-024-06052-6](http://dx.doi.org/10.1007/s11227-024-06052-6).

<a name=bib-Liu_20242></a>[[11]](#cite-Liu_20242) X. Liu, M. Li, Y. Ma, et al. “Personalized tourism product design focused on tourist expectations and online reviews: An integrated MCDM method”. In: _Computers &amp; Industrial Engineering_ 188 (Feb. 2024), p. 109860. ISSN: 0360-8352. DOI: [10.1016/j.cie.2023.109860](https://doi.org/10.1016%2Fj.cie.2023.109860). URL: [http://dx.doi.org/10.1016/j.cie.2023.109860](http://dx.doi.org/10.1016/j.cie.2023.109860).

<a name=bib-Liu_20241></a>[[12]](#cite-Liu_20241) Y. Liu, T. You, J. Zou, et al. “Modelling customer requirement for mobile games based on online reviews using BW-CNN and S-Kano models”. In: _Expert Systems with Applications_ 258 (Dec. 2024), p. 125142. ISSN: 0957-4174. DOI: [10.1016/j.eswa.2024.125142](https://doi.org/10.1016%2Fj.eswa.2024.125142). URL: [http://dx.doi.org/10.1016/j.eswa.2024.125142](http://dx.doi.org/10.1016/j.eswa.2024.125142).

<a name=bib-Montesinos_Yufa_2024></a>[[13]](#cite-Montesinos_Yufa_2024) H. Montesinos-Yufa and E. Musgrove. “A Sentiment Analysis of News Articles Published Before and During the COVID-19 Pandemic”. In: _International Journal on Data Science and Technology_ 10.2 (Aug. 2024), p. 38–44. ISSN: 2472-2200. DOI: [10.11648/j.ijdst.20241002.13](https://doi.org/10.11648%2Fj.ijdst.20241002.13). URL: [http://dx.doi.org/10.11648/j.ijdst.20241002.13](http://dx.doi.org/10.11648/j.ijdst.20241002.13).

<a name=bib-Smatov_2024></a>[[14]](#cite-Smatov_2024) N. Smatov, R. Kalashnikov, and A. Kartbayev. “Development of Context-Based Sentiment Classification for Intelligent Stock Market Prediction”. In: _Big Data and Cognitive Computing_ 8.6 (May. 2024), p. 51. ISSN: 2504-2289. DOI: [10.3390/bdcc8060051](https://doi.org/10.3390%2Fbdcc8060051). URL: [http://dx.doi.org/10.3390/bdcc8060051](http://dx.doi.org/10.3390/bdcc8060051).

<a name=bib-Wang_2024></a>[[15]](#cite-Wang_2024) Y. Wang and K. Wang. “Will Public Health Emergencies Affect Compensatory Consumption Behavior? Evidence from Emotional Eating Perspective”. In: _Foods_ 13.22 (Nov. 2024), p. 3571. ISSN: 2304-8158. DOI: [10.3390/foods13223571](https://doi.org/10.3390%2Ffoods13223571). URL: [http://dx.doi.org/10.3390/foods13223571](http://dx.doi.org/10.3390/foods13223571).

<a name=bib-Zhang_2024></a>[[16]](#cite-Zhang_2024) C. Zhang, Q. Wen, D. Li, et al. “Intelligent evaluation system for new energy vehicles based on sentiment analysis: An MG-PL-3WD method”. In: _Engineering Applications of Artificial Intelligence_ 133 (Jul. 2024), p. 108485. ISSN: 0952-1976. DOI: [10.1016/j.engappai.2024.108485](https://doi.org/10.1016%2Fj.engappai.2024.108485). URL: [http://dx.doi.org/10.1016/j.engappai.2024.108485](http://dx.doi.org/10.1016/j.engappai.2024.108485).

<a name=bib-Zhang_2023></a>[[17]](#cite-Zhang_2023) L. Zhang and Y. Jiang. “Fusing semantic aspects for formal concept analysis using knowledge graphs”. In: _Multimedia Tools and Applications_ 83.6 (Jul. 2023), p. 16763–16797. ISSN: 1573-7721. DOI: [10.1007/s11042-023-16271-3](https://doi.org/10.1007%2Fs11042-023-16271-3). URL: [http://dx.doi.org/10.1007/s11042-023-16271-3](http://dx.doi.org/10.1007/s11042-023-16271-3).


