---
author: Rafael Marcos Luque, Domingo López-Rodríguez, Enrique Domínguez, Esteban J.
  Palomo
Status: Published
date: '2008-01-01'
slug: 2008/DiCoNeNeViSe
title: A Dipolar Competitive Neural Network for Video Segmentation
categories:
- Competitive learning
- Image processing
- Neural networks
header_image: ~
details: Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial
  Intelligence and Lecture Notes in Bioinformatics), (5290 LNAI), <em>pp. 103-112</em>
doi: 10.1007/978-3-540-88309-8_11
link: 2008-iberamia/paper.pdf
project: ''
keywords: Background model, Background subtraction method, Competitive neural network,
  Data sets, Hardware implementations, Mixture of Gaussians, Realtime processing,
  Video segmentation, Hardware, Image segmentation, Pixels, Neural networks
---


# Abstract


This paper present a video segmentation method which separate pixels corresponding to foreground from those corresponding to background. The proposed background model consists of a competitive neural network based on dipoles, which is used to classify the pixels as background or foreground. Using this kind of neural networks permits an easy hardware implementation to achieve a real time processing with good results. The dipolar representation is designed to deal with the problem of estimating the directionality of data. Experimental results are provided by using the standard PETS dataset and compared with the mixture of Gaussians and background subtraction methods. © 2008 Springer-Verlag.












# Citation
Please, cite this work as:


<a name=bib-Luque2008></a>[[Luq+08]](#cite-Luque2008) R. M. Luque, D. López-Rodríguez, E. Domínguez, et al. “A Dipolar Competitive Neural Network for Video Segmentation”. In: _Advances in Artificial Intelligence - IBERAMIA 2008, 11th Ibero-American Conference on AI, Lisbon, Portugal, October 14-17, 2008. Proceedings_. Ed. by H. Geffner, R. Prada, I. M. Alexandre and N. David. Vol. 5290 LNAI. Lecture Notes in Computer Science. cited By 5; Conference of 11th Ibero-American Conference on Artificial Intelligence, IBERAMIA 2008 ; Conference Date: 14 October 2008 Through 17 October 2008; Conference Code:77561. Lisbon: Springer, 2008, pp. 103-112. DOI: [10.1007/978-3-540-88309-8_11](https://doi.org/10.1007%2F978-3-540-88309-8_11). URL: [https://doi.org/10.1007/978-3-540-88309-8_11](https://doi.org/10.1007/978-3-540-88309-8_11).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Luque2008,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Rafael Marcos Luque and Domingo López-Rodríguez and Enrique Domínguez and Esteban J. Palomo},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Advances in Artificial Intelligence - {IBERAMIA} 2008, 11th Ibero-American Conference on AI, Lisbon, Portugal, October 14-17, 2008. Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {A Dipolar Competitive Neural Network for Video Segmentation},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2008},<br>&nbsp;&nbsp;&nbsp;&nbsp;  address = {Lisbon},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Hector Geffner and Rui Prada and Isabel Machado Alexandre and Nuno David},<br>&nbsp;&nbsp;&nbsp;&nbsp;  note = {cited By 5; Conference of 11th Ibero-American Conference on Artificial Intelligence, IBERAMIA 2008 ; Conference Date: 14 October 2008 Through 17 October 2008; Conference Code:77561},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {103-112},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {5290 LNAI},<br>&nbsp;&nbsp;&nbsp;&nbsp;  abstract = {This paper present a video segmentation method which separate pixels corresponding to foreground from those corresponding to background. The proposed background model consists of a competitive neural network based on dipoles, which is used to classify the pixels as background or foreground. Using this kind of neural networks permits an easy hardware implementation to achieve a real time processing with good results. The dipolar representation is designed to deal with the problem of estimating the directionality of data. Experimental results are provided by using the standard PETS dataset and compared with the mixture of Gaussians and background subtraction methods. © 2008 Springer-Verlag.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/iberamia/LuqueLDP08.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  document_type = {Conference Paper},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/978-3-540-88309-8_11},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)},<br>&nbsp;&nbsp;&nbsp;&nbsp;  keywords = {Background model; Background subtraction method; Competitive neural network; Data sets; Hardware implementations; Mixture of Gaussians; Realtime processing; Video segmentation, Hardware; Image segmentation; Pixels, Neural networks},<br>&nbsp;&nbsp;&nbsp;&nbsp;  source = {Scopus},<br>&nbsp;&nbsp;&nbsp;&nbsp;  sponsors = {Lisbon University Institute (ISCTE); Fundacao para a Ciencia e Tecnologia (FCT); Asociacion Espanola de Inteligencia Artificial (AEPIA); Associacao Portuguesa para a Inteligencia Artificial (APPIA)},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/978-3-540-88309-8_11},<br>}

:::



# Bibliometric data


The following data has been extracted from free resources such as [OpenAlex](https://openalex.org/) or [Dimensions](https://app.dimensions.ai/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/978-3-540-88309-8_11" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/978-3-540-88309-8_11" class="plumx-details" data-site="plum" data-hide-when-empty="true">A Dipolar Competitive Neural Network for Video Segmentation</a></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Bouwmans_2014></a>[[1]](#cite-Bouwmans_2014) T. Bouwmans. “Traditional and recent approaches in background modeling for foreground detection: An overview”. In: _Computer Science Review_ 11–12 (May. 2014), p. 31–66. ISSN: 1574-0137. DOI: [10.1016/j.cosrev.2014.04.001](https://doi.org/10.1016%2Fj.cosrev.2014.04.001). URL: [http://dx.doi.org/10.1016/j.cosrev.2014.04.001](http://dx.doi.org/10.1016/j.cosrev.2014.04.001).

<a name=bib-Rai_2012></a>[[2]](#cite-Rai_2012) N. K. Rai, S. Chourasia, and A. Sethi. “An Efficient Neural Network Based Background Subtraction Method”. In: _Proceedings of Seventh International Conference on Bio-Inspired Computing: Theories and Applications (BIC-TA 2012)_. Springer India, Dec. 2012, p. 453–460. ISBN: 9788132210382. DOI: [10.1007/978-81-322-1038-2_38](https://doi.org/10.1007%2F978-81-322-1038-2_38). URL: [http://dx.doi.org/10.1007/978-81-322-1038-2_38](http://dx.doi.org/10.1007/978-81-322-1038-2_38).

<a name=bib-Rai_20121></a>[[3]](#cite-Rai_20121) N. K. Rai, A. Singh, and S. A. Mazhari. “Video Segmentation Using Neural Network and Distributed Genetic Algorithm”. In: _Proceedings of the International Conference on Soft Computing for Problem Solving (SocProS 2011) December 20-22, 2011_. Springer India, 2012, p. 229–237. ISBN: 9788132204916. DOI: [10.1007/978-81-322-0491-6_22](https://doi.org/10.1007%2F978-81-322-0491-6_22). URL: [http://dx.doi.org/10.1007/978-81-322-0491-6_22](http://dx.doi.org/10.1007/978-81-322-0491-6_22).

<a name=bib-Ryan_2009></a>[[4]](#cite-Ryan_2009) K. Ryan, A. Amer, and L. Gagnon. “Spatiotemporal Region Enhancement and Merging for Unsupervized Object Segmentation”. In: _EURASIP Journal on Image and Video Processing_ 2009 (2009), p. 1–13. ISSN: 1687-5281. DOI: [10.1155/2009/797052](https://doi.org/10.1155%2F2009%2F797052). URL: [http://dx.doi.org/10.1155/2009/797052](http://dx.doi.org/10.1155/2009/797052).


