---
title: Sub-propositional Fragments of the Interval Temporal Logic of Allen's Relations
author:
- Davide Bresolin
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
- Guido Sciavicco
date: '2014'
categories: uncategorised
slug: 2014/FrInTeLoRe
details: Logics in Artificial Intelligence - 14th European Conference, {JELIA} 2014,
  Funchal, Madeira, Portugal, September 24-26, 2014. Proceedings , Lecture Notes in
  Computer Science vol. 8761, pages 122--136.
doi: 10.1007/978-3-319-11558-0_9
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Bresolin2014a></a>[[BMS14]](#cite-Bresolin2014a) D. Bresolin, E. Mu~noz-Velasco, and G. Sciavicco. “Sub-propositional Fragments of the Interval Temporal Logic of Allen's Relations”. In: _Logics in Artificial Intelligence - 14th European Conference, JELIA 2014, Funchal, Madeira, Portugal, September 24-26, 2014. Proceedings_. Ed. by E. Fermé and J. Leite. Vol. 8761. Lecture Notes in Computer Science. Springer, 2014, pp. 122-136. DOI: [10.1007/978-3-319-11558-0\_9](https://doi.org/10.1007%2F978-3-319-11558-0%5C_9). URL: [https://doi.org/10.1007/978-3-319-11558-0\_9](https://doi.org/10.1007/978-3-319-11558-0\_9).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Bresolin2014a,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Davide Bresolin and Emilio Mu~noz-Velasco and Guido Sciavicco},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Logics in Artificial Intelligence - 14th European Conference, {JELIA} 2014, Funchal, Madeira, Portugal, September 24-26, 2014. Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Sub-propositional Fragments of the Interval Temporal Logic of Allen's Relations},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2014},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Eduardo Ferm{\a'e} and Jo~ao Leite},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {122--136},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {8761},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/jelia/BresolinMS14.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/978-3-319-11558-0\_9},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Wed, 07 Dec 2022 00:00:00 +0100},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/978-3-319-11558-0\_9},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/978-3-319-11558-0_9" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/978-3-319-11558-0_9" class="plumx-details" data-site="plum" data-hide-when-empty="true">Sub-propositional Fragments of the Interval Temporal Logic of Allen's Relations</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1007/978-3-319-11558-0_9"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Artale_2015></a>[[1]](#cite-Artale_2015) A. Artale, R. Kontchakov, V. Ryzhikov, et al. “Tractable Interval Temporal Propositional and Description Logics”. In: _Proceedings of the AAAI Conference on Artificial Intelligence_ 29.1 (Feb. 2015). ISSN: 2159-5399. DOI: [10.1609/aaai.v29i1.9406](https://doi.org/10.1609%2Faaai.v29i1.9406). URL: [http://dx.doi.org/10.1609/aaai.v29i1.9406](http://dx.doi.org/10.1609/aaai.v29i1.9406).

<a name=bib-Bresolin_2017></a>[[2]](#cite-Bresolin_2017) D. Bresolin, A. Kurucz, E. Muñoz-Velasco, et al. “Horn Fragments of the Halpern-Shoham Interval Temporal Logic”. In: _ACM Transactions on Computational Logic_ 18.3 (Jul. 2017), p. 1–39. ISSN: 1557-945X. DOI: [10.1145/3105909](https://doi.org/10.1145%2F3105909). URL: [http://dx.doi.org/10.1145/3105909](http://dx.doi.org/10.1145/3105909).

<a name=bib-Bresolin_2016></a>[[3]](#cite-Bresolin_2016) D. Bresolin, E. Muñoz-Velasco, and G. Sciavicco. “On the Expressive Power of Sub-Propositional Fragments of Modal Logic”. In: _Electronic Proceedings in Theoretical Computer Science_ 226 (Sep. 2016), p. 91–104. ISSN: 2075-2180. DOI: [10.4204/eptcs.226.7](https://doi.org/10.4204%2Feptcs.226.7). URL: [http://dx.doi.org/10.4204/eptcs.226.7](http://dx.doi.org/10.4204/eptcs.226.7).

<a name=bib-Mu_oz_Velasco_2015></a>[[4]](#cite-Mu_oz_Velasco_2015) E. Muñoz-Velasco, M. Pelegrín-García, P. Sala, et al. “On Coarser Interval Temporal Logics and their Satisfiability Problem”. In: _Advances in Artificial Intelligence_. Springer International Publishing, 2015, p. 105–115. ISBN: 9783319245980. DOI: [10.1007/978-3-319-24598-0_10](https://doi.org/10.1007%2F978-3-319-24598-0_10). URL: [http://dx.doi.org/10.1007/978-3-319-24598-0_10](http://dx.doi.org/10.1007/978-3-319-24598-0_10).

<a name=bib-Mu_oz_Velasco_2019></a>[[5]](#cite-Mu_oz_Velasco_2019) E. Muñoz-Velasco, M. Pelegrín, P. Sala, et al. “On coarser interval temporal logics”. In: _Artificial Intelligence_ 266 (Jan. 2019), p. 1–26. ISSN: 0004-3702. DOI: [10.1016/j.artint.2018.09.001](https://doi.org/10.1016%2Fj.artint.2018.09.001). URL: [http://dx.doi.org/10.1016/j.artint.2018.09.001](http://dx.doi.org/10.1016/j.artint.2018.09.001).

<a name=bib-Sciavicco_2019></a>[[6]](#cite-Sciavicco_2019) G. Sciavicco, I. E. Stan, and A. Vaccari. “Towards a General Method for Logical Rule Extraction from Time Series”. In: _From Bioinspired Systems and Biomedical Applications to Machine Learning_. Springer International Publishing, 2019, p. 3–12. ISBN: 9783030196516. DOI: [10.1007/978-3-030-19651-6_1](https://doi.org/10.1007%2F978-3-030-19651-6_1). URL: [http://dx.doi.org/10.1007/978-3-030-19651-6_1](http://dx.doi.org/10.1007/978-3-030-19651-6_1).

<a name=bib-Wa_ga_2016></a>[[7]](#cite-Wa_ga_2016) P. A. Wałęga. “Computational Complexity of a Hybridized Horn Fragment of Halpern-Shoham Logic”. In: _Logic and Its Applications_. Springer Berlin Heidelberg, Dec. 2016, p. 224–238. ISBN: 9783662540695. DOI: [10.1007/978-3-662-54069-5_17](https://doi.org/10.1007%2F978-3-662-54069-5_17). URL: [http://dx.doi.org/10.1007/978-3-662-54069-5_17](http://dx.doi.org/10.1007/978-3-662-54069-5_17).

<a name=bib-Wa_ga_20191></a>[[8]](#cite-Wa_ga_20191) P. A. Wałęga. “Computational Complexity of Core Fragments of Modal Logics T, K4, and S4”. In: _Logics in Artificial Intelligence_. Springer International Publishing, 2019, p. 744–759. ISBN: 9783030195700. DOI: [10.1007/978-3-030-19570-0_48](https://doi.org/10.1007%2F978-3-030-19570-0_48). URL: [http://dx.doi.org/10.1007/978-3-030-19570-0_48](http://dx.doi.org/10.1007/978-3-030-19570-0_48).

<a name=bib-Wa_ga_2019></a>[[9]](#cite-Wa_ga_2019) P. A. Wałęga. “Hybrid fragments of Halpern–Shoham logic and their expressive power”. In: _Theoretical Computer Science_ 797 (Dec. 2019), p. 102–128. ISSN: 0304-3975. DOI: [10.1016/j.tcs.2019.01.014](https://doi.org/10.1016%2Fj.tcs.2019.01.014). URL: [http://dx.doi.org/10.1016/j.tcs.2019.01.014](http://dx.doi.org/10.1016/j.tcs.2019.01.014).

<a name=bib-Wa_ga_2017></a>[[10]](#cite-Wa_ga_2017) P. A. Wałęga. “Searching for Well-Behaved Fragments of Halpern-Shoham Logic”. In: _Proceedings of the Twenty-Sixth International Joint Conference on Artificial Intelligence_. IJCAI-2017. International Joint Conferences on Artificial Intelligence Organization, Aug. 2017, p. 5219–5220. DOI: [10.24963/ijcai.2017/769](https://doi.org/10.24963%2Fijcai.2017%2F769). URL: [http://dx.doi.org/10.24963/ijcai.2017/769](http://dx.doi.org/10.24963/ijcai.2017/769).

