---
title: Logics in Artificial Intelligence, European Workshop, {JELIA} 2000 Malaga,
  Spain, September 29 - October 2, 2000, Proceedings
author:
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
- <a href='/people/staff/ipguzman/' style='color:rgb(100,0,50);'>Inma P. de Guzmán</a>
- Gerhard Brewka
- Luis Moniz Pereira
date: '2000'
categories: uncategorised
slug: 2000/LoArEuSeOcPr
details: []
doi: 10.1007/3-540-40006-0
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-OjedaAciego2000></a>[[Oje+00]](#cite-OjedaAciego2000) M. Ojeda-Aciego, I. P. de Guzmán, G. Brewka, et al., ed. _Logics in Artificial Intelligence, European Workshop, JELIA 2000 Malaga, Spain, September 29 - October 2, 2000, Proceedings_. Vol. 1919. Lecture Notes in Computer Science. Springer, 2000. ISBN: 3-540-41131-3. DOI: [10.1007/3-540-40006-0](https://doi.org/10.1007%2F3-540-40006-0). URL: [https://doi.org/10.1007/3-540-40006-0](https://doi.org/10.1007/3-540-40006-0).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Proceedings{OjedaAciego2000,<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Logics in Artificial Intelligence, European Workshop, {JELIA} 2000 Malaga, Spain, September 29 - October 2, 2000, Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2000},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Manuel Ojeda-Aciego and Inman P. {de Guzm{\a'a}n} and Gerhard Brewka and Lu\'\is Moniz Pereira},<br>&nbsp;&nbsp;&nbsp;&nbsp;  isbn = {3-540-41131-3},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {1919},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/jelia/2000.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/3-540-40006-0},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Tue, 14 May 2019 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/3-540-40006-0},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/3-540-40006-0" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/3-540-40006-0" class="plumx-details" data-site="plum" data-hide-when-empty="true">Logics in Artificial Intelligence, European Workshop, {JELIA} 2000 Malaga, Spain, September 29 - October 2, 2000, Proceedings</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1007/3-540-40006-0"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Betz_2008></a>[[1]](#cite-Betz_2008) G. Betz. “Evaluating Dialectical Structures”. In: _Journal of Philosophical Logic_ 38.3 (Sep. 2008), p. 283–312. ISSN: 1573-0433. DOI: [10.1007/s10992-008-9091-5](https://doi.org/10.1007%2Fs10992-008-9091-5). URL: [http://dx.doi.org/10.1007/s10992-008-9091-5](http://dx.doi.org/10.1007/s10992-008-9091-5).

<a name=bib-Cornejo_2018></a>[[2]](#cite-Cornejo_2018) M. E. Cornejo, D. Lobo, and J. Medina. “Syntax and semantics of multi-adjoint normal logic programming”. In: _Fuzzy Sets and Systems_ 345 (Aug. 2018), p. 41–62. ISSN: 0165-0114. DOI: [10.1016/j.fss.2017.12.009](https://doi.org/10.1016%2Fj.fss.2017.12.009). URL: [http://dx.doi.org/10.1016/j.fss.2017.12.009](http://dx.doi.org/10.1016/j.fss.2017.12.009).

<a name=bib-Cremonini_1989></a>[[3]](#cite-Cremonini_1989) R. Cremonini, E. Lamma, and P. Mello. “ADES: An expert system for ATP design”. In: _Artificial Intelligence for Engineering Design, Analysis and Manufacturing_ 3.1 (Feb. 1989), p. 1–21. ISSN: 1469-1760. DOI: [10.1017/s0890060400001062](https://doi.org/10.1017%2Fs0890060400001062). URL: [http://dx.doi.org/10.1017/s0890060400001062](http://dx.doi.org/10.1017/s0890060400001062).

<a name=bib-Vetterlein_2015></a>[[4]](#cite-Vetterlein_2015) T. Vetterlein. “Logic of approximate entailment in quasimetric spaces”. In: _International Journal of Approximate Reasoning_ 64 (Sep. 2015), p. 39–53. ISSN: 0888-613X. DOI: [10.1016/j.ijar.2015.06.008](https://doi.org/10.1016%2Fj.ijar.2015.06.008). URL: [http://dx.doi.org/10.1016/j.ijar.2015.06.008](http://dx.doi.org/10.1016/j.ijar.2015.06.008).

