---
title: 'Conference paper accepted: <em>Self-organization of probabilistic PCA models</em>'
author: E. López-Rubio, J.M. Ortiz-De-Lazcano-Lobato, Domingo López-Rodríguez, M.
  Del Carmen Vargas-González
date: '2007-01-01'
categories:
- Neural networks
- Competitive learning
- Principal component analysis
---

The work <u>Self-organization of probabilistic PCA models</u> has been published in <em>Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics), (4507 LNCS), <em>pp. 211-218</em></em>.

<u>Abstract</u>:



We present a new neural model, which extends Kohonen's self-organizing map (SOM) by performing a Probabilistic Principal Components Analysis (PPCA) at each neuron. Several self-organizing maps have been proposed in the literature to capture the local principal subspaces, but our approach offers a probabilistic model at each neuron while it has linear complexity on the dimensionality of the input space. This allows to process very high dimensional data to obtain reliable estimations of the local probability densities which are based on the PPCA framework. Experimental results are presented, which show the map formation capabilities of the proposal with high dimensional data. © Springer-Verlag Berlin Heidelberg 2007.




For more details on this work, visit <a href='/publications/conferences/2007-iwann2'>its own page</a>.
