---
title: On Galois Connections and Soft Computing
author:
- Francisca García-Pardo
- <a href='/people/staff/ipcabrera/' style='color:rgb(100,0,50);'>Inma P. Cabrera</a>
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '2013'
categories: uncategorised
slug: 2013/GaCoSoCo
details: Advances in Computational Intelligence - 12th International Work-Conference
  on Artificial Neural Networks, {IWANN} 2013, Puerto de la Cruz, Tenerife, Spain,
  June 12-14, 2013, Proceedings, Part {II} , Lecture Notes in Computer Science vol.
  7903, pages 224--235.
doi: 10.1007/978-3-642-38682-4_26
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-GarciaPardo2013></a>[[Gar+13]](#cite-GarciaPardo2013) F. Garc\'\ia-Pardo, I. P. Cabrera, P. Cordero, et al. “On Galois Connections and Soft Computing”. In: _Advances in Computational Intelligence - 12th International Work-Conference on Artificial Neural Networks, IWANN 2013, Puerto de la Cruz, Tenerife, Spain, June 12-14, 2013, Proceedings, Part II_. Ed. by I. Rojas, G. J. Caparrós and J. Cabestany. Vol. 7903. Lecture Notes in Computer Science. Springer, 2013, pp. 224-235. DOI: [10.1007/978-3-642-38682-4\_26](https://doi.org/10.1007%2F978-3-642-38682-4%5C_26). URL: [https://doi.org/10.1007/978-3-642-38682-4\_26](https://doi.org/10.1007/978-3-642-38682-4\_26).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{GarciaPardo2013,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Francisca Garc\'\ia-Pardo and Inma P. Cabrera and Pablo Cordero and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Advances in Computational Intelligence - 12th International Work-Conference on Artificial Neural Networks, {IWANN} 2013, Puerto de la Cruz, Tenerife, Spain, June 12-14, 2013, Proceedings, Part {II}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {On Galois Connections and Soft Computing},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2013},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Ignacio Rojas and Gonzalo Joya Caparr{\a'o}s and Joan Cabestany},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {224--235},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {7903},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/iwann/Garcia-PardoCCO13.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/978-3-642-38682-4\_26},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Sat, 30 Sep 2023 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/978-3-642-38682-4\_26},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/978-3-642-38682-4_26" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/978-3-642-38682-4_26" class="plumx-details" data-site="plum" data-hide-when-empty="true">On Galois Connections and Soft Computing</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1007/978-3-642-38682-4_26"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Cabrera_2018></a>[[1]](#cite-Cabrera_2018) I. P. Cabrera, P. Cordero, F. Garcia-Pardo, et al. “Galois Connections Between a Fuzzy Preordered Structure and a General Fuzzy Structure”. In: _IEEE Transactions on Fuzzy Systems_ 26.3 (Jun. 2018), p. 1274–1287. ISSN: 1941-0034. DOI: [10.1109/tfuzz.2017.2718495](https://doi.org/10.1109%2Ftfuzz.2017.2718495). URL: [http://dx.doi.org/10.1109/tfuzz.2017.2718495](http://dx.doi.org/10.1109/tfuzz.2017.2718495).

<a name=bib-Cabrera_2019></a>[[2]](#cite-Cabrera_2019) I. P. Cabrera, P. Cordero, E. Muñoz-Velasco, et al. “A Relational Extension of Galois Connections”. In: _Formal Concept Analysis_. Springer International Publishing, 2019, p. 290–303. ISBN: 9783030214623. DOI: [10.1007/978-3-030-21462-3_19](https://doi.org/10.1007%2F978-3-030-21462-3_19). URL: [http://dx.doi.org/10.1007/978-3-030-21462-3_19](http://dx.doi.org/10.1007/978-3-030-21462-3_19).

<a name=bib-Cabrera_20201></a>[[3]](#cite-Cabrera_20201) I. P. Cabrera, P. Cordero, E. Muñoz-Velasco, et al. “Relational Galois connections between transitive digraphs: Characterization and construction”. In: _Information Sciences_ 519 (May. 2020), p. 439–450. ISSN: 0020-0255. DOI: [10.1016/j.ins.2020.01.034](https://doi.org/10.1016%2Fj.ins.2020.01.034). URL: [http://dx.doi.org/10.1016/j.ins.2020.01.034](http://dx.doi.org/10.1016/j.ins.2020.01.034).

<a name=bib-Cabrera_2020></a>[[4]](#cite-Cabrera_2020) I. P. Cabrera, P. Cordero, E. Muñoz‐Velasco, et al. “Relational Galois connections between transitive fuzzy digraphs”. In: _Mathematical Methods in the Applied Sciences_ 43.9 (Feb. 2020), p. 5673–5680. ISSN: 1099-1476. DOI: [10.1002/mma.6302](https://doi.org/10.1002%2Fmma.6302). URL: [http://dx.doi.org/10.1002/mma.6302](http://dx.doi.org/10.1002/mma.6302).

<a name=bib-Cabrera_2016></a>[[5]](#cite-Cabrera_2016) I. P. Cabrera, P. Cordero, and M. Ojeda-Aciego. “On fuzzy relations, adjunctions, and functional fuzzy relations”. In: _2016 IEEE Symposium Series on Computational Intelligence (SSCI)_. IEEE, Dec. 2016, p. 1–7. DOI: [10.1109/ssci.2016.7850149](https://doi.org/10.1109%2Fssci.2016.7850149). URL: [http://dx.doi.org/10.1109/ssci.2016.7850149](http://dx.doi.org/10.1109/ssci.2016.7850149).

<a name=bib-Cabrera_20172></a>[[6]](#cite-Cabrera_20172) I. P. Cabrera, P. Cordero, and M. Ojeda-Aciego. “Relational fuzzy Galois connections”. In: _2017 Joint 17th World Congress of International Fuzzy Systems Association and 9th International Conference on Soft Computing and Intelligent Systems (IFSA-SCIS)_. IEEE, Jun. 2017, p. 1–6. DOI: [10.1109/ifsa-scis.2017.8023288](https://doi.org/10.1109%2Fifsa-scis.2017.8023288). URL: [http://dx.doi.org/10.1109/ifsa-scis.2017.8023288](http://dx.doi.org/10.1109/ifsa-scis.2017.8023288).

<a name=bib-Cabrera_2017></a>[[7]](#cite-Cabrera_2017) I. P. Cabrera, P. Cordero, and M. Ojeda-Aciego. “Towards relational fuzzy adjunctions”. In: _2017 IEEE International Conference on Fuzzy Systems (FUZZ-IEEE)_. IEEE, Jul. 2017, p. 1–5. DOI: [10.1109/fuzz-ieee.2017.8015677](https://doi.org/10.1109%2Ffuzz-ieee.2017.8015677). URL: [http://dx.doi.org/10.1109/fuzz-ieee.2017.8015677](http://dx.doi.org/10.1109/fuzz-ieee.2017.8015677).

<a name=bib-Cabrera_20173></a>[[8]](#cite-Cabrera_20173) I. Cabrera, P. Cordero, F. García-Pardo, et al. “On the construction of adjunctions between a fuzzy preposet and an unstructured set”. In: _Fuzzy Sets and Systems_ 320 (Aug. 2017), p. 81–92. ISSN: 0165-0114. DOI: [10.1016/j.fss.2016.09.013](https://doi.org/10.1016%2Fj.fss.2016.09.013). URL: [http://dx.doi.org/10.1016/j.fss.2016.09.013](http://dx.doi.org/10.1016/j.fss.2016.09.013).

<a name=bib-Cabrera_20171></a>[[9]](#cite-Cabrera_20171) I. Cabrera, P. Cordero, and M. Ojeda-Aciego. “Galois connections in computational intelligence: A short survey”. In: _2017 IEEE Symposium Series on Computational Intelligence (SSCI)_. IEEE, Nov. 2017, p. 1–7. DOI: [10.1109/ssci.2017.8285310](https://doi.org/10.1109%2Fssci.2017.8285310). URL: [http://dx.doi.org/10.1109/ssci.2017.8285310](http://dx.doi.org/10.1109/ssci.2017.8285310).

<a name=bib-Dzik_2014></a>[[10]](#cite-Dzik_2014) W. Dzik, J. Jarvinen, and M. Kondo. “Characterizing intermediate tense logics in terms of Galois connections”. In: _Logic Journal of IGPL_ 22.6 (Jul. 2014), p. 992–1018. ISSN: 1368-9894. DOI: [10.1093/jigpal/jzu024](https://doi.org/10.1093%2Fjigpal%2Fjzu024). URL: [http://dx.doi.org/10.1093/jigpal/jzu024](http://dx.doi.org/10.1093/jigpal/jzu024).

<a name=bib-Ferr__2020></a>[[11]](#cite-Ferr__2020) S. Ferré, M. Huchard, M. Kaytoue, et al. “Formal Concept Analysis: From Knowledge Discovery to Knowledge Processing”. In: _A Guided Tour of Artificial Intelligence Research_. Springer International Publishing, 2020, p. 411–445. ISBN: 9783030061678. DOI: [10.1007/978-3-030-06167-8_13](https://doi.org/10.1007%2F978-3-030-06167-8_13). URL: [http://dx.doi.org/10.1007/978-3-030-06167-8_13](http://dx.doi.org/10.1007/978-3-030-06167-8_13).

<a name=bib-Garc_a_Pardo_20143></a>[[12]](#cite-Garc_a_Pardo_20143) F. García-Pardo, I. P. Cabrera, P. Cordero, et al. “On Adjunctions between Fuzzy Preordered Sets: Necessary Conditions”. In: _Rough Sets and Current Trends in Soft Computing_. Springer International Publishing, 2014, p. 211–221. ISBN: 9783319086446. DOI: [10.1007/978-3-319-08644-6_22](https://doi.org/10.1007%2F978-3-319-08644-6_22). URL: [http://dx.doi.org/10.1007/978-3-319-08644-6_22](http://dx.doi.org/10.1007/978-3-319-08644-6_22).

<a name=bib-Garc_a_Pardo_2015></a>[[13]](#cite-Garc_a_Pardo_2015) F. García-Pardo, I. P. Cabrera, P. Cordero, et al. “On Closure Systems and Adjunctions Between Fuzzy Preordered Sets”. In: _Formal Concept Analysis_. Springer International Publishing, 2015, p. 114–127. ISBN: 9783319195452. DOI: [10.1007/978-3-319-19545-2_7](https://doi.org/10.1007%2F978-3-319-19545-2_7). URL: [http://dx.doi.org/10.1007/978-3-319-19545-2_7](http://dx.doi.org/10.1007/978-3-319-19545-2_7).

<a name=bib-Garc_a_Pardo_20141></a>[[14]](#cite-Garc_a_Pardo_20141) F. García-Pardo, I. P. Cabrera, P. Cordero, et al. “On the Existence of Isotone Galois Connections between Preorders”. In: _Formal Concept Analysis_. Springer International Publishing, 2014, p. 67–79. ISBN: 9783319072487. DOI: [10.1007/978-3-319-07248-7_6](https://doi.org/10.1007%2F978-3-319-07248-7_6). URL: [http://dx.doi.org/10.1007/978-3-319-07248-7_6](http://dx.doi.org/10.1007/978-3-319-07248-7_6).

<a name=bib-Garc_a_Pardo_20142></a>[[15]](#cite-Garc_a_Pardo_20142) F. García-Pardo, I. P. Cabrera, P. Cordero, et al. “Generating Isotone Galois Connections on an Unstructured Codomain”. In: _Information Processing and Management of Uncertainty in Knowledge-Based Systems_. Springer International Publishing, 2014, p. 91–99. ISBN: 9783319088525. DOI: [10.1007/978-3-319-08852-5_10](https://doi.org/10.1007%2F978-3-319-08852-5_10). URL: [http://dx.doi.org/10.1007/978-3-319-08852-5_10](http://dx.doi.org/10.1007/978-3-319-08852-5_10).

<a name=bib-Garc_a_Pardo_2014></a>[[16]](#cite-Garc_a_Pardo_2014) F. García-Pardo, I. Cabrera, P. Cordero, et al. “On the definition of suitable orderings to generate adjunctions over an unstructured codomain”. In: _Information Sciences_ 286 (Dec. 2014), p. 173–187. ISSN: 0020-0255. DOI: [10.1016/j.ins.2014.07.006](https://doi.org/10.1016%2Fj.ins.2014.07.006). URL: [http://dx.doi.org/10.1016/j.ins.2014.07.006](http://dx.doi.org/10.1016/j.ins.2014.07.006).

<a name=bib-Horv_th_2020></a>[[17]](#cite-Horv_th_2020) E. K. Horváth, S. Radeleczki, B. Šešelja, et al. “Cuts of poset-valued functions in the framework of residuated maps”. In: _Fuzzy Sets and Systems_ 397 (Oct. 2020), p. 28–40. ISSN: 0165-0114. DOI: [10.1016/j.fss.2020.01.003](https://doi.org/10.1016%2Fj.fss.2020.01.003). URL: [http://dx.doi.org/10.1016/j.fss.2020.01.003](http://dx.doi.org/10.1016/j.fss.2020.01.003).

<a name=bib-Madrid_2020></a>[[18]](#cite-Madrid_2020) N. Madrid and M. Ojeda-Aciego. “On Contradiction and Inclusion Using Functional Degrees”. In: _International Journal of Computational Intelligence Systems_ 13.1 (2020), p. 464. ISSN: 1875-6883. DOI: [10.2991/ijcis.d.200409.001](https://doi.org/10.2991%2Fijcis.d.200409.001). URL: [http://dx.doi.org/10.2991/ijcis.d.200409.001](http://dx.doi.org/10.2991/ijcis.d.200409.001).

<a name=bib-Ojeda_Hern_ndez_2023></a>[[19]](#cite-Ojeda_Hern_ndez_2023) M. Ojeda-Hernández, I. P. Cabrera, P. Cordero, et al. “Fuzzy closure structures as formal concepts”. In: _Fuzzy Sets and Systems_ 463 (Jul. 2023), p. 108458. ISSN: 0165-0114. DOI: [10.1016/j.fss.2022.12.014](https://doi.org/10.1016%2Fj.fss.2022.12.014). URL: [http://dx.doi.org/10.1016/j.fss.2022.12.014](http://dx.doi.org/10.1016/j.fss.2022.12.014).

<a name=bib-Rasouli_2020></a>[[20]](#cite-Rasouli_2020) S. Rasouli. “Quasicomplemented residuated lattices”. In: _Soft Computing_ 24.9 (Feb. 2020), p. 6591–6602. ISSN: 1433-7479. DOI: [10.1007/s00500-020-04778-y](https://doi.org/10.1007%2Fs00500-020-04778-y). URL: [http://dx.doi.org/10.1007/s00500-020-04778-y](http://dx.doi.org/10.1007/s00500-020-04778-y).

<a name=bib-Rasouli_2022></a>[[21]](#cite-Rasouli_2022) S. Rasouli and A. Dehghani. “Mp- and purified residuated lattices”. In: _Soft Computing_ 27.1 (Oct. 2022), p. 131–148. ISSN: 1433-7479. DOI: [10.1007/s00500-022-07583-x](https://doi.org/10.1007%2Fs00500-022-07583-x). URL: [http://dx.doi.org/10.1007/s00500-022-07583-x](http://dx.doi.org/10.1007/s00500-022-07583-x).

<a name=bib-Rasouli_2021></a>[[22]](#cite-Rasouli_2021) S. Rasouli and A. Dehghani. “The hull-kernel topology on prime filters in residuated lattices”. In: _Soft Computing_ 25.16 (Jul. 2021), p. 10519–10541. ISSN: 1433-7479. DOI: [10.1007/s00500-021-05985-x](https://doi.org/10.1007%2Fs00500-021-05985-x). URL: [http://dx.doi.org/10.1007/s00500-021-05985-x](http://dx.doi.org/10.1007/s00500-021-05985-x).

<a name=bib-httpsdoiorg1048550arxiv181211510></a>[[23]](#cite-httpsdoiorg1048550arxiv181211510) S. Rasouli and A. Dehghani. _The hull-kernel topology on residuated lattices_. 2018. DOI: [10.48550/ARXIV.1812.11510](https://doi.org/10.48550%2FARXIV.1812.11510). URL: [https://arxiv.org/abs/1812.11510](https://arxiv.org/abs/1812.11510).

<a name=bib-_e_elja_2020></a>[[24]](#cite-_e_elja_2020) B. Šešelja and A. Tepavčević. “Kernels of Residuated Maps as Complete Congruences in Lattices”. In: _International Journal of Computational Intelligence Systems_ 13.1 (2020), p. 966. ISSN: 1875-6883. DOI: [10.2991/ijcis.d.200714.001](https://doi.org/10.2991%2Fijcis.d.200714.001). URL: [http://dx.doi.org/10.2991/ijcis.d.200714.001](http://dx.doi.org/10.2991/ijcis.d.200714.001).

<a name=bib-Valverde_Albacete_2018></a>[[25]](#cite-Valverde_Albacete_2018) F. J. Valverde-Albacete, C. Peláez-Moreno, I. P. Cabrera, et al. “Formal Independence Analysis”. In: _Information Processing and Management of Uncertainty in Knowledge-Based Systems. Theory and Foundations_. Springer International Publishing, 2018, p. 596–608. ISBN: 9783319914732. DOI: [10.1007/978-3-319-91473-2_51](https://doi.org/10.1007%2F978-3-319-91473-2_51). URL: [http://dx.doi.org/10.1007/978-3-319-91473-2_51](http://dx.doi.org/10.1007/978-3-319-91473-2_51).

