---
author: Enrique Mérida Casermeiro, Domingo López-Rodríguez
Status: Published
date: '2005-04-01'
slug: 2005-maeb2
title: Memoria auto-asociativa y clasificación con redes neuronales recurrentes
categories: Neural networks
header_image: ~
details: <em>Congreso Español sobre Metaheurísticas, Algoritmos Evolutivos y Bioinspirados</em>
  2005
doi: ''
link: 2005-maeb2/paper.pdf
project: ~
keywords: Neural networks, Associative memory
---


# Abstract


El objetivo de este trabajo es presentar un nuevo modelo general de aprendizaje hebbiano para redes recurrentes discretas y dar una interpretación a la función de energía resultante cuando el número de patrones básicos sobrepasa la capacidad de la red. En este sentido, el modelo aquí presentado sostiene que aunque la capacidad de la red debe ser interpretada como una limitación de la red para aprender patrones individuales, cuando se sobrepasa dicha capacidad, la red tiende a identificar patrones similares formando grupos en torno a representantes típicos. Así, lo que en realidad se produce es el aprendizaje no supervisado de clases de patrones. De esta forma mediante la generalización del aprendizaje hebbiano aquí mostrado, pueden aprenderse grupos de patrones (conceptos) en lugar de patrones individuales y esto ocurre generalmente cuando se sobrepasa la capacidad de la red. Nuestro modelo presenta dos grandes ventajas sobre los algoritmos de clasificación típicos, no es necesario el ajuste de ningún parámetro, e incluso el numero de clases de patrones se aprende automáticamente, de forma que no hace falta ningún tipo de conocimiento a priori sobre el número de clases.







# Citation
Please, cite this work as:


<a name=bib-lopez2005memoria></a>[[ML05]](#cite-lopez2005memoria) E. Mérida-Casermeiro and D. López-Rodríguez. “Memoria auto-asociativa y clasificación con redes neuronales recurrentes”. In: _IV Congreso Español sobre Meraheurísticas, Algoritmos Evolutivos y Bioinspirados_. CEDI. 2005, pp. 339-346.

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@inproceedings{lopez2005memoria,<br>&nbsp;&nbsp;&nbsp;&nbsp;  title={Memoria auto-asociativa y clasificación con redes neuronales recurrentes},<br>&nbsp;&nbsp;&nbsp;&nbsp;  author={Mérida-Casermeiro, Enrique and López-Rodríguez, Domingo},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle={IV Congreso Español sobre Meraheurísticas, Algoritmos Evolutivos y Bioinspirados},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages={339--346},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year={2005},<br>&nbsp;&nbsp;&nbsp;&nbsp;  organization={CEDI}<br>}

:::


