---
title: Equivalence Relations on Fuzzy Subgroups
author:
- <a href='/people/staff/cbejines/' style='color:rgb(100,0,50);'>Carlos Bejines</a>
- María Jesús Chasco
- Jorge Elorza
- Susana Montes
date: '2018'
categories: uncategorised
slug: 2018/EqReFuSu
details: Advances in Artificial Intelligence - 18th Conference of the Spanish Association
  for Artificial Intelligence, {CAEPIA} 2018, Granada, Spain, October 23-26, 2018,
  Proceedings , Lecture Notes in Computer Science vol. 11160, pages 143--153.
doi: 10.1007/978-3-030-00374-6_14
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Bejines2018></a>[[Bej+18]](#cite-Bejines2018) C. Bejines, M. Chasco, J. Elorza, et al. “Equivalence Relations on Fuzzy Subgroups”. In: _Advances in Artificial Intelligence - 18th Conference of the Spanish Association for Artificial Intelligence, CAEPIA 2018, Granada, Spain, October 23-26, 2018, Proceedings_. Ed. by F. Herrera, S. Damas, R. Montes, S. Alonso, O. Cordón, A. González and A. Troncoso. Vol. 11160. Lecture Notes in Computer Science. Springer, 2018, pp. 143-153. DOI: [10.1007/978-3-030-00374-6\_14](https://doi.org/10.1007%2F978-3-030-00374-6%5C_14). URL: [https://doi.org/10.1007/978-3-030-00374-6\_14](https://doi.org/10.1007/978-3-030-00374-6\_14).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Bejines2018,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Carlos Bejines and Mar\'\ia Jes{\a'u}s Chasco and Jorge Elorza and Susana Montes},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Advances in Artificial Intelligence - 18th Conference of the Spanish Association for Artificial Intelligence, {CAEPIA} 2018, Granada, Spain, October 23-26, 2018, Proceedings},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Equivalence Relations on Fuzzy Subgroups},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2018},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Francisco Herrera and Sergio Damas and Rosana Montes and Sergio Alonso and Oscar Cord{\a'o}n and Antonio Gonz{\a'a}lez and Alicia Troncoso},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {143--153},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {11160},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/caepia/BejinesCEM18.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/978-3-030-00374-6\_14},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Tue, 14 May 2019 10:00:50 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/978-3-030-00374-6\_14},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/978-3-030-00374-6_14" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/978-3-030-00374-6_14" class="plumx-details" data-site="plum" data-hide-when-empty="true">Equivalence Relations on Fuzzy Subgroups</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1007/978-3-030-00374-6_14"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Bejines_2023></a>[[1]](#cite-Bejines_2023) C. Bejines. “Aggregation of fuzzy vector spaces”. In: _Kybernetika_ (Dec. 2023), p. 752–767. ISSN: 1805-949X. DOI: [10.14736/kyb-2023-5-0752](https://doi.org/10.14736%2Fkyb-2023-5-0752). URL: [http://dx.doi.org/10.14736/kyb-2023-5-0752](http://dx.doi.org/10.14736/kyb-2023-5-0752).

<a name=bib-Bejines_2021></a>[[2]](#cite-Bejines_2021) C. Bejines, S. Ardanza-Trevijano, and J. Elorza. “On Self-Aggregations of Min-Subgroups”. In: _Axioms_ 10.3 (Aug. 2021), p. 201. ISSN: 2075-1680. DOI: [10.3390/axioms10030201](https://doi.org/10.3390%2Faxioms10030201). URL: [http://dx.doi.org/10.3390/axioms10030201](http://dx.doi.org/10.3390/axioms10030201).

<a name=bib-Bejines_20211></a>[[3]](#cite-Bejines_20211) C. Bejines, M. Chasco, and J. Elorza. “Aggregation of fuzzy subgroups”. In: _Fuzzy Sets and Systems_ 418 (Aug. 2021), p. 170–184. ISSN: 0165-0114. DOI: [10.1016/j.fss.2020.05.017](https://doi.org/10.1016%2Fj.fss.2020.05.017). URL: [http://dx.doi.org/10.1016/j.fss.2020.05.017](http://dx.doi.org/10.1016/j.fss.2020.05.017).

