---
title: 'Fuzzy closure systems: Motivation, definition and properties'
type: journals
author:
- <a href='/people/staff/manuojeda/' style='color:rgb(100,0,50);'>Manuel Ojeda Hernández</a>
- <a href='/people/staff/ipcabrera/' style='color:rgb(100,0,50);'>Inma P. Cabrera</a>
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
date: '2022-01-01'
categories:
- Formal concept analysis
- Fuzzy logic
- Fuzzy sets
- Uncertainty
doi: 10.1016/j.ijar.2022.06.004
slug: 2022/FuClDePr
keywords: ''
project: 2019-flair
details: International Journal of Approximate Reasoning vol. 148 , pages 151 – 161.
listing:
- id: funding
  contents: funding.yml
  type: default
  sort: date desc
---




# Abstract

The aim of this paper is to extend closure systems from being crisp sets with certain fuzzy properties to proper fuzzy sets. The presentation of the paper shows a thorough discussion on the different alternatives that could be taken to define the desired fuzzy closure systems. These plausible alternatives are discarded if they are proven impossible to be in a bijective correspondence with closure operators. Finally, a definition of fuzzy closure system is established and a one-to-one relation with closure operators is proved.


# Funding
::: {.callout-note appearance='minimal' collapse=false}
## Projects funding this work

:::{#funding}
:::
:::








# Citation
Please, cite this work as:


<a name=bib-Ojeda-Hernandez2022151></a>[[Oje+22]](#cite-Ojeda-Hernandez2022151) M. Ojeda-Hern\’ndez, I. P. Cabrera, P. Cordero, et al. “Fuzzy closure systems: Motivation, definition and properties”. In: _International Journal of Approximate Reasoning_ 148 (2022). Cited by: 4; All Open Access, Green Open Access, Hybrid Gold Open Access, p. 151 – 161. DOI: [10.1016/j.ijar.2022.06.004](https://doi.org/10.1016%2Fj.ijar.2022.06.004). URL: [https://www.scopus.com/inward/record.uri?eid=2-s2.0-85132519163&doi=10.1016

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@ARTICLE{Ojeda-Hernandez2022151,<br>&nbsp;&nbsp;&nbsp;&nbsp;	author = {Ojeda-Hern\’ndez, Manuel and Cabrera, Inma P. and Cordero, Pablo and Muñoz-Velasco, Emilio},<br>&nbsp;&nbsp;&nbsp;&nbsp;	title = {Fuzzy closure systems: Motivation, definition and properties},<br>&nbsp;&nbsp;&nbsp;&nbsp;	year = {2022},<br>&nbsp;&nbsp;&nbsp;&nbsp;	journal = {International Journal of Approximate Reasoning},<br>&nbsp;&nbsp;&nbsp;&nbsp;	volume = {148},<br>&nbsp;&nbsp;&nbsp;&nbsp;	pages = {151 – 161},<br>&nbsp;&nbsp;&nbsp;&nbsp;	doi = {10.1016/j.ijar.2022.06.004},<br>&nbsp;&nbsp;&nbsp;&nbsp;	url = {https://www.scopus.com/inward/record.uri?eid=2-s2.0-85132519163&doi=10.1016%2fj.ijar.2022.06.004&partnerID=40&md5=d1a971a21900a5dc0f7c65e4de834098},<br>&nbsp;&nbsp;&nbsp;&nbsp;	type = {Article},<br>&nbsp;&nbsp;&nbsp;&nbsp;	publication_stage = {Final},<br>&nbsp;&nbsp;&nbsp;&nbsp;	source = {Scopus},<br>&nbsp;&nbsp;&nbsp;&nbsp;	note = {Cited by: 4; All Open Access, Green Open Access, Hybrid Gold Open Access}<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1016/j.ijar.2022.06.004" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1016/j.ijar.2022.06.004" class="plumx-details" data-site="plum" data-hide-when-empty="true">Fuzzy closure systems: Motivation, definition and properties</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1016/j.ijar.2022.06.004"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Bejines_2024></a>[[1]](#cite-Bejines_2024) C. Bejines, M. Ojeda-Hernández, and D. López-Rodríguez. “Analysis of Fuzzy Vector Spaces as an Algebraic Framework for Flag Codes”. In: _Mathematics_ 12.3 (Feb. 2024), p. 498. ISSN: 2227-7390. DOI: [10.3390/math12030498](https://doi.org/10.3390%2Fmath12030498). URL: [http://dx.doi.org/10.3390/math12030498](http://dx.doi.org/10.3390/math12030498).

<a name=bib-Ojeda_Hern_ndez_20232></a>[[2]](#cite-Ojeda_Hern_ndez_20232) M. Ojeda-Hernández, I. P. Cabrera, P. Cordero, et al. “Fuzzy closure structures as formal concepts”. In: _Fuzzy Sets and Systems_ 463 (Jul. 2023), p. 108458. ISSN: 0165-0114. DOI: [10.1016/j.fss.2022.12.014](https://doi.org/10.1016%2Fj.fss.2022.12.014). URL: [http://dx.doi.org/10.1016/j.fss.2022.12.014](http://dx.doi.org/10.1016/j.fss.2022.12.014).

<a name=bib-Ojeda_Hern_ndez_2023></a>[[3]](#cite-Ojeda_Hern_ndez_2023) M. Ojeda-Hernández, I. P. Cabrera, P. Cordero, et al. “Fuzzy closure structures as formal concepts II”. In: _Fuzzy Sets and Systems_ 473 (Dec. 2023), p. 108734. ISSN: 0165-0114. DOI: [10.1016/j.fss.2023.108734](https://doi.org/10.1016%2Fj.fss.2023.108734). URL: [http://dx.doi.org/10.1016/j.fss.2023.108734](http://dx.doi.org/10.1016/j.fss.2023.108734).

<a name=bib-Ojeda_Hern_ndez_20231></a>[[4]](#cite-Ojeda_Hern_ndez_20231) M. Ojeda-Hernández, I. P. Cabrera, P. Cordero, et al. “On the Commutative Diagrams Among Galois Connections Involved in Closure Structures”. In: _Formal Concept Analysis_. Springer Nature Switzerland, 2023, p. 49–63. ISBN: 9783031359491. DOI: [10.1007/978-3-031-35949-1_4](https://doi.org/10.1007%2F978-3-031-35949-1_4). URL: [http://dx.doi.org/10.1007/978-3-031-35949-1_4](http://dx.doi.org/10.1007/978-3-031-35949-1_4).


