---
title: On the Definition of Fuzzy Relational Galois Connections Between Fuzzy Transitive
  Digraphs
author:
- <a href='/people/staff/ipcabrera/' style='color:rgb(100,0,50);'>Inma P. Cabrera</a>
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
- Bernard De Baets
date: '2022'
categories: uncategorised
slug: 2022/DeFuReGaCoFuTrDi
details: Information Processing and Management of Uncertainty in Knowledge-Based Systems
  - 19th International Conference, {IPMU} 2022, Milan, Italy, July 11-15, 2022, Proceedings,
  Part {I} , Communications in Computer and Information Science vol. 1601, pages 100--106.
doi: 10.1007/978-3-031-08971-8_9
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Cabrera2022></a>[[Cab+22]](#cite-Cabrera2022) I. P. Cabrera, P. Cordero, E. Mu~noz-Velasco, et al. “On the Definition of Fuzzy Relational Galois Connections Between Fuzzy Transitive Digraphs”. In: _Information Processing and Management of Uncertainty in Knowledge-Based Systems - 19th International Conference, IPMU 2022, Milan, Italy, July 11-15, 2022, Proceedings, Part I_. Ed. by D. Ciucci, I. Couso, J. Medina, D. Slezak, D. Petturiti, B. Bouchon-Meunier and R. R. Yager. Vol. 1601. Communications in Computer and Information Science. Springer, 2022, pp. 100-106. DOI: [10.1007/978-3-031-08971-8\_9](https://doi.org/10.1007%2F978-3-031-08971-8%5C_9). URL: [https://doi.org/10.1007/978-3-031-08971-8\_9](https://doi.org/10.1007/978-3-031-08971-8\_9).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Cabrera2022,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Inma P. Cabrera and Pablo Cordero and Emilio Mu~noz-Velasco and Manuel Ojeda-Aciego and Bernard De Baets},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Information Processing and Management of Uncertainty in Knowledge-Based Systems - 19th International Conference, {IPMU} 2022, Milan, Italy, July 11-15, 2022, Proceedings, Part {I}},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {On the Definition of Fuzzy Relational Galois Connections Between Fuzzy Transitive Digraphs},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2022},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Davide Ciucci and In{\a'e}s Couso and Jes{\a'u}s Medina and Dominik Slezak and Davide Petturiti and Bernadette Bouchon-Meunier and Ronald R. Yager},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {100--106},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Communications in Computer and Information Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {1601},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/ipmu/CabreraCMOB22.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/978-3-031-08971-8\_9},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Thu, 25 Aug 2022 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/978-3-031-08971-8\_9},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/978-3-031-08971-8_9" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/978-3-031-08971-8_9" class="plumx-details" data-site="plum" data-hide-when-empty="true">On the Definition of Fuzzy Relational Galois Connections Between Fuzzy Transitive Digraphs</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1007/978-3-031-08971-8_9"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```





