---
title: Formation of the D-basis from implicational systems using Simplification logic
author:
- Estrella Rodríguez Lorenzo
- Kira V. Adaricheva
- <a href='/people/staff/pcordero/' style='color:rgb(100,0,50);'>Pablo Cordero</a>
- <a href='/people/staff/enciso/' style='color:rgb(100,0,50);'>Manuel Enciso</a>
- <a href='/people/staff/amora/' style='color:rgb(100,0,50);'>Ángel Mora</a>
date: '2017'
categories: uncategorised
slug: 2017/FoImSyUsSiLo
details: Int. J. Gen. Syst. vol. 46 (5), pages 547--568.
doi: 10.1080/03081079.2017.1349632
---



# Abstract


Sets of implications defining closure systems are used as a standard way to represent knowledge, and the search of implicational systems satisfying some criteria constitutes one of the most active topics in the study of closure systems and their applications. Here, we focus on the generation of the D-basis, known to be an ordered direct basis, allowing a very efficient attribute closure computation. We operate with the aggregated D-basis and provide an algorithm to get it from an arbitrary implicational set. The method has been designed on the interrelation between minimal covers and minimal generators, and it is inspired by the inference system of the Simplification Logic. Moreover, we develop an experiment to show the better performance of the new method compared to the earlier version of the algorithm.








# Citation
Please, cite this work as:


<a name=bib-Lorenzo2017></a>[[Rod+17]](#cite-Lorenzo2017) E. Rodr\'\iguezLorenzo, K. V. Adaricheva, P. Cordero, et al. “Formation of the D-basis from implicational systems using Simplification logic”. In: _Int. J. Gen. Syst._ 46.5 (2017), pp. 547-568. DOI: [10.1080/03081079.2017.1349632](https://doi.org/10.1080%2F03081079.2017.1349632). URL: [https://doi.org/10.1080/03081079.2017.1349632](https://doi.org/10.1080/03081079.2017.1349632).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@Article{Lorenzo2017,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Estrella Rodr\'\iguez Lorenzo and Kira V. Adaricheva and Pablo Cordero and Manuel Enciso and {\a'A}ngel Mora},<br>&nbsp;&nbsp;&nbsp;&nbsp;  journal = {Int. J. Gen. Syst.},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {Formation of the D-basis from implicational systems using Simplification logic},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2017},<br>&nbsp;&nbsp;&nbsp;&nbsp;  number = {5},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {547--568},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {46},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/journals/ijgs/LorenzoACEM17.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1080/03081079.2017.1349632},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Fri, 23 Sep 2022 01:00:00 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1080/03081079.2017.1349632},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1080/03081079.2017.1349632" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1080/03081079.2017.1349632" class="plumx-details" data-site="plum" data-hide-when-empty="true">Formation of the D-basis from implicational systems using Simplification logic</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1080/03081079.2017.1349632"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Adaricheva_2019></a>[[1]](#cite-Adaricheva_2019) K. Adaricheva and T. Ninesling. “Direct and Binary Direct Bases for One-Set Updates of a Closure System”. In: _Formal Concept Analysis_. Springer International Publishing, 2019, p. 55–72. ISBN: 9783030214623. DOI: [10.1007/978-3-030-21462-3_5](https://doi.org/10.1007%2F978-3-030-21462-3_5). URL: [http://dx.doi.org/10.1007/978-3-030-21462-3_5](http://dx.doi.org/10.1007/978-3-030-21462-3_5).

<a name=bib-Arag_n_2022></a>[[2]](#cite-Arag_n_2022) R. G. Aragón, M. Eugenia Cornejo, J. Medina, et al. “A Formal Method for Driver Identification”. In: _Computational Intelligence and Mathematics for Tackling Complex Problems 4_. Springer International Publishing, Sep. 2022, p. 153–159. ISBN: 9783031077074. DOI: [10.1007/978-3-031-07707-4_19](https://doi.org/10.1007%2F978-3-031-07707-4_19). URL: [http://dx.doi.org/10.1007/978-3-031-07707-4_19](http://dx.doi.org/10.1007/978-3-031-07707-4_19).

<a name=bib-Cordero_2022></a>[[3]](#cite-Cordero_2022) P. Cordero, M. Enciso, A. Mora, et al. “Interactive Search by Using Minimal Generators”. In: _Computational Intelligence and Mathematics for Tackling Complex Problems 2_. Springer International Publishing, 2022, p. 147–153. ISBN: 9783030888176. DOI: [10.1007/978-3-030-88817-6_17](https://doi.org/10.1007%2F978-3-030-88817-6_17). URL: [http://dx.doi.org/10.1007/978-3-030-88817-6_17](http://dx.doi.org/10.1007/978-3-030-88817-6_17).

<a name=bib-Cordero_2020></a>[[4]](#cite-Cordero_2020) P. Cordero, M. Enciso, Á. Mora, et al. “A Formal Concept Analysis Approach to Cooperative Conversational Recommendation”. In: _International Journal of Computational Intelligence Systems_ 13.1 (2020), p. 1243. ISSN: 1875-6883. DOI: [10.2991/ijcis.d.200806.001](https://doi.org/10.2991%2Fijcis.d.200806.001). URL: [http://dx.doi.org/10.2991/ijcis.d.200806.001](http://dx.doi.org/10.2991/ijcis.d.200806.001).

<a name=bib-L_pez_Rodr_guez_2021></a>[[5]](#cite-L_pez_Rodr_guez_2021) D. López-Rodríguez, E. Muñoz-Velasco, and M. Ojeda-Aciego. “Formal Methods in FCA and Big Data”. In: _Complex Data Analytics with Formal Concept Analysis_. Springer International Publishing, Dec. 2021, p. 201–224. ISBN: 9783030932787. DOI: [10.1007/978-3-030-93278-7_9](https://doi.org/10.1007%2F978-3-030-93278-7_9). URL: [http://dx.doi.org/10.1007/978-3-030-93278-7_9](http://dx.doi.org/10.1007/978-3-030-93278-7_9).

<a name=bib-Pattison_2021></a>[[6]](#cite-Pattison_2021) T. Pattison, M. Enciso, Á. Mora, et al. “Scalable Visual Analytics in FCA”. In: _Complex Data Analytics with Formal Concept Analysis_. Springer International Publishing, Dec. 2021, p. 167–200. ISBN: 9783030932787. DOI: [10.1007/978-3-030-93278-7_8](https://doi.org/10.1007%2F978-3-030-93278-7_8). URL: [http://dx.doi.org/10.1007/978-3-030-93278-7_8](http://dx.doi.org/10.1007/978-3-030-93278-7_8).

