---
title: A Logic for Order of Magnitude Reasoning with Negligibility, Non-closeness
  and Distance
author:
- Alfredo Burrieza
- <a href='/people/staff/ejmunoz/' style='color:rgb(100,0,50);'>Emilio Muñoz Velasco</a>
- <a href='/people/staff/aciego/' style='color:rgb(100,0,50);'>Manuel Ojeda-Aciego</a>
date: '2007'
categories: uncategorised
slug: 2007/LoOrMaReDi
details: Current Topics in Artificial Intelligence, 12th Conference of the Spanish
  Association for Artificial Intelligence, {CAEPIA} 2007, Salamanca, Spain, November
  12-16, 2007. Selected Papers , Lecture Notes in Computer Science vol. 4788, pages
  210--219.
doi: 10.1007/978-3-540-75271-4_22
---



# Abstract










# Citation
Please, cite this work as:


<a name=bib-Burrieza2007></a>[[BMO07]](#cite-Burrieza2007) A. Burrieza, E. Mu~noz-Velasco, and M. Ojeda-Aciego. “A Logic for Order of Magnitude Reasoning with Negligibility, Non-closeness and Distance”. In: _Current Topics in Artificial Intelligence, 12th Conference of the Spanish Association for Artificial Intelligence, CAEPIA 2007, Salamanca, Spain, November 12-16, 2007. Selected Papers_. Ed. by D. Borrajo, L. A. Castillo and J. M. Corchado. Vol. 4788. Lecture Notes in Computer Science. Springer, 2007, pp. 210-219. DOI: [10.1007/978-3-540-75271-4\_22](https://doi.org/10.1007%2F978-3-540-75271-4%5C_22). URL: [https://doi.org/10.1007/978-3-540-75271-4\_22](https://doi.org/10.1007/978-3-540-75271-4\_22).

::: {.callout-note appearance="minimal" collapse=true}

## BibTeX

@InProceedings{Burrieza2007,<br>&nbsp;&nbsp;&nbsp;&nbsp;  author = {Alfredo Burrieza and Emilio Mu~noz-Velasco and Manuel Ojeda-Aciego},<br>&nbsp;&nbsp;&nbsp;&nbsp;  booktitle = {Current Topics in Artificial Intelligence, 12th Conference of the Spanish Association for Artificial Intelligence, {CAEPIA} 2007, Salamanca, Spain, November 12-16, 2007. Selected Papers},<br>&nbsp;&nbsp;&nbsp;&nbsp;  title = {A Logic for Order of Magnitude Reasoning with Negligibility, Non-closeness and Distance},<br>&nbsp;&nbsp;&nbsp;&nbsp;  year = {2007},<br>&nbsp;&nbsp;&nbsp;&nbsp;  editor = {Daniel Borrajo and Luis A. Castillo and Juan M. Corchado},<br>&nbsp;&nbsp;&nbsp;&nbsp;  pages = {210--219},<br>&nbsp;&nbsp;&nbsp;&nbsp;  publisher = {Springer},<br>&nbsp;&nbsp;&nbsp;&nbsp;  series = {Lecture Notes in Computer Science},<br>&nbsp;&nbsp;&nbsp;&nbsp;  volume = {4788},<br>&nbsp;&nbsp;&nbsp;&nbsp;  bibsource = {dblp computer science bibliography, https://dblp.org},<br>&nbsp;&nbsp;&nbsp;&nbsp;  biburl = {https://dblp.org/rec/conf/caepia/BurriezaMO07.bib},<br>&nbsp;&nbsp;&nbsp;&nbsp;  doi = {10.1007/978-3-540-75271-4\_22},<br>&nbsp;&nbsp;&nbsp;&nbsp;  timestamp = {Tue, 14 May 2019 10:00:50 +0200},<br>&nbsp;&nbsp;&nbsp;&nbsp;  url = {https://doi.org/10.1007/978-3-540-75271-4\_22},<br>}

:::



# Bibliometric data


The following data has been extracted from resources such as [OpenAlex](https://openalex.org/), [Dimensions](https://app.dimensions.ai/), [PlumX](https://www.elsevier.com/insights/metrics/plumx) or [Altmetric](https://www.altmetric.com/).

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<span class="__dimensions_badge_embed__" data-doi="10.1007/978-3-540-75271-4_22" data-legend="always"></span></div><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<a href="https://plu.mx/plum/a/?doi=10.1007/978-3-540-75271-4_22" class="plumx-details" data-site="plum" data-hide-when-empty="true">A Logic for Order of Magnitude Reasoning with Negligibility, Non-closeness and Distance</a></div>

<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div data-badge-type="medium-donut" class="altmetric-embed" data-badge-details="right" data-doi="10.1007/978-3-540-75271-4_22"></div></div>


## Cites

The following graph plots the number of cites received by this work from its publication, on a yearly basis.

```{r citing2}
#| echo: false
#| results: asis
#| warning: false
#| message: false
source(here::here('scripts', 'manage_publications.R'))
df <- readRDS('citation_history.rds')
plot_citation_history(df)
```



## Papers citing this work

The following is a non-exhaustive list of papers that cite this work:


<a name=bib-Burrieza_2013></a>[[1]](#cite-Burrieza_2013) A. Burrieza. “Decidability of a Logic for Order of Magnitude Qualitative Reasoning with Comparability and Negligibility Relations”. In: _Advances in Artificial Intelligence_. Springer Berlin Heidelberg, 2013, p. 101–110. ISBN: 9783642406430. DOI: [10.1007/978-3-642-40643-0_11](https://doi.org/10.1007%2F978-3-642-40643-0_11). URL: [http://dx.doi.org/10.1007/978-3-642-40643-0_11](http://dx.doi.org/10.1007/978-3-642-40643-0_11).

<a name=bib-Burrieza_2010></a>[[2]](#cite-Burrieza_2010) A. Burrieza, E. Muñoz-Velasco, and M. Ojeda-Aciego. “Closeness and Distance Relations in Order of Magnitude Qualitative Reasoning via PDL”. In: _Current Topics in Artificial Intelligence_. Springer Berlin Heidelberg, 2010, p. 71–80. ISBN: 9783642142642. DOI: [10.1007/978-3-642-14264-2_8](https://doi.org/10.1007%2F978-3-642-14264-2_8). URL: [http://dx.doi.org/10.1007/978-3-642-14264-2_8](http://dx.doi.org/10.1007/978-3-642-14264-2_8).

<a name=bib-Burrieza_2018></a>[[3]](#cite-Burrieza_2018) A. Burrieza, E. Muñoz-Velasco, and M. Ojeda-Aciego. “Logics for Order-of-Magnitude Qualitative Reasoning: Formalizing Negligibility”. In: _Ewa Orłowska on Relational Methods in Logic and Computer Science_. Springer International Publishing, 2018, p. 203–231. ISBN: 9783319978796. DOI: [10.1007/978-3-319-97879-6_8](https://doi.org/10.1007%2F978-3-319-97879-6_8). URL: [http://dx.doi.org/10.1007/978-3-319-97879-6_8](http://dx.doi.org/10.1007/978-3-319-97879-6_8).

<a name=bib-BURRIEZA_2011></a>[[4]](#cite-BURRIEZA_2011) A. BURRIEZA, E. MUÑOZ-VELASCO, and M. OJEDA-ACIEGO. “A PDL APPROACH FOR QUALITATIVE VELOCITY”. In: _International Journal of Uncertainty, Fuzziness and Knowledge-Based Systems_ 19.01 (Feb. 2011), p. 11–26. ISSN: 1793-6411. DOI: [10.1142/s021848851100685x](https://doi.org/10.1142%2Fs021848851100685x). URL: [http://dx.doi.org/10.1142/s021848851100685x](http://dx.doi.org/10.1142/s021848851100685x).

<a name=bib-Goli_ska_Pilarek_2012></a>[[5]](#cite-Goli_ska_Pilarek_2012) J. Golińska-Pilarek. “On Decidability of a Logic for Order of Magnitude Qualitative Reasoning with Bidirectional Negligibility”. In: _Logics in Artificial Intelligence_. Springer Berlin Heidelberg, 2012, p. 255–266. ISBN: 9783642333538. DOI: [10.1007/978-3-642-33353-8_20](https://doi.org/10.1007%2F978-3-642-33353-8_20). URL: [http://dx.doi.org/10.1007/978-3-642-33353-8_20](http://dx.doi.org/10.1007/978-3-642-33353-8_20).

<a name=bib-Goli_ska_Pilarek_2008></a>[[6]](#cite-Goli_ska_Pilarek_2008) J. Golińska-Pilarek, A. Mora, and E. Muñoz-Velasco. “An ATP of a Relational Proof System for Order of Magnitude Reasoning with Negligibility, Non-closeness and Distance”. In: _PRICAI 2008: Trends in Artificial Intelligence_. Springer Berlin Heidelberg, 2008, p. 128–139. ISBN: 9783540891970. DOI: [10.1007/978-3-540-89197-0_15](https://doi.org/10.1007%2F978-3-540-89197-0_15). URL: [http://dx.doi.org/10.1007/978-3-540-89197-0_15](http://dx.doi.org/10.1007/978-3-540-89197-0_15).

<a name=bib-Golinska_Pilarek_2009></a>[[7]](#cite-Golinska_Pilarek_2009) J. Golinska-Pilarek and E. Munoz-Velasco. “Relational approach for a logic for order of magnitude qualitative reasoning with negligibility, non-closeness and distance”. In: _Logic Journal of IGPL_ 17.4 (Jun. 2009), p. 375–394. ISSN: 1368-9894. DOI: [10.1093/jigpal/jzp016](https://doi.org/10.1093%2Fjigpal%2Fjzp016). URL: [http://dx.doi.org/10.1093/jigpal/jzp016](http://dx.doi.org/10.1093/jigpal/jzp016).

